### ISSUE TITLE
Reduce react lib size

### ISSUE THREAD

**Issue by sokra** [kriasoft/react-starter-kit#1]
The size of the react lib is reduced if you define `process.env.NODE_ENV = "production"`.

See https://github.com/webpack/webpack-with-common-libs/blob/master/gulpfile.js#L25-L30

**Comment by koistya** [comment]
@sokra Good tip. Thanks!

![Image](https://github.com/user-attachments/assets/8cbb60bf-47e0-4d67-b7b6-cac0741428c3)

![Image](https://github.com/user-attachments/assets/cf784d69-0b75-49e4-8478-a4893ae7c28e)

<img width="224" height="60" alt="Image" src="https://github.com/user-attachments/assets/53f33b88-d9ef-4c95-b6a7-5aa5b7523246" />

<img width="128" height="128" alt="Image" src="https://github.com/user-attachments/assets/99b65df2-9d27-4f4a-8df2-f6a2803b2db0" />
