### ISSUE TITLE
Getting rid of relative imports

### ISSUE THREAD

**Issue by idrm** [kriasoft/react-starter-kit#100]
Here are some changes I made to avoid the pesky `import SomeClass from '../../SomeClass';` relative imports (which can be a pain to add/refactor if you have a deeper folder structure):
1. Assuming your project is called __myapp__, add the following property to __resolve__ in __webpack.config.js__: `alias: {myapp: path.resolve(__dirname, "src") + '/'}` and add an import for `path()` near the beginning of the file: `var path = require("path");`
2. Where there is a relative import such as `import SomeActions from '../actions/SomeActions';` replace it with `import SomeActions from 'myapp/actions/SomeActions';`

This change will not affect your existing relative imports, so you can refactor at your leisure.

Perhaps, something like this could be added to a future release of the kit.

**Comment by koistya** [comment]
THere are pros and cons of using relative paths vs shortcuts. It might be a matter of personal preference what approach to use. I personally try to avoid deeply nested folder structures whenever possible and using relative paths is more supported by text editors and IDEs (maybe)..
