### ISSUE TITLE
How to Integrate Material Design Lite (MDL) or react-mdl for react-starter-kit

### ISSUE THREAD

**Issue by hienhuynhtm** [kriasoft/react-starter-kit#1000]
I've problem when integrating MDL/react-mdl to our project. Could you please help me?

**Comment by hienhuynhtm** [comment]
Hi admin,

Could you guys please help me on integrating with MDL? I love this great boilerplate, but my requirement is using MDL, not bootstrap.
It seems that MDL scripts does not work in our client (CSS works well).

Thanks.

**Comment by koistya** [comment]
@hienhuynhtm the easiest way would be referencing MDL's .css and .js files in (src/components/Html.js), then decorate your UI elements with MDL classes as usual and call `upgradeElement()` / `downgradeElement()`. For example:

```jsx
class Button extends React.Component {
  componentDidMount() {
    window.componentHandler.upgradeElement(this.root);
  }
  componentWillUnmount() {
    window.componentHandler.downgradeElements(this.root);
  }
  render() {
    return (
      <button
        ref={node => { this.root = node; }}
        className="mdl-button mdl-js-button"
        {...this.props}
      />;
  }
}
```

Find more info here https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/recipes/how-to-integrate-material-design-lite.md

**Comment by hienhuynhtm** [comment]
Wow, thanks you so much for quick react.

I've referenced MDL's files in Html.js, but no luck.
I'll try your second step (upgradeElement()/downgradeElement()), hope it success.

Thanks again, Koistya.

**Comment by hienhuynhtm** [comment]
I've fixed this issue by referenced MDL JS file of React-MDL: https://cdn.rawgit.com/react-mdl/react-mdl/master/extra/material.min.js.
Anyway, thank again.

**Comment by zirho** [comment]
Hey all, 
Can we do this with HOC?
Thanks

**Comment by langpavel** [comment]
@zirho I'm sure that HoC are not good solution for this. But I can be wrong...

**Comment by zirho** [comment]
@langpavel I see, I was just wondering because if that's what I need to do for every component that I want to use MDL with, it seems not to be very practical. Hope someone can come up with better solution for that.

**Comment by langpavel** [comment]
What about this: http://www.material-ui.com/#/get-started/usage

**Comment by zirho** [comment]
@langpavel I used it one of my project and found that it's not that scalable.
It can get very slow and bottlenecking with quite amount of components calculating their own styles in client side.
Thank you for the suggestion tho. I'll get back to this when I found something useful.

**Comment by langpavel** [comment]
I find most useful to not depend on pure frontend style library. I like bootstrap for this but in practice I haven't using anything of these..
Everything I ever need is perfectly separated grid library. I didn't met any. I can miss some pretty good lib in this in mind. If you discover something useful in this sense, let us know please! :smiling_imp:

**Comment by zirho** [comment]
Maybe, you can use this http://getbootstrap.com/customize/ to select only the grid system. and apply to your project :)
