### ISSUE TITLE
How to use the helpers in createHelpers.js

### ISSUE THREAD

**Issue by bjackson** [kriasoft/react-starter-kit#1008]
How do I do a graphql request using the helpers in createHelpers.js in the redux branch?

**Comment by buildbreakdo** [comment]
Don't use this fork, but if you look at the bottom of https://github.com/kriasoft/react-starter-kit/blob/feature/redux/src/store/createHelpers.js you will see that the functions are exported as an object.

```js
// src/store/createHelpers.js
export default function createHelpers(config) {
  const fetchKnowingCookie = createFetchKnowingCookie(config);
  const graphqlRequest = createGraphqlRequest(fetchKnowingCookie);

  return {
    fetch: fetchKnowingCookie,
    graphqlRequest,
    history: config.history,
  };
}
```

Speaking generically, usage is similar to how a module/file is used.

```js
import createHelpers from '../../stores/createHelpers.js';

// Provides access to:
// createHelpers.fetch
// createHelpers.graphqlRequest
// createHelpers.history
```

@langpavel who created the branch could likely expand if you need it.

**Comment by langpavel** [comment]
Hi @bjackson, @buildbreakdo 

There is example how to use redux helpers in `feautre/react-intl` branch.

You can look at [src/actions/content.js](https://github.com/kriasoft/react-starter-kit/blob/feature/react-intl/src/actions/content.js#L20), there is `graphqlRequest` helper used.

**Comment by bjackson** [comment]
Thanks!

**Comment by ACPK** [comment]
@bjackson - The link to [src/actions/content.js](https://github.com/kriasoft/react-starter-kit/blob/feature/react-intl/src/actions/content.js#L20) no longer works.
