### ISSUE TITLE
How to access redux store from home route or component.

### ISSUE THREAD

**Issue by tomawilkinson** [kriasoft/react-starter-kit#1009]
Does anyone have any basic pointers on how to access (and update) the global store?

I have merged the redux feature into master.

When I run the server I get the following in the console:
SET_RUNTIME_VARIABLE: { name: 'initialNow', value: 1480609977766 }

Which I assume means the store / redux is actually working (on runtime).

I have followed the integration tutorial:
- I have created a constant, action, reducer and then combined them.

Now I'm not sure how to dispatch from the component or route .js files.

Any help would be amazing!

**Comment by Jaikant** [comment]
I am also looking for some pointers here.

**Comment by langpavel** [comment]
@tomawilkinson @Jaikant:
Look at [LanguageSwitcher](https://github.com/kriasoft/react-starter-kit/blob/feature/react-intl/src/components/LanguageSwitcher/LanguageSwitcher.js#L44..L51) component in `feature/react-intl`

**Comment by DylanYasen** [comment]
I'm struggling about this part as well.
I can fetch data in routes on the server side and pass down to components as props
And I can fetch data in components on the client side using redux actions.
But i just can't figure out how to fetch data in routes on server side and pass down the redux store with the data.
:(

**Comment by frenzzy** [comment]
@DylanYasen 
```js
const route = {
  path: '/news',
  async action({ store }) {
    if (!store.getState().news.length) {
      await store.dispatch(fetchNews())
    }
    return {
      title: 'News',
      component: <Layout><News news={store.getState().news} /></Layout>
      // or ReactRedux.connect(state => ({ news: state.news }))(News)
    }
  }
}

function fetchNews() { // redux action
  return (dispatch) => {
    dispatch({ type: 'NEWS_FETCH' })
    return fetch('/api/news') // return promise
      .then(resp => resp.json())
      .then(news => dispatch({ type: 'NEWS_FETCH', payload: news, error: false }))
      .catch(error => dispatch({ type: 'NEWS_FETCH', payload: error, error: true }))
  }
}
```

**Comment by DylanYasen** [comment]
@frenzzy thank you so much for the help! Appreciate it!
I didn't notice the context which contains the store was passed to UniversalRouter
`    const route = await UniversalRouter.resolve(routes, {
      ...context,
      path: req.path,
      query: req.query,
    });`

**Comment by ulani** [comment]
@tomawilkinson   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
