### ISSUE TITLE
How to make document title with multi language support ？

### ISSUE THREAD

**Issue by WenXuanYuan** [kriasoft/react-starter-kit#1018]
I want to make the document title to support multi language support, how should I write the routes file?
I defined messages like this
<pre>
const messages = defineMessages({
  title: {
    id: 'home.title',
    defaultMessage: "Hello world",
    description: 'home page title',
  },
});
</pre>
But I don`t know how to write code here
<pre>
return {
      title: @@@@ how to write here @@@@@',
      component: &lt;Layout&gt;&lt;Home news={data} /&gt;&lt;Layout&gt;,
 };
</pre>
Need your help, thank you!

**Comment by Ank49** [comment]
Did you find a solution to your problem ?
I'm having the same kind of trouble..

**Comment by langpavel** [comment]
Closed by #1346
