### ISSUE TITLE
npm start doesn't work

### ISSUE THREAD

**Issue by vyorkin** [kriasoft/react-starter-kit#102]
subj

**Comment by koistya** [comment]
@vyorkin do you get an error message when running `npm install`? The `browser-sync` and `jest-cli` modules require `node-gyp` and all its prerequisites met: https://github.com/TooTallNate/node-gyp#installation

**Comment by vyorkin** [comment]
@koistya maybe thats because there is no `server.js` at the root dir, but i'm using the master branch, i'll try `v0.3.3` tag

**Comment by vyorkin** [comment]
ah, ok, `npm start` at `v0.3.3` just runs `gulp` default task

**Comment by koistya** [comment]
To build the project and launch development server with Live Reload functionality you need to run `gulp` or `gulp --verbose`

**Comment by koistya** [comment]
`npm start` might be used when you need to deploy your site to Heroku
