### ISSUE TITLE
Component rendered (all html) but not visible in browser

### ISSUE THREAD

**Issue by archansel** [kriasoft/react-starter-kit#1020]
Hi, I got some weird problems here. Sometimes when I jump around between routes, my page content isn't visible but rendered correctly. and if if hit refresh button it will render correctly and all component visible.

For example, when I got to route A  then B, B rendered correctly and all visible. After that I jump back to route A and then to route B again, sometimes the problem appear. These are two example that show the problem (html rendered correctly but not visible in browser)

Below image should show some menu in the left, html rendered (as show in inspector) but not visible
![example1](https://cloud.githubusercontent.com/assets/816817/21048786/a85d40c0-be43-11e6-9c8e-5027ba6a9f7a.PNG)

Second image shows another example of the same issue in different route, so I think it isn't routing problem. This example is more weird because some component still visible 
![example2](https://cloud.githubusercontent.com/assets/816817/21048789/aae00562-be43-11e6-9830-b5ed9e739752.PNG)

Why this is happening? I don't have any clue, thanks

**Comment by frenzzy** [comment]
I think something wrong with styles, probably with flexbox. Need to see the demo to be able to say more.

**Comment by archansel** [comment]
this is the demo http://54.254.130.183:3000/, you can reproduce the problem (sometimes) by jumping from 'partnership' menu to 'activities' menu back and forth

**Comment by archansel** [comment]
fyi, it only happen on chrome base browser (tested on chrome and vivaldi). edge and firefox work fine

**Comment by archansel** [comment]
@frenzzy what do you think about my problem? did you have a chance to take a look at it? thanks

**Comment by frenzzy** [comment]
Problem: multiple usage of the same `@font-face` statement in different styles

How to fix:
1. Move everything except `:root {/* variables */}` to `src/components/Layout/Layout.css` because only variables may be imported in multiple files (the actual fix)
2. Rename `src/components/style.css` to `src/components/variables.css` for convenience
3. Always use fallback font `font-family: Lato, sans-serif;` instead of `font-family: Lato;`

**Comment by archansel** [comment]
Thanks @frenzzy it solved
