### ISSUE TITLE
Pass 'is logged on' info to frontend

### ISSUE THREAD

**Issue by Mykybo** [kriasoft/react-starter-kit#1032]
On BE `req.isAuthenticated()` tells me if the user is logged in, but I need to propagate this information to frontend. I noticed there is an admin route: 
`src/routes/admin/index.js:`
```
const isAdmin = false;

...
  async action() {
      if (!isAdmin) { // Redirect to login page if user is not admin
        return { redirect: '/login' };
      }

      ...
  },
```

but as you can see, the `isAdmin` bool is always set to false.
(I also need this info on FE to display logout button, etc)

Whats the best way to go about doing this?

**Comment by frenzzy** [comment]
For example if you are using flux/redux, you can add auth state to [the store in server.js](https://github.com/kriasoft/react-starter-kit/blob/258974315e18f5caf48ededda748cfd86e8f2466/src/server.js#L94) and get access to it inside route's `action` method:
```js
action({ store }) {
  if (store.getState().user) {
    /* user is logged in */
  }
  /* else */
}
```

**Comment by Mykybo** [comment]
@frenzzy Thanks a lot! Redux is great.

Just one more question, is there anyway to access the store easily from child react components? (Instead of passing it down through props from the parent) - for example accessing the store from the navigation component.

**Comment by frenzzy** [comment]
http://redux.js.org/docs/basics/UsageWithReact.html
```js
/* Greeting.js */
import React from 'react';
import { connect } from 'react-redux';

class Greeting extends React.Component {
  render() {
    const { user } = this.props;
    return <h1>Hello ${user ? user.name : 'Guest'}</h1>
  }
}

export default connect(state => ({ user: state.user}))(Greeting);
```

**Comment by Mykybo** [comment]
Thanks a lot, works great!

**Comment by Jaikant** [comment]
@frenzzy any reason for not using a redux action/reducer to update the user information into the store? I guess because of this, the user information is not present on client redux store. Is this intentional and not needed?

**Comment by frenzzy** [comment]
@Jaikant why not, you may add actions/reducers to update any data in your store including user, it is up to you. User info presented in store here: [(feature/redux branch) src/server.js#L94](https://github.com/kriasoft/react-starter-kit/blob/111fbdd0db90f92d8674d6c2eb44c99c20d02422/src/server.js#L94)
