### ISSUE TITLE
How to use apollo graphql client with universal router to render isomorphically

### ISSUE THREAD

**Issue by mypark** [kriasoft/react-starter-kit#1036]
I'm trying to use the Apollo client and I am running into a few issues with dropping it into the react starter kit with redux.  https://github.com/kriasoft/react-starter-kit/tree/feature/redux

Trying to use the techniques from here: http://dev.apollodata.com/react/server-side-rendering.html

But I get the error 

    warning.js:36Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
     (client) </div></header><div data-reactid="19">Lo
     (server) </div></header><div class="Home-root-2IM

Here's my implementation

    // server.js
    ...
    const component = (
      <App context={context}>
        <ApolloProvider client={context.client} store={context.store}>
          {route.component}
        </ApolloProvider>
      </App>
    );

    await getDataFromTree(component);

    data.children = ReactDOM.renderToString(component);
    data.style = [...css].join('');
    data.scripts = [
      assets.vendor.js,
      assets.client.js,
    ];
    data.state = context.store.getState();
    if (assets[route.chunk]) {
      data.scripts.push(assets[route.chunk].js);
    }

    const html = ReactDOM.renderToStaticMarkup(<Html {...data} />);
    res.status(route.status || 200);
    res.send(`<!doctype html>${html}`);
    ...

And client side

    // client.js
    ...
    const component = (
      <App context={context}>
        <ApolloProvider client={context.client} store={context.store}>
          {route.component}
        </ApolloProvider>
      </App>
    );

    appInstance = ReactDOM.render(
     component,
      container,
      () => onRenderComplete(route, location),
    );
    ...

	// Home.js

	class Home extends React.Component {
	  static propTypes = {
	    collections: PropTypes.arrayOf(PropTypes.shape({
	      id: PropTypes.string.isRequired,
	      title: PropTypes.string.isRequired,
	      subtitle: PropTypes.string.isRequired,
	      photo: PropTypes.string,
	    })).isRequired,
	  };

	  render() {
	    const props = this.props;
	    const { loading, allCollections } = props.data;

	    if (loading) {
	      return <div>Loading</div>;
	    } else {
	      return (
	        <div className={s.root}>
	          <div className={s.container}>
	            <h1 className={s.title}>Collections</h1>
	            <ul>
	              {allCollections.map((collection) =>
	                <li key={collection.id}>
	                  <h3>{collection.title}</h3>
	                  <img src={collection.photo} width="200"/>
	                </li>
	              )}
	            </ul>
	          </div>
	        </div>
	      );
	    }

	  }
	}

	Home.propTypes = {
	  data: PropTypes.shape({
	    loading: PropTypes.bool.isRequired,
	    allCollections: PropTypes.array,
	  }).isRequired,
	};

	const HomeWithStyles =  withStyles(s)(Home);
	const HomeWithData = graphql(getQuery)(HomeWithStyles);
	export default connect()(HomeWithData);

**Comment by varatep** [comment]
@mypark Any resolutions for this warning?

**Comment by mypark** [comment]
yeah - the resolution was to add more code to explicitly set the apollo store for the client - in server.js `data.state.apollo = client.store ? client.store.getState().apollo : null;`

**Comment by josephdburdick** [comment]
@mypark If this isn't an issue anymore perhaps you can close it or suggest this be covered under recipes?

**Comment by varatep** [comment]
Is it possible this issue is related to deployment on a server? I get the warning once deployed (docker), but not in my local environment. Works in local docker as well.

**Comment by mypark** [comment]
@josephdburdick yes I think it should be something that would be helpful if covered in recipes - do you want me to close this for now?

**Comment by josephdburdick** [comment]
@mypark in your server.js example above, what does client equate to and where do you place that line in `data.state.apollo = client.store ? client.store.getState().apollo : null;`? I'm also trying to add Apollo with SSR.

**Comment by josephdburdick** [comment]
Covering this thoroughly in recipes would be optimal, I'm struggling to adapt Apollo into this starter kit. @mypark When you produced the above example, did you have a gql query inside the `index.js` file for the Home component or did you skip the index file and do all the querying inside Home directly?

**Comment by mypark** [comment]
All the queries were done in the components using the built in apollo higher order component methods

**Comment by mypark** [comment]
I think client was the apollo client instance

**Comment by visualskyrim** [comment]
@mypark Hi, are you adding `data.state.apollo = client.store ? client.store.getState().apollo : null;` to the `server.js` in starter kit. Could you please tell me how do you define `data.state`? I can't find it in the original [server.js](https://github.com/kriasoft/react-starter-kit/blob/master/src/server.js) here.

**Comment by mypark** [comment]
@kongmu - if you look at my code sample you'll see that `data.state =
context.store.getState();`

**Comment by visualskyrim** [comment]
@mypark 
Thanks!
Could you please tell me how did you put the client into your context?
I tried as following:

```
const context = { ... };
context.client = client;
```

But I got an error saying
```
Invariant Violation: App.getChildContext(): key "client" is not defined in childContextTypes.
```

**Comment by visualskyrim** [comment]
@mypark 
Also, I wonder if I can see your `reducers/apollo.js`.
Thanks a lot!

**Comment by mypark** [comment]
I think if you follow the apollo examples of using your own redux store it would have it- I'm away from my computer for a while so can't give you the code snippet

**Comment by mypark** [comment]
@visualskyrim you'll need to set the client in the context object in server.js with your apollo client, e.g. (note that I'm also using my own redux store as well).

```
 const client = new ApolloClient({
      ssrMode: true,
      networkInterface: createNetworkInterface(apolloOptions),
    });

    const context = {
      // Enables critical path CSS rendering
      // https://github.com/kriasoft/isomorphic-style-loader
      insertCss: (...styles) => {
        // eslint-disable-next-line no-underscore-dangle
        styles.forEach(style => css.add(style._getCss()));
      },
      // Initialize a new Redux store
      // http://redux.js.org/docs/basics/UsageWithReact.html
      store,
      client,
    };
```

**Comment by visualskyrim** [comment]
@mypark 
Thanks!
I have read the [ssr document here](http://dev.apollodata.com/react/server-side-rendering.html#server-rendering):

> No changes are required to client queries to support this

So should I just initialize the client in `client.js` like following?

```
  const client = new ApolloClient({
      ssrMode: true,
      networkInterface: createNetworkInterface({ uri: 'http://localhost:4000/graphql' }),
    });
```

Or should I get the client from storage somewhere?(sorry, I'm not very familiar with the redux)

**Comment by visualskyrim** [comment]
Oh sorry, never mind, I found it [here](http://dev.apollodata.com/react/server-side-rendering.html#store-rehydration)
Thanks a LOT!

**Comment by mypark** [comment]
Yeah that's fine

**Comment by ulani** [comment]
@mypark   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
