### ISSUE TITLE
Error: Server terminated unexpectedly with code: null signal: SIGTERM

### ISSUE THREAD

**Issue by pvijeh** [kriasoft/react-starter-kit#1047]
webpack building...
webpack built 3d0f00bedde594ff100f in 580ms
Child
    Time: 580ms
Child
    Time: 663ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  286 kB       0  [emitted]  server
    ../../server.js.map  224 kB       0  [emitted]  server
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 3d0f00bedde594ff100f in 484ms
Child
    Time: 484ms
Child
    Time: 575ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  286 kB       0  [emitted]  server
    ../../server.js.map  224 kB       0  [emitted]  server
webpack: bundle is now VALID.
/Users/peter/Desktop/projects/www/react-starter-kit/tools/runServer.js:80
          throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
          ^

Error: Server terminated unexpectedly with code: null signal: SIGTERM
    at ChildProcess.server.once (/Users/peter/Desktop/projects/www/react-starter-kit/tools/runServer.js:54:17)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! web@0.0.0 start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web@0.0.0 start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/peter/Desktop/projects/www/react-starter-kit/npm-debug.log

**Comment by rizvified** [comment]
Facing the same problem with node v7.3.0 and npm v4.0.5

**Comment by rizvified** [comment]
@pvijeh i got it working by first installing babel-node : npm i -g babel node.
then running babel-node tools/run start manually in the root directory.
If it gives you an error of installing sqlite manually, just run npm rebuild. 
and viola!

**Comment by benweizhu** [comment]
The same issue.

**Comment by TristanDongMaster** [comment]
the same to me , how to fix it???
