### ISSUE TITLE
yarn doesn't recognize 'install'

### ISSUE THREAD

**Issue by ProbonoBonobo** [kriasoft/react-starter-kit#1050]
I followed the yarn installation instructions a few days ago (version 1.4.0), and on a fresh clone of the repository I'm encountering a little hiccup with the build instructions:

> 
> Kevins-MacBook-Pro-3:react-starter-kit $ yarn install
> yarn
> 
> 
> Commands:
>   init   scaffold a new yarn site
>   new    create new content
>   build  build your site
>   clean  cleans destination folder
>   serve  serve your site with http-server
>   watch  build, serve, and watch for file changes
> 
> Options:
>   --incremental  only build files that have changed    [boolean] [default: true]
>   --verbose      log out additional log information                    [boolean]
>   --version, -v  installed version                                     [boolean]
>   --help         Show help                                             [boolean]
> 
> 
> 
> 
>

I'm a little unsure how to proceed. Yarn is quite new and I'm not really sure how to use it yet. Any suggestions welcome and appreciated.

**Comment by ProbonoBonobo** [comment]
In the meantime, as of this writing the project skeleton builds just fine with npm.  As a temporary workaround, just replace 'yarn install' with 'npm install' and 'yarn start' with 'npm start'. I notice the yarn lockfile was just added a few days ago, so I'm guessing maybe the build instructions haven't been fully ported over yet?

**Comment by jonirrings** [comment]
update yarn to the newest may solve this
