### ISSUE TITLE
Getting the current route's name 

### ISSUE THREAD

**Issue by howardya** [kriasoft/react-starter-kit#1056]
I am trying to get the current route's name, for instance '/login' in one of my component. 

One way I can think of is to inject it into the props in the action method in the routes definition. However, this may not be practical if there are nested children and only one of the deeply nested children needs that info.

Is there a simpler method to get it directly? (For instance, in react router, can get it from this.props.location.pathname in any children of the routes)

**Comment by buildbreakdo** [comment]
@howardya Could alternatively set it in one place via context middleware in server.js?

**Comment by langpavel** [comment]
Use `history`. Search for `history` in `server.js`.
I think you can get instance in each route. This should work in both, server and client.
