### ISSUE TITLE
Usability Errors

### ISSUE THREAD

**Issue by TylerL-uxai** [kriasoft/react-starter-kit#1058]
I plan to put all my usability errors for improving the developer experience here.

Error: Thought the footer wrapped the feedback stuff. The footer doesn't include the feedback div.

Error: Not quite sure where to put the server controllers to create passport-local (future PR for this repo maybe).
- I created a folder in "core", hoping I'm doing it right.

Error: Lack of a concrete example using app.post (they're all app.get in server.js). Want to know if the sign up form needs something besides a typical html submit command (something using javascript or JSX).

-  learned that the JSX uses a 'fetch' command after some research. Hope this helps anyone with the same error. There's also an "isomorphic fetch", but idk the difference yet.
- see my post on how to configure a sign up page in the comments

Error: Not sure if the tests are configured to use a test database (I assumed they would be after thinking about it). Searched for a test db configuration and couldn't immediately find one.
- Update on error: Not trying to lecture people on the importance of usability, but I think we need to make it more obvious that test/setup.js is being executed, because I didn't even read that after a few hours of trying to run tests. Not really sure how to improve this error, but it is a usability error based on reason and actual user testing that people won't know if there's a test database right away.
- I know I'm an idiot for not being able to figure this stuff out, but my hope is that we can reduce the chances of other people encountering an error. Thanks everyone :)

**Comment by TylerL-uxai** [comment]
I'm by no means an expert, but here's a basic JSX sign up page.

```

class Register extends React.Component {
  static propTypes = {
    title: PropTypes.string.isRequired,
    slagline: PropTypes.string.isRequired,
  };
  constructor(props) {
    super(props);
    this.state = {
      inputEmail: 'aaaaa',
    };
  }

  handleInput = (event) => {
    this.setState({
      inputEmail: event.target.value,
    });
  }

  newCustomer = (event) => {
    fetch('/customers/sign-up', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        email: this.state.inputEmail,
        secondParam: 'yourOtherValue',
      }),
    });
  }
````

This part goes in render( )

````
              <input
                id="customer-email"
                className="form-control"
                value={this.state.inputEmail}
                onChange={this.handleInput}
                type="text"
              />
              <p>Input: {this.state.inputEmail}</p>
```

**Comment by TylerL-uxai** [comment]
## Example Server Testing

```
// customers.test.js

import { expect /* ,should */ } from 'chai';
import { Customer } from '../../data/models';

/* eslint-env mocha */

describe('Customer Server Tests', () => {
  it('Should start with 0 customers.', async () => {
    const allCustomers = await Customer.findAll();
    expect(allCustomers.length).to.equal(0);
  });
  it('Create a customer', async () => {
    const createCustomer = await Customer.create({ email: 'test@gmail.com' });
    expect(createCustomer).to.exist; // eslint-disable-line no-unused-expressions
  });
  it('Delete customer from test database.', async () => {
    const numberOfDeletedPeople = await Customer.destroy(
      { where: { email: 'test@gmail.com' } },
    );
    expect(numberOfDeletedPeople).to.equal(1); // eslint-disable-line no-unused-expressions
  });
});


```

**Comment by ulani** [comment]
@TylerL-uxai   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
