### ISSUE TITLE
wait so long

### ISSUE THREAD

**Issue by taoveweb** [kriasoft/react-starter-kit#1064]
when start project need too long

**Comment by langpavel** [comment]
Be more concrete. I know it can be tedious starting project again and again, but this is often not needed because hot replacement works for most cases.

**Comment by buildbreakdo** [comment]
@taoveweb @langpavel Assume he means time it takes for a rebundle... we probably could speed it up by not rebundling vendor as it doesn't change very often (unless package.json changes) and is usually the big one.

Maybe hash of package.json, if it matches old hash don't rebundle vendor both on startup and rebuild? Thinking out loud.

**Comment by stay2be** [comment]
> @buildbreakdo  Assume he means time it takes for a rebundle... we probably could speed it up by **not rebundling vendor** as it doesn't change very often (unless package.json changes) and is usually the big one.

For testing purposes, how can this be achived? What exactly has to be changed in `webpack.config.js`? 

Thanks. :)

**Comment by langpavel** [comment]
This is question for @koistya and @frenzzy because I have almost zero experience with webpack. Today I readed about Webpack 2.2, I'm not sure if this will be easier later or if it can be done now. Any help wanted :100:

**Comment by iDVB** [comment]
I would also be very interested in a way to speed up the build. Ours are taking an average of 4-5 mins even for local. We're still using Webpack v1, so I've been wondering if v2 might help. Or if we need to try a more agreesive approach like [DLLs](https://robertknight.github.io/posts/webpack-dll-plugins/)

**Comment by langpavel** [comment]
Build time was slightly reduced somewhere after webpack v2 was introduced in RSK. I'm not sure which PR or commit..
Introducing DLLs can speed things up more locally, but I'm not sure if it can help CI tools.. setting up cache and cache clean properly can be hard on tooling

**Comment by iDVB** [comment]
Can it really need to take that long though? Maybe it's worth diving in to see exactly what part is taking the bulk of the time?

**Comment by ulani** [comment]
@taoveweb   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
