### ISSUE TITLE
Calling history.push inside action() method crashes the app

### ISSUE THREAD

**Issue by howardya** [kriasoft/react-starter-kit#1065]
I tried to perform some middleware logic within the action method and then redirect under certain condition, in particular in one of the route i have

```
export default {
  path: '/mypath',
  action() {
    if(/*some logic */) {
      history.push('/'); // redirect to home page 
    }
    return {
      title,
      component: <MyPath />,
    };
  },
};
```

However, i get this error 
TypeError
_history2.default.push is not a function

Any issue with this? Thanks

**Comment by frenzzy** [comment]
Do not use browser history inside [isomorphic](http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/) `route.action()` method.
Look at the redirect example for admin page: [src/routes/admin/index.js#L22](https://github.com/kriasoft/react-starter-kit/blob/ebd5faa1f04b5e1f98bdda844d35658c1190160e/src/routes/admin/index.js#L22)
```js
const route = {
  path: '/your/path',
  action() {
    if (/* some logic */) {
      return { redirect: '/' } // redirect to home page 
    }
    return {
      title: 'Page Title',
      component: <YourComponent />,
    };
  },
};
```

**Comment by howardya** [comment]
alright, noted. Thanks. 👍
