### ISSUE TITLE
Adding a logout route

### ISSUE THREAD

**Issue by Mykybo** [kriasoft/react-starter-kit#1069]
I have added `require('./logout').default,` to routes/index.js and created routes/logout/index.js like so:
```
export default {
  path: '/logout',
  action({ req, res }) {
      req.session.destroy(function (err) {
        res.redirect('/');
      });
  },
};
```
But the req and res params are undefined. Is this a correct way to implement a logout route?

I would also prefer to use a post request for logout, can I send a post request to this route?

**Comment by frenzzy** [comment]
These routes are used for [isomorphic](http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/) html rendering and executed on both server-side and client-side (in the browser).
Api routes like PUT, POST, etc. should exist on the server side only. For example you may find authentication  api endpoints here: [src/server.js](https://github.com/kriasoft/react-starter-kit/blob/ebd5faa1f04b5e1f98bdda844d35658c1190160e/src/server.js#L50-L74)
```js
/* src/server.js#L75 */
app.post('/logout', (req, res) => {
  req.session.destroy();
  res.redirect('/');
});
```

**Comment by Mykybo** [comment]
I understand this, the reason I put it in routes/index.js was because I thought it could be done without refreshing the page. (More like the <a href> links are intercepted by the router, so the get request didn't get all the way to server.js)

But yeah, I guess there is nothing wrong with refreshing the page on logout. Thanks.

**Comment by Mykybo** [comment]
Any idea why there is no property session in req? ~`Cannot read property 'destroy' of undefined` (req.user exists and everything else seems ok)

**Comment by frenzzy** [comment]
You can override default behavior like this:
```js
function logout(event) {
  event.preventDefault(); // prevent page transition
  fetch('/logout').then(() =>
    window.location.reload() // stay at the same url
  )
}

<Link to="/logout" onClick={logout}>Logout</Link>
<a href="/logout" onClick={logout}>Logout</a>
<button type="button" onClick={logout}>Logout</button>
```

Also you can use redux action to logout user without page refresh:
```js
const USER_LOGOUT = 'USER_LOGOUT'; // action type

function logout() { // redux action
  return (dispatch) => {
    dispatch({ type: USER_LOGOUT });
    return fetch('/logout').then(resp => resp.json())
      .then(data => dispatch({ type: USER_LOGOUT, payload: data, error: false }))
      .catch(error => dispatch({ type: USER_LOGOUT, payload: error, error: true }))
  }
}

const initialState = null;

function user(state = initialState, action) { // redux reducer
  switch (action.type) {
    case USER_LOGOUT:
      return action.error === false ? initialState : state;
    default:
      return state;
  }
}
```

There is not session auth in the master branch, so you can just clear cookie for logout:
```js
/* src/server.js#L75 */
app.post('/logout', (req, res) => {
  res.clearCookie('id_token');
  res.redirect('/'); // or res.sendStatus(200);
});
```

**Comment by ethansinjin** [comment]
Is there any particular reason that this code example shouldn't be added?

**Comment by Mykybo** [comment]
@frenzzy directly sending the POST request works great (the first snippet you have posted).
However I have been trying to make the second snippet to work as well (on feature/redux branch) and I am not sure how to dispatch the logout action. 
The action from your snippet returns a callback to which a dispatch function should be passed however I am a little lost on how to do this.

Consider we are in navigation.js and add
`<Link className={s.link} to="#" onClick={user_logout}>Logout</Link>
`
What I tried, is adding following function
```
import { logout } from '../../actions/user';

function user_logout () {
  var cb = logout();
  cb(dispatch);
}

```
The thing is, I don't know where to get the dispatch function (or store, which has it). Could you please advise me how to do this correctly?

**Comment by frenzzy** [comment]
You may use `mapDispatchToProps` inside [react-redux](https://github.com/reactjs/react-redux) `connect()`: [Redux - Usage with React](http://redux.js.org/docs/basics/UsageWithReact.html)

Or dispatch manually:
```js
class LogoutButton extends React.Component {
  static contextTypes = {
    store: PropTypes.object.isRequired,
  };

  handleClick = () => {
    this.context.store.dispatch(logout());
  };

  render() {
    return <button type="button" onClick={this.handleClick}>Logout</button>;
  }
}
```

**Comment by Mykybo** [comment]
Thanks! For anyone interested, this is what I did:
`export default connect(state => ({ user: state.user }), dispatch => ({ logout_click: bindActionCreators(logout, dispatch) }))(withStyles(s)(NavLogin));`

Also, I had to add `credentials: 'same-origin'` to the logout post like so:
`return fetch('/logout', { method: 'POST', credentials: 'same-origin' })`
Otherwise on page refresh it logged me back in on FE (I wasn't properly logged out)
