### ISSUE TITLE
png broken after git commit 

### ISSUE THREAD

**Issue by giftman** [kriasoft/react-starter-kit#1072]
try to add "*.png binary" in .gitattributes,but it's not working. I'm not sure what's going wrong.Please  help.

my env:
macos sierra 10.12.2

**Comment by frenzzy** [comment]
Please try to remove [this line from package.json](https://github.com/kriasoft/react-starter-kit/blob/ebd5faa1f04b5e1f98bdda844d35658c1190160e/package.json#L187-L190)

**Comment by giftman** [comment]
@frenzzy  remove that line fix the problem,thank you!

**Comment by giftman** [comment]
![image](https://cloud.githubusercontent.com/assets/3108344/21756491/ea37c660-d65c-11e6-8071-232939dd877a.png)  I found it can work with the .editorconfig like this..

**Comment by rochadt** [comment]
@frenzzy can we get an updated pr for this on frenzzy/pre-commit? This issue appears to affect all newly added images.
