### ISSUE TITLE
Editing released project version

### ISSUE THREAD

**Issue by gmaijoe** [kriasoft/react-starter-kit#1074]
Now that I have released the app, whenever I want to edit the program locally (localhost with npm start), I get all sorts of errors like:

Module build failed: Error: ENFILE: file table overflow, open '/Users/gmaister/Desktop/workspace/shore_web/node_modules/babel-preset-latest/lib/index.js' (While processing preset: "/Users/gmaister/Desktop/workspace/shore_web/node_modules/babel-preset-latest/lib/index.js")

or

ERROR in ./src/data/models/UserLogin.js
    Module build failed: Error: Cannot find module 'babel-plugin-transform-es2015-template-literals' (While processing preset: "/Users/gmaister/Desktop/workspace/shore_web/node_modules/babel-preset-latest/lib/index.js")

Anybody know how to fix this?

**Comment by buildbreakdo** [comment]
Note `/node_modules/babel-preset-latest/lib/index.js` is in both of those. Looks like you have inadvertently deleted a module either from your `package.json` file or from your `node_modules` folder. 

Would run `npm install --save-dev babel-preset-latest` and then try to start the app. If that doesn't work, delete your node_modules folder and run `npm install`.

**Comment by gmaijoe** [comment]
npm install --save-dev babel-preset-latest worked!
