### ISSUE TITLE
Generate Custom URL for links/profiles

### ISSUE THREAD

**Issue by gmaijoe** [kriasoft/react-starter-kit#1079]
This is not a specific issue but I want to generate custom URLs for profiles such as localhost:3001/users/jim127. Anyone know a good way of doing this?

**Comment by frenzzy** [comment]
You may want to [add user route](https://github.com/kriasoft/react-starter-kit/blob/8625a744dc18d706d14c7ff6bfb55bc39b97e9f6/src/routes/index.js#L26):
```js
/* src/routes/users/index.js */
import React from 'react';
import Layout from '../../components/Layout';

export default {
  path: '/users/:username',
  async action({ params }) {
    // get user data from api
    const user = await fetch(`/api/users/${params.username}`).then(resp => resp.json());
    if (!user) return null; // user not found

    // code-splitting
    const UserProfile = await new Promise((resolve) => {
      require.ensure([], (require) => resolve(require('./UserProfile').default), 'users');
    });

    return {
      title: user.fullName,
      chunk: 'users',
      component: <Layout><UserProfile user={user} /></Layout>,
    };
  },
};
```

**Comment by langpavel** [comment]
If you want, create a single file with functions like this:
```js
export const getUserLink = ({user}) => `/users/${user}`;
```

**Comment by haipc** [comment]
@frenzzy 
I use your code to implement new dynamic router, but when I access to: 

> http://localhost:3001/users/haipc
 
And then get an error. CSS of page does not work fine :(
In want to hear your solution for this case or example. Thanks so much!

**Comment by frenzzy** [comment]
@haipc what the error with css do you have?

**Comment by haipc** [comment]
Thanks @frenzzy for hear my question.
It's my mistake when using relative path for CSS on my page. My problem has fixed when I was using the absolute path.
