### ISSUE TITLE
the function getPage in database.js always read a none existing file due a wrong path

### ISSUE THREAD

**Issue by yecwang** [kriasoft/react-starter-kit#108]
Here, if err, try to read file name, but after joined path, it always point to none existing path,

fs.readFile(fileName, {encoding: 'utf8'}, (err, data) => {
        if (err) {
          fileName = path.join(CONTENT_DIR, uri + '/index.jade');
    fs.readFile(fileName, {encoding: 'utf8'}, (err2, data2) => {
           resolve(err2 ? null : parseJade(uri, data2));
         });
        }

**Comment by koistya** [comment]
@yecwang thanks for the report! I believe this issue was resolved.
