### ISSUE TITLE
Replace the deprecated Google Api feed RSS to JSON service

### ISSUE THREAD

**Issue by westrem** [kriasoft/react-starter-kit#1080]
The current demo uses the Google Api feed service which has been [deprecated](https://developers.google.com/feed/) and no longer works. Therefore, after the initial `yarn install && yarn start` there are no news displayed on the Home page.

This might be quite confusing for newcomers as the [demo](https://demo.reactstarterkit.com/) shows these news.

A quick working fix might be to use rss2json.com like this:

```
...
const url = 'https://api.rss2json.com/v1/api.json?rss_url=https%3A%2F%2Freactjsnews.com%2Ffeed.xml';
...
```

and in the data handling section:

```
...
if (data.status === 'ok') {
  items = data.items;
}
...
```

Voala! The news are now showing properly.

**Comment by hienhuynhtm** [comment]
Good job men

**Comment by jwhchambers** [comment]
@westrem I have made the changes myself also, but it requires a bit more than the above as the requested data doesn't have exactly the same structure as before. publishedDate => pubDate, contentSnippet => content. The content field would need some truncation also to make it into a snippet, or just omit it completely as it isn't really necessary. Did you want to make a PR on this? or shall I give it a go?

**Comment by westrem** [comment]
@jwhchambers feel free to give it a go ;)

**Comment by iDVB** [comment]
+1
Any progress on this?

**Comment by Grabes** [comment]
I created a pull request for this https://github.com/kriasoft/react-starter-kit/pull/1092
