### ISSUE TITLE
npm start error when babel-cli upgrade to 6.22.1

### ISSUE THREAD

**Issue by infeng** [kriasoft/react-starter-kit#1095]
`npm start` error when babel-cli upgrade to 6.22.1, the error info like this:
![rsk-error](https://cloud.githubusercontent.com/assets/16483610/22137686/7a5c8d6c-df17-11e6-9055-2a420e9f7688.png)

**Comment by KyleChamberlin** [comment]
I am fairly new to react, and this issue popped up for me, any idea if I am doing something wrong, or if this is a bug?

**Comment by langpavel** [comment]
Use `yarn start` or `npm run start` commands. You can look inside `package.json` at `scripts` section.

**Comment by infeng** [comment]
I just use `npm run start`, the keypoint is when babel-cli upgrade to 6.22.1, `npm run start` cause error

**Comment by langpavel** [comment]
RSK is using 6.22.2 without errors now.
