### ISSUE TITLE
assets not loading over reverse proxy (nginx)

### ISSUE THREAD

**Issue by keatz55** [kriasoft/react-starter-kit#1096]
First of all great work on this project. You are truly thought leaders.

I am trying to serve a single instance react-starter-kit app over a nginx reverse proxy on the path name `/stories` - fe. the url would be `http://localhost/stories`.

The app itself loads fine, but the assets via webpack do not load at `http://localhost/stories/assets`. - where I need them to load.

Here is my nginx.conf:
```
worker_processes 4;

events { worker_connections 1024; }

http {

  upstream home {
    least_conn;
    server home:3001 weight=10 max_fails=3 fail_timeout=30s;
  }

  upstream stories {
    least_conn;
    server stories:3001 weight=10 max_fails=3 fail_timeout=30s;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://home;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    location /stories {
      rewrite ^/stories(.*) /$1 break;
      proxy_pass http://stories;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }
}
```

**Comment by varatep** [comment]
@keatz55 Were you able to find a resolution for this?

**Comment by tk1cntt** [comment]
I have the same issue

**Comment by mantap123** [comment]
Same here....
Execute build release command on my laptop:
`yarn run build -- --release`

And then upload the build/* directory to production server... Using nginx as reverse-proxy...

Assets name requested by compiled project, is different with real filename generated by build command...

Here file list generated by build command:
<img width="292" alt="jepretan layar 2017-02-24 pada 4 40 54 pm" src="https://cloud.githubusercontent.com/assets/23210857/23298415/26c6d856-fab0-11e6-9360-becb88232305.png">

But the app on browser requested another different file name:
<img width="695" alt="jepretan layar 2017-02-24 pada 4 41 14 pm" src="https://cloud.githubusercontent.com/assets/23210857/23298439/5061fbf0-fab0-11e6-8a86-0f72a4982fd9.png">

**Comment by langpavel** [comment]
I think problem here is with `/` prefixing resources path. You must tweak public path in webpack

**Comment by mantap123** [comment]
I'm sorry... 
Currently I am building 2 projects built with React Starter Kit...

I was upload Project A's build files to Project B's staging server... 😆

**Comment by hasan-aftab** [comment]
I have been iframing an external site in my website via nginx reverse proxy and site is being framing properly but its assets JS and CSS are not being loaded

 I tried sub_filter as well but still no success

  sub_filter 'href="/' 'href="/proxy/';
  sub_filter 'src="/' 'src="/proxy/';
