### ISSUE TITLE
Basic Form Handling

### ISSUE THREAD

**Issue by mikepc** [kriasoft/react-starter-kit#1097]
As an engineer new to React (this is my first universal app), I find it exceedingly challenging to know how forms/state is expected to be managed.

I don't want to use redux since the default opinion seems to be that it's not intended ( I know there is a branch for it, but I'd rather go with the default than go down the "old" path).

Basically I want to create a form, when the user submits that form it redirects to another page with values in the route url that the new page (a second form) will use to populate elements. A basic example showing the transfer of state from one page to another would be great, but just basic form usage (or a solid explanation in the docs) is absolutely essential.

The key disconnect I'm having is I the only onClick handler I see is in the custom Link handler, and the login/signup form I just do not understand how they work *at all*. The form is posting, but I see no handling of it .. at all. If anything is happening, it's pure magic.

Guidance here in the starter kit would be extremely helpful. Thank you very much for your awesome work!

**Comment by frenzzy** [comment]
Basic example (with full page reload):
```js
<form action="https://www.google.com" method="get">
  <input type="text" name="q" />
  <button>Search</button>
</form>
```
SPA example:
```js
import React from 'react';
import history from '../core/history';

class SearchForm extends React.Component {
  handleSubmit = (event) => {
    event.preventDefault(); // prevent full page reload

    // change current location without full page reload
    history.push(`/search?q=${event.target.elements.q.value}`);
  };
  render() {
    return (
      <form action="/search" method="get" onSubmit={this.handleSubmit}>
        <input type="text" name="q" />
        <button>Find</button>
      </form>
    );
  }
}

export default SearchForm;
```
Playground: https://jsfiddle.net/frenzzy/qv9rk7dc/
Documentation: https://facebook.github.io/react/docs/forms.html

**Comment by mikepc** [comment]
Yes but the fetch() inside async action() and I have no pointers to the router, or anywhere to get the query params from when the form loads.

I'm trying to adapt the starter kit action() to work with form data is really what I'm going for. I do not see a path where in index.js I can get this data, and it appears that's where I *should* be getting the data from.

I will try moving the fetch into a separate component, but I'm worried that this.router is not going to be available there either :\

`


import React from 'react';
import Home from './Home';
import fetch from '../../core/fetch';
import Layout from '../../components/Layout';

export default {

  path: '/',

  async action() {
    debugger;
    
    const resp = await fetch('/graphql', {
      method: 'post',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        query: `{
        search(
            lat: lat, 
            lon: lon, 
            category: cat, search: search ) 
            {
                name
                text
                category
            }
        }
      `,
      }),
      credentials: 'include',
    });
    const { data } = await resp.json();
    if (!data || !data.search) throw new Error('Failed to load the news feed.');
    return {
      title: 'Search',
      component: <Layout><Home pads={data.search} /></Layout>,
    };
  },

};

`

**Comment by frenzzy** [comment]
Playground with query: https://jsfiddle.net/frenzzy/1gk5mh1d/1/
Can you explain your problem a bit more? What is the expected result?

**Comment by langpavel** [comment]
This is really a beginner question. You should play with react and router a little.
