### ISSUE TITLE
Material-UI Support

### ISSUE THREAD

**Issue by mikepc** [kriasoft/react-starter-kit#1099]
I've put the MuiThemeProvider in Layout.js like so:

```
        MuiThemeProvider
        div
          Header 
          {this.props.children}
          Footer 
        div
      /MuiThemeProvider

```

And I added the 
`
import injectTapEventPlugin from 'react-tap-event-plugin';
`
To the top of client.js

and call injectTapEventPlugin() on line 112 after the FastClick.attach() call.

I want to make sure that this is the *right* way to add Material-UI support to the app.

**Comment by langpavel** [comment]
I'm not fan of MUI, but I have it in one project.
This is exactly what you need, as far as I know...

**Comment by ninjavungve** [comment]
@langpavel  You can share source code to me?

**Comment by langpavel** [comment]
Unfortunately it is not my project and I'm keeping busy. Your description looks good.

**Comment by ninjavungve** [comment]
@langpavel Okay. Thanks!
