### ISSUE TITLE
I got error on npm start

### ISSUE THREAD

**Issue by awa1988** [kriasoft/react-starter-kit#1102]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\vv\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.1.2
3 info using node@v4.4.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mss-frontend@0.0.7~prestart: mss-frontend@0.0.7
6 silly lifecycle mss-frontend@0.0.7~prestart: no script for prestart, continuing
7 info lifecycle mss-frontend@0.0.7~start: mss-frontend@0.0.7
8 verbose lifecycle mss-frontend@0.0.7~start: unsafe-perm in lifecycle true
9 verbose lifecycle mss-frontend@0.0.7~start: PATH: C:\Users\vv\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\sprint8\mss-frontend\node_modules\.bin;C:\Users\vv\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\vv\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone;C:\Users\vv\AppData\Roaming\npm;%NVM_HOME%;%NVM_SYMLINK%;C:\Program Files\nodejs;C:\Users\vv\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\vv\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle mss-frontend@0.0.7~start: CWD: D:\sprint8\mss-frontend
11 silly lifecycle mss-frontend@0.0.7~start: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dev-server --config webpack.config.dev.js  --content-base app --inline --hot' ]
12 silly lifecycle mss-frontend@0.0.7~start: Returned: code: 1  signal: null
13 info lifecycle mss-frontend@0.0.7~start: Failed to exec start script
14 verbose stack Error: mss-frontend@0.0.7 start: `webpack-dev-server --config webpack.config.dev.js  --content-base app --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\vv\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\vv\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid mss-frontend@0.0.7
16 verbose cwd D:\sprint8\mss-frontend
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vv\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.4.4
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error mss-frontend@0.0.7 start: `webpack-dev-server --config webpack.config.dev.js  --content-base app --inline --hot`
22 error Exit status 1
23 error Failed at the mss-frontend@0.0.7 start script 'webpack-dev-server --config webpack.config.dev.js  --content-base app --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mss-frontend package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --config webpack.config.dev.js  --content-base app --inline --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mss-frontend
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mss-frontend
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by frenzzy** [comment]
[Requirements:](https://github.com/kriasoft/react-starter-kit/blob/6bc41c93124afa3336c7a55f5f57dab6a566b956/docs/getting-started.md#requirements) node.js v6.5 or newer

**Comment by buildbreakdo** [comment]
@awa1988 Echoing frenzzy:

```
17 error Windows_NT 6.1.7601
18 error argv "C:\Program Files\nodejs\node.exe"
"C:\Users\vv\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "start"
19 error node v4.4.4        <--------------------- Wrong version
20 error npm v4.1.2 
21 error code ELIFECYCLE
```
