### ISSUE TITLE
HMR doesn't work

### ISSUE THREAD

**Issue by danhead** [kriasoft/react-starter-kit#1104]
I'm new to React, Webpack and the concept of HMR so forgive me if it is user error. I have a fresh clone of master, yarn install && yarn start works fine, but no file edits to anything in the src/ folder triggers webpack to rebuild. 

I do see [HMR] connected in the console.

OS: Ubuntu 16.04
Node: v7.0.0
Yarn: v0.19.1

Any help would be greatly appreciated!

**Comment by danhead** [comment]
Looking through the yarn install log, I suspect I've found the reason:

```
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
```

**Comment by danhead** [comment]
I've discovered if I repeatedly save a file (usually between 5-10 times in quick succession), eventually Webpack will acknowledge that the bundle is now invalid and will rebuild it:

```
webpack: bundle is now INVALID.
webpack building...
webpack built 2f57754fc47745110ff4 in 975ms
```

**Comment by mesrob-fender** [comment]
Experiencing a similar problem, but only when I merge the react-intl library. Webpack does pick it up to compile the latest changes, and I do see the API call in the network tab e.g. `http://localhost:3001/assets/4.301d2714688028822ff3.hot-update.js` to go through but the browser still does not refresh using Chrome.

**Comment by danhead** [comment]
Silly solution to this problem for me, VIM's :w command doesn't seem to trigger the webpack rebuild, using Sublime Text it works every time, so it must be something to do with the way VIM writes changes to the disk. I'll investigate further when I have more time, but for now I guess this can be closed :-)
