### ISSUE TITLE
Deeply nested folder structure

### ISSUE THREAD

**Issue by lnaie** [kriasoft/react-starter-kit#111]
After running npm install, you get a deeply nested folder structure in node modules folder. The problem is on windows, it cannot be easily removed if you need to -- cygwin helps with: rm -fr "PATH".
I think this should be investigated and fixed.

**Comment by alexmcmillan** [comment]
This is a well known problem for us Windows devs:  https://github.com/joyent/node/issues/6960

**Comment by koistya** [comment]
@lnaie you can remove `node_modules` on Windows by executing the following command in a console:

```shell
cmd /c rmdir /s /q node_modules
```

If it doesn't help, you may try to rename problematic folders inside the `node_modules` folder by giving them shorter names. E.g. `node_modules/liba-a/node_modules/lib-b` -> `1/2/3/4`, then run `cmd /c rmdir /s /q node_modules` again.
