### ISSUE TITLE
Error: Only absolute urls are supported

### ISSUE THREAD

**Issue by Shadowman4205** [kriasoft/react-starter-kit#1120]
Hello, i get this error when i am trying this:

```
 path: '/news',

  children: [
    {
      path: '/',
      action() {
        return {
          component: <Layout><News /></Layout>,
        };
      }
    },
    {*/
      path: '*',
      async action({ path, store }) {
        try {
          await store.dispatch(loadSelectedNews({ path }));
          debugger
          const data = store.getState().selectedNews;
          return {
            component: <Layout><Content content={data} /></Layout>,
          };
        } catch (e) {
          throw new Error(e);
        }
    },
 },]
};
```
Is this error because i am using dynamic path as nested of parent /news?

**Comment by frenzzy** [comment]
No, nested wildcard routes e.g. { path: '*', ... } should work fine.
Playground: https://jsfiddle.net/frenzzy/220eq2sv/

But need to remember that `path` inside `action` method is relative to the parent route:
```js
const routes = [
  {
    path: '/one',
    action({ path }) {
      console.log(path); // => /one
    },
  },
  {
    path: '/two',
    children: [
      {
        path: '/',
        action({ path }) {
          console.log(path); // => / (not /two/)
        },
      },
      {
        path: '/three',
        action({ path }) {
          console.log(path); // => /three (not /two/three)
        },
      },
    ],
  },
];
```

Also need to remember about url encoding:
```js
// window.location.pathname or req.path in express example
const location = new URL('/café');
console.log(location.pathname); // => /caf%C3%A9

const routes = [
  {
    path: '*',
    action({ path, params }) {
      console.log(path); // => /caf%C3%A9
      console.log(params); // => {}
    },
  },
  {
    path: '/:any*',
    action({ path, params }) {
      console.log(path); // => /caf%C3%A9
      console.log(params); // => { any: 'café' }
    },
  },
];
```

And if you need the original url inside your `action` method, you can pass it down via router:
```js
UniversalRouter.resolve(routes, {
  path: location.pathname, // or req.path for express
  originalUrl: location.pathname, // or req.path for express
});

const routes = { path: '/one', children: [
  { path: '/two', action({ path, originalUrl }) {
    console.log(path);        // => '/two'
    console.log(originalUrl); // => '/one/two'
  } },
] };
```

looks like in your example `loadSelectedNews()` throws an error, so need to exactly know what this function expects, can you provide an example?

**Comment by Shadowman4205** [comment]
Ok lets say i am in my parent pat /news , there is one link thats navigate to selected news the link has path
/news/2017-01-17/winter.. i want use this path and pass it to loadSelectedNews() where i am usinng split splice to get 2017-01-17,winter after that i am using these both to query database.

But when i click a link with href-> /news/2017-01-17/winter i get this error

**Comment by frenzzy** [comment]
Can you share implementation of `loadSelectedNews()` then?
This function should not query db directly, but only via http request to api.

**Comment by Shadowman4205** [comment]
```
loadSelectedNews(newsPath) {
    let query;
    var s = newsPath
    let res = s.split('/');
    res = res.splice(0,1);
    let newsDate = moment(res[0]);
    query.newsDate = newsDate.format('YYYY-MM-DDΤHH-mm-ssΖ');
    query.sUrl = 'winter';
    
    if(newsPath == "" || newsPath == null ){
         query = "/api/news";
    }else{ 
         query = "/api/news?newsDate="+ query.newsDate + "&sUrl=" +query.sUrl;  
    }
 
    return async (dispatch) =>  {
        return await fetch(query)
            .then(response => response.json())
            .then((data) => {
                dispatch(loadSelectedNewsSuccess(data));
            }).catch(error => {
                throw (error);
            });
    }
}
```
I am use feathers js this is working well when i do direct seacrh using url

**Comment by Shadowman4205** [comment]
I found the problem, it is the store i think that i pass to async action :/

**Comment by frenzzy** [comment]
Do you have `import fetch from '../../core/fetch';` at the top of this file?

This module uses [whatwg-fetch](https://github.com/github/fetch) and [node-fetch](https://github.com/bitinn/node-fetch) polyfills on client and server side respectively.

Protocol and hostname [should be always specified](https://github.com/bitinn/node-fetch/blob/560d5d6a023f069c37497f633fe65955182fa3d5/src/index.js#L44) in the url for `node-fetch`, and our [src/core/fetch](https://github.com/kriasoft/react-starter-kit/blob/fb36e0fb732da65351df5aa0cedf56d9ddaadc1c/src/core/fetch/fetch.server.js#L17-L27) isomorphic module should resolve this problem.

**Comment by Shadowman4205** [comment]
No i am using import fetch from 'isomorphic-fetch'; Is there any way to solve it fast :/
