### ISSUE TITLE
How to access assets with proxy?

### ISSUE THREAD

**Issue by varatep** [kriasoft/react-starter-kit#1121]
App is hosted at https://domain.com/app but it tries to access assets from https://domain/ at the top level.

**Comment by frenzzy** [comment]
[tools/webpack.confg.js => config.output.publicPath](https://github.com/kriasoft/react-starter-kit/blob/fb36e0fb732da65351df5aa0cedf56d9ddaadc1c/tools/webpack.config.js#L28) = `'/app/assets/'`

**Comment by varatep** [comment]
@frenzzy After changing publicPath, when going to a valid route, the components do not render with no errors. Does changing publicPath somehow change rendering?

**Comment by varatep** [comment]
Re-deployed using no `--release` tag for outputs and there is a warning. Referencing #1121
