### ISSUE TITLE
React reuse markup (server rendering) issues

### ISSUE THREAD

**Issue by varatep** [kriasoft/react-starter-kit#1122]
Receiving this warning 
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) iv></div></div><div data-reactid="17"></
 (server) iv></div></div><div class="EyeW-App-root
```

**Comment by varatep** [comment]
This works fine in local environment from `node build/server.js`, but when it is run on the server side, with exact same methods, it results in that warning.

**Comment by langpavel** [comment]
This happens when your code yields into different component tree (or same tree but with different `props`) on server then on client when React re-mounting...

**Comment by langpavel** [comment]
Please, figure it out, write a short description why this happens and then reopen issue if it was tricky :smiling_imp:

**Comment by Shadowman4205** [comment]
Hello i get this similar error too:

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
> 
>  (client) " data-reactid="1"><div data-reactid="2"
>  (server) " data-reactid="1"><!-- react-empty: 2 -

in view source i see this
`div id="app"><div data-reactroot="" data-reactid="1" data-react-checksum="1689853031"><!-- react-empty: 2 --><!-- react-empty: 3 --></div>`

Any suggestion how i can solve this error? Is this because of redux?

**Comment by langpavel** [comment]
@Shadowman4205 This is because your first render on client is not done with exactly same conditions (redux state or client/server conditionals)

**Comment by Shadowman4205** [comment]
Any workaround or similar example?
Sorry but i do not understand well what you mean? 
Do need make changes on component?

**Comment by Shadowman4205** [comment]
Ok as i found the problem is i am using mediaquery of react -responsive. If you know, is there any suggested to pass device width from serverside?
