### ISSUE TITLE
Issue with postcss-partial-import@3.1.0

### ISSUE THREAD

**Issue by rochadt** [kriasoft/react-starter-kit#1123]
If you import a css file from node_modules in the global scope, css selectors are still interpolated. I noticed this because I include styles from highlight.js in my Layout.css:
```
:global {
  @import 'highlight.js/styles/default.css';
}
```
This appears to be a result of the update to postcss-partial-import@3.1.0 introduced in [a55d311](https://github.com/kriasoft/react-starter-kit/commit/a55d311492b82dc6db19f3100d0a1b0b214d8fb9). Reverting back to 2.1.0 seems to work, but I'm not sure what is causing this issue.

**Comment by guokeke** [comment]
@rochadt which your nodejs version?

**Comment by frenzzy** [comment]
ref https://github.com/jonathantneal/postcss-partial-import/issues/35

**Comment by rochadt** [comment]
@guokeke node v6.9.4

@frenzzy Thank you for the reference. Since this issue is being tracked with partial-import, I will close this issue. If anyone else is experiencing this problem, rolling back to 2.1.0 seems to be the only fix as of now.
