### ISSUE TITLE
Multiple Wildcard Routes Under Same Parent Path

### ISSUE THREAD

**Issue by Shadowman4205** [kriasoft/react-starter-kit#1125]
I do not know how to properly formulate the question.  I will try with example.

***1***
```
export default {
  path: '/article',
  children: [     {
      path: '*',
      async action({ path, store }) {
        await store.dispatch(loadPageInfo(path)); 
        const data = store.getState().pagedata;
        return {
          component: <Layout><Header_1 /><Content content={data} /><Section /></Layout>,
        };
      },
    }
  ]
};
```
This working fine.
but i want do the same thing in another folder(With diffent component  Header_2)
The Header_1 and Header_2 is similar but in already existing db i cannot connect the datas from pagedata table so i can get header dynamically (there is no connection bettween these tables). So i need load Header with componentdidmount inside header.
***2***
```
export default {
  path: '/article',
  children: [     {
      path: '*',
      async action({ path, store }) {
        await store.dispatch(loadPageInfo(path)); 
        const data = store.getState().pagedata;
        return {
          component: <Layout><Header_2/><Content content={data} /><Section /></Layout>,
        };
      },
    }
  ]
};
```
Is this possible somehow?

**Comment by frenzzy** [comment]
just use condition:
```js
export default {
  path: '/article',
  children: [
    {
      path: '*',
      async action({ path, store }) {
        await store.dispatch(loadPageInfo(path)); 
        const data = store.getState().pagedata;
        const Header = condition ? Header_1 : Header_2;
        return {
          title: data.title,
          component: <Layout><Header /><Content content={data} /><Section /></Layout>,
        };
      },
    },
  ],
};
```

**Comment by Shadowman4205** [comment]
Is this the only option? Because still i have to make the condition more complex. The problem is that i do not have any link assocation with header data and page data. Thats why i wanna do something like this. Is this  not possible, i will try with condition.  But my condition will be something like this
const Header = condition ? Header_1 : condition2  ? Header_3 : condition3  ? Header_4;
: condition4 ? Header_5;

**Comment by frenzzy** [comment]
There are many options, depends on your needs. As I understand you want to display different headers depending on page data field, so my suggestions about that:
```js
let Header = Header_Default;
switch (data.pageType) {
  case 'type1':
    Header = Header_1;
  case 'type2':
    Header = Header_2;
  // ...
}
```
or
```js
const Header = require(`./headers/${data.pageHeaderComponentName}.js`).default;
```

**Comment by Shadowman4205** [comment]
Yeah i know, this would be good solution if i had direct connection between page data and header data. But the problem is that i do not have. In condition i have to check 2 o 3 datas of page to get header. But thank you i wll try this. And see how it is going.
