### ISSUE TITLE
I got a warning blew,should I ignore this?

### ISSUE THREAD

**Issue by vagusX** [kriasoft/react-starter-kit#114]
sudo npm install
npm WARN package.json node-libs-browser@0.5.0 No repository field.
npm WARN unmet dependency /home/vagusx/source/project/react-starter-kit/node_modules/protractor requires lodash@'~2.4.1' but will load
npm WARN unmet dependency /home/vagusx/source/project/react-starter-kit/node_modules/lodash,
npm WARN unmet dependency which is version 3.8.0

**Comment by koistya** [comment]
Yep, safe to ignore.
