### ISSUE TITLE
Deploying a plain bundle.js on a JBOSS web server 

### ISSUE THREAD

**Issue by jaivardhanbhati** [kriasoft/react-starter-kit#1140]
I have a landing page (some.html) pointing to bundle.js . Under the chrome debugger I do see all my files getting loaded properly but still I get errors in the code like 'this' is undefined etc .

Please note : 
1. I don't have node / npm / webpack installed 
2. I am not running webpack-dev-server running on this server 

- What is the proper way to deploy / refer a bundle.js file ? 
- Do I need to install webpack globally on this server ? 

I need to know is it possible to just get the functionality of my SPA through a bundle.js being pointed from index.html provided that bundle.js was generated using a webpack on my dev-machine ?

**Comment by frenzzy** [comment]
1. Generate [static html files of all pages](https://github.com/kriasoft/react-starter-kit/blob/4bc6f834534c254daf0a6f12785ea45f3e6c44bb/tools/render.js#L15-L32) with js bundle:
    `yarn run build -- --static --release`
2. Deploy to your server only the content of `build/public` folder

**Comment by jaivardhanbhati** [comment]
Its the same as npm run and does build me the same bundle.js under my dist folder . But if I reference this bundle.js in an index.html on my webserver - things don't work

**Comment by frenzzy** [comment]
Put your files to the root: `build/public/*` => `example.com/*`
and not into sub folder `example.com/some/sub/folder/*`

**Comment by langpavel** [comment]
Sorry, I'm not sure this belong here. But if you solve this, leave a comment. Thanks!

**Comment by jaivardhanbhati** [comment]
Thanks - I should have closed it .
