### ISSUE TITLE
Git Pre-commit Hook: error on eslint --fix

### ISSUE THREAD

**Issue by mantap123** [kriasoft/react-starter-kit#1143]
Hi there...
I am cloning the master branch at Feb 22th 2017.
But I am facing error when want to commit changes to my private repository.

Screenshots:
<img width="547" alt="jepretan layar 2017-02-22 pada 9 51 59 am" src="https://cloud.githubusercontent.com/assets/23210857/23195235/c37b7ff8-f8e4-11e6-8d4a-dfd7477d886b.png">

<img width="553" alt="jepretan layar 2017-02-22 pada 9 52 19 am" src="https://cloud.githubusercontent.com/assets/23210857/23195238/c7bbbd12-f8e4-11e6-967e-8882f755c457.png">

**Comment by frenzzy** [comment]
Why you want to commit compiled file?

**Comment by langpavel** [comment]
You can force commit by git commit -n but question is same, why commit this ugly compiled file
