### ISSUE TITLE
How to get current user data in server?

### ISSUE THREAD

**Issue by alfiepoleon** [kriasoft/react-starter-kit#1146]
I'm using the redux branch and I can get the user from redux in the client, how can I do the same in the server, for instance before sending a document from the database I check if the current user is the owner, or after uploading a document, I get the owner details from the logged in user from server other than uploading from the client since I think someone can tamper with that

**Comment by jonirrings** [comment]
have you maintain a session for the logined user ?
maybe server session will solve your problem.

**Comment by langpavel** [comment]
`req.user`

**Comment by alfiepoleon** [comment]
@langpavel it returns undefined in my case

**Comment by frenzzy** [comment]
`req.user` will be available after [these lines](https://github.com/kriasoft/react-starter-kit/blob/e73083eb1d50a4035bf5d11803a822fbdd41289b/src/server.js#L49-L73) only if user is authorized.

**Comment by alfiepoleon** [comment]
@frenzzy thank you, I had placed authentication routes below the other api routes, it works now.
