### ISSUE TITLE
Webpack: speed up bundling time

### ISSUE THREAD

**Issue by wkrdixon** [kriasoft/react-starter-kit#1149]
When I make any change to a CSS file, I don't see the update in my browser for approximately 1 second.  This feels like very slow feedback.

What is the best way to improve this so it is near instant?   Is/does vendor.js need to be recompiled on every change? 

```webpack: Compiling...

webpack building...
webpack built 3c6e2ea029cdebeb13d6 in 870ms
Child client:
    Time: 870ms
                                       Asset      Size  Chunks                    Chunk Names
                                   client.js    214 kB       3  [emitted]         client
                                   vendor.js   1.42 MB       4  [emitted]  [big]  vendor
        3.5494f35aa8c40cbc7d77.hot-update.js   4.56 kB       3  [emitted]         client
        5494f35aa8c40cbc7d77.hot-update.json  43 bytes          [emitted]         
                               client.js.map    148 kB       3  [emitted]         client
    3.5494f35aa8c40cbc7d77.hot-update.js.map   5.27 kB       3  [emitted]         client
                               vendor.js.map   1.78 MB       4  [emitted]         vendor
Child server:
    Time: 880ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  233 kB       0  [emitted]  server
    ../../server.js.map  199 kB       0  [emitted]  server
webpack: Compiled successfully.
```

**Comment by langpavel** [comment]
> Is/does vendor.js need to be recompiled on every change?

Yes, because styles are inside. 1s is near instant :-)

**Comment by iDVB** [comment]
In all seriousness though, the issue is talking about speeding up build times. Currently our local and prod builds are taking about 4-5 mins on average, which is a bit much. Even more so, since its all CI/CD'd up. Seems like there must be something we can individually do to tighten up the bolts?

**Comment by ulani** [comment]
@wkrdixon   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
