### ISSUE TITLE
Back button doesn't work on redirect.

### ISSUE THREAD

**Issue by Jaikant** [kriasoft/react-starter-kit#1154]
Maybe I should be posting this issue for universal-router.

My server is redirecting a user if he isn't authenticated to the login route along with a query string. 

On the client, the back button stops functioning on the login page after the redirect.

So if the user doesn't want to login and he clicks the back button - but it doesn't work.

**Comment by frenzzy** [comment]
Redirect from `/admin` (link in the footer) page to `/login` and browser's back button works fine in master branch, so probably you do something wrong.

For proper isomorphic redirect you need to just [`return { redirect: '/login' }`](https://github.com/kriasoft/react-starter-kit/blob/057b5ca1cdd2580559c44311cd1d6134e03e17f2/src/routes/admin/index.js#L22) from your route.

**Comment by Jaikant** [comment]
I am redirecting from my server after checking for authentication. Do you suggest that I check for authentication on the route instead? (This will ensure the state of the history module so I get a proper redirect?) 

I think I am convinced, but just to be doubly sure as this is related to authentication -This is what I am doing on the server
  - Check if the user is authenticated when he accesses any route on "/guide/*"
  - If not authenticated, I append a query string of the url he wants to access and redirect him to the login page. (The back button doesn't work if the user decides not to login)
 - I append a query string, so after Facebook login, the user is redirected to the page he initially intended to view.

`function checkAuthentication(req,res,next){
    if(req.isAuthenticated()){
        //if user is logged in, req.isAuthenticated() will return true
        next();
    } else{
        let redirectto = "/login?url=" + req.url;
        res.redirect(redirectto);
    }
}

app.get('/guide/*',checkAuthentication,function(req,res,next){
    //do something only if user is authenticated
    next();
});`

**Comment by Jaikant** [comment]
Hats off to you sir! The solution works seamlessly.
