### ISSUE TITLE
Cant resolve modules

### ISSUE THREAD

**Issue by kuongknight** [kriasoft/react-starter-kit#1155]
In webpack config we have: `resolve: {
    modules: [path.resolve(__dirname, '../src'), 'node_modules'],
  }`
But when `import Link from 'components/Link'`
Found error:
`Error: Cannot find module 'components/Link'`

**Comment by frenzzy** [comment]
You need to explicitly specify this option for client and server config separately, because webpack mutates this section =/
```js
// tools/webpack.config.js

// ...

const clientConfig = {
  // ...
  resolve: {
    modules: [path.resolve(__dirname, '../src'), 'node_modules'],
  },
  // ...
};

const serverConfig = {
  // ...
  resolve: {
    modules: [path.resolve(__dirname, '../src'), 'node_modules'],
  },
  // ...
};

// ...
```

**Comment by kuongknight** [comment]
currently we have:
`const config = {
resolve: {
    modules: [path.resolve(__dirname, '../src'), 'node_modules']
  }
}
const clientConfig = {
  // ...
  resolve: { ...config.resolve },
  // ...
};

const serverConfig = {
  // ...
  resolve: { ...config.resolve },
  // ...
};
`
But it not working

**Comment by kuongknight** [comment]
Please help me resolve this issue :)

**Comment by frenzzy** [comment]
If you want to use absolute paths to your modules you also need to mark your modules as internal [here](https://github.com/plyo/plyo.web/blob/a8207594242717989771ec901bbc1904526f9bd0/tools/webpack.config.js#L285-L293) for server-side bundle or copy them manually to the build folder so that `build/server.js` can find them.

**Comment by Kohze** [comment]
> If you want to use absolute paths to your modules you also need to mark your modules as internal here for server-side bundle or copy them manually to the build folder so that build/server.js can find them.

the link is not working - have a similar issue with installing react-office-fabric and then not resolving because of the /src/ in between the path resolve.

**Comment by langpavel** [comment]
@frenzzy Private links should not be here :-)

**Comment by langpavel** [comment]
@Kohze Are you still interested or this can be closed?

**Comment by frenzzy** [comment]
oops, was a wrong link)

**Comment by kuongknight** [comment]
@frenzzy can you write sample internals config for src folder?

**Comment by frenzzy** [comment]
sure, for example if you want to make `import Header from 'src/components/Header'` works:

```js
// tools/webpack.config.js

// ...

const clientConfig = {
  // ...
  resolve: {
    modules: [path.resolve(__dirname, '..'), 'node_modules'],
  },
  // ...
};

const serverConfig = {
  // ...
  resolve: {
    modules: [path.resolve(__dirname, '..'), 'node_modules'],
  },
  externals: [
    /^\.\/assets\.json$/,
    (context, request, callback) => {
      const isExternal =
        request.match(/^[@a-z][a-z/.\-0-9]*$/i) &&
        !request.match(/^src\//i) && // module is not external if starts with `src/`
        !request.match(/\.(css|less|scss|sss)$/i);
      callback(null, Boolean(isExternal));
    },
  ],
  // ...
};

// ...
```

**Comment by comerc** [comment]
... and solution for Atom [js-hyperclick](https://atom.io/packages/js-hyperclick):

![2017-03-17 12 30 23](https://cloud.githubusercontent.com/assets/1025241/24037210/0f325986-0b0e-11e7-8e6e-b6fd689aaa13.png)
