### ISSUE TITLE
Rendering App Component Client and Server Side

### ISSUE THREAD

**Issue by dbrrt** [kriasoft/react-starter-kit#1157]
Would it be possible to render the App component rendered Server Side, on the client too to make it easier to create a Single Page Application ?

**Comment by jonirrings** [comment]
isn't it now? do you mean "isomorphic"? it is isomorphic already.

**Comment by dbrrt** [comment]
By that I mean the server renders the component, but the client can't interact with it. It needs to be rendered on the client too to allow interaction.

**Comment by langpavel** [comment]
@dbrrt Of course client can interact with it! Check your browser console if you see errors and if client bundle is loaded correctly.
