### ISSUE TITLE
Improving extractMessages.js function(s)

### ISSUE THREAD

**Issue by Pomanks** [kriasoft/react-starter-kit#1158]
Hi guys,

Here's my request, I'd like to improve the `extractMessage.js` file with some order in the result.

Now it puts all the extracted messages in a single `.json` file for each locale available... but when you have a lot of text in your website it becomes a real mess to find your way inside it.. 😩
So I'd like to replace the actual result and separate it by component/container where the function found these messages. The problem is.. I don't have any idea on how to do it (for now) and mostly, I wonder if anyone has ever done it ? @langpavel maybe ? (It would avoid me some work as you may know we developers are kind of lazy.. 😜)

So if you have any idea, solution, advice, or anything else.. Post it right here please, I thank you in advance !  😉

I'll keep you posted if I find a solution BTW ! 👍🏻

**Comment by langpavel** [comment]
Hi. Extracting messages from container to standalone file is basic usage of [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl).

As you can see, recommended configuration creates extra JSON for each file.
Try play with babel plugin configuration. You can possibly drop `extractMessages` step away.
If you find something awesome, please, don't keep it for yourself only, share your results there.

Thanks for asking! :+1:

**Comment by Ank49** [comment]
Well.. this is pretty much what I want to do but I still got one problem, the [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl) output is only one `.json` file per component/container. I still want to have two different `.json` files like `fr-FR.json` and `en-US.json`

I also noticed that the extractMessages function needs the files to properly work, it doesn't creates them, am I right ? I'm looking for a way to make that happen and in the same time, do you know how I can include the path in the result ?

For exemple if I have a file in : 
`components`
`-/About`
`--/messages.js`

I'd like to have as a result something like : 
`messages`
`-/components`
`--/About`
`---/fr-FR.json`
`---/en-US.json`


Anyway, for those who just need to have one `.json` file per component/container, you just need to do the following stuff.
In `webpack.config..js`, find the following refs : 

`[
              'react-intl', {
                enforceDescriptions: INTL_REQUIRE_DESCRIPTIONS
              }
]`

and then add this line inside the braces :  `"messagesDir": "./src/messages/"` with your custom path output

**Comment by langpavel** [comment]
Well @Ank49 

> Well.. this is pretty much what I want to do but I still got one problem, the babel-plugin-react-intl output is only one .json file per component/container. I still want to have two different `.json` files like `fr-FR.json` and `en-US.json`

I think, purpose is to extract only default messages. You can create files with custom locales yourself, by copying and maintaining it yourself.
Look at [react-intl-webpack-plugin](https://github.com/Ognian/react-intl-webpack-plugin), possibly in source and try to use/patch this stuff.

I'm sure this is good direction... About loading.. this can be tricky... You can create some decorator like `withStyles` is to collect info about all needed messages to load, or you can load all messages for chosen language, like current implementation do.
Of course, you should setup caching on server, this can be easier if you load messages statically, not through GraphQL endpoint like current implementation do..

**Comment by langpavel** [comment]
@Ank49 Did you find your path?

**Comment by Ank49** [comment]
@langpavel not yet, I didn't had the time to dive into it.. 😔

**Comment by ulani** [comment]
@Pomanks   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
