### ISSUE TITLE
Every major issue I encounter is reducible to server side rendering. Turn it off?

### ISSUE THREAD

**Issue by curtd59** [kriasoft/react-starter-kit#1159]
This boilerplate is promising but terribly unstable.  It's unstable because the underlying technologies are relatively unstable. But almost every crisis I run into is reducible to the fragility of server side rendering.  

We need to tag routes for client or server side rendering.

**Comment by frenzzy** [comment]
Can you please explain which exactly problems do you have with server-side rendering?
Maybe we need some docs to help you to avoid issues...

**Comment by langpavel** [comment]
Hi @curtd59
I have `NoSSR` coponent implemented exactly like this:

```js
/* @flow */

import React, { PropTypes } from 'react';

declare var __BROWSER__: boolean;

function renderValue(value) {
  let result = value;
  if (typeof result === 'function') {
    result = result();
  }
  if (typeof result === 'string') {
    result = <span>{result}</span>;
  }
  return result;
}

export default class NoSSR extends React.Component {

  static propTypes = {
    children: PropTypes.oneOfType([PropTypes.node, PropTypes.func]),
    onSSR: PropTypes.oneOfType([PropTypes.node, PropTypes.func]),
  };

  static defaultProps = {
    children: null,
    onSSR: null,
  };

  state = {
    canRender: __BROWSER__ && window.RSK_MOUNTED,
  };

  componentDidMount() {
    const { canRender } = this.state;
    if (canRender) return;
    // eslint-disable-next-line react/no-did-mount-set-state
    this.setState({ canRender: true });
  }

  render() {
    const { children, onSSR } = this.props;
    const { canRender } = this.state;
    return canRender ? renderValue(children) : renderValue(onSSR);
  }
}
```

It works nicely, note you should set `window.RSK_MOUNTED` after initial render, this prevents React checksum warning.
If you are interested I can prepare PR for master. @koistya @frenzzy?

**Comment by tim-soft** [comment]
I will need to try this method

Here is an example of something that breaks with SSR
https://github.com/auth0/lock/issues/592

**Comment by ulani** [comment]
@curtd59   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
