### ISSUE TITLE
How to implement routing and navigation

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#116]
##### [docs/recipes/how-to-implement-routing.md](https://github.com/kriasoft/react-starter-kit/blob/master/docs/recipes/how-to-implement-routing.md)
- [x] Basic routing
- [x] Asynchronous routes
- [x] Parametrized routes
- [x] Setting page title and meta tags
- [ ] Redirects
- [ ] Code splitting
- [ ] Nested routes
- [ ] Integration with Flux
- [x] Server-side rendering

See also [Universal Router](http://slides.com/koistya/universal-router/fullscreen)
##

**Comment by Sunil6591** [comment]
Why can just use ```react-router```

**Comment by 9mm** [comment]
Yeah I was wondering the same thing, how do I use `react-router`? This isn't vert documented as is a bit challenging to figure out.

**Comment by MattReimer** [comment]
I'm trying to figure out how to redirect based on an action. 

Most of the posts Ive seen about `react-router` suggest getting the router from the `this.context` object but mine is empty. Any ideas?

**Comment by subodh-malgonde** [comment]
@koistya Any idea when the docs would be updated? Especially the docs for nested routes and code splitting.

**Comment by karlstanton** [comment]
+1

**Comment by zomars** [comment]
I agree with the `react-router` approach.

**Comment by FakhruddinAbdi** [comment]
react-router  +1

**Comment by zazapeta** [comment]
react-router +1

**Comment by zazapeta** [comment]
Nice demonstration :+1:

**Comment by rnjailamba** [comment]
@koistya  please update docs with Redirects example.

**Comment by yookore** [comment]
What do we need to do to encourage the completion of these docs?

**Comment by langpavel** [comment]
I'm sure something of goals are met. Other are described precisely in standalone issues. Can everybody interesting into this update, reference other issues?

**Comment by langpavel** [comment]
@koistya I think more or less all goals mentioned here are achieved, except redirects.

Code splitting is demonstrated in `feature/react-intl`, not in router, but technically it is same..

**Comment by ulani** [comment]
@koistya  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
