### ISSUE TITLE
Async store.getState().intl.locale 

### ISSUE THREAD

**Issue by Shadowman4205** [kriasoft/react-starter-kit#1163]
I am using react starter kit with redux and intl.

```js
export default {
  path: '/article',
  children: [
    {
      path: '*',
      async action({ path, store }) {
        const language = store.getState().intl.locale;
        await store.dispatch(loadPageData( language,path));
        const data = store.getState().pagedata;
        return { 
          title: data.title,
          component: <Layout><Content content={data} /></Layout>,
        };
      },
    }
  ]
};
```
The problem is that when i change language  using 
```js
onClick={async (e) => {
           e.preventDefault();
          await setLocale({ locale });
        }}
```
first get called SET_LOCALE_START action, then const language = store.getState().intl.locale; 
then SET_LOCALE_SUCCESS and the result i am using language from previeus state. Any help, suggestion?

**Comment by langpavel** [comment]
Oh, I spotted this.
And my solution is [this](https://github.com/kriasoft/react-starter-kit/blob/feature/react-intl/src/components/App.js#L69..L73). Are you sure you have this lines included? ... Yes.. but this change does not touch router..

But this is clue... not solution..

**Comment by Shadowman4205** [comment]
Yes i have got this lines,  for now i just did this
```
  let language = store.getState().intl.**newLocale**;
  if(language==null) {language=store.getState().intl.locale}
```

**Comment by langpavel** [comment]
@Shadowman4205 But I guess, this is not enough.. You should listen for locale change by `store.subscribe` and then refetch, rerender.. Or you can handle fetching at component level, then you will not need handle fetching data in route which is too early for your use case

**Comment by Shadowman4205** [comment]
Yeah i am trying avoid calling actions from components. For the moment i will keep like this.
Also  about react intl, why it is stopped working when i am using connect in same component? Is this general issue?

**Comment by langpavel** [comment]
> about react intl, why it is stopped working when i am using connect in same component? Is this general issue?
I think it works, but it works differently then you think @Shadowman4205.
`<App>` is rendered after router,
so when you change locale, router will not re-execute, but everything under App is re-rendered correctly. This behavior was not changed from very first implementation..

**Comment by Shadowman4205** [comment]
I do not understood what you mean exactly. At the moment i just passing props to component from routes/home/index.js, so i do not have pick data from redux store with connect.

**Comment by Shadowman4205** [comment]
For example i have got this 

```
import React, { PropTypes } from 'react';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import * as actions from '../actions/test';
import s from './Test.css';
import { defineMessages, FormattedMessage } from 'react-intl';

const messages = defineMessages({
  heading: {
    id: "test.heading",
    description: "Heading for Test",
    defaultMessage: "Test this",
  }
});

class ContactSection extends React.Component {
  componentDidMount(){
    this.props.actions.loadTest();
  }

  render() {
    return (
      <div className={s.test + " container"}>
        <h2 className={s.centertext}>
          <div className={s.twolines}>
            <span><FormattedMessage {...messages.heading} /></span>
          </div>
        </h2>
      </div>
    );
  }
}

function mapStateToProps(state, ownProps) {
  return {
    test:state.test,
    language:state.intl.locale
  };
}

function mapDispatchToProps(dispatch) {
  return {
    actions: bindActionCreators(actions, dispatch)
  };
}
const EnhancedContent = connect(mapStateToProps, mapDispatchToProps)(Test);
export default withStyles(s)(EnhancedContent);
```
By changing language defaultMessage do not change to given language message.
But if i remove the part with connect, it will.

**Comment by langpavel** [comment]
Sorry, I don't know, can you mark which connect stuff does not work for you?

**Comment by Shadowman4205** [comment]
I just put key={locale} on App.js, and it is just rerendering but it is working.
Like in the example connect is working for me but this not <FormattedMessage {...messages.heading} />,but if i remove the part with connect <FormattedMessage {...messages.heading} /> changing.

**Comment by Shadowman4205** [comment]
@langpavel Can you show me how i can pick defaultLocale from subdomain. 
What i mean mean is if my page with en language is en.test.com, for de language is de.test.com, for ru is 
ru.test.com. How can i implement this? So with language pick i will reload the app.

**Comment by langpavel** [comment]
Subdomain prefix looks like good idea BUT you then must use only one domain for resources to allow HTTP layer caching. Different domain forces you to setup various policies like CORS.

More easy way is to have URL prefix like `/en/`...

Most easy way is enforce page reload by using `<a href="?lang=en">English</a>`. This will trigger new HTTP request, set language cookie and rerender page.

I'm not sure why your nested `<FormattedMessage />` elements are not rerendered, but it can be because this:

> Calling `forceUpdate()` will cause `render()` to be called on the component, skipping `shouldComponentUpdate()`. **This will trigger the normal lifecycle methods for child components, including the shouldComponentUpdate()** method of each child. React will still only update the DOM if the markup changes.

I will change this to use [`react-deep-force-update`](https://github.com/gaearon/react-deep-force-update)

**Comment by langpavel** [comment]
@Shadowman4205 Try `git fetch && git cherry-pick 8c3189ea6fc8cda20d3f8c0d931575163e9ee523`
[See changes](https://github.com/kriasoft/react-starter-kit/commit/8c3189ea6fc8cda20d3f8c0d931575163e9ee523)
It uses react-deep-force-update so nested components should be updated too. I believe this will help you

**Comment by Shadowman4205** [comment]
Thanks for suggestions and help.
@langpavel Can you guide me how i use Subdomain prefix?
Lets  say i have  en.test.com, de.test.com, ru.test.com that uses same src of webapp.
i will use <a> tag  for language switch. How i can set locale from current sub-domain(or pick it from hostname)
to set language. In my thought, i think i must change intial locale in server.js. But how i pick the subdomain? 
Sorry for inconvenience.

**Comment by langpavel** [comment]
@Shadowman4205 Sorry, I cannot guide you to subdomain. It is out of scope and as I said you will have much more configuration with this, not only in RSK but with server configuration as well:
* You should serve static assets from only one domain
* This implies CORS setup
* You must then use domain qualified URL paths for resources
* Where to put GraphQL endpoint? on *common* domain
* Check all the cookies, set domain correctly
* much more questions here...

**Comment by Shadowman4205** [comment]
Thanks @langpavel  i will make more research and for now i will your 2ond suggested option.
