### ISSUE TITLE
entry point in react starter

### ISSUE THREAD

**Issue by rajkundan** [kriasoft/react-starter-kit#1164]
find ans asap

**Comment by Ank49** [comment]
You might wanna be a bit more specific in your.. is that even a question ? 🤔

**Comment by rajkundan** [comment]
hi,kriasoft

thanks for response,
 yes i want to know, which is the main rendering page.
 because app.js is exported somewhere else then where is index.js for whole
app.As i have seen en every app from begining of my knowledge in React.
 please reply asap.

thanks
raj kundan

**Comment by rajkundan** [comment]
import { Router, Route, Link, browserHistory, IndexRoute  } from 'react-router'
import {Provider} from 'react-redux';
import thunk from 'redux-thunk';
import {createStore,applyMiddleware} from 'redux';

const store = createStore(
	(state ={}) => state,
	applyMiddleware(thunk)
	);



ReactDOM.render((
   <Provider store={store}>
   <Router history={browserHistory} routes={routes} />
   </Provider>), document.getElementById('root'))
hey where should i write the code above in react starter kit  i want to implement action dispatcher i think this should be in index.js but whr it is 
                                            please let me out out here.

**Comment by ucay** [comment]
If you use redux, you can follow this docs: [How to Integrate Redux](https://github.com/kriasoft/react-starter-kit/blob/master/docs/recipes/how-to-integrate-redux.md)

**Comment by rajkundan** [comment]
i need to know  the first page of of the application of react starter kit
 just like other app as index.js

**Comment by rajkundan** [comment]
i need to know  the first page of of the application of
react-starter-kit-master  just like other app as index.js
   please help me iam stuck over her nd not able to do any thing.

**Comment by rajkundan** [comment]
i need to know  the first page of of the application of
react-starter-kit-master  just like other app as index.js
   please help me ,* I *am stuck over here nd not able to do any thing

**Comment by langpavel** [comment]
Sorry, no place in issues for baby steps. Entry points are two, for server it is `src/server.js`, for client it is `src/client.js`, but you should know structure of entire app.
