### ISSUE TITLE
browserSync doesn't refresh IE 11

### ISSUE THREAD

**Issue by OutsourcedGuru** [kriasoft/react-starter-kit#1167]
From: [getting-started guide](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md)
node: v6.9.5
yarn: 0.21.3
(Presumably I pulled the `master` branch here in the next step)
Installed:  `git clone -o react-starter-kit -b master --single-branch https://github.com/kriasoft/react-starter-kit.git react-app`
Next step:  `yarn install`
Finally:  `yarn start`
OS: Windows 7 Professional 64-bit
IE URL automatically started:  http://localhost:3001/

Bring up second URL for `browserSync`:  http://localhost:3002/
Refreshing first tab and visiting second indicates that `IE - (11.0)` is attached.

Bring up http://_IPADDRESS_:3001/ from iPad.
browserSync indicates `Mobile Safari - (9.0)` is attached.

1. With everything running, edit `src\components\Header\Header.js` to change the title
2. Note that Safari on the iPad instantly updates with the new information
3. **Note that IE 11 does not.**
4. Press F5 on IE 11 and see the update.
5. Return to browserSync tab and verify that both browsers are still listed.

**Comment by langpavel** [comment]
Sorry, please report this to browser-sync team.
