### ISSUE TITLE
"Not Found" link in Footer

### ISSUE THREAD

**Issue by OutsourcedGuru** [kriasoft/react-starter-kit#1168]
![notfound](https://cloud.githubusercontent.com/assets/15971213/23776240/ee3c20ae-04e1-11e7-9e2f-acb08432f35d.png)

Still looking through all this so I'm not sure if the `src\components\Footer\Footer.js` is generated or not.  Regardless, it looks like the `src\routes\notFound` collection is making its way into the bullet-separated list at the bottom of the page.

**Comment by ucay** [comment]
I think it's an example of unlisted route that should show 404 Page Not Found.
