### ISSUE TITLE
How to configure text editors and IDEs

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#117]
How to configure text editors and IDEs to work with React.js, ES6+, JSX, Babel, ESLint...

- [x] How to configure WebStorm
- [x] How to configure Atom
- [x] How to configure SublimeText

See [/docs/how-to-configure-text-editors.md](https://github.com/kriasoft/react-starter-kit/blob/master/docs/how-to-configure-text-editors.md)

**Comment by koistya** [comment]
[![image](https://cloud.githubusercontent.com/assets/197134/7723510/db493f4c-fef1-11e4-8055-eb47f5f79d86.png)](https://twitter.com/katyaprigara/status/600966343190511616)

**Comment by stupidisum** [comment]
Hello, now we have our .eslintrc moved into package.json.
How can we configure editors and IDEs then?

**Comment by koistya** [comment]
@stupidisum editors use `eslint` npm module behind the scene which is capable of reading configuration from `package.json`. Have you tried that?

**Comment by lukemt** [comment]
How about visual studio code?
