### ISSUE TITLE
cannot run npm run build after installing dependencies with --prod

### ISSUE THREAD

**Issue by belens** [kriasoft/react-starter-kit#1177]
When running `yarn install --prod ` followed by `npm run build` I am lacking dependencies that are present in devDependencies.

Is the prod/dev dependency split intentionally made without supporting the command `npm run build` or should I submit a pull request that fixes this?

**Comment by langpavel** [comment]
Uff.. you must install all dependencies for build. Then you should deploy result from `yarn build -- --release` to production.
Build process will create new `package.json` inside `build` directory. It will carry in `(`all`|`only production`)` needed dependencies listed in `dependencies` in root/original `package.json`

**Comment by langpavel** [comment]
NOTE: there is `yarn deploy` task, look how it works inside `tools/` dir.
