### ISSUE TITLE
Sass won't run @import directive

### ISSUE THREAD

**Issue by thathurtabit** [kriasoft/react-starter-kit#1178]
Hello.

Forgive my lack of knowledge with Webpack here, but hopefully this can help others out.

The problem is running an @import directive inside components/variables.scss (changed from variables.css after the steps below) returns the error:

`Module build failed: Error: Failed to find 'myscssfile'.`

So, in: [Getting Started](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md#quick-start)

I follow steps **1, 2, 3** (so far so good)

And then try to get Sass working through: [How to use Sass](https://github.com/kriasoft/react-starter-kit/blob/master/docs/recipes/how-to-use-sass.md#how-to-use-sassscss)

There I follow steps **1, 2, 3** (seems to be going ok).

But when I try to use an `@import "scss/myscssfile";` from the `components/variables.scss` file (I created the folder/file `scss/_myscssfile.scss` inside of the components folder) it returns the error:

`Module build failed: Error: Failed to find 'scss/myscssfile'.`
Or
`Module not found: Error: Can't resolve 'scss/_myscssfile.scss'` (when trying to reference the full file name.

It must be something simple I've overlooked. Thank you very much for any help.

**Comment by langpavel** [comment]
Please, use full file name when referencing different files then `*.js`.
Also ensure that you have right tooling setup in `tools/webpack.config.js`.
If you are still in trouble, try ask on gitter.im, right, as `README.md` says

**Comment by thathurtabit** [comment]
Thanks, I'll try gitter.im, but just to be clear, this problem seems to occur out-of-the-box following these steps (_the only .js files I edit is exactly as stated in your docs in the following steps_):

> So, in [Getting Started](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md#quick-start)
> I follow steps 1, 2, 3 (so far so good)
> And then try to get Sass working through: [How to use Sass](https://github.com/kriasoft/react-starter-kit/blob/master/docs/recipes/how-to-use-sass.md#how-to-use-sassscss)
> There I follow steps 1, 2, 3 (seems to be going ok).

I then change the file `src/components/variables.css` to `src/components/variables.scss`, which seems ok, but from that point I want to use **@import** to call in either `node_modules` `*.scss` or just reference any other `*.scss` file, but each time it just results in errors:

`Module build failed: Error: Failed to find 'scss/myscssfile'.`
Or
`Module not found: Error: Can't resolve 'scss/_myscssfile.scss'` (when trying to reference the full file name.

I presume it must be something simple as I'm still in the basic set-up stage. Thanks for any help.

**Comment by frenzzy** [comment]
Unable to reproduce, sass imports works fine for me when I follow the [docs](https://github.com/kriasoft/react-starter-kit/blob/master/docs/recipes/how-to-use-sass.md#how-to-use-sassscss).

**Comment by thathurtabit** [comment]
Seem this may have been down to an unknown error on my side. Although it seems to have something to do with relative paths or using ~
