### ISSUE TITLE
loading jQuery and simulating API calls 

### ISSUE THREAD

**Issue by ssmlee04** [kriasoft/react-starter-kit#118]
Hi everyone.  Currently I have a API server running and I'd like to configure this app a bit so it can be act as a frontend of my website. 

My thinking is that I have to import jQuery into my components so that I can do $.get, $.post and interact with my API serv.er

am I thinking correctly?  Thanks.

**Comment by koistya** [comment]
Alternatively you can use `superagent` (http client) library as follows:

```js
let http from 'superagent';

http.get('/api/data', (err, res) => {
  if (err) {
    throw new Error(err);
  }
  console.log(res);
});
```

**Comment by ssmlee04** [comment]
yes I can import http this way.  But what if my API server is at port 8000 and frontend (react) server running at 3000? I tried to do http.get('http://localhost:3000/api/data', ... and it gives me an error message that says XMLHttpRequest cannot load http://localhost:3000/apis..

**Comment by mychaelgo** [comment]
@koistya  can you give me full example using superagent? Thank you

**Comment by lycandjava** [comment]
Is there a solution to this problem

**Comment by koistya** [comment]
Here is an example:

[src/Router.js#L28](https://github.com/kriasoft/react-starter-kit/blob/9a78f9c1c01f50ba73ab52379633ee0058e7bcf3/src/Router.js#L28)
[src/core/HttpClient.js](https://github.com/kriasoft/react-starter-kit/blob/9a78f9c1c01f50ba73ab52379633ee0058e7bcf3/src/core/HttpClient.js)

**Comment by lycandjava** [comment]
in the "HttpClient.js"  file I add a funcion like this :
```javascript
 getJson: (path,value,fail) => new Promise((resolve, reject) => {
    request
      .get(getUrl(path))
      .accept('application/json')
      .end((err, res) => {
        if (err) {
          if (err.status === 404) {
            resolve(null);
          } else {
            reject(err);
          }
        } else {
          resolve(res.text);
        }
      });
  }).then(value,fail)
```
I user it by this :
```javascript
 var result = HttpClient.getJson(Path.getSNSData+"?time="+new Date().getTime(),function(value){
          //  console.log("value success:"+value);
            data.document = eval("("+value+")");
            that.setState(data);
        },function(fail){
            console.log("value fail:"+fail);
        });
```
is this correctly

**Comment by koistya** [comment]
FYI, the HTTP client utility has been refactored and moved to `src/core/fetch`. Sorry, I'm going to close this one as it was remaining open for too long. But feel free to continue the conversation on this thread. You're also welcome to participate in discussions on [Gitter](https://gitter.im/kriasoft/react-starter-kit), [Appear.in](https://appear.in/react), or [StackOverflow](https://stackoverflow.com/tags/react-starter-kit).
