### ISSUE TITLE
ESLint: Unable to resolve path to module 

### ISSUE THREAD

**Issue by comerc** [kriasoft/react-starter-kit#1180]
We have [solution](https://github.com/kriasoft/react-starter-kit/issues/1155#issuecomment-286687023) for absolute path, like this:
```javasript
import MyComponent from 'src/components/MyComponent'
```

It is work fine for `yarn start`, but for `yarn lint`:   
```
Unable to resolve path to module 'src/components/MyComponent'     import/no-unresolved
```

I have solution for my other project (no RSK) with WebStorm:

1) project_dir - Mark Directory as > Resource Root

2) yarn add eslint-import-resolver-webpack -D

3) config/default.js

```
...
	resolve: {
		// We can now require('file') instead of require('file.jsx')
		extensions: ['', '.js', '.jsx', '.scss'],
		alias: {
			src: path.resolve(__dirname, '../src')
		}
	},
...

```

4) .eslintrc.js

```

/* global __dirname */

const path = require('path');

...
	settings: {
		'import/resolver': {
			webpack: {
				config: path.join(__dirname, '/config', 'default.js')
			}
		}
	}
...

```

How to solve this issue for RSK? Please help me.

**Comment by comerc** [comment]
"import/no-unresolved": "off"

(as temporary solution)

**Comment by Stupidism** [comment]
Maybe you should track this project.https://github.com/benmosher/eslint-plugin-import/issues/496

**Comment by Stupidism** [comment]
Aha~ I'm facing a same issue like you
I wanted to do absolute imports with a special prefix(So I can tell what's extenal easily). #1193 
I fixed the mocha test to work with this https://stackoverflow.com/questions/33793504/using-webpack-aliases-in-mocha-tests/42989394#42989394;
Now I don't know how to eslint it.
I used to solve this problem by [eslint-import-resolver-webpack](https://www.npmjs.com/package/eslint-import-resolver-webpack) in another project. However, it seems not working with newest webpack.

**Comment by Stupidism** [comment]
Update: you will face the test problem, too.

**Comment by Stupidism** [comment]
Here is the answer for [eslint](http://stackoverflow.com/questions/41769880/how-to-manually-add-a-path-to-be-resolved-in-eslintrc)
Here is the answer for [mocha](http://stackoverflow.com/a/34425880/5562128)

I think you can add a code recipe for this.

**Comment by karanssj4** [comment]
try this https://gist.github.com/karanssj4/7188528ab36fb4e78c8fc385510f3136

**Comment by MattEhrlich** [comment]
For me it was a case sensitivity issue. I opened the project using `atom .` which gave me path `/desktop/apps/my_app` when i go into atom and open the project manually it's actually at `/Desktop/apps/my_app` this gets rid of the error for me.

**Comment by lucasdu4rte** [comment]
You have the option of this lib here

https://github.com/unconfident/eslint-import-resolver-babel-plugin-root-import

**Comment by skube** [comment]
As @karanssj4 linked to, this seems to be fixed by adding the following to `.eslintrc`
```
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [".js", ".jsx", ".ts", ".tsx"]
      }
    }
  },
```

**Comment by mohammedelzanaty** [comment]
// .eslintrc.js
```
"settings": {
        "import/resolver": {
            "node": {
                "paths": ["src"],
                "extensions": [".js", ".jsx", ".ts", ".tsx"]
            }
        }
    }
```

**Comment by piavgh** [comment]
You can use this package `https://www.npmjs.com/package/eslint-import-resolver-webpack`

```
"settings": {
    "import/resolver": "webpack"
  }
```

**Comment by vianneyguesdon** [comment]
Solved here for TS :
https://stackoverflow.com/questions/55198502/using-eslint-with-typescript-unable-to-resolve-path-to-module

**Comment by saravanakumargn** [comment]
`"settings": {
        "import/resolver": {
          "node": {
            "extensions": [".js", ".ts", ".d.ts"]
          }
        }
      }`

**Comment by dbeetoven** [comment]
> **If you crawled through here from google and have absolute paths when importing resulting in eslint screaming at you NOT FOUND**:
> 
> Use [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import):
> 
> ```
> // App.js
> import { ComponentName } from 'components/ComponentName';
> ```
> 
> ```
> // .eslintrc.js
> module.exports = {
>   ...   
>   "settings": {
>     "import/resolver": {
>       "node": {
>         "paths": ["src"],
>         "extensions": [".js", ".jsx", ".ts", ".tsx"]
>       }
>     },
>   },
> }
great solution thanks

**Comment by milieu** [comment]
I just needed
```
"settings": {
    "import/resolver": {
      "node": {
        "extensions": [".js", ".jsx"]
      }
    },
  }
```
🎉

**Comment by ploth** [comment]
For people using eslint + webpack + single repo

```js
// .eslintrc.js
module.exports = {
  ...   
  "settings": {
    "import/resolver": {
       node: {
         paths: [".", "app", "lib", "functions"], //name the subproject folders here!!!
         extensions: [".js", ".jsx", ".ts", ".tsx"]
      }
    },
  },
}
```

and you may want some overrides
```js
// .eslintrc.js
module.exports = {
  ...   
  overrides: [
    {
      files: ["**/*.stories.tsx", "backend/**/*", "storybook/**/*"],
      rules: {
        "import/no-unresolved": "off",
      },
    },
  ],
}
```

**Comment by vijaybajrot** [comment]
Working Fine.

https://github.com/johvin/eslint-import-resolver-alias

**Comment by Sedose** [comment]
> "import/no-unresolved": "off"

Where to put this? Which file?

**Comment by soujvnunes** [comment]
> > "import/no-unresolved": "off"
> 
> Where to put this? Which file?

`.eslintrc.json` file at app root.

**Comment by salmagomaa** [comment]
For me it is fixed by https://stackoverflow.com/a/71874257/1770571

**Comment by leflores-fisi** [comment]
What if I already have a `baseUrl` and custom aliases for paths in my `jsconfig.json` like this
```js
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@/components/*": ["components/*"],
            "@/styles/*": ["styles/*"],
            "@/public/*": ["public/*"],
            "@/hooks/*": ["hooks/*"]
        }
    }
}
```
After I setup eslint, the import aliases doesn't work anymore, how can I tell eslint to respect the `jsconfig.json` compiler options?

**Comment by umerfarooq69** [comment]
In .eslintrc.json File 

Add this lines

"settings": {
    "import/resolver": {
      "node": {
        "paths": ["src"]
      }
    }
  }
