### ISSUE TITLE
Unexpected Redirect with Passport

### ISSUE THREAD

**Issue by jeanpaulversace** [kriasoft/react-starter-kit#1186]
Hi,

I just implemented the passport-local strategy and am attempting to protect certain routes (e.g. if user is not logged in and navigates to '/home', it will redirect to '/login'). 

```js
app.post('/login', function(req, res, next) {
  passport.authenticate('local', { session: false }, function (err, user, info) {
    if (err) { return next(err); }
    if (info) {
      let errorString = encodeURIComponent(info.message);
      return res.redirect('/login?error='+errorString);
    }
    if (!user) { res.redirect('/login'); }
    const expiresIn = 60 * 60 * 24 * 180; // 180 days
    const token = jwt.sign(user, auth.jwt.secret, { expiresIn });
    res.cookie('id_token', token, { maxAge: 1000 * expiresIn, httpOnly: true });
    res.redirect('/');
  })(req, res, next);
});
```

In the server-side rendering middleware, I check to see if req.user is non-null and pass it into the Universal Router context.
```js
app.get('*', async (req, res, next) => {
  try {
    const css = new Set();

    // Global (context) variables that can be easily accessed from any React component
    // https://facebook.github.io/react/docs/context.html
    const context = {
      // Enables critical path CSS rendering
      // https://github.com/kriasoft/isomorphic-style-loader
      insertCss: (...styles) => {
        // eslint-disable-next-line no-underscore-dangle
        styles.forEach(style => css.add(style._getCss()));
      },
      user: req.user,
    };

    const routeContext = {
      path: req.path,
      query: req.query,
    };

    if (req.user) { routeContext.user = req.user; }

    const route = await UniversalRouter.resolve(routes, routeContext);
```

In my Home component's index.js, I check the route context for the user, and if it is null I redirect to the user to the '/login' path. 

```js
import React from 'react';
import Home from './Home';
import Layout from '../../components/Layout';

export default {

  path: '/',

  async action({ user }) {
    console.log("User from Home index.js: ", user);
    if ( !user ) {
      console.log("Redirecting HAHA!");
      return { redirect: '/login' };
    }

    return {
      title: 'React Starter Kit',
      component: <Layout><Home /></Layout>,
    };
  },

};
```

Now here's the problem - even though I have successfully authenicated through Passport, the app redirects me back to the login page. A quick console log before the redirect verifies that the user is non-null.

![screen shot 2017-03-20 at 1 04 03 am](https://cloud.githubusercontent.com/assets/7007564/24090012/9c19626a-0d0a-11e7-95fa-df4fc7d15e74.png)

As if it could make less sense, when replicate this on the actual server (not the Browsersync proxy) I login successfully and am redirected to the correct ('/home') page.

P.S. On another note, when I hit the actual server, the page failed to load the client.js and the vendor.js files. 

![screen shot 2017-03-20 at 1 08 04 am](https://cloud.githubusercontent.com/assets/7007564/24090013/9c1d22ba-0d0a-11e7-9dfd-5778ecdc0a18.png)

Any help would be appreciated as I've been left scratching my head about this for a while!

**Comment by langpavel** [comment]
I read your question really quickly, but it looks like you don't think about client side. Router will run after your browser script be fetched. So if you see page as you expecting and after it flick away (may be some React errors there about checksums), it is because your router have not same context.

I'm not sure where 404 errors came from.. but you should think about [`feature/redux`](https://github.com/kriasoft/react-starter-kit/blob/feature/redux/src/server.js#L116) as a reference.

**Comment by jeanpaulversace** [comment]
@langpavel Thanks for the quick reply. I just integrated redux, and it seems to have solved my problems. Cheers!
