### ISSUE TITLE
Being able to deploy to multiple remote heroku servers systematically.

### ISSUE THREAD

**Issue by Andriy-Kulak** [kriasoft/react-starter-kit#1187]
So I am able to deploy to heroku from local master to remote master using the default configs that are provided (Thank You so much!) using 'yarn run deploy' and using the remote object is below.

However, how do I make sure that I can also push to different remote branches (let's say heroku dev and prod server) the same way ??

Also how can I push to dev from different local branches? (I need this to test local branch commits on server before merging to master).

I don't want to change the 'const remote' every time I make a change and I am bit confused on how yarn run deploy is currently executing everything. Any help would be greatly appreciated! :-)

```
// Heroku
const remote = {
  name: 'heroku',
  url: 'https://git.heroku.com/<heroku-git>.git',
  branch: 'master',
  website: 'https://<heroku-git>.herokuapp.com',
};
```

**Comment by langpavel** [comment]
~~There are two deploy scenarios, with and without `--release`.~~ Huh this was changed!
@frenzzy ? Why? :-)

But you can patch deploy script by `if(process.argv.includes('--prod'))` condition, for example

**Comment by frenzzy** [comment]
@Andriy-Kulak you can specify deploy slot manually like so:
```sh
$ yarn run deploy -- --slot staging
```
```js
// deploy.js
const slots = ['staging', 'test'];
const slot = process.argv.find((val, i) => process.argv[i - 1] === '--slot') || slots[0];
if (!slots.includes(slot)) {
  console.error('Invalid slot', slot);
  console.error('Must be one of', slots);
  return;
}

const remote = {
  name: 'heroku',
  url: 'https://git.heroku.com/<app>.git',
  branch: `deploy-${slot}`,
  website: 'https://<app>.herokuapp.com',
};

// ...
```

> @frenzzy ? Why? :-)

Because debug mode for local development only (hot reload etc.). If you want to deploy the app that means you want to test or publish it in release mode (it is important to test in release mode).

**Comment by Andriy-Kulak** [comment]
@frenzzy thanks! this works great.

**Comment by Andriy-Kulak** [comment]
@frenzzy @langpavel quick question. why doesn't a simple push to heroku remote master work like with a more typical node.js application? why do we need all these extra spawn commands in deploy.js that I am unfamiliar with?

If there is resource I can find out more about deploying universal/isophormhic apps, feel free to send me the links :-). Part of the reason I ended up staying with heroku is that I had trouble deploying this on AWS EC2.

**Comment by langpavel** [comment]
@Andriy-Kulak Of course, you can build `yarn run build -- --release` and then manually copy content of `build` directory and install packages on server.
Build step will always be needed if you are not a fool, because you need *js* for client.
Server code in this kit is processed by babel and bundled by webpack.
About *extra spawn commands in deploy.js*.. which one?
