### ISSUE TITLE
react-optimize preset breaks my app

### ISSUE THREAD

**Issue by phpeek** [kriasoft/react-starter-kit#1189]
I have a use case where `react-optimize` preset breaks the app when build with `--release`, but everything works correctly when run in development mode with `yarn start` since `react-optimize` is not being applied.

Here's na example use case:

`routes/hello/index.js`

```javascript
import React from 'react';
import Layout from '../../components/Layout';
import Hello from './Hello';

export default {

  path: '/hello/:name',

  async action(context, { name }) {
    const upperCasedName = name.trim().toUpperCase();
 
    // awaits should be here but they don't matter in this case

    return {
      component: <Layout><Hello name={upperCasedName} /></Layout>,
    };
  },
};
```

is being optimized to this form

```javascript
/* harmony default export */ __webpack_exports__["default"] = {

  path: '/hello/:name',

  action(context, { name }) {
    var _ref = _jsx(__WEBPACK_IMPORTED_MODULE_1__components_Layout__["a" /* default */], {}, void 0, _jsx(__WEBPACK_IMPORTED_MODULE_2__Hello__["a" /* default */], {
      name: upperCasedName
    }));

    return _asyncToGenerator(function* () {
      const upperCasedName = name.trim().toUpperCase();

      return {
        component: _ref
      };
    })();
  }

};
```

Issue lies here

```javascript
var _ref = _jsx(__WEBPACK_IMPORTED_MODULE_1__components_Layout__["a" /* default */], {}, void 0, _jsx(__WEBPACK_IMPORTED_MODULE_2__Hello__["a" /* default */], {
      name: upperCasedName
    }));
```

`upperCasedName` is not yet defined and app breaks.

So far I was not able to found a workaround and submit PR for You guys. Do You have any suggestions how to do it properly ?

**Comment by phpeek** [comment]
Issue is caused by `babel-plugin-transform-react-constant-elements`.

`react-optimize` preset is pretty outdated - last released on 16 Apr 2016. It's using version `6.5.0` of ``babel-plugin-transform-react-constant-elements`. However, issue is still occuring for latest release `6.23.0`. :(

**Comment by phpeek** [comment]
I've created an issue with babel. - https://github.com/babel/babel/issues/5520

**Comment by ulani** [comment]
@phpeek   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
