### ISSUE TITLE
render the view according to this.state instead of this.props

### ISSUE THREAD

**Issue by ssmlee04** [kriasoft/react-starter-kit#119]
The following is another implementation of react.js I saw
https://scotch.io/tutorials/build-a-real-time-twitter-stream-with-node-and-react-js

It renders the component according to this.state variable.  And you can do getInitialState() to set this.state using this.props variables and bind this.state to render the view accordingly. 

// Render the component
  render: function(){
    return (
      < div className="tweets-app">
        < Tweets tweets={this.state.tweets} />
        < Loader paging={this.state.paging}/>
        < NotificationBar count={this.state.count} onShowNewTweets={this.showNewTweets}/>
      < /div>
    )
  }

You example renders the view only according to this.props variable.  I was wondering if there's anything similar? Thanks

**Comment by cmnstmntmn** [comment]
i also have an issue in using **getInitialState** in components
[these examples](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es6-classes) doesn't seem to work either

i was trying to get **scrollY** and change component state / class .. from **sticky** to **unsticky**. 

i ended by using @koistya's **withWiewport** aproach

**Comment by langpavel** [comment]
This is really old issue without reactions.
Feel free to reopen it if you think it may be useful for someone.
