### ISSUE TITLE
Cannot add `resolve` property in webpack config

### ISSUE THREAD

**Issue by Stupidism** [kriasoft/react-starter-kit#1193]
# What do I want to do.
I wanted to add `resolve.alias` like #945 said.
```js
  resolve: {
    alias: {
      '~': path.resolve(__dirname, '../src'),
    },
  },
```
But failed. Finally I found add blank resolve will cause the same problem:
```js
resolve: {},
```

# Current result
When I run `yarn start`, the error showed up in command line:
```
/.../webpack:/src/core/fetch/fetch.client.js:14
export const Headers = self.Headers;
^
ReferenceError: self is not defined
```
It seems webpack resolved fetch to `fetch.client` for some reason
# Expected behaviour
webpack should resolve to `fetch.server` on the server side.

# Temp way to fix
I found the temp way to fix this. I put it here in case someone has the same problem like me.
I'm not sure this is a problem with RSK or webpack. Maybe https://github.com/webpack/webpack/issues/4160 is related.

```
const clientConfig = {
  ...config,

  name: 'client',
  target: 'web',

  resolve: {
    ...config.resolve,
    // Webpack should automatically set mainFields for `target: 'web'`
    // https://webpack.js.org/configuration/resolve/#resolve-mainfields
    // Webpack fails to do this when resolve property is specified.
    // Wait for RSK or webpack to fix this
    // https://github.com/kriasoft/react-starter-kit/issues/1193
    mainFields: ['browser', 'module', 'main'],
  },
}

const serverConfig = {
  ...config,

  name: 'server',
  target: 'node',

  resolve: {
    ...config.resolve,
    // Webpack should automatically set mainFields for `target: 'node'`
    // https://webpack.js.org/configuration/resolve/#resolve-mainfields
    // Webpack fails to do this when resolve property is specified.
    // Wait for RSK or webpack to fix this
    // https://github.com/kriasoft/react-starter-kit/issues/1193
    mainFields: ['module', 'main'],
  },
}
```

**Comment by Stupidism** [comment]
WTF. I can't reproduce this even on the same commit. I think I should just close it myself.

**Comment by plemarquand** [comment]
@Stupidism You're not crazy, I just had this happen too. Your workaround fixed it for me. It does feel like it could be related to webpack/webpack#4160.

**Comment by Stupidism** [comment]
Good to know I'm not crazy but only stupid!(LOL) @plemarquand

**Comment by lennerd** [comment]
We experienced the same. Looks like a bug in `webpack` though.
