### ISSUE TITLE
React-select on safari mobile does not work 

### ISSUE THREAD

**Issue by martinratinaud** [kriasoft/react-starter-kit#1195]
Hi guys, I forked the project and made a branch to illustrate this problem.

https://github.com/martinratinaud/react-starter-kit/tree/fix/react-select

Launch `npm start` and go to http://localhost:3000 from a mobile (not the chrome simulator but a real device or the iOS Simulator)

When you try to select `Two`, nothing happens even though it works well on a desktop browser.

In the meantime, the official page of react-select deos work on safari mobile http://jedwatson.github.io/react-select/

I tested by disabling SSR but it does not work either.

I think the problem comes from the webpack config but I could not figure this out.

If somebody could help me on this, that would be awesome.

PS: I experienced the same with react-dropzone but hopefully fixing this will fix it too

**Comment by frenzzy** [comment]
Maybe it requires some polyfills which should be executed before the lib?
Do you have [this change](https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js#L161-L163) in your RSK version?

**Comment by martinratinaud** [comment]
Hi, 

I have the change you mention and I don't have any error, it is just that I can't select the `two` entry as the `logChange` function is never triggered on safari mobile

**Comment by phpeek** [comment]
@martinratinaud What happens if You use port 3001 instead of 3000 ?

**Comment by Jaikant** [comment]
I had a similar issue with react-select, using port 3001 was a workaround which worked for me.

**Comment by martinratinaud** [comment]
Thanks for the insights

Actually, I tried it on production env and I get the same problem.
I also disabled SSR and I still have the problem (see the updated repo https://github.com/martinratinaud/react-starter-kit/tree/fix/react-select)

Finally if I make a long click on a select option it will select it but if I just tap/click it won't (in safari mobile again)

Again, react-select is working fine outside of react-starter-kit.

Thnaks for your help

**Comment by Jaikant** [comment]
@martinratinaud Trying to recall what else I had to change, one other thing which I had to modify for react-select and mobile was I moved to 'react-fastclick'

In client.js

// Commented out the existing Fastclick and used react-fastclick instead.
//import FastClick from 'fastclick';
import initReactFastclick from 'react-fastclick';

//FastClick.attach(document.body);
initReactFastclick();

**Comment by martinratinaud** [comment]
Thanks a lot @Jaikant it works well if I replace `fastclick` with `react-fastclick`. I'll submit a PR for this.

Cheers
