### ISSUE TITLE
Error: Unable to find element with ID (275)

### ISSUE THREAD

**Issue by Shadowman4205** [kriasoft/react-starter-kit#1203]
I am using redux store. 
I am getting this error 

> Error: Unable to find element with ID 275.
>     at invariant (invariant.js:38)
>     at precacheChildNodes (ReactDOMComponentTree.js:96)
>     at Object.getNodeFromInstance (ReactDOMComponentTree.js:172)
>     at Object.didPutListener (SimpleEventPlugin.js:210)
>     at Object.putListener (EventPluginHub.js:143)
>     at Object.putListener (ReactDOMComponent.js:176)
>     at CallbackQueue.notifyAll (CallbackQueue.js:76)
>     at ReactReconcileTransaction.close (ReactReconcileTransaction.js:80)
>     at ReactReconcileTransaction.closeAll (Transaction.js:206)
>     at ReactReconcileTransaction.perform (Transaction.js:153)

with this too

> Uncaught (in promise) TypeError: Cannot read property 'remove' of undefined
>     at Object.willDeleteListener (SimpleEventPlugin.js:220)
>     at Object.deleteAllListeners (EventPluginHub.js:201)
>     at ReactDOMComponent.unmountComponent (ReactDOMComponent.js:976)
>     at Object.unmountComponent (ReactReconciler.js:79)
>     at ReactCompositeComponentWrapper.unmountComponent (ReactCompositeComponent.js:418)
>     at Object.unmountComponent (ReactReconciler.js:79)
>     at Object.unmountChildren (ReactChildReconciler.js:146)
>     at ReactDOMComponent.unmountChildren (ReactMultiChild.js:373)
>     at ReactDOMComponent.unmountComponent (ReactDOMComponent.js:974)
>     at Object.unmountComponent (ReactReconciler.js:79)

I found (i think why this error happen) Like i did some test.
When i am using server side navigation it is working but in some pages when i click reload button it gives me this error.

in these pages i get dynamic my data using some html code from db. And i am using some function htmlparser to put one gallery component by replacing some certain parts of external html code. For example @gallery1@ will be replaced with Gallery component. When i have to place one gallery it is working fine with server navigation and the error do not appear when i reload the page. But when i have to put second gallery the serverside navigation working  well but when i reload the page with 1< galleries i get this error. So i think the problem is that the delay in time to replace the parts with galleries. 
So the client is ready but data is still loading. 

I also tried make the replaces with galleries in the part but nothing

```
export default {
     path: 'about',
children: [
     {
         path: '*',
         async action({ path, store }) {
            ................
            const children = await htmlparser(store.getState().content)
            debugger
            return {
               title: data.title,
               component: <Layout><About /><Content content={children} /></Layout>,
             }
          }
     }
]
}

function htmlparser(content) {
  children = parts.map((item, index) => {
            if (typeof item === "string") { //item is raw html
                return <div key={index} dangerouslySetInnerHTML={{ __html: item }} />
            } else { // object  => component
                return <div key={index}>{item}</div>;
            }
        })   
    return children;
}
```

For some reason i see this on inspect at chrome
```
<div data-reactid="274">  // this is item in children
     <p>............</p>
    <div data-reactid="275"></div>//but this is another item in children that for unknow reason nested in data-reactid="274"
</div>
```
but it should be this
```
<div data-reactid="274"> 
     <p>............</p>
</div>
<div data-reactid="275"></div>
```

Sorry for inconvience. I hope this explaination good. And this all happens like i mentioned ,when i reload page.
Anyone who knows how solve this problem?

**Comment by Shadowman4205** [comment]
Ok this was  due to invalid HTML structure that i was setting via dangerouslySetInnerHTML, there where unclosed tag.

**Comment by langpavel** [comment]
Short summary. You can get this error when you break DOM structure and browser will fix it for you. In this case your virtual DOM does not match real browser's DOM. Mostly table and p

**Comment by Shadowman4205** [comment]
Yes this is hard with react. I am getting html from database which is generated with one tool at cms. So i need to use this html and if there is on specific tag (@item12@) i have to replace it but sometimes because users do not what they do, they generate html code where hard to replace with component. And also i do not know exactly what to do with it. For now i just use markdown like this. 

```
function htmlparser(parts) {
 const children = parts.map((item, index) => {
        const md = new MarkdownIt({ html: true });
        if (typeof item === "string") {
            let markdown = toMarkdown(item)
            markdown = md.render(markdown);
            return <ReactMarkdown key={index} source={markdown} />; //<div key={index} dangerouslySetInnerHTML={{ __html: markdown }} />//<div key={index} dangerouslySetInnerHTML={{ __html: markdown }} />
        } else {
            return <div key={index}>{item}</div>;
        }
    })
    return children;
}
```
But this is it still problem because sometimes i have got this in html
`<strong><strong>Test</strong <strong>this</strong</strong>`
so it becomes `******Test this ******` and not `**Test this**` . Hard time!

**Comment by langpavel** [comment]
@Shadowman4205 Hi, I think that you have typical [dangerouslySetInnerHTML](https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml) use case. But you should sanitize html before passing them. Converting to markdown and back is.. well.. strange
