### ISSUE TITLE
[Branch react-intl] hot-loader for reducers not working

### ISSUE THREAD

**Issue by Stupidism** [kriasoft/react-starter-kit#1205]
## Problem
Because this branch changed the code for [`reducers/index.js`](https://github.com/kriasoft/react-starter-kit/blame/feature/react-intl/src/reducers/index.js#L6)
```
export default function createRootReducer({ apolloClient }) {
```

Forgot to change the hot loader code in [`store/configureStore`](https://github.com/kriasoft/react-starter-kit/blob/feature/react-intl/src/store/configureStore.js#L46)

## Fix
```
-     store.replaceReducer(require('../reducers').default),
+     store.replaceReducer(require('../reducers').default()),
```

**Comment by langpavel** [comment]
Can you create PR for this please? Thanks!

**Comment by Stupidism** [comment]
https://github.com/kriasoft/react-starter-kit/pull/1209 @langpavel please review

**Comment by langpavel** [comment]
You are most clever @Stupidism I met all the time ;-) Thanks. I should cherry-pick this to `feature/apollo` branch where this was introduced, but I'm not sure who follow what branch and it will become time expensive to maintain all..
