### ISSUE TITLE
runServer - Typo? 

### ISSUE THREAD

**Issue by squirmsound** [kriasoft/react-starter-kit#1206]
I noticed this weird comma. I'm either here to learn something knew about destructuring arrays or to report a typo.
```
// tools/runServer.js
const [, serverConfig] = webpackConfig;
```
Please confirm ?

Thanks!

**Comment by koistya** [comment]
`webpackConfig` is an array of two configs `[clientConig, serverConfig]`, this way you can grab the second element from the array.

**Comment by squirmsound** [comment]
@koistya Thanks! 

So if there were 8 configs?

```
[, , , , , , , serverConfig]
```
