### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by hourliert** [kriasoft/react-starter-kit#121]
Hi,

This is maybe a silly issue but I can't find how to debug the code of this starter kit.

Firstly, is it possible to debug it on chrome with devtools ? I didn't find in the code the sourcemap generation. Maybe I missed it..

Finally, since the node.js server renders the app, I have tried to set some breakpoints in Webstorm 10 in server.js file and then debug the default gulp task.

I always get this output: 
```
/usr/local/bin/node --debug-brk=52560 /usr/local/lib/node_modules/gulp/bin/gulp.js --color --gulpfile /Users/thomashourlier/Work/react-seed/gulpfile.js default
Debugger listening on port 52560
[13:26:50] Using gulpfile ~/Work/react-seed/gulpfile.js
[13:26:50] Starting 'build:watch'...
[13:26:50] Starting 'clean'...
[13:26:50] Finished 'clean' after 21 ms
[13:26:50] Starting 'build'...
[13:26:50] Starting 'vendor'...
[13:26:50] Starting 'assets'...
[13:26:51] Starting 'bundle'...
[13:26:52] Finished 'vendor' after 1.53 s
    Asset    Size  Chunks             Chunk Names
server.js  530 kB       0  [emitted]  main
[13:27:39] Finished 'bundle' after 48 s
 Asset     Size  Chunks             Chunk Names
app.js  2.39 MB       0  [emitted]  main
[13:27:45] 'assets' all files 30.84 kB
[13:27:45] Finished 'assets' after 55 s
[13:27:45] Finished 'build' after 55 s
[13:27:45] Finished 'build:watch' after 55 s
[13:27:45] Starting 'serve'...
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at Agent.Server.listen (net.js:1257:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3
```

However, I only get one running node process and nothing that could already listen on the port needed by this app:

```
$ ps -aef | grep node
  501 70115 70106   0  1:27PM ??         0:00.15 /usr/local/bin/node --debug-brk=52560 build/server.js
  501 70119 70061   0  1:28PM ttys000    0:00.00 grep node
```

```
$ lsof -i -P | grep -i "listen"
Skype     36399 thomashourlier   88u  IPv4 0x688fe303b2f225      0t0  TCP 10.0.1.54:21911 (LISTEN)
prl_clien 66435 thomashourlier   51u  IPv4 0x688fe31ba82955      0t0  TCP localhost:63937 (LISTEN)
vfstool   66648 thomashourlier    7u  IPv4 0x688fe303da27b5      0t0  TCP localhost:63973 (LISTEN)
vfstool   66648 thomashourlier    8u  IPv4 0x688fe303da27b5      0t0  TCP localhost:63973 (LISTEN)
webstorm  70216 thomashourlier   46u  IPv4 0x688fe31f407e35      0t0  TCP localhost:6942 (LISTEN)
webstorm  70216 thomashourlier  274u  IPv4 0x688fe2fad88955      0t0  TCP localhost:63342 (LISTEN)
node      70266 thomashourlier   16u  IPv6 0x688fe2f7cc8ae5      0t0  TCP *:52560 (LISTEN)
```

Any idea ?
Thanks in advance,
Thomas

**Comment by alexmcmillan** [comment]
Is it safe to assume you've tried different ports anyway?

**Comment by hourliert** [comment]
Yes, I have tried to change the node.js ports. I always get this error.
If I set a breakpoint at the first debuggable line of src/server.js. I never reach it.

**Comment by koistya** [comment]
As an alternative solution you can run web server by WebStorm, as opposed to starting it up with Gulp. E.g. you can build the project and start watching for modifications like so:

```sh
$ gulp build --watch
```

Then create a new run config in WebStorm which fires up `build/server.js` via Node,js, and start this run config in debug mode.

**Comment by hourliert** [comment]
Thanks, it works but it seems I need to set breakpoint in the build/server.js file. Then the  inline sourcemaps are read by webstorm and it redirects me to the es6 equivalent code. This file is large and not easy to manipulate. Is it possible to set the breakpoint directly in the es6 files ?

**Comment by koistya** [comment]
You can also try to debug your code with [node-inspector](https://github.com/node-inspector/node-inspector). You should be able to set breakpoints in source files..

E.g. you can run `node --debug build/server.js` in one console  window, then open another window and run `node-inspector`, then open your site and visit [http://127.0.0.1:8080/debug?ws=127.0.0.1:8080&port=5858](http://127.0.0.1:8080/debug?ws=127.0.0.1:8080&port=5858) to start debugging.

**Comment by koistya** [comment]
`EADDRINUSE` means that the port 5000 (used by Express.js) or port 3000 (used by BrowserSync) is already in use by another app.

**Comment by hourliert** [comment]
For the EADDRINUSE problem : That was not Express or BS that was running. In fact, when I debugged the gulp task sync. Webstorm auto add --debug-brk=xxxxx to launch the task and it seems when the gulp task fork `build/server.js`, the same option --debug-brk=xxxxx is passed. So it tries to run with the same debug port.

Everything works when I try to debug the code in the browser. It works with your previous solution. The only thing I can't get working is to debug directly in Webstorm because the sourcemaps translation doesn't work (but it doesn't matter, this debugger is very slow).

Thanks for your time.
Thomas

**Comment by AndrewRevinsky** [comment]
@koistya , please consider adding this (or similar) fragment into `gulpfile.babel.js`:

```
const child = cp.fork('build/server.js', {
      env: Object.assign({NODE_ENV: 'development'}, process.env),
      execArgv: process.debugPort ? [`--debug-brk=${process.debugPort + 1}`] : []
    });
```

I think, I used wrong debugging session detection so feel free to adjust that. 

It saves so much time and allows debugging inside server.js.

**Comment by koistya** [comment]
@AndrewRevinsky cool, thanks! I will check it out.

**Comment by kurtmarcink** [comment]
I am still struggling to find an efficient way to debug from this thread. I've got [this comment](https://github.com/kriasoft/react-starter-kit/issues/121#issuecomment-107833638) working, but how can I get it to work with the webpack and browsersync hotloading? Also, I still haven't been able to get this to work with the Webstorm debugger, which would be my preferred solution.

**Comment by mypark** [comment]
So I'm a bit confused on how to get it to follow the sourcemaps in webstorm.  It seems to start the debugger fine on the build/server.js but it doesn't follow any of the sourcemaps.  What was the solution to this?

**Comment by prigara** [comment]
WebStorm 11 adds support for debugging client-side apps built with Webpack, though you need to configure the mappings as described in this [blog post](http://blog.jetbrains.com/webstorm/2015/09/debugging-webpack-applications-in-webstorm/).
First, in tools/config.js change  ` devtool: DEBUG ? 'cheap-module-eval-source-map' : false,` to ` devtool: DEBUG ? 'source-map' : false,`
Then build the app and run server.js from the command line or using Node.js run configuration.
Exclude build directory from the project.
Then create new JavaScript debug configuration for the URL http://localhost:5000
In the run configuration map build/public to http://localhost:5000 and project root to webpack:///.
Now you can put breakpoints in the original files in src folder and start JavaScript debug session.
<img width="368" alt="screen shot 2015-10-23 at 16 58 54" src="https://cloud.githubusercontent.com/assets/782562/10696344/7ffaaeec-79a7-11e5-9b5b-da334e63bf96.png">

**Comment by mypark** [comment]
what about for debugging the server side code?

**Comment by prigara** [comment]
No, Node.js debugger doesn't support source maps structure generated by Webpack. We don't have any similar issues now, so would appreciate if you report it on https://youtrack.jetbrains.com/issues/WEB

**Comment by mypark** [comment]
ok, added to https://youtrack.jetbrains.com/issue/WEB-18751

**Comment by zomco** [comment]
@prigara It doesn't work     😢

Is `localhost:5000` the URL of `server.js` running at?

**Comment by koistya** [comment]
@zomco The Node.js/Express server is running at port 3000, see [src/config.js#L13](https://github.com/kriasoft/react-starter-kit/blob/0d01779c3df27d887e05cb50b5335c08e0de90b8/src/config.js#L13), [src/server.js#L141](https://github.com/kriasoft/react-starter-kit/blob/0d01779c3df27d887e05cb50b5335c08e0de90b8/src/server.js#L141). You can either build the project (`npm run build`) and launch server directly (`node --debug ./build/server.js`), or you can try to tweak [tools/runServer.js#L43-46](https://github.com/kriasoft/react-starter-kit/blob/0d01779c3df27d887e05cb50b5335c08e0de90b8/tools/runServer.js#L43-L46) and add additional debug arguments in there (see Andrew's comment above). Please, share your experience.
