### ISSUE TITLE
How to change route with props?

### ISSUE THREAD

**Issue by mdmush** [kriasoft/react-starter-kit#1214]
Heyy guys,

You have created a awesome kit which includes everything. I just wanted to know that **how to change routes with props that i want to transfer to another route?**. 

Thanks.

**Comment by Stupidism** [comment]
For now, RSK's route code is not that flexable.
```
export default {
  path: '/login',
  action() {
    return {
      title,
      component: <Layout><Login title={title} /></Layout>,
    };
  },
};
```
But we can make some change:
```
export default {
  path: '/login',
  action() {
    return {
      title,
      Wrapper: Layout,
      Component: Login,
      componentProps: { title },
    };
  },
};
```

**Comment by mdmush** [comment]
Okay thanks. 
Let me use this piece of code, then i'll let you know.

**Comment by langpavel** [comment]
You should think about every route as stateless. You need all the info in URL. Think about user which hits `F5` or `^R` key...

**Comment by Stupidism** [comment]
@langpavel I also tried this before, but didn't find a very convenient way to remain querystring when change route. Would you like to show some code snipt?
How to determine which part of query should be remained and which not?

**Comment by langpavel** [comment]
@Stupidism Not trivial. You must make your own decision. For tabs for example you can use fragment `#?panel1=tabId&panel2=otherTabId`, for filters you should use `?option=value`.. You must decide yourself how to do this, all the good rules for making SEO friendly URLs are valid here..
You should have functions for constructing URL..
Sorry but I have not enough time to play with this more..
