### ISSUE TITLE
Split Routes for backoffice based on the hostname

### ISSUE THREAD

**Issue by ricardomoura** [kriasoft/react-starter-kit#1215]
is it possible to split the client.js routes in order to have a admin subdomain with a different router file ou even using the same and export 2 consts to the server.js and client.js ?

i'm trying to make 2 different routes based on req.hostname on the server.js inside the app.get('*')

```
    let routes;
    let hostname = `${req.hostname}:${port}`;

    if (hostname === adminHost) {
      routes = require('./routes').admin;
    }

    if (hostname === host) {
      routes = require('./routes').client;
    }
```

on the client.js i basically do the same but instead req.hostname i use window.location.host
then i send to universalRouter the router, also inside HMR.

but i always get: 
TypeError: Cannot read property 'children' of undefined
React attempted to reuse markup in a container but the checksum was invalid.

it loads the page nicely during a second more or less

thanks!

**Comment by koistya** [comment]
You may want to use Webpack's code-spitting feature. Here is an example. When a user opens any admin page, the admin routes (chunk) are going to be loaded:

```js
{
  path: '/admin',
  action({ route }) {
    if (!route.children) {
      require.ensure('/admin', require => { route.children = require('./admin').default; });
    }
  }
}
```

**Comment by ricardomoura** [comment]
thanks @koistya 
that doesnt fix the issue, my problem resides on the client.js, if i force the routes to be the client or the admin ones everything works the problem is when i go to admin.localhost it loads the routes corresponding to the ones i have on the client.js

for instance:

on the client.js if i put require('./routes').client
then i go to admin.localhost:3001/ it loads the default / path of a client route instead the admin since isnt listed and vice versa

server.js:
```
    let routes;
    let hostname = `${req.hostname}:${port}`;

    if (hostname === adminHost) {
      routes = require('./routes').admin;
    }

    if (hostname === host) {
      routes = require('./routes').client;
    }

    const route = await UniversalRouter.resolve(routes, {
      path: req.path,
      query: req.query,
    });
```

routes/index.js:
```
/* eslint-disable global-require */

// The top-level (parent) route
export const client = {

  path: '/',

  // Keep in mind, routes are evaluated in order
  children: [
    require('./home').default,
    require('./contact').default,
    require('./login').default,
    require('./register').default,
    require('./about').default,
    require('./privacy').default,

    // Wildcard routes, e.g. { path: '*', ... } (must go last)
    require('./notFound').default,
  ],

  async action({ next }) {
    // Execute each child route until one of them return the result
    const route = await next();

    // Provide default values for title, description etc.
    route.title = `${route.title || 'Untitled Page'} - www.reactstarterkit.com`;
    route.description = route.description || '';

    return route;
  },

};

// const isAdmin = false;

export const admin = {

  path: '/',
  // Keep in mind, routes are evaluated in order
  children: [
    require('./admin/login').default,
    require('./admin/dashboard').default,
    require('./admin/chat').default,
    require('./admin/notFound').default,
  ],

  async action({ next }) {

    // if (!isAdmin) {
    //   return { redirect: '/login' };
    // }
    
    // Execute each child route until one of them return the result
    const route = await next();

    // Provide default values for title, description etc.
    route.title = `${route.title || 'Untitled Page'} - ADMIN DASHBOARD`;
    route.description = route.description || '';

    return route;
  },

};

```
client.js:

```

let hostname = window.location.host;
let routes;

console.log(hostname);
if (hostname === adminHost) {
  routes = require('./routes').admin;
  console.log('INSIDE ADMIN');
}

if (hostname === host) {
  routes = require('./routes').client;
  console.log('INSIDE CLIENT ROUTES');
}

async function onLocationChange(location, action) {
...
   const route = await UniversalRouter.resolve(routes, {
      path: location.pathname,
      query: queryString.parse(location.search),
    });
...

if (module.hot) {
  module.hot.accept('./routes', () => {
    
    routes = require('./routes').admin; // eslint-disable-line global-require
   // i think is here
...

}
```

**Comment by ricardomoura** [comment]
fixed, the conditions on the client.js  dont know why but the window.location.hostname was returning the express server port :3000 instead 3001

is working now.
thanks anyway

**Comment by shishirarora3** [comment]
Yes. This is done right on client.js. Just use the same routes in server.js
also so that server also renders same route pages and check sum error goes.

**Comment by langpavel** [comment]
Be careful with this. Everyone can fake admin subdomain in `hosts` file, I'm just ensuring you know what you are doing...

**Comment by ricardomoura** [comment]
@langpavel thats one or my concerns with this approach theres any other way of doing this?
Thnks

**Comment by langpavel** [comment]
@ricardomoura you can authenticate user by password and then set JWT token into (same-site, http-only, secure) cookie for example. This is most common way of doing this.
