### ISSUE TITLE
Get Current Path On Component

### ISSUE THREAD

**Issue by Shadowman4205** [kriasoft/react-starter-kit#1220]
Hello sorry if this stupid question;
but how i get current path in one component?
do i need use window?

**Comment by ucay** [comment]
You can use browse history from this [core](https://github.com/kriasoft/react-starter-kit/blob/master/src/core/history.js).

```javascript
import React, { Component } from 'react';
import history from '../../core/history';

class MyClass extends Component {
     
    // ...
    
    componentDidMount() {
        console.log(history.location.pathname);
    }

    // ...
}
```
