### ISSUE TITLE
I have some problem with source code........

### ISSUE THREAD

**Issue by weishijun14** [kriasoft/react-starter-kit#1221]
in './src/tools/start.js'

      let handleBundleComplete = async () => {

      //I don't know what this assign operation means ?
      handleBundleComplete = stats => !stats.stats[1].compilation.errors.length && runServer();
 
      const server = await runServer();
      const bs = browserSync.create();

      bs.init({
        ...isDebug ? {} : { notify: false, ui: false },

        proxy: {
          target: server.host,
          middleware: [wpMiddleware, hotMiddleware],
          proxyOptions: {
            xfwd: true,
          },
        },
      }, resolve);
    };

    bundler.plugin('done', stats => handleBundleComplete(stats));

Is syntax like this ? 

`
 let handleBundleComplete = async ( ) => {
    handleBundleComplete = (...) => {...}
    do something..
 }
`

**Comment by almeynman** [comment]
@weishijun14 
```
handleBundleComplete = stats => !stats.stats[1].compilation.errors.length && runServer();
```
The code above is equivalent to 
```
handleBundleComplete = stats => {
  if(!stats.stats[1].compilation.errors.length) {
    runServer();
  }
}
```

**Comment by weishijun14** [comment]
@almeynman 
em.....I know this, but what confuse me is :

```
// it`s  has been declare a variable (handleBundleComplete) and and assigned a value outside.
let handleBundleComplete = async () => { 

  // then assigned a value again , what does this mean?
  handleBundleComplete = stats => {
     if(!stats.stats[1].compilation.errors.length) {
       runServer();
     }
   }

 }
```

it`s gives a function expression assigned a value for handleBundleComplete ,
and assigned a value inside again. Why do this？
and I try to run```bundler.plugin('done', stats => handleBundleComplete(stats))```,

this code block inside 
```
handleBundleComplete = stats => {
     console.log('hello')
}
```
doesn`t work?

**Comment by almeynman** [comment]
@weishijun14 Oh got it! 

When it is run for the first time it does some extra stuff: 
```
const server = await runServer();
  const bs = browserSync.create();

  bs.init({
    ...isDebug ? {} : { notify: false, ui: false },

    proxy: {
      target: server.host,
      middleware: [wpMiddleware, hotMiddleware],
      proxyOptions: {
        xfwd: true,
      },
    },
  }, resolve);
```

For 2nd, 3rd,... it is overridden to 
```
handleBundleComplete = stats => !stats.stats[1].compilation.errors.length && runServer();
```

**Comment by weishijun14** [comment]
@almeynman 
I understand，Thank you very much for helping me！Although my English is not so good...

**Comment by weishijun14** [comment]
@almeynman
I found it, call Lazy loading function..
