### ISSUE TITLE
What is the purpose of window.APP_STATE and how best to save store in localStorage?

### ISSUE THREAD

**Issue by Andriy-Kulak** [kriasoft/react-starter-kit#1223]
What is the purpose of windows.APP_STATE in **redux** branch? I see it in the **Html.js** and **client.js** file. I am trying to save and load my state from local storage according to Dan Abramov's method [(link here)](https://egghead.io/lessons/javascript-redux-persisting-the-state-to-the-local-storage)and I need to load initial state in place of where window.APP_STATE is in client.js folder so state is initiated every time a user refreshes the page.

My main goal is to be able to save and retrive all of state in localStorage. In doing this, I have trouble figuring out where to subscribe to state so that everything is saved to local storage.

Any tips would be greatly appreciated!

in Html.js file:
```
<script
              // eslint-disable-next-line react/no-danger
              dangerouslySetInnerHTML={{ __html:
              `window.APP_STATE=${serialize(state, { isJSON: true })}` }}
            />
```
in  client.js file:
`const store = configureStore(window.APP_STATE, { history });`

store function from configureStore.js.
`const store = createStore(rootReducer, initialState, enhancer);`

Whenever I try to intialize state from localStorage into the store with this function in cliient.js file, I get an error below
`const store = configureStore({ photos: localStorage.getItem('APphotos') && JSON.parse(localStorage.getItem('APphotos')) }, { history });`

error:

> warning.js:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server

**Comment by langpavel** [comment]
Hi. You need transfer state from server to client for initial React mount. If you initial render with different state you may expect artifacts.
If you need load something from localStorage, do it after initial render. You may hook ReactDOM.render in client.js and dispatch action here. You can also have some initial bool indicating first render to prevent do this after route change.

**Comment by Andriy-Kulak** [comment]
@langpavel Thanks for the insight! I ended up loading local storage in a componentDidMount in the specific component that needs it. If I ever want to load the entire redux store from storage no matter what components are rendered, I can probably just put the logic in componentDidMount inside the App.js component which will hold all the child components by default.
