### ISSUE TITLE
Asynchronous load component, error in production environment

### ISSUE THREAD

**Issue by MinJieLiu** [kriasoft/react-starter-kit#1225]
Asynchronous load component, error in production environment

Example `Admin` component:

Remove `redirect` code

`yarn run build -- --release`

![4.png](https://minjieliu.github.io/assets/issures-image/4.png)

start `node build/server.js`
Visit `http://localhost:3000/admin`

![5.png](https://minjieliu.github.io/assets/issures-image/5.png)

It is also a mistake to upgrade to the new version of my project😥😥

**Comment by langpavel** [comment]
Oh, do webpack report you admin chunk?
I'm merging head continuously and did not notice this error

**Comment by MinJieLiu** [comment]
You can look at this error, thank you

**Comment by langpavel** [comment]
It works on `master` and other branches.
Check if you have this in your server part of `tools/webpack.config.js`:
```js
    // Do not create separate chunks of the server bundle
    // https://webpack.github.io/docs/list-of-plugins.html#limitchunkcountplugin
    new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 }),
```

**Comment by MinJieLiu** [comment]
@langpavel The code already contains this plugin
My environment:
```
node: v7.7.1
```
It can't works on master

**Comment by langpavel** [comment]
I tested it. It works. Try to wipe all caches, reinstall all
```
rm ~/.babel.json
rm -rf node_modules
yarn cache clean
yarn
yarn build -- --release && node build/server.js
```

**Comment by MinJieLiu** [comment]
It is still in my project is wrong, then I try `react-starter-kit`

**Comment by langpavel** [comment]
Ok, let me know and reopen only if it does not work in RSK.

**Comment by MinJieLiu** [comment]
It is still can't works on master.

![6.png](https://minjieliu.github.io/assets/issures-image/6.png)

![7.png](https://minjieliu.github.io/assets/issures-image/7.png)

😭😭 
I've tested it on both computers

**Comment by MinJieLiu** [comment]
This is a real problem, it is recommended that you use a new environment in accordance with the steps to try @langpavel

**Comment by MinJieLiu** [comment]
@langpavel 
This issue occurs after this submission 🤓
[c47984d9fa917274ce4de87e72d35146ac4939d2](https://github.com/kriasoft/react-starter-kit/commit/c47984d9fa917274ce4de87e72d35146ac4939d2)

**Comment by langpavel** [comment]
Try this in `webpack.config.json` **only in server** part:
```js
  ...
  module: {
     ...config.module,
 
     // Override babel-preset-env configuration for Node.js
     rules: config.module.rules.map(rule => (rule.loader !== 'babel-loader' ? rule : {
        ...rule,
        query: {
          ...rule.query,
          // Try add line below.. don't forget to install babel-preset-latest
          presets: rule.query.presets.map(preset => (preset[0] !== 'env' ? preset : ['latest', { es2015: { modules: false } }])),
        },
      })),
    },
    ...
```
I needed this some time before, but not now..

**Comment by MinJieLiu** [comment]
I know the reason for this problem.
In `package.json`
```json
"production": {
        "presets": [
          "react-optimize"
        ]
      },
```

remove `react-optimize` just fine.
Before this commit, but no problem. @langpavel

**Comment by langpavel** [comment]
Can you explain/discover more @MinJieLiu? Possibly opening new issue for this?

**Comment by MinJieLiu** [comment]
The `commit` before is good, I think it is updated one of the configuration led to this problem.
I'm going to open a new `issue `.
