### ISSUE TITLE
How to Import all of css from npm pacakge in node_modules to Component?

### ISSUE THREAD

**Issue by Andriy-Kulak** [kriasoft/react-starter-kit#1228]
I am trying to use a npm package which asks me to import all its css from node_modules to a plain css file to be used with the component. I am unsure how to do this with the isomorphic-style-loader which is used by default in all of the containers/components.
If If add the style loader part 'withStyles' then I have to define every class that is being used and none of the css is being picked up by default
```
...
export default withStyles(s)(ArtFilter);
```
**NPM package:**  https://github.com/xiaolin/react-image-gallery

Any ideas on the best way to tackle this?

Below are importing techniques asked to be used by creator of this package

```

# SCSS
@import "node_modules/react-image-gallery/styles/scss/image-gallery.scss";

# CSS
@import "node_modules/react-image-gallery/styles/css/image-gallery.css";

# Webpack
import "react-image-gallery/styles/css/image-gallery.css";

# Stylesheet with no icons
node_modules/react-image-gallery/styles/scss/image-gallery-no-icon.scss
node_modules/react-image-gallery/styles/css/image-gallery-no-icon.css
```

**Comment by frenzzy** [comment]
Have you tried to use `global-import` ?
```css
/* YourComponent.css */
@global-import 'react-image-gallery/styles/css/image-gallery.css';
```
ref #1153

**Comment by Andriy-Kulak** [comment]
@frenzzy this works great. Thanks!

**Comment by jhlav** [comment]
In case anyone goes back and finds this - only to find the solution doesn't work anymore - see commit [#1277](https://github.com/kriasoft/react-starter-kit/commit/a5392fa5684301908be3e1a5f2cdca65fc4c4cdf).

Seems `postcss-global-import` was removed due to being broken.

The correct behavior can be achieved by importing each external CSS file like so:
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import withStyles from 'isomorphic-style-loader/lib/withStyles';

// external-global styles must be imported in your JS.
import reactMD from 'react-md/dist/react-md.blue-amber.min.css'; /* Include full path & file extension */
import s from './Layout.css';
import Header from '../Header';
import Feedback from '../Feedback';

class Layout extends React.Component {
  ...
}
 
export default withStyles(reactMD, s)(Layout); /* Add comma-separated params in withStyles. */
```

This seems to be a common need without much documentation, no?
