### ISSUE TITLE
Documentation about IDE configuration is broken

### ISSUE THREAD

**Issue by abguy** [kriasoft/react-starter-kit#1229]
[How to Configure Text Editors and IDEs](/kriasoft/react-starter-kit/blob/master/docs/how-to-configure-text-editors.md)

Images don't exist on dropbox. Links doesn't work also.
Could you update it?

**Comment by langpavel** [comment]
@koistya What happened?

**Comment by abguy** [comment]
Doesn't it make sense to move these images into the repository?

**Comment by langpavel** [comment]
What about GH Wiki? Images can be stored here and they should be accessible outside I believe..

**Comment by abguy** [comment]
I guess that it should be atomic. Text and its images (attachments) should be located together.
On the other hand, I don't really care. GH wiki works for me either.

**Comment by koistya** [comment]
@langpavel DropBox has shut down "public folders" feature, will move those images somewhere else.

**Comment by abguy** [comment]
Any updates on this?

**Comment by abguy** [comment]
@koistya Could you attach those images to this issue?

**Comment by gowsisaran** [comment]
documentation is broken out into a number of user, reference and ... This chapter shows how to setup and use two of the most popular IDEs, 
https://www.gangboard.com/app-programming-scripting/react-js-course

**Comment by Sanaya1428** [comment]
Just stumbled across your blog and was instantly amazed at all the useful information that is on it.

[](https://nareshit.com/reactjs-online-training/)

**Comment by Sanaya1428** [comment]
Just stumbled across your blog and was instantly amazed by all the useful information that is on it.

https://nareshit.com/reactjs-online-training/

**Comment by devidroy** [comment]
The content was very interesting, I like this post. Your explanation way is very attractive and very clear.
[sap testing training in bangalore](https://bangaloretrainingcenter.blogspot.com/2021/04/sap-testing-training-in-bangalore.html)
https://bangaloretrainingcenter.blogspot.com/2021/04/sap-testing-training-in-bangalore.html

**Comment by devidroy** [comment]
Thank you for the most informative article from you to benefit people like me.
[microsoft azure training in bangalore](https://www.bangaloretrainingacademy.com/)

**Comment by ulani** [comment]
@abguy   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Comment by bharathiamarnath** [comment]
thanks for posting here i am sharing the most popular trending online certification course that will advance your career. 
[ios training in chennai](<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\BLACKB~1\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\BLACKB~1\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



https://intellimindz.com/ios-training-in-chennai/
--




</body>

</html>
)

**Comment by bharathiamarnath** [comment]
thanks for posting here i am sharing the most popular trending online certification course that will advance your career.
[ios training in chennai](

<style> </style>
https://intellimindz.com/ios-training-in-chennai/

**Comment by bharathiamarnath** [comment]
thanks for posting here i am sharing the most popular trending online certification course that will advance your career.
[android  training in chennai](

<style> </style>
https://chennaitraining.in/android-training-in-chennai/
