### ISSUE TITLE
react-optimize will cause a serious error

### ISSUE THREAD

**Issue by MinJieLiu** [kriasoft/react-starter-kit#1231]
In `webpack.config.js`,` react-optimize` will cause a serious error.
```js
presets: [
  ['env', {
    // Optimize React code for the production build
    // https://github.com/thejameskyle/babel-react-optimize
      ...isDebug ? [] : ['react-optimize'],
  ],
],
```

Reproduce the problem:

```
git clone https://github.com/kriasoft/react-starter-kit.git
yarn
```
`/src/routes/admin/index.js` Remove `redirect`
```
yarn run build -- --release && node build/server.js
```
Visit http://localhost:3000/admin

![5.png](https://minjieliu.github.io/assets/issures-image/5.png)

**Comment by frenzzy** [comment]
I'm unable to reproduce the issue with current master and node 7.9.0, [demo](https://frenzzy.herokuapp.com/admin).
The same with node 6.9.5, what node version do you use?

**Comment by MinJieLiu** [comment]
node v7.9 @frenzzy

**Comment by MinJieLiu** [comment]
This issue occurs after this submission 
[c47984d9fa917274ce4de87e72d35146ac4939d2](https://github.com/kriasoft/react-starter-kit/commit/c47984d9fa917274ce4de87e72d35146ac4939d2)

**Comment by langpavel** [comment]
I cannot reproduce too

**Comment by langpavel** [comment]
Can you publish branch on your public fork with changes causing this issue please?

**Comment by MinJieLiu** [comment]
I submitted the `build` folder
and you can run it.
[https://github.com/MinJieLiu/react-starter-kit](https://github.com/MinJieLiu/react-starter-kit)
@langpavel @frenzzy

**Comment by langpavel** [comment]
Confirmed. It does not happen in development, only in production build.

**Comment by langpavel** [comment]
What is really silly is fact, that almost same code behaves differently!
## This code works as expected:
```diff
diff --git a/src/routes/admin/index.js b/src/routes/admin/index.js
index e651363..195f839 100644
--- a/src/routes/admin/index.js
+++ b/src/routes/admin/index.js
@@ -11,7 +11,7 @@ import React from 'react';
 import Layout from '../../components/Layout';
 
 const title = 'Admin Page';
-const isAdmin = false;
+const isAdmin = true;
 
 export default {
 
```
## This code does not work:
Does not matter if you comment out or delete lines.
```diff
diff --git a/src/routes/admin/index.js b/src/routes/admin/index.js
index e651363..addd5ee 100644
--- a/src/routes/admin/index.js
+++ b/src/routes/admin/index.js
@@ -18,9 +18,9 @@ export default {
   path: '/admin',
 
   async action() {
-    if (!isAdmin) {
-      return { redirect: '/login' };
-    }
+    // if (!isAdmin) {
+    //   return { redirect: '/login' };
+    // }
 
     const Admin = await require.ensure([], require => require('./Admin').default, 'admin');
 
```

**Comment by frenzzy** [comment]
Looks like React components should not be mixed with async/await or generators inside single scope, for example:
```jsx
// src/routes/admin/index.js
import React from 'react';
import Layout from '../../components/Layout';

const title = 'Admin Page';

export default {

  path: '/admin',

  action() {
    return require.ensure([], require => require('./Admin').default, 'admin')
      .then(Admin => ({ // simple function without async/await or generators
        title,
        chunk: 'admin',
        component: <Layout><Admin title={title} /></Layout>,
      }));
  },

};
```

**Comment by dmitru** [comment]
Thanks @frenzzy - your answer has solved the problem for me.

**Comment by frenzzy** [comment]
I just looked at the compiled code and play a bit with it :)

**Comment by ulani** [comment]
@MinJieLiu   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
