### ISSUE TITLE
How to deal with modules inside node_modules that depends .css files?

### ISSUE THREAD

**Issue by jancassio** [kriasoft/react-starter-kit#1232]
Originally published [here](http://stackoverflow.com/questions/43523041/how-to-deal-with-modules-inside-node-modules-that-depends-css-files).

I'm working in a project where some of dependencies are a self made UI library components.

Those components has its proper `.css` file. The source structure is something like this:

    |- src
    |-|
      |- components
      |-| 
        | Component
        |-|
          |- index.js
          |- Component.js
          |- Component.css

The same structure is published in a build folder, with each `.js` file transpiled for a production compatible JavaScript format.

About components. Each component, imports itself styles, so I don't bundle all styles and load globally.

The core concept of each component, is like this

    import React from 'react';
    import { string, func } from 'prop-types';

    import Styles from './Component.css';

    function Component({ label, onClick }) {
      return (
        <div className={Styles.Component} onClick={onClick}>{ label }</Component>
      );
    }

    Component.propTypes = {
      label: string.isRequired,
      onClick: func
    };

    Component.defaultProps = {
      label: 'Hello',
      onClick: null
    };

    export default Component;

In a new project, made with [React-Starter-Kit](https://reactstarter.com), I'm able to install the lib above with `yarn add` or `npm install`, everything good here. So, when I try to use some component and run `yarn start` or `npm start`, I get the following error:

    /Users/someone/myproject/node_modules/mycomponentslib/build/Component/Component.css:1
    (function (exports, require, module, __filename, __dirname) { .Component {
                                                                  ^
    SyntaxError: Unexpected token .
        at createScript (vm.js:53:10)
        at Object.runInThisContext (vm.js:95:10)
        at Module._compile (module.js:543:28)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/someone/myproject/node_modules/mycomponentslib/build/Component/Component.js:13:15)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
    /Users/someone/myproject/tools/runServer.js:67
              throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);

I guess the problem is about babel trying to read `.css` files, but I would like to know if someone have a good approach to avoid this kind of problem, using the actual boilerplate I'm using right now (React Starter Kit).
 
**UPDATE 1**

I forgot to mention this. If I import that module using relative path sintax:
    
    ./../../node_modules/@scope/my-project

It works as expected.

**UPDATE 2**

Added details about component design and improved info about usage and error output.

Thanks.

**Comment by frenzzy** [comment]
Maybe you need to play with [tools/webpack.config.js#externals](https://github.com/kriasoft/react-starter-kit/blob/c442026a6b8df5af1a0b74d002a2cc5a71c4b168/tools/webpack.config.js#L276-L284)

**Comment by jancassio** [comment]
Hi @frenzzy thank you by adivice. I tried that before without sucess.

Check, actually I'm trying to figure out how to get same behaviour of relative path import to specific module.

Maybe you're point to right point and I lost some detail here.

Anyway, thank so much!

**Comment by frenzzy** [comment]
This is pretty strange content of css file, don't you think?

```js
// node_modules/mycomponentslib/build/Component/Component.css
(function (exports, require, module, __filename, __dirname) { .Component {
```

**Comment by jancassio** [comment]
@frenzzy yes I think, but `Component.css` is a valid css file. This happens only when `webpack` or `babel` are trying to interpret this file (I'm guessing).

**Comment by langpavel** [comment]
Hmmmm,I guess you must dig more what really happening there. If you find something, I'm afraid it will be on second party side. But please keep us informed. I'm not sure that this is issue on RSK side so I will close this, but we are watching forward

**Comment by jancassio** [comment]
Hi all,

Is fair enough to close this issues since it isn't an issue on React Starter Kit, it is a question about how to deal with this kind of problem by the right way.

Let me share with you guys my current solution.

As I mentioned before, I've a secondary UI lib for for visual elements, this UI lib is exposed by a private npm dependency or local npm link, so I'm able to add that UI lib to my main project (and other ones) just adding it as dependency. No secrets here.

The fundamental change I made to make everything working as expected was packing my UI lib using [Rollup](https://rollupjs.org).

Rollup bundles modules as I expect and my main project loads anything from UI lib without configure anything on webpack or doing workarounds with import path, just works like a charm.

Another advantage is about the tree shaking feature provided by Rollup, so this add some good and welcome code optimization for production.

Thank @frenzzy and @langpavel by attention 👍

**Comment by langpavel** [comment]
Great! If you feel you can reopen, but I think it's solved, right?

**Comment by jancassio** [comment]
Yep, it's solved @langpavel.
