### ISSUE TITLE
build / app.js not minimized

### ISSUE THREAD

**Issue by cmnstmntmn** [kriasoft/react-starter-kit#124]
i was looking at **app.js** file size, and it's about 2,4MB ..
the file itself isn't minimized, so this is the problem

**Comment by koistya** [comment]
You can build the app in either DEBUG (default) or RELEASE mode. Try to run:

```sh
$ gulp build --release     # build the app in `release` mode
```
or

```sh
$ gulp --release           # build and launch the site
```
