### ISSUE TITLE
Environment variables in config file are ugly, how about use node-config?

### ISSUE THREAD

**Issue by Stupidism** [kriasoft/react-starter-kit#1240]
https://github.com/lorenwest/node-config

I've successfully done it in my own project. 
Mainly benifits dev operators

**Comment by langpavel** [comment]
I'm not sure that this should be included in RSK. I'm using dotenv with minimal changes in code for development.

**Comment by Stupidism** [comment]
![image](https://cloud.githubusercontent.com/assets/5801015/25540363/a36133d6-2bff-11e7-9b33-1fe24447c6ed.png)
Environment config files, local config file will be like this.
It's very easy to override and cutomize.

**Comment by Stupidism** [comment]
![image](https://cloud.githubusercontent.com/assets/5801015/25540429/ce0abbac-2bff-11e7-8a7d-fcb66935a891.png)
Environment variables are easy to customize, too.

**Comment by Stupidism** [comment]
Also, it will throw an error if some necessary config is undefined if you call
`config.get('auth.jwt.secret')`
@langpavel

**Comment by koistya** [comment]
@Stupidism many developers use RSK just for front-end, there is no much environment variables, just `API_URL`, `GOOGLE_TRACKING_ID` etc. I would rather have `dotenv` integrated as @langpavel suggested, in order to be able to override these env variables (e.g. being able to test the front-end either with a local API http://localhost:8080/graphql or a remote one, e.g. https://reactstarter.com/graphql).

**Comment by Stupidism** [comment]
Can `dotenv` be used in frontend? I thought `dotenv` and `node-config` both works on server side.

I used environment variables because I used the server of RSK as a api-proxy gateway, too. And for our dev oprator, it's a save to have different config files for different deploy environments(develop, release, production).

**Comment by langpavel** [comment]
@Stupidism There is no library which can work on frontend as for dynamic configuration..Do you have an idea how it should work?
You must pass your config to client from server yourself.. it is just a part of state..

**Comment by Stupidism** [comment]
@langpavel Agreed, I misunderstood @koistya 's words
> many developers use RSK just for front-end

**Comment by langpavel** [comment]
BTW integrating `dotenv` is easy and clean and library itself is few bytes.

**Comment by Stupidism** [comment]
Current code
1. environment variables in code are implicit
2. default values and overrides are not clear
3. can't handle related config variables decently
4. determined when server is started
5. hard to require some env_variables
6. hard to handle local env_variables
```
// config.js
const port = process.env.PORT || 3000;
const host = process.env.HOST || 'localhost';

if (process.env.NODE_ENV === 'production' && !process.env.JWT_SECRET) {
  throw new Error('JWT_SECRET is required in production!');
}

module.exports = {
  // Node.js app
  port,
  host,
  exampleUrl: process.env.EXAMPLE_URL || `${host}:${port},
  auth: {
    jwt: { secret: process.env.JWT_SECRET || 'React Starter Kit' },
  }
};

// usage
import { exampleUrl } from '../config';
```

Use node-config:
```
// config/default.js
const defer = require('config/defer').deferConfig;

module.exports = {
  port: 3000,
  host: 'localhost',
  exampleUrl: defer(cfg => `${cfg.host}:${cf.gport}),
  auth: {
    jwt: undefined,
  }
};

// config/development.js
module.exports = {
  port: 3000,
  host: 'localhost',
  auth: {
    jwt: 'React Starter Kit',
  }
};

// .gitignore
src/config/local

// config/local.js
module.exports = {
  exampleUrl: 'What ever I want. Won\'t affect the repo.'
};

// config/custom-environment-variables.js
```
module.exports = {
  host: 'HOST',
  port: 'PORT',
  exampleUrl: 'EXAMPLE_URL',
  databaseUrl: 'DATABASE_URL',

  analytics: {

    // https://analytics.google.com/
    google: {
      trackingId: 'GOOGLE_TRACKING_ID', // UA-XXXXX-X
    },
  },

  auth: {
    jwt: 'JWT_SECRET',

    // https://developers.facebook.com/
    facebook: {
      id: 'FACEBOOK_APP_ID',
      secret: 'FACEBOOK_APP_SECRET',
    },

    // https://cloud.google.com/console/project
    google: {
      id: 'GOOGLE_CLIENT_ID',
      secret: 'GOOGLE_CLIENT_SECRET',
    },

    // https://apps.twitter.com/
    twitter: {
      key: 'TWITTER_CONSUMER_KEY',
      secret: 'TWITTER_CONSUMER_SECRET',
    },
  },
};

```

**Comment by ulani** [comment]
@Stupidism   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
