### ISSUE TITLE
Causes prop-types warning at run time

### ISSUE THREAD

**Issue by BhumiSukhadiya** [kriasoft/react-starter-kit#1244]
i am using prop-types package with react-starter-kit but it shows the warning every time :
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

React Version: ^15.5.4
ReactDOM Version: ^15.5.4
prop-types Version: ^15.5.8

I have tried every possible solutions but none of them can fix this warning.
Please show me right solution.

![image](https://cloud.githubusercontent.com/assets/26542624/25470778/7abacc26-2b41-11e7-8431-9cc781b156b7.png)

**Comment by frenzzy** [comment]
Run `npm run build` then search for `react__["PropTypes"]` in `build/public/assets`.
Maybe it is third-party components which you are using.

**Comment by BhumiSukhadiya** [comment]
I can not find any react__["PropTypes"] in build/public/assets.

**Comment by koistya** [comment]
@BhumiSukhadiya also you can try to install a tool similar to [`npm-check-updates`](https://github.com/tjunnone/npm-check-updates) and see what modules in your project are outdated:

![image](https://cloud.githubusercontent.com/assets/197134/25471879/ab3fd4dc-2b31-11e7-91b5-eaeafde49e74.png)

**Comment by frenzzy** [comment]
Try to search with regexp: `/react.*PropTypes/gi` to find something like
```js
ThirdPartyComponent.propTypes = {
  propName: __WEBPACK_IMPORTED_MODULE_0_react___default.a.PropTypes.any.isRequired
};
```

**Comment by BhumiSukhadiya** [comment]
@frenzzy i have tried to search it with regexp but i didn't find anything.
@koistya i am getting output as below:
![image](https://cloud.githubusercontent.com/assets/26542624/25472111/8903cf2a-2b47-11e7-83e6-cc01a25a8f5b.png)

**Comment by frenzzy** [comment]
It strange why you did not found this
```js
var contextTypes = {
  insertCss: _react.PropTypes.func
};
```
You need to update `isomorphic-style-loader` to v2

**Comment by BhumiSukhadiya** [comment]
Thanks a lot @frenzzy update isomorphic-style-loader to v2 has worked.
Warning is gone.
