### ISSUE TITLE
button in navigation.js not work

### ISSUE THREAD

**Issue by zsu13579** [kriasoft/react-starter-kit#1251]
I want to add logout Button in navigation component, but it just cant't work when I click on it. The handleClick functiion won't print logs. I've stuck on it for days and just can't find out why. Please help to check. Thanks in advance.

```
import React from 'react';
import cx from 'classnames';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './Navigation.css';
import Link from '../Link';
import { connect } from 'react-redux';
import { logout } from '../../actions/user'

class Navigation extends React.Component {

  constructor(props) {
        super(props);
        this.handleClick = this.handleClick.bind(this);
    }
    componentDidMount() {
        console.log('I was mounted');
    }
    handleClick(){
        console.log('I was clicked');
    }

  render() {
    return (
      <div className={s.root} role="navigation" >
        <Link className={s.link} to="/about">About</Link>
        <Link className={s.link} to="/contact">Contact</Link>
        <span className={s.spacer}> | </span>
        <Link className={s.link} to="/login">Log in</Link>
        <span className={s.spacer}>or</span>
        <Link className={cx(s.link, s.highlight)} to="/register">Sign up</Link>
        <span className={s.spacer}> | </span>
        <button onClick={()=>this.handleClick()}>Log out</button>
      </div>
    );
  }
}

export default connect(false, { logout })(withStyles(s)(Navigation));
```

**Comment by langpavel** [comment]
Do you see other logs in console in browser?

**Comment by zsu13579** [comment]
Yes I can see other logs in

**Comment by zsu13579** [comment]
@langpavel thanks for you hint. There's some other error in the browser logs, which means can't get the vendor.js.  I run the web by `yarn start`  and I find that the `build` directory just don't have the vendor.js file. So should I run the web by other command?  Any advice?

**Comment by langpavel** [comment]
You must open http://localhost:3001 not on port 3000 because of browsersync in development

**Comment by Timson020** [comment]
import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux'
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './Home.css';

class Home extends React.Component {

  static propTypes = {
  };

  render() {
    return (
      <div className={s.root}>
        <div className={s.container}>
          <h1>{this.props.user.name}</h1>
          <a onClick={() => {
            this.props.dispatch({type:'login_success'})
          }} >11111</a>
        </div>
      </div>
    );
  }

}

export default connect(state => ({
  user: state.user.toJSON()
}))(withStyles(s)(Home))

**Comment by Timson020** [comment]
same question
but I can't see the console.log
and I can't see the event bind in element

**Comment by Timson020** [comment]
```
import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux'
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './Home.css';

class Home extends React.Component {

  static propTypes = {
  };

  render() {
    return (
      <div className={s.root}>
        <div className={s.container}>
          <h1>{this.props.user.name}</h1>
          <a onClick={() => {
            console.log(1)
          }} >11111</a>
        </div>
      </div>
    );
  }

}

export default connect(state => ({
  user: state.user.toJSON()
}))(withStyles(s)(Home))
```
