### ISSUE TITLE
Redux, extend demo to dispatch the fetch graphlq and dispatch from a component

### ISSUE THREAD

**Issue by rolele** [kriasoft/react-starter-kit#1254]
Hi,
thanks for your work this project looks awesome.
I have been inactive with javascript for 1 year, the hot example I was following last year is dead cold today so I basically have to start all over again.

I am interested in the react-redux integration. 
I see that in the current redux demo only one dispatch is done and it is at the server level in ```src/server.js```
I would like to have a more typical example of dispatch. I see that the ```src/routes/home/index.js``` is requesting to the endpoint /graphql. I will be interested to see how the redux integration will look like in that case?

Also it seems that the ```routes``` folder have all the logic regarding the AJAX requests to feed the UI. It is like if the actual URL define the triggering of the AJAX requests. but let say I would like to implement an application that does not have URL changes. Let say I have ```mydomain.com/```and no matter which button I click, I still dispatch action, do requests, update my UI but the url does not change, is this possible? Basically, I am interested to know how to dispatch action from the components and not the routes?

To resume 
1) I would like to know how to dispatch the fetch('graphql') using redux and have the result in the state before displaying the state in a component using connect()
2)  I am interested to know how to dispatch action from the components themselves and not from the routes?

Thanks a lot

**Comment by langpavel** [comment]
Hi @rolele. All you need is follow react-redux docs. Situations which are not documented there are covered exactly by code samples in RSK.

**Comment by ulani** [comment]
@rolele   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
