### ISSUE TITLE
All data are server-fetched on port 3000 and client-fetched on port 3001. How to server-fetch only the first request?

### ISSUE THREAD

**Issue by rolele** [kriasoft/react-starter-kit#1256]
I am playing with the feature/redux branch.
For some reason 2 app are deployed: one on 3000 (server-side fetch) and one on 3001 (HMR + client-side fetch)

- The app on port 3000 refresh the page every time I click and the data is already on the page (no XHR) (fetching server-side). If I build the app and run ```node server.js``` I am having the same behavior, every click trigger a refresh as well. 
Is this the expected behavior?

- On 3001 all the data is fetch on the client side so even when you load the page for the first time the XHR to /graphql is done client side and not server side. 
That is not how I would expect the app to behave. I would like to have the first page with server-side fetch (for SEO purpose) but from then I would like the page to not refresh at all.
Is this possible with react-starter-kit?

- Also I have the redux dev tool plugin installed on my chrome and it is not available on the server version on port 3000 but it is available on the client version port 3001.
Is the redux version working on server-side?

**Comment by rolele** [comment]
The demo on https://demo.reactstarter.com/.
If I curl the page I see that all the data is on the page meaning the server side worked.
Now if I visit the page with a browser I still see the XHR being done (see the image)

![react](https://cloud.githubusercontent.com/assets/22406571/25728407/3aff3464-3172-11e7-886b-f402016862b7.jpg)

Is the request done 2 times?

**Comment by nschurmann** [comment]
I'm having the same issues! interested to know what is going on.

**Comment by nschurmann** [comment]
It's a bug with the branch, try with redux without intl.

**Comment by nschurmann** [comment]
@rolele

**Comment by ulani** [comment]
@rolele   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
