### ISSUE TITLE
Stylelint/commit command alters my CSS file with Slashes

### ISSUE THREAD

**Issue by Andriy-Kulak** [kriasoft/react-starter-kit#1259]
So I've started to use the post css grid system, [lost](https://github.com/peterramsing/lost), in my app. The grid is defined in the css file with fractions like below.

I noticed a very odd behaviour... when I make a commit, something in the app is adding spaces between slashes. The additional spaces after commit prevent my grid system from working. Does anyone have any idea on how to resolve this?

Before I commit in my css file:
```
.avatarSecondRowWidth {
  lost-column: 1/12;
  lost-offset: 1/3;
  margin-top: -20px;
}
```

After I commit in my css file: this is how it is stored in git!!! :-O ...
```
.avatarSecondRowWidth {
  lost-column: 1 / 12;
  lost-offset: 1 / 3;
  margin-top: -20px;
}
```

**Comment by langpavel** [comment]
This is done by lint-staged package

**Comment by Andriy-Kulak** [comment]
@langpavel. ok, thanks. I ended simply removing the part where it lint checks the css before committing. I will not have a ton of complicated css so this has little relevance to me.

Thanks!

**Comment by langpavel** [comment]
Better for you can be fix config of csslint, report it if is a bug :-)
