### ISSUE TITLE
why less?

### ISSUE THREAD

**Issue by cmnstmntmn** [kriasoft/react-starter-kit#126]
https://css-tricks.com/sass-vs-less/

i switched to sass, buy i'm just courious why less was choosen as a default option since, many frameworks (compass, burbon, neat) are build on sass

**Comment by tommmyy** [comment]
+1

**Comment by chiefGui** [comment]
+1

**Comment by Aluxian** [comment]
+1

**Comment by eikeco** [comment]
PostCSS +1

**Comment by frob** [comment]
Shouldn't this be closed?

**Comment by langpavel** [comment]
Yes, this should be closed
