### ISSUE TITLE
Do not import `config.js` from inside the client-side code.

### ISSUE THREAD

**Issue by charyorde** [kriasoft/react-starter-kit#1260]
In what scenario would I be able to avoid this?
```
if (process.env.BROWSER) {
  throw new Error('Do not import `config.js` from inside the client-side code.');
}
```
I'm hitting this in the browser when I launch the app.

**Comment by koistya** [comment]
It's better to explicitly pass some portion of that config by serializing it into `<script>window.foo={...}</script>` on the server and consuming that object on the client. Otherwise, you may accidentally lick some confidential info (db password etc.)

**Comment by charyorde** [comment]
Thanks. But any reason why `config.js` is not loaded into the `store` by default?
```
const store = configureStore(initialState, {
      fetch,
      config
    });
``` for example?

**Comment by koistya** [comment]
@charyorde because there is no Redux on the master branch, but you can find examples here:

https://github.com/kriasoft/react-starter-kit/pull/1250
https://github.com/kriasoft/react-starter-kit/pull/883

It's important not to pass the whole config object, but rather cherry-pick the actual values your going to use on the client, for example:

```js
// on the server
const store = createStore({
  apiUrl: config.api.publicUrl,
});
```

**Comment by langpavel** [comment]
@charyorde you cannot pass entire config in c client side code. You have no secrets? :-)

**Comment by charyorde** [comment]
Thanks makes sense. I'll just leave out my secret data out of that file. :)

In the end, I ended up with something like this in `server.js`:
`store.dispatch(setServiceCatalog(config));` // setServiceCatalog being an action creator

**Comment by langpavel** [comment]
@charyorde Ok, this is possible, why not? You will be able to change your config on any time by this action. But I'm not sure if all of your client side services are flexible like this too :-)
It is correct to pass general config variables statically, you can do this with Redux `initialState` or by global variable, both are correct in this edge case :-)

**Comment by charyorde** [comment]
Kind of super flexibile though. `store.getState().config`. I like how it's now part of a server-side resource.
