### ISSUE TITLE
Error: Cannot find module 'logo.png'

### ISSUE THREAD

**Issue by moshest** [kriasoft/react-starter-kit#1271]
I have a component `Logo` with `Logo.css` and `logo.png` files.

When I use the image on the css file like:
```css
.root {
  background: url('logo.png') no-repeat 0 0;
}
```

I got the following error: `Error: Cannot find module 'logo.png'`

If I change the path to `url('/logo.png')` and put the logo image on the `public` folder, everything works fine but that's breaks the component-based UI development principle.

**Comment by langpavel** [comment]
Try ./logo.png

**Comment by moshest** [comment]
Same results. Please see [guidelines](https://github.com/webpack-contrib/css-loader#url)  on `css-loader` library.

I tries to import the image file from the `Logo.js` component class and it's works:
```js
import image from "./logo.png";

assert.equal(image, "/assets/../logo.png?xxxx");
```
I can't figure out why it's failed on the CSS file.

**Comment by frenzzy** [comment]
https://github.com/webpack-contrib/css-loader#url
```js
/* src/components/Header/Header.css */
.root {
  background-image: url('./banner.png'); /* src/components/Header/banner.png */
}
```

**Comment by moshest** [comment]
`url('./logo.png')`, `url('logo.png')`, `url(./logo.png)`and `url(logo.png)` give me the same error.

**Comment by ucay** [comment]
is this related with webpack's issue?
https://github.com/webpack-contrib/css-loader/issues/74

**Comment by moshest** [comment]
Yes. Looks like it's the same issue.

Disabling the `modules: true` on **css-loader** options break all the images on the website but the warning gone.

**Comment by moshest** [comment]
I was able to reproduce this error to a clean **react-starter-kit** project by adding: 
```
.bannerTitle {
  background: url('logo-small.png');
  ...
}
```
to the [Header.css](https://github.com/kriasoft/react-starter-kit/blob/master/src/components/Header/Header.css) file under the `Header` component.

**Comment by moshest** [comment]
I open a new project of "react-start-kit" and change the file [Header.css](https://github.com/kriasoft/react-starter-kit/blob/master/src/components/Header/Header.css) to:

```css
.bannerTitle {
  background: url('logo-small.png');
  /*...*/
}
```

And the build was failed with error: `Cannot find module 'logo-small.png'`.

When I change it to:

```css
.bannerTitle {
  background: url('./logo-small.png');
  /*...*/
}
```

Everything works fine.

That's incompatible with the [guidelines](https://github.com/webpack-contrib/css-loader#url)  of `css-loader` library and can case problems when requiring third-party style files.

**Comment by frenzzy** [comment]
For third-party lib libraries you may to [disable CSS Modules](https://github.com/kriasoft/react-starter-kit/issues/1274#issuecomment-302958948), then `url('logo-small.png')` also will work fine.

**Comment by moshest** [comment]
Confirm. Working.

Thanks!
