### ISSUE TITLE
Question: Prefetch data only for specific component/route during Server-side rendering

### ISSUE THREAD

**Issue by blz-ea** [kriasoft/react-starter-kit#1273]
Hello,
You have created a awesome starter kit with everything developer needs. 
And I have a question.
I am using **feature/react-intl** branch and trying to figure out how to fetch data from API only for specific route during server-side rendering.
Right now I just dispatch an action in **src/server.js** ( **await store.dispatch(setData())** ) and get what I almost need. That action will fire on every single page. But what I want is when we request e.g. **/contact/:id** that action will fire only when **route** is /contact/:id
We can parse **route(req.path)** in **src/server.js**, but is it a good practice? Is there any better solutions for this?

Thank you

**Comment by seberik** [comment]
Would it not work if you specify the routes data dependence in each route, more precisely in the action function? I have also looked at solutions using a library like Redial to specify the data dependence in components and have the server and client handle the resolution of the dependencies differently.

**Comment by langpavel** [comment]
You can prefetch data in `action` on route exactly same way. You have `store` accessible through `context` of route.
And you can prefetch this on server only by simple condition `if (!process.env.BROWSER) ...` see [tools/webpack.config.js](https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js#L188) line [188](tools/webpack.config.js#L188) and [303](https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js#L303)

**Comment by blz-ea** [comment]
@langpavel Thank you very much thats exactly what I needed. I ended up populating store in route handler
```
export default {
  path: '/post/:id',
  async action({ store }) {
    await store.dispatch(setData());
    return {
      title,
      component: <Layout><StyledPost title={title} /></Layout>,
    };
  },
};
```
That is unbelievably useful
