### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by suryasingh** [kriasoft/react-starter-kit#1281]
Getting this error after including element-react
`import {Menu} from 'element-react';
import 'element-theme-default';`

![error](https://cloud.githubusercontent.com/assets/5394014/26487695/d414b3f6-4200-11e7-91cb-f4ddcbeaa33b.png)

**Comment by frenzzy** [comment]
Looks like the `element-react` lib does not support server-side rendering.

How to render a component on client-side only? #186

**Comment by langpavel** [comment]
This is really common trouble with client side components only. You should ask your package vendor for solution.
If package rely on client side features, you can create a wrap for it and make different code paths for server and client.
Best advice is to avoid libraries which cannot support ssr.
