### ISSUE TITLE
Accessing non-modular files anywhere app

### ISSUE THREAD

**Issue by Andriy-Kulak** [kriasoft/react-starter-kit#1285]
First off, I really appreciated the effort put into this project!

**Is there a way to add non-modular javascript files/scripts into the app somehow so that I can access the variables and functions within them anywhere?** The reason is..

I am trying to get an AWS API Gateway Javascript SDK to work with the react-starter-kit and am having difficulty so maybe someone can provide a suggestion.

The instructions for SDK are [here](http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk-javascript.html), but the basic just of it is:
1. downloading a bunch of javascript files that **are not modular**
2. referencing them in your index.html files as scripts (as shown in part 1 below)
3. use the available variables and functions (as shown in part 2 below)

Part I (in hypothetical index.html file)
```
<script type="text/javascript" src="lib/axios/dist/axios.standalone.js"></script>
<script type="text/javascript" src="lib/CryptoJS/rollups/hmac-sha256.js"></script>
... + 9 more scripts
```
Part II (in your javascript file)
```
var apigClient = apigClientFactory.newClient();
... + a bunch more code that is not modular
```

The problem is that this approach is that the js files AWS creates **are not modular** and it's hard for me to reference the 'apigClientFactory' for instance.

I tried making it work by adding the 11 javascript files into the public folder and then referencing them with script tags in Html.js file as below

in Html.js
```
<script type="text/javascript" src="lib/axios/dist/axios.standalone.js"></script>
<script type="text/javascript" src="lib/CryptoJS/rollups/hmac-sha256.js"></script>
... + 9 more scripts
```
I am having trouble accessing this code in my react components. I tried using:
- window.apigClientFactory
- global.apigClientFactory

Also, when I deploy the app in heroku, half of the script files are missing in the sources so I am not sure if putting them in public folder is reliable.

**Comment by frenzzy** [comment]
1. Put external files to the `/public` folder, for example:
```bash
~your-project-name/public/js/file1.js
~your-project-name/public/js/file2.js
```
2. Insert `<script>` tags into `src/components/Html.js` component [before app entry point](https://github.com/kriasoft/react-starter-kit/blob/71206afb8b274154f5d273e4bad5f15ce3dc39fd/src/components/Html.js#L57):
```js
<script src="/js/file1.js"></script>
<script src="/js/file2.js"></script>
```
3. Call third-party api on client-side only in your components:
```js
class YourComponent extends React.Component {
  componentDidMount() {
    window.thirdPartyApi.call();
  }
  // ...
}
```

**Comment by Andriy-Kulak** [comment]
Thank you for the prompt response @frenzzy. Your detailed approach is exactly what I have been trying to do, and everything works well locally however this has some  weird side effects once I deploy the app in production (via heroku). Only some of the javasctipt files (4 out of 11) show up in sources in chrome console. 

I added all of the 11 js files in the public folder and then referenced them in Html.js file.

Html.js file
```
          <script type="text/javascript" src="js/lib/axios.standalone.js" />
          <script type="text/javascript" src="js/lib/hmac-sha256.js" />
          <script type="text/javascript" src="js/lib/sha256.js" />
          <script type="text/javascript" src="js/lib/hmac.js" />
          <script type="text/javascript" src="js/lib/enc-base64.js" />
          <script type="text/javascript" src="js/lib/url-template.js" />
          <script type="text/javascript" src="js/lib/sigV4Client.js" />
          <script type="text/javascript" src="js/lib/apiGatewayClient.js" />
          <script type="text/javascript" src="js/lib/simpleHttpClient.js" />
          <script type="text/javascript" src="js/lib/utils.js" />
          <script type="text/javascript" src="js/lib/apigClient.js" />
```
Everything works well locally. I see all of the 11 js files in my sources and no errors per image below.

**Local envirionment:**
![screen shot 2017-05-29 at 1 08 16 pm](https://cloud.githubusercontent.com/assets/12179976/26557857/6e9d6292-4472-11e7-8680-7d08aa2eee79.png)

**However, when I deploy in production (via heroku), only 4 of the 11 files are in the sources: (per image below)**
![screen shot 2017-05-29 at 1 04 10 pm](https://cloud.githubusercontent.com/assets/12179976/26558016/ab283970-4473-11e7-9e97-6d950c9e6964.png)
![screen shot 2017-05-29 at 12 59 17 pm](https://cloud.githubusercontent.com/assets/12179976/26558015/ab23c520-4473-11e7-8fcb-d63874fa4f21.png)


**Any idea on what the problem can be?**

The js files themselves look fine. Below is the download link for the files if you want to take a look:
- https://developer.deeparteffects.com/download/deeparteffects-javascript-sdk-1.0.0.zip

**Comment by Andriy-Kulak** [comment]
Ahh something with express was not serving the static files correctly. I fixed the following in server.js and it works now:

Before:
`app.use(express.static(path.join(__dirname, 'public')));`
After
`app.use(express.static(path.join(`${__dirname}/public`)));`

**Comment by frenzzy** [comment]
Can you try `path.resolve(__dirname, 'public')` instead?

**Comment by Andriy-Kulak** [comment]
thanks for the help!
