### ISSUE TITLE
Styles from External files are not being inserted into HTML file

### ISSUE THREAD

**Issue by manoj150283** [kriasoft/react-starter-kit#1286]
I am having a Style folder containing .scss files in /src folder

![image](https://cloud.githubusercontent.com/assets/7291281/26540969/e7f1828a-4464-11e7-90e9-bb8ac8f41fea.png)

**In App.js, I am importing all the styles from styles folder like this:**

![image](https://cloud.githubusercontent.com/assets/7291281/26541020/09e68746-4465-11e7-9e6f-55928c89160b.png)

**My webpack.config.js looks like this:**

![image](https://cloud.githubusercontent.com/assets/7291281/26541045/23904678-4465-11e7-8ec5-21e9c243abb0.png)

**postcss.sass.js file**
![image](https://cloud.githubusercontent.com/assets/7291281/26541069/3e91ec24-4465-11e7-8622-c077a1c95f8a.png)

**My login.js file look like this**
![image](https://cloud.githubusercontent.com/assets/7291281/26541088/55d2aeaa-4465-11e7-8481-670eca0f0162.png)

My css are getting loaded into client.js file 

![image](https://cloud.githubusercontent.com/assets/7291281/26541134/8b715e62-4465-11e7-822e-a9d53ba61130.png)

But it is not getting inserted into html file.

Please help and advice.

**Comment by frenzzy** [comment]
You need to insert them manually. For example if you want that you're styles appears on all pages, just do something like this in `src/components/Layout/Layout.js`:
```js
import bootstrap from '../styles/bootstrap.scss';
import ui from '../styles/ui.scss';
import s from './Layout.css';

// ...

export default withStyles(bootstrap, ui, s)(Layout);
```

**Comment by manoj150283** [comment]
Thank  you @frenzzy :) I have one question though. In this case all styles will appear on all pages irrespective it is used or not. Is there any workaround for this ? Is there any other way to insert only used css on the html ?

**Comment by frenzzy** [comment]
Sure, for example, if you want only button styles to appear on the page, import them inside react `Button` component, and when you use the button on the page, its styles will automatically be added to the page and removed when all the buttons disappear.
```css
/* src/components/RedButton/RedButton.css */
.root {
  border: 0;
  background: red;
  color: white;
}
```
```js
/* src/components/RedButton/RedButton.js */
import React from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './RedButton.css'; // <= button styles

class RedButton extends React.Component {
  render() {
    return <button type="button" className={s.root} {...this.props}>;
  }
}

export default withStyles(s)(RedButton); // <= apply button styles if necessary
```
```js
/* src/routes/login/Login.js */

// ...
<RedButton>Log In</RedButton>
// ...
```

**Comment by manoj150283** [comment]
@frenzzy Thank you for your suggestion.

**Comment by pihyper** [comment]
@frenzzy , So much thanks for the solution. The doc needs to be specific about this for newbies.
