### ISSUE TITLE
error  "WithContext" is not defined  no-undef

### ISSUE THREAD

**Issue by cmnstmntmn** [kriasoft/react-starter-kit#129]
i'm getting these errors right after i run gulp

![screen shot 2015-06-02 at 14 10 02](https://cloud.githubusercontent.com/assets/2312755/7934560/62e57396-0931-11e5-94ad-48366710ff97.png)

**Comment by cmnstmntmn** [comment]
also if i run `npm test` i get same errors
![screen shot 2015-06-02 at 14 16 59](https://cloud.githubusercontent.com/assets/2312755/7934642/253a1686-0932-11e5-9a1c-33919bcb2f2f.png)

**Comment by koistya** [comment]
Looks like a bug in ESLint. There is a workaround in e6e3a97.
