### ISSUE TITLE
import jsx files not working

### ISSUE THREAD

**Issue by JavoByte** [kriasoft/react-starter-kit#1293]
Hi, i pulled the feature/redux branch and I'm used to develop saving my react components with `.jsx` extension.

However, using this boilerplate, gives me the error

`Module not found: Error: Can't resolve './MyComponent'`

Adding the extension to the `import` statement solves the problem.

I tried adding the `resolve.extensions` to the `webpack.config.js` file but it breaks the `createLogger` files. The `createLogger.client.js` is always loaded both in the client and in the server. 

How can I fix this issue?? I'm out of ideas.

**Comment by langpavel** [comment]
Can you provide more code? I believe it's bad regexp in you webpack

**Comment by JavoByte** [comment]
I didn't touch the regexp. This is the part for jsx in the rules:

    {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        include: [
          path.resolve(__dirname, '../src'),
        ],
        query: {
          // https://github.com/babel/babel-loader#options
          cacheDirectory: isDebug,

          // https://babeljs.io/docs/usage/options/
          babelrc: false,
          presets: [
            // A Babel preset that can automatically determine the Babel plugins and polyfills
            // https://github.com/babel/babel-preset-env
            ['env', {
              targets: {
                browsers: pkg.browserslist,
              },
              modules: false,
              useBuiltIns: false,
              debug: false,
            }],
            // Experimental ECMAScript proposals
            // https://babeljs.io/docs/plugins/#presets-stage-x-experimental-presets-
            'stage-2',
            // JSX, Flow
            // https://github.com/babel/babel/tree/master/packages/babel-preset-react
            'react',
            // Optimize React code for the production build
            // https://github.com/thejameskyle/babel-react-optimize
            ...isDebug ? [] : ['react-optimize'],
          ],
          plugins: [
            // Adds component stack to warning messages
            // https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-source
            ...isDebug ? ['transform-react-jsx-source'] : [],
            // Adds __self attribute to JSX which React will use for some warnings
            // https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-self
            ...isDebug ? ['transform-react-jsx-self'] : [],
          ],
        },
      },

I think the `/jsx?$/`regexp it's ok

**Comment by langpavel** [comment]
Okay, I thing so.. But where it can be? @frenzzy can know this in second but I don't. It must be kind of stupid bug I believe

**Comment by ucay** [comment]
Maybe you forget the extension in `package.json` of component.
```javascript
// src/components/MyComponent/package.json
{
    "name": "MyComponent",
    "version": "0.0.0",
    "private": true,
    "main": "./MyComponent.jsx"
}
```

**Comment by JavoByte** [comment]
Is it necessary to have a `package.json` file. I had my files in the same folder. With this file approach, I should have a `folder` per `component` right?

**Comment by ucay** [comment]
I think, that's the structure of component (in RSK). A folder per component.
A component can has it's assets, such as css, images, icons, or other `.jsx` file that used only in the component.
Here's the example of mine:
![example](https://user-images.githubusercontent.com/3348846/26935654-b69be722-4c96-11e7-95d4-99690818c19d.png)

**Comment by Allasudha** [comment]
# ergergerg# 

> ergergergergergr**egergergrgergergerg**

**Comment by savioseb** [comment]
did you try restarting your server. That helped me resolve this. Simply run

```
npm start
```

**Comment by ulani** [comment]
@JavoByte   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
