### ISSUE TITLE
How get store in server side?

### ISSUE THREAD

**Issue by Shadowman4205** [kriasoft/react-starter-kit#1294]
Hello,
how i can get current state of redux store in server side?

**Comment by jonirrings** [comment]
you can get the initial redux store only if you do not share states between session and the initial store.

**Comment by Shadowman4205** [comment]
Yeah i do not need the initial state. Is there way pass  state to server side?
What i need is to disable rest call when user type on adress bar, so i want pass something as token from redux-state (to hooks from feathers) when i dispatch any action to make rest call available only inside app.

**Comment by jonirrings** [comment]
sorry, I dont understand you much.
if you want to share something (we often call it state) between client and server, you may use `session` on server-side, and a `rest?` call from client to server, in order to update the `session` on server.

**Comment by langpavel** [comment]
> What i need is to disable rest call when user type on adress bar

Can you explain?

You can get new store on server for every request. If you need preload something, you can manually dispatch action which loads your previously saved state from session.

It is on you how you create session and what you store in it

**Comment by Shadowman4205** [comment]
Ok i found solution, i am using feathersjs and needed make rest call unavailable to external users and wanted store so i could pass token (wrong way passing security token with redux store).
