### ISSUE TITLE
How to remote debug using WebStorm

### ISSUE THREAD

**Issue by ghost** [kriasoft/react-starter-kit#1299]
Hi, I have some problems remote debugging using WebStorm. I understand the project is using BrowserSync but just wondering if it is possible to attach webstorm debugger as well. Thank you!

**Comment by vincentjames501** [comment]
+1

**Comment by langpavel** [comment]
Personally I don't need debug session, but it can be possible debug it as any node process on the server.
It should be possible debug app in the browser too but really, if you need debug something in this kit, you should extract the thing as separate library instead I believe

**Comment by trungtin** [comment]
I can debug the server code with Webstorm (2017.2) by:
package.json: `"start": "babel-node tools/run start"`   =>   `"start": "babel-node $NODE_DEBUG_OPTION tools/run start"`
tools/runServer.js: `server = cp.spawn('node', [serverPath], {`   =>   `server = cp.spawn('node', ['--debug --debug-brk', serverPath], {`

and start normally. Not sure how to debug with VSCode

And for the client side code, the chrome dev-tools debugger work properly

**Comment by Tsvetkovv** [comment]
@trungtin, 

> and start normally

do you start as npm task with debugging? Or node task?

I run as npm task, but I face with trouble: `only one instance of babel-polyfill is allowed` what imports only in webpack.config.js: `server: ['babel-polyfill', './src/server.js']`
Even if I remove it from server-side config, my app runs but doesn't stop on Webstorm's breakpoints
P.S. For Windows: `"start": "babel-node %NODE_DEBUG_OPTION% tools/run start"`

**Comment by trungtin** [comment]
@Tsvetkovv oh sorry, my mistake. I also add an npm script like this 
<img width="1084" alt="screen shot 2017-10-19 at 12 46 47 pm" src="https://user-images.githubusercontent.com/8097699/31756006-bf06b64c-b4cb-11e7-97bb-6787209d526f.png">

And then I use `Debug 'start'` in `Run` menu to start

**Comment by Tsvetkovv** [comment]
@trungtin, thank you. The problem with babel-polyfill is gone.
But WS can't attach debugger to my code. After 20-30 sec the connection is refused.
node v.8.6.0, also I tried to `--inspect` instead of `--debug`

**Comment by trungtin** [comment]
OK, the last time I can debug this project with WS is because the project is base on feature-apollo branch. And now when trying with another project fork from master branch, I cannot use WS debugger anymore. have anyone got solution for this?

**Comment by ulani** [comment]
Thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
