### ISSUE TITLE
Create Yeoman template for this project

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#13]

**Comment by honkskillet** [comment]
Cool.  Any ideas for sub-generators for this?

**Comment by sdiaz** [comment]
great! thanks

**Comment by luckylooke** [comment]
@alduro I was getting here from yeoman webpage via react-fullstack name of generator.. is it same generator as flux-webapp?

**Comment by jhabdas** [comment]
Be really cool to create [some generators](https://github.com/trunkclub/brunch-with-panache/tree/master/generators) to stub out new components so there's less manual effort to get yourself on a tear. WDYT?

**Comment by koistya** [comment]
@jhabdas yep, that would be nice. There is a minimum Yeoman generator template located at [yeoman-generator](https://github.com/kriasoft/react-starter-kit/tree/yeoman-generator) branch. Contributions are welcome!
