### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by cmnstmntmn** [kriasoft/react-starter-kit#130]
PostCSS is used by Google, Twitter, Alibaba, and Shopify. Its plugin, Autoprefixer, is one of the most popular CSS processors.

PostCSS can do the same work as preprocessors like Sass, Less, and Stylus. But PostCSS is modular, 3-30 times faster, and much more powerful.

https://github.com/postcss/postcss

**Comment by koistya** [comment]
Just have plugged PostCSS into webpack's bundling pipeline.

**Comment by cmnstmntmn** [comment]
:+1: great
