### ISSUE TITLE
Socket.Io client on Server Side returns error  - I can not make Socket.io client working on SSR

### ISSUE THREAD

**Issue by ibudisteanu** [kriasoft/react-starter-kit#1307]
Because my Server Side Rendering is making a lot of requests to the REST Backend (that is connected with DB), I don't want to make enormous number of http requests and instead I want to use the web socket.io framework.

Thus, I have created the SocketWorker - a singleton Socket.Io client. The SocketWorker works executed in the browser (using the componentDidMount from React Starter kit), **but it fails connecting in the server side rendering.** Moreover, the socket is trying to re-connect in a loop, and it fails with the same error every time.

```
class SocketWorkerClass {

  socket = null;

  sServerSocketAddress = "myskyhub.ddns.net:4000/";
  sServerSocketApi = "api/";

  sServerSocketVersion = "";

  startService() {
    this.createClientWorkerSocket();
  }

  createClientWorkerSocket() {

    console.log("Trying to create Worker Socket ...");

    this.socket = io.connect(this.sServerSocketAddress , {
        //transports: [ 'xhr-polling' ],
        //transports: ['xhr-multipart'],
        //transports: ['polling'],
        //transports: ['websocket'],
        transports: ['websocket', 'polling'],
        port:4000,
      } );

//i have been trying all the above transports

    this.setSocketReadObservable("connect").subscribe(response => {
      console.log('SocketWorker has connected to the server!');
    });

    this.socket.on("connect_failed",function () {
      console.log('SocketWorker Connecting failed 222');
    });

    this.setSocketReadObservable("connect_error").subscribe(response => {
      console.log('SocketWorker Connecting Error ',response);
    });

    this.socket.on("error",function () {
      console.log('SocketWorker error 222');
    });

  }
.....

```

I have tried to place my WorkerSocket everywhere in the server.js and it fails.

```
let SocketWorkerFile = require('./utils/socket-worker/SocketWorker');
let SocketWorker = SocketWorkerFile.default.SocketWorker;
```

but it fails returning two types of errors:

If I use the **default transport** (no transporation config), I receive a strange error:

![image](https://user-images.githubusercontent.com/17750489/27015572-5dddbd6a-4f19-11e7-8553-548b2e19ed0c.png)

if I use the  `transports: ['websocket', 'polling'],` it returns me the following error:

![image](https://user-images.githubusercontent.com/17750489/27015595-5d65b4f4-4f1a-11e7-9299-c5b67d4bf0e6.png)

![image](https://user-images.githubusercontent.com/17750489/27015563-1e91938e-4f19-11e7-8aec-ed000f56745a.png)

**Comment by langpavel** [comment]
Refer to `socket.io` what they recommending for use on server.

BTW if you end using polling, you probably make more requests with `socket.io` then what you did with HTTP rest.
If you want aggregate your API, look at GraphQL, I believe you can setup websocket transport for GraphQL too ;-)

**Comment by ibudisteanu** [comment]
So, you are saying it is a socket.io issue/miss-configuration. I think, you are right, because even on a server-side rendering Vue.js project i still get the same exact error code. I know about GraphQL, but I don't want to use it at the moment.

The answer solving this problem will be a snippet of doing a client socket.io on a simple express.js (SSR)

**Comment by langpavel** [comment]
@ibudisteanu Yes, `socket.io` is possibly only client side library. On server it makes sense to use TCP directly, or some pub-sub service like Redis, RabbitMQ, ZeroMQ... there are hundreds of better fitting solution.
You can build a thin layer for WebSockets on top of this services which will can have stronger security validation.

**Comment by ibudisteanu** [comment]
Isn't websock a TCP connection directly? But, why the websock client can not work on a server side rendering and can work a server side rendering as a server (listener).

**Comment by langpavel** [comment]
@ibudisteanu Look at [`ws`](https://www.npmjs.com/package/ws). This can work for you.

> Isn't websock a TCP connection directly?

No. It will be insane to allow make every browser on the world a tool of attack :-D
Websockets are build on top of HTTP `Connection: upgrade` feature and have defined protocol for messages.

**Comment by ulani** [comment]
@ibudisteanu   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
