### ISSUE TITLE
Failed to load resource 404 all js files can't load on safari

### ISSUE THREAD

**Issue by promin04** [kriasoft/react-starter-kit#1308]
![screen shot 2560-06-12 at 10 57 25 am](https://user-images.githubusercontent.com/19229309/27018930-671aa042-4f5e-11e7-8628-d9b6632eddf9.png)

i just clone repo -> npm install -> npm start 
the result as picture above js files can't run.
is there solution for this problem?

**Comment by frenzzy** [comment]
In development mode the app is available on the 3001 port: http://localhost:3001/
[Getting Started → Yarn start](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md#3-run-yarn-start)
