### ISSUE TITLE
Using dotenv for local development environment

### ISSUE THREAD

**Issue by archansel** [kriasoft/react-starter-kit#1309]
Hi, I tried to use dotenv for my local environment, I read #1240 and @langpavel already succeed but I cant get it work. I use `require('dotenv').config();` on top of config.js file and put my `.env` in root folder but it still doesn't work, any suggestion?

**Comment by archansel** [comment]
I figure it out, thank

**Comment by jandramila** [comment]
Hello there, i'm having some troubles using dotenv.

While I'm able to use it and get my ENV vars on development, I can't make it work at Heroku, as every asset get's built on localhost whenever I deploy to staging (so env variables declared at heroku app are ignored).

Is there any workaround for this?

**Comment by hakunin** [comment]
Can you guy share how you made it work? I am just trying to customize the port.

**Comment by archansel** [comment]
This is what I do in my `config.js`
```
import dotenv from 'dotenv';
dotenv.config({ path: '.env/env.dotenv' }); // path to your .env file, by default it will use .env in root folder

export const port = process.env.PORT || 3000;
```

**Comment by hakunin** [comment]
I ended up doing this and confirming that port is 4000.

```
require('dotenv').config({path: '.env'})
console.log('PORT', process.env.PORT);
```

However, when starting it it says 3000 and its not running on port 4000.
