### ISSUE TITLE
Question: Composition vs. Inheritance in decorators

### ISSUE THREAD

**Issue by AndrewRevinsky** [kriasoft/react-starter-kit#131]
@koistya , I really liked how you wrapped a certain functionality in decorators `withStyles`, `withContext` and so on. I have a question, why did you choose to compose a wrapped component inside rather then just inherit from it?

I attempted to create my own decorator for pages that need authentication. I called it, naturally, `withAuth`. The best way to accomplish this task, it turned out, was to involve inheritance.

Let me demonstrate it with this gist: https://gist.github.com/AndrewRevinsky/ff9e39f4f1a93948b25b
(If you like my implementation, please feel free to use it.)

So, my question again: why composition and not inheritance in your cases?

**Comment by koistya** [comment]
Maybe it's better to get user instance from a store.. for example:

```js
class MyComponent {
  render() {
    let user = store.getCurrentUser();
    if (user.isAuthenticated) {
      return <div>Hello, {user.userName}!</div>;
    } else {
      return <div>Hello, Guest!</div>;
    }
  }
}
```

**Comment by koistya** [comment]
Or, separate your components into dumb component + a container component for it. For example:

```js
// Listen to stores etc., has no any markup
class MyComponent extends Component {
  constructor() {
    super();
    this.state = { user: store.getCurrentUser(); }
    store.onCurrentUserChanged(user => this.setState({user});
  }
  render() {
    return <MyComponentUI user={this.state.user} />;
  }
}

// Only markup
class MyComponentUI {
  render() {
    if (user.isAuthenticated) {
      return <div>Welcome, {user.userName}! | <button>Logout</button></div>;
    } else {
      return <div><button>Login</button> | <button>Signup</button></div>;
    }    
  }
}
```

**Comment by AndrewRevinsky** [comment]
@koistya , I came acrross this pattern after realizing I'm copy-pasting a bunch of code a couple of times. 
Your comments only stress on this thing: you need to drag the same code from page to page.
Whereas in my example of `withAuth` decorator for pages, you simply create a page class and mark it with this decorator. After this, the page assumes it is viewed by a logged in user. It doesn't have to contain this logic to - once again - test if the user is logged in or not. The user is logged in by declaration - you request that the page's logic and markup ran only in this case.

Your comments by the way touched the Navigation component, and not the entire page, too. I agree, this Component doesn't have a need with this sort of decorator.

1. My initial question, though, was regarding the strategy that you used: why picking Composition (i.e. wrapping a component in another component) and not Inheritance (i.e. create a class that inherits from the component being decorated)?

2. Another question. It turns out, components are instantiated with a couple of arguments: `props` and `context`, I believe. And it seems it's a must to pass them to `super()` constructor. Otherwise they will be lost. Is it truly undocumented thing or did I miss something?

**Comment by AndrewRevinsky** [comment]
@koistya I liked your separation example, by the way. Thank you.

**Comment by koistya** [comment]
@AndrewRevinsky did you see this article by @gaearon? https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by AndrewRevinsky** [comment]
@koistya As a matter of fact, no I didn't. :+1: Thank you, I'll follow it up and then may or may not return with the question. :wink:

**Comment by PhilippKrone** [comment]
@koistya I like your way of separating UI and logic. For example you have a button and an input field and would like to do something with the input text onClick - how would you ideally do that taking into account a full separation of UI and logic?

**Comment by AndrewRevinsky** [comment]
@koistya I haven't been able to voice my opinition elsewhere just yet, so here I go here: I don't understand *why is there a bias between* **inheritance** *and* **mixing-in***?* These are two separate methodics of stitching functionalities together. Mixing-in is nothing like inheritance. It seems so at first, maybe. But it isn't. They, mixins, seem like a real evil. I feel lucky enough to having dived into React at the moment of parting with mixins altogether. And I don't understand why all authors pull it up when inheritance is mentioned.
Now, coming back to compositing. I feel very cautious towards this pattern: seems like you have to be real careful not to rely on state of the wrapped component, you have to pass every property and field down.. These, to name a few. Also, creating an extra node for the super component feels.. uhmm.. strange.
I am sure, the practice can find justification for both methods: compositing *and* inheritance, not just the first. Like, a set of conditions one of the two will seem more preferable than the other, and vice versa.
What do you think?

**Comment by koistya** [comment]
I haven't yet encountered a use case where I would want to use inheritance or mixins while creating React components. Do you have an example, where this could be justified?

If you don't want to test your UI components in isolation, then you don't need to bother creating these wrapper components mentioned above. BTW, have you seen this presentation regarding "Pure" and "Container" components approach used at Facebook?

##### Making your app fast with high-performance components ([React.js Conf 2015](http://www.youtube.com/watch?v=KVZ-P-ZI6W4&list=PLb0IAmt7-GS1cbw4qonlQztYV1TAW0sCr))
[![img](http://img.youtube.com/vi/KYzlpRvWZ6c/0.jpg)](http://www.youtube.com/watch?v=KYzlpRvWZ6c)

**Comment by AndrewRevinsky** [comment]
@koistya Why does the word 'mixins' even have to come up when 'inheritance' mentioned? I.e. your words: "inheritance or mixins". I am against mixins, I stated so earlier. (I'll bring up proof need be.) It is like an outsider, ever. OOP has its weight, it has proven itself useful for this many years. So inheritance is something worth at least taking a look at. Mixins - are just a crutch for the no OOP-land. Javascript's outlawed son. When we deal with ES6 - with language support for inheritance, then no more crutches. We need to stop even mentioning the M word. 
So I take your question to be as *"[..] a use case where I would want to use inheritance while creating React components. Do you have an example, where this could be justified?"* I can live with that. :smile: And I'll be on the lookout for this. Please hold this question-issue open for a while. Perhaps, other readers might be faster than I, too. I am all for it.
Thank you for the presentation! I haven't. But I will.

**Comment by langpavel** [comment]
Sorry guys, I think this is little off topic. My answer is composition. High Order Components is functional answer to object composition and here we are :-)

So, I'm closing this.
