### ISSUE TITLE
inject component inside html provided by DB

### ISSUE THREAD

**Issue by ricardomoura** [kriasoft/react-starter-kit#1313]
atm i changed the default RSK routing for the client point in order to fetch all the pages available from a DB then dynamically i inject them into the router. 
it works, but i dont know how to load the component returned in the html string.

```
	import Router from 'universal-router';
	import routes from './routes';
	import Page from '../components/Page';
	import React from 'react';
	
	import ReactDOMServer from 'react-dom/server';
	import ReactDOM from 'react-dom';
	import { Parser as htmlToReact } from 'html-to-react';

	import languageswitcher from '../components/LanguageSwitcher';

	export const generateClientRoutes = function({entries}) {

	routes.children = [];

	entries.forEach(page => {

		let parsedHTML = new htmlToReact();
		const newRootElement = parsedHTML.parse(page.body);
		
		// let body;

		// if (process.env.BROWSER) {
		// 	body = ReactDOM.render(newRootElement);
		// }

		// if (process.env.SERVER) {
		// 	body = ReactDOMServer.renderToStaticMarkup(newRootElement);
		// }
		

		routes.children.unshift({
			path: page.path,
			children: page.childrens || [],
			async action() {
				return {
					title: page.title,
					component: <Page id="master" title={page.title}>{newRootElement}</Page>
				}
			}
		})
	});

	routes.children.push(require('./routes/notFound').default);
	return new Router(routes);
};
```

on the src/server.js
i dispatch an action to reduce the pages, then send it to the generateClientRoutes. i reused the default starting point of routes then i append to the childrens array the pages.

any help?
thanks

**Comment by ucay** [comment]
Dynamic routes already supported.
Pleas check [tools/render.js](https://github.com/kriasoft/react-starter-kit/blob/master/tools/render.js#L37)
```javascript
// add dynamic routes
// const products = await fetch(`http://${server.host}/api/products`).then(res => res.json());
// products.forEach(product => routes.push(
//   `/product/${product.uri}`,
//   `/product/${product.uri}/specs`
// ));
```

**Comment by ricardomoura** [comment]
ucay im aware of that but thats no the case. i actually have a html string and i need to parse it as JSX

**Comment by frenzzy** [comment]
@ricardomoura configure webpack to generate a chunk/bundle/lib from jsx string, then use [bundle-loader](https://github.com/webpack/webpack/tree/master/examples/code-splitting-bundle-loader) to import the result at runtime.

**Comment by ricardomoura** [comment]
thanks for the suggestions, we ended up using a redux tree of components with props and so .. we even made a page builder using the node. cheers
