### ISSUE TITLE
Single Page Applications + ReactJS

### ISSUE THREAD

**Issue by SmboBeast** [kriasoft/react-starter-kit#1316]
Hi everyone,

I'm not sure if this is the correct place to post this, but I hope posting this might help others as well.  I've tried posting this in gitter, but it's been hard getting to the bottom of things.  I'm still trying to figure things out myself.  @koistya was nice enough to direct me in gitter once, but I need more direction...

I also know the RSK in itself is a single page application.  Aside from the initial hit, the client is responsible for subsequent page requests, and the server isn't being hit again.

My scenario: I have a website where I need a component to never unmount, even when requesting other pages.  Think of a global upload component where the user can be continuing to upload files while continuing to do other work on the website.  Basically I will have two main containers on every page: an upload container, and a body container.  I only need the body container updated and rerendered.

Here is the approach I have thought about until now.  I'm hoping someone can tell me if it makes sense or if I'm wasting my time and should look into a different approach.

1. Create a new middleware handler in Node to handle new AJAX requests for pages.  This will just render the new markup that needs to be shown to the user, similar to the app.get('*') we have now.
2. Hijack all page requests (maybe using the Link component) and force to hit this AJAX call, instead of allowing the default anchor action take place by the browser.
3. Take the AJAX response and dispatch an action within the Link component to let ReactJS rerender every component that's connected automatically.
4. Somehow update the url to show the correct url.

What I am not understanding fully is what happens to all the event handlers that may be associated with the new HTML that needs to be rendered?  Would clicking buttons to do certain actions work?

Will this even work or should I be looking at a different approach?  Maybe looking at creating a route like normal, so that the RSK can handle the routing, url changes, and such like normal?  But then I have no idea how I can make only a portion of each page render.  

Any help is appreciated!  I'll continue to try and figure this all out.

**Comment by langpavel** [comment]
Hi. You can place component in Layout. As far as Layout instance can be clearly reused, it should persist. But if you need some state to be guaranteed, you can use Redux and do the work outside, thing about it as a service. As far as your app will stay SPA you will have this redux state and you can subscribe to state updates.
You can also install a handler that will ask user if he really want leave page with upload in progress.

**Comment by SmboBeast** [comment]
Hey @langpavel,

Thanks for responding.  Actually, I was thinking something like this also.  

I thought I could let the RSK handle everything as needed.  In every routes\[route]\index.js page, I could have something like the following:

```
<Layout>
  <GlobalUpload />
  <div id="pageContent">
    <ComponentA />
    <ComponentB />
    ...
  </div>
</Layout>
```

This way, the RSK will handle the url changes, and everything else as normal.

The only thing I don't know about this approach is if the GlobalUpload component will refresh and rerender as well since it's part of this whole piece?  The whole point is for that GlobalUpload component to stay intact while the rest of the page is being updated to the new page...

Does React only update/render whatever is being changed or does it always rerender everything all the time?

Regarding the handler and asking the user if they want to leave the page, yes I can do that.  Unfortunately this isn't a viable option, unless it's the only way and somehow technically it's not possible.

I appreciate you.  I will start testing both scenarios now and see what I can come up with.

Thanks,
Sam
