### ISSUE TITLE
Don't clean on start?

### ISSUE THREAD

**Issue by charyorde** [kriasoft/react-starter-kit#1327]
Not sure why we're cleaning on `npm start`. [ref](https://github.com/kriasoft/react-starter-kit/blob/master/tools/start.js#L97)

**Comment by frenzzy** [comment]
To cleanup folder from outdated files. Why do you think that it is not necessary?

**Comment by charyorde** [comment]
`npm run build` builds the project and outputs to build dir. The build dir gets wiped again on `npm start` nullifying the work of `npm run build`. 

`npm start` doesn't build the project again.

**Comment by frenzzy** [comment]
`npm run build` generates files for production, then you can deploy content of the `build` folder to production server.
`npm start` generates files for development, they contain modules which are useful for development only and must not used in production.
Both commands overwrite each other's work, you must not use them together at the same time.

Maybe when webpack will add support for in memory hot module replacement for server side bundles, `npm start` script will not generate anything to the `build` folder.

**Comment by charyorde** [comment]
Thanks. How would you suggest I go about running the `copyDir` task?
```
/* tools/copy.js */
copyDir('node_modules/bootstrap/dist/css', 'build/public/css'),
copyDir('node_modules/bootstrap/dist/fonts', 'build/public/fonts'),
```
At the moment, `npm start` would clean the build dir even though `npm run copy` succeeds.

**Comment by frenzzy** [comment]
Why you don't want to add all static files into public folder without any copying?

Alternatively you can add `await run(copy)` line right after [`await run(clean)`](https://github.com/kriasoft/react-starter-kit/blob/5c0e011666a7a436e9f235d24d0bdd3b759b09dc/tools/start.js#L97) within `tools/start.js` script.

**Comment by charyorde** [comment]
+1 to public folder.
