### ISSUE TITLE
Every time refresh page HMR will disconnect once

### ISSUE THREAD

**Issue by zation** [kriasoft/react-starter-kit#1328]
I cloned the newest repo and run `npm start`. Every time I enter the web page, HMR will disconnect once: connect => disconnect => connect. After disconnect, it won't disconnect agin and works fine. Is this because I enter page before client compiler finish?

<img width="1438" alt="screen shot 2017-06-25 at 4 32 27 pm" src="https://user-images.githubusercontent.com/1049425/27514681-ed72af1c-59c3-11e7-881b-334675b6ef49.png">

**Comment by frenzzy** [comment]
Nope, it because webpack hmr is not compatible with node.js 8 yet

**Comment by frenzzy** [comment]
Looks like this was fixed in node 8.1.1, refs:
- https://github.com/glenjamin/webpack-hot-middleware/issues/210
- https://github.com/nodejs/node/pull/13549

**Comment by zation** [comment]
Thanks for you response. The error is gone when I use node 8.1.2
