### ISSUE TITLE
pagespeed task empty callback in terminal

### ISSUE THREAD

**Issue by cmnstmntmn** [kriasoft/react-starter-kit#133]
when i run

`gulp pagespeed`

i get

`[16:22:38] Requiring external module babel/register`
`[16:22:39] Using gulpfile ~/repos/gg/gulpfile.babel.js `
`[16:22:39] Starting 'pagespeed'... `
`[16:22:39] Finished 'pagespeed' after 486 ms`

the API key is ok an i can see the results [Google Developers Console](https://console.developers.google.com)

**Comment by langpavel** [comment]
Sorry, I cannot imagine what this issue is about.. Closing
