### ISSUE TITLE
assets.json?

### ISSUE THREAD

**Issue by charyorde** [kriasoft/react-starter-kit#1330]
What's its role? Can I add own things to it?

**Comment by frenzzy** [comment]
[assets-webpack-plugin](https://github.com/kossnocorp/assets-webpack-plugin) generates `assets.json` file during compilation (`npm run build`), if you will modify this file manually it will be overwritten during next compilation, I guess it is not what you want.

**Comment by charyorde** [comment]
I see. Thanks
