### ISSUE TITLE
Weird Behavior  http://localhost:3000 changes to //localhost:3001

### ISSUE THREAD

**Issue by Shadowman4205** [kriasoft/react-starter-kit#1349]
Hello,
i have this weird behaviour,
when i put 

> <a href="http://localhost:3000">Test</a>
First i am getting React Reuse Markup warning

> (client) actid="42"><a href="http://localhost:300
>  (server) actid="42"><a href="//localhost:3001/tes

and checking the source page i see this 
`<a href="//localhost:3001">`
instead of
`<a href="http://localhost:3000">`

why happening this change? Does it because localhost:3000 is where server run? Any suuggestion?

**Comment by frenzzy** [comment]
Hey! Can you show us a source code of your component which renders this link?

**Comment by Shadowman4205** [comment]
```
const test = ['http://localhost1:3000',
'http://localhost:3000',]

function LangSwitcher({currentPath }) {
  const isSelected = (locale) => locale === currentLocale;
  return (
    <NavDropdown eventKey={1} title={"TEST"} id="nav-dropdown">
      <MenuItem  eventKey={1+"."+1} href={http://localhost1:3000+ currentPath}>Lang1</MenuItem>
      <MenuItem eventKey={1+"."+2} href={http://localhost:3000 + currentPath}>Lang2</MenuItem>
      })}
    </NavDropdown>
  );
}

LanguageSwitcher.propTypes = {
  currentPath: PropTypes.string,
};

const mapState = (state) => ({
  currentPath: state.location,
});
const EnhancedContent = connect(mapState)(LangSwitcher);
export default withStyles(s)(EnhancedContent);
```
If i change http://localhost:3000 to http://localhost2:3000 its give the same on client and server but only 
http://localhost:3000 give this odd behaviour

**Comment by frenzzy** [comment]
I guess there is [Browsersync](https://www.browsersync.io/) replaces all urls while proxying (3001 → 3000).
After 426556f62290e3ad818cfaa924514663e53da5a2 commit we do not use proxy for dev server anymore.

**Comment by Shadowman4205** [comment]
ohh i am using the version of January. Ok i try remove it and will close the issue.
