### ISSUE TITLE
Security issue: ability to download server.js code

### ISSUE THREAD

**Issue by brunotavares** [kriasoft/react-starter-kit#135]
By enabling express to serve the current directory as static routes, it's possible for the user from the frontend to download server-side code, like server.js

Code:
```
server.use(express.static(path.join(__dirname)));
```

Route to download code:
`http://localhost:5000/server.js`

One suggestion is to wrap all public assets in a `/public` folder of some sort (e.g. `app.use(express.static('public'));`)

**Comment by koistya** [comment]
@brunotavares good catch! Yep, what you're suggesting sounds perfectly good. Need to modify Gulp/Webpack config, so that all public assets are compiled into `/build/public` folder and private assets like `server.js` - into `/build` folder as before.
