### ISSUE TITLE
How to setup Webpack Proxy? 

### ISSUE THREAD

**Issue by ImanMh** [kriasoft/react-starter-kit#1355]
```
devServer: {
    port: 8080,
    proxy: {
      '/user/login': {
        target: 'https://www.mydomain.com',
        changeOrigin: true,
      },
    },
  }
```

I need to setup a proxy like this in my webpack config but sounds like webpack doesn't read my config. How can I fix this?

**Comment by langpavel** [comment]
RSK is using our server, devServer is not in use. You can implement your express based proxy in server.js

**Comment by ImanMh** [comment]
The only helpful proxy that I found is `http-proxy-middleware`. It is very easy to use and you can change the origin easily: 

```
app.use(proxyPathsArray, proxy({
  target: 'https://targetSite.com',
  changeOrigin: true,
}));
```
