### ISSUE TITLE
Seprating appConfig from ServerConfig plus dynamic env configs

### ISSUE THREAD

**Issue by ImanMh** [kriasoft/react-starter-kit#1357]
@koistya
I think server config should be in a separate file from client config. I have added my secret configs to the serverConfig.js and public configs to the appConfig.js and passed appConfig to both client and server. I'm also dynamically loading different configs for different "production" or "development" environments. If you like the Idea I can create a pull request and add it to the starter kit.

**Comment by langpavel** [comment]
There is no client config. You should pass your client config from server by serialize-javascript, save them to window. Otherwise it's not config but just another untouchable bundled in code.

**Comment by ImanMh** [comment]
The kind of config I'm talking about is like base API address, or CDN root directory and etc. These are not the configs you want to change in run-time but you want to change just before build. I know this is possible to pass server config to the client but keeping these two configs separated can be a little more interesting. My opinion is that react starter kit is introducing more than just a react app that has server side rending. So those options must be in a file (`config.js`) and other configs that are related to react must be in a separate file for example `config.js` .

**Comment by langpavel** [comment]
@ImanMh We will not introduce new config file which may confuse users. Current config file is simply proxy for environment variables and this is the right way.
You can create `clientStaticConfig.js` file and use it everywhere you want. But remember, it's just a static code.
> These are not the configs you want to change in run-time but you want to change just before build
Oh, everywhere I hear this, someone else after some time want real config :smiling_imp:

**Comment by ImanMh** [comment]
Hmmm...Perhaps this is the best way to pass configurations to the client and I absolutely agree with you that two configuration files is confusing. The reason I'm working on this issue is that I see one of the basic needs of other users of this project which is loading production and development configurations based on their environment. Is it possible to easily load different config files right now?
by the way since this is not an issue I close it and we can continue the conversation.

**Comment by langpavel** [comment]
> Is it possible to easily load different config files right now?

No, but you can easily set all with environment variables, (even possibly name of file you can then `require(process.env.CUSTOM_CONFIG)` in config)

Or you can use `dotenv` package, it's integration is very easy

**Comment by ImanMh** [comment]
Thanks.
