### ISSUE TITLE
Material-ui RadioButtonGroup doesn't seem to be working with React Starter Kit?

### ISSUE THREAD

**Issue by vu0tran** [kriasoft/react-starter-kit#1358]
I posted this issue on [StackOverflow](https://stackoverflow.com/questions/44994904/radiogroupbutton-doesnt-seem-to-work-with-react-starter-kit) as well.

I'm implementing material-ui's RadioButtonGroup component but it seems like there's something in React Starter Kit that's making it incompatible. Any idea what it could be? 

When I create a fresh webpack of it [here, it works fine,](https://www.webpackbin.com/bins/-KoaaPYxDno695fiUBMn) but when I go through RSK's routing, what I get is something that [looks like this.](https://giphy.com/gifs/3oKIP7arhKhNzNzytq) The buttons are unresponsive.

I've wrapped material-ui in my client and made sure to inject the tap event plugin.

```js
// client.js

import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import injectTapEventPlugin from 'react-tap-event-plugin';
injectTapEventPlugin();

...
...
    appInstance = ReactDOM.render(
      <App context={context}><MuiThemeProvider>{route.component}</MuiThemeProvider></App>,
      container,
      () => onRenderComplete(route, location),
    );
```

```js
import React from 'react';
import { RadioButton, RadioButtonGroup } from 'material-ui/RadioButton';

class Contact extends React.Component {

  render() {
    return (
      <div>
        <RadioButtonGroup name="shipSpeed" defaultSelected="not_light">
          <RadioButton
            value="light"
            label="Simple"
          />
          <RadioButton
            value="not_light"
            label="Selected by default"
          />
          <RadioButton
            value="ludicrous"
            label="Custom icon"
          />
        </RadioButtonGroup>
      </div>
    );
  }
}

export default (Contact);
```

**Comment by langpavel** [comment]
Did you checked browser's console? Any hint there?

**Comment by vu0tran** [comment]
@langpavel Thanks for the reply. The only thing in the console is: "[HMR] connected".

If it would help, I can create a fresh React Starter Kit project with Material-UI and push it to Git.

**Comment by langpavel** [comment]
sorry, I don't know

**Comment by vu0tran** [comment]
Some more information that might help is that this is only happening on latest Chrome browser: Version 60.0.3112.50.

Works as expected on Safari / Firefox.

**Comment by langpavel** [comment]
Then it's really weird. Did you open issue on Material-ui? I'm almost sure that it's not connected to RSK

**Comment by kamaz** [comment]
@vu0tran I was hit with the same problem, it looks like the problem is with BrowserSync and its option **Sync Options** on **Clicks**. After disabling it material-ui works. 

Although I'm not sure if the problem is with BrowserSync or material-ui.

**Comment by langpavel** [comment]
So It's development trouble? It works when you build?

**Comment by kamaz** [comment]
yes all works when it's build, and it only effects development process

**Comment by CostaRico** [comment]
+1 
browserSync({
	port: 3000,
	ui: {
		port: 3001
	},
	ghostMode: false, // <-  

Thx to @kamaz

**Comment by kevinpaulretiban** [comment]
@CostaRico Thank you! That solved that issue I'm having.

**Comment by ulani** [comment]
@vu0tran   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
