### ISSUE TITLE
[feature/Apollo] Error on page refresh: Cannot match against 'undefined' or 'null'. 

### ISSUE THREAD

**Issue by tim-soft** [kriasoft/react-starter-kit#1360]
On the [feature/apollo] branch, I have a very basic component that receives data from a GraphQL query. When I go to this page, the query returns all of the data I would expect.
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import { graphql } from 'react-apollo';

import getChannelsandUsersQuery from './getChannelsandUsersQuery.graphql';

class SendMessageForm extends React.Component {
  render() {
    return (
      <div>
        Test
      </div>
    );
  }
}

export default graphql(getChannelsandUsersQuery)(SendMessageForm);
```

If I refresh the page, the app throws a big error:
```
Error: GraphQL error: Cannot match against 'undefined' or 'null'.
    at new ApolloError (C:\Users\asdf\Desktop\asdf\node_modules\apollo-client\src\errors\ApolloError.js:32:28)
    at C:\Users\asdf\Desktop\asdf\node_modules\apollo-client\src\core\QueryManager.js:281:41
    at C:\Users\asdf\Desktop\asdf\node_modules\apollo-client\src\core\QueryManager.js:726:25
    at Array.forEach (native)
    at C:\Users\asdf\Desktop\asdf\node_modules\apollo-client\src\core\QueryManager.js:723:27
    at Array.forEach (native)
    at QueryManager.broadcastQueries (C:\Users\asdf\Desktop\asdf\node_modules\apollo-client\src\core\QueryManager.js:720:42)
    at QueryManager.broadcastNewStore (C:\Users\asdf\Desktop\asdf\node_modules\apollo-client\src\core\QueryManager.js:71:14)
    at C:\Users\asdf\Desktop\asdf\node_modules\apollo-client\src\ApolloClient.js:45:44
    at C:\Users\asdf\Desktop\asdf\node_modules\redux-thunk\lib\index.js:14:16
    at Object.dispatch (C:\Users\asdf\Desktop\asdf\node_modules\redux\lib\applyMiddleware.js:45:18)
    at C:\Users\asdf\Desktop\asdf\node_modules\apollo-client\src\core\QueryManager.js:657:33
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)
```
I am still on the new side to react/graphql and this is a real head scratcher, can someone point me in the right direction so that refreshes do not break the app?

**Comment by manhhailua** [comment]
@tim-soft I got the same error when I passed an object (imported from another file) to express-graphql context option then called that context on a resolver. It took me one week to find out.
Did you do something similar to this in one of your resolvers?
```
content: {
  type: StringType,
  resolve: (news, args, { butcher }) => { // Error from here
    console.log(butcher);
    return news.content;
  },
},
```

**Comment by tim-soft** [comment]
Yes! This appears to be exactly my issue. I'm passing various objects into these resolver functions as context. Only my queries that receive objects as context will crash the app if I refresh the page

Is this an SSR issue or is their a better pattern for passing data/functions to resolvers?

**Comment by manhhailua** [comment]
Honestly, for this moment, I have no solution other than not passing something to context. Sorry! Need someone better understand graphql context tell us about the root cause. If no, I'll give it a shot next week, when I have time :(.

**Comment by tim-soft** [comment]
There appears to be some disconnect between server and client apollo 

Just adding stuff to the middleware context causes problems with SSR, but adding the same context beneath allows queries to run without crashing. I'll need to keep digging as I don't understand why this helps
```javascript
//server.js
// Register API middleware
// -----------------------------------------------------------------------------
const graphqlMiddleware = expressGraphQL(async req => ({
  schema,
  context: {
   // Add some stuff
  },
  graphiql: __DEV__,
  rootValue: { request: req },
  pretty: __DEV__,
}));

//
// Register server-side rendering middleware
// -----------------------------------------------------------------------------
app.get('*', async (req, res, next) => {
  try {
    const css = new Set();

    const apolloClient = createApolloClient({
      schema,
      rootValue: { request: req },
      context: {
        // Add the same context stuff here
      }
    });
```

**Comment by manhhailua** [comment]
@tim-soft : actually, I'm having the same thought about "something wrong with server side rendering" ... please let me know if you figure it out.

**Comment by tgdn** [comment]
Happens to me also, any fix?

**Comment by langpavel** [comment]
Hi all. Thank you for using this stuff.
It should be all OK now. And if not...

# *all cases I've seen before:*

* At first, if it works with SSR, it *should* works always. If not, there *is* the error in client code.
Not so bad, but you should delete all your client and start again with isomorphics :smiling_imp: 

* At second, if it works on client, it should work with SSR.
Opposite only indicates that you have inconsistencies (probably (only) in routing) and this cannot be the very nasty. So you only need holydays for management. Try tell them you only need them at lost island in Pacific :smiling_imp: 

* At third. It should be independent. Really. This kit have performance benefit from the fact, that everything **node** related is on one place, so no loops. All GraphQL is evaluated in-place as any other promise. This is main advantage. But you must be prepared for splitting this away at any time. So, this is only *promised* advantage as far as your needs will be under hundred per second. After that you should create new two **package.json** files and run multiple of them on multiple machines near to DB. But wait. You can do this by current design as well, so if you want.. Use half of stack twice. Front or back parts only, your choice.
You should consider that less barriers always have better times, so why make additional request/response cycle if there is built-in loopback including all request specific auth/route/any mechanisms of your wish. This can be called **my greatests arguments against process branching**, like if you can — without penalty — you should execute same code in same process!

**Comment by altsab** [comment]
@tim-soft @manhhailua  try to pass your context as contextValue key, like so:

```
const apolloClient = createApolloClient({
      schema,
      rootValue: { request: req },
      contextValue: {
        // Add the same context stuff here
      }
    });
```

**Comment by ulani** [comment]
@tim-soft   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
