### ISSUE TITLE
Websockets with new Isomorphic Hot Module Replacement 

### ISSUE THREAD

**Issue by pdeszynski** [kriasoft/react-starter-kit#1362]
Hello,

I'm looking for a way to integrate websockets into an app with current version of HMR, after changes being made to the start script.

In previous version I could easily access http server to attach WS capability (exactly Apollo Subscriptions server for GraphQL Subscriptions)

```js
// server.js
//...
import { createServer } from 'http';
import { SubscriptionServer } from 'subscriptions-transport-ws';

// ...
const server = createServer(app);
server.listen(config.port, () => {
    console.info(`The server is running at http://localhost:${config.port}/`);
    SubscriptionServer.create({
      subscriptionManager,
    }, {
      server,
      path: config.subscriptions.path,
    });
  });
```

With current way the HMR is done Browsersync's server is used. I was thinking to attach own websocket server directly to Browsersync's by changing a little start script like:

```js
// start.js
// ...
// Launch the development server with Browsersync and HMR
const b = await new Promise((resolve, reject) => browserSync.create().init({
    // https://www.browsersync.io/docs/options
    server: 'src/server.js',
    middleware: [server],
    open: !process.argv.includes('--silent'),
    ...isDebug ? {} : { notify: false, ui: false },
}, (error, bs) => (error ? reject(error) : resolve(bs))));

SubscriptionServer.create({
      subscriptionManager,
}, {
      b.server,
      path: config.subscriptions.path,
});
```
this enables GraphQL subscriptions but sadly breaks socket.io in Browsersync, so no HMR then (probably overrides socket.io from BS server).

I'm looking for a hint how could it be implemented with current setup, without Browsersync's proxy. Is it at all possible to be done this way?

**Comment by lobnico** [comment]
I use them and they work fine with "yarn start" script so far, HMR too.

**Comment by piteer1** [comment]
@lobnico do you use latest version of React Starter Kit and are you sure that the websocket connection you see is only the one Browsersync uses for HMR and not your app's websockets?

If yes, then how do you attach your own socket.io handlers? To attach any events you need to have a socket.io server reference and to create a socket.io server you need a reference to http server. Traditionally you do it this way:

```js
const app = express();
const server = http.createServer(app);
const io = socketioServer(server);
io.on('connection', () => do_something);
```

With new version even if you do this way, this server is never started when HMR is turn on:
```js
//
// Launch the server
// -----------------------------------------------------------------------------
const promise = models.sync().catch(err => console.error(err.stack));
if (!module.hot) {
  promise.then(() => {
    server.listen(config.port, () => {
      console.info(`The server is running at http://localhost:${config.port}/`);
    });
  });
}
```
so the listen is never executed (and it shouldn't be because you would end with 2 servers being started on the same ports).

Requests from browsersync's server are just forwarded to the the app with this code:

```js
server.use((req, res) => {
  appPromise.then(() => app.handle(req, res)).catch(error => console.error(error));
});
```

but i'm not sure if something similar would be possible with Websockets.

So summarizing, your websockets shouldn't work as your server with attached handlers probably shouldn't be started, but maybe I'm missing something. 😄

**Comment by lobnico** [comment]
Well, not sure with a separate ws server instance; but subscriptions-transport-ws can be attached along 
with same server instance (same address/port) with a different path
e.g. server is running on http://smthin:3000, 
graphql on http://smthin:3000/graphql 
apollo websocket interface on http://smthin:3000/subscribs

To have it working you will have to update starter kit dependencies, 
here s my corresponding packages used

>     "apollo-client": "^1.4.2",
> 
>     "graphql": "^0.10.3",
>     "graphql-server-express": "^1.0.0",
>     "graphql-subscriptions": "^0.4.3",
>     "graphql-tag": "^2.4.0",
>     "graphql-tools": "^1.1.0",
> 
>     "subscriptions-transport-ws": "0.8.0",
But I might not have understood well your question.

**Comment by piteer1** [comment]
@lobnico yes, it's exactly as you write, you can attach to a single server using different paths. But in the newest React Starter Kit your server from `server.js` file is not run at all when you use Hot Module Reload. Instead of that Browsersync's server is started, which has already websockets server attached and you cannot simple attach there another WS server on different path. So you cannot anymore do

```js
// server.js
const app = express();
const server = createServer(app);
const io = socketioServer(server);
io.on(...);
```

Because this server will be never run.

If i don't use HMR then this works as it should and it's really easy. It's also simple in older versions of React Starter Kit (before this PR https://github.com/kriasoft/react-starter-kit/pull/1317).

I'm thinking if it would be possible to get Browsersync's socket.io reference and then proxy requests or somehow get the direct socket reference and pass it to `SubscriptionServer` for reuse, but I'll have to dig further. Just wondering if there's better / easier way to achieve it.

**Comment by lobnico** [comment]
" Instead of that Browsersync's server is started, which has already websockets server attached and you cannot simple attach there another WS server on different path. "

Well I tried to but I can't reproduce any error described :3 

- inspiration from sysGearsApp starter kit, they have some subscription server rolling along with
hotreload. I ve tried to remove the "hot.module" parts but it doesn t seem to affect anything :3 

- using 'graphql-server-express' instead of graphql-server,
not sure if it would have an incidence. Here s what I use

```
// ./core/server/subscriptions.js
import { SubscriptionServer } from 'subscriptions-transport-ws';
import { execute, subscribe } from 'graphql';

import schema from '../../data/schema';
import log from '../log'

// private var
let subscriptionServer;


const addSubscriptions = httpServer => {
  subscriptionServer = SubscriptionServer.create({
    schema,
    execute,
    subscribe,
    onConnect: (connectionParams, webSocket) => {
      console.log({ connectionParams,  })
      return ({ connectionParams,  })
    },
  },
  {
    server: httpServer,
    path: '/subs',
  });
};

const addGraphQLSubscriptions = httpServer => {
  if (module.hot && module.hot.data) {
    const prevServer = module.hot.data.subscriptionServer;
    if (prevServer && prevServer.wsServer) {
      log.debug('Reloading the subscription server.');
      prevServer.wsServer.close(() => {
        addSubscriptions(httpServer);
      });
    }
  } else {
    addSubscriptions(httpServer);
  }
};

if (module.hot) {
  module.hot.dispose(data => {
    try {
      data.subscriptionServer = subscriptionServer;
    } catch (error) {
      log(error.stack);
    }
  });
}

```
```

// --- Server.js
export default addGraphQLSubscriptions;

import { graphqlExpress as expressGraphQL, graphiqlExpress } from 'graphql-server-express';
import addGraphQLSubscriptions from './core/server/subscriptions';
// [ . . .]


//
// Launch the server
// -----------------------------------------------------------------------------
let server = http.createServer(app);
addGraphQLSubscriptions(server);

const promise = mongoConnector.sync().catch(err => console.error(err.stack));
if (!module.hot) {
  promise.then(() => {
    server.listen(config.port, () => {
      console.info(`The server is running at http://localhost:${config.port}/`);
    });
    server.on('close', () => {
      server = undefined;
    });

  });
}

//
// Hot Module Replacement
// -----------------------------------------------------------------------------
if (module.hot) {
// no idea at all about this part usefulness / functionalness
  app.hot = module.hot;
    module.hot.dispose(() => {
      try {
        if (server) {
          server.close();
        }
      } catch (error) {
        console.error(error.stack);
      }
    });
// no idea at all about this part usefulness / functionalness
    module.hot.accept(['./core/subscriptionServer', './router'], () => {
      try {
        addGraphQLSubscriptions(server);
        console.log("attached addGraphQLSubscriptions to module.hot")
      } catch (error) {
        console.error(error.stack);
      }
    });

}

```

**Comment by piteer1** [comment]
@lobnico thanks for the code, I'll test it if it solves my problem also.

**Comment by Asthor** [comment]
Someone have a solution ?

**Comment by piteer1** [comment]
@Asthor for now I've reverted to the Proxy mode using the older `start.js` script from this version https://github.com/kriasoft/react-starter-kit/blob/a8fa75d5d2d6c252a73e08c3d8c705e812b90f89/tools/start.js

and added ```ws: true``` option to the proxy settings for Browsersync. Didn't have time to dig deeper.

**Comment by tim-soft** [comment]
@Asthor I solved this problem by giving the socket server it's own port and then managing it's creation/destruction via HMR's dispose/accept functions like what @lobnico proposed.

Doing it this way accomplishes two things:
- [X] Browser-Sync and your own socket server can coexist
- [X] The socket server won't break HMR/crash the app when it goes to reload

Assuming you have the latest version of RSK (after start.js got redone)

Add a value for your socket port in /src/config.js (I call it subPort)
```javascript
module.exports = {
  // Node.js app
  port: process.env.PORT || 3000,

  // GraphQL subscriptions websocket port
  subPort: process.env.SUB_PORT || 4040,

{Stuff...}
```

Create /src/core/server/subscriptions.js
```javascript
import { SubscriptionServer } from 'subscriptions-transport-ws';
import { execute, subscribe } from 'graphql';
import schema from '../../data/schema';

let subscriptionServer;

const addSubscriptions = httpServer => {
  httpServer.listen(4040, () => { // This is where the magic happens
    SubscriptionServer.create({
        execute,
        subscribe,
        schema,
        onConnect: (connectionParams, webSocket) => {
          console.log({ connectionParams,  })
          return ({ connectionParams,  })
        },
      },
      {
        server: httpServer,
        path: '/subscriptions'
      },
    );
    console.log(`App's websocket is listening on port ${httpServer.address().port}`);
  });
};

const addGraphQLSubscriptions = httpServer => {
  if (module.hot && module.hot.data) {
    const prevServer = module.hot.data.subscriptionServer;
    if (prevServer && prevServer.wsServer) {
      console.log('Reloading the subscription server.');
      prevServer.wsServer.close(() => {
        addSubscriptions(httpServer);
      });
    }
  } else {
    addSubscriptions(httpServer);
  }
};

if (module.hot) {
  module.hot.dispose(data => {
    try {
      data.subscriptionServer = subscriptionServer;
    } catch (error) {
      console.log(error.stack);
    }
  });
}

export default addGraphQLSubscriptions;
```

Then modify /src/server.js
```javascript
import { graphqlExpress, graphiqlExpress } from 'apollo-server-express';
import { execute, subscribe } from 'graphql';
import { SubscriptionServer } from 'subscriptions-transport-ws';
import { createServer } from 'http';
import addGraphQLSubscriptions from './core/server/subscriptions';
import config from './config';

{Stuff...}

// Add in your graphql endpoint
app.use('/graphql', bodyParser.json(), graphqlAuthMiddleware, graphqlMiddleware);

// Enable graphiql with subscriptions
app.use('/graphiql', graphiqlExpress({
  endpointURL: '/graphql',
  subscriptionsEndpoint: `ws://supercoolsite.com:${config.subPort}/subscriptions`
}));

// Create websocket server
const websocketServer = createServer((_request, response) => {
  response.writeHead(404);
  response.end();
});

// Wrap the Express server
const server = createServer(app);
// Try to spin up the websocket server with diff port
addGraphQLSubscriptions(websocketServer);

//
// Launch the server
// -----------------------------------------------------------------------------
const promise = models.sync(
  //{ force: true },
).catch(err => console.error(err.stack));

if (!module.hot) {
  promise.then(() => {
    server.listen(config.port, () => {
      console.info(`The server is running at http://supercoolsite.com:${config.port}/`);
    });

    server.on('close', () => {
      server = undefined;
    });
  });
}

//
// Hot Module Replacement
// -----------------------------------------------------------------------------
if (module.hot) {
  app.hot = module.hot;
  module.hot.dispose(() => {
    try {
      if (server) {
        server.close();
        websocketServer.close();
      }
    } catch (error) {
      console.error(error.stack);
    }
  });

  module.hot.accept(['./core/server/subscriptions', './router'], () => {
    try {
      addGraphQLSubscriptions(websocketServer);
      console.log("attached addGraphQLSubscriptions to module.hot")
    } catch (error) {
      console.error(error.stack);
    }
  });
}

export default app;
```

This one was a bit of a headscratcher, there are probably better ways to solve this problem but here's where I said "It's good enough". Many thanks to @lobnico for getting me 80% of the way to working subscriptions :)

**Comment by ricardomoura** [comment]
@tim-soft i used your solution but ended having issues with HMR, any update i did ended with EADDRESS already in use. any solutions?

**Comment by langpavel** [comment]
@ricardomoura `EADDRESS` already in use means that something already listening on port. In really weird situation it can be ending process which not release resource yet, but, this is very rare :stuck_out_tongue: 
If you get `EADDRESS` without any reason, try kill widely used (video)chat application :rofl:

**Comment by pdeszynski** [comment]
@ricardomoura I don't know if this will be still useful for you, but I had the same problem after reloads as it was not always calling `dispose` from hot reload (depending which file I was exactly editing). Sadly I still didn't have luck to make subscriptions working on the same port as the server (maybe this could help solve this problem https://github.com/websockets/ws/pull/885), but for now I've solved `EADDRESS`, by closing previous subscription server not using webpack's hot module `accept/dispose` but inside of `start.js` script. Code looks like:


```js
// server.js
import createSubscriptionsServer from './core/createSubscriptionsServer';
import { createServer } from 'http';
// other RSK imports

//...

//
// Launch the server
// -----------------------------------------------------------------------------
if (!module.hot) {
  const server = createServer(app);
  createSubscriptionsServer({ server });
  server.listen(config.port, () => { // on production it will be working under the same port as main app
    console.info(`The server is running at http://localhost:${config.port}/`);
  });
}

//
// Hot Module Replacement
// -----------------------------------------------------------------------------
if (module.hot) {
  app.hot = module.hot;
  const server = createServer();
  createSubscriptionsServer({ server });
  server.listen(config.subscriptionsPort, () => {
    console.info(
      `The subscription server is running at http://localhost:${
        config.subscriptionsPort
      }`,
    );
  });

  app.subsciptionsServer = server;
  module.hot.accept('./router');
}

export default app;
```

```js
// createSubscriptionsServer
import { SubscriptionServer } from 'subscriptions-transport-ws';
import { execute, subscribe } from 'graphql';
import config from '../config';
import schema from '../data/schema';

export default function createSubscriptionServer(socketOpts = {}) {
  return SubscriptionServer.create(
    {
      schema,
      execute,
      subscribe,
      async onConnect(connectionParams, webSocket) {
       // stuff to create a context for subscriptions like logged in user
        return context;
      },
    },
    {
      ...socketOpts,
      path: '/subscriptions',
    },
  );
}
```

And the last part is an update in `tools/start.js` to close previously opened websocket server:

```
// start.js
//...

function checkUpdate(fromUpdate) {
// ...

return app.hot
  .check(true)
  //...
  .catch(error => {
        if (['abort', 'fail'].includes(app.hot.status())) {
          console.warn(`${hmrPrefix}Cannot apply update.`);
          app.subsciptionsServer.close(); // close the previous subscription server, getting here it means that server side code needs to be reloaded
         // ... rest of function body
  });
}
```


It's important that on production it will be working under the same port as your app, so for e.g. if you have set a port  `3000` then it will also listen for subscriptions under the port `3000`. Locally you will have to setup port inside of a config and use other one for subscriptions.

It would be great if somebody could share a better solution.

**Comment by WiktorKa** [comment]
@pdeszynski Did you manage to run subscription server on the same port?

**Comment by pdeszynski** [comment]
@WiktorKa not for development, only for production. I didn't have time to investigate this further and solve it without the need of switching BrowserSync to proxy mode.

**Comment by frenzzy** [comment]
About HMR, have you tried use global?
```js
const ws = global.ws || new WebSocket(...)
global.ws = ws
```

**Comment by ulani** [comment]
@pdeszynski   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
