### ISSUE TITLE
Accessing Webpack Hash On Server

### ISSUE THREAD

**Issue by valeeum** [kriasoft/react-starter-kit#1366]
Similar to the following issue (https://github.com/kriasoft/react-starter-kit/issues/59), i'd like to create a polling mechanism in the Layout component that will hit a graphql service for the hash string created by webpack.  If the component detects that a new version is available, it would prompt the user to reload the page.  So my question is how would one be able to refer to this hash on the server side of the app?

**Comment by ucay** [comment]
Please have a look at [this](https://webpack.js.org/api/stats/).
You can create webpack's stats (json format) after compiling.
```bash
$ webpack --profile --json > compilation-stats.json
$ #or
$ ./node_modules/webpack/bin/webpack.js --profile --json > compilation-stats.json
```
Then you'll get the result in json.
eg:
```json
{
  "version": "1.4.13", // Version of webpack used for the compilation
  "hash": "11593e3b3ac85436984a", // Compilation specific hash
  "time": 2469, // Compilation time in milliseconds
  "other fields..." : "goes here.."
}
```

**Comment by valeeum** [comment]
that's exactly what i'm looking for, thank you!
