### ISSUE TITLE
Documentation on How to Create a a new chunk with Code Splitting?

### ISSUE THREAD

**Issue by Andriy-Kulak** [kriasoft/react-starter-kit#1367]
I don't see any documentation on how to create a new webchunk with code splitting in the repo.

Is there any documentation on this topic?

I cannot find it. I tried adding a new route (called 'order') in the routes folder by replicating another route. I also added it to the routes array in render.js file, but I get the following error:

> Cannot read property 'js' of undefined ( on line 126 of server.js file)

It appears that assets.order.js (the chunk that I am trying to create does not exist). I do not understand how assets.json is being created from within webpack.config.js file. Does it not pull directories from render.js?

Any help would be greatly appreciated!

**Comment by Andriy-Kulak** [comment]
Never mind and figured it out! . This can be deleted!

**Comment by MarijnBrosens** [comment]
@Andriy-Kulak how did you do it?

**Comment by lvian** [comment]
@MarijnBrosens Had the same problem and fixed it by changing the _webpackChunkName to match the new route_
```
{
      path: '/store',
      load: () => import(/* webpackChunkName: 'store' */ './store'),
},
```
