### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by ricardomoura** [kriasoft/react-starter-kit#1368]
anybody has an example of file upload using graphql and apollo?
thanks

**Comment by ucay** [comment]
Haven't use graphql and apollo yet, just simple multer with express middleware.
Maybe you can try this one, [graphql-server-express-upload](https://github.com/HriBB/graphql-server-express-upload)

**Comment by joanrodriguez** [comment]
I do it using S3 if it's OK to be in the cloud or Minio if it needs to be self-hosted https://github.com/minio/minio

Essentially I upload the file to the file server, save the resulting URL in the db and return that URL in the graphql queries....

**Comment by ricardomoura** [comment]
ended up using graphql-server-express-upload for server and apollo-upload-network-interface on client
