### ISSUE TITLE
Multiple paths per route not working

### ISSUE THREAD

**Issue by SmboBeast** [kriasoft/react-starter-kit#1374]
Hi guys,

I'm using the RSK and I've tried getting this to work in every way I can think of.  For some reason, every time the following code runs, it seems like the second path is being hit even if the first one should.  

For example, imagine my url being /project/123/media.  My view media component ends up receiving the params object, but all the params (projectId and iterationId) are set to undefined.  I have no clue what's going on.

I literally just want two different paths to hit the same page/code.

```
export default {
  path: [
    '/project/:projectId/media', //project media
    '/project/:projectId/iteration/:iterationId/media', //iteration media
  ],

  async action({ params }) {
    return {
      //uniqueId: 'MediaEdit',
      title: 'View Media',
      component: <ViewMedia params={params} />,
    };
  }
};
```

**Comment by ucay** [comment]
Try `children` approach, this works in my case.

```javascript
export default {
  path:  '/project/:projectId', 
  children: [
    path: [
      '/media', //project media
      '/iteration/:iterationId/media', //iteration media
    ],
    async action({ params }) {
      return {
        //uniqueId: 'MediaEdit',
        title: 'View Media',
        component: <ViewMedia params={params} />,
      };
    }
  ]
};

**Comment by SmboBeast** [comment]
That works great.  Thanks @ucay
