### ISSUE TITLE
Integrate bootstrap.less or bootstrap.scss

### ISSUE THREAD

**Issue by apptemplateshop** [kriasoft/react-starter-kit#138]
I have tried include bootstrap.less/bootstrap.scss for reusing variable from bootstrap to each component, but no way. 

How we can create custom_variable.less/custom_variable.scss for bootstrap and using it into each component.

Thank you.

**Comment by korczis** [comment]
It will be nice to have this as opt in.

:+1:

**Comment by langpavel** [comment]
My little old PR: #646 Things changed a little but princip is same, see https://github.com/kriasoft/react-starter-kit/pull/646/commits/0eba0fde19189415d58d9ce90854e3c02d7eaeec
