### ISSUE TITLE
Importing Lodash globally

### ISSUE THREAD

**Issue by holgersindbaek** [kriasoft/react-starter-kit#1380]
I'm using Lodash in (basically) all my components, so I'd like to import Lodash globally. I'm using Lodash both for the server side and client side of my components, so it should be available on both.

The way I accomplish that now, is to import and set Lodash in both `server.js` and `client.js`:

    import _ from 'lodash';
    global._ = _;

Does this seem like an unreasonable way of doing things? If so, how else would you do it?

**Comment by kristjanmik** [comment]
You should only import the lodash module that you need on a per component basis. Importing the whole library seems like a waste of resources.
From the docs:
```
// Cherry-pick methods for smaller browserify/rollup/webpack bundles.
var at = require('lodash/at');
```

**Comment by holgersindbaek** [comment]
Would it be very much against the React way of doing things to import it globally? Seems like such a hassle to import each and every method I need individually into every component I have. 

-- 

All the best

Holger Sindbaek

 · UI/UX

 Designer & Web/iOS Programmer 

·

 

http://holgersindbaek.com/

On Wed, Aug 23, 2017 at 9:33 AM "Kristján Ingi Mikaelsson"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

You should only import the lodash module that you need on a per component basis. Importing the whole library seems like a waste of resources.

From the docs:

// Cherry-pick methods for smaller browserify/rollup/webpack bundles. var at = require('lodash/at');

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/kriasoft/react-starter-kit/issues/1380#issuecomment-324332560
, or

**Comment by kristjanmik** [comment]
I guess it comes down to what you are comfortable with. I'm worried about the output file size. You can see the effect by running: 
```
yarn build-stats
```

**Comment by holgersindbaek** [comment]
Will do.

If I want to import globally, would that be the way to do it though?

-- 

All the best

Holger Sindbaek

 · UI/UX

 Designer & Web/iOS Programmer 

·

 

http://holgersindbaek.com/

On Wed, Aug 23, 2017 at 9:48 AM "Kristján Ingi Mikaelsson"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I guess it comes down to what you are comfortable with. I'm worried about the output file size. You can see the effect by running:

yarn build-stats

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/kriasoft/react-starter-kit/issues/1380#issuecomment-324337389
, or

**Comment by borestad** [comment]
`const _ = window._ `

?

**Comment by holgersindbaek** [comment]
`global._ = _;` seems to work fine. What would be the advantage of doing `const _ = window._`?

**Comment by Andriy-Kulak** [comment]
'global' is understood by node. 'window' is understood by browsers. since its a server side app, global may work in this particular case anyway. I don't understand what the big hassle is. You're importing 'react' into every component you use so it doesn't mean you should make react available globally.

**Comment by holgersindbaek** [comment]
Maybe I'm just being a fuzz about this. @Andriy-Kulak Does it seem like a bad idea to do a global import? Is it very un-React like?

I'm going to close the topic. Thanks for the feedback everybody.
