### ISSUE TITLE
asset.json not update my new route

### ISSUE THREAD

**Issue by pansitwattana** [kriasoft/react-starter-kit#1382]
I add index.js in src/routes/paper
```import React from 'react';
import Paper from './Paper';

function action() {
  return {
    chunks: ['paper'],
    title: 'Paper',
    component: <Paper />,
  };
}

export default action;
```

then add path to index.js in src/routes/index.js
```
{
      path: '/paper',
      load: () => import('./paper'),
},
```

so I can route to the path via <Link to='/paper'>
but when I refresh it error on asset.json

```
TypeError: Cannot read property 'js' of undefined
    at E:\OneDrive\Documents\GitHub\Ezam\src\server.js:153:1
    at Array.map (native)
    at E:\OneDrive\Documents\GitHub\Ezam\src\server.js:153:1
    at Generator.next (<anonymous>)
    at step (E:\OneDrive\Documents\GitHub\Ezam\build\server.js:699:191)
    at E:\OneDrive\Documents\GitHub\Ezam\build\server.js:699:361
    at <anonymous>
```

then I try to add a route in asset.json then it works

```
"paper": {
    "js": "/assets/8.chunk.js"
}
```

**Comment by pansitwattana** [comment]
solve by add `/* webpackChunkName: 'paper' */` in route

didn't know that the comment effect the webpack

from ` load: () => import('./paper'),`
to `load: () => import(/* webpackChunkName: 'paper' */ './paper'),`

**Comment by langpavel** [comment]
Sure, [magic comments in webpack](https://webpack.js.org/guides/code-splitting/) (search the `webpackChunkName`) do the think.
