### ISSUE TITLE
ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by Shadowman4205** [kriasoft/react-starter-kit#1385]
Hello, i am trying use  `__DEV__` on config.js
```js
let _dbhost='http://test:3100'; 
if(__DEV__){
  _dbhost='http://localhost:3100'
}
export const dbhost=_dbhost;
```
But i got this error on initial npm start

```
> @ start C:\.......\.......
> babel-node tools/run start

isDebug:true
C:\......\.....\src\config.js:30
if (__DEV__) {
    ^

ReferenceError: __DEV__ is not defined
```
Is this bad usage or i forgot something?

**Comment by SmboBeast** [comment]
Yes, it seems like I'm hitting a case where my client side code needs to access the environment as well, to know which endpoint my AJAX calls need to hit.

The odd things with my situation is everything builds and runs fine, but committing my changes is where I get this issue to come up.  So I can't commit anything.

**Comment by langpavel** [comment]
@Shadowman4205 You can use `__DEV__` and similar globals injected by **webpack** only in files processed by webpack only.
Because config is a kind of special — can be required by another code, you cannot use this globals here.

**Comment by langpavel** [comment]
@SmboBeast 
> Yes, it seems like I'm hitting a case where my client side code needs to access the environment as well, to know which endpoint my AJAX calls need to hit.

Do not use config in client code. Feed `App` component on server or redux store instead, you can use this on client. Many related issues here, try look... ;-)

> The odd things with my situation is everything builds and runs fine, but committing my changes is where I get this issue to come up. So I can't commit anything.

You can always commit with `git commit -n` but pssst, I don't tell you this ;-)

**Comment by SmboBeast** [comment]
@langpavel I understand what you mean.  Thank you for telling us that __DEV__ and similar globals is injected by webpack in only processed files.  Makes perfect sense.

Also thank you for the tip you didn't give me. ;)

**Comment by ulani** [comment]
@SmboBeast   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
