### ISSUE TITLE
TypeError: action.default is not a function

### ISSUE THREAD

**Issue by mxmtsk** [kriasoft/react-starter-kit#1386]
I have created a new route that works perfectly fine when I navigate to it from a different route via the `Link` Component but when I enter the url in the browser and open the page directly all I get is this `TypeError`:

```
TypeError: action.default is not a function
    at context.route.load.then.action ([....]/src/router.js:16:1)
```

I don't really get what it's trying to tell me.

My `routes.js` (the swiper route fails)

```js
const routes = {
  path: '/',

  // Keep in mind, routes are evaluated in order
  children: [
    {
      path: '/',
      load: () => import(/* webpackChunkName: 'home' */ './home'),
    },
    {
      path: '/swiper',
      load: () => import(/* webpackChunkName: 'swiper' */ './swiper'),
    },

    // Wildcard routes, e.g. { path: '*', ... } (must go last)
    {
      path: '*',
      load: () => import(/* webpackChunkName: 'not-found' */ './not-found'),
    },
  ],

  async action({ next }) {
    // Execute each child route until one of them return the result
    const route = await next();

    // Provide default values for title, description etc.
    route.title = `${route.title || 'Untitled Page'} - x`;
    route.description = route.description || '';

    return route;
  },
};
```

And the `swiper/index.js` route:

```js

function action() {
  return {
    chunks: ['swiper'],
    title: 'Swiper',
    component: (
      <Layout>
        <Swiper />
      </Layout>
    ),
  };
}
```

**Comment by frenzzy** [comment]
`swiper/index.js` must export `action` fn:
```js
export default action;
```

**Comment by worc** [comment]
yeah no, that doesn't work. there's a strange requirement that the title match the chunk name?

**Comment by baishengmei** [comment]
Excuse me, did you resolve the question? I have the same question now. Thanks for your reply.

**Comment by damiangreen** [comment]
I get this a lot. I have to kill yarn run start and restart it

**Comment by amille44420** [comment]
I did notice the issue, the original build works fine but sometimes with the hot reload the chunck does not match the expected prototype anymore. It does works again if I kill and restart the webpack or if my whole app (server-side) is reloaded.

**Comment by valeeum** [comment]
same for me.  usually happens when you add a new route.  restart fixes issue.

**Comment by tusharkotlapure** [comment]
I am facing same issue and still it's not working after restart.

**Comment by damiangreen** [comment]
@tusharkotlapure this error can silently hide bugs in your code unfortunately. so if a restart doesnt work there may be some other problem
