### ISSUE TITLE
Wildcard routing

### ISSUE THREAD

**Issue by kppf** [kriasoft/react-starter-kit#1387]
I'm trying to route the path `task/<id>` to `.\task` and pass the `id` to the `Task.js`

I've added following to the `routes/index.js`
```
    {
      path: '/task/:id',
      load: () => import('./task'),
    },
```

As per the docs (and several related issues), I can use the `id` as:

```
{
    path: '/task/:id',
    action: (context) => `Task #$(context.param.id)`, 
}
```

But here, I've to import the `'.task'` and pass the param there, rather than returning from `action`. 
How to achieve it? The project structure is same as in the repository itself.

Other details:
* I can access `context.param.id` in `resolveRoute` function of `router.js`
* The function `resolveRoute` is called twice - once with `undefined` `params` and second time with as in previous point.

It seems like a fairly common use case - would be nice if there was a simple example for this in the project itself. Kindly help, and I can raise a PR adding the same.

Thanks.

**Comment by frenzzy** [comment]
```js
// task.js
function action(context) {
  return `Task #$(context.param.id)`;
}

export default action;
```

**Comment by kppf** [comment]
Thanks. It worked in `Task/index.js`
