### ISSUE TITLE
npm install error, minimatch, express, connect dependences deprecated

### ISSUE THREAD

**Issue by gko1943** [kriasoft/react-starter-kit#1392]
npm version 5.4.0
node version 8.4.0

npm install got warn and error: 
minimatch@2.0.10: Please update to minimatch 3.0.2
express@2.5.11: express 2.x series is deprecated

npm ERR! code EINTEGRITY
npm ERR! sha1-xxx integrity checksum failed when using sha1: wanted sha1-xxx1 but got sha1-xxx2

**Comment by ucay** [comment]
I think you can ignore the warning, for the checksum error, try this:
```bash
$ npm cache verify
```

chek this for more : [npm ERR! code EINTEGRITY (npm 5)](https://github.com/npm/npm/issues/16861)

**Comment by gko1943** [comment]
@ucay thx for reply. 
But i have tried all of methods in that page, before i create the issue.

**Comment by langpavel** [comment]
Reopen if desired
