### ISSUE TITLE
Can't receive the web-socket request when I start project use npm run start

### ISSUE THREAD

**Issue by AtrisMio** [kriasoft/react-starter-kit#1395]
Hey buddy, your start-kit is very awesome. I very loooove it. But when I build my project with web-socket, I found the server can't receive the request.

I use the 'express-ws' package for resolving web-socket request.

Here is the code in my 'src/server.js'

> ```
> import path from 'path';
> import express from 'express';
> import expressWS from 'express-ws';
> import cookieParser from 'cookie-parser';
> ...
> 
> const app = express();
> expressWS(app);
> 
> ...
> 
> app.ws('/ws', (ws, req, ...args) => {
>     const { cookies } = req;
>     console.log(cookies);
>     console.log(args);
>     ws.on('message', (msg) => {
>         console.log(msg);
>         ws.send({ status: 'recived', ...msg });
>     });
> });
> 
> //
> // Register server-side rendering middleware
> // -----------------------------------------------------------------------------
> app.get('*', async (req, res, next) => {
> 
> ...
> ```

I can't receive the web-socket request when I launch project use 'npm run start'.
But it's miraculously working well when I use 'npm run build && npm run serve'.

I don't know what makes this problem. Could you help me?

**Comment by frenzzy** [comment]
Please check #1362

**Comment by AtrisMio** [comment]
@frenzzy thanks a lot, it works! But is there a way that I could use the same port of http server at my websocket server?

**Comment by tim-soft** [comment]
I ran out of time attempting to reconcile websockets with browser sync. With the way things are set up I recommend yanking bs if you aren't using it and roll your own HMR.

**Comment by AtrisMio** [comment]
@tim-soft emmmm, I know that. Any way, I appreciate your time.
