### ISSUE TITLE
Automatically generate sitemap on production build

### ISSUE THREAD

**Issue by holgersindbaek** [kriasoft/react-starter-kit#1401]
It seems like there's packages out there that'll automatically generate sitemaps - https://github.com/kuflash/react-router-sitemap - but only works with React router.

Has anyone been able to setup React Start Kit to automatically generate sitemaps on production build?

**Comment by frenzzy** [comment]
You can use [https://github.com/ekalinin/sitemap.js](sitemap.js).

**Comment by holgersindbaek** [comment]
Thanks for the suggestion. How would you do that? 

Generate and write the file to the public server when running the deploy script?

**Comment by frenzzy** [comment]
If your routes are static, you can generate sitemap during build process (`tools/build.js`)
But if you are using route params and staff from db, you probably must generate them manually at runtime (getting list of items/product from db first)

**Comment by holgersindbaek** [comment]
They are static. They’re in the index.js file under /routes. How do I get the different routes though? Do I just import the routes and create the sitemap from that file?

**Comment by frenzzy** [comment]
Maybe something like this?
```js
// build-sitemap.js
import sm from 'sitemap';
import fs from 'fs';
import routes from '../src/routes';

function urls(array, route, baseUrl) {
  const url = `${baseUrl}${route.path || ''}`;
  if (route.children) {
    route.children.forEach(childRoute => print(array, childRoute, url));
  } else {
    urls.push(url);
  }
}

const rootRoute = Array.isArray(routes) ? { path: '', children: routes } : routes;

const sitemap = sm.createSitemap({
    hostname: 'https://www.example.com',
    urls: urls([], rootRoute, ''),
});

fs.writeFileSync('build/public/sitemap.xml', sitemap.toString());
```

**Comment by holgersindbaek** [comment]
Thanks for the mockup. I'll try it out tomorrow or so and post what I ended up with here.

I'll close the issue for now.

**Comment by Filco306** [comment]
@holgersindbaek what did you end up with?

**Comment by holgersindbaek** [comment]
I ended up with what @frenzzy did.

**Comment by Filco306** [comment]
Awesome, yes it seems logical. I assume you just put this script inside the repo and include to run this upon build?

**Comment by holgersindbaek** [comment]
Exactly. As one of the first things.

**Comment by Filco306** [comment]
Thank you very much! :)

But hmm, it does not find the module. 

My `build-sitemap.ts`:

```typescript
// tools/build-sitemap.js
import sm from 'sitemap';
import fs from 'fs';
import routes from '../src/routes';

function urls(array, route, baseUrl) {
  const url = `${baseUrl}${route.path || ''}`;
  if (route.children) {
    route.children.forEach(childRoute => urls(array, childRoute, url));
  } else {
    array.push({
      url: url || '/',
      // ...
    });
  }
  return array;
}

const rootRoute = Array.isArray(routes) ? { path: '', children: routes } : routes;

const sitemap = sm.createSitemap({
    hostname: 'http://www.mydomain.com',
    urls: urls([], rootRoute, ''),
});

function buildsitemap() {
  fs.writeFileSync('build/public/sitemap.xml', sitemap.toString());
}
export default buildsitemap;
```

Then I put it in `build.ts`, so I change the build function and add: 
```typescript
async function build() {
  await run(clean);
  await run(copy);
  await run(bundle);
  await run(buildsitemap); <-- added
```

However, I end up with the error
```
Error: Cannot find module '../src/routes'
Require stack:
- /../tools/build-sitemap.ts
- /../tools/build.ts
- /../tools/run.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/filipcornell/Desktop/web/web/tools/build-sitemap.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Module._compile (/../node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.newLoader [as .ts] (/../node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:996:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/../tools/build-sitemap.ts',
    '/../tools/build.ts',
    '/../tools/run.ts'
  ]
}
error Command failed with exit code 1.

```

Basically, it cannot find the src map upon build. Now, this is probably a noob question, but would you know what the issue is?

**Comment by holgersindbaek** [comment]
I'm not sure where you put the module. If you're using the react-starter-kit your routes files should be under /src/routes/index.js:

https://github.com/kriasoft/react-starter-kit/blob/master/src/routes/index.js

That's where it's getting the routes from.

**Comment by Filco306** [comment]
Thank you so much for your quick replies! My routes are in `src/routes/index.tsx`. I am following the general default structure. 

First of all, when I import like this:
```
import routes from '../src/routes';
```
or
```
import routes from '../src/routes/index';
```

Then I get the error I wrote about, `MODULE NOT FOUND`. However, when I import like this:
```
import routes from './../src/routes/index.tsx';
```

I get the error 
```
/../src/routes/index.tsx:13
import { Route } from 'universal-router';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

My `index.tsx` exports routes like:
```
export default routes;
```

Thank you so much for the help! Greatly appreciated!

**Comment by holgersindbaek** [comment]
I'm not sure. I'm using "normal" .js files. I'm not familiar with .tsx files. I'm pretty sure your issue is related to that, so maybe try to look on SO on  how to import from .tsx files.

**Comment by frenzzy** [comment]
@Filco306 maybe you should run this script using `ts-node` instead of `node`?
```diff
-    "build": "node tools/build.js"
+    "build": "ts-node tools/build.js"
```

**Comment by Filco306** [comment]
Thank you for your answer @frenzzy ! I think that is part of the issue, but in my build I am running: 

```
"build": "babel-node --extensions \".ts\" tools/run build",
```

In accordance with the `feature/apollo-pure` branch. I think that if I change that, I will run into other issues.
