### ISSUE TITLE
How would I combine and minify JS libraries on build?

### ISSUE THREAD

**Issue by holgersindbaek** [kriasoft/react-starter-kit#1404]
I have a bunch of JS libraries in my public folder, that I'm loading at the bottom of my HTML.js file, since they don't render server side:

<img width="319" alt="screen shot 2017-09-21 at 11 30 20 pm" src="https://user-images.githubusercontent.com/698979/30719817-4c48d6c8-9f25-11e7-9af0-73f435d1e52b.png">

I've just tested my sites speed on - https://tools.pingdom.com/ - and it's suggested that I combine as many of my JS files as possible and minify them.

How would you go about combining and/or minifying the JS files in my public folder?

**Comment by langpavel** [comment]
You are misusing RSK probably.
Why you aren't processing this scripts by webpack (inside `client.js`)?

**Comment by holgersindbaek** [comment]
Because they don't work server side. So I need to load them from the client.

Loading it from the client works fine, but when I check up on my website on different website optimizers, they're all suggesting that I bundle my JS files into one.

So I'm looking for a way to bundle all the JS files in my public folder into one JS file when I deploy the app.

Any suggestions on how to do this?

**Comment by frenzzy** [comment]
There are a lot of ways how you can include external libs to the bundle:
```js
/* YourComponent.js */
import 'self-exec-external-lib-with-ssr-support';
import lib1 from 'external-lib-with-export-and-ssr-support';

let lib2;
if (process.env.BROWSER) {
  require('self-exec-external-lib');
  lib2 = require('external-lib-with-export');
}

class YourComponent extends React.Component {
  componentDidMount() {
    import('external-lib-lazy-init');
    this.lib3 = import('external-lib-with-export-lazy-init');
  }
}
```

**Comment by holgersindbaek** [comment]
Hmm ok. That might work for some of them. I'm definitely going to try that out. 

There are still some libraries that I'd like to have available globally though.

Do you have a suggestion on how I can bundle multiple JS files into one on deploy?

**Comment by ulani** [comment]
@holgersindbaek   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
