### ISSUE TITLE
Authenticate user on server side and pass to client ?

### ISSUE THREAD

**Issue by Shadowman4205** [kriasoft/react-starter-kit#1407]
Hello, 

I am using this kit, and i want implement oidc authentication but on server side, the cycle of authentication is this

User click on login 

on server:

> -->router.get('/external/login,function()....) -> redirect to external login page
> -->after succesfully login the external page make post back to this url
> -->router.post('/get/logindata, function()....) -> how can i pass req.body data to client side?

any suggestion?

**Comment by langpavel** [comment]
@Shadowman4205 Please, this have no one common with RSK.
If you want help, you should describe your flow more precisely. You can reopen then.
