### ISSUE TITLE
upgrade to react@16

### ISSUE THREAD

**Issue by wasap** [kriasoft/react-starter-kit#1410]
react@16 is ready [https://www.npmjs.com/package/react](https://www.npmjs.com/package/react) are you planning to upgrade to 16?

**Comment by frenzzy** [comment]
yes

**Comment by seberik** [comment]
Are you considering implementing https://facebook.github.io/react/docs/react-dom-server.html#rendertonodestream

**Comment by tim-soft** [comment]
There are a lot of interesting performance gains with v16's SSR stuff. The downside is losing backwards compatibility with v15 in the process.

**Comment by frenzzy** [comment]
@seberik would be nice to use streaming of course, but it hard to extract critical path css in this case, need to think about it more.

- [Critical-path (Above-the-fold) CSS Tools](https://github.com/addyosmani/critical-path-css-tools) [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)
- [A React And Preact Progressive Web App Performance Case Study: Treebo](https://medium.com/dev-channel/treebo-a-react-and-preact-progressive-web-app-performance-case-study-5e4f450d5299)
