### ISSUE TITLE
Importing antdesign css appends random string to class names

### ISSUE THREAD

**Issue by jhowarth15** [kriasoft/react-starter-kit#1414]
Hi everyone, hoping for some help importing [antdesign](https://ant.design/) into my react-starter-kit project.

I currently `@import '../../../node_modules/antd/dist/antd.css';` in the Layout.css file. This does import the ant-design styles into my html source, but all of the style class names are appended with random strings like this: `form .Layout-ant-input-group-3C740 .Layout-ant-select-3TuWM,`. So none of the css is actually applied.

**Comment by frenzzy** [comment]
import them inside `Layout.js` and add to `withStyles` by analogy with normalize css:
https://github.com/kriasoft/react-starter-kit/blob/b7ea8fc20248c5bf63d86f6d024d6588de9328e8/src/components/Layout/Layout.js#L15

https://github.com/kriasoft/react-starter-kit/blob/b7ea8fc20248c5bf63d86f6d024d6588de9328e8/src/components/Layout/Layout.js#L38

**Comment by Shadowman4205** [comment]
@frenzzy  Hello,i just updated all my packages that were old 
and now i get error about css.

> BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
>                      You need to specify 'isomorphic-style-loader' instead of 'isomorphic-style',
>                      see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed

So now instead of 

> import NeededCss from '!!isomorphic-style!css?modules=false!

i will do

> import NeededCss from ''../../../node_modules/.....     ?

is there other option or this is?

**Comment by frenzzy** [comment]
```js
'!!isomorphic-style-loader!css-loader?modules=false!'
  // isomorphic-style   =>   isomorphic-style-loader
  // css                =>   css-loader
```
if you want to configure some files to be loaded as global css, just add paths to such files to corresponding css loaders in webpack.config.

**Comment by jhowarth15** [comment]
Perfect - thank you!!
