### ISSUE TITLE
[Question] How to hidden source code or minify source code?

### ISSUE THREAD

**Issue by Shinichi52** [kriasoft/react-starter-kit#1415]
Hi guy,
i tried start with command 
```sh
NODE_ENV=production
yarn run start -- --release 
```
to run application. And here are my source in chrome inspector (i can see all source code)
![untitled](https://user-images.githubusercontent.com/14195575/31056862-0efa1094-a703-11e7-9a84-4a011398bf84.png)

I have a question. How to hidden source code or minify source code?
thank you so much

**Comment by frenzzy** [comment]
Disable source maps (set `false`):
https://github.com/kriasoft/react-starter-kit/blob/b7ea8fc20248c5bf63d86f6d024d6588de9328e8/tools/webpack.config.js#L274

**Comment by Shinichi52** [comment]
@frenzzy thanks for response. i'm trying it now
