### ISSUE TITLE
OverwriteModelError: Cannot overwrite `xxx` model once compiled.

### ISSUE THREAD

**Issue by dpblh** [kriasoft/react-starter-kit#1418]
Hi Guys. I have a problem. I understand what is going on, but I don't know how it fixed.
I'm using mongoose as common ORM instead sequelize. It work not bad. But when HMR started, I have seen error in my console.
`(node:29695) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): OverwriteModelError: Cannot overwrite `Client` model once compiled.
`
Mongoose doesn't allow to define the model twice. When HMR tries to update server, it defines model twice.
Can you save me?:)

**Comment by frenzzy** [comment]
You can try to init model once inside `tools/start.js` script

**Comment by dpblh** [comment]
Thank you very much @frenzzy, but it didn't work for me. Because model have deep integration into server app. And I'd like to update my model in runtime. Or I don't understand something:).
I found a solution that helped me.

mongoose.js
`import mongoose from 'mongoose';
import config from '../../config';

const connectionString = config.mongo.host
  .split(',')
  .map(host => `mongodb://${host}:${config.mongo.port}/${config.mongo.dbname}`)
  .join(',');

// todo workaround for HMR. It remove old model before added new ones
Object.keys(mongoose.connection.models).forEach(key => {
  delete mongoose.connection.models[key];
});

mongoose.connect(connectionString, config.mongo.options);
mongoose.Promise = global.Promise;

export default mongoose;
`

client.js
`import mongoose from './mongoose';

const Client = mongoose.model(
  'Client',
  new mongoose.Schema({
    _id: { type: String, required: true },
    secret: { type: String, required: true },
  }),
);

export default Client;`

So my model has always a new clean connection.
I hope it'll help somebody!

**Comment by frenzzy** [comment]
Maybe
```js
/* server.js */
import mongoose from './mongoose';

// ...

if (model.hot) {
  module.hot.accept();
  module.hot.dispose(() => {
    mongoose.disconnect();
  });
  // ...
}
```

**Comment by dpblh** [comment]
It doesn't work for me :(
Because the model is initialized before.

```js
/* server.js */
import mongoose from './mongoose';

// somewhere here the model is initialized

if (model.hot) {
  module.hot.accept();
  module.hot.dispose(() => {
    mongoose.disconnect();
  });
  // ...
}
```

**Comment by langpavel** [comment]
Hi @dpblh
Personally I don't like magick like this, it will eat you in production. You have an options:
- at first, split migrations to standalone script
- at second, do not keen on magic :tada: :wink: 
- and at last, use proper database or service which can save your paycheck :raised_hands:

**Comment by tgdn** [comment]
The way I did it is removing the model from mongoose's models with

```javascript
delete mongoose.connection.models['client'];

const clientSchema = mongoose.Schema({
  ...
});

export default mongoose.model('client', clientSchema);
```

Then you can register the model again through HMR or anything else.

**Comment by dpblh** [comment]
Hi @langpavel
I really agree with you
1. It should never be used in production
2. Undocumented features’s bed way)
3. I don’t think)
Only this way worked
Late I’ll fix it

**Comment by kppf** [comment]
@dpblh I fixed it like this: 

```
export default (mongoose.models && mongoose.models.User
  ? mongoose.models.User
  : mongoose.model('User', userSchema));

```

**Comment by tgdn** [comment]
@dpblh that won't work if you change your schema and save if you use Hot Module Replacement though

**Comment by kppf** [comment]
@tgdn Yes. That doesn't update the schema using Hot Module Replacement. Your approach (delete/create/export) seems better.

**Comment by jithumohandas** [comment]
This approach worked for me.

let UserSchema = null;

try {
  UserSchema = mongoose.model('User', userSchema);
} catch (e) {
  UserSchema = mongoose.model('User');
}

export default UserSchema;

**Comment by Rohit221990** [comment]
If you want to overwrite the existing class for different collection using typescript
then you have to inherit the existing class from different class.

export class User extends Typegoose{
  @prop
  username?:string
  password?:string
}


export class newUser extends User{
    constructor() {
        super();
    }
}

export const UserModel = new User ().getModelForClass(User , { schemaOptions: { collection: "collection1" } });

export const newUserModel = new newUser ().getModelForClass(newUser , { schemaOptions: { collection: "collection2" } });

**Comment by shireefkhatab** [comment]
For me, i was requiring the model like this:
var Book = .require('./models/Book.model');

the name of the model is actually 'book.model.js'
so the uppercase B caused the problem..

After i don the following all worked fine:
var Book = .require('./models/book.model');

**Comment by pols63** [comment]
In my case, I need change the structure of schemas and requires code without restart the service.

**Comment by langpavel** [comment]
@pols63 You will always need split points. This stack is ready to be chopped to peaces, splitted, you must know when, it's only your responsibility ;-)
Is I said above, against dislikes: No magic cannot help you unboudlesly.
Get bigger and break this stack to pieces. It should be easy if you are good architect ;-)
Break out backend. If you can do it, you will learn why this stack is so awesome as starter…

**Comment by pols63** [comment]
Thanks for the answer. You right. But, I still think Mongoose must give the option to redefine a model. Many developers search the method for many reason, that must to say that option help us. In my case, our system must not be restarted because many collaborators and industrial machines are connected and we can't wait to night for updates.

**Comment by langpavel** [comment]
Sure @pols63 some models are more smooth than others.
If you evolve you must be prepared for this steps. Better soon then later :-)
You should evolve your model faster than your customers ;-) So you will not be surprised…
BTW RSK is opinionated stack with much of different use cases, so no prediction here, sorry, we all guess :-D
Don't take me bad, but you may look under the hood and target on your needs.
Cheers

**Comment by pols63** [comment]
Ok. I understand. But not all is one hundred percent predictible. Not always we can anticipate, proof of that is that Mongoose hasn't option for update models at runtime, like many customers want. I insist, let us choice update or not in runtime.

**Comment by HansonVPHAM** [comment]
import mongoose from 'mongoose'
const PetSchema = new mongoose.Schema({
...
})
export default mongoose.models.Pet || mongoose.model('Pet', PetSchema)

**Comment by ulani** [comment]
@dpblh   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Comment by thinhquocle** [comment]
> For me, i was requiring the model like this:
> var Book = .require('./models/Book.model');
> 
> The name of the model is actually 'book.model.js'
> so the uppercase B caused the problem..
> 
> After i don the following all worked fine:
> 
> var Book = .require('./models/book.model');

this one worked for me, Thank youi
