### ISSUE TITLE
Is this starter kit SEO friendly?

### ISSUE THREAD

**Issue by adamchenwei** [kriasoft/react-starter-kit#1422]
I heard PWA are very SEO friendly. I think this boilerplate is like that in default? Is there an additional config I need to do to make it possible? Thanks!

**Comment by frenzzy** [comment]
Yes, this boilerplate is SEO friendly of of the box.
Follow usual SEO guidelines during site creation to keep it friendly.

**Comment by langpavel** [comment]
React Starter Kit is supporting SSR (server side rendering) out of the box, so if you use it correctly, static page requests will give you exactly same output as on client rendered pages.
So I don't know about more friendliest way for crawlers.
