### ISSUE TITLE
Page/Route Specific External Javascript?

### ISSUE THREAD

**Issue by SmboBeast** [kriasoft/react-starter-kit#1424]
Hi guys,

I notice we drop all of our external JS files in html.js.  This is great, however, I've ended up dropping page/route specific external JS files here as well, where it's not really optimal.  Is there a way I can define specific external files to be loaded only on the page(s) that it's needed on and not the entire site?

Thanks

**Comment by dphrag** [comment]
I solved this by using https://www.npmjs.com/package/react-load-script

**Comment by SmboBeast** [comment]
@dphrag 

You're awesome.  This is what I needed.

Just out of curiosity, would this also be possible with webpack and code splitting or am I entirely missing the point of what code splitting even is?

Thanks!

**Comment by frenzzy** [comment]
```js
/* page.js */
import 'path/to/external.js';
// ...
```
and this external script will be bundled together with `page.js` (it could be in a separate chunk)

**Comment by SmboBeast** [comment]
@frenzzy 

Thank you! Will try this out in a bit and update the thread.

**Comment by langpavel** [comment]
Webpack code splittiong is awesome — in `async function` you can do:
```js
const {default: ChunkComponent} = await import(/* webpackChunkName: 'chunk-name' */ './chunk-file');
```
