### ISSUE TITLE
Heroku deploy failed with babel-node not found

### ISSUE THREAD

**Issue by adamchenwei** [kriasoft/react-starter-kit#1426]
**Environment**
OS: Win10 up to date
Deploy: Heroku 64bit latest
React Starter Kit: Latest Version

**Problem**
![image](https://user-images.githubusercontent.com/4201698/31304134-3bee93c4-aae9-11e7-88c8-a91ff8730ef2.png)

I see the tools/deploy.js has a config with a commented out heroku config (and yes I switched the url to my heroku url repo name instead), so I enable that and disable one the default enabled for git. I did the regular heroku actions, adding stuff into heroku and just do `git push heroku master` 

However every time I do it keep getting the error log above... Is there any step I missed? 

I know maybe simple way is[ just to install it in prod](https://stackoverflow.com/questions/36781542/package-json-start-script-babel-node-not-found-on-heroku-deploy), but I heard its not recommended, so definately want a right fix, than hack
**Comment**
On the side note:
Is that possible to have more explanation on ` Note, you should only deploy the contents of the /build folder to a remote server.`  for the getting start page? https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md
I am not really sure how to just deploy /build? Like, how can it be not deploying just build? 

Thanks

**Comment by langpavel** [comment]
Did you deploy from `build` directory?

**Comment by adamchenwei** [comment]
actually, yea, I was exploring myself also found that that's how it should go as well lol

Thanks for pointing it out though!

The flow for heroku is really

init heroku repo 
uncomment out the deploy.js heroku config and comment out git config
check heroku git remote info, copy and paste that into the deploy.js replace placeholder text for repo name
then do exactly ou mentioned yar build --release and then yarn run deploy. 

Worked very well!!! Very excited! Thanks
