### ISSUE TITLE
Typescript and HMR infinite loop (Hot Module Reloading)

### ISSUE THREAD

**Issue by franleplant** [kriasoft/react-starter-kit#1429]
Hi there! Thanks a lot for this project, it has helped me and my team a lot!

We are trying to add typescript to the existing build system. Not much of a problem with that, I've included the Typescript loader, successfully compiled a couple of files that I migrated to typescript (i.e. `client.tsx` and `server.tsx`) but the problem comes when HMR is in play.

**How To reproduce**
- Clone this [repo](https://github.com/franleplant/webpack-typescript-hmr-infinite-loop) (it's React Starter Kit with Typescript, some files migrated to typescript and type definitions for the most part)
- install all deps (`yarn`) and run the app in dev mode with `npm start`
- The app will compile successfully and a browser window will open
- Now edit any source file, say `App.tsx` or `home/index.js`
- Watch the build system catch up with the changes and your app changing
- Watch client recompile
- Watch server recompile
- Watch client recompile
- Watch server recompile
- Repeat until infinity

Checkout this Gif for a more visual representation of the problem

![bug](https://user-images.githubusercontent.com/1852455/31339143-4f5a0632-acd8-11e7-9280-9b85dca58af4.gif)

These are some of the files that I think are more relevant 

<details>
 <summary>webpack.config.js</summary>

```javascript
   ...
   rules: [
      { test: /\.tsx?$/,
        rules: [
          {
            //include: path.resolve(__dirname, '../src'),
            loader: 'babel-loader',
            options: {
              // https://github.com/babel/babel-loader#options
              cacheDirectory: isDebug,

              // https://babeljs.io/docs/usage/options/
              babelrc: false,
              presets: [
                // A Babel preset that can automatically determine the Babel plugins and polyfills
                // https://github.com/babel/babel-preset-env
                [
                  'env',
                  {
                    targets: {
                      browsers: pkg.browserslist,
                      uglify: true,
                    },
                    modules: false,
                    useBuiltIns: false,
                    debug: false,
                  },
                ],
                // Experimental ECMAScript proposals
                // https://babeljs.io/docs/plugins/#presets-stage-x-experimental-presets-
                'stage-2',
                // JSX, Flow
                // https://github.com/babel/babel/tree/master/packages/babel-preset-react
                'react',
                // Optimize React code for the production build
                // https://github.com/thejameskyle/babel-react-optimize
                ...(isDebug ? [] : ['react-optimize']),
              ],
              plugins: [
                // Adds component stack to warning messages
                // https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-source
                ...(isDebug ? ['transform-react-jsx-source'] : []),
                // Adds __self attribute to JSX which React will use for some warnings
                // https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-self
                ...(isDebug ? ['transform-react-jsx-self'] : []),
              ],
            },
          },

           // This is the typescript lodare, as you can see
           // Im still using the old babel config after processing typescript
          {
            loader: 'awesome-typescript-loader',
            options: {
              useBabel: true,
              useCache: true
            }

          },
        ]
      },
  ...
```

</details>

<details>
 <summary>tsconfig.json</summary>

```javascript
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "alwaysStrict": true,
    "jsx": "preserve",
    "module": "es6",
    "moduleResolution": "node",
    "lib": ["dom", "es2015", "es2016", "es2017"],
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "preserveConstEnums": true,
    "pretty": true,
    "removeComments": false,
    "skipLibCheck": true,
    "sourceMap": true,
    "target": "es6"
  }
}
``` 

</details>

So I need to:
- Prevent this infinite loop
- Validate that this actually a problem, it looks like the page is being notified over and over that the bundle is updating

<details>
 <summary>Bonus: Images from the app</summary>

<img width="1403" alt="screen shot 2017-10-09 at 9 40 59 am" src="https://user-images.githubusercontent.com/1852455/31339815-82b76978-acda-11e7-98fe-188fa44af779.png">
<img width="1404" alt="screen shot 2017-10-09 at 9 41 07 am" src="https://user-images.githubusercontent.com/1852455/31339862-a6b6e754-acda-11e7-80cb-e874ed3ccbe6.png">

</details>

**Comment by franleplant** [comment]
Update:

Switching `awesome-typescript-loader` for `ts-loader` fixes this problem.

**Comment by ulani** [comment]
@franleplant   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
