### ISSUE TITLE
Use babel-preset-react-optimize instead of 3 individual transform plugins

### ISSUE THREAD

**Issue by Stupidism** [kriasoft/react-starter-kit#1437]
[babel-react-optimize](https://github.com/thejameskyle/babel-react-optimize) has all 3 common used transform plugins you added into starter in https://github.com/kriasoft/react-starter-kit/commit/08d44d0a2a9c2150880f331e9b5f0d625033bf6b.

**Comment by Stupidism** [comment]
Noticed it's removed intentionally

**Comment by rodeyseijkens** [comment]
@frenzzy & @Stupidism Can you elaborate on the [babel-react-optimize](https://github.com/thejameskyle/babel-react-optimize).

Cause my findings are that now also [transform-react-inline-elements](https://github.com/thejameskyle/babel-react-optimize#transform-react-inline-elements) is removed. Aren't functional components the best practice speed wise in the end? [Benchmark article](https://medium.com/missive-app/45-faster-react-functional-components-now-3509a668e69f)

Or is the 'transforming classes to functional components' already part of Babel or something?
