### ISSUE TITLE
no gulp file?

### ISSUE THREAD

**Issue by rossthedevigner** [kriasoft/react-starter-kit#144]
No gulpfile found.

Perhaps I'm missing something here?

**Comment by ionicteam** [comment]
update your gulp by type this: npm install -g gulp
I think this repository organize not good for CSS, you can't write CSS by reuse variable or mixin from bootstrap or any CSS framework.

**Comment by koistya** [comment]
```
$ gulp -v
```

It should be 3.9.0+. Alternatively run it via npm script:

```
$ npm run build      # builds the project
$ npm run sync       # builds the project and launches dev server
```

If you want to do the same in release mode (minimize and optimize compiled output):

```
$ npm run build -- --release
$ npm run sync -- --release
```

For more info, see `package.json/scripts`.

**Comment by oliverbenns** [comment]
Thanks @koistya . My Gulp was on 3.8.8 so I simply updated with `npm update gulp -g`
