### ISSUE TITLE
How to redirect user without reload page?

### ISSUE THREAD

**Issue by FMakareev** [kriasoft/react-starter-kit#1445]
Hello. I want to redirect a user without reload page through method 'fetch'. 
On server i added get handler:
`app.get('/test', function (req, res, next) {
    res.redirect('/redirect'); // example path
});`

From the browser i do request:
`fetch('test');`

These action no job. I think I understand why but I do not know what I need to do to get it working.

**Comment by frenzzy** [comment]
If you want redirect for specific route, take a look at universal router [redirects](https://github.com/kriasoft/universal-router/blob/master/docs/redirects.md) recipe.

For client side only redirect use [History](https://github.com/ReactTraining/history) module:
```js
import history from '../history';

function onClick() {
  history.push('/target/path');
}
```

**Comment by FMakareev** [comment]
Thank you very much.
