### ISSUE TITLE
Incorrect logic in Webpack Config

### ISSUE THREAD

**Issue by eltonjuan** [kriasoft/react-starter-kit#1448]
In the Webpack config `plugins` section, the conditional logic seems flipped for including various plugins. See the following line: 

https://github.com/kriasoft/react-starter-kit/blob/07b7da9d87dcc2a960978ae1908df5a2a7374f5c/tools/webpack.config.js#L109

Unless I'm losing my mind, this is saying if `isDebug` (i.e. `development === true`), then include the following plugins: 
`transform-react-constant-elements`
`transform-react-inline-elements`
`transform-react-remove-prop-types`

Shouldn't the logic be flipped so that those plugins are included if `!isDebug`, i.e. 
`...(isDebug ? [] : 'transform-react-constant-elements'`?

Cheers

**Comment by frenzzy** [comment]
Thank you for mention this, fixed.

**Comment by Borales** [comment]
@eltonjuan @frenzzy `...(isDebug ? [] : 'transform-react-constant-elements')`

so, `transform-react-constant-elements` plugin will be applied for prod-mode only (`isDebug = false`), right? 
But we still have babel plugins in `devDependencies` (for dev-mode):

```
"babel-plugin-transform-react-constant-elements": "7.0.0-beta.3",
"babel-plugin-transform-react-inline-elements": "7.0.0-beta.3",
"babel-plugin-transform-react-remove-prop-types": "^0.4.10"
```

**Comment by Borales** [comment]
@frenzzy I guess we should add build `prod || dev` step tests as well (at least to check that it's not broken)

**Comment by frenzzy** [comment]
Babel plugins are specified in `devDependencies` because they are used only for compilation but not on the production server.
Would be nice to add a basic configuration of functional tests to the kit with maybe [puppeteer](https://github.com/GoogleChrome/puppeteer), PRs are welcome.

**Comment by Borales** [comment]
@frenzzy you are right, sorry, my mistake (compiling bundle on prod is a bad habit, I have to get rid of it)
