### ISSUE TITLE
Dependency issues with lerna

### ISSUE THREAD

**Issue by bluematter** [kriasoft/react-starter-kit#1451]
I am stuck and can't figure out any solutions other than `cd packages/name` then `rm -rf node_modules` then `npm install` this will install all the dependencies in the lerna package aka react-starter-kit defeating the purpose of lerna and breaking every lerna bootstrap. So not a good solution, the only workable solution I could come up with.

When running the project with yarn workspace I get the error below. `yarn workspace @bannagram/server start` @bannagram/server is RSK.

How can I use this project with lerna properly? Thanks

entrepreneur-projects/bannagram - [master●] » yarn workspace @bannagram/server start
yarn workspace v1.2.1
yarn run v1.2.1
$ babel-node tools/run start
[01:25:44] Starting 'start'...
[01:25:44] Starting 'clean'...
[01:25:44] Finished 'clean' after 31 ms
[01:25:44] Compiling 'client'...
[01:25:44] Compiling 'server'...
Time: 8906ms
                                           Asset     Size  Chunks                    Chunk Names
                                  login.chunk.js   259 kB       4  [emitted]  [big]  login
   src/components/Header/logo-small.png?2f751285  2.83 kB          [emitted]
                                privacy.chunk.js   234 kB       0  [emitted]         privacy
                                  about.chunk.js   234 kB       1  [emitted]         about
                               register.chunk.js   226 kB       2  [emitted]         register
                              not-found.chunk.js   226 kB       3  [emitted]         not-found
src/components/Header/logo-small@2x.png?8844262b  6.81 kB          [emitted]
                                   home.chunk.js   233 kB       5  [emitted]         home
                                contact.chunk.js   226 kB       6  [emitted]         contact
                                  admin.chunk.js   228 kB       7  [emitted]         admin
                                       client.js  73.7 kB       8  [emitted]         client
                                       vendor.js  6.16 MB       9  [emitted]  [big]  vendor
[01:25:53] Finished 'client' compilation after 8906 ms
Time: 14062ms
 13 assets

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/ajv/lib/async.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/ajv/lib/ajv.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/har-validator/lib/node4/promise.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/request/lib/har.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/request/request.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/request/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/install.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib ^\.\/.*$
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/lib/sqlite3.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/ajv/lib/compile/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/ajv/lib/ajv.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/har-validator/lib/node4/promise.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/request/lib/har.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/request/request.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/request/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/install.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib ^\.\/.*$
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/lib/sqlite3.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js
15:20-67 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib ^\.\/.*$
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/lib/sqlite3.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/pre-binding.js
19:22-48 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/pre-binding.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/lib/sqlite3.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mssql/connection-manager.js
21:19-62 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mssql/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mssql/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/postgres/connection-manager.js
22:16-59 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/postgres/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/postgres/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
25:19-62 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mysql/connection-manager.js
32:19-62 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mysql/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mysql/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
387:61-74 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/lib/sqlite3.js
4:14-35 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/lib/sqlite3.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/express/lib/view.js
81:13-25 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/express/lib/view.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/express/lib/application.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/express/lib/express.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/express/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/bindings/bindings.js
81:22-40 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/bindings/bindings.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sspi-client/src_js/sspi_client.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sspi-client/src_js/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/tedious/lib/connection.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/tedious/lib/tedious.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mssql/query.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mssql/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/bindings/bindings.js
81:43-53 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/bindings/bindings.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sspi-client/src_js/sspi_client.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sspi-client/src_js/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/tedious/lib/connection.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/tedious/lib/tedious.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mssql/query.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mssql/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/ajv/lib/async.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/ajv/lib/ajv.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/har-validator/lib/node4/promise.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/request/lib/har.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/request/request.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/request/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/install.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib ^\.\/.*$
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/lib/sqlite3.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/encoding/lib/iconv-loader.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/encoding/lib/encoding.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/node-fetch/lib/body.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/node-fetch/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mysql/connection-manager.js
Module not found: Error: Can't resolve 'mysql2' in '/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mysql'
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mysql/connection-manager.js 34:19-36
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/mysql/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'npm' in '/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util'
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js 39:27-49
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib ^\.\/.*$
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/lib/sqlite3.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

WARNING in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/postgres/connection-manager.js
Module not found: Error: Can't resolve 'pg' in '/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/postgres'
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/postgres/connection-manager.js 24:16-29
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/postgres/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js

ERROR in /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/rc/index.js
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #! /usr/bin/env node
| var cc   = require('./lib/utils')
| var join = require('path').join
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/unpublish.js 12:13-26
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib ^\.\/.*$
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sqlite3/lib/sqlite3.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/dialects/sqlite/index.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/lib/sequelize.js
 @ /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/sequelize/index.js
 @ ./src/data/models/UserProfile.js
 @ ./src/data/models/index.js
 @ ./src/server.js
 @ multi babel-polyfill ./src/server.js
[01:25:58] Failed to compile 'server' after 14069 ms
Error: Compilation failed!
    at Compiler.<anonymous> (/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/packages/server/tools/start.js:247:16)
    at Compiler.applyPlugins (/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/webpack/lib/Compiler.js:104:17)
    at onCompiled (/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/webpack/lib/Compiler.js:54:18)
    at applyPluginsAsync.err (/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (/Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/node_modules/tapable/lib/Tapable.js:195:46)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/michaelaubry/.nvm/versions/node/v8.6.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.2.1/libexec/lib/cli.js start
Directory: /Users/michaelaubry/Documents/projects/entrepreneur-projects/bannagram/packages/server
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.

**Comment by bluematter** [comment]
bump

**Comment by ulani** [comment]
@bluematter   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
