### ISSUE TITLE
Testing server-side api with Jest

### ISSUE THREAD

**Issue by jwchang0206** [kriasoft/react-starter-kit#1462]
I'm trying to test my REST APIs built with RSK.
I created a file `foo.test.js` in 'test' directory.

I used `chai` and `chai-http` to test the behavior of my REST APIs.

The problem was this.
```javascript
import server from '../src/server';

it('test 1', (done) => {
  chai.request(server)
    .get('/api/test')
    .end((err, res) => {
      res.should.have.status(200);
      done();
    });
});
```

I ran `yarn run test`.

By importing server, it reaches the  `src/routes/index.js` file.

So I'm getting this error.
```bash
load: function load() {return import( /* webpackChunkName: 'home' */'./home');} },
                                      ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (src/router.js:2:38)
```

Do you guys have some recommended patterns for setting up test environment for REST APIs with RSK?

**Comment by frenzzy** [comment]
I believe that to solve the error above you need to install [babel-plugin-dynamic-import-node](https://github.com/airbnb/babel-plugin-dynamic-import-node):
```js
// .babelrc.js
{
  presets: [/* ... */],
  plugins: ['dynamic-import-node'],
  /* ... */
}
```

**Comment by wenlisu** [comment]
@inspiredjw   Hi, I have the same problem when npm run build, what do you do?

**Comment by inspiredjw** [comment]
For `.babelrc.js`, `plugins: ['dynamic-import-node']`.

`.eslintrc.js`, `env: { jest: true }`.

`jest.config.js`
```javascript
transformIgnorePatterns: [
    '!node_modules/jest-runtime',
    '/node_modules/',
],

setupFiles: ['raf/polyfill']
```

Added these as `devDependencies`.

- babel-plugin-dynamic-import-node
- chai
- chai-http
- regenerator-runtime
- raf

**Comment by dcsan** [comment]
was also looking for info, this maybe relevant to you
https://mongoosejs.com/docs/jest.html

**Comment by ulani** [comment]
@jwchang0206   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
