### ISSUE TITLE
tools/run does not pass options

### ISSUE THREAD

**Issue by rochadt** [kriasoft/react-starter-kit#1469]
When calling the run function in tools/run, options are never passed:

https://github.com/kriasoft/react-starter-kit/blob/8e79361d4ccfcbf70530237bfed3033264770df1/tools/run.js#L39-L44  

Assuming that the task name is the first argument, shouldn't this look something like the following?
```js
  const module = require(`./${process.argv[2]}.js`).default;

  run(module, process.argv.slice(3)).catch((err) => {
    console.error(err.stack);
    process.exit(1);
  });
```

**Comment by jorrit** [comment]
I think the code that is executed by run.js fetches the arguments from `process.argv` directly. See webpack.config.js, for instance.

**Comment by rochadt** [comment]
Yea ok, I just thought it's kinda odd the run function has an options argument that isn't used anywhere:

https://github.com/kriasoft/react-starter-kit/blob/6c599b72e6ca1f75f9e52b995a7f9a6f387555ea/tools/run.js#L14

will close.
