### ISSUE TITLE
unable to compile - react starters

### ISSUE THREAD

**Issue by 1greenapplee** [kriasoft/react-starter-kit#1471]
C:\Users\ed\Desktop\react-starter-kit-master
λ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\minimist-fdcda6eb\test\dash.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\mkdirp-64d68eda\examples\pow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\hmac-drbg-a749e66c\test\drbg-test.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\minimist-fdcda6eb\test\default_bool.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\des.js-501d9a36\lib\des.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\minimist-fdcda6eb\test\dotted.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\parse5-d3f328e9\lib\tokenizer\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\minimist-fdcda6eb\test\long.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\minimist-fdcda6eb\test\parse.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\weinre-f4aed180\web\tests\element-highlighter.html'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\pako-5997ac48\lib\zlib\README'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\minimist-fdcda6eb\test\parse_modified.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\moment-timezone-0f8434fc\data\meta\latest.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\weinre-f4aed180\web\tests\index.html'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\pako-5997ac48\lib\zlib\constants.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\minimist-fdcda6eb\test\short.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\pako-5997ac48\lib\zlib\crc32.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\minimist-fdcda6eb\test\whitespace.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\pako-5997ac48\lib\zlib\deflate.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules\har-validator\lib\node4\async.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules\har-validator\lib\node4\error.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules\har-validator\lib\node4\promise.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\asn1.js-15c65573\lib\asn1\base\buffer.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\hash.js-8bfe4580\lib\hash\sha'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\asn1.js-15c65573\lib\asn1\base\index.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules\har-validator'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\asn1.js-15c65573\lib\asn1\base\node.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\asn1.js-15c65573\lib\asn1\base\reporter.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\nan-b22c73e6\tools\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\nan-b22c73e6\tools\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\nan-b22c73e6\tools\1to2.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\stylelint-a21ee2d8\lib\rules\selector-attribute-operator-whitelist\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\stylelint-a21ee2d8\lib\rules\selector-attribute-operator-whitelist\README.md'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\stylelint-a21ee2d8\lib\rules\selector-attribute-quotes'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\fsevents-25801e3f\node_modules\asn1\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules\asn1\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\fsevents-25801e3f\node_modules\asn1\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules\asn1\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\fsevents-25801e3f\node_modules\asn1\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules\asn1\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\fsevents-25801e3f\node_modules\asn1\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules\asn1\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\fsevents-25801e3f\node_modules\asn1\.travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules\asn1\.travis.yml'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\fsevents-25801e3f\node_modules'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\sqlite3-d32f47dc\node_modules'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\fsevents-25801e3f\node_modules\ecc-jsbn\lib'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\fsevents-25801e3f\node_modules\minimist'
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-html@0.11.0 requires a peer of postcss-sass@>=0.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\ed\Desktop\react-starter-kit-master\node_modules\.staging\fsevents-25801e3f'

npm ERR! code EINTEGRITY
npm ERR! sha512-yJDRffvby5mCTkbwOdXwiGDjeea8Z+BPVuP53/tHqHIZC+KtQD790zopVf7mHk65v+wRn+TZ7tkRSNA9oDmyLg== integrity checksum failed when using sha512: wanted sha512-yJDRffvby5mCTkbwOdXwiGDjeea8Z+BPVuP53/tHqHIZC+KtQD790zopVf7mHk65v+wRn+TZ7tkRSNA9oDmyLg== but got sha512-g7qyU93fDHo+fGDKRbcJb7vRnENs2ouj7EzJPIY+U0kM7VoqukjuMelD0/719l0ZuLIa7EFsMAkAoaVVEjKbXA==. (3358720 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ed\AppData\Roaming\npm-cache\_logs\2017-12-05T13_42_54_001Z-debug.log

**Comment by frenzzy** [comment]
Please install [Yarn](https://yarnpkg.com/) package and [Node.js](https://nodejs.org/) v6.5 or newer first.
Then pull latest version of react-starter-kit and try again:
```sh
node -v # v8.9.1
yarn -v # 1.3.2
git clone -o react-starter-kit -b master --single-branch \
      https://github.com/kriasoft/react-starter-kit.git MyApp
cd MyApp
yarn install
yarn start
```
Read more: [Getting Started](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md)

**Comment by 1greenapplee** [comment]
this worked. Thank you!
