### ISSUE TITLE
Migration to Apollo Client 2.0 in react Apollo branch.

### ISSUE THREAD

**Issue by GPnow** [kriasoft/react-starter-kit#1473]
2.* replaces Redux https://www.apollographql.com/docs/react/2.0-migration.html#redux , in addition to many other new features,we need to update this branch

**Comment by tim-soft** [comment]
I've been contemplating this for a little while now. I like having the Apollo Cache in Redux for a variety of reasons, mostly revolving around it's middleware/afterware capabilities and time travel.

Since Apollo has made the cache implementation extendable to other platforms, I've been testing out https://github.com/rportugal/apollo-cache-redux/issues/6 which is passing (nearly) all of Apollo's InMemoryCache tests, although it currently doesn't support middlewares. The other option is going with InMemoryCache, but I haven't been convinced to make the switch.

What does @langpavel think?

**Comment by rportugal** [comment]
Update on the above: all tests are passing, and the middleware work is being tracked in https://github.com/rportugal/apollo-cache-redux/issues/12 .

**Comment by ricardomoura** [comment]
How should make this work with the current implementation of createApolloClient and configureStore, because the redux thunk middleware?

i'm trying the following:
```
//client.js

import configureStore from './store/configureStore';
import createApolloClient from '../core/createApolloClient';

const apolloClient = createApolloClient();

const store = configureStore(window.App.state, {
  apolloClient,   // => i have to provide this in order to use it on the redux-thunk middleware
  fetch,
});

```

```
// core/createApolloClient.client.js

import { ApolloClient } from 'apollo-client';
import { ApolloLink } from 'apollo-link';
import { HttpLink } from 'apollo-link-http';
import { WebSocketLink } from "apollo-link-ws";
import { getOperationAST } from 'graphql';
import { ReduxCache } from 'apollo-cache-redux';
import Cookies from 'js-cookie';

const HTTP_ENDPOINT = `${window.App.api}/graphql`;
const WS_ENDPOINT   = `${window.App.ws}/subs`;

const link = ApolloLink.split(
  operation => {
    const operationAST = getOperationAST(operation.query, operation.operationName);
    return !!operationAST && operationAST.operation === 'subscription';
  },
  new WebSocketLink({
    uri: WS_ENDPOINT,
    options: {
      reconnect: true, //auto-reconnect
      connectionParams: {
        token: Cookies.get('id_token'),
      }
    }
  }),
  new HttpLink({ uri: HTTP_ENDPOINT })
);

export default function createApolloClient() {
  // how i get store here?
  const cache = new ReduxCache();

  return new ApolloClient({
    connectToDevTools: true,
    queryDeduplication: true,
    link,
    cache,
  });
}
```

```
// store/configureStore.js
export default function configureStore(initialState, config) {

  const { apolloClient, fetch } = config;
  const { query, mutate, subscribe } = apolloClient; // 

  const client = {
    query,
    mutate,
    subscribe,
  };

  const middleware = [
    thunk.withExtraArgument({ client, fetch }),
// apolloClient.middleware() // => this is deprecated now, 
  ];


(....)
```

on the combineReducer i have:
apollo: apolloClient.extract(),


any help to make this work seamless?

**Comment by rportugal** [comment]
`configureStore()` would need to be called before `createApolloClient()`, and the latter would need to be called with `store` as argument.

Another thing, your `combineReducers()` needs to use the `apolloReducer` reducer available from `ReduxCache`, something like:
```
import { apolloReducer } from 'apollo-cache-redux';

...
combineReducers({
   apollo: apolloReducer,
   ...yourRemainingReducers
});
```

Let me know how that goes!

**Comment by tim-soft** [comment]
@ricardomoura don't forget the server side Apollo, maybe it's time to upgrade how that works, avoiding the extra http round-trips

**Comment by ricardomoura** [comment]
@rportugal i understood that, I have to call configureStore before apolloClient.
but I whim at using thunk. then how i pass it to the configureStore in order to inject it on the thunk middleware?

```
export default function configureStore(initialState, config) {

  const { apolloClient, fetch } = config;
  const { query, mutate, subscribe } = apolloClient; // this needs to be injected, before, the apolloClient.middleware() returned the store state also the client/mutate/subscribe interface. now theres not middleware(), 


  const client = {
    query,
    mutate,
    subscribe,
  };

  const middleware = [
    thunk.withExtraArgument({ client, fetch }),
// before we had here the apolloClient.middleware()
// that allowed me to call inside a thunk on redux
// return async (dispatch, getState, { client, fetch }) => { ... 
// client and fetch would be exposed here,
// 
  ];
```

@tim-soft yes  the schemaLink and it works fine.

**Comment by tim-soft** [comment]
@ricardomoura have you made any progress with redux thunk? The current setup doesn't fit the new pattern since you can't make the Apollo instance before the store -- where the cache resides, so you cannot create the store with the Apollo client inside for the thunk. 

@rportugal have any suggestions?

**Comment by tim-soft** [comment]
https://github.com/kriasoft/react-starter-kit/pull/1492

**Comment by langpavel** [comment]
I just upgrade all feature branches, including @tim-soft's work on Apollo 2
@rportugal It is possible to solve circular dependencies by passing global-like container, for example called `context`; apollo and redux store can be accessed from redux actions through this `context`.
Also this `context` can be passed as top level context to Redux, including `intl` and all the other stuff.
Anyone interested in writing patch? :slightly_smiling_face:

**Comment by tim-soft** [comment]
I didn't think the lemon was worth the squeeze. :wink:

Links can provide pretty much any functionality that thunk or other redux middleware could provide. Apollo needlessly makes the redux store huge, which I am assuming there's a perf penalty as a result.

I think it's more efficient and a lot less complex to keep them separate, aside from official Apollo team support for inmemorycache and just basic separation of concerns. I'm open to other opinions but this is what I concluded

**Comment by lslima91** [comment]
with apollo link state, isn't it  a safe bet to just ditch redux altogether? This being a starter kit imo makes sense, there is already a branch dedicated for redux.

**Comment by langpavel** [comment]
@lslima91 I like redux. It is simple and much more lightweight than crazy *manage state in GraphQL*, also keep in mind existing stuff based on this branch, so Redux will remain there.

**Comment by langpavel** [comment]
Migration is done, closing
