### ISSUE TITLE
Link in new tab

### ISSUE THREAD

**Issue by mmarkelov** [kriasoft/react-starter-kit#1478]
How can I link user to new tab? I tried to use target="_blank" on Link, but seems that it doesn't work.
Thanks

**Comment by frenzzy** [comment]
```html
<a href="https://github.com/" target="_blank">Open GitHub in a new tab</a>
```

**Comment by mmarkelov** [comment]
Sorry that is my fault! Tried to do this using Link component, but now understand that is not right way! Thanks a lot!

**Comment by frenzzy** [comment]
You also can use `Link` component, but then need to add one more check [there](https://github.com/kriasoft/react-starter-kit/blob/master/src/components/Link/Link.js#L38-L44):
```js
if (event.currentTarget.target === '_blank') {
  return;
}
```
so, it's up to you
