### ISSUE TITLE
How to bypass the router to return a real file on a specific location (/test.html or /test.pdf)

### ISSUE THREAD

**Issue by MarijnBrosens** [kriasoft/react-starter-kit#1479]
Hi,
I want to return a file from a specific location  (/test.html or /test.pdf), but the router always intercepts and wants me to return a react component, i want to bypass this behavior. Is there a way around?

**Comment by frenzzy** [comment]
The easiest way is to put your file into `public` folder. Second way is to use [express middleware](https://github.com/kriasoft/react-starter-kit/blob/8e79361d4ccfcbf70530237bfed3033264770df1/src/server.js#L100-L108).
