### ISSUE TITLE
Preloader on route change

### ISSUE THREAD

**Issue by mmarkelov** [kriasoft/react-starter-kit#1481]
Good day! I am using preloader just like in this issue #1033 and it works like a charm, but I wanna to improve this. For example I want to display it, for example if loading page time is greater than 2 seconds. Can I do this? Thanks

**Comment by frenzzy** [comment]
Maybe if improve #1033 with something like this?
```js
let timeout;

function showLoader() {
  clearTimeout(timeout);
  timeout = setTimeout(
    () => { document.getElementById('spinner').style.display = '' },
    2000, // 2 seconds delay
  );
}

function hideLoader() {
  clearTimeout(timeout);
  document.getElementById('spinner').style.display = 'none';
}
```

```js
showLoader(); // document.getElementById('spinner').style.display = '';
hideLoader(); // document.getElementById('spinner').style.display = 'none';
```

**Comment by frenzzy** [comment]
```js
const start = new Date();
// render
const end = new Date();
const diff = end.getTime() - start.getTime();
if (diff > 2000) {
  console.log('Loading is longer than two seconds');
}
```

**Comment by mmarkelov** [comment]
@frenzzy Thanks, just understand that I don't need to use time between renders. So I solve it with this tricky thing:
After src/client.js#117 add
`let showPreloader;
	if (location.pathname.split('/')[1] !== currentLocation.pathname.split('/')[1]) {
		showPreloader = true;
	} else {showPreloader = false;}
`
And show preload only if showPreloader is equal to true. So thanks a lot!
