### ISSUE TITLE
Route exact

### ISSUE THREAD

**Issue by mmarkelov** [kriasoft/react-starter-kit#1488]
Hello! How can I indicate exact route?
With react router it was exact param
<Route exact path="/one" component={About}/>

**Comment by frenzzy** [comment]
All routes exact by default, or can you provide an example what the behavior you expect?

For example `path: '/route/'` will match only `/route/` url.

If you are talking about case-sensitive feature, can you explain why do you need it?
ref https://github.com/kriasoft/universal-router/issues/90

**Comment by mmarkelov** [comment]
@frenzzy with react-router I could do something like this
```<Route exact strict path="/one" component={About}/>```
And this is match only with '/one' and does not with '/one/'
That is my fault I need strict mode with route. Can I pass parameter to do it?

**Comment by frenzzy** [comment]
A trailing slash in url is optional if your router's path does not require it explicitly. There are no option to change the behavior right now, but you can create a feature request to [universal-router repo](https://github.com/kriasoft/universal-router) to add a strict mode support. But anyway I would like to hear any use cases why it may need.

**Comment by frenzzy** [comment]
Btw, if you need two routes with a different behavor depends on trailing slash you can put path with trailing slash first:
```js
const routes = [
  { path: '/one/', action: () => 'Matches only "/one/"'                          },
  { path: '/one',  action: () => 'Matches only "/one" because of previous route' },
];
```

**Comment by mmarkelov** [comment]
@frenzzy Thank you! I just want to know if it is possible. It was seo requirement, so 'strict' param was needed. Thank you! You are awesome!
