### ISSUE TITLE
How to call 2 rest API for 1 resource?

### ISSUE THREAD

**Issue by krrishna22** [kriasoft/react-starter-kit#1490]
Hi All,

I am new with Reactjs . Now I have a requirement to call 2 rest API on click of My training history menu list and populate the response of 1st API to current registration report and response of 2nd API to Registration History report

REFRESH
.
![myapphistory](https://user-images.githubusercontent.com/12063899/34431883-be829708-ecad-11e7-9b08-1cfe65544a91.PNG)

**Below is my code:**

**_App.js_**
...
  render ()
  {
	
  return (
  <Admin
      authClient={authClient}
      title="SS System"
      theme={getMuiTheme (MiaTheme)}
	  
      restClient= {restClient('https://startroi.com/dev/mia',httpClient)}
	  
      menu={MenuLeft}
      customRoutes={AppRoutes}
      loginPage={Login}>
	  
	  <Resource name={`mia/web_home/${this.state.encsessiontoken}`} list={HomePage}    />
	  <Resource name={`mia/training/${this.state.encsessiontoken}`} list={UpcomingTrainings}   /> 
	  <Resource name={`mia/current_registration/${this.state.custNo}/${this.state.encsessiontoken}`} list={MyTrainings} />
      <Resource name="register" edit={Register} />
      
      <Resource name={`posts/${this.state.postNo}`}   list={PostList}/>

  </Admin>
);
}
}

export default App;

**_Code for Menu list:_**

...
<div>

		
      <Menu>
        <MenuItem containerElement={<Link to={`/mia/web_home/${encsessiontoken}`} />} replace  primaryText="Home"                leftIcon={<Home   />} />
        <MenuItem containerElement={<Link to={`/mia/training/${encsessiontoken}`} />} replace primaryText="Upcoming Trainings"  leftIcon={<School />} />
        <MenuItem containerElement={<Link to= {`/mia/current_registration/${custNo}/${encsessiontoken}`} />} replace primaryText="My Training History" leftIcon={<School />} />

		       
        <Divider />
        <MenuItem primaryText="Submit Applications"  leftIcon={<ContentLink />}  rightIcon={<ArrowDropRight />}
            menuItems={[
            <Subheader>Application Types</Subheader>,
            <Divider />,
            <MenuItem containerElement={<Link to="/submitMembership" />}  primaryText="Membership" />,

            <MenuItem primaryText="CARE" />
            ]}
        />
        <Divider />
		
		<WithPermission authClient={authClient} value="2">
        <MenuItem containerElement={<Link to="/applicationsHistory" />}   primaryText="My Applications History"  leftIcon={<History />} />
		</WithPermission>
		
        <MenuItem primaryText="My Payments"       leftIcon={<Payment />} />
		
		<WithPermission authClient={authClient} value="1">
        <MenuItem primaryText="My CPE Hours"      leftIcon={<ContentLink />} />
		</WithPermission>
        <Divider />
        <MenuItem primaryText="My Notifications"   leftIcon={<Notification />} />

        <Divider />
        <MenuItem primaryText="My Mentees"        leftIcon={<PeopleOutline />} />
        <MenuItem primaryText="My Privileges"      leftIcon={<CardGiftcard />} />
        <MenuItem primaryText="Update My Profile"   leftIcon={<PersonAdd />} />
        <MenuItem primaryText="Enquiry"           leftIcon={<InfoOutline />} />
        <MenuItem containerElement={<Link to={`/posts/${postNo}`} />}  primaryText="FAQ"               leftIcon={<QuestionAnswer />} />
        <Divider />
        {logout}
      </Menu>

</div>

);

export default  (MenuLeft);

**_Code for My training component_** 

import React from 'react';

//import {List, Datagrid, TextField } from 'admin-on-rest';
import { List, Edit, Create, Datagrid, ReferenceField, TextField, EmailField, EditButton, DisabledInput, LongTextInput, ReferenceInput, SelectInput, SimpleForm, TextInput } from 'admin-on-rest';

export const MyTrainings =(props) =>
(
  <div>
<List {...props} title="Current Registration">
  <Datagrid>
    <TextField source="id" />
    <TextField source="EVT_TITLE" label = "Event Title"/>
    <TextField source="EVT_CPE_HOURS" />
    <TextField source="EVR_REG_STATUS" />
                <EditButton />
  </Datagrid>
</List>

<List {...props} title="Registration History">
  <Datagrid>
    <TextField source="id" />
    <TextField source="EVT_TITLE" label = "Event Title"/>
    <TextField source="EVT_CPE_HOURS" />
    <TextField source="EVR_REG_STATUS" />
                 
  </Datagrid>
</List>
</div>
);

**Comment by VrajSolanki** [comment]
I understand that you want to call 2 rest apis on clicking My Training History.
this can be done using redux/apollo
onClicking the div dispatch a thunk which dispatches 2 other thunks internally each which calls the api individually, which on success updates your redux or apollo store.

**Comment by frenzzy** [comment]
```js
const [dataA, dataB] = await Promise.all([
  fetch('/api/a'),
  fetch('/api/b'),
]);
```

**Comment by ulani** [comment]
@krrishna22   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
