### ISSUE TITLE
请教一下，这个框架更新之后，，怎么配置百度的ECharts

### ISSUE THREAD

**Issue by thb2338** [kriasoft/react-starter-kit#1494]
现在我遇到的问题是，在第一次进入界面，routes的地址正确的，，但是，我按F5刷新后，框架会在routes里面报错，有大神知道什么问题吗？好像报的错误是地址不正确

**Comment by langpavel** [comment]
In English please. Thank you!

**Comment by l2weng** [comment]
@thb2338 please pass the window object to your component. It works well.

**Comment by thb2338** [comment]
@l2weng Not very know what you mean, I've tried on componentDidMount inside, however, the error is the same, but, I use the antd echarts library, didn't appear, will use baidu, have you solved the problem?
