### ISSUE TITLE
Problem async/await jest test

### ISSUE THREAD

**Issue by ValSol** [kriasoft/react-starter-kit#1497]
```
const testAsync = () => Promise.resolve('hello world');

describe('async await test', () => {
  test('try 1', async () => {
    const result = await testAsync();
    expect(result).toBe('hello world');
  });
});
```

```
async await test
     encountered a declaration exception (5ms)

async await test › encountered a declaration exception

ReferenceError: regeneratorRuntime is not defined
    
    4  |   
    5  |   describe('async await test', () => {
  > 6  |   test('try 1', async () => {
    7  |     const result = await testAsync();
    8  |     expect(result).toBe('hello world');
    9  |   });
```

**Comment by ValSol** [comment]
Found a way:

In the file **jest.config.js** set:

`
setupFiles: ["<rootDir>/jest.setup.js"],
`

create new file **jest.setup.js** with this content:

`
import '@babel/polyfill';
`

Working!

**Comment by langpavel** [comment]
Hey, Thank you! Do you think that this should not be included?
New versions of node should support this seamplesly I believe :slightly_smiling_face:

**Comment by ValSol** [comment]
I used node version 8.9.4 on Windows 7 and had the problem. Generally, including **polyfill** makes available using any last ES6/ES7/ES8 semantic innovations in **tests**.

**Comment by langpavel** [comment]
you are running test with `babel-node` ?
`regeneratorRuntime` is used by babel. There is also `babel-plugin-regenerator-runtime` plugin which can inject this dependency automatically I believe..
Best will be to use simply `node` instead of `babel-node`

**Comment by ValSol** [comment]
I'm running test with node 8.9.4.
But you use **babel/polyfill** in **webpack** despite what feauteres support **node**.

**Comment by ValSol** [comment]
Figuring out how to make the `webdriver.io + mocha` work with `RSK` found another way for solution the issue. Instead of changing **jest.config.js** and adding **jest.setup.js** file  we: 

`yarn add --dev @babel/runtime@7.0.0-beta.36 @babel/plugin-transform-runtime@7.0.0-beta.36`

and insert this row:

`plugins: [['@babel/plugin-transform-runtime', { polyfill: false }]],`

in the **.babelrc.js** file

**Comment by zargold** [comment]
yes I too would prefer to not have to compile/use polyfills for my test suite Node v 10.0.0 I still get async
``` javascript
beforeEach(async () => {
                      ^
    SyntaxError: Unexpected token (
```

**Comment by ulani** [comment]
@ValSol   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
