### ISSUE TITLE
Scroll to hash anchor not working on initial render

### ISSUE THREAD

**Issue by jorrit** [kriasoft/react-starter-kit#1501]
The code in client.js supports jumping to an anchor while navigating through the site. However, this code is not hit when initially loading the site with a hash.

I created a fork of react-starter-kit at https://github.com/jorrit/react-starter-kit/tree/hashinit where the footer has an id attribute. The header contains a Link component to #footer and clicking this link works fine.

However, visiting http://localhost:3000/#footer on a new tab doesn't scroll to the footer.

Should React take care of scrolling to the anchor on first load? Or should the code in client.js that scrolls to an anchor also be executed when `isInitialRender = true`?

Finally, I added a regular `<a href="#footer">` to the navigation bar. This one doesn't work at all, because regular hash changes cause a `POP` history event and `<Link to="#footer">` causes a `PUSH` event. The condition `if (action === 'PUSH') {` should be extended to check for location changes that indicate a hash change.

I could make some PR's if you like but perhaps the direction of the solution should be discussed first because there are different ways to handle this.

**Comment by frenzzy** [comment]
I believe the browser should care about scrolling to hash at initial page load. If it does not work, then probably [disabling scroll restoration code](https://github.com/kriasoft/react-starter-kit/blob/065fb242806c3c6378cd94386603253611f88a0f/src/client.js#L47-L49) must be executed right after initial page render but not before as it is now.

**Comment by jorrit** [comment]
Moving that line to after `if (isInitialRender) { ... }` correctly allows scrolling on first load. However, clicking on a  regular `<a>` anchor link still doesn't work.

**Comment by frenzzy** [comment]
What if you move them inside `if (isInitialRender) {...}` ?

**Comment by jorrit** [comment]
Good idea, will try later.

**Comment by jorrit** [comment]
Seems to work, see #1518.

**Comment by jorrit** [comment]
There is a remaining issue that is not fixed by #1518: regular `<a>` links to anchors don't work.

**Comment by frenzzy** [comment]
They should now work, you must use `<Link>` component instead.
But if you are about `dangerouslySetInnerHTML` case, see #784

**Comment by jorrit** [comment]
Thanks, I was also thinking about the situation where `<a>` tags are present in data coming from a CMS or something like that. I think `onLocationChange` can be amended to take into account these kinds of location changes. I don't yet need this myself and I have the feeling that it isn't a priority for you either, so I will not create a PR for it now. Maybe later.
