### ISSUE TITLE
Problem with update keywords when open page

### ISSUE THREAD

**Issue by mmarkelov** [kriasoft/react-starter-kit#1508]
There is problem with updating keywords:
In my client.js: 
```javascript
updateMeta('keywords', route.keywords);
```
I pass keywords with route, but something does wrong. I pass description - this is just fine, but keywords appears only if I change route. First time I open page - there is no keywords, but there is description

**Comment by langpavel** [comment]
I absolutely cannot even guess what you want to do and how did you try it.
Please, add more context and you can reopen then
