### ISSUE TITLE
build error on windows 10

### ISSUE THREAD

**Issue by eeeman1** [kriasoft/react-starter-kit#1511]
node - v8.9.4
npm - 5.6.0
an error occurs when starting build - 
the author that this fails on your system:
npm ERR!     if test -d ./build; then rm -r build; fi

**Comment by frenzzy** [comment]
What the actual error message do you see?

**Comment by eeeman1** [comment]
![default](https://user-images.githubusercontent.com/26044998/35112126-218cda30-fc8e-11e7-8677-665273be4794.JPG)

**Comment by frenzzy** [comment]
It looks like you write to a wrong repository.
Here is `react-starter-kit` but not `isomorphic-react-starter-kit`.

**Comment by eeeman1** [comment]
How does the application name and the reference to the repository affect this error?

**Comment by frenzzy** [comment]
You are not using this `react-starter-kit`, your issue is not related to this repo

**Comment by frenzzy** [comment]
If you want to use this project, please see [Getting Started Guide](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md) to begin.

**Comment by eeeman1** [comment]
this project is yours, I just changed the name

**Comment by frenzzy** [comment]
`npm run build` in this project must run `babel-node tools/run build`, see [package.json#L138](https://github.com/kriasoft/react-starter-kit/blob/065fb242806c3c6378cd94386603253611f88a0f/package.json#L138)
in your screenshot it runs `npm run clean && npm run build:client && npm run build:server`
