### ISSUE TITLE
Disable BrowserSync keep webpack watch and HMR?

### ISSUE THREAD

**Issue by reactor81** [kriasoft/react-starter-kit#1516]
Is it possible to disable BrowserSync but keep the webpack watch and HMR running? I want to be able to update real-time on the fly, but I really dont want form syncronization.

**Comment by reactor81** [comment]
tim-soft helped me find this in tools/start.js by adding "ghostMode: false," to the browserSync init options.

**Comment by frenzzy** [comment]
Maybe you can create a PR with this option a comment why you may need to change it?
