### ISSUE TITLE
Looking for docs to setup reactjs with ssl and https using Apache as the proxy.

### ISSUE THREAD

**Issue by wyattbiker** [kriasoft/react-starter-kit#1523]
I have it 1/2 working with the vanilla RSK test page (I am using SSL for myserver.com)

>         RewriteEngine  On
>         RewriteRule "^/rfun$" "https://%{HTTP_HOST}/rfun/"  [PT] #[L]
>         ProxyPass /rfun/ http://localhost:3000/
>         ProxyPassReverse /rfun/ http://localhost:3000/

However the response page does not alias back any links with **/rfun/**

So what I would like is for the baseURL to be https://myserver.com/rfun/ instead of https://myserver.com/

For example a link on the page, shows the URL as follows:
https://myserver.com/assets/src/components/Header/logo-small.png?2f751285   
instead of 
https://myserver.com/rfun/assets/src/components/Header/logo-small.png?2f751285

**Comment by frenzzy** [comment]
Looks like you need to specify proper [baseUrl](https://github.com/kriasoft/universal-router/blob/v5.1.0/docs/api.md)/[publicPath](https://github.com/kriasoft/react-starter-kit/blob/2c8558140b10548e1e46e1c15e30679183711ac7/tools/webpack.config.js#L45) etc.

**Comment by frenzzy** [comment]
Also take a look: https://github.com/h5bp/server-configs-apache

**Comment by wyattbiker** [comment]
baseUrl will be handy because I don't need to add more certs.

I am also looking at the option of having subdomains. https://serverfault.com/questions/670753/two-https-virtualhosts-on-same-server-same-port-different-subdomains

Thanks!
