### ISSUE TITLE
Question about ReactJS single page in production with Apache.

### ISSUE THREAD

**Issue by wyattbiker** [kriasoft/react-starter-kit#1525]
I'd like to use Apache to serve static ReactJS content without the need of nodejs running.

Once I create a bundle and just a bunch of static files (e.g. html, json, txt, jpg, etc) on the back end, do I still need nodejs or webpack for anything in production. Also can I use .fetch() for fetching data, from REST services? 

In RSK the default dependencies include express and sqlite. What else would I need to forego to make this work (e.g. sqllite?). Thanks

```
  "dependencies": {
    "@babel/polyfill": "7.0.0-beta.36",
    "bluebird": "^3.5.1",
    "body-parser": "^1.18.2",
    "classnames": "^2.2.5",
    "cookie-parser": "^1.4.3",
    "core-js": "^2.5.3",
    "express": "^4.16.2",
    "express-graphql": "^0.6.11",
    "express-jwt": "^5.3.0",
    "graphql": "^0.12.3",
    "history": "^4.7.2",
    "isomorphic-style-loader": "^4.0.0",
    "jsonwebtoken": "^8.1.0",
    "node-fetch": "^1.7.3",
    "normalize.css": "^7.0.0",
    "passport": "^0.4.0",
    "passport-facebook": "^2.1.1",
    "pretty-error": "^2.1.1",
    "prop-types": "^15.6.0",
    "query-string": "^5.0.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "sequelize": "^4.28.6",
    "serialize-javascript": "^1.3.0",
    "source-map-support": "^0.5.0",
    "sqlite3": "^3.1.13",
    "universal-router": "^5.0.0",
    "whatwg-fetch": "^2.0.3"
  },
```

**Comment by frenzzy** [comment]
If you don't want ti run node.js server, then you have the following options (choose 1 or 2 or 3):
1. Build an app to static files [`yarn run build --static`](https://github.com/kriasoft/react-starter-kit/tree/master/tools) and serve the content of `build` folder only with no dependencies.
2. Use [`react-firebase-starter`](https://github.com/kriasoft/react-firebase-starter).
3. Use [`create-react-app`](https://github.com/facebook/create-react-app).
