### ISSUE TITLE
Problem with Mobile Safari - (9.0)

### ISSUE THREAD

**Issue by mmarkelov** [kriasoft/react-starter-kit#1527]
Good evening! There is a problem with prod version. It doesn't work and throw Type error
![error](http://dl3.joxi.net/drive/2018/02/02/0026/1598/1717822/22/e5b96f183e.jpg)
But it is all right with dev. So I can't understand what is wrong and how can i fix this.
Thank you!

**Comment by frenzzy** [comment]
Try to disable [react optimization plugins](https://github.com/kriasoft/react-starter-kit/blob/c3f0c85e387a2df8579701ab871842386325ab97/tools/webpack.config.js#L106-L115), maybe it is related.
