### ISSUE TITLE
Any Mocha docs need to be erased

### ISSUE THREAD

**Issue by piglovesyou** [kriasoft/react-starter-kit#1529]
From #657 . There is already Jest installed so any docs should not include something about Mocha to avoid confusion.

> @langpavel
> Documentation indeed needs improvements

There are still article written about Mocha:
https://github.com/kriasoft/react-starter-kit/blob/master/docs/testing-your-application.md#testing-your-application

**Comment by langpavel** [comment]
Good point. This should be easy PR! :-)

**Comment by aguscha333** [comment]
I can work on this if it's not taken already 😄

**Comment by aguscha333** [comment]
Wasn't this done already in #1624?

**Comment by piglovesyou** [comment]
@aguscha333 Seems you're right. And I found a few more "mocha" descriptions left in `docs/getting-started.md` so glad if you would modify that part too.

**Comment by aguscha333** [comment]
@piglovesyou done, link to the PR #1729

**Comment by piglovesyou** [comment]
Resolved by #1729 .
