### ISSUE TITLE
is it possible to run with forever

### ISSUE THREAD

**Issue by hoonyland** [kriasoft/react-starter-kit#153]
I'd like to run an app with this template on linux server.

can I run with forever or something like forever?
##

**Comment by cmnstmntmn** [comment]
@thechunsik cource you can; just package it and than run 

```
forever start  build/server.js
```

**Comment by korczis** [comment]
I am running in way mentioned by @cmnstmntmn and it works like a charm!

**Comment by jhabdas** [comment]
[`PM2`](devo.ps/blog/goodbye-node-forever-hello-pm2/) is alternative to `forever`.

**Comment by dastiw1** [comment]
How can i run server with PM2?
i can try  _pm2 start build/server.js _  and   _pm2 start tools/run.js_
But it's not correct way. How to?

**Comment by dfrankland** [comment]
For [pm2](https://www.npmjs.com/package/pm2) you will need to create an [application declaration](http://pm2.keymetrics.io/docs/usage/application-declaration/) at the root of react-starter-kit like this:
```json
{
  "apps": [
    {
      "name": "react-starter-kit",
      "script": "tools/run.js",
      "args": ["start", "--release"],
      "exec_interpreter": "./node_modules/.bin/babel-node",
      "exec_mode": "fork",
    }
  ]
}
```

**Comment by Ilshidur** [comment]
@dfrankland Sorry to post this after one year, but I had to point this out for other people reaching to our answer :

`babel-node` must not be run in production ! See [the doc](https://babeljs.io/docs/usage/cli/#babel-node) for more information.

I strongly recommend to build the sources instead and run the main script using the following command :
`node build/server.js`.

**Comment by ulani** [comment]
@hoonyland   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
