### ISSUE TITLE
Why are you using universal-router instead of react-router?

### ISSUE THREAD

**Issue by JulianeAlbuquerque** [kriasoft/react-starter-kit#1531]
What's the better decision I should have to use universal-router instead or react-router? I cannot know the difference between those libraries.

**Comment by langpavel** [comment]
`universal-router` was created to work seamlessly on the server as on the client. 
`react-router` had much more gotchas in early stages and was designed with focus on client side routing.
I don't know how comfort is using `react-router` on the server now, but it was really hard before.

`react-router` had hack in its early stages to do the job right.
React was simply not ready and writing routes in React syntax in the past was really tricky. JSX above purpose was not work well leading to really hard to spot bugs and unpredictable behavior.
Some constructs was too fragile in the past. Then hype comes and time and needs allows `react-router` to evolve
In past it was really better choice to use `express` compatible solution on client then the other way.

`universal-router` is small and simple to learn+use and does not need to be replaced by my opinion.
You will see in next React release (17) that there is evolution in *context* behavior an may be possible that `react-router` will need update, may be it will work better, but `universal-router` will still work as expected without need to upgrade/change anything.

May be @frenzzy or @koistya can answer you better, but I think about replacing in past and I decided that continuity and maintainability of projects based on RSK will be better if we keep `universal-router`.

See [all issues containing `react-router`](https://github.com/kriasoft/react-starter-kit/issues?utf8=%E2%9C%93&q=%22react-router%22), you can **@** mention me directly if you want my opinion

**Comment by JulianeAlbuquerque** [comment]
Perfect, Thanks for answering my question!
