### ISSUE TITLE
Network error when make a request from the react-native app

### ISSUE THREAD

**Issue by nguyenviethoa** [kriasoft/react-starter-kit#1537]
Hi,

I got this error when make a query to the server (that use react-starter-kit). 
![error](https://user-images.githubusercontent.com/3621738/35953661-45359550-0cb8-11e8-838d-3e8be8a883a9.png)

The code that we used in the react-native app to make a request to the server:
![code](https://user-images.githubusercontent.com/3621738/35953668-4adeb068-0cb8-11e8-84bc-3e14f8c8d96e.png)

The code that initiate appollo-client and the connection to server  
![apolloclient](https://user-images.githubusercontent.com/3621738/35953712-861d0e86-0cb8-11e8-96f6-bbe2019a7c49.png)

I have tested with Graphiql and the web app, that work fine without any problem. Do you have any idea pls? and are there someone tested with react-native?

Thanks

**Comment by langpavel** [comment]
Sorry,I don't know how to help. Try catch request on the network how it looks and what it returns and figure out where the misunderstanding is. Then reopen :-)
