### ISSUE TITLE
will RSK-client bring re-render the DOM?

### ISSUE THREAD

**Issue by TristanDongMaster** [kriasoft/react-starter-kit#1539]
question: please think about the scene
1. RSK server will return the total HTML in browser
2. RSK client also generated the same HTML.
I didn't find RSK use "checksum", will it bring re-render the DOM?
please refer to link:https://stackoverflow.com/questions/34311221/what-is-checksum-in-react-and-how-to-use-it.

**Comment by frenzzy** [comment]
Please see [official React.js hydrate docs](https://reactjs.org/docs/react-dom.html#hydrate).
https://github.com/kriasoft/react-starter-kit/blob/9081d93b5331f338b3112e99ef2e0bb80b59fa44/src/client.js#L79
