### ISSUE TITLE
how to build source to html/css/js to bring up the system

### ISSUE THREAD

**Issue by ducvietsqt** [kriasoft/react-starter-kit#1548]
i did build to source of forder  ./build by command npm run build but:
- i not find file html and i do not know how to bring up forder source in /build to server not use nodejs
pls help me!

**Comment by frenzzy** [comment]
@ducvietsqt use `yarn run build --static --release`

**Comment by ducvietsqt** [comment]
@frenzzy thanks so much, this work fine!
you please update document for other user don't know that!

**Comment by frenzzy** [comment]
@ducvietsqt docs are here: [/tools](https://github.com/kriasoft/react-starter-kit/blob/master/tools/README.md#build-automation-tools)
