### ISSUE TITLE
Upgrade to Webpack 4.0

### ISSUE THREAD

**Issue by rodeyseijkens** [kriasoft/react-starter-kit#1549]
Well [Webpack 4.0](https://github.com/webpack/webpack/releases/tag/v4.0.0) is out and it is of course awesome, so we need an upgrade.

Things to ook out for:
- You have to choose (mode or --mode) between two modes now: production or development
- ModuleConcatenationPlugin -> optimization.concatenateModules (on by default in production mode)
- CommonsChunkPlugin was removed -> optimization.splitChunks, optimization.runtimeChunk
- Resolving can now be configured with module.rules[].resolve. It's merged with the global configuration.

There is probably more but these are the first things that I saw that needed to be addressed I think.

UPDATE:
So far I have it working, but there is a weird bug in BundleAnalyzerPlugin where it cannot analyse the "shared" bundle. Not sure why but probably has to do something with JSONP
I'll make an PR soon with the "bug" in there.

**Comment by joemewes** [comment]
where are you specifying the `--mode` option ?  Inline with the `babel-node tools/run start` command?  or in the build/start scripts somewhere?

**Comment by rodeyseijkens** [comment]
@joemewes In the webpack config itself. 
The PR was wrong, too many changes from my own fork, but the initial setup was there:
https://github.com/rodeyseijkens/react-starter-kit/blob/73c445017ef57414dd6c9ed2bac862ccb4436488/tools/webpack.config.js#L35

**Comment by tim-soft** [comment]
Have you tested BundleAnalyzerPlugin after this PR? https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/159
