### ISSUE TITLE
Run function on server only?

### ISSUE THREAD

**Issue by colt082295** [kriasoft/react-starter-kit#1551]
I need to be able to run some functions on the server only, and not both client and server. Is there a way I can do this? I'm trying to run the function based on a route/api call. When I do this, it runs on both client and server.

**Comment by frenzzy** [comment]
```js
if (process.env.BROWSER) {
  console.log('client')
} else {
  console.log('server')
}
```

**Comment by colt082295** [comment]
Thanks, works great!
