### ISSUE TITLE
How to set canonicalUrl while using SSR ?

### ISSUE THREAD

**Issue by manoj150283** [kriasoft/react-starter-kit#1554]
Hi, 

I am using react-intl branch for my website which is multilingual with SSR ? I am not finding any way to update the canonicalUrl.

Any help will be highly appreciated.

**Comment by frenzzy** [comment]
Return a canonical url from your [route](https://github.com/kriasoft/react-starter-kit/blob/6c599b72e6ca1f75f9e52b995a7f9a6f387555ea/src/routes/about/index.js#L16)
```js
function action() {
  return {
    title: 'Page',
    canonicalUrl: 'http://example.com/page',
    component: <Page />,
  };
}
```
and render it inside your [`src/components/Html.js`](https://github.com/kriasoft/react-starter-kit/blob/6c599b72e6ca1f75f9e52b995a7f9a6f387555ea/src/components/Html.js#L51) component
```js
<link rel="canonical" href={canonicalUrl}>
```

**Comment by manoj150283** [comment]
Hi frenzzy,

Thank you for this suggestion but here I am taking about dynamic links. Since my website is multilingual, I have common route for all the language. In that case how I will set the url ?
e.g. 

http://example.com/page
http://example.com/ar/page
http://example.com/fr/page
http://example.com/ru/page

All the above urls are pointing to same route. I hope you understand my concern.

**Comment by manoj150283** [comment]
Hi @frenzzy , Thank you for the solution. Closing this for now :)
