### ISSUE TITLE
TypeError: Cannot read property 'js' of undefined [webpack 4]

### ISSUE THREAD

**Issue by dbrrt** [kriasoft/react-starter-kit#1555]
Error after upgrade to webpack 4.
I removed `webpack.optimize.CommonsChunkPlugin` from webpack config,  then got this error after generating the project assets.

**Comment by dbrrt** [comment]
similar to #1549

**Comment by dbrrt** [comment]
Solved after replacing in server.js (line 162)
`data.scripts = [assets.vendor.js]`
with
`data.scripts = []`

**Comment by langpavel** [comment]
Not good solution, check current
