### ISSUE TITLE
how to use localStorage in project?

### ISSUE THREAD

**Issue by ducvietsqt** [kriasoft/react-starter-kit#1556]
i used HTML5 API localStorage in project but look at the command line build that show issues 'localStorage 
 is not define', the same with 'window, etc...', pls give know how to use that?

**Comment by frenzzy** [comment]
use it inside `src/client.js`

**Comment by hxg543453406** [comment]
used like that:
let localStorage  = window.localStorage;
 localStorage.setItem('a', '1111');
