### ISSUE TITLE
Javascript Heap Out Of Memory

### ISSUE THREAD

**Issue by mackenzienolan** [kriasoft/react-starter-kit#1557]
Started happening recently when making changes, and has now not allowed me to push deploy with `yarn deploy` to heroku. Wondering if anyone has had this issue.
 
`<--- Last few GCs --->

[8337:0x105800000]   762889 ms: Mark-sweep 1337.5 (1429.1) -> 1337.5 (1429.1) MB, 736.3 / 0.0 ms  allocation failure GC in old space requested
[8337:0x105800000]   763863 ms: Mark-sweep 1337.5 (1429.1) -> 1337.5 (1423.1) MB, 973.9 / 0.0 ms  last resort GC in old space requested
[8337:0x105800000]   764714 ms: Mark-sweep 1337.5 (1423.1) -> 1337.5 (1423.1) MB, 850.7 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3845143a5501 <JSObject>
    0: builtin exit frame: stringify(this=0x384514388d31 <Object map = 0x384548a82ba1>,0x3845ca7822d1 <undefined>,0x3845ca7822d1 <undefined>,0x38456944d611 <Object map = 0x3845e9f079a9>)

    1: arguments adaptor frame: 1->3
    2: /* anonymous */(aka /* anonymous */) [/Users/mackenzienolan/Documents/Shuttershare/web/node_modules/webpack/lib/SourceMapDevToolPlugin.js:173] [bytecode=0x3845ac4e97a...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/Cellar/node/9.7.1/bin/node]
 2: node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node/9.7.1/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/Cellar/node/9.7.1/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/Cellar/node/9.7.1/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/Cellar/node/9.7.1/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/Cellar/node/9.7.1/bin/node]
 7: v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [/usr/local/Cellar/node/9.7.1/bin/node]
 8: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/Cellar/node/9.7.1/bin/node]
 9: v8::internal::JsonStringifier::SerializeArrayLikeSlow(v8::internal::Handle<v8::internal::JSReceiver>, unsigned int, unsigned int) [/usr/local/Cellar/node/9.7.1/bin/node]
10: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/Cellar/node/9.7.1/bin/node]
11: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/Cellar/node/9.7.1/bin/node]
12: v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/local/Cellar/node/9.7.1/bin/node]
13: v8::internal::Builtin_Impl_JsonStringify(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/Cellar/node/9.7.1/bin/node]
14: 0x36021588697d
15: 0x36021588535f
16: 0x36021593d196
17: 0x36021588535f
error An unexpected error occurred: "Command failed.
Exit signal: SIGABRT
Command: sh
Arguments: -c babel-node tools/run deploy
`

Error Log 
`Arguments: 
  /usr/local/Cellar/node/9.7.1/bin/node /usr/local/Cellar/yarn/1.5.1/libexec/bin/yarn.js deploy

PATH: 
  /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Yarn version: 
  1.5.1

Node version: 
  9.7.1

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "web",
    "version": "0.0.0",
    "private": true,
    "engines": {
      "node": "^9.3.0",
      "npm": ">=3.10"
    },
    "browserslist": [
      ">1%",
      "last 4 versions",
      "Firefox ESR",
      "not ie < 9"
    ]`

**Comment by frenzzy** [comment]
Looks like you have a memory leak somewhere in your app, try to find it.
