### ISSUE TITLE
ReferenceError: document is not defined with echart

### ISSUE THREAD

**Issue by winwave** [kriasoft/react-starter-kit#1559]
Hello,
I am using react start kit. I import react echart  but i have an error. Have you the error like that
![image](https://user-images.githubusercontent.com/19307759/36988496-50e64732-209f-11e8-8d07-b08afc921120.png)
here is my code
![image](https://user-images.githubusercontent.com/19307759/37023837-6f5c276c-2127-11e8-8441-ea5fa194ed38.png)
![image](https://user-images.githubusercontent.com/19307759/37023886-9a04a6b0-2127-11e8-8fc2-96888ed2ad22.png)

**Comment by aLIEzsss4** [comment]
can you show getOption function code?or other component has error

**Comment by winwave** [comment]
i think the error isn't in the getOption and components, it's can be at the configuration or version.
The option I got from the soruce exemple [https://github.com/hustcc/echarts-for-react/blob/master/demo/src/charts/Simple.jsx](url)

getOption = () => {
    return {
      title: {
        text: '堆叠区域图'
      },
      tooltip : {
        trigger: 'axis'
      },
      legend: {
        data:['邮件营销','联盟广告','视频广告']
      },
      toolbox: {
        feature: {
          saveAsImage: {}
        }
      },
      grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
      },
      xAxis : [
        {
          type : 'category',
          boundaryGap : false,
          data : ['周一','周二','周三','周四','周五','周六','周日']
        }
      ],
      yAxis : [
        {
          type : 'value'
        }
      ],
      series : [
        {
          name:'邮件营销',
          type:'line',
          stack: '总量',
          areaStyle: {normal: {}},
          data:[120, 132, 101, 134, 90, 230, 210]
        },
        {
          name:'联盟广告',
          type:'line',
          stack: '总量',
          areaStyle: {normal: {}},
          data:[220, 182, 191, 234, 290, 330, 310]
        },
        {
          name:'视频广告',
          type:'line',
          stack: '总量',
          areaStyle: {normal: {}},
          data:[150, 232, 201, 154, 190, 330, 410]
        }
      ]
    };
  };

**Comment by winwave** [comment]
@frenzzy It works, tks so much :+1:
