### ISSUE TITLE
chinese display will be garbled,is this a bug ? how to prevent this from happending

### ISSUE THREAD

**Issue by aLIEzsss4** [kriasoft/react-starter-kit#1560]
const data={
        Q:'数字品牌榜的数据来源是什么？',
        A:`我们运用先进的大数据采集、处理和分析技术，每日定向追踪中国主流社交媒体平台微博、微信订阅号、今日头条（头条号和悟空问答）、知乎等平台上的用户评论和文章，数据积累迄今已达10亿条以上，并继续逐日增长。同时，我们的已有数据已包含了自2016年1月1日以来的所有与追踪品牌相关的四个社交媒体平台上的内容。<br>
        所有原始数据和信息均来自于互联网用户的真实表达，我们仅运用云计算和自然语言处理技术，对此进行记录、追踪和计算，而并不干预，由此建立数字品牌榜的数据和计算基础。`
      }

display:
![_20180306182153](https://user-images.githubusercontent.com/24380830/37027076-493f71da-216b-11e8-9649-04c112acfa4b.png)

sometimes there will bee such a situation ，can explain why this is the case ,thank you!:smiley::smiley:

**Comment by frenzzy** [comment]
Why do you think it is related to react-starter-kit?

**Comment by tim-soft** [comment]
I can definitely tell you that your db must have the right charset to _store_ those characters.
