### ISSUE TITLE
yarn test failed: src/components/Layout/Layout.test.js: Unexpected token (22:8)

### ISSUE THREAD

**Issue by pfxstar** [kriasoft/react-starter-kit#1564]
When I run "yarn test", I get this error:

$ yarn test
yarn test v0.21.3
$ jest 
 FAIL  src/components/Layout/Layout.test.js
  ● Test suite failed to run

    /my-local-project-path/src/components/Layout/Layout.test.js: Unexpected token (22:8)
        20 |     const wrapper = renderer
        21  |       .create(
      > 22 |         <App context={{ insertCss: () => {}, fetch: () => {} }}>
               |         ^
        23 |           <Layout>
        24 |             <div className="child" />
        25 |           </Layout>

Test Suites: 1 failed, 1 total

**Comment by rodeyseijkens** [comment]
Added the fix for this in #1562

**Comment by langpavel** [comment]
#1562 is merged, so I'm closing
