### ISSUE TITLE
Intergrating jquery with Reactjs

### ISSUE THREAD

**Issue by anitahkimanzi** [kriasoft/react-starter-kit#1565]
I am wondering why this does not work.please help me it has took  me two weeks trying to solve this but nothing I have done.Still throwing error.

ERROR.
![capture](https://user-images.githubusercontent.com/25051454/37344495-974df516-26db-11e8-955b-423b13b9adee.PNG)

CODE.
![code](https://user-images.githubusercontent.com/25051454/37344496-9781e218-26db-11e8-8d50-877ddda1dc34.PNG)

WITHOUT JQUERY.
![mainwebsite](https://user-images.githubusercontent.com/25051454/37344757-4a7d424a-26dc-11e8-807b-5f09d876d3b0.PNG)

**Comment by anitahkimanzi** [comment]
http://materializecss.com/side-nav.html#options  refers it as a jquery so what is it if not jquery.

**Comment by anitahkimanzi** [comment]
what is it then because materialize-css refers it as jquery plugin.
http://materializecss.com/side-nav.html#options
![image](https://user-images.githubusercontent.com/25051454/37346926-b7c24f26-26e1-11e8-9acb-8a7688517fd8.png)

**Comment by frenzzy** [comment]
Looks like you have missed installation instructions: http://materializecss.com/getting-started.html

```jsx
// src/components/Html.js
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js" />
```

**Comment by anitahkimanzi** [comment]
Thanks you frenzzy for your help though I don't think I missed the installation instruction because everything else in the Reactjs project that  I am doing,I am using materialize-css and is working including the sidenav, only **jquery plugin initialization** method to make it slide out it's not working.

**Comment by anitahkimanzi** [comment]
Thanks you frenzzy for your help though I don't think I missed the installation instruction because everything else in the Reactjs project that I am doing,I am using materialize-css and is working including the sidenav, only jquery plugin initialization method to make it slide out it's not working.

**Comment by frenzzy** [comment]
@anitahkimanzi how/where you initialize jquery plugin?

If you are adding jquery with materialize as mentioned above in my comment, then you DO NOT NEED to use import from npm ~~`import $ from 'jquery'`~~

**Comment by anitahkimanzi** [comment]
when I don't import $ from jquery it brings an error that $ is not defined.what should I do,I confused

**Comment by frenzzy** [comment]
@anitahkimanzi are you added jquery with plugins before this line?
https://github.com/kriasoft/react-starter-kit/blob/6c599b72e6ca1f75f9e52b995a7f9a6f387555ea/src/components/Html.js#L65

change this line to:
```js
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js" />
{scripts.map(script => <script key={script} src={script} />)} 
```

then use `$` in your components as a global function without `import`.

**Comment by langpavel** [comment]
@anitahkimanzi Looks like you are trying make *ball of mud*..
Do not use jQuery except it's really necessary. Try look for another solutions not using jQuery.

### Why not use jQuery:

 * Need much more boilerplate to correctly mount jQuery on React components,
   even not possible on server, so you kill SSR which is mostly main reason for choosing this kit
 * If you use jQuery, you should not use React for same fragments of DOM
 * It's hard to find bugs, React and jQuery may fight together against you :timer_clock: :bomb: 
 * If you learn React, you can find soon that you are writing smaller, readable and efficient code :tada:
 * You can always use only CSS
 * You can ask your vendor for the best way to integrate with React
