### ISSUE TITLE
use together with server language!

### ISSUE THREAD

**Issue by ducvietsqt** [kriasoft/react-starter-kit#1569]
is it used with server language  as PHP, ... etc, if used it, please can tell me how to use it?

**Comment by WiktorKa** [comment]
This particular project is equipped with Server Side Rendering (meaning same code, or at least parts of it, is run on both client and server sides) so you need a Node.js environment on the server to run it. In other words, this project is about overcoming such concepts as "client side language" and "server side language".  What you're looking is probably non-isomorphic (regular) ReactJS solution (i.e. https://github.com/kriasoft/react-firebase-starter).

**Comment by ducvietsqt** [comment]
ops..! thanks @WiktorKa , This project has crossed the limit of my requirements

**Comment by koistya** [comment]
@ducvietsqt often it makes sense to separate front-end development from API development, especially if different people are working on those parts. You can use RSK for the front-end and server-side rendering (SSR) and compliment it with a PHP-based backend in a separate project. You would deploy the front-end inside a Node.js Docker container, and your API will use a PHP container.
