### ISSUE TITLE
Problems with SVG loading

### ISSUE THREAD

**Issue by maZahaca** [kriasoft/react-starter-kit#1572]
Hi,

I'm having an issue with svg loading on dev builds.
Code example:
```jsx
import logoUrl from './logo.svg';

function () {
    return (
      <img 
            width="30px"
            height="30px"
            src={logoUrl}
      />
    );
}
```

Having the following result:
```html
<img width="20px" height="20px" src="data:image/svg+xml,module.exports = '/assets/src/components/Logo/logo.svg?cbd77765';">
```

Project was started from this version: https://github.com/kriasoft/react-starter-kit/commit/8e79361d4ccfcbf70530237bfed3033264770df1

Could you please help me to find a solution for it?
Thanks

**Comment by langpavel** [comment]
I'm curious if this is still an issue

**Comment by zaycker** [comment]
Not for me :( I tried <4kb and >4kb SVGs, but it's ok. @maZahaca could you make a gist of webpack.config.js please? Did you change it?

**Comment by maZahaca** [comment]
@zaycker you're absolutely right. We have changed the webpack config, which cause this issue.
Sorry for that. Closing now.

**Comment by zaycker** [comment]
@maZahaca did you find a problem? Such boilerplates are made for rapid start and it is OK to change webpack config of your own project (for ex. I like to use svg-sprite-loader for processing svg). Don't limit webpack customizing cause of such a small incidents ^_^
