### ISSUE TITLE
Cant get dynamicy variable

### ISSUE THREAD

**Issue by sydkaz** [kriasoft/react-starter-kit#1573]
I have my URL structure as follow
/users/1

I have created a mapping for required URL in my index.js under routes folder like below
path: '/users/:id',
load: () => import(/* webpackChunkName: 'users' */ './users/')

I am really having issues with getting that "id" in the users/index.js no matter what I do it just doesn't pass to the view.

Can anyone help or advise me how do I go about achieving this?

**Comment by frenzzy** [comment]
```js
// src/routes/users/index.js
import React from 'react'

function action(context, params) {
  console.log(context.params) // => { id: ... }
  console.log(params) // => { id: ... }
  console.log(context.params === params) // => true
  return {
    title: 'User',
    component: <h1>User #{context.params.id}</h1>
  }
}

export default action
```
Universal Router docs:
- [URL Parameters](https://github.com/kriasoft/universal-router/blob/v6.0.0/docs/api.md#url-parameters)
- [Context](https://github.com/kriasoft/universal-router/blob/v6.0.0/docs/api.md#context)

**Comment by sydkaz** [comment]
Thanks for coming back Frenzzy, managed to solve this. Appreciate your help :)
