### ISSUE TITLE
State Management

### ISSUE THREAD

**Issue by Olamyy** [kriasoft/react-starter-kit#1574]
My application logic requires I call a django api for handling registration. I have my function setup as shown below:

``` javascript
app.post('/register', function (req, res) {
    // res.json(req.body);
  const axios_instance = axios.create({
    baseURL: config.api_host,
    timeout: 1000,
    headers: {'Content-Type': 'application/json', 'X-Frame-Options': 'SAMEORIGIN', 'Vary': 'Accept'}
  });
  axios_instance.post('register/', {
    email : req.body.email,
    username : req.body.username,
    password : req.body.password,
    firstname : req.body.firstname,
    lastname : req.body.lastname
  })
    .then(function (response) {
      return res.json(response);
    })
    .catch(function (error) {
      var formerrors = error.response.data 
      res.json(error.response.data);
    });
});
```

My main question is "How do I move this `formerrors`  from the function down to react"? Sorry if it comes out as a bit naive.

**Comment by langpavel** [comment]
Hi @Olamyy 
I'm reading this second time, but don't know what you expect from this, you just write manual proxy for one method.

You should choose state management strategy.
Simplest can be Redux. There are more advanced libraries and even frameworks like Apollo or Relay.

Example of fetching data directly is at `master` branch, on homepage. You should see router.

There are also `feature` branches, in this order: `feature/redux`, `feature/apollo`, `feature/react-intl`

This kit is relatively advanced and it is not for beginners, but we are trying best to keep code easy to read and commented where necessary.

BTW there is advanced example on `feature/apollo` branch, check it out
