### ISSUE TITLE
Login with database user

### ISSUE THREAD

**Issue by nikitong** [kriasoft/react-starter-kit#1575]
Hi all, 

Newbie here, learning React via React-starter-kit. I'm trying to login in the app via a user created in the database, but I get `Cannot POST /login`. I would like to ask: the login system with user/pass is implemented? Does it need any configuration?

Thanks!

**Comment by langpavel** [comment]
You should look at express and server.js code

**Comment by nikitong** [comment]
Hi, thanks! Yeah, I know it will be somewhere in server.js, but I can't find it; can you point to a specific line?

**Comment by langpavel** [comment]
Look at lines [src/server.js lines 64..106](https://github.com/kriasoft/react-starter-kit/blob/master/src/server.js#L64..L106)

**Comment by nikitong** [comment]
Yep, I checked this authentication logic, but it seems to be for Facebook login only; For testing purposes, do I have to implement my own logic if I want to use user/pass from db?

**Comment by langpavel** [comment]
Yes

**Comment by nikitong** [comment]
Great, thanks! : )
