### ISSUE TITLE
https and facebook login

### ISSUE THREAD

**Issue by ghost** [kriasoft/react-starter-kit#1582]
Hi all,

Trying to authenticate, I see that Facebook is asking for https. When I try to connect to `https://localhost:3000` the connection is rejected, both in `master`or `feature/apollo`. Shall I suppose that https is not implemented in RSK? How can this be done?

Thanks!

**Comment by tim-soft** [comment]
Things like SSL are generally better handled upstream through your webserver

**Comment by nikitong** [comment]
Hi @tim-soft, something like this: [https://gist.github.com/jonathantneal/774e4b0b3d4d739cbc53](https://gist.github.com/jonathantneal/774e4b0b3d4d739cbc53)?

**Comment by jorrit** [comment]
Yes, or nginx, or using CloudFlare or CloudFront or something like that.

If you want none of those, see https://aghassi.github.io/ssl-using-express-4/ for adding https support.

**Comment by nikitong** [comment]
@jorrit Thank you, I will have a look to it!
