### ISSUE TITLE
Compatibility with ImmutableJs?

### ISSUE THREAD

**Issue by damiangreen** [kriasoft/react-starter-kit#1587]
Has anyone managed to get this working with Immutable JS?

I ran into issues whereby functions on the Record object did not work. I'm suspecting this is owing to the isomorphic part of the solution whereby it converts the state to JSON.

**Comment by langpavel** [comment]
Of course you can use immutable but you then must use immutable APIs where needed.
In today reality you often do not need immutable, you can write immutable code just by using object or array rest, spread and destructuring.

**Comment by damiangreen** [comment]
Is there something special required to get it to work?

**Comment by langpavel** [comment]
No. Nothing special except you should handle serialization on server and initial revive on client. But you must do this tasks for other cases of you want use library as immutable so you should know this

**Comment by langpavel** [comment]
@damiangreen Do you need something more from us? I'm closing this but anybody can reopen. But please, scope of immutable living out of this starter.

**Comment by damiangreen** [comment]
We're looking to integrate it in the forthcoming weeks so if we come up with a solution we'll endeavour to post the solution for others.
