### ISSUE TITLE
Heads up! "webpack-assets-manifest" v3.0.0 has a breaking change

### ISSUE THREAD

**Issue by rodeyseijkens** [kriasoft/react-starter-kit#1588]
https://github.com/kriasoft/react-starter-kit/blob/454efa6fc57ed814aa563bc89114273a502282a9/tools/webpack.config.js#L319

Starting from version 3.0.0 `webpack-assets-manifest` has a breaking change.

Needs to change to:
```
customize: ({key, value}) => {
...
```

See version change [example](https://github.com/webdeveric/webpack-assets-manifest/blob/master/examples/customized.js)

function arguments change to this now: `entry, original, manifest, asset`

**Comment by langpavel** [comment]
Nice, thanks, will check later today or tomorrow, please ping me if I forget,I need fix this soon

**Comment by langpavel** [comment]
Looks like only needed change is what you already figure out :-)
I'm quite busy, would you like prepare PR against `master` ?

**Comment by rodeyseijkens** [comment]
@langpavel Will do when I have time too :P

**Comment by langpavel** [comment]
I hope this can be closed :slightly_smiling_face:
