### ISSUE TITLE
Continuously re-running express wildcard route

### ISSUE THREAD

**Issue by tim-soft** [kriasoft/react-starter-kit#1589]
The express wildcard route in `server.js` is seemingly executed every 500ms or so, causing this code to run constantly and flood the terminal. This is on a fresh copy of the Apollo branch

```
store.dispatch(
  setRuntimeVariable({
    name: 'initialNow',
    value: Date.now(),
  }),
);
```

Edit: After installing [morgan](https://github.com/expressjs/morgan) it looks like some nonexistent `/json` route keeps getting requested, where is this coming from?

![capture](https://user-images.githubusercontent.com/10257939/38278479-63213f26-3759-11e8-9c23-b5f4bdcbecaa.PNG)

Yet simply adding to `server.js` stops the loop, the body is always an empty object
```
app.get('/json', (req, res, next) => {
    console.log(req.body) // {}
  },
);
```
the request seems to be some kind of keep-alive
```
GET /json - - ms - -
{ host: 'localhost:3000',
  connection: 'keep-alive',
  accept: 'application/json, text/plain, */*',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'en-US,en;q=0.9',
  cookie: 'io=mXbHqzr7hDFaAmElAAAD' }
```

**Comment by langpavel** [comment]
This can be from browsersync or webpack hot plugin or something in your currently opened tabs. This may or may not have origin in RSK. Check all your opened tabs and applications

**Comment by tim-soft** [comment]
This problem happens on Windows 10, only after https://github.com/kriasoft/react-starter-kit/pull/1571 so it seems to be tied into the Webpack 4 upgrade. Before this PR, everything works as expected

I don't notice the problem in linux, the issue isn't resolved?

**Comment by langpavel** [comment]
May be some dev tool is behaving strange on Windows?

**Comment by tim-soft** [comment]
I'm trying to narrow it down, I can actually checkout up to this commit https://github.com/kriasoft/react-starter-kit/commit/454efa6fc57ed814aa563bc89114273a502282a9 just fine, something in the last two commits to apollo/branch is where the issue lies

**Comment by ulani** [comment]
@tim-soft   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
