### ISSUE TITLE
Resolving date fields in schema

### ISSUE THREAD

**Issue by iwoork** [kriasoft/react-starter-kit#1590]
Is there any example on how to resolve fields in Apollo? 

I have this on my schema
```
type History
  id: ID!
  begin: String
  end: String
```
The `begin` and `end` are mapped from a mongodb date function and the API returns the format:

```
...
begin: {
  "$date:": 3347683200000
}
...
```
What's the proper way to resolve this back into a String/Date format?

Thanks in advance!

**Comment by tim-soft** [comment]
What does your resolver look like?

**Comment by iwoork** [comment]
@tim-soft it's something like this:

```
export const resolvers = {
  RootQuery: {
    async getAllPosts(parent, args, context) {
      const url = 'https://www.domain.com/api'
      const result = fetch(url)
      .then(response => response.json())
      .then(data => {
        return data;
      })
      .catch(err => {
        throw err;
      });
      return result;
    },
  },
};
```
Note that `history` is a nested schema:

```
export const queries = [
  `
  getAllPosts: Posts
  `
]
```

and schema is something like:

```
type History
  id: ID!
  begin: String <-- this should be date
  end: String <-- this should be date

type Posts
  id: ID!
  history: [History]
```

**Comment by tim-soft** [comment]
When you return an object from a resolver, graphql matches those object keys to fields on your type. 

In your resolver, spread the original request object, then override the begin and end keys with human readable dates
```
return {
    ...request,
    begin: new Date(request.begin),
    end: new Date(request.end)
}

**Comment by iwoork** [comment]
Thanks @tim-soft! This works!

**Comment by langpavel** [comment]
I also have gist for custom datetime GraphQL type
