### ISSUE TITLE
Question about /data/graphql/Database/* quotes on feature/apollo

### ISSUE THREAD

**Issue by nikitong** [kriasoft/react-starter-kit#1591]
Hi all,

On the branch `feature/apollo` I can see in the folder `/data/graphql/Database/*` some files with code quoted with backticks, like in [https://github.com/kriasoft/react-starter-kit/blob/feature/apollo/src/data/graphql/Database/users/CreateUser.js#L4](https://github.com/kriasoft/react-starter-kit/blob/feature/apollo/src/data/graphql/Database/users/CreateUser.js#L4). 

My question is if this is about Apollo or about Graphql, and what do they mean.

Thanks!

**Comment by tim-soft** [comment]
Apollo's GraphQL-Tools accepts a string for it's schema, what is happening here is you are combining a bunch of strings together like the one you referenced, they get parsed by Apollo and the result is a full graphql schema.

As for why there are template literals, you can add expressions inline which is really handy
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by nikitong** [comment]
Testing the Apollo thing. Really interesting, [this](https://www.youtube.com/watch?v=kXH2dbnHYA0) helped to understand what and why.

Now I'm with `feature/react-intl` branch to test the Apollo thing. I created a model for `Things` in my schema and populated it with some data, only fields for ids and names. 

Using the code from Home component for news and the query for the users I can retrieve all the data of the things in my database and display it. But now I want to display one specific thing, so I create this route in `src/routes/index.js`

``` 
 {
      path: '/onething/:id',
      load: () => import(/* webpackChunkName: 'oneThing' */ './oneThing'),
    },
```

And then I create a structure like Home:
```
├── OneThing.css
├── OneThing.graphql
├── OneThing.js
└── index.js
``` 
In `OneThing.js` I have:
```
import React from 'react';
import { graphql, compose } from 'react-apollo';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import oneThingQuery from './OneThing.graphql';
import s from './OneThing.css';

class OneThing extends React.Component {
  render() {
    const { data: { databaseGetOneThing } } = this.props;
    return (
      <div className={s.root}>
        <div>
          <h1>This is one thing</h1>
          <article key={databaseGetOneThing.id}>
            <h1>{databaseGetOneThing.name}</h1>
          </article>
          }
        </div>
      </div>
    );
  }
}

export default compose(withStyles(s), graphql(oneThingQuery))(OneThing);
```
and in `OneThing.graphql` I have the query:
query AllThings($id: Int!){
  databaseGetOneThing(id: $id){
    id
    name
  }
}
```
Given this, my question is how to pass the variable from the url, lets say `/onething/1`, to the query. I have been reading about it, but I'm pretty confused about that.

**Comment by langpavel** [comment]
Of course, you cannot read property `params` of HoC `OneThing`.
You must pass it form route:
```js
async function action({ client, /* here you can get other params from route */ }) {
  const data = await client.query({
    query: oneThingQuery,
  });
  return {
    title: 'React Starter Kit',
    chunks: ['oneThing'],
    component: (
      <Layout>
        <OneThing news={data.databaseGetOneThing} params={{ id: 1 /* pass down from params */ }} />
      </Layout>
    ),
  };
}
```

**Comment by antoniodcorrea** [comment]
@langpavel I don't know If I understood your answer correctly. I just managed to retrieve the parameter on the url doing this in `index.js`:

Lets say I have this route for a component oneUser:
 ```
    {
      path: '/oneuser/:id',
      load: () => import(/* webpackChunkName: 'oneUser' */ './oneUser'),
    },
```

Then in the component, in `index.js`:
```
import React from 'react';
import OneUser from './OneUser';
import oneUserQuery from './OneUser.graphql';
import Layout from '../../components/Layout';

async function action({ client }, context) {
  const data = await client.query({
    query: oneUserQuery,
    variables: { id: context.id },
  });
  return {
    title: 'React Starter Kit',
    chunks: ['oneUser'],
    component: (
      <Layout>
        <OneUser dataForComponent={data} />
      </Layout>
    ),
  };
}

export default action;
```
The query in `OneUser.graphql` will be:
```
query OneUser($id: Int) {
  databaseGetUser(id: $id) {
    id
    email
  }
}
```
And in `oneUser.js`:

```
import React from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './OneUser.css';

class OneUser extends React.Component {
  render() {
    const { id, email } = this.props.dataForComponent.data.databaseGetUser;

    return (
      <div className={s.root}>
        <div>
          <h1>This is one thing</h1>
          <article key="a">
            <h1>{id}</h1>
            <p>{email}</p>
          </article>
        </div>
      </div>
    );
  }
}

export default withStyles(s)(OneUser);
```

I just had to modify the `databaseGetUser` query to search by `id` instead by `email`.

I'm pretty sure that this is not the best way. Any advice?

**Comment by nikitong** [comment]
@langpavel I don't know If I get your answer correctly. I just managed to retrieve the parameter on the url doing this in `index.js`:

Lets say I have this route for a component oneUser:
 ```
    {
      path: '/oneuser/:id',
      load: () => import(/* webpackChunkName: 'oneUser' */ './oneUser'),
    },
```

Then in the component, in `index.js`:
```
import React from 'react';
import OneUser from './OneUser';
import oneUserQuery from './OneUser.graphql';
import Layout from '../../components/Layout';

async function action({ client }, context) {
  const data = await client.query({
    query: oneUserQuery,
    variables: { id: context.id },
  });
  return {
    title: 'React Starter Kit',
    chunks: ['oneUser'],
    component: (
      <Layout>
        <OneUser dataForComponent={data} />
      </Layout>
    ),
  };
}

export default action;
```
The query in `OneUser.graphql` will be:
```
query OneUser($id: Int) {
  databaseGetUser(id: $id) {
    id
    email
  }
}
```
And in `oneUser.js`:

```
import React from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './OneUser.css';

class OneUser extends React.Component {
  render() {
    const { id, email } = this.props.dataForComponent.data.databaseGetUser;

    return (
      <div className={s.root}>
        <div>
          <h1>This is one thing</h1>
          <article key="a">
            <h1>{id}</h1>
            <p>{email}</p>
          </article>
        </div>
      </div>
    );
  }
}

export default withStyles(s)(OneUser);
```

I just had to modify the `databaseGetUser` query to search by `id` instead by `email`.

I'm pretty sure that this is not the best way. Any advice?

**Comment by langpavel** [comment]
Ughh `this.props.dataForComponent.data.databaseGetUser` souds really crazy.
You can use something like `this.props.user` in component, go for it! :slightly_smiling_face:
It's real and you can unlock new level, please keep discovering :slightly_smiling_face:
