### ISSUE TITLE
Strategy for multilingual site

### ISSUE THREAD

**Issue by nikitong** [kriasoft/react-starter-kit#1592]
Hi all, 

Playing with RSK. I was wondering about a good strategy for a multilingual site. Is there any implementation in RSK? Or is there any common package used for this task?

EDIT: I see that `feature/react-intl` has language support. It works with apollo, which I try to avoid: can anyone give me any idea on how to get rid of Apollo there, or translate this language support implementation into `feature/redux`?

**Comment by langpavel** [comment]
Before the Apollo feature was introduced there was implementation purely on redux. See first commits of feature/react in taking PR

**Comment by nikitong** [comment]
Thanks! I'm checking it. I'm getting used to Apollo, is more complex but now I understand that it have some benefits, like the cache.

Anyway, doesn't matter the branch used, I'm facing the problem of passing params in url defined by the router to the React component: [https://github.com/kriasoft/react-starter-kit/issues/1591#issuecomment-377796783](https://github.com/kriasoft/react-starter-kit/issues/1591#issuecomment-377796783). There is an example for retrieving a list of items —the react news—, but not with a detail view, which would be useful!

**Comment by langpavel** [comment]
https://github.com/kriasoft/react-starter-kit/blob/master/docs/recipes/how-to-implement-routing.md

**Comment by langpavel** [comment]
Please, reopen if you will end in trouble.
