### ISSUE TITLE
How to update document title?

### ISSUE THREAD

**Issue by mxmtsk** [kriasoft/react-starter-kit#1593]
How would I go about updating the title of a page, especially for dynamically loaded things like a blog post.

My route:
```Javascript
  return {
    title: 'Lorem ipsum',
    component: (
      <Layout>
        <Post slug={slug} /> // the data get's loaded here so I need to set the document title there
      </Layout>
    ),
  };
```

**Comment by frenzzy** [comment]
1. Load data before rendering the page
```js
async function action(context) {
  const data = await fetch(`/api/post/${context.params.id}`)
  return {
    title: data.title,
    component: <Layout><Post {...data} /></Layout>,
  };
}
```
2. Update title manually in your component
```js
class Post extends React.Component {
  componentDidMount() {
    fetch(`/api/post/${this.props.id}`).then(data => {
      document.title = data.title;
    })
  }
}
```

**Comment by mxmtsk** [comment]
I work with [react-apollo](https://github.com/apollographql/react-apollo) to load my data, which happens in the component. 2nd option won't work for server side rendering. I guess I should switch to a different approach like helmet then right?

**Comment by frenzzy** [comment]
`componentDidMount` is executed on client-side only, so it is safe to update `document.title` there.

Also you might be interesting how this stuff works in https://github.com/kriasoft/react-firebase-starter with Relay.
