### ISSUE TITLE
babel-node: not found

### ISSUE THREAD

**Issue by lukemarsh** [kriasoft/react-starter-kit#1596]
When I'm running docker build I'm getting the error "babel-node: not found".

here's my DockerFile:

`FROM node:latest

ENV APP_HOME /myapp

ARG PRISMIC_API_ENDPOINT
ENV PRISMIC_API_ENDPOINT ${PRISMIC_API_ENDPOINT}
ARG PRISMIC_API_TOKEN
ENV PRISMIC_API_TOKEN ${PRISMIC_API_TOKEN}
ARG STRIPE_PUBLISHABLE_KEY
ENV STRIPE_PUBLISHABLE_KEY ${STRIPE_PUBLISHABLE_KEY}
ENV NODE_ENV production

RUN mkdir $APP_HOME

WORKDIR $APP_HOME

ADD . $APP_HOME/

WORKDIR $APP_HOME/

RUN yarn install --production --no-progress

RUN yarn build:ssr --release
`

The build script i'm using is: `"build:ssr": "babel-node universal/tools/run build"`

Question is: How to you guys use babel-node when running the build?

**Comment by jorrit** [comment]
babel-node is only installed in development builds and you are explicitly installing only production dependencies. Remove `--production`.

**Comment by lukemarsh** [comment]
Thanks for your reply but the Dockerfile in this repo is using —production

**Comment by jorrit** [comment]
This is true, but that Dockerfile has a different purpose. In that case, the actual building is done outside docker (notice that the repository Dockerfile has no reference to yarn build). You are building inside docker. Big difference.

**Comment by lukemarsh** [comment]
@jorrit Thank you! I understand the issue now :)
