### ISSUE TITLE
Where did UglifyJS go in Webpack Config?

### ISSUE THREAD

**Issue by tim-soft** [kriasoft/react-starter-kit#1597]
Minification for production seems to be missing from the webpack config?

**Comment by jorrit** [comment]
I believe it is automatically enabled in production mode, see https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a

**Comment by tim-soft** [comment]
I see, the devil is in the details
>Setting optimization.minimizer overrides the defaults provided by webpack, so make sure to also specify a JS minimizer:

So if you use _anything_ in optimization it will cancel out the built-in js optimization

**Comment by jorrit** [comment]
I think, based on the text, that setting `optimization.minimize.anything` overrides the defaults, not `optimization.anything`.

**Comment by tim-soft** [comment]
I use a css minimizer for some extracted styles, which meant the built in js optimization wasn't happening until I explicitly added uglifyJS to webpack.optimization

**Comment by langpavel** [comment]
IMHO I think that webpack will refuse to do anything with this, but RSK can add explicit config which will solve this. Instead of focusing on webpack where others opened many similar issues and may be PRs I will welcome patch to RSK

**Comment by tim-soft** [comment]
We can specifically add an uglifyJS config that is more aggressive than the default

**Comment by langpavel** [comment]
@tim-soft Sure, but marking diversities from default webpack preset by comments

**Comment by tim-soft** [comment]
Totally. Webpack v4 brings in all kinds of new suprises
