### ISSUE TITLE
Will you be implementing react-router?

### ISSUE THREAD

**Issue by mattiasewers** [kriasoft/react-starter-kit#160]
Seems like the obvious thing to do.

**Comment by cmnstmntmn** [comment]
:+1:

**Comment by koistya** [comment]
Guys, maybe it's better to have a simplified version of a router instead? Because not everyone is using react-router, and in many cases it might be an overkill to have it in the mix.

Here is an example of a basic routing without using any 3rd party libraries:

[![image](https://cloud.githubusercontent.com/assets/197134/8484352/e43742ae-20ff-11e5-99aa-7274f2b9a2ba.png)](https://twitter.com/koistya/status/609762956646219776)

https://twitter.com/koistya/status/609762956646219776

**Comment by devnomad** [comment]
I would find *react-router* more appealing as it's the go to solution at the moment for routing with React. I also get your position about the overkill (considering this is a starter kit), but a custom implementation would add more things to maintain ;)

Maybe https://github.com/gaearon/flux-react-router-example could serve as example/inspiration?

**Comment by sasajib** [comment]
I also think react-router will be a top notch addition, in this great project. We can then, maintain one router file for both server side and client side rendering. Keep up the good work.

**Comment by gonsfx** [comment]
I'd love to see react-router included!

**Comment by korczis** [comment]
:+1:

**Comment by zotterb** [comment]
:+1:

**Comment by Aluxian** [comment]
+1 for React router

Though, since this kit is so popular, isn't there anyone who already added react-router in their fork so we can take a look?

**Comment by MauriSalazar** [comment]
+1

**Comment by tizmagik** [comment]
+1

**Comment by shankarsridhar** [comment]
please include react router :+1:

**Comment by Aluxian** [comment]
I implemented react-router myself, but I made massive changes to the kit. I also added immutablejs, fluxible, webpack dev server, react hot reload and a few others. It's right [here](https://github.com/FOUfashion/frontend) if you'd like to take a look.

**Comment by thenikso** [comment]
I've tried to use react-router myself but (being new to this world) changing route via link does not render the expected component (while reloading does). So I guess I'm missing something in the "should render" business

**Comment by muneef** [comment]
+1

**Comment by jul-** [comment]
+1

**Comment by ArsalanDotMe** [comment]
+1. Is there a working guide/fork for this currently?

**Comment by luankefei** [comment]
+1

**Comment by Bogdaan** [comment]
+1 react-router

**Comment by lastcoolnameleft** [comment]
Yarr!  +1

**Comment by FakhruddinAbdi** [comment]
+1

**Comment by Bogdaan** [comment]
@ArsalanDotMe  
Working fork (4.1+ branch, no graphql) - https://github.com/Bogdaan/react-auth-kit
( better to use the latest version of the RSK )

link #422
link #345
link #20
link #70

**Comment by koistya** [comment]
Closing in favor of #20. See https://github.com/kriasoft/react-starter-kit/issues/20#issuecomment-207592082
