### ISSUE TITLE
Pre-compiled source code ( pre-minified ) can be seen on Chrome Sources

### ISSUE THREAD

**Issue by gijoncheng** [kriasoft/react-starter-kit#1600]
So I have tried to use `yarn run build -- --release` to build my app on my EC2 instance (Ubuntu) using Nginx web server , while I ran `node server.js` I know it's running on my server and I can browse the page from my domain, but I can also inspect all the source code that are unminimized (from my server root path), I inspected using Chrome.

![screen shot 2018-04-13 at 11 56 27 am](https://user-images.githubusercontent.com/13028235/38753406-1b85caa8-3f13-11e8-980e-0a9ffd371d4f.png)

I supposed this is a release version, shouldn't all js source code have been optimized and minimized after running the `build` command?

**Comment by gijoncheng** [comment]
[https://github.com/kriasoft/react-starter-kit/issues/1415] answered my question.

**Comment by hackhat** [comment]
You can use `GENERATE_SOURCEMAP` environment variable. Not sure why this issue has been closed without a solution, but here is a way.

In the docs of react-starter:

Variable | Development | Production | Usage
:--- | :---: | :---: | :---
BROWSER | :white_check_mark: | :x: | By default, Create React App will open the default system browser, favoring Chrome on macOS. Specify a [browser](https://github.com/sindresorhus/opn#app) to override this behavior, or set it to `none` to disable it completely. If you need to customize the way the browser is launched, you can specify a node script instead. Any arguments passed to `npm start` will also be passed to this script, and the url where your app is served will be the last argument. Your script's file name must have the `.js` extension.
HOST | :white_check_mark: | :x: | By default, the development web server binds to `localhost`. You may use this variable to specify a different host.
PORT | :white_check_mark: | :x: | By default, the development web server will attempt to listen on port 3000 or prompt you to attempt the next available port. You may use this variable to specify a different port.
HTTPS | :white_check_mark: | :x: | When set to `true`, Create React App will run the development server in `https` mode.
PUBLIC_URL | :x: | :white_check_mark: | Create React App assumes your application is hosted at the serving web server's root or a subpath as specified in [`package.json` (`homepage`)](#building-for-relative-paths). Normally, Create React App ignores the hostname. You may use this variable to force assets to be referenced verbatim to the url you provide (hostname included). This may be particularly useful when using a CDN to host your application.
CI | :large_orange_diamond: | :white_check_mark: | When set to `true`, Create React App treats warnings as failures in the build. It also makes the test runner non-watching. Most CIs set this flag by default.
REACT_EDITOR | :white_check_mark: | :x: | When an app crashes in development, you will see an error overlay with clickable stack trace. When you click on it, Create React App will try to determine the editor you are using based on currently running processes, and open the relevant source file. You can [send a pull request to detect your editor of choice](https://github.com/facebookincubator/create-react-app/issues/2636). Setting this environment variable overrides the automatic detection. If you do it, make sure your systems [PATH](https://en.wikipedia.org/wiki/PATH_(variable)) environment variable points to your editor’s bin folder.
CHOKIDAR_USEPOLLING | :white_check_mark: | :x: | When set to `true`, the watcher runs in polling mode, as necessary inside a VM. Use this option if `npm start` isn't detecting changes.
GENERATE_SOURCEMAP | :x: | :white_check_mark: | When set to `false`, source maps are not generated for a production build. This solves OOM issues on some smaller machines.
