### ISSUE TITLE
npm start not running - code ELIFECYCLE

### ISSUE THREAD

**Issue by David-McD** [kriasoft/react-starter-kit#1602]
**From debug log:**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.8.0
3 info using node@v6.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 info lifecycle @~start: @
7 verbose lifecycle @~start: unsafe-perm in lifecycle true
8 verbose lifecycle @~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/david/Documents/A/AVM/UI/sb-admin-react/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @~start: CWD: /home/david/Documents/A/AVM/UI/sb-admin-react
10 silly lifecycle @~start: Args: [ '-c', 'babel-node tools/run start' ]
11 silly lifecycle @~start: Returned: code: 1  signal: null
12 info lifecycle @~start: Failed to exec start script
13 verbose stack Error: @ start: `babel-node tools/run start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid @
15 verbose cwd /home/david/Documents/A/AVM/UI/sb-admin-react
16 verbose Linux 4.13.0-38-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v6.11.4
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ start: `babel-node tools/run start`
22 error Exit status 1
23 error Failed at the @ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**From command line:**
npm start

> @ start /home/david/Documents/A/AVM/UI/sb-admin-react
> babel-node tools/run start

/home/david/Documents/A/AVM/UI/sb-admin-react/node_modules/webpack/lib/BannerPlugin.js:19
			throw new Error("BannerPlugin only takes one argument (pass an options object)");
			^

Error: BannerPlugin only takes one argument (pass an options object)
    at new BannerPlugin (/home/david/Documents/A/AVM/UI/sb-admin-react/node_modules/webpack/lib/BannerPlugin.js:19:10)
    at Object.<anonymous> (/home/david/Documents/A/AVM/UI/sb-admin-react/tools/webpack.config.js:287:5)
    at Module._compile (module.js:570:32)
    at loader (/home/david/Documents/A/AVM/UI/sb-admin-react/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/david/Documents/A/AVM/UI/sb-admin-react/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2018-04-18T03_31_43_714Z-debug.log

**Comment by Yashwanthv21** [comment]
Did you solve this problem ??

**Comment by ulani** [comment]
@David-McD   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
