### ISSUE TITLE
defer="defer" attribute gets converted to defer="" in html source

### ISSUE THREAD

**Issue by chughgaurav** [kriasoft/react-starter-kit#1605]
If you add attribute defer="defer" to script tags in components/Html.js
and check the page source, it always gets converted to defer=""
the same is happening for async="async" or defer="true"
however, if i add any custom attribute like test="test", it works fine
could someone, please help point me point in the right direction ?

**Comment by frenzzy** [comment]
React generates XML-compatible markup, see https://github.com/facebook/react/pull/2842
All of these versions are valid: `defer`, `defer=""` and `defer="defer"`.
