### ISSUE TITLE
node debugging __DEV__ is not defined

### ISSUE THREAD

**Issue by goldylucks** [kriasoft/react-starter-kit#1617]
I'm trying to debug through VScode, but since `__DEV__` is created by webpack, it's undefined in debug mode so I'm getting this error.

Is there a way around it?

Should I attach the debugger to some `localhost:SOME_PORT` instead of the server source file?

I'm running the following:
`$ babel-node --inspect --inspect-brk ./src/server.js`

And my `launch.json` inside `.vscode` is:
```
    {
      "type": "node",
      "request": "attach",
      "name": "Node Attach",
      "sourceMaps": true,
      "port": 9229,
      "protocol": "inspector"
    }
```

**Comment by frenzzy** [comment]
For example you may use `--require ./setup.js` flag with the following content:
```js
global.__DEV__ = true
```

**Comment by goldylucks** [comment]
@frenzzy that seemed to work, thanks. now I have another issue of parsing `.css` files, specifically keyframes (see below)

It feels like the right approach would be to attach the node debugger to a bundle served by webpack. Thoughts?

<details>
<summary>Error log</summary>
```bash
➜  adamgoldman.me git:(master) ✗ npm run debug

> @ debug /home/goldy/apps/adamgoldman.me
> babel-node --inspect --inspect-brk ./src/server.js --require './test/nodeDebuggerSetup.js'

Debugger listening on ws://127.0.0.1:9229/1ee60f0f-4d6d-4c03-96b0-d1732ebc42b1
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
/home/goldy/apps/adamgoldman.me/src/components/LoadingSite/LoadingSite.css:1
(function (exports, require, module, __filename, __dirname) { @keyframes fadeIn {
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Module._extensions..js (module.js:654:10)
    at Object.newLoader [as .js] (/home/goldy/apps/adamgoldman.me/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/goldy/apps/adamgoldman.me/src/components/LoadingSite/LoadingSite.js:6:1)
    at Module._compile (module.js:643:30)
    at Module._compile (/home/goldy/apps/adamgoldman.me/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:654:10)
    at Object.newLoader [as .js] (/home/goldy/apps/adamgoldman.me/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:556:32)
Waiting for the debugger to disconnect...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ debug: `babel-node --inspect --inspect-brk ./src/server.js --require './test/nodeDebuggerSetup.js'`
npm ERR! Exit status 1
```
</details>

**Comment by goldylucks** [comment]
you mean compile once with a build or with `npm start`?

Hopefully it's the latter :)

**Comment by goldylucks** [comment]
when running `npm run start` and `node --inspect --inspect-brk build/server.js`m the breakpoints don't work, I get `breakpoint ignored because generated code not found (source map problem?)`

Any ideas?

**Comment by goldylucks** [comment]
I also tried the `.vscode` settings from [this example](https://github.com/kube/vscode-ts-webpack-node-debug-example), and got the same problem

**Comment by frenzzy** [comment]
If I remember correctly, `npm run start` does not write to file system, need to use:
1. `npm run build`
2. `node --inspect --inspect-brk build/server.js`

One more option is to addd inspect to start task to package.json
- `"start": "babel-node --inspect --inspect-brk tools/run start"`

(not sure if it will work)

**Comment by goldylucks** [comment]
Tried this with no luck:
`"start": "babel-node --inspect --inspect-brk tools/run start"`
I'm brand new to visual studio, so I'm not sure how to start approaching implementing/debugging this.

`npm run start` does write to the file system. If you delete the `build` folder, and make a change in the code, it gets regenerated.

The method you suggest might work if I set the breakpoints inside the compiled server code in `build/server.js`, which Is probably worse DX than just console log everything (i.e. not having the DX experience of vscode.

Since this starter kit is so popular, there must be many other s`vscode` users out there that will benefit from handling this.

Thoughts?

**Comment by ulani** [comment]
@goldylucks   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
