### ISSUE TITLE
README needs some update

### ISSUE THREAD

**Issue by jyotirmaybanerjee** [kriasoft/react-starter-kit#162]
I appreciate the effort. It will be of great help for many. But it seems the README.md is not up-to-date. Specially the section where you described how to build the application.

**Comment by michaelghinrichs** [comment]
running into this issue as well, i believe it has something to do with `gulpfile.js` being renamed to have `babel` in it.

**Comment by koistya** [comment]
You need to either update Gulp installed globally to v3.9+ or use npm scripts instead which use Gulp version installed locally in the project, e.g.

```shell
# Build the project
$ npm run build

# Build the project in release mode (optimized and minimized)
$ npm run build -- --release

# Built the project and launch a development server (borwser-sync)
$ npm run sync
```

For more info see `package.json/scripts`

**Comment by jyotirmaybanerjee** [comment]
That helped. Thanks.
