### ISSUE TITLE
what's the state of this project

### ISSUE THREAD

**Issue by imhazige** [kriasoft/react-starter-kit#1627]
Hi, All,

I like this project, and I am using this project for current product, but I did not see any update recently, the latest release is still at year 2016, is this project alive? or is there any other project is better than this one that make this project pending?

**Comment by rodeyseijkens** [comment]
The maintainers are not versioning it. It gets constantly updated. Just dont use the npm install or anything. Just checkout the latest version in the master branch. I get that versioning is nice but there isn’t really a roadmap or anything so it doesn’t really make sense too.

**Comment by frenzzy** [comment]
Also you may find some continuation of this boilerplate in [react-firebase-starter](https://github.com/kriasoft/react-firebase-starter).

**Comment by imhazige** [comment]
@rodeyseijkens Thank you.
@frenzzy  Thank you, but I don't like the idea binding to a service.
