### ISSUE TITLE
babel-node can't be executed directly... why?

### ISSUE THREAD

**Issue by adamchenwei** [kriasoft/react-starter-kit#1640]
I saw in the package.json there is a command under "start" as `babel-node tools/run start`
but when I run inside the project root `babel-node tools/run start` it won't work and says 

**-bash: babel-cli: command not found**

wonder why?

**Comment by jorrit** [comment]
When running a command from a `script` it automatically adds anything in `node_modules/.bin` to the PATH. When running the command yourself this obviously doesn't happen. You can use `npx` if you have a recent npm like this:

`npx babel-node tools/run start`

npx allows you to run commands installed locally in `node_modules/.bin`, among other things.

**Comment by piglovesyou** [comment]
@adamchenwei I think you should thank him.

**Comment by pcmourya** [comment]
@jorrit It is not working, still it is showing the same.
