### ISSUE TITLE
Multiple time API call issue 

### ISSUE THREAD

**Issue by nisargrthakkar** [kriasoft/react-starter-kit#1648]
We also find some wired behavior of starter kit when we tried to call API(3rd party URL) from starter kit call it will call 2 time, One form server side and one is from client time at time of loading. Any one has solution for this type of wired behavior and why this is happening with it?

**Comment by nisargrthakkar** [comment]
I just download a starter kit and run it and it will call API 2 time. I also tried with cached page on client side so not issue over there. Problem I found is server run and call API while making html(page) that page(html) goes to client side again that line of code will run so again API call aill be done on client side.

**Comment by rodeyseijkens** [comment]
Its not about caching in that sense of a way, your client side and server side don't communicate so you need to put it in a store and send that to client side then check if the page that is being fetched is already in the store or not.

**Comment by nisargrthakkar** [comment]
Ok yes got your point. Thank you so much :)

**Comment by nisargrthakkar** [comment]
For other that have query same, I had before.

You need to check in store if you are using redux then if there is data in your redux store or not. If not call for API. otherwise didn't call 

How its work?

When your code is rendering on server side there is no data on `store.getState().stateaName` this store state. So its will call API and when same code run on client site there is data on `store.getState().stateaName` so it will not go in if so API didn't call.

```
if (!_.has(store.getState().stateaName,'value')) {
  const data =  await store.dispatch(action('actionName'));
}
```
