### ISSUE TITLE
webpack.config.js customize key is undefined after merge of react-intl

### ISSUE THREAD

**Issue by mrgswift** [kriasoft/react-starter-kit#1656]
Hello,

After merging react-intl feature branch with my project, running yarn install, and doing the steps noted in [Issue 1654](https://github.com/kriasoft/react-starter-kit/issues/1654) to fix the preset-stage-2 deprecation in babel v7.0.0-beta.55 (works fine before the merge), I got this error when running yarn start to start the server process:

```
Entrypoint server = server.js
[17:39:23] Finished 'server' compilation after 11857 ms
tools/webpack.config.js:272
      if (key.toLowerCase().endsWith('.map')) return false;
              ^

TypeError: Cannot read property 'toLowerCase' of undefined
```

To see if I could fix this, I changed lines 352-354 in tools/webpack.config.js to:
```
        if (typeof key !== 'undefined') {
          // You can prevent adding items to the manifest by returning false.
          if (key.toLowerCase().endsWith('.map')) return false;
          return {key, value};
        }
```

This stopped the error and I was able to browse to the react-starter-kit page successfully on http://localhost:3000 and browsersync at http://localhost:3001.  

Everything seems to work fine thus far, but I just wanted to verify that something else I haven't noticed yet is broken since the key argument in the customize function is undefined during the start process.

Thanks!

**Comment by ahashem** [comment]
Changing it as below worked for me:

```
      customize: ({ key, value }) => {
        // You can prevent adding items to the manifest by returning false.
        if (key.toLowerCase().endsWith('.map')) return false;
        return { key, value };
      },
```

**Comment by huangyanxiong01** [comment]
me too

**Comment by ulani** [comment]
@mrgswift   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
