### ISSUE TITLE
webpack-hot-middleware's client requires EventSource to work. 

### ISSUE THREAD

**Issue by damiangreen** [kriasoft/react-starter-kit#1657]
In Edge I get this console error:
"webpack-hot-middleware's client requires EventSource to work."

``` webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools```
```SCRIPT445: SCRIPT445: Object doesn't support this action``` 

in client.js (94,1)

I tried downgrading querystring to 5.1.1 as per [this](https://github.com/kriasoft/react-starter-kit/issues/1655) issue

Are there instructions / polyfill already included I can enable?

**Comment by askurat** [comment]
I am also having this same issue. Did you ever find a solution?

**Comment by damiangreen** [comment]
not yet. I've tried a few polyfills, I'll need to revisit this soon when I do more IE11 testing for our initial release

**Comment by berikiushi** [comment]
I noticed that this error only occurs in development mode

**Comment by frenzzy** [comment]
Yes, this is relevant in development mode only. How to fix:
1. Run `yarn add --dev event-source-polyfill`
2. Add `import 'event-source-polyfill'` as a first line to [`tools/lib/webpackHotDevClient.js`](https://github.com/kriasoft/react-starter-kit/blob/867ebe58673ac32f87af6843e18fde06671771eb/tools/lib/webpackHotDevClient.js#L9)
3. Done

**Comment by askurat** [comment]
frenzzy, thanks for the update. I have done what you said but now receive:
`SCRIPT438: Object doesn't support property or method 'finally'`.

It shows this error is coming from eventsource.js.

**Comment by torontodeveloper** [comment]
Hi, We are using reacct-starter-kit for server side rendering and now I hit the same issue on IE11

webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools

App not rendering and displaying blank white screen

Any help appreciated

**Comment by ulani** [comment]
@damiangreen   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
