### ISSUE TITLE
preload data in server

### ISSUE THREAD

**Issue by Levi-ackerman** [kriasoft/react-starter-kit#1659]
Hello guys,
Thank for amazing starter. I use this starter kit in my project.
My current situation : 
- Login with facebook => get token => set token to cookie
- When reload page => get cookie from server => dispatch an action (such as `setToken` action)

It work. But I wonder how can I preload some data, for example when I get cookie from server, I want to make an api to get user info after render html page. How can I do that ?

Thank you and sr about my english.

**Comment by piglovesyou** [comment]
HI. I'm afraid but not sure if I can get what you mean. User info is in your cookie with `id_token` key. You can use it by `req.user` in Express middlwares. I hope it helps, please reopen it if it didn't.
