### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by villesau** [kriasoft/react-starter-kit#1663]
Hi,

Looks like there's only data models but I couldn't find Sequelize migrations from the repo. How should they be run with react-starter-kit? The folder structure seems to vary from what Sequelize suggests, and sequelize-cli init produces different result. Is that intentional or should it be changed?

Ref: http://docs.sequelizejs.com/manual/tutorial/migrations.html

**Comment by ricardomoura** [comment]
this repo is intended to work with another external api like(https://github.com/kriasoft/nodejs-api-starter) but you can check this out: https://github.com/kriasoft/react-starter-kit/issues/1568

**Comment by piglovesyou** [comment]
Duplicated to #1568 where we can keep discussing.
