### ISSUE TITLE
External Graphql API

### ISSUE THREAD

**Issue by lionls** [kriasoft/react-starter-kit#1670]
Hi, I would like to use an external GraphQL Server as the API. How can I specify the URL and Port in the config file?

Thank in advance

**Comment by piglovesyou** [comment]
@lionls I would suggest you to see [here](https://github.com/kriasoft/react-starter-kit/blob/d0c3341248f60867978e2c35c5486405280bb957/src/config.js#L30-L32). Please make sure browser clients can access the external GraphQL API. Please reopen it if it didn't help you.
