### ISSUE TITLE
How to create two separate clients

### ISSUE THREAD

**Issue by ray-wu** [kriasoft/react-starter-kit#1674]
I'd like to create TWO separate client, one for frontend, another one for dashboard (maybe admin use only), and both of them will communicate with server through graphQL,  is there any way to do that?

Or is there any better solutions ?

Any suggestions are appreciated!

**Comment by inomn** [comment]
What difference will be between this clients?
You can make, for example, different routs, with different layouts and divide their bundles

**Comment by piglovesyou** [comment]
The advice from @inomn does make sense. Please reopen it if it didn't.
