### ISSUE TITLE
Support old devices

### ISSUE THREAD

**Issue by blz-ea** [kriasoft/react-starter-kit#1679]
Hi,
I've built an app with **react-starter-kit** that works perfectly fine with modern browsers. But I can't make it work on old **iOS (9.5)** device and old un-updated Android devices **(Chrome 44)** 
(unfortunately updating those devices is not an option)

![image](https://user-images.githubusercontent.com/19339605/46452101-f02f7100-c767-11e8-88f1-a276315886b1.png)

As far as I'm understanding, those browsers does not support arrow functions and destructuring assignment (and any other ES6 cool features).

Is there any way to make babel trinspile code that has been imported from **node_modules** to ES2015 ?

**Comment by blz-ea** [comment]
Thank you very much @frenzzy 
You saved my day

**Comment by MaxInMoon** [comment]
@blz-ea can you provide your modifications please?
