### ISSUE TITLE
i want to access state variable of one component in another component i.e. from offline.js to login.js

### ISSUE THREAD

**Issue by rajkishoreandia** [kriasoft/react-starter-kit#1680]
offline.js
---------
import React, { PureComponent } from 'react';
import { View, Text, NetInfo, Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

function MiniOfflineSign() {
  return (
    <View style={styles.offlineContainer}>
      <Text style={styles.offlineText}>No Internet Connection</Text>
    </View>
  );
}

class OfflineNotice extends PureComponent {
  state = {
    isConnected: false
  };

  componentDidMount() {
    NetInfo.isConnected.addEventListener('connectionChange', this.handleConnectivityChange);
  }

  componentWillUnmount() {
    NetInfo.isConnected.removeEventListener('connectionChange', this.handleConnectivityChange);
  }

  handleConnectivityChange = isConnected => {
    if (isConnected) {
      this.setState({ isConnected });
    } else {
      this.setState({ isConnected });
    }
  };

  render() {
    if (!this.state.isConnected) {
      return <MiniOfflineSign />;
    }
    return null;
  }
}

login.js
---------
import OfflineNotice from '../components/OfflineNotice';

export default class Login extends Component{
  constructor(props) {
    super(props);
    this.state = {
      userName: '',
      Password:'',
      showMe:true,
    };
  console.log("here i want offline.js state variable is connected")
    
  }
componentDidMount() {
   console.log("here i want offline.js state variable is connected")
    

}

componentWillUnmount() {
  // this.backHandler.remove();
}

**Comment by inomn** [comment]
Looks like you talking about Redux (https://github.com/reduxjs/redux). 
Try to use feature/redux branch 
https://github.com/kriasoft/react-starter-kit/tree/feature/redux

**Comment by piglovesyou** [comment]
@rajkishoreandia Did the advice from @inomn works? Please reopen it if it didn't.
