### ISSUE TITLE
SSL Expired for reactstarter.com

### ISSUE THREAD

**Issue by dwdraju** [kriasoft/react-starter-kit#1681]
Renew ssl cert for https://reactstarter.com/

**Comment by AndreyVavilov** [comment]
Any news? Don't you care?

**Comment by gianpaj** [comment]
> This server could not prove that it is reactstarter.com; its security certificate expired 167 days ago.

**Comment by piglovesyou** [comment]
Seems that they updated it with Let's Encrypt.
