### ISSUE TITLE
FOUC while using JSS with RSK

### ISSUE THREAD

**Issue by code2end** [kriasoft/react-starter-kit#1685]
Hello , I'm just having trouble setting up material-ui (which uses JSS) to set up with RSK, I get a flash of unstyled contents before the page loads. It may be a problem with webpack as it is earlier configured for CSS Modules not for JSS. Could also be related to dynamic loading of routes via universal router ? 

Is there any guide for this "JSS with RSK"?

I'm new to react and having trouble resolving this, if anyone can just put me in right direction.

**Comment by mmarkelov** [comment]
@code2end you can check my [fork](https://github.com/mmarkelov/react-starter-kit) where I replaced **isomorphic-style-loader** with **styled-components** may be it will helpful for you

**Comment by code2end** [comment]
@mmarkelov thanks I will check it out.

**Comment by Arnaud-codeur** [comment]
hello I have the same problem how to solve it I did not understand very well?
