### ISSUE TITLE
How to use Apollo Client (Graphql API) in redux actions?

### ISSUE THREAD

**Issue by gijonc** [kriasoft/react-starter-kit#1686]
I want to wrap all my API calls in redux so that I can dispatch these api functions wherever I use inside react components. As I know RSK pass Apollo client as a context property of the component, but how can use it in my redux actions?

**Comment by albertsyh** [comment]
@gijoncheng 
As the Apollo client is saved as 'client' within the context variable, and redux-thunk middleware enabled within the redux store, you may call your GraphQL queries in the following way.

```javascript
function foo(bar) {
  return async (dispatch, getState, { client }) => {
    const request = await client.query({
      query: someQuery,
      variables: {
        input: bar
      }
    });
    const result = await request;
    dispatch({
      type: DEFAULT_ACTION,
      payload: result
    })
  }
}
```

**Comment by piotrdelikat** [comment]
To be able to use Apollo client in redux-thunk actions, pass is as an extra argument to thunk while creating the store.

```
export const client = new ApolloClient({
  link: createHttpLink({ uri: `${apiUrl}/graphql` })
  ),
  cache: new InMemoryCache()
});
const store = createStore(
  rootReducer,
  initialState,
  applyMiddleware(thunk.withExtraArgument(client)),
  )
);
```

Then you will be able to use it in your actions easly.

```
export const getCartAction = () => (
  dispatch,
  getState,
  client
) => {
  dispatch({
    type: 'GET_CART_ATTEMPT'
  });
  client
    .query({
      query: GET_CARD,
      fetchPolicy: 'no-cache'
    })
    .then(res => {
      dispatch({
        type: 'GET_CART_SUCCESS',
        payload: res.data
        }
      });
    });
};
```

**Comment by ulani** [comment]
@gijonc   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
