### ISSUE TITLE
Gulp error with unmodified template

### ISSUE THREAD

**Issue by matt404** [kriasoft/react-starter-kit#169]
When I follow the instructions in the Readme, I get an error when trying to run 'gulp build'.  Please fix or update the readme to be accurate.

**Comment by bado22** [comment]
Would be helpful if you specified the error message that you are getting, but if you are getting a `no gulpfile found` error like I was, updating gulp by using the command `npm install -g gulp` worked for me.

**Comment by matt404** [comment]
Thank you that solved my issue, I had tried `npm install -g gulp` already but not from within the template directory.  Appreciate the help!

**Comment by bado22** [comment]
@matt404 glad it helped!
