### ISSUE TITLE
New plugins cannot be resolved

### ISSUE THREAD

**Issue by CacheMoneyPlaya** [kriasoft/react-starter-kit#1692]
I am trying to add some new plugins but whenever I try to import them I and then build the project I get:

![44b85975eb4303d5cbc7b8776feb8f7c](https://user-images.githubusercontent.com/39480577/49733730-33332680-fc7a-11e8-8f4a-8da9c7438d63.png)

Everything is imported properly and this issue is present on other peoples computers who are also working on it with me.

**Comment by mmarkelov** [comment]
@ThePeelerShredder Seems like **other peoples** just don't install packages, when your **package.json** was changed

**Comment by ThePeelerShredder** [comment]
> @ThePeelerShredder Seems like **other peoples** just don't install packages, when your **package.json** was changed

Has anyone come across any reason why this is the case?
