### ISSUE TITLE
Have to restart dev server each time i make change inside server code

### ISSUE THREAD

**Issue by FinnFrotscher** [kriasoft/react-starter-kit#1700]
i am on branch [apollo pure](https://github.com/kriasoft/react-starter-kit/tree/feature/apollo-pure).

when editing inside client code, hot reload works fine.
when editing inside server code, then no hot reload and the only way to persist the changes is to recompile the whole project.

NOTE: i will track the progress of my solution here, if i find any myself. if anyone has a tip on where to look, i am thankful for any help.

**Comment by FinnFrotscher** [comment]
So far i have understood this much:
(babel-node)[https://babeljs.io/docs/en/babel-node]  loads `tools/run.js`, which in turn runs `start.js`, which starts the webpack compilation (and all the other magic). on line 91 of that file, it says ` // Configure server-side hot module replacement` which I take to assume that my expected behavior SHOULD work.
keep you updated.

**Comment by piglovesyou** [comment]
@FinnFrotscher Thank you for using `feature/apollo-pure`. I wish I could get notified from this thread sooner.

At https://github.com/kriasoft/react-starter-kit/tree/27035c756d1e5effceeaf88170daf4e40f183d8f  I confirmed server-side hot-module-replacement (HMR) works properly. But I'm not 100% sure the branch always makes HMR work correctly.

The codebase was drastically changed... Now the branch is implemented in TypeScript.
