### ISSUE TITLE
The download buffer file in node with problems.(node-xlsx)

### ISSUE THREAD

**Issue by luffyZh** [kriasoft/react-starter-kit#1701]
In my project , the browser can download the 'xx.xlsx' file with 'node-xlsx', but the file can't be open. And the current version of React-Starter-Kit has the same problem. 
Even the simplest code to build the file.
```
import xlsx from 'node-xlsx';
...
 const filename = `xxxx_${startDate}_${endDate}.xlsx`;
 const buffer = excel.build([{ name: 'sheet1', data: [['date', 'showNum']].concat([]) }]);
...
 res.status(200).attachment(filename).send(buffer);
```
Open the file, it will show the file format is wrong.

```
// The same code
const buffer = xlsx.build([{ name: 'sheet1', data: [['date', 'showNum']].concat([]) }]);
res.status(200).attachment('def.xlsx').send(buffer);
```
### Another old react-starter-kit  project  is right:
<img width="648" alt="default" src="https://user-images.githubusercontent.com/17840558/50943498-ac1add80-14c7-11e9-8a04-340e02365794.png">

<img width="645" alt="default" src="https://user-images.githubusercontent.com/17840558/50943431-6a8a3280-14c7-11e9-8cc7-4b5cbf14f515.png">

### But the new project is wrong:(includes the current version)
<img width="648" alt="default" src="https://user-images.githubusercontent.com/17840558/50943541-da98b880-14c7-11e9-8ba6-994d19c652a6.png">
<img width="645" alt="default" src="https://user-images.githubusercontent.com/17840558/50943551-e5ebe400-14c7-11e9-9c53-0ef4c52bdcc2.png">

**Comment by luffyZh** [comment]
@mmarkelov Thank you very much for your answer and it inspired me. But I want to download the file directly to the browser instead of downloading it locally first. 
#### The solution of mine
```
 res.writeHead(200, {
    'Content-Type': 'application/octet-stream',
    'Content-Disposition': 'attachment; filename=${filename}'
  });
  const bufferStream = stream.PassThrough();
  bufferStream.end(buffer);
  bufferStream.pipe(res);
```
And it works, very thank you finally~

**Comment by langpavel** [comment]
This code
```js
  const bufferStream = stream.PassThrough();
  bufferStream.end(buffer);
  bufferStream.pipe(res);
```
is effectively equivalent to `res.write(buffer)`

**Comment by luffyZh** [comment]
@langpavel Thanks, I tried it using the code `res.end(buffer);` or `res.write(buffer);`, but it don't works. So i still using the old code with `stream`.

And I want to know why this problem happens, the old `React-Starter-Kit`(about one year ago) is works with `res.end(buffer)`.

**Comment by langpavel** [comment]
@luffyZh weird. Thanks for feedback
