### ISSUE TITLE
error @babel/core@7.0.0-beta.51: The engine "node" is incompatible with this module. Expected version ">=6.9.0".

### ISSUE THREAD

**Issue by paolopan83** [kriasoft/react-starter-kit#1702]
In the README.md sais node 6.5.0 +, which apparently is not correct?

**Comment by paolopan83** [comment]
Version 6.11.5 actually works, should you update the doc?

**Comment by mmarkelov** [comment]
@paolopan83 yeah! I suppose this is incorrect info in **Readme** , cause **@babel/core@7.0.0-beta.51** expect node >=6.9.0

**Comment by minggas** [comment]
Can I make the change?

**Comment by piglovesyou** [comment]
@minggas Yes please by all means. Also be aware what Node version [the current `@babel/core` version](https://github.com/kriasoft/react-starter-kit/blob/64f7558bd2897cabe98fb30da2e63fe0ca9a37aa/package.json#L44) supports.

**Comment by minggas** [comment]
On they gh [this is the current @babel/core package.json](https://github.com/babel/babel/blob/master/packages/babel-core/package.json), here they are using `"node": ">=6.9.0"`

**Comment by piglovesyou** [comment]
Cool. You should see what Babel `7.0.0` uses actually, but looks like they didn't change it.

**Comment by minggas** [comment]
Yeah, I looked at the 7.0.0 version now and is `>=6.9.0`. I'll do the change on the readme right now.
