### ISSUE TITLE
unable to import antd css 

### ISSUE THREAD

**Issue by vamsi981** [kriasoft/react-starter-kit#1704]
I modified the webpack config to load antd.css and antd.less we are unable to load the .css or .less files 

below is my webpack config file what else do i need to change to load antd css
` import path from 'path';
import webpack from 'webpack';
import AssetsPlugin from 'assets-webpack-plugin';
import nodeExternals from 'webpack-node-externals';
import {
    BundleAnalyzerPlugin
} from 'webpack-bundle-analyzer';
import overrideRules from './lib/overrideRules';
import pkg from '../package.json';

const isDebug = !process.argv.includes('--release');
const isVerbose = process.argv.includes('--verbose');
const isAnalyze = process.argv.includes('--analyze') || process.argv.includes('--analyse');

const reScript = /\.jsx?$/;
const reStyle = /\.(css|less|scss|sss)$/;
const reImage = /\.(bmp|gif|jpe?g|png|svg)$/;
const staticAssetName = isDebug ? '[path][name].[ext]?[hash:8]' : '[hash:8].[ext]'; `

const config = {
    context: path.resolve(__dirname, '..'),
    devtool: 'source-map',
    output: {
        path: path.resolve(__dirname, '../build/public/assets'),
        publicPath: '/assets/',
        pathinfo: isVerbose,
        sourceMapFilename: '[file].map',
        filename: isDebug ? '[name].js' : '[name].[chunkhash:8].js',
        chunkFilename: isDebug ? '[name].chunk.js' : '[name].[chunkhash:8].chunk.js',
        devtoolModuleFilenameTemplate: info => path.resolve(info.absoluteResourcePath),
    },

    resolve: {
        modules: ['node_modules', 'src'],
    },
    module: {
        strictExportPresence: true,

        rules: [{
                test: reScript,
                include: path.resolve(__dirname, '../src'),
                loader: 'babel-loader',
                options: {
                    cacheDirectory: isDebug,

                    babelrc: false,
                    presets: [
                        ['env', {
                            targets: {
                                browsers: pkg.browserslist,
                                uglify: true,
                            },
                            modules: false,
                            useBuiltIns: false,
                            debug: false,
                        }],
                        'stage-2',
                        'react',
                        ...isDebug ? [] : ['react-optimize'],
                    ],
                    plugins: [
                        ...isDebug ? ['transform-react-jsx-source'] : [],
                        ...isDebug ? ['transform-react-jsx-self'] : [],
                    ],
                },
            },
///// ant Configuration

{
    test: /\.css$/,
    include: [/node_modules\/.*antd/],
    use: [
      {
        loader: 'style-loader',
      },
      {
        loader: 'css-loader',
      },
      {
        loader: 'postcss-loader',
        options: {
          config: {
            path: './tools/postcss.config.js',
          },
        },
      },
    ],
  },
// {
//     test: /\.less$/,
//     include: [/node_modules\/.*antd/],
//     use: [
//       {
//         loader: "style-loader" // creates style nodes from JS strings
//       }, {
//         loader: "css-loader" // translates CSS into CommonJS
//       }, {
//         loader: "less-loader", // compiles Less to CSS
//         options: {
//           modifyVars: themeVariables,
//         }
//       }
//     ],
//   },
/////
            {
                test: reStyle,
                exclude: [/node_modules\/.*antd/],
                rules: [{
                        issuer: {
                            not: [reStyle]
                        },
                        use: 'isomorphic-style-loader',
                    }, {
                        exclude: path.resolve(__dirname, '../src'),
                        loader: 'css-loader',
                        options: {
                            sourceMap: isDebug,
                            minimize: !isDebug,
                            discardComments: {
                                removeAll: true
                            },
                        },
                    },

                    {
                        include: path.resolve(__dirname, '../src'),
                        loader: 'css-loader',
                        options: {
                            importLoaders: 1,
                            sourceMap: isDebug,
                            modules: true,
                            localIdentName: isDebug ? '[name]-[local]-[hash:base64:5]' : '[hash:base64:5]',
                            minimize: !isDebug,
                            discardComments: {
                                removeAll: true
                            },
                        },
                    },

                    {
                        loader: 'postcss-loader',
                        options: {
                            config: {
                                path: './tools/postcss.config.js',
                            },
                        },
                    }
                ],
            },

            {
                test: reImage,
                oneOf: [{
                        issuer: reStyle,
                        oneOf: [{
                                test: /\.svg$/,
                                loader: 'svg-url-loader',
                                options: {
                                    name: staticAssetName,
                                    limit: 4096,
                                },
                            },

                            {
                                loader: 'url-loader',
                                options: {
                                    name: staticAssetName,
                                    limit: 4096,
                                },
                            },
                        ],
                    },

                    {
                        loader: 'file-loader',
                        options: {
                            name: staticAssetName,
                        },
                    },
                ],
            },

            {
                test: /\.txt$/,
                loader: 'raw-loader',
            }, {
                test: /\.html$/,
                loader: 'html-loader'
            }, {
                test: /\.md$/,
                loader: path.resolve(__dirname, './lib/markdown-loader.js'),
            },

            {
                exclude: [
                    reScript,
                    reStyle,
                    reImage,
                    /\.json$/,
                    /\.txt$/,
                    /\.md$/,
                ],
                loader: 'file-loader',
                options: {
                    name: staticAssetName,
                },
            },

            ...isDebug ? [] : [{
                test: path.resolve(__dirname, '../node_modules/react-deep-force-update/lib/index.js'),
                loader: 'null-loader',
            }, ],
        ],
    },

    bail: !isDebug,

    cache: isDebug,

    stats: {
        cached: isVerbose,
        cachedAssets: isVerbose,
        chunks: isVerbose,
        chunkModules: isVerbose,
        colors: true,
        hash: isVerbose,
        modules: isVerbose,
        reasons: isDebug,
        timings: true,
        version: isVerbose,
    },

    devtool: isDebug ? 'cheap-module-inline-source-map' : 'source-map',
};

var plugins = [];
plugins.push(new webpack.DefinePlugin({
            'process.env.NODE_ENV': isDebug ? '"development"' : '"production"',
            'process.env.BROWSER': true,
            __DEV__: isDebug,
        }));
plugins.push(new AssetsPlugin({
            path: path.resolve(__dirname, '../build'),
            filename: 'assets.json',
            prettyPrint: true,
        }));
plugins.push(new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: module => /node_modules/.test(module.resource),
            sourceMap: false
        }));
plugins.push(new webpack.optimize.ModuleConcatenationPlugin());
if(!isDebug)
    plugins.push(new webpack.optimize.UglifyJsPlugin({
                sourceMap: false,
                compress: {
                    screw_ie8: true,
                    warnings: isVerbose,
                    dead_code: true,
                    unused: true,
                    drop_debugger: true,
                    conditionals: true,
                    evaluate: true,
                    drop_console: true, // strips console statements
                    sequences: true,
                    booleans: true,
                },
                mangle: {
                    screw_ie8: true,
                },
                output: {
                    comments: false,
                    beautify: false,
                    screw_ie8: true,
                },
            }));
if(isAnalyze)
plugins.push(new BundleAnalyzerPlugin());
const clientConfig = {
    ...config,

    name: 'client',
    target: 'web',

    entry: {
        client: ['babel-polyfill', './src/client.js'],
    },

    plugins: plugins,

    node: {
        fs: 'empty',
        net: 'empty',
        tls: 'empty',
    },
};

const serverConfig = {
    ...config,

    name: 'server',
    target: 'node',

    entry: {
        server: ['babel-polyfill', './src/server.js'],
    },

    output: {
        ...config.output,
        path: path.resolve(__dirname, '../build'),
        filename: '[name].js',
        chunkFilename: 'chunks/[name].js',
        libraryTarget: 'commonjs2',
    },

    resolve: {
        ...config.resolve,
    },

    module: {
        ...config.module,

        rules: overrideRules(config.module.rules, (rule) => {
            if (rule.loader === 'babel-loader') {
                return {
                    ...rule,
                    options: {
                        ...rule.options,
                        presets: rule.options.presets.map(preset => (preset[0] !== 'env' ? preset : ['env', {
                            targets: {
                                node: pkg.engines.node.match(/(\d+\.?)+/)[0],
                            },
                            modules: false,
                            useBuiltIns: false,
                            debug: false,
                        }])),
                    },
                };
            }

            if (rule.loader === 'file-loader' || rule.loader === 'url-loader' || rule.loader === 'svg-url-loader') {
                return {
                    ...rule,
                    options: {
                        ...rule.options,
                        name: `public/assets/${rule.options.name}`,
                        publicPath: url => url.replace(/^public/, ''),
                    },
                };
            }

            return rule;
        }),
    },

    externals: [
        './assets.json',
        nodeExternals({
            whitelist: [
                reStyle,
                reImage,
            ],
        }),
    ],

    plugins: [........],

    node: {
        console: false,
        global: false,
        process: false,
        Buffer: false,
        __filename: false,
        __dirname: false,
    },
};

clientConfig.module.rules[0].options.plugins = [...clientConfig.module.rules[0].options.plugins];
clientConfig.module.rules[0].options.plugins.push(['import', { libraryName: 'antd', style: 'css' }]);

// clientConfig.module.rules[0].options.plugins = [...clientConfig.module.rules[0].options.plugins];
// clientConfig.module.rules[0].options.plugins.push(['import', { libraryName: 'antd', style: true }]);

export default [clientConfig, serverConfig];`

**Comment by mmarkelov** [comment]
@vamsi981 Duplicated in #1690 
And you can check this issue #1691 may be it help

**Comment by mmarkelov** [comment]
@vamsi981 I think you don't need any changes in your **webpack.config.js**. You can just do:
Your component with **antd**:
```javascript
import React from 'react';
// Import components from antd
import { ... } from 'antd';
// Import styles - whole styles of antd
import s from 'antd/dist/antd.min.css';
import withStyles from 'isomorphic-style-loader/lib/withStyles';

...

// Pass you style to withStyles function
export default withStyles(s)(Component);
```

**Comment by vamsi981** [comment]
@mmarkelov  Yeah I tried above also but no hope. below is the error which we are getting
`@font-face {
^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)`

**Comment by ACPK** [comment]
@vamsi981 - Have you seen this app? It might help with your Antd integration?

https://github.com/tim-soft/react-starter-kit-antd

**Comment by yihaozhadan** [comment]
I got the same issue. The antd CSS only works when SPA is loaded first time. If the page is refreshed, it throws error. I refer to https://github.com/tim-soft/react-starter-kit-antd and setup. But that git repo is old and doesn't work any more. I wonder if it is the server routing issue.

**Comment by piglovesyou** [comment]
@yihaozhadan Could you show me a minimum repository that reproduces it?

**Comment by yihaozhadan** [comment]
@piglovesyou Here is the my repository. https://github.com/yihaozhadan/Wisdom/tree/Wisdom. When the home page is loaded, the font color and size will change immediately. Click "Dashboard" you can see the CSS is loaded. But it throws error after refreshing page.

**Comment by piglovesyou** [comment]
I was able to reproduce. You wrote too much webpack.config so I couldn't patch it in my time. At least:

```jsx
if(canUseDOM && __DEV__) { require('components/antThemeLoader.less') }
```

The above is not what you have to do. isomorphic-style-loader can load external css on SSR. I suggest you to read how the original webpack.config distinguishes internal and external css.

**Comment by ulani** [comment]
@vamsi981   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
