### ISSUE TITLE
Using Nodejs clustering feature

### ISSUE THREAD

**Issue by hienhuynhtm** [kriasoft/react-starter-kit#1706]
Hi guys,

I'm a fan of this boilerplate. Nodejs provide us great Clustering feature, which allow us to speedup performance. Detail here: https://nodejs.org/api/cluster.html

Why we don't use this feature? Is it not suitable for our boilerplate?

Thanks.

**Comment by langpavel** [comment]
There is many ways how to scale up. This is only one of. As an example you may see https://stackoverflow.com/questions/34682035/cluster-and-fork-mode-difference-in-pm2

**Comment by hienhuynhtm** [comment]
@langpavel thank you so much
