### ISSUE TITLE
react-mdl 'TypeError: undefined is not an object (evaluating 'window.componentHandler.upgradeElements')

### ISSUE THREAD

**Issue by kevin-johar** [kriasoft/react-starter-kit#1709]
![screen shot 2019-01-27 at 11 48 30 pm](https://user-images.githubusercontent.com/29691406/51815350-4633a180-228e-11e9-8152-68997d9f7067.png)

The above picture is the error I get with my react web-app. I am new to react and was following a tutorial that used react-mdl. I installed react-mdl and its in my package.json as well as node_modules but when I add the components from react-mdl onto my App.js it causes the error above to show.
<img width="503" alt="screen shot 2019-01-27 at 11 51 28 pm" src="https://user-images.githubusercontent.com/29691406/51815375-7a0ec700-228e-11e9-990f-492ee7b934de.png">

Any help would be appreciated.

**Comment by mmarkelov** [comment]
@kevin-johar I suppose this is because in node **window** is not defined. And by the way you shouldn't use **react-mdl**, cause it is deprecated. Use [Material Design Components](https://github.com/material-components/material-components-web) instead.

**Comment by piglovesyou** [comment]
Seems like it solved the issue? Please reopen it if didn't.
