### ISSUE TITLE
i cant start... so pls can u help me?

### ISSUE THREAD

**Issue by squirtle34** [kriasoft/react-starter-kit#1710]
C:\Users\Gabriel\Desktop\MyApp>yarn install
yarn install v1.13.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > babel-loader@7.1.4" has incorrect peer dependency "babel-core@6".
warning " > webpack-assets-manifest@3.0.1" has unmet peer dependency "webpack-sources@^1.0".
[5/5] Building fresh packages...
[1/3] ⢀ sqlite3
[2/3] ⠠ uws
error C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.9.1
node-pre-gyp info using node@11.9.0 | win32 | x64
node-pre-gyp info check checked for "C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/node-v67-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/node-v67-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/node-v67-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@4.0.0 and node@11.9.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/node-v67-win32-x64.tar.gz

C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.9.0 | win32 | x64
gyp info ok

C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64 --napi_version=4 --node_abi_napi=napi )  else (node "" configure --fallback-to-build --module=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64 --napi_version=4 --node_abi_napi=napi )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.9.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Gabriel\\Desktop\\MyApp\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Gabriel\\.node-gyp\\11.9.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Gabriel\\.node-gyp\\11.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Gabriel\\.node-gyp\\11.9.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Gabriel\\Desktop\\MyApp\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Gabriel\\Desktop\\MyApp\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok

C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64 --napi_version=4 --node_abi_napi=napi )  else (node "" build --fallback-to-build --module=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64 --napi_version=4 --node_abi_napi=napi )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.9.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Los proyectos de esta soluci�n se van a compilar de uno en uno. Para habilitar la compilaci�n en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: No se pueden encontrar las herramientas de compilaci�n para v140 (Conjunto de herramientas de la plataforma = 'v140'). Para compilar con las herramientas de compilaci�n v140, instale las herramientas de compilaci�n v140. Tambi�n puede actualizar a las herramientas actuales de Visual Studio. Para ello, seleccione el men� Proyecto o haga clic con el bot�n secundario en la soluci�n y, a continuaci�n, seleccione "Actualizar soluci�n". [C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Gabriel\\Desktop\\MyApp\\node_modules\\sqlite3\\lib\\binding\\node-v67-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Gabriel\\Desktop\\MyApp\\node_modules\\sqlite3\\lib\\binding\\node-v67-win32-x64" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Gabriel\Desktop\MyApp\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gabriel\\Desktop\\MyApp\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3
node-pre-gyp ERR! node -v v11.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Gabriel\Desktop\MyApp\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Gabriel\Desktop\MyApp\

**Comment by jorrit** [comment]
Try running this command in an administrator console:

`npm install --vs2015 -g windows-build-tools`

**Comment by squirtle34** [comment]
> 
> 
> Try running this command in an administrator console:
> 
> `npm install --vs2015 -g windows-build-tools`

Thx i solved this issue using: npm install --saved sqlite3

**Comment by piglovesyou** [comment]
@squirtle34 Can we close this now?

**Comment by squirtle34** [comment]
Yes, we can close it.

**Comment by ACPK** [comment]
@squirtle34 - You'll need to close this issue.
