### ISSUE TITLE
sh: node-pre-gyp: command not found

### ISSUE THREAD

**Issue by reactdev208** [kriasoft/react-starter-kit#1716]
sh: node-pre-gyp: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the sqlite3@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mch/.npm/_logs/2019-02-19T23_35_27_909Z-debug.log

**Comment by piglovesyou** [comment]
[Travis CI](https://travis-ci.org/kriasoft/react-starter-kit/builds/497815626?utm_source=github_status&utm_medium=notification) and I on MacOS cannot reproduce it. It seems that it's a problem of `sqlite3` side, not React Starter Kit itself.

**Comment by deidei** [comment]
same problem here! node version problem? please have a check

**Comment by mmarkelov** [comment]
@maksim208 @deidei https://github.com/mapbox/node-sqlite3/issues/1000
You can try ```npm install --unsafe-perm=true``` usually it helps

**Comment by piglovesyou** [comment]
Thank you @mmarkelov . Seems like it solved the issue? Please reopen it if didn't.
