### ISSUE TITLE
Apollo Branch - Showing Parent's Children in Graph

### ISSUE THREAD

**Issue by ACPK** [kriasoft/react-starter-kit#1717]
When I use the code below, all the fields in the children record are blank as shown below. Please note, I am using Mongoose (i.e. the Ids are not integers) .

    query GetPostQuery($id: String!){
      databaseGetPost(id: $id) {
        id,
        text,
        comments {
          id,
          text,
        },
      }
    }

Returns:

    {
      "data": {
        "databaseGetPost": {
          "id": "5c7dbdf066c685236c54463d",
          "text": "adfadf",
          "comments": [
            {
              "id": "\\}ˊ��\u000f,>p\t{",
              "text": null
            },
            {
              "id": "\\}ˋ��\u000f,>p\t}",
              "text": null
            },
          ]
        }
      }
    }
 
The issue seems to be that graphql-tools (the program used in the Apollo branch) requires a resolver. Do you have any advice on how to edit the resolver below to match the ids in the parent with the correct record details?

Example:

    async databaseGetAllPosts() {
      const posts = await Post.find({
      });
      return posts;
    },

**Comment by langpavel** [comment]
Hi @ACPK. What a weird IDs! It looks like a mess, you should definitely fix this ;-)

I cannot help you, except an advice, put `console.log(posts)` and see if keys match.

Also every resolver receives few arguments, see [Resolver function signature](https://www.apollographql.com/docs/graphql-tools/resolvers.html#Resolver-function-signature) in `graphql-tools` doc.

You can put this arguments to `console.log` and then play with queries in `/graphiql`, you whould give better picture after few minutes.

Good luck!

**Comment by ACPK** [comment]
@langpavel - Those Ids where automatically generated by Mongo...

**Comment by langpavel** [comment]
- Again: every resolver receives few arguments, see [Resolver function signature](https://www.apollographql.com/docs/graphql-tools/resolvers.html#Resolver-function-signature) in `graphql-tools` doc.
- Read documentation on Apollo, try play around, try [google mongoose+graphql](https://www.google.cz/search?q=mongoose+graphql).

> Additionally, why was this closed?

Issues are not for basic questions. Mongoose is out of scope.
