### ISSUE TITLE
Warnings: history/createBrowserHistory deprecated, history/PathUtils deprecated, 403 errors

### ISSUE THREAD

**Issue by kutaloweb** [kriasoft/react-starter-kit#1724]
Imports should be just like that:

```
import { createBrowserHistory } from 'history';
import { createPath } from 'history';
```

<img width="1278" alt="Screen Shot 2019-04-07 at 1 01 37 PM" src="https://user-images.githubusercontent.com/17153568/55689077-58d4f180-5935-11e9-930d-0c33ba6f3d0d.png">

**Comment by kutaloweb** [comment]
Take a look at this commit 8d22ecb214d29a0d5689f8fb41f8fbe0b309e944

**Comment by piglovesyou** [comment]
#1726 fixed this.
