### ISSUE TITLE
WebStorm shows error in Home.css

### ISSUE THREAD

**Issue by kutaloweb** [kriasoft/react-starter-kit#1725]
This will fix it:

```
.newsDesc h1,
.newsDesc h2,
.newsDesc h3,
.newsDesc h4,
.newsDesc h5,
.newsDesc h6 {
  font-size: 1.125rem;
}

.newsDesc pre {
  white-space: pre-wrap;
  font-size: 0.875rem;
}

.newsDesc img {
  max-width: 100%;
}
```

<img width="1278" alt="Screen Shot 2019-04-07 at 1 11 03 PM" src="https://user-images.githubusercontent.com/17153568/55689225-db11e580-5936-11e9-875b-e45750c6e15a.png">

**Comment by mmarkelov** [comment]
@kutaloweb webstorm shows error, cause this is not valid css - it should be **Home.scss**

**Comment by kutaloweb** [comment]
@mmarkelov We'd rather use valid CSS in order to be consistent because all files in the project have this extension. I proposed a pull request: 1ef1cca861602f37adccc07a318b832d837a439b.

**Comment by piglovesyou** [comment]
#1726 fixed this.
