### ISSUE TITLE
Question: Is there any way to get URL fragments in routes?

### ISSUE THREAD

**Issue by ImanMh** [kriasoft/react-starter-kit#1727]
I'm looking for a way to get the URL fragment inside my route but I see no way of ding it. For example this is my route: 

``` https://www.myWeb.com/someUrl?someParams=A#BBBBB```

This code can handle params but can't handle URL fragments: 

```
function action({ params }) {
  /*
   * I have params.someParams but I can't get #BBBBB part of my url
   */


  return {
    chunks: ['chunck'],
    component: (
      <Layout>
        <Page />
      </Layout>
    ),
  };
}
```

**Comment by ImanMh** [comment]
Pay attention that I'm also running this code in nodeJS environment for SSR.

**Comment by piglovesyou** [comment]
@ImanMh URL hash (fragment) is not sent to HTTP server in the first place.

**Comment by piglovesyou** [comment]
Tell me if there is something I can do more.
