### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by cmnstmntmn** [kriasoft/react-starter-kit#173]
[redux](https://github.com/gaearon/redux) as a flux alternative

Watch [Dan Abramov's talk on Hot Reloading with Time Travel.](https://www.youtube.com/watch?v=xsSnOQynTHs)

Ref #579

**Comment by timdoes** [comment]
+1

**Comment by tanertopal** [comment]
:+1:

**Comment by Hyra** [comment]
😸

**Comment by MyBoon** [comment]
Redux is pretty simple to integrate to react-starter-kit ... I can PR this feature if @koistya want it.

**Comment by mirchiseth** [comment]
+1

**Comment by nmrony** [comment]
+1

**Comment by vkammerer** [comment]
+1

**Comment by leonprou** [comment]
+1

**Comment by sebastianpicklum** [comment]
+1

**Comment by damirv** [comment]
+1

**Comment by rustanacexd** [comment]
+1 yes please

**Comment by andyhu** [comment]
+1

**Comment by tconroy** [comment]
:+1: !!!

**Comment by learntoswim** [comment]
+1

**Comment by joshua-robinson** [comment]
+1

**Comment by rusenask** [comment]
could we get some kind of discussion here instead of "+1" ? I am also for redux as it looks like a better and cleaner approach although it would be interesting to hear other opinions.

**Comment by tconroy** [comment]
@rusenask I mean... that pretty much sums it up. It's a cleaner flux architecture pattern, and rapidly becoming the community favorite implementation. We could fork this starter kit into two variants (a Flux and a Redux version) if the maintainer isn't interested in swapping out for Redux, but I think it would be in the best interest of the community to do so.

**Comment by langpavel** [comment]
@koistya I'm interesting in implementing redux to this project. Will be PR possibly accepted?

**Comment by koistya** [comment]
@langpavel yes, it can be merged into `feature/redux` branch for now. The problem is that many developer prefer Relay over Redux. I need to conduct a poll to check how many RSK users would like to see Redux on the master branch, how many Relay, and how many would like to keep it Flux-agnostic.

**Comment by langpavel** [comment]
@koistya I'm interesting in Relay too. I thing that can be possible and beneficial to have both but this will need some more digging

**Comment by koistya** [comment]
A bare minimum Redux integration (example)
https://github.com/kriasoft/react-starter-kit/pull/883
