### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by aloysius-tim** [kriasoft/react-starter-kit#1732]
Hello there,

Before anything else, thank you to all the contributors maintaining this amazing boilerplate !

Thus, I have huge performance issues on my latest project using react starter kit.

Here's the report of Lighthouse: https://0x0.st/zMTQ.png

Any idea of what exactly did a do wrong? I do not have any JS dependencies except the one related to the boilerplate. My project is quite small too.

Thank you,
Tim

**Comment by mmarkelov** [comment]
I suppose you check performance in dev mode. And for this case it is totally fine.

**Comment by aloysius-tim** [comment]
I've been using `yarn run build --release`. Should be good?

**Comment by mmarkelov** [comment]
Youp. With release build it should be fine

**Comment by mmarkelov** [comment]
@aloysius-tim here is performance of my starter example
![performance](http://joxi.ru/RmzZKYBUY5GwXm.jpg)

**Comment by piglovesyou** [comment]
So possibly he measured against development mode. Please open this if anyone would like.
