### ISSUE TITLE
Showing a loading indicator when fetching data for a route

### ISSUE THREAD

**Issue by vincentbello** [kriasoft/react-starter-kit#1736]
Likely more of a universal-router question, but figured I'd also ask in here:
When following a route on the client (i.e. clicking a link) that fetches data asynchronously, how would I show visual feedback that the data for the route is loading? Ideally I would show a big spinner on the page instead of blocking the transition until data is ready.
I could hack my way into the DOM, but that seems backwards.

```jsx
async function action({ fetch }) {
  const data = await fetch(); // Show loading indicator while this is happening??
  return {
    title: 'Hello',
    chunks: ['hello'],
    component: (
      <Layout>
        <Hello data={data} />
      </Layout>
    ),
  };
}
```

**Comment by piglovesyou** [comment]
Hi @vincentbello . I suppose you're developing on `kriasoft:master`.

As long as I know, unfortunately the `master` structure is not easy to integrate such loading screen. When a route transitions from A to B, at least A needs to communicate with router, which requires external data management such as Redux, Apollo or something others.

**Comment by mmarkelov** [comment]
@vincentbello yeah! If you are not using Redux or another state manager it will be difficult. And changing DOM is solution.
https://github.com/kriasoft/react-starter-kit/issues/1033

**Comment by vincentbello** [comment]
Super helpful, thank you both!
