### ISSUE TITLE
Unable to run Gulp commands

### ISSUE THREAD

**Issue by varghesep** [kriasoft/react-starter-kit#174]
I was able to install react-starter-kit in **Visual Studio 2015**. However, I can't see any Gulp tasks from the IDE to build the project. I have to run the **gulp** command in the command prompt to build the project.

This is what I see in the IDE:

![gulp](https://cloud.githubusercontent.com/assets/12233474/8762254/59e04862-2d39-11e5-9a81-e5fc883b98e9.PNG)

**Comment by eikeco** [comment]
When running ```gulp``` in the command prompt it triggers the 'default' task. 
If you look at the gulpfile you will see what it does:
```js
// The default task
gulp.task('default', ['sync']);
```

It triggers the 'sync' task. The 'sync' task holds all the build stuff like browser-sync and watch tasks. 
Try running the 'sync' task in VS 2015 and see if it builds.

**Comment by varghesep** [comment]
That worked.

**Comment by eikeco** [comment]
@varghesep awesome.

@koistya I guess this one can be closed now.
