### ISSUE TITLE
Blinking icons and images

### ISSUE THREAD

**Issue by racshaser** [kriasoft/react-starter-kit#1743]
Hello!

I have the following problem: 
Absolutely all images such as avatar images and icons (both SVG and PNG) flicker / blink when moving from page to page. The same thing happens when you refresh the current page. 

Images are stored in the component folder.
```
/Component
    - Component.js
    - icon.svg || icon.png
```

In my case, this is a very serious problem. I use SVG icons in the menu that is on every page.

**Comment by frenzzy** [comment]
How you are using these images, for `<img>` tags or css backgrounds?
Are they are flicker/blink because a browser does a http request for an image when you change page?

**Comment by racshaser** [comment]
I using them for `<img>`.
The problem is solved. 
I added caching to the server.js code.
```
app.use(
  express.static(path.resolve(__dirname, 'public'), { maxAge: 86400000 }),
);
```
