### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by mediahack** [kriasoft/react-starter-kit#178]
I've cloned the repo and followed the install, but I'm getting the error:

```[21:26:51] No gulpfile found```

node: v0.12.2
npm: 2.13.1
gulp: CLI version 3.8.5, Local version 3.9.0

**Comment by alexmcmillan** [comment]
Have a look at some of the other issues in this repo.

**Comment by mediahack** [comment]
@alexmcmillan I did. They are marked as closed for the same issue. Their solution was to update gulp because it needs 3.9.x+ That did not help me.

**Comment by mediahack** [comment]
An issue. I found a solution under a different title. It was my gulp-cli not being up to date.
