### ISSUE TITLE
Getting an error while running "npm run serve" or "npm start" on branch "feature/apollo-pure"

### ISSUE THREAD

**Issue by nitinreddy3** [kriasoft/react-starter-kit#1803]
Getting an error while running "npm run serve" or "npm start" on branch "feature/apollo-pure"

![error_ts](https://user-images.githubusercontent.com/5886208/68567396-e30ea680-047e-11ea-8ccf-cbb6560ffa1e.PNG)

Can anyone please help me out with this?
Packages are installed successfully as well.

**Comment by piglovesyou** [comment]
Hi @nitinreddy3 . I've not checked the behavior of `npm run server`, let me take a look.

Note: I'd like to have tests to make sure all the jobs run well.

**Comment by nitinreddy3** [comment]
For the record, all the scripts fail, they give the above error.

**Comment by piglovesyou** [comment]
@nitinreddy3 Would you please try running `yarn`, `yarn codegen` and `yarn start` instead of npm? Or it might come from the difference of OSs. What's your environment?

**Comment by nitinreddy3** [comment]
OS: Windows10

**Comment by piglovesyou** [comment]
Thank you. I think I could [reproduce it.](https://travis-ci.org/piglovesyou/react-starter-kit/jobs/610323603#L122-L141)

**Comment by nitinreddy3** [comment]
@piglovesyou Thanks for the quick action. BTW is there a possible solution to this since I am migrating my project to Typescript.

**Comment by piglovesyou** [comment]
@nitinreddy3 Not too sure but [could you try this?](https://github.com/piglovesyou/react-starter-kit/commit/9f0d3bf6d6c55721a3301fa5bcff828ac4be6193) Seems like it's working.

**Comment by piglovesyou** [comment]
[Supporting Windows in Travis CI is another story.](https://travis-ci.org/piglovesyou/react-starter-kit/jobs/610336746#L141-L164)

**Comment by piglovesyou** [comment]
In a Travis environment, I checked [it runs well](https://travis-ci.org/piglovesyou/react-starter-kit/builds/610345794#L290). Closing.
