### ISSUE TITLE
what's the http.get('/api/query?path=') for?

### ISSUE THREAD

**Issue by constantx** [kriasoft/react-starter-kit#181]
I'm getting a lot of 404 from this when route are changing.

**Comment by koistya** [comment]
This was supposed to be used for loading HTML content for static pages such as `/about`, `/privacy` etc. I'm going to refactor it within next couple of days.

**Comment by constantx** [comment]
:+1:

**Comment by koistya** [comment]
Fixed in 9bf87bfbac2f605f354d122ab9967ee2cfe28b9e
