### ISSUE TITLE
Graphiql wont render

### ISSUE THREAD

**Issue by akhileshacc** [kriasoft/react-starter-kit#1822]
I clone  the repo, installed everything and tried to see localhost:3000/graphql, it wont render anything. 
Instead shows, some javascript like
```
<｜]|"+re.src_ZPCc+"))("+slist+")","i"),self.re.schema_search=RegExp("(^|(?!_)(?:[><｜]|"+re.src_ZPCc+"))("+slist+")","ig"),self.re.pretest=RegExp("("+self.re.schema_test.source+")|("+self.re.host_fuzzy_test.source+")|@","i"),function(self){self.__index__=-1,self.__text_cache__=""}(self)}function Match(self,shift){var start=self.__index__,end=self.__last_index__,text=self.__text_cache__.slice(start,end);this.schema=....
```
and console shows this error
`Uncaught SyntaxError: Unexpected token '<'`
`graphql:1997 Uncaught ReferenceError: GraphiQL is not defined    at graphql:1997`
`

**Comment by akhileshacc** [comment]
node -v : v10.9.0
yarn -v : 1.19.1

**Comment by piglovesyou** [comment]
Thank you @akhileshacc, I reproduced that. The recent "bumps" might affect it. I'll dig into it.

**Comment by piglovesyou** [comment]
* I took a look but I couldn't spot the root problem
* `express-graphql@0.9.0` returns somehow the broken HTML
* `0.8.9` works fine. I'll downgrade it as a quick fix so far
* We need simple E2E tests to avoid another regression like this

**Comment by piglovesyou** [comment]
@langpavel @frenzzy I'd like to know your opinions if I say I'll set up simple [puppetteer](https://github.com/GoogleChrome/puppeteer) tests to make sure `yarn start`:

* shows the top page
* enables Hot Module Replacement
* launches GraphiQL

. These are the relatively sensitive points to be affected easily in RSK, I think.

You would say it's too much for RSK, however. I'll be glad if you leave a quick comment. I'll wait for a couple of days.

**Comment by langpavel** [comment]
Hey, sorry. I'm so busy now, but if you introduce additional tests, it will be great!

**Comment by piglovesyou** [comment]
Thank you for the quick response. Let me finish it now.
