### ISSUE TITLE
componentDidMount does not work properly

### ISSUE THREAD

**Issue by dvera123** [kriasoft/react-starter-kit#183]
(noob question) I have tried to implement http://jsfiddle.net/torresomar/H6vhQ/ within the components, with no luck, is there a special treatment for componentDidMount in this project? it must to run after the initial rendering occurs in the client side, but it does not seem to work.

Any thoughts?

**Comment by rodolfo2488** [comment]
did you try encapsulating the method body with

```
if(this.isMounted()){
...
}
```
?

**Comment by koistya** [comment]
If you're using ES6 class-based syntax for creating React components, there is no `this.isMounted()` method, instead you need to do proper clean up inside `componentWillUnmount()`.

**Comment by dvera123** [comment]
it is working now, thanks!
