### ISSUE TITLE
Errors from missing files with react-0.14.0-beta2

### ISSUE THREAD

**Issue by RanzQ** [kriasoft/react-starter-kit#184]
I had a module not found error when trying to deploy my app and I realized it was caused by react update. When I did `npm install` for `build/` on my deploy machine it installed `react-0.14.0-beta2` cause there was `^react-0.14.0-beta1` on deps. Tried to update on my dev setup and also got errors.

So maybe the modules should be fixed to work with beta2 or freeze package.json to beta1 for now?

**Comment by tomesposito** [comment]
+1 @RanzQ - beta2 is causing errors on build. freezing react to beta1 gets me building again for now

**Comment by FuzzOli87** [comment]
Do an `npm update` so that it also updates the `react-dom` package as well. When I did `npm-install-missing` it showed that the package was not updated. You also want to change your `package.json` accordingly.
