### ISSUE TITLE
Material UI wont add styles on refreshing

### ISSUE THREAD

**Issue by akhileshacc** [kriasoft/react-starter-kit#1854]
First, I am not sure how to exactly add Material UI support.
I added by doing this in client.js
```
<App context={context} insertCss={insertCss}>
        <MuiThemeProvider>
          <CssBaseline />
          {route.component}
        </MuiThemeProvider>
      </App>
```
Please tell whats the right way to integrate material UI. 
Material UI applies styles well when server starts. But at next refresh none of styles defined inside component are applied.  I apply component wise styles using.
```
const useStyles = makeStyles(theme => ({
  root: {
    color: 'red',
  },
})

export function example() {
const classes = useStyles()
return (
<div className={classes.root}> Hello</>
)
}
```
Please help.

**Comment by akhileshacc** [comment]
class gets applied to a element, but seems like there is no css to be applied.

**Comment by piglovesyou** [comment]
1. Put the theme provider in App.js, not in client.js
2. Try this https://material-ui.com/guides/server-rendering/

**Comment by akhileshacc** [comment]
@piglovesyou Thanks for the help ❤️. It worked.

**Comment by Arnaud-codeur** [comment]
Hi, I'm having a problem with material UI too.
The style is well applied and visible on the screen, but it is rendered with a little delay.

(Each time you load a react page, first the html is imported without the style, then the style appears a few seconds later), it seems to me that this is the effect (FOUC) that the documentation of material UI talks about:

https://material-ui.com/fr/guides/server-rendering/

I can't make the modifications to reproduce what is indicated in this documentation because react starter kit is already using a lot of things that complicates the integration of UI material, could you help me ?

**Comment by Arnaud-codeur** [comment]
> 
> 
> @piglovesyou Thanks for the help ❤️. It worked.

@akhileshacc 
Hello, 
Did you just add the theme in the App file or did you follow the documentation of material Ui?

**Comment by Arnaud-codeur** [comment]
I'm stuck at this step, I don't understand how to add the renderFullPage function, please help me. 

`function renderFullPage(html, css) {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <title>My page</title>
        <style id="jss-server-side">${css}</style>
      </head>
      <body>
        <div id="root">${html}</div>
      </body>
    </html>
  `;
}`

**Comment by piglovesyou** [comment]
Hi. `<Html {...data} />` in [this line](https://github.com/kriasoft/react-starter-kit/blob/1029f9aca15b84a4d66ec924c19bd3e89d749e10/src/server.js#L184) does that so I think you can pass the initial css string there. Hope it helps.

**Comment by Arnaud-codeur** [comment]
thank you, sorry I'm starting with react, I'm a bit lost here, how to proceed exactly?

**Comment by piglovesyou** [comment]
I can't work out time to instruct it in detail, I'm afraid.

**Comment by akhileshacc** [comment]
> > @piglovesyou Thanks for the help ❤️. It worked.
> 
> @akhileshacc
> Hello,
> Did you just add the theme in the App file or did you follow the documentation of material Ui?

I added the theme in App.js and made changes to server.js to include server side rendering things. A part of server.js looks like this 
```
  ........
  ........
const data = { ...route };
    const sheets = new ServerStyleSheets();
    const rootComponent = sheets.collect(
      <App context={context} insertCss={insertCss}>
        {route.component}
      </App>,
    );
    await getDataFromTree(rootComponent);
    // this is here because of Apollo redux APOLLO_QUERY_STOP action
    await Promise.delay(0);
    data.children = await ReactDOM.renderToString(rootComponent);
    data.styles = [{ id: 'css', cssText: [...css].join('') }];
    data.muiStyles = sheets.toString();

    const scripts = new Set();
    const addChunk = chunk => {
      if (chunks[chunk]) {
        chunks[chunk].forEach(asset => scripts.add(asset));
      } else if (__DEV__) {
        throw new Error(`Chunk with name '${chunk}' cannot be found`);
      }
    };
    addChunk('client');
    if (route.chunk) addChunk(route.chunk);
    if (route.chunks) route.chunks.forEach(addChunk);
    data.scripts = Array.from(scripts);
  ........
  ........

```
Hope it helps...

**Comment by Arnaud-codeur** [comment]
Thanks for coming back, you didn't touch the area.
_client.js_?

**Comment by akhileshacc** [comment]
> Thanks for coming back, you didn't touch the area.
> _client.js_?

yeah, dId'nt do any changes in client.js

**Comment by harzkr** [comment]
Trying to do it through modifications in `App.js`, even though I was able see the style changes upon refreshing I was getting a className mismatch warning between the server and client.

When I made changes to the client though, 

```
if (isInitialRender) {
  if (window.history && 'scrollRestoration' in window.history) {
    window.history.scrollRestoration = 'manual';
  }
  
  const elem = document.getElementById('css');
  if (elem) elem.parentNode.removeChild(elem);
  
  //This part specifically
  const jssStyles = document.querySelector('jss-server-side');
  if (jssStyles) {
    jssStyles.parentElement.removeChild(jssStyles);
  }

  return;
}
```

I was able to get it working properly, without warnings

Anyone facing this issue, follow the server config from [https://material-ui.com/guides/server-rendering/](url)

```
 const sheets = new ServerStyleSheets();
 ...
 data.children = ReactDOM.renderToString(
      sheets.collect(
          <ThemeProvider theme={theme}>
            <App context={context} insertCss={insertCss}>
              {route.component}
            </App>
          </ThemeProvider>,
      ),
 );
    ...
  data.styles.push({id:'jss-server-side' , cssText:sheets.toString()});
```

and then modifying the `client.js` as mentioned, should work

**Comment by SuleBenme** [comment]
> Trying to do it through modifications in `App.js`, even though I was able see the style changes upon refreshing I was getting a className mismatch warning between the server and client.
> 
> When I made changes to the client though,
> 
> ```
> if (isInitialRender) {
>   if (window.history && 'scrollRestoration' in window.history) {
>     window.history.scrollRestoration = 'manual';
>   }
>   
>   const elem = document.getElementById('css');
>   if (elem) elem.parentNode.removeChild(elem);
>   
>   //This part specifically
>   const jssStyles = document.querySelector('jss-server-side');
>   if (jssStyles) {
>     jssStyles.parentElement.removeChild(jssStyles);
>   }
> 
>   return;
> }
> ```
> 
> I was able to get it working properly, without warnings
> 
> Anyone facing this issue, follow the server config from [https://material-ui.com/guides/server-rendering/](url)
> 
> ```
>  const sheets = new ServerStyleSheets();
>  ...
>  data.children = ReactDOM.renderToString(
>       sheets.collect(
>           <ThemeProvider theme={theme}>
>             <App context={context} insertCss={insertCss}>
>               {route.component}
>             </App>
>           </ThemeProvider>,
>       ),
>  );
>     ...
>   data.styles.push({id:'jss-server-side' , cssText:sheets.toString()});
> ```
> 
> and then modifying the `client.js` as mentioned, should work

How do know if it's the initial render? How is that possible? I don't know how to do it

**Comment by harzkr** [comment]
@SuleBenme check this out in `client.js` . The `isInitialRender` is available already 

<img width="700" alt="Screenshot 2021-04-28 at 5 36 36 PM" src="https://user-images.githubusercontent.com/11775091/116400963-4c879e00-a848-11eb-83b0-5404cb8fb53c.png">

**Comment by ShindeShubhamm** [comment]
I'm **not** using server side rendering. Just the normal reactjs along with material ui. I've wrapped App.js with ThemeProvider. Also in input prop to ThemeProvider, I'm configuring font to use **Inter** font (this changes material ui components default font). This is causing some delay on fonts to load on route change. As soon as I change the route, Arial is applied first and then Inter after a delay. Any solution to this issue?

**Comment by ulani** [comment]
@akhileshacc   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
