### ISSUE TITLE
only render a component on client-side

### ISSUE THREAD

**Issue by constantx** [kriasoft/react-starter-kit#186]
I'm trying to use `react-select` and got an error throw `document is not defined`. I assume this is because it's trying to render the component on the server side and there's no document.

What's the best way to only render a specific component only on the client side?
##

**Comment by lehneres** [comment]
I think you need to have an container in your HTML and then call `renderToString` with this target in the `componentDidMount`method which will only be called on client siede

**Comment by koistya** [comment]
You can either fake that document object on the server to trick that component. E.g. if component is using `window.addEventListener(...)`. You can create the following global var:

```
import emptyFunction from 'fbjs/lib/emptyFunction';

global.window = {
  addEventListener: emptyFunction,
  removeEventListener: emptyFunction
};
```

Or, even better, don't render that component on the server, e.g.:

```
import { canUseDOM } from 'fbjs/lib/ExecutionEnvironment';

class MyComponent {
  render() {
    return (
      <div>
        { canUseDOM && React.createElement(require('react-select')) }
      </div>
    );
  }
}

```

**Comment by lehneres** [comment]
thx @koistya I think that is a much better solution than using `componentDidMount`!

**Comment by markserbol** [comment]
I tried the `canUseDOM` solution and it worked for me. However it is showing a warning, invalid checksum about the markup being generated is different on the client. I think this means React redraws the markup on the client-side. 
Is it possible to get rid of this warning?

**Comment by jonirrings** [comment]
i tried `canUseDOM` solution and turn out `{canUseDOM ? React.createElement(rte.default):"Rendering"}` as my 'rte.js' `export default class rte`
leave this just for someone who later encounters the problem like me

**Comment by hellais** [comment]
> I tried the canUseDOM solution and it worked for me. However it is showing a warning, invalid checksum about the markup being generated is different on the client. I think this means React redraws the markup on the client-side.

I also ran into this issue. As a way to resolve it used a state variable to ensure the client-side only module is rendered after the first render, like this:

```js
import React, { PropTypes } from 'react';

class MyComponent extends React.Component {

  constructor(props) {
    super(props);
    this.state = {appIsMounted: false};
  }

  componentDidMount() {
    requestAnimationFrame(() => {
      this.setState({ appIsMounted: true });
    });
  }

  render() {
    return (
      <div>
      { this.state.appIsMounted
        && React.createElement(
          require('../../client-side-only').default
        )
      }
      </div>
    );
  }
}
```

Hope this helps somebody else...

**Comment by langpavel** [comment]
This is one which should be mentioned in the docs. *There is no DOM on server.*
PRs welcomed!

**Comment by ulani** [comment]
@constantx   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
