### ISSUE TITLE
Tutorial, guide or even just a youtube-video...?

### ISSUE THREAD

**Issue by tofagerl** [kriasoft/react-starter-kit#187]
I'm having a hell of a time getting into this project. I've been trying for a week, and I still don't know how to create a new page with a component in it. Does anyone know of some sort of guide or tutorial which makes this project more accessible?
##

**Comment by koistya** [comment]
@tofagerl I will try to document the steps which needs to be taken to create a new page / screen.

**Comment by alexmcmillan** [comment]
:+1: It would be awesome if somebody would make a tutorial a little more complex than a TodoApp...

**Comment by unboundfire** [comment]
I created a admin dashboard over a month ago with this project for a coding challenge you can check it out and see if it helps.

https://github.com/unboundfire/example-react-dashboard

**Comment by tofagerl** [comment]
@koistya Great! Even just adding some comments to the code would be great. Using JSdoc's tutorial stuff would probably be best. http://usejsdoc.org/about-tutorials.html

**Comment by tofagerl** [comment]
@unboundfire Your implementation is far simpler it seems, but it would have been far easier to follow your changes with gradual commits. As it is it's ```tons of code -> tons of other code```

**Comment by tofagerl** [comment]
Can anyone give me at least a two sentence quickie on how to integrate react-router in App.js? That way I can just add and remove components as I please. Possibly as a branch?

**Comment by koistya** [comment]
@tofagerl

- install `react-router`
- replace the contents of `src/router.js` with react-router specific routes
- move async code (data fetching etc.) from the router to React components
- update render method in `app.js` (client-side) and `server.js` files

**Comment by tofagerl** [comment]
@koistya Thanks! I'll try that tomorrow.

**Comment by etanxing** [comment]
May help you a little bit: [5 things you should know about react-starter-kit repo](http://william.xingyp.com/5-things-you-should-know-about-react-starter-kit-repo/).

**Comment by tofagerl** [comment]
It did. I ended up just learning react-routing instead of moving to react-router by the way. It does the same thing, just a little differently, and if I end up moving to react-router at a later time, that will be because of an actual lack in react-routing, instead of the old "this is a word I've heard more often, so it must be better" argument.

**Comment by ulani** [comment]
@tofagerl   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
