### ISSUE TITLE
How to fix this error? - 'TypeError: action.default is not a function'

### ISSUE THREAD

**Issue by jeenhyung** [kriasoft/react-starter-kit#1878]
Hi,
I use react-naver-maps. [https://github.com/zeakd/react-naver-maps](url)

I try direct connect to url(localhost:3000/mymap).
And occuring this error blow:
```
TypeError
TypeError: action.default is not a function
    at context.route.load.then.action (/Users/.../src/router.js:16:1)
```
OR
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
**When I connect to direct to url path only..**
(It works fine when connected via the navigation bar.)

I think this problem related to Asynchronous naver map component.
but I couldn't find a solution.

Source code:
file: ../route/mymap/index.js

```
 ...
return {    
title: 'mymap',
    chunks: ['mymap'],
    component: (
      <Layout>
        <RenderAfterNavermapsLoaded
          ncpClientId='...'
          error={<p>Maps Load Error</p>}
          loading={<p>Maps Loading...</p>}
        >
          <NaverMap
            mapDivId="maps-getting-started-uncontrolled" // default: react-naver-map
            ...
          >
          </NaverMap>
        </RenderAfterNavermapsLoaded>
      </Layout>
    ),
  };
}
export default action;
```

file: .../route/index.js

```
 const routes = {
  path: '',
  children: [
    ...
    {
      path: '/mymap',
      load: () => import(/* webpackChunkName: 'mymap' */ './mymap'),
    },
...
```

**Comment by samankhademi** [comment]
i think NaverMap not support SSR, use it in CSR

**Comment by ulani** [comment]
@jeenhyung   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Comment by dsert1** [comment]
The same thing is happening to me. Was there a solution for this ?
