### ISSUE TITLE
feature/apollo-pure not finding __generated__/dataBinders on yarn start command

### ISSUE THREAD

**Issue by Filco306** [kriasoft/react-starter-kit#1890]
Hello! 

First of all, thank you an amazing repo! I am currently trying to use the _feature/apollo-pure_ branch created by @piglovesyou , but am currently struggling to get it up and running when I follow the Getting Started guide. 

Way to reproduce: 
```
$ git clone -o react-starter-kit -b feature/apollo-pure --single-branch https://github.com/kriasoft/react-starter-kit.git MyApp
$ cd MyApp
$ yarn install
$ yarn start
```

Output received: 

```
ERROR in ./src/routes/home/Home.tsx
Module not found: Error: Can't resolve '../../__generated__/dataBinders' in '/*/src/routes/home'
 @ ./src/routes/home/Home.tsx 15:0-63 16:11-23
 @ ./src/routes/home/index.tsx
 @ ./src/routes/index.tsx
 @ ./src/router.ts
 @ ./src/client.tsx
 @ multi ./tools/lib/webpackHotDevClient ./src/client
```

I am new to this repo of course, so might have forgotten some step or something, but it seems not be as straightforward as just getting started here :) 

Thank you in advance!

**Comment by piglovesyou** [comment]
Hi! Please run [`yarn codegen` as the doc instructs](https://github.com/kriasoft/react-starter-kit/blob/09afe1d89eb526a6c60324b13607a35d43e7395e/docs/getting-started.md#3-run-yarn-codegen).

**Comment by Filco306** [comment]
Oh, thank you! I followed the guide on the master branch!
