### ISSUE TITLE
CSS not loading until refresh of CSS file is made

### ISSUE THREAD

**Issue by Filco306** [kriasoft/react-starter-kit#1898]
I am currently trying to create a component, and not a function since I need to maintain state within the component. it works fine, except for the fact that the CSS styling is not working. 

My `Flow.tsx`:

```
import React, { Component } from 'react';
import s from './Flow.css';
import cx from 'classnames';
import useStyles from 'isomorphic-style-loader/useStyles';

class Flow extends Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0,
      currentState: 1
    };
  };

  render() {
    return (
      <div className={s.root}>
        <div className={s.container}>

        Hello

        </div>
      </div>

    );
  }
};
export default Flow;
```

My `Flow.css`:

```
.root {
  background-color: #fff;
}

.container {
  margin: 0 auto;
  padding: 20px 15px;
  max-width: var(--max-content-width);
  text-align: center;
  font-size: 50px;
}
```

The crux is that, in development mode, if I modify `Flow.css`, the CSS code suddenly starts working. With other types of components, e.g., `FunctionComponent`, it gets rendered without a problem. Problem there is that I can't maintain state. Does anybody know what is wrong?

**Comment by piglovesyou** [comment]
Hi. Please try wrapping your component with the `withStyles` HOC [as we do here](https://github.com/kriasoft/react-starter-kit/blob/d8b16a63c51283b17f4d3c59e8614a0228a80cbc/docs/react-style-guide.md#use-css-modules).

**Comment by Filco306** [comment]
Thank you very much @piglovesyou ! That was the solution. Closing this now.
