### ISSUE TITLE
Build issues on ubuntu 12.xx

### ISSUE THREAD

**Issue by jamespsterling** [kriasoft/react-starter-kit#191]
after doing npm install, running gulp produces the following:

ERROR in (undefined) ./src/router.js
Module build failed: SyntaxError: /apps/yoggle/src/router.js: Unexpected token (16:30)
  14 | const router = new Router(on => {
  15 |

> 16 |   on('*', async (state, next) => {
>      |                               ^
>   17 |     const component = await next();
>   18 |     return component && <App context={state.context}>{component}</App>;
>   19 |   });

ERROR in (undefined) ./src/server.js
Module build failed: SyntaxError: /apps/yoggle/src/server.js: Unexpected token (29:39)
  27 | const template = _.template(fs.readFileSync(templateFile, 'utf8'));
  28 |

> 29 | server.get('*', async (req, res, next) => {
>      |                                        ^
>   30 |   try {
>   31 |     let statusCode = 200;
>   32 |     const data = { title: '', description: '', css: '', body: '' };

```
ERROR in ./src/router.js
Module build failed: SyntaxError: /apps/yoggle/src/router.js: Unexpected token (16:30)
  14 | const router = new Router(on => {
  15 |
> 16 |   on('*', async (state, next) => {
     |                               ^
  17 |     const component = await next();
  18 |     return component && <App context={state.context}>{component}</App>;
  19 |   });


ERROR in ./src/server.js
Module build failed: SyntaxError: /apps/yoggle/src/server.js: Unexpected token (29:39)
  27 | const template = _.template(fs.readFileSync(templateFile, 'utf8'));
  28 |
> 29 | server.get('*', async (req, res, next) => {
     |                                        ^
  30 |   try {
  31 |     let statusCode = 200;
  32 |     const data = { title: '', description: '', css: '', body: '' };
```
##

**Comment by vladikoff** [comment]
Gulp is no longer used, please try again with `master` branch

**Comment by AmitMY** [comment]
@jamespsterling Please revisit this issue, and close it if necessary. It seems to be fixed

**Comment by ulani** [comment]
@jamespsterling   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
