### ISSUE TITLE
Forcing a component to re-render

### ISSUE THREAD

**Issue by theunreal** [kriasoft/react-starter-kit#1915]
I'm got the following code in part of the server application:

    if (duel.players.length === 2) {
          console.log('Start duel, emit event!');
          pubsub.emit('DUEL_ROOM_FULL', {
            duel
          });
        }

I'm submitting an event through NodeJS, and I want to update the UI in case there is a new event on this topic.

My routes/battleArea/index.js file:

    let duelStart = 'no';
    pubsub.on('DUEL_ROOM_FULL', msg => {
      console.log("Should start duel");
      duelStart = 'yes';
    });
    
    async function action({ fetch }) {
    
      const resp = await fetch('/graphql', {
        body: JSON.stringify({
          query: '{duel{id,round_id,status,players{user_id,username,rank}}}',
        }),
      });
      const { data } = await resp.json();
      if (!data) throw new Error('Failed to load the battle data.');
      const { duel } = data;
      if (duel && duel.status === 'WAITING') {
        return {
          component: (
            <Layout>
              <div>Duel Start: {duelStart}</div>
              <WaitRoom duel={duel} />
            </Layout>
          ),
        };
      }
    
      return {
        title: 'Battle Area',
        chunks: ['battleArea'],
        component: (
          <Layout>
            <BattleArea />
          </Layout>
        ),
      };
    }
    
    export default action;

Unfortunately, the following code:
`<div>Duel Start: {duelStart}</div>` prints `'no'` and stays, although I see in the console that the event has been received.
I assume it happens because the component has been rendered by the server before he received this event, so I want to re-render the component in case I received this event. 

Any idea if it's possible \ how to do this?

Thanks.

  [1]: https://github.com/kriasoft/react-starter-kit

**Comment by ulani** [comment]
@theunreal   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
