### ISSUE TITLE
getInitialState does not work

### ISSUE THREAD

**Issue by dvera123** [kriasoft/react-starter-kit#193]
It seems I cannot set initial states when I use 

class whatever {
  getInitialState(){
  //it does not work
  }
  render() {
  };
}

it only works in this way: 

var whatever React.createClass({
  getInitialState: function() {
  //it works
},

return function(){
}
});

If I choose the second one everything works fine except the @withStyles(styles)

any ideas in how to set the @withStyles(styles) working properly using the second approach?

**Comment by WolfspiritM** [comment]
Just stumpled over this issue.
The getInitialState function is not used for ES6 classes as it's not needed anymore.
If you use the es6 syntax you have two choices to define the state.
If you are brave enough to use early development features of es7 (they can change very much until they are a feature in es7 over the next year(s)) you can use class property initializiers like that:

class whatever {
    state = { test: "test" };
    render() {
       ...
    }
}

a more "es6-like" way is to use the class constructor:
class whatever {
    constructor(props) {
        super(props);
        this.state = {test: "test"};
    }
    render() {
       ...
    }
}

You can read more about it here:
https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

**Comment by dvera123** [comment]
Got it, it works now, thanks!
