### ISSUE TITLE
How to use in `.vscode/react.code-snippets `

### ISSUE THREAD

**Issue by acbde45** [kriasoft/react-starter-kit#1953]
Is it useful?
And how to use?
Please tech me, 3q.

**Comment by koistya** [comment]
@acbde45 hey! It helps to scaffold common js modules (React components etc.)

![2021-06-24 23 21 09](https://user-images.githubusercontent.com/197134/123327283-eca92d00-d542-11eb-8d1c-d2f1d6205fed.gif)

**Comment by acbde45** [comment]
Thats cool, 3q very much.
