### ISSUE TITLE
Error 500: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by mahbodmo** [kriasoft/react-starter-kit#1958]
i did every steps you wrote, step by step
but after running the project (yarn start), this is a message i get
i deleted and retried from the beginning many times,
but this is the message i get every time

**Comment by koistya** [comment]
It fails when trying to access API at `http://localhost:3000/api/` which is a [proxy](https://github.com/kriasoft/react-starter-kit/blob/c9c685bade0f2409c48e13e344517d0875846bb6/webpack.config.js#L268-L279) to this [example API](https://us-central1-kriasoft.cloudfunctions.net/reactstarter/api) serving as an example, you can replace it with your own API endpoint by tweaking [`config.ts`](https://github.com/kriasoft/react-starter-kit/blob/c9c685bade0f2409c48e13e344517d0875846bb6/config.ts#L14-L20). It looks like the example API is not accessible from you location (my guess).

**Comment by mahbodmo** [comment]
i changed the api address in config.ts but it didn't work
could you please tell exactly where do you mean in code

**Comment by shivam2093** [comment]
h

**Comment by koistya** [comment]
Hey @mahbodmo, sorry for the late response. If you're using the latest version of the template, you can find/change API URL in one of the `*.env` file for the target environment (see `core/.local.env` → `API_ORIGIN` that is used for local development).
