### ISSUE TITLE
Cannot find module ... TypeScript error in VSCode

### ISSUE THREAD

**Issue by stephyswe** [kriasoft/react-starter-kit#1982]
After cloning, running "yarn install", then "yarn start" I get the following error messages.
Full log: <https://gist.github.com/stephyswe/8c6a749304aaeb84a3450258688e2ba5>
```
  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
X [ERROR] Could not resolve "./C:/Users/Stephanie/AppData/Local/Yarn/Berry/cache/firebase-npm-9.9.1-4f1112f562-9.zip/node_modules/firebase/auth/dist/index.esm.js"

    dep:firebase_auth:2:14:
      2 │ export * from "./C:/Users/Stephanie/AppData/Local/Yarn/Berry/cache/firebase-npm-9.9.1-4f1112f562-9.zip/node_modules/firebase/auth/dist/index.esm.js" 
```

FIX - yarn set version latest
it set package.json to a lower yarn version. "packageManager": "yarn@4.0.0-rc.14", to "packageManager": "yarn@3.2.2",
then , yarn install, yarn start, started with no errors. not sure why.

Another issue not related is that inside an .tsx file (App.tsx) get syntax error. not sure why is there a workaround? 

![image](https://user-images.githubusercontent.com/20955623/182106784-011dd307-7ecf-4172-a493-09cc3a19adfd.png)

**Comment by stephyswe** [comment]
*FIX*  - `yarn set version latest`

it set package.json to a lower yarn version from. 
from `  "packageManager": "yarn@4.0.0-rc.14", ` to ` "packageManager": "yarn@3.2.2",`

then , yarn install, yarn start, started with no errors. not sure why.

**Comment by koistya** [comment]
@stephyswe please ensure that you're using the local version of TypeScript in VSCode (`Shift` + `Cmd` + `P`)

![image](https://user-images.githubusercontent.com/197134/182196489-a3fc06dd-a9a6-4384-94f3-cf9550a3c453.png)

![image](https://user-images.githubusercontent.com/197134/182196766-8e9c4b17-7332-4b48-9e14-1cefa17a6ba0.png)

Note, that the project is configured to use Yarn with PnP; it's also possible to configure Yarn to use `node_modules` folder instead (via `yarn config set nodeLinker node-modules` then removing PnP paths from `.vscode/settings.json`).

**Comment by cglacet** [comment]
Wow, what the heck was that, thanks. I've been using typescript projects for years, first time this happens to me. 

Thanks @koistya
