### ISSUE TITLE
Hot Reload CSS and JS files changes

### ISSUE THREAD

**Issue by Sadam-MCA** [kriasoft/react-starter-kit#1995]
Branch: master
Node: 14

I have updated the code on the **JS and CSS** file but it does not reflect on a webpage.  The code will reflect When I refresh the page.

I have attached the video link: https://drive.google.com/drive/folders/1qkP1LPaY6cwuIw0fF6Wdj14X8O5UVdF0

**Comment by koistya** [comment]
@Sadam-MCA sorry, I have to close this issue in favor of #1991 discussion since it's not relevant to the latest version of the starter kit (from the `main` branch).
