### ISSUE TITLE
Cannot open started application due to Firebase error

### ISSUE THREAD

**Issue by emirmo** [kriasoft/react-starter-kit#2006]
_Environment details_

**OS:** Ubuntu 22.04.1 LTS
**Node version**: v18.8.0

_Steps to reproduce:_

1) Execute the following steps from readme:
```
$ git clone https://github.com/kriasoft/react-starter-kit.git example
$ cd ./example
$ yarn install
$ yarn start
```

2) Navigate via web browser to the following URL:
http://localhost:5173/

The browser shows the following error:
`Uncaught FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).
`

_Fixes attempted:_

Changing Firebase credentials by adding my own does not help.
If there are additional instructions in readme file that I've missed, please add them.

**Comment by peterkuykendall** [comment]
Having the same problem

**Comment by emirmo** [comment]
> Having the same problem

I suspect the following part of the readme file is intended to indicate how to approach this:

`update the environment variables found in [env/*.env]
`

So if you set the following environment variables to some values (they do not even have to be valid credentials), the error no longer occurs:

```
GOOGLE_CLOUD_PROJECT=
GOOGLE_CLOUD_REGION=
```

However, I'd suggest developers update the readme file to clarify this further. 

Additionally, my web browser reports other console errors even after this issue is fixed.
