### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "10". Got "18.14.0"

### ISSUE THREAD

**Issue by BigWinston** [kriasoft/react-starter-kit#2042]
Hi All,

Just found your repo... Look's exciting but I'm afraid I fell at the first hurdle.

In following the QuickStart guide, on the `yarn install` command, I receive the following error `The engine node is incompatible with this module. Expected version 10. Got 18.14.0`.

However, on the readme it says I need node 18+.

In searching the issues, I see a related issue from 2019 concerning installing vs build tools.  Is this still a current resolution?  I tried installing this package but it failed.

How can I get past this error?

Many Thanks,

BW.

**Comment by jaypatel9800** [comment]
hey @BigWinston, @AlexJanow 

I also tried to repro this issue on my local machine but I am not found any error related to node 18.
let me know guys if you face this issue.

Happy to help...

**Comment by koistya** [comment]
@bsr203 the GitHub repo URL in your example is invalid, I believe.

```bash
$ git clone -o seed -b main --single-branch https://github.com/kriasoft/react-starter-kit example
$ cd ./example
$ corepack enable
$ yarn install
$ yarn workspace app start
```
