### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by cnewfeldt** [kriasoft/react-starter-kit#205]
Hi, 

I'm starting from a fresh install following the steps in the readme and getting 14 errors like the sample below   

    ERROR in ./src/components/App/App.js
    Module build failed: SyntaxError: /src/components/App/App.js: Unexpected token (11:0)
       9 | import Footer from '../Footer';
      10 |
    > 11 | @withContext
         | ^
      12 | @withStyles(styles)

I'm seeing this with any file that references the @ symbol in it. I'm assuming this is on my end as no one else has the same issue, but I'm stuck as to what the problem is. 

Any pointers or suggestions would be appreciated.

Thank you, 

Cary

**Comment by cnewfeldt** [comment]
Well, looks like npm cache clean fixed my issue! Sorry for the bother.

**Comment by ro0sterjam** [comment]
Hi, I'm also having issues with this. I even tried npm cache clean to no avail.

**Comment by Anenth** [comment]
am having the same problem !

**Comment by koistya** [comment]
Do you get this error when you run `npm start` or `npm run build`?

**Comment by Anenth** [comment]
@koistya both ! where is the babel experimental flag set ? (to use the es7.decorators)

**Comment by koistya** [comment]
It should read settings from the [.babelrc](https://github.com/kriasoft/react-starter-kit/blob/master/.babelrc) file...

**Comment by koistya** [comment]
@Anenth you can try to replace `babel-loader` with `babel-loader?stage=0` on this line to check if it helps:

https://github.com/kriasoft/react-starter-kit/blob/17a2dc0dfc6bc60c0a702565a0dc2e430fea7229/tools/config.js#L90

**Comment by Anenth** [comment]
@koistya `.babelrc` file was missing ! worked fine after i created the file.
Thanks

**Comment by ro0sterjam** [comment]
My god that was the problem all along. I've been ripping my hair out about this. I too was missing the .babelrc file. Thank you so much.
