### ISSUE TITLE
Using stylus instead of PostCSS

### ISSUE THREAD

**Issue by jnsandrew** [kriasoft/react-starter-kit#207]
I'm in the process of porting bits of my old site into RSK and since the styles are written with stylus I need to rip out postcss / disable it and use a stylus loader instead.

I've got so far but the problem is with the server side rendering - in the <style> tags in the head it only displays 

<style type="text/css">[object Object] [object Object]</style>

This only happens server side, once app.js loads the styles are fine. Have I missed a step?

**Comment by koistya** [comment]
Maybe you accidentally added `style-loader` for server-side bundle configuration? Can you share your Webpack config file?

**Comment by jnsandrew** [comment]
That's exactly what the problem was! Thank you!
