### ISSUE TITLE
--> GET /__webpack_hmr doesn't handle

### ISSUE THREAD

**Issue by tadjik1** [kriasoft/react-starter-kit#213]
When I turn on logger on my express server I see requests on /__webpack_hmr, but my application doesn`t know what to do with it. I think that it's an error and that type of requests should handle in webpack middlewares.

**Comment by koistya** [comment]
@tadjik1 good catch! I will check what's wrong

**Comment by koistya** [comment]
Looks like a bug in [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware). See glenjamin/webpack-hot-middleware#16
