### ISSUE TITLE
rename Dispatcher.js to dispatcher.js

### ISSUE THREAD

**Issue by jifeon** [kriasoft/react-starter-kit#214]
I'm about https://github.com/kriasoft/react-starter-kit/blob/master/src/core/Dispatcher.js

File name should start with lower 'd' because it exports an instance of Dispatcher

**Comment by jifeon** [comment]
The same for Location.js, it's just an object

**Comment by nodegin** [comment]
+1

**Comment by koistya** [comment]
+1 will do

**Comment by arvigeus** [comment]
This issue can be closed: [/src/core/Dispatcher.js](https://github.com/kriasoft/react-starter-kit/blob/master/src/core/Dispatcher.js) is no longer used.
