### ISSUE TITLE
Flux / onChange doesn't fire after changing pages

### ISSUE THREAD

**Issue by jnsandrew** [kriasoft/react-starter-kit#216]
I'm not sure if this is a specific RSK issue but it's one I'm having trouble with. If a component is in App.js (as part of the layout, not the child components e.g. header) and it has a listener on a Flux Store e.g.

```
componentDidMount() {
  DataStore.onChange(() => {
    // Fn doesn't fire after changing pages
    this.setState({data: DataStore.getData()});
  });
}
```

Then after changing pages (via pushState not a full page reload), the component doesn't receive any onChange events after that, but I'm not sure why? The child components always get the onChange events. 

Any ideas?
##

**Comment by koistya** [comment]
@jnsandrew you're sure that the child elements gets updates via `DataStore.onChange(...)` and not with the initial data load? E.g. `constructor() { this.state = DataStore.getData(); }`

**Comment by jnsandrew** [comment]
The child components all refresh as expected (anything in {children} in components/App.js), what doesn't refresh are the other components in App.js e.g. Header or Footer. As with the example in the original issue, even if I add a console.log into the onChange, it won't show in my console.

    // Header.js
    componentDidMount() {
      DataStore.onChange(() => {
        console.log('change happened'); // Doesn't show after page change
      });
    }

Whereas in my DataStore
    
    // ../stores/DataStore.js
    emitChange() {
      console.log('change emitted'); // This shows
      return this.emit(CHANGE_EVENT);
    },

If the console.log would at least show then it would mean it's just my data not refreshing, but if I don't event get a console.log then it's like the onChange registers, but after the page change it creates a new DataStore or something?

**Comment by lehneres** [comment]
how is the `onChange` method looking?, Maybe try `DataStore.on( CHANGE_EVENT, callback )`

**Comment by jnsandrew** [comment]
Yeah that's what it is in the DataStore:
    
    // ../stores/DataStore.js
    onChange(callback) {
        this.on(CHANGE_EVENT, callback);
    },

**Comment by lehneres** [comment]
Hm maybe is `this` not pointing to the emitter in this context?

**Comment by jnsandrew** [comment]
Some extra weirdness (maybe!) is that I have another button inside the header bar (for toggling navigation), and this works even after page change, but if I move the button into a child component, then the same thing happens again - doesn't work after changing page.

So yeah the context of `this` might be a good shout.

**Comment by jnsandrew** [comment]
Update on this. I didn't find the "why" this is happening, but I worked around it, so if anyone is having the same issue, here's one way to get around this issue.

I removed all the constant components from <App />, so this is your <Header />, <Footer /> etc. and included the {this.props.children} in on it's own. Then I moved them into a layouts component and included that in the pages components. E.g.

*LoginPage.js*

    @withStyles(styles)
    class LoginPage extends Component {

      static contextTypes = {
        onSetTitle: PropTypes.func.isRequired,
        onSetMeta: PropTypes.func.isRequired
      };

      render() {
        this.context.onSetTitle(`Login`);
        this.context.onSetMeta('description', `Log in to your account`);
        // <Message /> is the name of the layout component
        return (
          <Message>
            <LoginForm />
          </Message>
        );
      }
    }

*MessageLayout.js*

    @withStyles(styles)
    class Message extends Component {

      render() {
        let className = 'layout-default';
        return (
          <div className={className}>
            <Header />
            <div className="layout__content">{this.props.children}</div>
            <Footer />
          </div>
        );
      }
    }

This is a good solution for me because I have multiple layouts on my platform (a default one with headers and footers, and other smaller pages with just a different type of footer or something) so this works out easier for me to manage rather than adding styles to hide components I don't want on certain pages.

This whole issue came about because I wanted a button on the header that works like a shopping cart button, where the user would click 'add to cart' and the button on the header would refresh the number of items in the cart. 

Hope this helps someone else having the same issue.
