### ISSUE TITLE
Which Flux implementation should I use?

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#22]
### [Relay](https://github.com/facebook/relay/) by Facebook + [examples](https://github.com/facebook/relay/tree/master/examples)
[![img](https://img.shields.io/npm/dm/react-relay.svg?style=flat-square)](https://www.npmjs.com/package/react-relay) [![img](https://img.shields.io/github/issues-raw/gfacebook/relay.svg?style=flat-square)](https://github.com/facebook/relay/issues) [![img](https://img.shields.io/github/stars/facebook/relay.svg?style=flat-square)](https://github.com/facebook/relay) [![img](https://img.shields.io/github/forks/facebook/relay.svg?style=flat-square)](https://github.com/facebook/relay)
[![npm](https://nodei.co/npm-dl/react-relay.png?months=12&height=3)](https://www.npmjs.com/package/react-relay)

### [redux](https://github.com/gaearon/redux) by Dan Abramov
[![img](https://img.shields.io/npm/dm/redux.svg?style=flat-square)](https://www.npmjs.com/package/redux) [![img](https://img.shields.io/github/issues-raw/gaearon/redux.svg?style=flat-square)](https://github.com/gaearon/redux/issues) [![img](https://img.shields.io/github/stars/gaearon/redux.svg?style=flat-square)](https://github.com/gaearon/redux) [![img](https://img.shields.io/github/forks/gaearon/redux.svg?style=flat-square)](https://github.com/gaearon/redux)
[![npm](https://nodei.co/npm-dl/redux.png?months=12&height=3)](https://www.npmjs.com/package/redux)

### [flux](https://facebook.github.io/flux) by Facebook + [examples](https://github.com/facebook/flux/tree/master/examples)
[![img](https://img.shields.io/npm/dm/flux.svg?style=flat-square)](https://www.npmjs.com/package/flux) [![img](https://img.shields.io/github/issues-raw/facebook/flux.svg?style=flat-square)](https://github.com/facebook/flux/issues) [![img](https://img.shields.io/github/stars/facebook/flux.svg?style=flat-square)](https://github.com/facebook/flux) [![img](https://img.shields.io/github/forks/facebook/flux.svg?style=flat-square)](https://github.com/facebook/flux)
[![npm](https://nodei.co/npm-dl/flux.png?months=12&height=3)](https://www.npmjs.com/package/flux)

### [alt](http://alt.js.org/) by Josh Perez +  [examples](https://github.com/goatslacker/alt/tree/master/examples)
[![img](https://img.shields.io/npm/dm/alt.svg?style=flat-square)](https://www.npmjs.com/package/alt) [![img](https://img.shields.io/github/issues-raw/goatslacker/alt.svg?style=flat-square)](https://github.com/goatslacker/alt/issues) [![img](https://img.shields.io/github/stars/goatslacker/alt.svg?style=flat-square)](https://github.com/goatslacker/alt) [![img](https://img.shields.io/github/forks/goatslacker/alt.svg?style=flat-square)](https://github.com/goatslacker/alt)
[![npm](https://nodei.co/npm-dl/alt.png?months=12&height=3)](https://www.npmjs.com/package/alt)

### [reflux](https://github.com/spoike/refluxjs) by Mikael Brassman + [examples](https://github.com/spoike/refluxjs#examples)
[![img](https://img.shields.io/npm/dm/reflux.svg?style=flat-square)](https://www.npmjs.com/package/reflux) [![img](https://img.shields.io/github/issues-raw/spoike/refluxjs.svg?style=flat-square)](https://github.com/spoike/refluxjs/issues) [![img](https://img.shields.io/github/stars/spoike/refluxjs.svg?style=flat-square)](https://github.com/spoike/refluxjs) [![img](https://img.shields.io/github/forks/spoike/refluxjs.svg?style=flat-square)](https://github.com/spoike/refluxjs)
[![npm](https://nodei.co/npm-dl/reflux.png?months=12&height=3)](https://www.npmjs.com/package/reflux)

### [flummox](http://acdlite.github.io/flummox) (deprecated) by Andrew Clark
[![img](https://img.shields.io/npm/dm/flummox.svg?style=flat-square)](https://www.npmjs.com/package/flummox) [![img](https://img.shields.io/github/issues-raw/acdlite/flummox.svg?style=flat-square)](https://github.com/acdlite/flummox/issues) [![img](https://img.shields.io/github/stars/acdlite/flummox.svg?style=flat-square)](https://github.com/acdlite/flummox) [![img](https://img.shields.io/github/forks/acdlite/flummox.svg?style=flat-square)](https://github.com/acdlite/flummox)
[![npm](https://nodei.co/npm-dl/flummox.png?months=12&height=3)](https://www.npmjs.com/package/flummox)

### [fluxible](http://fluxible.io/) by Yahoo
[![img](https://img.shields.io/npm/dm/fluxible.svg?style=flat-square)](https://www.npmjs.com/package/fluxible) [![img](https://img.shields.io/github/issues-raw/yahoo/fluxible.svg?style=flat-square)](https://github.com/yahoo/fluxible/issues) [![img](https://img.shields.io/github/stars/yahoo/fluxible.svg?style=flat-square)](https://github.com/yahoo/fluxible) [![img](https://img.shields.io/github/forks/yahoo/fluxible.svg?style=flat-square)](https://github.com/yahoo/fluxible)
[![npm](https://nodei.co/npm-dl/fluxible.png?months=12&height=3)](https://www.npmjs.com/package/fluxible)

### [fluxxor](http://fluxxor.com/) by Brandon Tilley + [examples](https://github.com/BinaryMuse/fluxxor/tree/master/examples)
[![img](https://img.shields.io/npm/dm/fluxxor.svg?style=flat-square)](https://www.npmjs.com/package/fluxxor) [![img](https://img.shields.io/github/issues-raw/BinaryMuse/fluxxor.svg?style=flat-square)](https://github.com/BinaryMuse/fluxxor/issues) [![img](https://img.shields.io/github/stars/BinaryMuse/fluxxor.svg?style=flat-square)](https://github.com/BinaryMuse/fluxxor) [![img](https://img.shields.io/github/forks/BinaryMuse/fluxxor.svg?style=flat-square)](https://github.com/BinaryMuse/fluxxor)
[![npm](https://nodei.co/npm-dl/fluxxor.png?months=12&height=3)](https://www.npmjs.com/package/fluxxor)

### [marty.js](http://martyjs.org/) by James Hollingworth + [examples](https://github.com/martyjs/marty/tree/master/examples)
[![img](https://img.shields.io/npm/dm/marty.svg?style=flat-square)](https://www.npmjs.com/package/marty) [![img](https://img.shields.io/github/issues-raw/martyjs/marty.svg?style=flat-square)](https://github.com/martyjs/marty/issues) [![img](https://img.shields.io/github/stars/martyjs/marty.svg?style=flat-square)](https://github.com/martyjs/marty) [![img](https://img.shields.io/github/forks/martyjs/marty.svg?style=flat-square)](https://github.com/martyjs/marty)
[![npm](https://nodei.co/npm-dl/marty.png?months=12&height=3)](https://www.npmjs.com/package/marty)

### [fynx](http://foss-haas.github.io/fynx) by Alan Plum
[![img](https://img.shields.io/npm/dm/fynx.svg?style=flat-square)](https://www.npmjs.com/package/fynx) [![img](https://img.shields.io/github/issues-raw/foss-haas/fynx.svg?style=flat-square)](https://github.com/foss-haas/fynx/issues) [![img](https://img.shields.io/github/stars/foss-haas/fynx.svg?style=flat-square)](https://github.com/foss-haas/fynx) [![img](https://img.shields.io/github/forks/foss-haas/fynx.svg?style=flat-square)](https://github.com/foss-haas/fynx)
[![npm](https://nodei.co/npm-dl/fynx.png?months=12&height=3)](https://www.npmjs.com/package/fynx)

### [McFly](https://github.com/kenwheeler/mcfly) by Ken Wheeler + [example](https://github.com/kenwheeler/mcfly/tree/master/example)
[![img](https://img.shields.io/npm/dm/mcfly.svg?style=flat-square)](https://www.npmjs.com/package/mcfly) [![img](https://img.shields.io/github/issues-raw/kenwheeler/mcfly.svg?style=flat-square)](https://github.com/kenwheeler/mcfly/issues) [![img](https://img.shields.io/github/stars/kenwheeler/mcfly.svg?style=flat-square)](https://github.com/kenwheeler/mcfly) [![img](https://img.shields.io/github/forks/kenwheeler/mcfly.svg?style=flat-square)](https://github.com/kenwheeler/mcfly)
[![npm](https://nodei.co/npm-dl/mcfly.png?months=12&height=3)](https://www.npmjs.com/package/mcfly)

### [DeLorean.js](http://deloreanjs.com/) by Fatih Kadir Akın + [examples](https://github.com/deloreanjs/delorean/tree/master/examples)
[![img](https://img.shields.io/npm/dm/delorean.svg?style=flat-square)](https://www.npmjs.com/package/delorean) [![img](https://img.shields.io/github/issues-raw/deloreanjs/delorean.svg?style=flat-square)](https://github.com/deloreanjs/delorean/issues) [![img](https://img.shields.io/github/stars/deloreanjs/delorean.svg?style=flat-square)](https://github.com/deloreanjs/delorean) [![img](https://img.shields.io/github/forks/deloreanjs/delorean.svg?style=flat-square)](https://github.com/deloreanjs/delorean)
[![npm](https://nodei.co/npm-dl/delorean.png?months=12&height=3)](https://www.npmjs.com/package/delorean)

### [fluxify](https://github.com/arqex/fluxify) by Javier Márquez
[![img](https://img.shields.io/npm/dm/fluxify.svg?style=flat-square)](https://www.npmjs.com/package/fluxify) [![img](https://img.shields.io/github/issues-raw/arqex/fluxify.svg?style=flat-square)](https://github.com/arqex/fluxify/issues) [![img](https://img.shields.io/github/stars/arqex/fluxify.svg?style=flat-square)](https://github.com/arqex/fluxify) [![img](https://img.shields.io/github/forks/arqex/fluxify.svg?style=flat-square)](https://github.com/arqex/fluxify)
[![npm](https://nodei.co/npm-dl/fluxify.png?months=12&height=3)](https://www.npmjs.com/package/fluxify)

Comparison: https://github.com/voronianski/flux-comparison

**Comment by frankleng** [comment]
one more to consider...
https://github.com/arqex/fluxify

**Comment by hipertracker** [comment]
I don't see compelling reason why to use Dispatcher. I prefer Reflux, it's simpler and cleaner.

**Comment by irium** [comment]
I'm personally using https://github.com/goatslacker/alt

**Comment by honkskillet** [comment]
FWIW, a bunch of the links to the npm packages (from the images) go to the wrong packages.

**Comment by koistya** [comment]
@honkskillet fixed

**Comment by mridgway** [comment]
If the goal is for the application to be isomorphic, you should look into our [Fluxible](http://fluxible.io) library. We're using store instances instead of singletons to avoid concurrency issues that you'd see on the server when doing isomorphic.

**Comment by koistya** [comment]
@mridgway, but that adds complexity... Have you tried the other way around - keep using singletons, but make sure that each server-side rendering operation (HTTP request) uses a separate JavaScript execution environment?

**Comment by mridgway** [comment]
You have two options if you want to use a separate environment: use a separate node process for rendering each request or using node's `vm` module. Neither of these options will give you very good scalability.

We haven't found that it adds that much complexity at all. In fact, it makes it easier to test stores because you don't have to worry about side effects between tests. You can see an implementation of Fluxible in our [flux-examples](https://github.com/yahoo/flux-examples) or our [docs site](https://github.com/yahoo/fluxible.io).

**Comment by koistya** [comment]
@mridgway what about rendering React app directly with V8 without Node's overhead?

**Comment by goatslacker** [comment]
I came to post about this exact thing and found this discussion.

[alt](https://github.com/goatslacker/alt) gives you lots of flexibility in terms of isomorphism, you can keep your stores as singletons without using `vm` or you can take the fluxible approach and create instances of flux and pass it around your react components using context.

The case for alt:

* Actually flux. It doesn't deviate from the flux architecture and uses flux's dispatcher.
* Isomorphic. Both creating instances or keeping stores as singletons.
* Terse, lessens the overhead (no constants, switch statements, no writing own dispatcher) but still has all the benefits of those (code grepability, able to listen to global dispatcher)
* Has some nice features (bootstrap / snapshots) which allow you to save the entire application state and then reload it later. This is great for debugging.

**Comment by cluelessjoe** [comment]
Well, there is also [Flummox](https://github.com/acdlite/flummox) which aims to be idiomatic, modular, testable, isomorphic Flux & with no singletons required.

On the other hand, I start to wonder about framework evolution as well, rewriting working code for each version is a pain!

**Comment by aaronGoshine** [comment]
I came across this post and thought it was quite interesting, I have read the FLUX docs a while back and the possibilities are endless, however these flavours of flux just add a few tweaks to the Facebook flux minus a few of the core concept. (dispatching order, single point store optimisation, wait-for, and over all granular control) 
Moreover the Facebook flux is more tested, more used and Facebook have demonstrated that it is very scalable.

The npm charts  that are at the top of this page, is not drawn on the same scale, so comparing them visually will be misleading read the values carefully

**Comment by goatslacker** [comment]
@aaronGoshine I encourage you to check out a lot of the flux libraries if you're interested in flux. Most of them use the flux dispatcher so contrary to what you're saying they add value on top of flux. A lot of these libraries are also used in production on high traffic websites like fluxible and alt.

**Comment by dandv** [comment]
What a wonderful example of the [paradox of choice](http://wiki.dandascalescu.com/summaries/ted_talks/0093_barry_schwartz_-_the_paradox_of_choice)!

No wonder that it's [easier to get started with Meteor + React](https://www.youtube.com/watch?v=-QtrkXKvQFc&t=348), than with Flux + React.

**Comment by erkieh** [comment]
@goatslacker and others
I found a old post at https://news.ycombinator.com/item?id=8989495 saying
"Alt[1] has isomorphic support but there are some trade offs such as you're unable to use actions on the server."

Is this still the case? Are there other libraries which support actions on the server?
Since i have yet to make a single react app, i don't know how relevant this feature is.

**Comment by goatslacker** [comment]
@erkieh depends on what you're going for and what your setup is like:

You can go a singleton-free approach a'la Fluxible and pass around your instance down through props or context (or even better use something like [AltContainer](http://alt.js.org/docs/components/altContainer/)) this will allow you to call actions on the server and load your data into your stores.

In some cases you already have all the data available, say you're using rails or something, in which case all you need to do is load it into the right stores and then render. In that case you can go with singletons, just load your stores up using [bootstrap](http://alt.js.org/docs/bootstrap/) and then [flush](http://alt.js.org/docs/flush/) them after you've created your markup.

I'll be posting a how-to isormorphic guide sooner or later.

**Comment by lleolin** [comment]
@dandv The irony is that, for a newb like myself, Meteor becomes another option to research. Thanks for mentioning it, though (sincerely).

**Comment by dandv** [comment]
@lleolin: the difference is that you can pick up the basics of Meteor in [one hour](http://meteor.com/try) and that will give you a lot more out of the box (a web+mobile reactive app built on a realtime platform) vs. what you'd learn from one Flux implementation (just a server).

**Comment by Kobold** [comment]
@dandv Stop shilling for Meteor. It's cool tech, but this is a discussion of flux implementations.

**Comment by scottycoupa** [comment]
I dont mind knowing Meteor is an option.

**Comment by koistya** [comment]
There are some other alternatives as well, take a look [here](http://qiita.com/kimagure/items/22cf4bb2a967fcba376e) (RxJS) and [here](https://github.com/petehunt/minimongo-cache) (Minimongo).

**Comment by sompylasar** [comment]
Have a look at this one: https://github.com/optimizely/nuclear-js

**Comment by vjpr** [comment]
Flummox is now deprecated in favour of Redux.

**Comment by melvin0008** [comment]
[Evolution of Flux](https://medium.com/@dan_abramov/the-evolution-of-flux-frameworks-6c16ad26bb31) Great article

**Comment by coryhouse** [comment]
@koistya Can you please add these two to your list? (and thanks for the excellent compilation!)

https://github.com/optimizely/nuclear-js
https://github.com/gaearon/redux

**Comment by hipertracker** [comment]
Flummox is replaced by Redux.

**Comment by luqin** [comment]
How about [redux](https://github.com/gaearon/redux) ?

**Comment by goatslacker** [comment]
Just in case no one has mentioned it, redux?

**Comment by ericdfields** [comment]
@hipertracker how does redux "replace" flummox, exactly? Seems like they have two very different approaches.

**Comment by hipertracker** [comment]
@ericdfields "Flummox 4.0 will likely be the last major release. Use Redux instead."

**Comment by ericdfields** [comment]
@hipertracker oh, right there in the readme. 

i'm an animal.

**Comment by luandro** [comment]
Redux seems to be the clear winner

**Comment by Dindaleon** [comment]
Can someone please tell me what this is:
https://github.com/elierotenberg/react-nexus
Does it have anything to do with flux? What can I use it for?
I am leaning towards using redux.

**Comment by iMoses** [comment]
Can I get some pros and cons from someone who used redux for a large scale / complicated project?

**Comment by AlexGalays** [comment]
Small and straight-to-the-point implementation:   https://github.com/AlexGalays/fluxx

**Comment by AdamBrodzinski** [comment]
> What a wonderful example of the paradox of choice!
>No wonder that it's easier to get started with Meteor + React, than with Flux + React.

I think it's worth mentioning that ***flux doesn't replace Meteor***. In fact Meteor doesn't have *any* built in architecture to keep yourself from getting buried in a game of 'whack a mole' when changing large codebases. I did write [a spec](https://forums.meteor.com/t/flux-for-meteor-using-blaze-or-react-would-like-your-design-opinions/6651) for something based on flux to solve this (using Blaze) but that's off topic. 

However i've used Meteor + flux + React to have a pretty nice workflow with  @goatslacker 's Alt. This gives you Relay type benefits while still using flux. In this context, Alt's snapshots are handy because you can snap the state before a hot code reload and bootstrap on re-load. It also makes it easy to track mongo cursors and update the store on change. Alt seems to be one of the best choices so far with Meteor. I've used it in a large Meteor prod app and it's working great.

If interested I have a leaderboard repo with Meteor + Alt/Reflux + React:
https://github.com/AdamBrodzinski/meteor-flux-leaderboard

**Comment by jaraquistain** [comment]
Looks like Redux has replaced MartyJS too:

http://martyjs.org/blog/2015/08/02/marty-last.html

**Comment by jhabdas** [comment]
**Isomorphic Flux example:**
**Stack:** React Native Starter Kit, Alt, Iso, Firebase

https://github.com/jhabdas/lumpenradio-com/blob/ea00ec7d542e7251b88e27572c48ca95f8e2c745/src/server.js#L41-L49

![wlpn-com-proto-navigation](https://cloud.githubusercontent.com/assets/440298/10523933/98b4cafa-7342-11e5-85da-7e4966aea6a8.gif)

**Comment by Bartekus** [comment]
Any ideas as to the best way to wrap whole application state with Provider as per Redux requirement?
I tried to inject Provider into src/app.js into the ReactDOM.render but I'm getting Unhandled promise rejection ReferenceError: React is not defined tho webpack is bundling without a hitch and not reporting any error. 

This is what I've done: 
![redux-wrap](https://cloud.githubusercontent.com/assets/7887446/11174573/a32c93e0-8bda-11e5-9a34-0830fcfcfa40.png)

**Comment by sompylasar** [comment]
@Bartekus 
> ReferenceError: React is not defined

That's because any JSX expression (`<Provider ...>...</Provider>` in your case) is transformed to [React.createElement()](https://facebook.github.io/react/docs/top-level-api.html#react.createelement) under the hood.

> I've circled the addition

That's what you get after JSX:
```#!js
ReactDOM.render(
  React.createElement(
    /*string/ReactClass type*/ Provider,
    /*[object props]*/ { store: store },
    /*[children ...]*/ {
      component: component,
      appContainer: appContainer,
      () => {
        // ...
      }
    }
  )
)
```

Is this what you expected to get?

> Any ideas as to the best way to wrap whole application state with Provider as per Redux requirement?

https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/client.js#L37

**Comment by Bartekus** [comment]
@sompylasar 
Oh damn, I'm so thick, thank you for pointing the problem out and for the possible solution! 
I guess in case of react-starter-kit direct, conversion to redux aint going to be as smooth as I was hoping it to be lol but erikras' example is the best yet so let's see if I can bend react-starter-kit to redux will... 

On a side note I'm kinda surprised nobody has converted this kit to redux yet, considering it's part of WebStorm and it now being used in real, high-end development.

**Comment by petermoresi** [comment]
https://github.com/fluxury/fluxury

**Comment by ryanez** [comment]
This is quite simple to use,

https://www.npmjs.com/package/fluxtore

https://github.com/ryanez/fluxtore

**Comment by jhabdas** [comment]
What flux? http://github.com/hellyeahllc/exim

**Comment by paulmillr** [comment]
:smirk_cat:

**Comment by vedmant** [comment]
I personally use Alt, tried Redx and I didn't like switch statements, constants, too much boilerplate as for me.

**Comment by cusspvz** [comment]
@koistya could you please fix the typo **depricated** to **deprecated** ?

**Comment by Oliboy50** [comment]
redux please :)

**Comment by vedmant** [comment]
Switched to redux finally, it's easier when App grows I need to change and access data from different stores, it's easier when it's all single store.

**Comment by Dindaleon** [comment]
Here we are using redux, the best of them all: github.com/Dindaleon/hapi-react-starter-kit

**Comment by heks** [comment]
Does anyone have a fork of this kit with redux implemented?

**Comment by jhabdas** [comment]
@heks if not, you should be able to cobble one together using one or more of these: http://habd.as/awesome-react-boilerplates/

**Comment by koistya** [comment]
I'm going to close this one as it's not a real issue or feature request. But feel free to continue the conversation on this thread. You're also welcome to participate in discussions on [Gitter](https://gitter.im/kriasoft/react-starter-kit), [Appear.in](https://appear.in/react), or [StackOverflow](https://stackoverflow.com/tags/react-starter-kit).

**Comment by rdewolff** [comment]
Redux rocks :)

**Comment by rstormsf** [comment]
mobx? https://github.com/mobxjs/mobx

**Comment by jhabdas** [comment]
It's gaining mindshare. Haven't used it myself yet. I'd personally love to explore something a little less clever than Redux. The amount of boilerplate one has to write with Redux, middleware you have to use (i.e. thunk, saga, whathaveyou) can quickly lead to a mind numbing amount of analysis paralysis. That said just pick something and go with it, learn from your mistakes and get better next time. There is and will never be a "correct" answer to this infinite thread.

**Comment by rstormsf** [comment]
@jhabdas 100% agree. I'm really tired seeing so many new JS things these days. RxJS, cycle, NG2.0, etc, etc. Besides that, we have to be able to stay productive and GSD.

**Comment by xgqfrms-GitHub** [comment]
# react's family!

react & redux & react-redux & redux-thunk/redux-saga

**Comment by jhabdas** [comment]
Preact FTW! Wait, no. Inferno. Wait... ::thump::

**Comment by valera-rozuvan** [comment]
Simpler redux alternative - dynamo.Js
http://www.medsquared.com.au/blog/simpler-redux-alternative-dynamojs/

**Comment by jhabdas** [comment]
Thanks for sharing @valera-rozuvan. I worked with Redux and React for 6 months at the Enterprise level and constantly felt myself wasting time trying to create simple interfaces. ⭐️ added

**Comment by langpavel** [comment]
Apollo and Redux or Relay modern or everything else in this order.
Why? 
Because of future.

**Comment by jhabdas** [comment]
But probably not [this Apollo](https://github.com/ApolloAuto/apollo). Or [this one](https://github.com/chrislgarry/Apollo-11).

**Comment by valera-rozuvan** [comment]
@langpavel Do you mean Apollo from this project https://github.com/apollographql/react-apollo ?

**Comment by petermoresi** [comment]
I use this one.

https://www.npmjs.com/package/fluxury

**Comment by langpavel** [comment]
@valera-rozuvan Yeah, this one; https://www.apollographql.com/docs/react/
