### ISSUE TITLE
field name of action type is different in location.js

### ISSUE THREAD

**Issue by lehneres** [kriasoft/react-starter-kit#222]
in most cases
````
Dispatcher.dispatch( {
            actionType: ActionTypes.ACTION,
            somepayload
        } );
````
is used. In location,.js
````
Dispatcher.dispatch( {
            type: ActionTypes.CHANGE_LOCATION,
            somepayload
        } );
````
is used. I think this could be simplified to `actionType` such that every `dispatch` recieves the same pattern.

PS: I'm sorry that I can not create a PR by myself at the moment

**Comment by nodegin** [comment]
Actually you can also create FooTypes.ACTION_FOO or BazTypes.FOO_BAZ
It's not limited to ActionTypes, indeed, it just an example

**Comment by lehneres** [comment]
well this issue is not about the `ActionTypes.FOO`, of course... Its about the naming of the arguments given to the dispatcher. And yes, of course, you could name the anyway you want, but for consistency, I would suggest to keep them uniform...

**Comment by koistya** [comment]
@lehneres I'm not sure I understand, how are you suggesting to pass arguments to the dispatcher?

**Comment by lehneres** [comment]
no ;) Its not a big issue at all. I just stumbled over the naming of the `actionType` field in the dispatch payload, which is `actionType` in most places and `type` in the `Location.js`

**Comment by koistya** [comment]
@lehneres I can't find any `actionType` occurrences:

https://github.com/kriasoft/react-starter-kit/search?utf8=%E2%9C%93&q=actionType

**Comment by lehneres** [comment]
oh. really? Than I did introduce this discrepancy by myself... sorry for the disturbance....
