### ISSUE TITLE
css hashing? 

### ISSUE THREAD

**Issue by raptoria** [kriasoft/react-starter-kit#225]
Is there any way to 'turn on' hashing for CSS classes in the webpack config, or does this concept not exist in PostCSS?

I tried this...to no avail 

	var cssLoader = options.minimize ? "css-loader?module" : "css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader";
	var stylesheetLoaders = {
		"css": cssLoader,
		"less": [cssLoader, "less-loader"],
		"styl": [cssLoader, "stylus-loader"],
		"scss|sass": [cssLoader, "sass-loader"]

ps. just checked out your latest code, I had a small bit of trouble resolving modules because Link was lower cased, but the one you referred to was upper cased. Otherwise, everything works great.

**Comment by koistya** [comment]
@raptoria I'm planning on adding `css-loader?module` thing but didn't have time to handle it yet in the starter kit. Will try to implement it in the near future.

**Comment by raptoria** [comment]
awesome, can't wait!
