### ISSUE TITLE
Title not working on server side

### ISSUE THREAD

**Issue by vitaminwater** [kriasoft/react-starter-kit#226]
There is a typo in [index.html](https://github.com/kriasoft/react-starter-kit/blob/master/src/templates/index.html#L6)

`<title><%- title %></title>`

instead of:

`<title><%= title %></title>`

notice the '=' instead of '-'

But the title still doesn't show up in the generated content.
##

**Comment by rodolfo2488** [comment]
I think it uses https://lodash.com/docs#template 

```
// using the "interpolate" delimiter to create a compiled template
var compiled = _.template('hello <%= user %>!');
compiled({ 'user': 'fred' });
// → 'hello fred!'

// using the HTML "escape" delimiter to escape data property values
var compiled = _.template('<b><%- value %></b>');
compiled({ 'value': '<script>' });
// → '<b>&lt;script&gt;</b>'
```

**Comment by vitaminwater** [comment]
Well that's is strange then because in [index.html](https://github.com/kriasoft/react-starter-kit/blob/master/src/templates/index.html) it uses the `<%= %>` way of doing.

**Comment by vitaminwater** [comment]
oups, hadnt read carefully.

anyway the title bug is not related the "typo".

any idea why it is not showing up in the html generated by the server ?

I'm just calling:

`this.context.onSetTitle('zilia.fr - Ajoutez votre annonce gratuitement');`

in `componentDidMount` in a classe with the `withContext` decorator.

**Comment by koistya** [comment]
@vitaminwater `componentDidMount()` is never called on the server (during server-side rendering). You may want to use `componentWillMount()` instead.

**Comment by vitaminwater** [comment]
Still not working:(

**Comment by rodolfo2488** [comment]
can you paste your class here?

**Comment by vitaminwater** [comment]
After deploying on my server, it works.

I'm building on this server with `npm run build -- release` and run with `forever restart build/server.js`

So looks like the bug is only when running with `npm start`

**Comment by aayler** [comment]
I have the same issue, but with the call to this.context.onSetTitle( this.props.title ) in render(). The title reads 'undefined' but I've specified a title in the jade template.

@vitaminwater : can you please share how you called the method in your component? I tried the run build and forever combination that you mentioned but without success ...

**Comment by ulani** [comment]
@vitaminwater   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
