### ISSUE TITLE
babel-node --eval "require('./tools/start')().catch(err => console.log(err.stack))

### ISSUE THREAD

**Issue by busla** [kriasoft/react-starter-kit#231]
Getting this error on `$ npm start`

Using Node v0.12.7

```
react-starter git:(master) npm start

> @ start /Users/nonni/Code/react-starter
> babel-node --eval "require('./tools/start')().catch(err => console.log(err.stack))"

/Users/nonni/Code/react-starter/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:104
      throw err;
            ^
SyntaxError: /Users/nonni/package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (/Users/nonni/Code/react-starter/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:100:62)
    at OptionManager.findConfigs (/Users/nonni/Code/react-starter/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/Users/nonni/Code/react-starter/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/nonni/Code/react-starter/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/nonni/Code/react-starter/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/nonni/Code/react-starter/node_modules/babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at _eval (/Users/nonni/Code/react-starter/node_modules/babel/lib/_babel-node.js:78:16)
    at Object.<anonymous> (/Users/nonni/Code/react-starter/node_modules/babel/lib/_babel-node.js:106:16)
    at Module._compile (module.js:460:26)

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node --eval "require('./tools/start')().catch(err => console.log(err.stack))"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node --eval "require('./tools/start')().catch(err => console.log(err.stack))"'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --eval "require('./tools/start')().catch(err => console.log(err.stack))"
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nonni/Code/react-starter/npm-debug.log
```

**Comment by chentaixu** [comment]
That is wierd... Is this reacter kit fresh-new? I really couldn't tell what caused the error. It seems that your npm run start is executed correctly...

**Comment by busla** [comment]
Yes, cloned it just now.

**Comment by chentaixu** [comment]
Try this: npm run build
Then see if any error gets thrown

**Comment by busla** [comment]
yes, I get the same error.

**Comment by chentaixu** [comment]
Ok, I've cloned it just now and it does not throw any error. My voodoo programming skill suggests me to suggest you to upgrade your npm... My is running on npm@2.13.5. Maybe that is what caused the program. Aslo, delete the node_modules folder and run npm install again...

**Comment by chentaixu** [comment]
It should be an npm issue... It seems that the npm server is experiencing some turbulence... My first trail installing the npm modules stuck at certain place and I had to ^+c, delete and install again.

**Comment by busla** [comment]
Ok, thanks a million for looking into this on a saturday morning :-) What a support!

The latest osx Node installer comes with npm v2.11.3 and node 0.12.7

Upgraded npm to v2.14.0

Deleted node_modules -> npm install -> no profit
Cloned repo again -> npm install -> no profit

Must be NPM, all my yeoman generators are failing :-/

**Comment by chentaixu** [comment]
Once again my voodoo spirit triumphs again! Hope you get this issue solved soon : )

**Comment by busla** [comment]
@chentaixu what version of Node are you running?

**Comment by chentaixu** [comment]
@busla I've updated my to v2.14.0, too. It is still working find. I am using Ubuntu Gnome 15.04. Have you checked your global npm settings? And try cleaning the npm cache, too: https://docs.npmjs.com/cli/cache

**Comment by busla** [comment]
wait, why the hell is it trying to reference package.json in my home dir?

`SyntaxError: /Users/nonni/package.json: Error while parsing JSON - Unexpected end of input`

**Comment by busla** [comment]
ok, I found an empty package.json file in my home directiory that was messing things up :-)

Deleted it and everything is running as expected.

**Comment by chentaixu** [comment]
oh damn
