### ISSUE TITLE
how to integration fluxible 

### ISSUE THREAD

**Issue by lycandjava** [kriasoft/react-starter-kit#234]
in the server.js ，I found a defined as this：
  const context = {
      onInsertCss: value => css.push(value),
      onSetTitle: value => data.title = value,
      onSetMeta: (key, value) => data[key] = value,
      onPageNotFound: () => statusCode = 404,
      getStore:(sotre) => sotre = wiserApp.getComponent().getStore(sotre)
  };

but in fluxible context is a keywords ,so I think they are have some conflict. who can shared your integration experience? thank you

**Comment by tarkanlar** [comment]
Hey @lycandjava you can check this out https://github.com/FOUfashion/frontend

**Comment by lycandjava** [comment]
Hey @tarkanlar   ,could you tell me which version you used  about  kriasoft/react-starter-kit ?

**Comment by tarkanlar** [comment]
Actually, this is not mine @aluxian made this so i am not sure which version was it.

**Comment by Aluxian** [comment]
Hey @lycandjava, I made that (https://github.com/FOUfashion/frontend). It is based on this commit (https://github.com/kriasoft/react-starter-kit/commit/ed1ea9e6c18863a3077d837e0df6b979b403505c).

**Comment by lycandjava** [comment]
thank you very much for everyone !
