### ISSUE TITLE
Dependency issue with postcss-nested

### ISSUE THREAD

**Issue by RanzQ** [kriasoft/react-starter-kit#236]
I ran into a weird problem when using nested CSS... Can be reproduced by adding a simple nested div into `ContentPage.css`:

```
.ContentPage-container {
  margin: 0 auto;
  padding: 0 0 40px;
  max-width: var(--max-content-width);

  div {
    color: black;
  }

}
```

And I get this error:

```
Your current PostCSS version is 4.1.16, but postcss-nested uses 5.0.2. Perhaps this is the source of the error below.
Child
    Time: 7207ms

    ERROR in ./~/css-loader!./~/postcss-loader!./src/components/ContentPage/ContentPage.css
    Module build failed: TypeError: Cannot set property 'semicolon' of undefined
        at processRule (/home/ranzq/workspace/react-starter-kit/node_modules/postcss-nested/index.js:64:29)
        at /home/ranzq/workspace/react-starter-kit/node_modules/postcss-nested/index.js:80:17
```

These packages install version 4.1.16 of PostCSS: `autoprefixer-core, css-loader, cssnext, postcss-loader`.

I'm not sure which of the packages cause this error.
##

**Comment by koistya** [comment]
`postcss-loader` needs to be updated, but some of the postcss plugins have not yet switched to the new PostCSS 5.0 API.. I guess we need to wait a couple of days

**Comment by Benvorth** [comment]
have the same issue...

**Comment by airen** [comment]
have the same issue for postcss-write-svg

```
Your current PostCSS version is 4.1.16, but postcss-write-svg uses 5.0.10. Perhaps this is the source of the error below.

events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function
  
```

**Comment by ChezFre** [comment]
I had the same problem, but by going in my package.json and changing the 'grunt-postcss' version to '*' and then running 'npm install grunt-postcss --save-dev' my postcss version was updated to 0.7.1 (coming from 0.4.something) and now it's working fine again.

**Comment by ulani** [comment]
@RanzQ   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
