### ISSUE TITLE
API auto-reload

### ISSUE THREAD

**Issue by MyBoon** [kriasoft/react-starter-kit#237]
Is there a way to make the API reloads on files change? I don't know if I missed something or what but right now I have to **npm start** all the time ...

**Comment by koistya** [comment]
The `tools/serve.js` script needs to be updated by adding `if (global.WATCH) { gaze('build/server.js, () => { /* restart */ }); }` line, which would restart the server right after `build/server.js` file is changed. See how it was done in the previous version of the starter kit (didn't have time to port it yet): [gulpfile.babel.js#L115-L137](https://github.com/kriasoft/react-starter-kit/blob/c882f383dc0f1f9316e4a45499abe9fd33ab02e0/gulpfile.babel.js#L115-L137)

**Comment by MyBoon** [comment]
Thanks for your answer @koistya!
I tried something similar (with watch instead of gaze tho) but without success.

My main problem is that the `build/server.js` *never* change ...

**Comment by MyBoon** [comment]
Found it. Please look at #238 :)

**Comment by rstormsf** [comment]
nodemon?

**Comment by jacobwgillespie** [comment]
For anybody else who finds this issue and wants something to copy-paste, this is what I've got in `tools/serve.js` to enable auto-reloading:

```javascript
import path from 'path';
import cp from 'child_process';
import watch from './lib/watch';

/**
 * Launches Node.js/Express web server in a separate (forked) process.
 */
export default () => new Promise(async (resolve, reject) => {
  console.log('serve');

  const start = () => {
    const server = cp.fork(path.join(__dirname, '../build/server.js'), {
      env: Object.assign({ NODE_ENV: 'development' }, process.env)
    });

    server.once('message', message => {
      if (message.match(/^online$/)) {
        resolve();
      }
    });
    server.once('error', err => reject(err));
    process.on('exit', () => server.kill('SIGTERM'));
    return server;
  };

  let server = start();

  if (global.WATCH) {
    const watcher = await watch('build/server.js');

    watcher.on('changed', async () => {
      server.kill('SIGTERM');
      server = start();
    });
  }
});
```
