### ISSUE TITLE
API demo

### ISSUE THREAD

**Issue by vko-online** [kriasoft/react-starter-kit#243]
How to make an API file that can handle external requests?
There is already a file called `src/api/content.js` 
I want to make a module that will handle all my http requests to _http://api.example.com_ (Sails api server)
Any demo would be great

Also found this, what is that `WEBSITE_HOSTNAME`, can i use it as external api URL?

`````` js
const getUrl = path => path.startsWith('http') ?
  path : ExecutionEnvironment.canUseDOM ? path :
    process.env.WEBSITE_HOSTNAME ?
      `http://${process.env.WEBSITE_HOSTNAME}${path}` :
      `http://127.0.0.1:${global.server.get('port')}${path}`;```

``````

**Comment by koistya** [comment]
FYI, the `WEBSITE_HOSTNAME` is only available when you deploy your site to [Azure Web Apps](http://azure.microsoft.com/en-us/services/app-service/web/). It is used to replace requests such as `/api/content` to `https://<app-name>.azurewebsites.net/api/content` to make those request work server-side during server-side rendering.

You may want to update this logic to prepend your SailsJS REST API endpoint / hostname.

**Comment by frob** [comment]
I asked a similar question in the gitter irc channel. This was the response:

@frob You can create new files in the api folder and then register them in server.js
a basic example would have an api/account.js

```
import { Router } from 'express';
import http from 'superagent';
import Api from '../constants/Api';
const router = new Router();
router.get('/', (req, res1) => {
http.post(Api.UPDATE_URL).query(req.query).end((err, res) => {
res1.send({response: res});
});
});
```

export default router;

```
 import { Router } from 'express';
import http from 'superagent';
import Api from '../constants/Api';

const router = new Router();

router.get('/', (req, res1) => {
  http.post(Api.UPDATE_URL).query(req.query).end((err, res) => {
    res1.send({response: res});
  });
});
```

export default router;
and in server.js you register it

```
 //
// Register API middleware
// -----------------------------------------------------------------------------
server.use('/api/account', require('./api/account'));
```

**Comment by ulani** [comment]
@vko-online   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
