### ISSUE TITLE
Add fbjs to jest mock ignored modules to fix unit testing

### ISSUE THREAD

**Issue by thenikso** [kriasoft/react-starter-kit#255]
I was trying to run `npm test` with a test like `MyModule/__tests__/MyModule-test.js`:

```
jest.dontMock('../MyModule.js');
var React = require('react');
...
```

And it was failing until I modified `package.json` like this:

```
"jest": {
    "rootDir": "./src",
    "scriptPreprocessor": "../preprocessor.js",
    "unmockedModulePathPatterns": ["react", "fbjs"]
  },
```

Adding `"fbjs"` to the unmocked module patterns.

**Comment by koistya** [comment]
Thanks for the report! Fixed in 26668a7f685fdae17f8a95663b99b66ac260e8c2
