### ISSUE TITLE
Error  babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"

### ISSUE THREAD

**Issue by marekdano** [kriasoft/react-starter-kit#256]
Getting this error on $ npm start

    0 info it worked if it ends with ok
    1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
    1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'start' ]
    2 info using npm@2.10.1
    3 info using node@v0.12.4
    4 verbose run-script [ 'prestart', 'start', 'poststart' ]
    5 info prestart @
    6 info start @
    7 verbose unsafe-perm in lifecycle true
    8 info @ Failed to exec start script
    9 verbose stack Error: @ start: `babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"`
    9 verbose stack Exit status 1
    9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
    9 verbose stack     at EventEmitter.emit (events.js:110:17)
    9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
    9 verbose stack     at ChildProcess.emit (events.js:110:17)
    9 verbose stack     at maybeClose (child_process.js:1015:16)
    9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    10 verbose pkgid @
    11 verbose cwd C:\Users\Marek\react-starter-kit
    12 error Windows_NT 6.3.9600
    13 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
    14 error node v0.12.4
    15 error npm  v2.10.1
    16 error code ELIFECYCLE
    17 error @ start: `babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"`
    17 error Exit status 1
    18 error Failed at the @ start script 'babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"'.
    18 error This is most likely a problem with the  package,
    18 error not with npm itself.
    18 error Tell the author that this fails on your system:
    18 error     babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"
    18 error You can get their info via:
    18 error     npm owner ls
    18 error There is likely additional logging output above.
    19 verbose exit [ 1, true ]

**Comment by brandon-arnold** [comment]
Not sure why these issues are being ignored. Fixed in PR #272. Add a line to your package.json in the meantime:

```javascript
    "babel-core": "^5.4.0",
```
