### ISSUE TITLE
Materialize Css Integration

### ISSUE THREAD

**Issue by tapas4java** [kriasoft/react-starter-kit#259]
How to integrate materialize css with this starter kit? 
Where all third party vendor js and css files are getting added?

**Comment by koistya** [comment]
`/src/components/App` - is a root component which is used on all other pages. You can include 3rd party CSS into it like this:

##### `src/components/App/App.css`
```css
@import '.../../../node_modules/materialize-css/dist/css/materialize.css';
```

**Comment by tapas4java** [comment]
What about materialize.js?

Do i need to change something for fonts?

**Comment by koistya** [comment]
You can try to reference both `jquery.js` and `materialize.js` in `src/templates/index.html` in the `<head>` section:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.14/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
```

**Comment by tapas4java** [comment]
Thanks a lot @koistya!

It worked when I added both CSS and JS in index.html. Just curious about to understand how other libraries are bundled in this starter kit?

**Comment by patrickgordon** [comment]
I'd love a solution to this other than adding the files to the index.html. Anyone able to point me in the right direction? When I do what @koistya said on Sep 19th I get a bunch of errors:

```
ERROR in ./src/components/App/App.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../font/material-design-icons/Material-Design-Icons.eot in /Users/patrickgordon/sites/small-frontend/src/components/App
 @ ./src/components/App/App.css 6:66432-66498
```

Etc.

**Comment by zomco** [comment]
@patrickgordon  `postcss-url` may help you #179

**Comment by prampey** [comment]
I import _materialize-css_ styles into my react component like this: `import sm from 'materialize-css/bin/materialize.css'`
This way I can selectively apply styles to my components without worrying about polluted global CSS namespace or overriding global CSS styles.
