### ISSUE TITLE
Error while trying to run Jest tests

### ISSUE THREAD

**Issue by aabakumovs** [kriasoft/react-starter-kit#264]
Hi. 
I am using jest-cli v0.5.4 and iojs v3.3.1. When I am trying to test my react components I get this error: 

**Error: Invariant Violation: The style-loader must be configured with reference-counted API.**

The components are using withStyles.
##

**Comment by joshchandler** [comment]
Have you run the tests using a different version of io.js?  Is there a need a specific need for it to be on v3.3.1?

**Comment by aabakumovs** [comment]
I have tried it with 3.3.0 , 2.5.0 and 2.0.0 still the same result. I think it's not an iojs problem.

**Comment by ncthis** [comment]
The preprocessor drops all the css files from being transformed for jest tests. Therefore, jest doesn't know that the `use` and `unuse` needed for the referenced-counted API needs to be mocked.

My solution: mock the css require.

So, you would have your component and the decorator unmocked:

```js
jest.dontMock('./FooFile.js');
jest.dontMock('../../decorators/withStyles.js');
```

and then you'll have to mock the css file

```js
jest.setMock('./FooFile.css', {use: function noop() {}, unuse: function noop() {}});
```

@aabakumovs, Hope this helps you.

**Comment by aabakumovs** [comment]
@ncthis when I use your example I get the error 

**Super expression must either be null or a function, not undefined**

**Comment by alexlrobertson** [comment]
@aabakumovs and @ncthis I'm getting the same error.

**Comment by ncthis** [comment]
@aabakumovs @alexlrobertson Check your decorators in the unmocked files. If you already have a valid `super()` in the constructor, there should be something wrong with the decorator.

**Comment by jooj123** [comment]
To get around this issue I have turned automocking off and im also using the `babel-plugin-remove-decorators` plugin. 

I can do a simple unit test like this now:

```
jest.autoMockOff();
jest.dontMock('../RiskAssessment');
jest.mock('../../../core/Location');
jest.mock('../../Link');
jest.mock('../../TitlePanel/TitlePanel');

import React from 'react';
import ReactDOM from 'react-dom';
import TestUtils from 'react-addons-test-utils';

describe('RiskAssessment', () => {
  it('displays the risk assessment', () => {

    var RiskAssessment = require('../RiskAssessment');

    const shallowRenderer = TestUtils.createRenderer();
    shallowRenderer.render(<RiskAssessment />);
    var result = shallowRenderer.getRenderOutput();

    expect(result.type).toBe('div');
  });
});
```

**Comment by ulani** [comment]
@aabakumovs   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
