### ISSUE TITLE
Error at npm start @withStyles 

### ISSUE THREAD

**Issue by hyptos** [kriasoft/react-starter-kit#279]
Hi I got this weird error after creating a repository with react-starter-kit and then running for the second time (first time it worked) npm run build.

I got this error : 
![screenshot from 2015-10-12 09 47 13](https://cloud.githubusercontent.com/assets/1622722/10423718/974a66e6-70c9-11e5-9303-8e75dc247314.png)

**Comment by hyptos** [comment]
that's weird on my mac, it run smoothly and I get this weird error on my other laptop. I have this repository https://github.com/hyptos/checkJobs

And All I did was npm install && npm run build && npm start

**Comment by koistya** [comment]
Do you have `.babelrc` file in the root directory of your project? It says Babel to use `stage 0`, alternatively you can add ?stage=0 parameter to the babel-loader in webpack config file (`tools/config.js`).

**Comment by hyptos** [comment]
Nice exactly this :o Why does it need it ?

**Comment by rodolfo2488** [comment]
decorators are part of ES7 and still in experimental stage.

**Comment by hyptos** [comment]
Ok thanks :)
