### ISSUE TITLE
npm install get stuck

### ISSUE THREAD

**Issue by fenos** [kriasoft/react-starter-kit#280]
Hi guys, my colleague has installed this package in his windows machine successfully. 
I wanted to do the same and start playing around with it. I just cloned the repo as usual and run `npm install` in my Mac machine with the following node and npm versions.

Node: `4.0.0`
Npm: `3.3.6`

The packages seem to be installed correctly but it get stuck here:

![screen shot 2015-10-13 at 17 46 02](https://cloud.githubusercontent.com/assets/4754064/10461757/e26952ae-71d2-11e5-8df0-38731cbdfacc.png)

After 40 minute that i leave it at that stage I decided to kill the process and try to do `npm start`

giving the following error:

![screen shot 2015-10-13 at 17 52 00](https://cloud.githubusercontent.com/assets/4754064/10461817/2592ae7c-71d3-11e5-8143-b56d420d1caa.png)

I'm not sure what i'm missing, if I have some dependency not installed globally (not sure about) any help would be appreciated

**Comment by maysale01** [comment]
You don't need to run npm with sudo, either way, any issues with npm install are going to be either network/machine related and not issues with the repository.

From the image provided, it looks like you didn't have missing modules, more so you have an @import statement in `ContactPage.css` for `../features`. That should probably be `../features.css`?

**Comment by kascote** [comment]
The problem seems related to PostCSS / caniuse-api modules. I fixed it doing:

    cd node_modules/postcss-cssnext/node_modules/caniuse-api
    node generator.js

That will genenerate the required __features.js__ file
