### ISSUE TITLE
Uncaught TypeError: Cannot read property 'props' of null

### ISSUE THREAD

**Issue by martin-jujou-sirca** [kriasoft/react-starter-kit#281]
This change:
https://github.com/kriasoft/react-starter-kit/pull/275

has seemed to affected on handleClick action now, seems like I get:
`Uncaught TypeError: Cannot read property 'props' of null`
error in the console each time I click on a link. 

Changing back to format:
`static handleClick = event => {`
seems to fix the issue.

**Comment by koistya** [comment]
Fixed in 989918622ee2811847cdc8d78fdf11fa4e4b7381

**Comment by martin-jujou-sirca** [comment]
Thanks koistya!
