### ISSUE TITLE
i18n integration

### ISSUE THREAD

**Issue by hamczu** [kriasoft/react-starter-kit#282]
Has anyone tried to integrate any i18n library i.e. react-intl?
Or is there any plan to make i18n a part of this repo?

**Comment by maysale01** [comment]
Seems trivial to implement in the `Html` component or in `routes.js` and not core to React. I guess it depends on @koistya's preference. I think this would be more suited for a react hackathon starter kit.

**Comment by arvigeus** [comment]
This issue can be closed - implementation is available in [feature:reat-intl](https://github.com/kriasoft/react-starter-kit/tree/feature/react-intl)
