### ISSUE TITLE
react-intl

### ISSUE THREAD

**Issue by andreasi** [kriasoft/react-starter-kit#291]
Hi! Any idea on how to implement internationalization - localization using yahoo's react-intl library with react-starter-kit.
Thanks

**Comment by zkirill** [comment]
They just released 2.0.0-beta-1 which supports ES6 but the docs aren't there yet. Check it out!

**Comment by arvigeus** [comment]
This issue can be closed - implementation is available in [feature:reat-intl](https://github.com/kriasoft/react-starter-kit/tree/feature/react-intl)
