### ISSUE TITLE
Which module bundler should I use?

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#3]
#### [Browserify](http://browserify.org)
[![img](https://img.shields.io/npm/dm/browserify.svg?style=flat-square)](https://www.npmjs.com/package/browserify) [![img](https://img.shields.io/github/issues-raw/substack/node-browserify.svg?style=flat-square)](https://github.com/substack/node-browserify/issues) [![img](https://img.shields.io/github/stars/substack/node-browserify.svg?style=flat-square)](https://github.com/substack/node-browserify) [![img](https://img.shields.io/github/forks/substack/node-browserify.svg?style=flat-square)](https://github.com/substack/node-browserify)
[![npm](https://nodei.co/npm/browserify.png)](https://www.npmjs.com/package/browserify)
[![npm](https://nodei.co/npm-dl/browserify.png?months=12&height=3)](https://www.npmjs.com/package/browserify)
[![img](https://img.shields.io/npm/dm/babelify.svg?style=flat-square)](https://www.npmjs.com/package/babelify)
[![npm](https://nodei.co/npm-dl/babelify.png?months=12&height=3)](https://www.npmjs.com/package/babelify)

Who's using **React.js** with **Browserify**?

 * KhanAcademy.org
 * AirBnb.com
 * SoundCloud.com

#### [Webpack](http://webpack.github.io/)
[![img](https://img.shields.io/npm/dm/webpack.svg?style=flat-square)](https://www.npmjs.com/package/webpack) [![img](https://img.shields.io/github/issues-raw/webpack/webpack.svg?style=flat-square)](https://github.com/webpack/webpack/issues) [![img](https://img.shields.io/github/stars/webpack/webpack.svg?style=flat-square)](https://github.com/webpack/webpack) [![img](https://img.shields.io/github/forks/webpack/webpack.svg?style=flat-square)](https://github.com/webpack/webpack)
[![npm](https://nodei.co/npm/webpack.png)](https://www.npmjs.com/package/webpack)
[![npm](https://nodei.co/npm-dl/webpack.png?months=12&height=3)](https://www.npmjs.com/package/webpack)
[![img](https://img.shields.io/npm/dm/babel-loader.svg?style=flat-square)](https://www.npmjs.com/package/babel-loader)
[![npm](https://nodei.co/npm-dl/babel-loader.png?months=12&height=3)](https://www.npmjs.com/package/babel-loader)

Who's using **React.js** with **Webpack**?

 * Instagram.com

#### Good Read

* [Browserify for Webpack users](https://gist.github.com/substack/68f8d502be42d5cd4942)
* [Browserify Handbook](https://github.com/substack/browserify-handbook)
* [Webpack How-to](https://github.com/petehunt/webpack-howto)

**Comment by radum** [comment]
@sloria You can do everything you said with browserify also, and when does one need to require a CSS file in his javascript file or an image?

It's like JSX, it worked and made sense for them (FB) doesn't mean it will work for everyone else.

I think both are great, so you might as well chose the one you like and stick with it. I personally us browserify because I started with this one and it has a big ecosystem.

**Comment by mauriyouth** [comment]
+webpack, you can have multiple entry point so you can split your js bundles, and load the necessary only when you needs them.

**Comment by koistya** [comment]
@mauriyouth does it differ from what you can do with Browserify and [factor-bundle](https://www.npmjs.com/package/factor-bundle)?

**Comment by AveVlad** [comment]
:+1: webpack

**Comment by hekar** [comment]
+1 webpack

**Comment by amit242** [comment]
Do I need Webpack or Browserify if I'm already using gulp? I'm trying to understand if I need any of these 2 if I'm using the react-starter-kit.

**Comment by Sunil6591** [comment]
can somebody point me to some samples for using browserify with react?
Thanks in advance

**Comment by cosminnicula** [comment]
What do you think about JSPM?

**Comment by blackxored** [comment]
+1 for jspm, not even a mention? :sob:

**Comment by koistya** [comment]
I'm going to close this one as it's not a real issue or feature request. But feel free to continue the conversation on this thread. You're also welcome to participate in discussions on [Gitter](https://gitter.im/kriasoft/react-starter-kit), [Appear.in](https://appear.in/react), or [StackOverflow](https://stackoverflow.com/tags/react-starter-kit).
