### ISSUE TITLE
accessing app when URL has a sub-path/prefix breaks a number of things

### ISSUE THREAD

**Issue by mkaminsky** [kriasoft/react-starter-kit#30]
I've been playing around with your starter kit, which I really like--thank you--but I ran into a snag when trying to serve the app from a subdirectory on my webserver.  Essentially, what I did was:
```
//  build app as per your README
cp -a build ~/public_html/MyApp
//  point browser at  http://webserver/~username/MyApp
```
and several things don't seem to work.

First, there seems to be a built-in assumption that the app is rooted at ``/``, such that the browser can't find ``/images/logo-small.png`` and the Links at the bottom of the page to ``/`` and ``/privacy`` don't work.

Second, javascript, at least to some extent, doesn't seem to be running.

An easy way to reproduce is as follows.  Add the following line somewhere in the render() function of Index.jsx
```
<button onClick={function() { console.log("test")}}>Test</button>
```
and build the app as usual (``gulp build``).

To see a working version (clicking button prints "test" to console):
```
cd build
python -m SimpleHTTPServer
//  point browser at  http://localhost:8000/
```
To see the broken setup (nothing shows up in console):
```
cd ..     // i.e., go back to top level MyApp directory
python -m SimpleHTTPServer
//  point browser at  http://localhost:8000/build/
```

Note that although I happened to use a button in this example. Even just adding a ``console.log()`` call to the beginning of the render() function (before the return) doesn't show anything on page load when the URL has ``/build/`` in it.

Thanks again.

**Comment by langpavel** [comment]
This is really old issue without reactions.
Feel free to reopen it if you think it may be useful for someone.
