### ISSUE TITLE
Get socket error when using https

### ISSUE THREAD

**Issue by zkirill** [kriasoft/react-starter-kit#303]
Getting this error for https://localhost:5000/ when using self-signed certificates.

``` bash
Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at Socket.socketOnEnd (_http_client.js:288:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

Interestingly this URL resolves correctly: https://localhost:5000/api/content?path=about

Modifications to server.js to support https

``` javascript
var options = {
  key: fs.readFileSync('server.key'),
  cert: fs.readFileSync('server.crt'),
  ca: fs.readFileSync('ca.crt'),
  requestCert: false,
  rejectUnauthorized: false
};

https.createServer(options, server).listen(port);
```

Not sure but maybe this is related http://stackoverflow.com/a/23637556.
##

**Comment by zkirill** [comment]
Issue seems to be resolved with the following:

src/server.js
```javascript
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```

src/core/HttpClient.js

> Replace `http` to `https` as shown below.

```javascript
  return process.env.WEBSITE_HOSTNAME ?
    `https://${process.env.WEBSITE_HOSTNAME}${path}` :
    `https://127.0.0.1:${global.server.get('port')}${path}`;
```

**Allowing unauthorized certificates presents security problems in production so only do this for development environment when using self-signed certificates.** I assume that we can use `process.env.NODE_ENV` to check whether we should do this.

**Comment by ulani** [comment]
@zkirill   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
