### ISSUE TITLE
Build gets pretty big

### ISSUE THREAD

**Issue by codeorelse** [kriasoft/react-starter-kit#306]
Hi, 

When I build the react-starter-kit without any adjustments, the client app.js is over 280KB. I think this is quite huge, especially when using it in a mobile app. What are your thoughts on this? What can we do to optimise it?

Cheers!
##

**Comment by ChrisCinelli** [comment]
React with add ons alone is 140Kb

**Comment by codeorelse** [comment]
When we serve the JS gzipped, it's getting very acceptable :). But still I think 140KB on top of the 140KB (React+addons) is quite a lot..

**Comment by doug-orchard** [comment]
Any big eCommerce site on a mobile phone will be a minimum 250kb in .js files. That's not considering extra external scripts and the monolithic CSS files they force you to download. To me, this is a trade off. No one said isomorphic sites were slim, or any site using a framework of any kind.
Anyway, that's my two-cents.

**Comment by koistya** [comment]
To reduce this file size, you may want to use [code splitting](https://webpack.github.io/docs/code-splitting.html), making sure that only the code which is actually is going to be used on the page is loaded at the initial load.

**Comment by Bogdaan** [comment]
Anyone have example with code-splitting ?

**Comment by alotov-agina** [comment]
I just downloaded the boilerplate and did an `npm run build`. 
The main.js in build/public is 3.33 MB in file-size. For real? Or am I doing something wrong here?

**Comment by codeorelse** [comment]
@alatov-agina: the production build is a lot smaller.
'''npm run build -- --production'''

**Comment by Bogdaan** [comment]
Note that build includes CSS, you can make it even faster and less with:

1. code-splitting (https://github.com/webpack/webpack/tree/master/examples/code-splitting)

2. plugins
transform-react-remove-prop-types
transform-react-constant-elements
transform-react-inline-elements

3. use NODE_ENV=production

**Comment by alotov-agina** [comment]
Thank you guys!

**Comment by ulani** [comment]
@codeorelse  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
