### ISSUE TITLE
Any help / turorials on how the router works in this specific kit?

### ISSUE THREAD

**Issue by AlastairTaft** [kriasoft/react-starter-kit#308]
It seems to be that the router in this project isn't configured the same standard way all the tutorials and documentation out there do.

e.g. server.js uses a dispatch event, I can't find any sample code elsewhere that uses this method, even in the API docs for react-router.

```js
server.get('*', async (req, res, next) => {
    ...

    await Router.dispatch({ path: req.path, context }, (state, component) => {
      data.body = ReactDOM.renderToString(component);
      data.css = css.join('');
    });

    const html = ReactDOM.renderToStaticMarkup(<Html {...data} />);
    res.status(statusCode).send('<!doctype html>\n' + html);

  ...
});
```

I'm trying to configure the router to load routes lazily in a similar way to [this example project](https://github.com/rackt/react-router/tree/master/examples/huge-apps).

In that huge-apps example code you can asynchonouly chose which routes to load in a route config

```js
module.exports = {
  path: 'course/:courseId',

  getChildRoutes(location, cb) {
    require.ensure([], (require) => {
      cb(null, [
        require('./routes/Announcements'),
        require('./routes/Assignments'),
        require('./routes/Grades')
      ])
    })
  },

  ...
}
```

I can't figure out how to apply the same thing to the way routing is done in this starter kit, anyone got similar experiences or can share their knowledge?
##

**Comment by AlastairTaft** [comment]
Just realised this starter kit uses `react-routing` not `react-router`, why not use the second one? It's got more weight behind it, or what's the difference?

**Comment by AlastairTaft** [comment]
I couldn't get the router to do what I needed to do, I was after some [dynamic routing](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/DynamicRouting.md) so I'm trying to convert over to using the `react-router`.

I feel like I'm ripping the guts of this starter kit out now, I've learnt a hell of a lot about react using it, so thanks. As a newbie though the router was a particular point of confusion for me while learning, so I kind of glossed over it in the beginning. 

For anyone else looking at this kit as a newbie it's worth pointing out what I've learnt
  
  - You won't be able to use those `willTransitionTo` methods you'll find all over Google, that's related to `react-router`. I hacked in redirects with `window.location.href =` to get something working. 
  - You'll lose the benefits of only re-rendering a small portion of the page when changing paths. From what I can tell react-router uses a `history` repo that doesn't actually do a callback to the server to change your url, instead it keeps track of your history and renders only the html that changes (makes things look super slick to your users).
  - This starter kit has to do a postback to update the css (not that I have figured out a better way of doing it yet)

**Comment by franklinjavier** [comment]
+1

**Comment by kottameister** [comment]
:+1: @AlastairTaft I'm trying the same thing, so keep us updated if you get this kit to work with react-router.

**Comment by AlastairTaft** [comment]
I did do, I'll try and summarise and strip down my files so you can make use of them. There's three main files I had to change, app.js, server.js and routes.js. You'll probably have to edit them a bit to get them to work, but the jist of it is there (bare in mind this is a work in progress).

routes.js
```
import React from 'react';
import { Router, Route, IndexRoute } from 'react-router'

const routes = 
  <Route path="/" component={App}>
    <IndexRoute onEnter={redirectToLogin} component={LandingPage} />
    <Route path="callback" component={ CallbackRedirect } />
    <Route path="panel" component={ ControlPanel }>
      <Route path="content" component={ ContentOverview } />
      <Route path="site-type-selection" component={ SiteTypeSelection } />
      <Route path="create" component={ CreateContent } />
      <Route path="site-settings" component={ SiteSettings } />
      <Route path="edit/:contentId" component={ EditContent } />
    </Route>
  </Route>

export default routes
```

I heavily stripped out the server.js and app.js just to get something working for now, might still be some dead code I haven't gone through it properly yet.

With the new server.js file you won't be able to use the decorators `@withContext` and `@withStyles`, this is because it requires a post back to update the css which defeats a lot of the benefits of `react-router`. For my solution I converted all css to inline styles as pointed out [here](https://speakerdeck.com/vjeux/react-css-in-js), you may find a different way to do it. If you need to do media queries a good alternative is to use the `@withViewport` decorator that already exists, then in your render method check `this.props.viewport.width`. See [here](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md) for more info on server routing.

server.js
```
server.get('*', async (req, res, next) => {
  try {
    const context = {
      jwt: req.session.jwt
    };

    match({ routes, location: req.url }, (error, redirectLocation, renderProps) => {
      if (error) {
        res.status(500).send(error.message)
      } else if (redirectLocation) {
        res.redirect(302, redirectLocation.pathname + redirectLocation.search)
      } else if (renderProps) {
        var content = renderToString(
          <Html 
            body={renderToString(<AuthRoutingContext jwt={req.session.jwt} {...renderProps} />)} 
            css=""
          />
        )
        res.status(200).send(content)
      } else {
        res.status(404).send('Not found')
      }
    })

  } catch (err) {
    next(err);
  }
});
```

I'm using a jwt token for my user authentication so I like having this readily available in the context. To do this I had to extend the react-router `RoutingContext` class and add it in. You can skip this if you don't want a context and just use the default `RoutingContext` class in your server.js file instead. There's probably an easier way of doing this.

AuthRoutingContext.js
```
import React, { PropTypes, Component } from 'react'
import {RoutingContext} from 'react-router'

export default class AuthRoutingContext extends RoutingContext {
  static propTypes = {
    jwt: React.PropTypes.string
  }

  static childContextTypes = {
    history: React.PropTypes.object.isRequired,
    location: React.PropTypes.object.isRequired,
    jwt: React.PropTypes.string
  }

  getChildContext() {
    const { history, location, jwt } = this.props
    return { history, location, jwt }
  }
}
```

For the app.js I actually used the same method as the server.js, even though [the documentation encourages you not to](https://github.com/rackt/react-router/blob/master/docs/API.md#matchlocation-cb), so there's probably a better way of doing it, however I couldn't find a way using the normal method to include my `jwt` token in the context.

app.js
```
/*! React Starter Kit | MIT License | http://www.reactstarterkit.com/ */

import 'babel-core/polyfill';
import React from 'react'
import { render } from 'react-dom'
import FastClick from 'fastclick';
import {Router, match} from 'react-router'
import routes from './routes';
import Location from './core/Location';
import { addEventListener, removeEventListener } from './utils/DOMUtils';
import AuthRoutingContext from './components/AuthRoutingContext'

import injectTapEventPlugin from 'react-tap-event-plugin'
injectTapEventPlugin()

let cssContainer = document.getElementById('css');
const appContainer = document.getElementById('app');

function run() {
  let currentLocation = null;
  let currentState = null;

  // Make taps on links and buttons work fast on mobiles
  FastClick.attach(document.body);

  match({ routes, location: window.location.pathname }, (error, redirectLocation, renderProps) => {
    if (error) {
      throw error
      //res.status(500).send(error.message)
    } else if (redirectLocation) {
      throw new Error('Redirect not handled')
      //res.redirect(302, redirectLocation.pathname + redirectLocation.search)
    } else if (renderProps) {
      //console.log(require('util').inspect(renderProps))
      render(<AuthRoutingContext jwt={localStorage.getItem('jwt')} {...renderProps} />, appContainer) 
    } else {
      throw new Error('Not found')
    }
  })

}

// Run the application when both DOM is ready
// and page content is loaded
if (window.addEventListener) {
  window.addEventListener('DOMContentLoaded', run);
} else {
  window.attachEvent('onload', run);
}
```
 
Apologies for not piecing it together nicely but you might find some of the concepts of use. And I'm open to ideas if anyones got better ways of doing things.

**Comment by pukhalski** [comment]
Thanks, @AlastairTaft, I guess, the replacement of `react-routing` with `react-router` should be the next natural step for this kit.

**Comment by zhiyelee** [comment]
@AlastairTaft Thanks. Do you have a fork version of this kit?

**Comment by AlastairTaft** [comment]
@zhiyelee Not at the moment sorry

**Comment by N8-B** [comment]
If you're interested in a starter boilerplate for a universal web app that uses React Router I recommend checking out ![react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example).

**Comment by zhiyelee** [comment]
thanks @N8-B

**Comment by subodh-malgonde** [comment]
Can someone help summarize the benefits of using react-routing over react-router? The (website)[http://www.kriasoft.com/react-routing/] has no docs. Its very difficult to get started if you are a beginner.

**Comment by andrewmclagan** [comment]
bump why are we not suing react-router? can we get some info or should we go ahead with a PR?

**Comment by jshultz** [comment]
Seconding this bump. the biggest frustration to using this kit is that it isn't using react-router and the documentation for the router is does use is fairly lacking. otherwise, it's a great project. 

It seems at one time it did use react-router and it was replaced with react-routing. Not sure why, but a strong vote from me to go back to react-router.

**Comment by k00k** [comment]
:+1:  +1 Agreed, seems like the majority (the noisy majority anyway) are in favor of moving to react-router.

**Comment by jshultz** [comment]
Rabble rabble!



On Thursday, January 7, 2016, Steve Babigian <notifications@github.com>
wrote:

> [image: :+1:] +1 Agreed, seems like the majority (the noisy majority
> anyway) are in favor of moving to react-router.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kriasoft/react-starter-kit/issues/308#issuecomment-169783699>
> .
>


-- 
Sent from Gmail Mobile

**Comment by xugy0926** [comment]
+1

**Comment by jeroenransijn** [comment]
+1. Would love to see a way to transition from using the current router to `react-router` also. Even if it's not yet part of the framework.

**Comment by pickingausername** [comment]
@AlastairTaft 
Can you help about issue(discussion) #430 ? i would really appreciate that.
Thanks for this awesome post.

+1

**Comment by mika75** [comment]
@AlastairTaft , I see you use 

import injectTapEventPlugin from 'react-tap-event-plugin'
injectTapEventPlugin()

on client side. 
does it works on mobile ?  

Thansk

**Comment by kenjim83** [comment]
+1

**Comment by koistya** [comment]
Here is a demo (sandbox) project that demonstrates how the router works and some of its use cases:

https://github.com/koistya/demos/tree/master/functional-react-routes

**Comment by joenot443** [comment]
From what I can tell, the author of this project @kriaoft, is also the author of Universal Router, which is presumably why he insists on including UR in the project instead of the superior React Router.

**Comment by frenzzy** [comment]
@joenot443 it is hard to configure React Router with stuff like Relay or render page with data fetching during server-side rendering without overhead, etc.

**Comment by langpavel** [comment]
I see no reason why keep this open :-)
