### ISSUE TITLE
Run app in Subdirectory via Apache ProxyPass

### ISSUE THREAD

**Issue by jonas-veselka** [kriasoft/react-starter-kit#310]
Hi,
I'am trying to run Your app in subdirectory using Apache ProxyPass.

```
ProxyPass /backoffice http://127.0.0.1:3000
ProxyPassReverse /backoffice http://127.0.0.1:3000
```

to be able to load page on http://mydomain.tld/backoffice
I can't use subdomain. There has to be a non-React main app on the domain root.

React started kit seems to be able to run only on domain root. When using this ProxyPass, main page is loaded correctly, but other requests are on domain root.
I changed path of `app.js` to `{publicPath+"/app.js"}` in the Html class (https://github.com/kriasoft/react-starter-kit/blob/master/src/components/Html/Html.js#L45), but there are more problems I can't solve.
For example: I added `${publicPath}` before API call in routes.js (https://github.com/kriasoft/react-starter-kit/blob/master/src/routes.js#L27), but this causes server Errors:

```
Error: socket hang up
    at createHangUpError (_http_client.js:209:15)
    at Socket.socketOnEnd (_http_client.js:294:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
```

Did I miss something? Anybody know the way to make it working?
##

**Comment by diego200052** [comment]
Me to

**Comment by diego200052** [comment]
Me too, I need help plz.

**Comment by frenzzy** [comment]
Have you tried [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) html tag? `History` and `UniversalRouter` modules also support `baseUrl` option.

**Comment by ulani** [comment]
@jonas-veselka  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
