### ISSUE TITLE
why is my state undefined  ?

### ISSUE THREAD

**Issue by hyptos** [kriasoft/react-starter-kit#314]
Hi,

You could check there : https://github.com/hyptos/checkJobs/blob/master/src/components/SearchForm/SearchForm.js

the error is : Uncaught TypeError: Cannot read property 'state' of undefined at line 24 of the file when I type something.

I'm trying to use state in order to save the query from an input text search. I saw how you did it in the chat and tried to do the same. But I don't know why it still fails.

Could you help me ?

Thanks

**Comment by koistya** [comment]
Check out this article:

http://babeljs.io/blog/2015/06/07/react-on-es6-plus/

You may want to change your `doSearch` method to:

```js
  doSearch = (event) => {
        this.setState({ query: event.target.value }};
        this.props.doSearch(query);
  };
```

**Comment by hyptos** [comment]
Ok thanks, I still don't understand why I need to use the arrow syntax in order to make the function keep state or props :/

**Comment by koistya** [comment]
Alternatively you can bind your `doSeach` function to the component instance inside the constructor:

```js
class SearchForm extends Component {

  constructor() {
    super();
    this.state = { query: '' };
    this.doSearch = this.doSearch.bind(this);
  }

  doSearch() {
    this.setState({ query: event.target.value }};
    this.props.doSearch(query);
  }

  render() {
    // ...
  }

}
```

https://facebook.github.io/react/docs/reusable-components.html#no-autobinding
