### ISSUE TITLE
Please use some test coverage

### ISSUE THREAD

**Issue by bingomanatee** [kriasoft/react-starter-kit#320]
It is difficult to use Jest; it would be good to have test coverage off the included components so we can have some confidence in the ability of Jest to work with react :D
##

**Comment by tommmyy** [comment]
+1

**Comment by jaredpalmer** [comment]
+1 or use enzyme

**Comment by sashakru** [comment]
+1

**Comment by flysonic10** [comment]
Yea, Jest doesn't seem to actually work out of the box.

**Comment by bingomanatee** [comment]
what I have found is that Jasmine can test general components -- straight unit tests -- but the Jest stuff is just not friendly.

**Comment by Stupidism** [comment]
It's quite simple @bingomanatee @kriasoft
`yarn add --dev nyc`
```
"test:cover": "nyc --require babel-register mocha \"src/**/*.test.js\" --require test/setup.js",
```

**Comment by Stupidism** [comment]
https://github.com/kriasoft/react-starter-kit/pull/1213 Please review!

**Comment by visualskyrim** [comment]
@Stupidism 
Thanks for your solution.
I have tried #1213 in my project, but it seems that nyc doesn't work with [conditional rendering](https://facebook.github.io/react/docs/conditional-rendering.html).
It seems that the conditions within the conditional rendering would not be considered as multiple branches by nyc.

Is there a walk around for this issue, or conditional rendering is not a recommended way in react starter kit?

Pls tell me if you need more information.

**Comment by Stupidism** [comment]
I think the problem is `jsx` is not supported well. @visualskyrim

**Comment by Stupidism** [comment]
If you jsx support is OK. Have you tried to write in multiple lines like the demo?
```
    <div>
      {isLoggedIn ? (
        <LogoutButton onClick={this.handleLogoutClick} />
      ) : (
        <LoginButton onClick={this.handleLoginClick} />
      )}
    </div>
```

If it's not working, either. Propose an issue in repo [nyc](https://github.com/istanbuljs/nyc) or [istanbuljs](https://github.com/istanbuljs/istanbuljs)

**Comment by Stupidism** [comment]
I did a test in my own project. It seems to be working...

![image](https://cloud.githubusercontent.com/assets/5801015/24873562/29b6456c-1dd6-11e7-93aa-568f7fc3e2bb.png)

**Comment by visualskyrim** [comment]
@Stupidism 

Thanks a lot!

It's now working well on my project.
I'm still not sure why it didn't work in the first place. Sorry for the incorrect information I put above.

**Comment by ulani** [comment]
@bingomanatee   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
