### ISSUE TITLE
time to upgrade to React 0.14 and babel 6

### ISSUE THREAD

**Issue by eyasliu** [kriasoft/react-starter-kit#324]
new version react 0.14 and babel 6 was released some time. when upgrade?

**Comment by koistya** [comment]
@eyasliu there are some missing features in Babel v6.x, for example decorators don't work. Need to wait some time until these issues are resolved.

**Comment by koistya** [comment]
@eyasliu React 0.14 is up to date: https://github.com/kriasoft/react-starter-kit/blob/master/package.json#L20-L21

**Comment by eyasliu** [comment]
sorry, I was payed no attention

**Comment by mikehuebner** [comment]
Have you checked in on this? I'm willing to PR it in if you want :dancer:
