### ISSUE TITLE
How to re render component with new properties 

### ISSUE THREAD

**Issue by khawerrind** [kriasoft/react-starter-kit#338]
I am using `react-intl` and passing locales inside `routes.js`

``` javascript
var intlData = {
  locales : ['en-US']
};

const router = new Router(on => {
  on('*', async (state, next) => {
    const component = await next();
    return component && <App context={state.context} {...intlData}>{component}</App>;
  });
});
```

inside my `App` component i have `handleLocaleChange` function which should update the component with new properties. React `setProps` & `replaceProps` are deprecated and hence i can no longer use that so how to re-render the component with new props inside my `handleLocaleChange` function?

``` javascript
import React, { PropTypes, Component } from 'react';
import {IntlMixin} from 'react-intl';

const App = React.createClass({
    mixins : [IntlMixin],

    handleLocaleChange: function(e) {
        var locale = e.target.value;
        if(locale == 'en-US'){
            //switch to english
        } else {
            //switch to chinese
        }
    },

    render: function() {
        return (
            <div>
                <select onChange={this.handleLocaleChange}>
                    <option value="en-US">English</option>
                    <option value="zh-CN">Chinese</option>
                </select>
            </div>
        );
    }
});
```
##

**Comment by maysale01** [comment]
Components only render on state changes, so you need to call `setState`.

**Comment by Kepro** [comment]
why you don't use stackoverflow??? this is not a issue

**Comment by ulani** [comment]
@khawerrind  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
