### ISSUE TITLE
how to use 'react-codemirror'

### ISSUE THREAD

**Issue by xugy0926** [kriasoft/react-starter-kit#344]
i will use react-codemirror(https://github.com/JedWatson/react-codemirror)

step 1, add to package.json
<img width="222" alt="2015-12-14 11 51 35" src="https://cloud.githubusercontent.com/assets/3000884/11785666/db51abee-a2bd-11e5-9a35-3763ee40cd93.png">

step 2, use component in js

<img width="519" alt="2015-12-14 11 52 54" src="https://cloud.githubusercontent.com/assets/3000884/11785685/e5670e76-a2bd-11e5-9eef-28cee0cf507d.png">

step 3, start project...... have a error ...

i think it‘s pack error 。。how fixed it？

<img width="845" alt="2015-12-14 11 56 26" src="https://cloud.githubusercontent.com/assets/3000884/11785796/50034f1a-a2be-11e5-9edc-76d2ca309cf5.png">

**Comment by koistya** [comment]
I personally prefer using such libraries directly, e.g.

```jsx
import React from 'react';
import { canUseDOM } from 'fbjs/lib/ExecutionEnvironment';

class Editor extends Component {
  componentDidMount() {
    if (canUseDOM) {
      this.codeMirror = require('codemirror').fromTextArea(this.refs.input);
      this.codeMirror.on('change', ...); // etc.
    }
  }
  componentWillUnmount() {
    if (this.codeMirror) {
      this.codeMirror.toTextArea();
      this.codeMirror = null;
    }
  }
  render() {
    return <textarea ref="input" />;
  }
}

export default Editor;
```

**Comment by xugy0926** [comment]
@koistya thx for your help. 

about markdown editor，Do you have a good solution？

**Comment by koistya** [comment]
@xugy0926 how about:

https://github.com/thlorenz/brace
https://github.com/sofish/pen

**Comment by xugy0926** [comment]
@koistya thx!
