### ISSUE TITLE
Convert from react-routing to react-router

### ISSUE THREAD

**Issue by thehashrocket** [kriasoft/react-starter-kit#345]
Has anyone done this recently? I see that around Sept of 2014 it switched from director to react-router and now it's on react-routing. There doesn't seem to be a lot of documentation around that, furthermore, most people seem to be using react-router instead. 

Is anyone else in the same boat I am? I'd rather use something that has a bit more community around it if possible.

**Comment by dfejgelis** [comment]
+1. Same concern here.
So far reat-routing has been working ok for me, but I'm thinking on refactor to react-router every time I need something and cannot find any doc.

**Comment by yidongnan** [comment]
+1

**Comment by jerez** [comment]
+1

**Comment by ziogaschr** [comment]
+1

**Comment by audi70r** [comment]
+1

**Comment by leonprou** [comment]
Hey @koistya, react-router will be supported soon?
I wonder about the `ready` tag

**Comment by wstoettinger** [comment]
+1

**Comment by flysonic10** [comment]
+1

**Comment by putudondo** [comment]
+1

**Comment by koistya** [comment]
@leonprou `ready` means that it's on a [to-do list](https://waffle.io/kriasoft/react-starter-kit) (what's coming next).

Have anybody tried replacing the routing information inside the `src/routes.js` file with routes in RR format + modify the server-side rendering logic in `src/server.js` ([here](https://github.com/kriasoft/react-starter-kit/blob/master/src/server.js#L35-L57))? Maybe you can share your fork with work-in progress and we can collaboratively fix the remaining issues in that integration if any.

**Comment by kwelch** [comment]
I haven't started on it but I had plans on looking into this week. I was looking at going the same direction you mentioned.

**Comment by kwelch** [comment]
I started to look into this, but I wanted to share this incase someone else attempts to pick this up. 
I believe the lazy routes will be a better win for this project. 

https://medium.com/@ryanflorence/welcome-to-future-of-web-application-delivery-9750b7564d9f#.ibtn2fxh3

**Comment by Bogdaan** [comment]
@kwelch +1 lazy routes is awesome, but i have no idea how to use them with alt js / flux

**Comment by kwelch** [comment]
Agreed. It has slowed my ability to wrap this convert up.

**Comment by MathieuCh** [comment]
+1 react-router

**Comment by hamzazar** [comment]
+1

**Comment by okendoken** [comment]
+1

**Comment by okendoken** [comment]
@kwelch did you start work on that? I could try to handle it too.

**Comment by kwelch** [comment]
I did but haven't gotten far enough for someone to leverage it. Feel free
to start tackling it.

**Comment by okendoken** [comment]
Cool! Thanks for response, Then I'll provide a fork for review in next days.



Philip Daineka,
flatlogic.com

**Comment by okendoken** [comment]
Hi everyone,

I have just finished with the basic integration of react-router. PR is not ready yet as the code is still in progress https://github.com/flatlogic/react-starter-kit/commit/c31ab4f1e59271eea7ea9a41ead8f1cb5653f79d.

Open questions:
1. Passing context to components https://github.com/flatlogic/react-starter-kit/commit/c31ab4f1e59271eea7ea9a41ead8f1cb5653f79d#diff-e6a5b42b2f7a26c840607370aed5301aR43. Better way than class variables?
2. Server- and client-side markup difference:

    Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
    (client) <noscript data-reacti
    (server) <div data-reactid=".s

This seems to be connected with react/react-router lifecycles; react checks for markup consistence before react-router markup is ready

3. Preserving the scroll position. This is to be solved.

Any feedback appreciated

**Comment by puradox** [comment]
+1

**Comment by raigudakesa** [comment]
+1

**Comment by NPhi** [comment]
+1

**Comment by FakhruddinAbdi** [comment]
+1

**Comment by virusvn** [comment]
+1

**Comment by learntoswim** [comment]
+1

**Comment by leonardoelias** [comment]
+1

**Comment by anaibol** [comment]
:D

**Comment by Deepblue129** [comment]
+1

**Comment by langpavel** [comment]
I'm sorry to all of you. This is very old issue. We have universal router now. Can anyone create pull request with React-router? I promise I will maintain it as feature for some time, then we can create some comparison of pros and cons against universal-router.

**Comment by djpark** [comment]
@langpavel/@koistya - Just submitted a [PR](https://github.com/kriasoft/react-starter-kit/pull/766 ) that integrates react-router with this starter kit.  Look forward to hearing your thoughts.
