### ISSUE TITLE
Replace Superagent with WHATWG Fetch

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#346]

**Comment by subodh-malgonde** [comment]
@koistya What was the reason you did this?

**Comment by koistya** [comment]
@subodh-malgonde `fetch` is already supported natively by Chrome, Firefox and Opera; and via polyfill by other browsers as well. It has modern API and covers more use cases than what you can do with `XMLHttpRequest` (`superagent`, `jQuery.ajax` etc.). Take a look at this article:

https://jakearchibald.com/2015/thats-so-fetch/

[![image](https://cloud.githubusercontent.com/assets/197134/12215870/9c687760-b6df-11e5-8b39-e03b58cd693e.png)](http://caniuse.com/#feat=fetch)

**Comment by subodh-malgonde** [comment]
Thanks.
