### ISSUE TITLE
duplicated assets by file-loader

### ISSUE THREAD

**Issue by aunz** [kriasoft/react-starter-kit#362]
When requiring images (or anything handled by file-loader) in js files shared by client and server (e.g. in the [Header component] (https://github.com/kriasoft/react-starter-kit/blob/master/src/components/Header/Header.js)), the output asset will be duplicated in both the build and build/public directory.

This can be reproduced by changing https://github.com/kriasoft/react-starter-kit/blob/master/src/components/Header/Header.js#L25 
```js
 <img src={require('./logo-small.png')} width="38" height="38" alt="React" />

// to
 <img src={require('./largeFile.png')} ... />

```

Can this be optimised so the asset will only be in the public folder?

**Comment by Bogdaan** [comment]
see #392

**Comment by aunz** [comment]
Hi @Bogdaan, the #392 describes a different issue

**Comment by Bogdaan** [comment]
@aunz sory, wrong page
