### ISSUE TITLE
Release mode is broken on port 5000

### ISSUE THREAD

**Issue by dfrankland** [kriasoft/react-starter-kit#370]
Using `npm start -- --release` and port 5000 causes full-page reloads instead of working like a SPA.

Seems like Express is also catching all routes and returning an `<Html />` component for everything like files and unknown routes instead of throwing 404's too. For example:
* `localhost:5000/main.a9s8d7f89s7df.js` returns a fully rendered html page, not a file
* `localhost:5000/path-that-does-not-exist` returns a fully rendered html page, not a 404
* `localhost:5000/about` renders the about page, but all links reload the page instead of transitioning.

This is the commit that broke it: https://github.com/kriasoft/react-starter-kit/commit/8da2f4eee616cc295c07ab192b1de9e054f00110

**Comment by koistya** [comment]
Thanks for the report, Dylan! Checking what's wrong with that commit..

**Comment by koistya** [comment]
@dfrankland As of now, when you launch a development server (`node build/server.js` + Browsersync proxy on top of it) by running `npm start` or `npm start -- --release`, it injects HMR module into the client-side application bundle (`build/public/client.js`) and it assumes that you access the site via Browsersync's endpoint ([localhost:3000](http://localhost:3000/)). If you need to test the site without Browsersync / HMR / React Transform. You may want to start the Node.js server manually by running `npm run build -- --release && node build/server.js`.

Do you think it would be better to remove HMR / React Transofrm integration when you launch the site via `npm start -- --release`?

**Comment by dfrankland** [comment]
In my opinion `--release` should be no frills for better performance. By adding the overhead of Browsersync and opening the extra ports (read extra security vulnerability) 3000 and 3001, I believe it makes `--release` a misnomer.

HMR and React Transform are still very important even for `--release`, when needing performance and pushing updates fast. Isn't there a way for `client.js` to assume a different endpoint than `localhost:3000` when in `--release` mode?

**Comment by dfrankland** [comment]
Fixed by https://github.com/kriasoft/react-starter-kit/pull/387
