### ISSUE TITLE
use camelCase CSS class names is painful

### ISSUE THREAD

**Issue by panlilu** [kriasoft/react-starter-kit#373]
What about supporting react-css-modules?
[react-css-modules](https://github.com/gajus/react-css-modules)

I think it is much better than isomorphic-style-loader. 
##

**Comment by koistya** [comment]
You can enable dash-separated class names in CSS by adding `camelCase` or `camelCase=dashes` flag to `css-modules` loader in `tools/webpack.config.js`. E.g. `css-loader?modules&camelCase=dashes`. Does this work for you?

**Comment by DavidWells** [comment]
css-loader supports camelCase now.

See: https://github.com/ianmcnally/css-loader/commit/68f5a6975a88f6848adde45e6eeb8b000b4ef553

This worked for me:
```css-loader?modules&camelCase=dashes```

**Comment by koistya** [comment]
Note: With CSS Modules, the class names tend to be short, single-word keywords. If you want to use `lisp-case` for CSS class names, I would recommend checking with your team members if their text editors / IDEs support selecting the whole class name when you double-click on any of the words in `list-case` combinations.
