### ISSUE TITLE
How to switch from *.scss to *.sass?

### ISSUE THREAD

**Issue by vishalvijay** [kriasoft/react-starter-kit#376]
How to switch from *.scss to *.sass?
##

**Comment by ivosabev** [comment]
+1

This will let us use Bootstrap 4's sass files directly.

**Comment by dfrankland** [comment]
@ivosabev this will not let you use Bootstrap 4's sass files directly, because they don't use sass files.
https://github.com/twbs/bootstrap/tree/v4-dev/scss

**Comment by ivosabev** [comment]
Long story short (http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax), the current setup is using the css-loader which doesn't process pure .scss and I would love to see a sass-loader implementation.

**Comment by dfrankland** [comment]
The current implementation supports almost pure `.scss` using [precss](https://github.com/jonathantneal/precss). The main difference is that you cannot use css `//` comments, you instead need to use javascript `/* */` comments.

**Comment by ivosabev** [comment]
Not having // comments is a big show stopper.

**Comment by dfrankland** [comment]
@ivosabev I fixed the `//` comment issue with this pull request: https://github.com/kriasoft/react-starter-kit/pull/384/files

**Comment by ivosabev** [comment]
Awesome!

**Comment by okendoken** [comment]
@dfrankland is there any way you can share your code when you use RSK and Bootstrap 4 together?
I am in the middle of solving the same issue..

**Comment by dfrankland** [comment]
@okendoken to get Bootstrap 4 working properly with RSK you will need to swap [precss](https://github.com/jonathantneal/precss) for [scss-loader](https://github.com/jtangelder/sass-loader). Beyond comments there are other things, like includes and partials that are not properly supported with precss, so save yourself the hassle of trying to get it to be compatible and use the proper tools.

My webpack.config.js looks something like this:
...
```js
{
  test: /\.scss$/,
  loaders: [
    'isomorphic-style-loader',
    `css-loader?${DEBUG ? 'sourceMap&' : ''}modules&localIdentName=` +
    `${DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]'}`,
    'postcss-loader?pack=minimize',
    'postcss-loader?pack=polyfill',
    'sass-loader',
  ],
}
```
...
```js
postcss: () => {
  return {
    polyfill: [
      require('autoprefixer')({ browsers: AUTOPREFIXER_BROWSERS }),
    ],
    minimize: DEBUG ? [] : [
      require('cssnano')({
        autoprefixer: false,
        discardComments: { removeAll: true },
      }),
    ],
  };
},
```
...

An example of one of the `.scss` files looks something like this:
```scss
@import "~bootstrap/scss/bootstrap.scss";

.my-cool-class {
  color: $coolColor;
}
```

**Comment by ulani** [comment]
@vishalvijay   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
