### ISSUE TITLE
is this kit still flux?

### ISSUE THREAD

**Issue by nodegin** [kriasoft/react-starter-kit#382]
just notified the dispatcher have been removed, so is this kit still base on flux architecture?

**Comment by koistya** [comment]
I think it would be good to move sample Flux implementation from the boilerplate to docs / recipes section.

**Comment by Eightyplus** [comment]
I used the Dispatcher as well. @koistya what are you saying?, do you have a link to elaborate the switch?

**Comment by Eightyplus** [comment]
Fund this link: https://github.com/kriasoft/react-starter-kit/issues/22
