### ISSUE TITLE
Add react-widgets to react-starter-kit - ERROR webpack: bundle is now INVALID.

### ISSUE THREAD

**Issue by rgomezcuervo** [kriasoft/react-starter-kit#386]
Hi!
What is the way to add  react-widgets to react-starter-kit?
I made this:

npm install react-widgets
npm install less-loaders

Add below to webpack.config.js

  { test: /.less$/, loader: "style-loader!css-loader!less-loader" },
  { test: /.(ttf|eot|svg)(\?v=[0-9].[0-9].[0-9])?$/, loader: "file-loader?name=[name].[ext]" },

In the page:

import React, { Component, PropTypes } from 'react';
import withStyles from '../../decorators/withStyles';
import 'react-widgets/lib/less/react-widgets.less';
import DropdownList from 'react-widgets/lib/DropdownList';

npm run build

> babel-node tools/run build

[10:39:41] Starting 'build'...
[10:39:41] Starting 'clean'...
[10:39:41] Finished 'clean' after 22 ms
[10:39:41] Starting 'copy'...
build/package.json
[10:39:41] Finished 'copy' after 23 ms
[10:39:41] Starting 'bundle'...
Child
    Time: 5454ms
                                   Asset     Size  Chunks             Chunk Names
                          rw-widgets.eot  5.82 kB          [emitted]  
                          rw-widgets.ttf  5.64 kB          [emitted]  
                          rw-widgets.svg  2.71 kB          [emitted]  
    a770b6797b68e3f8920e473eb824bac0.gif  23.3 kB          [emitted]  
            main.js?b5f9087a3894971e3e4c  3.21 MB       0  [emitted]  main
Child
    Time: 5226ms
            Asset    Size  Chunks             Chunk Names
        server.js  209 kB       0  [emitted]  main
    server.js.map  186 kB       0  [emitted]  main
[10:39:47] Finished 'bundle' after 5492 ms
[10:39:47] Finished 'build' after 5539 ms

But, when npm start

> babel-node tools/run start

[10:39:55] Starting 'start'...
[10:39:55] Starting 'clean'...
[10:39:55] Finished 'clean' after 23 ms
[10:39:55] Starting 'bound copy'...
build/package.json
[10:39:55] Finished 'bound copy' after 139 ms
webpack built 93c0f221f830caab5475 in 6832ms
Child
    Time: 6832ms
                                   Asset     Size  Chunks             Chunk Names
                          rw-widgets.eot  5.82 kB          [emitted]  
                          rw-widgets.ttf  5.64 kB          [emitted]  
                          rw-widgets.svg  2.71 kB          [emitted]  
    a770b6797b68e3f8920e473eb824bac0.gif  23.3 kB          [emitted]  
            main.js?93c0f221f830caab5475  3.52 MB       0  [emitted]  main
Child
    Time: 6359ms
            Asset    Size  Chunks             Chunk Names
        server.js  209 kB       0  [emitted]  main
    server.js.map  186 kB       0  [emitted]  main
webpack: bundle is now VALID.
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/virtualEnvs/fronttmsenv/fronttms/build/webpack:/external "react-widgets/lib/less/react-widgets.less":1:1)
    at __webpack_require__ (/opt/virtualEnvs/fronttmsenv/fronttms/build/webpack:/webpack/bootstrap 75b29c3a756d30d53417:19:1)
    at Object.<anonymous> (/opt/virtualEnvs/fronttmsenv/fronttms/build/webpack:/src/components/LoginPage/LoginPage.js:13:33)
webpack: bundle is now INVALID.
##

**Comment by Bogdaan** [comment]
@rgomezcuervo hi, this code is incorrect:

```
import 'react-widgets/lib/less/react-widgets.less';
import DropdownList from 'react-widgets/lib/DropdownList';
```

This kit use isomorphic-style-loader for class names. 
react-widgets uses **global css**. 

It means that you have two options:
1. make fork of react widgets and upgrade it to css-modules 
2. make component-wrappers for each widget, and load styles with not unique global class names

**Comment by rgomezcuervo** [comment]
Hi @Bogdaan, Thanks!! 
I will review that!!

**Comment by na57** [comment]
@Bogdaan hi. I've got the same problem with @rgomezcuervo .
I guess what you said can help me, but I can not understand about your options.
Could you tell me more about those two options so that I can solve the problem?
I hope you can help me.
Thanks a lot.

**Comment by ulani** [comment]
@rgomezcuervo   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Comment by ulani** [comment]
@rgomezcuervo   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
