### ISSUE TITLE
Why are there static properties on ES6 classes?

### ISSUE THREAD

**Issue by ianwalter** [kriasoft/react-starter-kit#388]
I have to commend the authors for the outstanding amount of effort that has been put into this, but I keep seeing bits of code like this:

```js
class Link extends Component {

  static propTypes = {
    to: PropTypes.string.isRequired,
    query: PropTypes.object,
    state: PropTypes.object,
    onClick: PropTypes.func,
  };
// ...
```

ES6 classes do not have static properties, only static functions. Even React's docs do not use ES6 classes this way: https://facebook.github.io/react/docs/reusable-components.html#es6-classes

Am I missing something or can I submit a pull request?

**Comment by dfrankland** [comment]
This kit is ES6+ that's why the static properties are there although they are ES7. It's all transpilied into ES5 with babel.js; you can see their article explaining using ES6+ with React here: http://babeljs.io/blog/2015/06/07/react-on-es6-plus/

**Comment by ianwalter** [comment]
Ah it all makes sense now, thanks for your time @dfrankland.
