### ISSUE TITLE
Why not use `isomorphic-fetch`?

### ISSUE THREAD

**Issue by dfrankland** [kriasoft/react-starter-kit#391]
Seems like [RSK has its own version](https://github.com/kriasoft/react-starter-kit/tree/master/src/core/fetch) of [`isomorphic-fetch`](https://www.npmjs.com/package/isomorphic-fetch) so why not just use that package?

**Comment by koistya** [comment]
@dfrankland basically it's just the same, with a custom version it's easier to plug your own functionality in it, e.g. prefix all the relative URLs with `http://localhost:${port}` during server side rendering and add context-aware functionality to make it work smoothly with server-side rendering.
