### ISSUE TITLE
Where to put commonly shared images?

### ISSUE THREAD

**Issue by vishalvijay** [kriasoft/react-starter-kit#392]
Currently when develop using react starter kit I add images in `images` folder which is inside a  component.

```
├──/src
│   ├──/components
│   │   ├──/AComponent
│   │   │   ├──/AComponent.js
│   │   │   ├──/AComponent.scss
│   │   │   ├──/images
│   │   │   │   ├──/abc.png
│   │   │   │   ├──/xyz.png
│   │   ├──/BComponent
│   │   │   ├──/BComponent.js
│   │   │   ├──/BComponent.scss
│   │   │   ├──/images
│   │   │   │   ├──/xyz.png
```
And I use `require("./images/abc.png")` in Javascript and `url("./images/abc.png")` in scss.

Here I'm duplicating `xyz.png` image in both the folder. I want to keep this images in a common folder. 

What is the best way to do that?

**Comment by koistya** [comment]
Does creating a separate React component for it make sense in your case? For example, you may have the same icon used in different places; you can create an `Icon` component, which may contain multiple SVG icons in it and use it like this: `<Icon type="back" /> <Icon type="home" />`.

**Comment by vishalvijay** [comment]
This is a great Idea. I'll follow this.

I though of creating a folder in `src` called `images` and accessing it using `../../../images/xyz.png`, **Will this work?**

**Comment by koistya** [comment]
@vishalvijay yep, that should work. Though it might be a better idea to prefer having shared components, as opposed to shared resources whenever possible.

**Comment by vishalvijay** [comment]
Ok I got it.

But `<Icon/>` component idea won't work when I have to access the image in css, right?

**Comment by koistya** [comment]
You may want to extract both images and CSS which are used in multiple places into a stand-alone component.

**Comment by vishalvijay** [comment]
Ok
