### ISSUE TITLE
How to start in Debug Mode for Starter Kit

### ISSUE THREAD

**Issue by manodupont** [kriasoft/react-starter-kit#396]
I was trying to debug and found myself stuck in somewhere pretty strange ...

I just replaces this line by the other line in package.json

``` javascript
"start": "babel-node tools/run start"
```

to 

``` javascript
"start": "babel-node --debug tools/run start"
```

which, as expected, just launchin the server in debug node.

``` javascript
/usr/local/bin/npm run-script start

> @ start /Users/manueldupont/react-starter-kit
> babel-node --debug tools/run start

Debugger listening on port 5858
[14:51:24] Starting 'start'...
[14:51:24] Starting 'clean'...
```

But why, when I launch node-inspector and puts some breakpoints, it never stop. Like never. No matter where I put my breakpoints (i.e in api/content.js:35) on the

``` javascript
router.get('/', async (req, res, next) => {
  try {
    const path = req.query.path;
```
##

**Comment by buritos** [comment]
@manodupont it is because the application runs in a child process.

https://github.com/kriasoft/react-starter-kit/blob/master/tools/runServer.js#L43

Adding ```execArgv: ['--debug']``` as on option to ```spawn``` will enable debugging of the child process.

**Comment by timothyerwin** [comment]
try using this -- working great for me!

https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.ftvoeb786

**Comment by quyetvv** [comment]
Does someone know how to make debug work with babel-node at the moment? I can not start debugging event if I add --debug/--inspect in the commands:
babel-node --debug tools/run start

Moreover, from the official site, babel-node is not recommended? Why is it applied to this kit?
https://babeljs.io/docs/usage/cli/#babel-node

**Comment by ucay** [comment]
> Moreover, from the official site, babel-node is not recommended? Why is it applied to this kit?
> https://babeljs.io/docs/usage/cli/#babel-node

It's clear, babel-node(babel-cli) isn't recommended **for production**. But in this kit, babel-node is used **only for development**. Just look at `package.json `, there are `dependencies` (production) and `devDependencies` (development).

**Comment by joenot443** [comment]
@quyetvv I'm having the same issue at the moment. Did you ever find a solution? Or has anyone else found success in using `--debug` to debug the server?

**Comment by quyetvv** [comment]
@joenot443 
At last I install babel-node and add this command to package.json
"debug": "babel-node tools/run start --inspect"
Then call: npm run debug to debug from chrome.
You can see it from here:
https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

**Comment by ulani** [comment]
@manodupont   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
