### ISSUE TITLE
Implement server-side rendering

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#4]
Server / middleware libraries to consider if you're using [Node.js](nodejs.org) on the server:

 * [Express](http://expressjs.com/)<br />
   [![NPM](https://nodei.co/npm-dl/express.png?months=12)](https://nodei.co/npm/express/)
 * [koa](http://koajs.com/)<br />
   [![NPM](https://nodei.co/npm-dl/koa.png?months=12)](https://nodei.co/npm/koa/)
 * [hapi](http://hapijs.com/)<br />
   [![NPM](https://nodei.co/npm-dl/hapi.png?months=12)](https://nodei.co/npm/hapi/)

Approaches to consider when you don't use Node.js:

 * For each incoming HTTP request run the server-side bundle via Google's [V8](https://code.google.com/p/v8/) egnine, then send the resulting string to the client.

**Comment by wouterAA** [comment]
+1

**Comment by koistya** [comment]
What do you think about implementing server-side rendering with Node.js/Express, something similar to this: https://github.com/koistya/react-recipes/blob/master/server-side-rendering-with-nodejs-express.md

**Comment by yrokhlin** [comment]
@koistya that would be lovely actually.

**Comment by goatslacker** [comment]
+1 we can also take a look at [koa](https://github.com/koajs/koa) or [hapijs](http://hapijs.com/).

**Comment by koistya** [comment]
I have updated `webpack` configuration so that it should now generate both client-side (`./build/app.js`) and server-side (`./build/server.js`) bundles. The server-side bundle can be used for server-side rendering and there is no need to worry about any transforms that could be missing if you would use original source files on the server.

@goatslacker and all, what do you think?
