### ISSUE TITLE
Outdated Packages

### ISSUE THREAD

**Issue by ankitduseja** [kriasoft/react-starter-kit#401]
I just tried to setup and found these packages are outdated as of today:
Package                       Current  Wanted       Latest
babel                          5.8.34  5.8.34       6.3.26  
babel-core                     5.8.34  5.8.34        6.4.0  
babel-eslint                    4.1.6   4.1.6  5.0.0-beta6  
babel-loader                    5.4.0   5.4.0        6.2.1  
babel-plugin-react-transform    1.1.1   1.1.1        2.0.0  
classnames                      2.2.1   2.2.1        2.2.3  
eslint-config-airbnb            2.1.1   2.1.1        3.1.0  
fbjs                            0.5.1   0.5.1        0.6.1  
front-matter                    2.0.1   2.0.1        2.0.5  
history                        1.16.0  1.16.0    2.0.0-rc2  
lodash.merge                    3.3.2   3.3.2        4.0.1  
react                          0.14.3  0.14.3       0.14.6  
react-dom                      0.14.3  0.14.3       0.14.6  
react-routing                   0.0.6   0.0.6        0.0.7

**Comment by Bogdaan** [comment]
@ankitduseja hi, 
babel6 related to #343
for others - can you create PR with tested actual packages?

**Comment by romancsandl** [comment]
so far everything but
    "babel-core": "5.8.34"
    "babel": "^5.8.34",
    "babel-eslint": "^4.1.6",
    "babel-loader": "^5.4.0",
    "babel-plugin-react-transform": "^1.1.1",
    "lodash.merge": "^3.3.2",
should be upgradeable

**Comment by koistya** [comment]
:+1: all the packages are up to date now on `master`
