### ISSUE TITLE
What's about `react-helmet` instead of context functions insertCss, onSetTitle, etc.

### ISSUE THREAD

**Issue by nodkz** [kriasoft/react-starter-kit#412]
Kostya, what do you think about changing the context's functions (`insertCss`, `onSetTitle`, `onSetMeta`) in `App` component to https://github.com/nfl/react-helmet

Pros
- well documented and covered with tests package
- used in code like React component
- no need in context variables
- encode html special characters for title and attributes
- title chain

Cons
- +1 package
- may be it will became more complicated for newbie 

NB It is not clear, what to do with `onPageNotFound `. May be it should be in `public` folder with name `404.html`. Also add `500.html`. It is good practise to not generate this files (serve it as simple html files).

**Comment by arvigeus** [comment]
Indeed looks much cleaner!

**Comment by AwesomeJerry** [comment]
any news on react-helmet? looking for a way to manage meta og tag.

**Comment by AwesomeJerry** [comment]
just made a PR. Please see if it helps.
https://github.com/kriasoft/react-starter-kit/pull/688

**Comment by langpavel** [comment]
This have been moved into router which is much more deterministic and cleaner
