### ISSUE TITLE
"createHref is deprecated warning" on start

### ISSUE THREAD

**Issue by damienfa** [kriasoft/react-starter-kit#416]
I just come to install this "react-starter-kit". An `npm install` followed by an `npm start`, and I've got a lot of : 
`Warning: the query argument to createHref is deprecated; use a location descriptor instead`
(on Terminal and in the Chrome console on http://localhost:3000/ )

Does anybody has an idea from where it comes ?

**Comment by damienfa** [comment]
In `package.json`, pasing `history` to version 1.17.0 instead of 1.16.0 seems to resolve the problem.
Just check here : https://github.com/rackt/history/blob/master/CHANGES.md (they have just fixed bugs between those two versions, so I don't really worry about any regression).
It has worked well for me !

**Comment by koistya** [comment]
@damienfa I think this is fixed in PR #343, which needs a little bit more testing / feedback before merging to master.

**Comment by damienfa** [comment]
ha. Sorry then.
