### ISSUE TITLE
how does client.js work?

### ISSUE THREAD

**Issue by panezhang** [kriasoft/react-starter-kit#419]
Found your project a great starter kit, but I did not get the point what client.js is used for? or where to use it?

**Comment by frenzzy** [comment]
`client.js` is the entry point for the client side - running on the browser
as `server.js` is the entry point for the server-side - running on the server
they both use the same React.js components (universal or isomorphic javascript)

**Comment by koistya** [comment]
There are two JavaScript apps in the project - client-side app that runs in a browser and Node.js/Express app that runs on the server. Each app needs to have an entry point, in case with the client-side app, it's `src/client.js` and the entry point for Node.js app is `src/server.js`.

These two files are being passed to Webpack bundler (see `tools/webpack.config.js`), which is responsible for building dependency trees for each of these entry files, and creating two bundles - `build/server.js` for the server and `build/public/main.js` for browsers (or, `build/public/main.04eb5e6426edc50ac434.js` in production/release mode). The `build` folder is not under the source control, it's created on the fly when you run either `npm run build`, or `npm start` command. You're supposed to run/test your app by launching it from the `build` folder. That's handled automatically when you run `npm start` (or, `npm run start -- --release`) command.

@panezhang try to run either `npm run build` or `npm run build -- --release` commands and check the generated `build/public/main.js` file, which should contain all the client-side code and other assets such as CSS and small images.

**Comment by panezhang** [comment]
@frenzzy @koistya thanks a lot.

**Comment by kalim-bms** [comment]
@koistya Thanks for explaining the SSR in depth.
