### ISSUE TITLE
Can't find the  main.js file in build folder after npm run build . But it's loading in browser.

### ISSUE THREAD

**Issue by pickingausername** [kriasoft/react-starter-kit#427]

**Comment by koistya** [comment]
In release mode, this file is being saved into memory by `webpack-middleware`, if you run `npm start -- --release`, it should be saved into the `build` folder.

**Comment by pickingausername** [comment]
Thanks for the reply.
Even after npm start -- --release there is no main.js file.
In build folder there is a assets.js file which exports the main.js file.
module.exports = {"main":{"js":"/main.7e3187658062e94cfad8.js"}};
But there is no main.js? or main?.js file.

**Comment by pickingausername** [comment]
Do i need to change webpack.config file?

**Comment by nss213** [comment]
apparently you need to use `npm run build -- --release` to get the `main.<HASH>.js` file. I'm assuming `npm start` is still using the in-memory version.

**Comment by pickingausername** [comment]
I ran the command npm run build -- --release but there is no main.js file in build folder.
Child
    Time: 7997ms
                           Asset    Size  Chunks             Chunk Names
    main.43ed41ef32cb66610227.js  270 kB       0  [emitted]  main
Child
    Time: 4842ms
            Asset    Size  Chunks             Chunk Names
        server.js  150 kB       0  [emitted]  main
    server.js.map  140 kB       0  [emitted]  main
there are server.js and server.js.map  but no main.js file in build folder.

**Comment by pickingausername** [comment]
In release mode, there is  assets.js file which exports main.js file but i can't see any main.[hash].js file

**Comment by nss213** [comment]
It's in build/public since it's a file that will be served up to the client.

**Comment by pickingausername** [comment]
Thanx nss213 :+1:

**Comment by mde17** [comment]
still not working,
