### ISSUE TITLE
React-bootstrap

### ISSUE THREAD

**Issue by pickingausername** [kriasoft/react-starter-kit#428]
How can i use react-botstrap with components in this RSK src folder  structure?

**Comment by nss213** [comment]
`npm install --save react-bootstrap`

include the bootstrap css files however you want. Lazy (maybe sloppy) way is just including them in Html.js

in your file:
`import Button from 'react-bootstrap/lib/Button';`

in your render method, just use `<Button {...buttonProps} />`

**Comment by pickingausername** [comment]
:+1:

**Comment by pickingausername** [comment]
How i add a custom class name in a component?
When i do <Navbar fixedTop inverse className={s.navbar}> it produces 
<nav class="Navigation_navbar_20N navbar navbar-inverse navbar-fixed-top" >
it gives custom class name first why?

**Comment by pickingausername** [comment]
How do i add a custom class name in component to use css with react-bootstrap class included?

`<Navbar fixedTop inverse className={s.navbar}>`  in Navcomponent.js 

gives 

`<nav class="Navigation_navbar_20N navbar navbar-inverse navbar-fixed-top"   data-reactid=".1ovq1r9dbeo.0.0">` in html. 
But that's not anyone wants.
