### ISSUE TITLE
Page transitions

### ISSUE THREAD

**Issue by subodh-malgonde** [kriasoft/react-starter-kit#434]
Any pointers on how to go about doing simple slide-in/slide-out transitions on url/component changes?
##

**Comment by Bogdaan** [comment]
@subodh-malgonde
I think it is possible only in conjunction with react-router
You can see https://github.com/reactjs/react-router/tree/master/examples/animations

**Comment by dfrankland** [comment]
@Bogdaan that's not the only way, React has an addon for animations: https://facebook.github.io/react/docs/animation.html

**Comment by Bogdaan** [comment]
@dfrankland Of course I know ReactCSSTransitionGroup, but can you provide working example with react-routing (https://github.com/kriasoft/react-routing)?

**Comment by dfrankland** [comment]
This really has nothing to do with [`react-routing`](https://github.com/kriasoft/react-routing). For a quick overview of one way to do it:

1. Add a method to the [`context` object inside `client.js`](https://github.com/kriasoft/react-starter-kit/blob/master/src/client.js#L19) to get the `window.location`.
2. Check for the `window.location` using the new method inside of `this.props.context` in the [`render` method of the `App` component](https://github.com/kriasoft/react-starter-kit/blob/master/src/components/App/App.js#L55) and pass it as a prop to its children.
3. Inside the component you want to add the animation to, use the [`componentWillReceiveProps`](https://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops) method to check if the URL changed and then use [ReactCSSTransitionGroup](https://facebook.github.io/react/docs/animation.html) to animate the rendering of the component.

**Comment by Bogdaan** [comment]
@dfrankland "Inside the component you want to add the animation to"
as far as I understand, this issue about animation between the different routes.
For example when i click on link (or change url in address) from "/a" to "/b".
Your approach is to change the code of all the components?

**Comment by dfrankland** [comment]
By passing props to child components you may pick and choose which components you want to update based on a change in the route, you do not have to change anything, but the components you plan to animate.

**Comment by ulani** [comment]
@subodh-malgonde   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
