### ISSUE TITLE
npm start / hot reload gets stuck in loop

### ISSUE THREAD

**Issue by erichardson30** [kriasoft/react-starter-kit#436]
This issue is occuring sometimes when I run npm start and ALWAYS when I make a change, save the file, and it reloads. It goes through the normal startup process and then just loops continuously. My console output looks like : 
PS C:\Users\Documents\react-starter-kit\react-sample-demo\react-starter> n

> @ start C:\Users\Documents\react-starter-kit\react-sample-demo\react-sta
> babel-node tools/run start

[10:57:58] Starting 'start'...
[10:57:58] Starting 'clean'...
[10:57:58] Finished 'clean' after 62 ms
[10:57:58] Starting 'bound copy'...
build/package.json
[10:57:58] Finished 'bound copy' after 189 ms
webpack built 474547464546eacb7261 in 11421ms
Child
    Time: 11421ms
                           Asset     Size  Chunks             Chunk Names
    main.js?474547464546eacb7261  4.34 MB       0  [emitted]  main
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 361ms
Child
    Time: 361ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 378ms
Child
    Time: 378ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 369ms
Child
    Time: 369ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 374ms
Child
    Time: 374ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 372ms
Child
    Time: 372ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 390ms
Child
    Time: 390ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 378ms
Child
    Time: 378ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 362ms
Child
    Time: 362ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 367ms
Child
    Time: 367ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 377ms
Child
    Time: 377ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 369ms
Child
    Time: 369ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 372ms
Child
    Time: 372ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 381ms
Child
    Time: 381ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 474547464546eacb7261 in 409ms
Child
    Time: 409ms
Child
    Time: 9894ms
            Asset    Size  Chunks             Chunk Names
        server.js  220 kB       0  [emitted]  main
    server.js.map  223 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.

Any ideas as to why this is happening?
##

**Comment by Bogdaan** [comment]
@erichardson30 you use old babel5 version of kit? (I also got similar results, only with babel5)

**Comment by erichardson30** [comment]
@Bogdaan No I'm using babel6

**Comment by ulani** [comment]
@erichardson30   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
