### ISSUE TITLE
Why eslint not work in components?

### ISSUE THREAD

**Issue by borovik96** [kriasoft/react-starter-kit#437]
Eslint works everywhere except for the components folder
.eslintrc:
`{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "globals": {
    "__DEV__": true
  },
  "env":{
    "mongo": true,
    "jest": true
  },
  "rules": {
    "react/jsx-quotes": 0,
    "jsx-quotes": [2, "prefer-double"],
    "no-param-reassign": [2, {"props": false}],
    "no-shadow": [2, {"builtinGlobals": false, "hoist": "never", "allow": [sql, err, result]}]
  }
}
`

**Comment by learntoswim** [comment]
How are you executing eslint?

**Comment by borovik96** [comment]
From sublime text 3 with sublimeLinter, ESLInt works everywhere except components folders, If I remove the package.json in folder with component It starts to work

**Comment by learntoswim** [comment]
Yes, that's because when you have eslint installed locally to the project, SublimeText uses package.json as the path root for add ins. You need to install eslint globally for it to work in components folders. Very frustrating, I know... I'm not sure I'm 100% inline with having a package.json file in each components folder but there are good arguments for it.

**Comment by koistya** [comment]
How would you make `core/fetch` component work for without `package.json`? Webpack bundles different versions of this library for `web` and `node` bundles.

**Comment by borovik96** [comment]
ESLint is installed locally and globally, if I delete it locally, then there are unresolved depending eslint-config-ayrbnb and eslint-loader

**Comment by learntoswim** [comment]
@koistya I'm neither not for nor against it, this issue is really a problem with SublimeText and not your starter kit.

**Comment by maximhoffman** [comment]
@borovik96 Really weird situation, I had this problem with Sublime Text 3. Eslint and etc shouldn't be installed globally and in my case it occurred after updating eslint-plugin-jsx-a11y plugin to last version. After downgrading everything is fine.
