### ISSUE TITLE
how do css classnames per component get dynamically generated during run-time?

### ISSUE THREAD

**Issue by awongCM** [kriasoft/react-starter-kit#444]
For eg.  I notice in the `About Us` content section, you see the html markup as follows:

````
<div class="ContentPage_root_1Kg" data-reactid=".uz6k8ai134.1">
<div class="ContentPage_container_1JT" data-reactid=".uz6k8ai134.1.0">
  <h1 data-reactid=".uz6k8ai134.1.0.0">About Us</h1>
  ....................
  </div>
</div>
</div>
````

`ContentPage_root_1Kg` and `ContentPage_container_1JT` are obviously dynamically generated so obviously cause you can see classnames inherit names of your component class, embedded into the markup during run-time?

Thus I want to know how do they get in there in the first place, firstly?

Secondly, is it possible to disable this dynamic css class generation?

**Comment by koistya** [comment]
@awongCM those CSS class names are generated by Webpack's [css-loader](https://github.com/webpack/css-loader) plugin, which itself uses [PostCSS](https://github.com/postcss/postcss) and [CSS Modules](https://github.com/css-modules/css-modules) spec behind the scene. This is configured in [tools/webpack.config.js](https://github.com/kriasoft/react-starter-kit/blob/d496698e9be478774e004d6135d27b8fa522385d/tools/webpack.config.js#L79-L80). To disable this behavior, remove `modules` and `localIdentName` flags from the `css-loader` config for `*.scss` files.

**Comment by awongCM** [comment]
Thanks @koistya 

BTW I also raised this issue in your repo.

https://github.com/koistya/react-static-boilerplate/issues/71

Cheers!

**Comment by koistya** [comment]
@awongCM you may want to disable CSS Modules only for 3rd party libraries (e.g. Bootstrap CSS, Fontawesome, Material Design Light etc.) but keep automatically generated CSS class names for custom CSS styles. For example, you can have one `css-loader` settings for `fontawesome.min.css` file, and another ones for `*.scss` files:

```js
// tools/webpack.config.js
{
  loaders: [
    { test: /fontawesome\.min\.css/, loader: ... },
    { test /\.scss$/, loader: ... }
  ]  
}
```

**Comment by awongCM** [comment]
Thanks @koistya -  Will check this out shortly.

Looking back at this, the only good thing I like this dynamic css classnames generation is because it reminded me one of the core principles of UI design methodology - specifically it's B.E.M.

https://en.bem.info/

The CSS module pretty much embraces most aspects of BEM hence it's a fantastic aid how you want to comparmentalize and reuse UI components in React's way.

Cheers!
