### ISSUE TITLE
Questions on Link

### ISSUE THREAD

**Issue by TintypeMolly** [kriasoft/react-starter-kit#451]
When I made some anchor tags with `Link` in this project,

I noticed that page loading indicator didn't appear on my chrome tap icon.

I'm using [Material UI](http://www.material-ui.com/) on this starter kit.
```
import IconButton from 'material-ui/lib/icon-button';
import SocialNotificationsNone from 'material-ui/lib/svg-icons/social/notifications-none'
...
<IconButton
  href="/notifications"
  linkButton
>
  <SocialNotificationsNone />
</IconButton>
```

This code renders an anchor tag with style of material design, but without this `Link.handleClick` function.

First, I tried bellow but didn't work
```
<IconButton
  href="/notifications"
  linkButton
  onClick={Link.handleClick}
>
  <SocialNotificationsNone />
</IconButton>
```

Second, I tried this, too
```
<IconButton>
  <Link to="/notifications"
    <SocialNotificationsNone />
  </Link>
</IconButton>
```

The first one, the link worked but not smoothly.

Apparently it seemed like `Link.handleClick` doesn't work on Material UI Components.

The second one, the page did not change at all.

It seems like there's some kind of strange bug that replaces `a` with useless `span` element,

probably because of Material UI's animation feature.
(`a` disappeared right after the animation. I could see that on console)

Anyway, I want this feature available on my project since the smoothness felt so good.

And also, I think I want a function that changes the location so I can use it anytime I want to change page.

If it was possible, I could just have it plugged it to `onClick` event and it's done.

But because I'm quite new to react,

and I don't see any code that actually change `window.location` or something like that on `Link` component and its `handleClick` function,

I feel frustrated with this problem.

**Comment by koistya** [comment]
Maybe do something like `onClick={e => { e.preventDefault(); Location.push('/notifications') }}`

**Comment by TintypeMolly** [comment]
@koistya Wow it worked! Thanks a lot. Does `Location.push('/some/url`)` do this job?

**Comment by koistya** [comment]
@TintypeMolly yep, it redirects a user to the new location without causing full-page refresh, combined with `Location.listen(...)` in `src/client.js`

**Comment by TintypeMolly** [comment]
@koistya So `e.preventDefault()` prevent following link, an then `Location.push` actually do the redirect. I got it. Thank you very much.
