### ISSUE TITLE
client auto send request with options method

### ISSUE THREAD

**Issue by hoangdreamer** [kriasoft/react-starter-kit#454]
i'im using sync-request to request api. But when run it on client always have a request with options method before my function
> browser.js?5dcd:53 OPTIONS http://example.com/news/search?keyword=rona 401 (Unauthorized)

**Comment by koistya** [comment]
@hoangdreamer I'm not sure I understand how it's related to **react-starter-kit**?

**Comment by hoangdreamer** [comment]
@koistya i think in some where have a function auto scan url and send OPTIONS request in main.js. It make errors and other script can not runing
