### ISSUE TITLE
security: content api /api/content can read paths outside the content directory

### ISSUE THREAD

**Issue by nss213** [kriasoft/react-starter-kit#458]
Repro:
in react starter kit root dir:

```
$ echo hello > foo.jade
$ npm start
```

navigate to `/api/content?path=../../foo` in the browser
Expected: `/api/content?path=../../foo` should return an error (perhaps 404?)
Actual: `/api/content?path=../../foo` returns `{"path":"../../foo","content":"<hello></hello>"}`

It seems that the content API actually has nearly unrestricted access to the filesystem (as long as the files end in `jade`). This works even outside of the react-starter-kit root directory (anywhere your node app has access to). 

Suggested fix: just error out if the path contains `/..`, `../` or is equal to `..`
##

**Comment by Bogdaan** [comment]
+1 this feature in master branch is unsecure

**Comment by koistya** [comment]
@nss213 goot catch!

**Comment by kngu9** [comment]
I replaced:

let fileName = join(CONTENT_DIR, `${path === '/' ? '/index' : path}.jade`);

with:

let fileName = join(CONTENT_DIR, `${path === '/' ? '/index' : path.replace('../', '/')}.jade`);

This will just give a 404, instead of a 500 error.

**Comment by frenzzy** [comment]
It seems it is not too safe, take a look at:
- [Node.js Security Checklist - Command Injection](https://blog.risingstack.com/node-js-security-checklist/#commandinjection)
- [How can I secure my code?](https://docs.nodejitsu.com/articles/file-system/security/introduction)

**Comment by nss213** [comment]
@frenzzy @koistya I was thinking about this, and perhaps it makes more sense to scan the content directory on startup and enter all the files into a whitelist (and probably also just load their content into memory). It doesn't really make sense to hit disk every time (I dunno what kind of caching there is with node's `fs`). Once all the filenames are in a whitelist, you just look them up by name based on the param.

**Comment by frenzzy** [comment]
@nss213 agree, the whitelist is the better approach I believe.

**Comment by ulani** [comment]
@nss213   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
