### ISSUE TITLE
Issues with enabling CORS

### ISSUE THREAD

**Issue by FakhruddinAbdi** [kriasoft/react-starter-kit#459]
I've been trying to enable Cross-origin-resource-sharing using the links below:

http://stackoverflow.com/questions/7067966/how-to-allow-cors-in-express-node-js
http://enable-cors.org/server_expressjs.html
http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

But i couldn't, 
I think it should be something related to browser-sync.
Is there's anyone can help me with that?

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31110960-issues-with-enabling-cors?utm_campaign=plugin&utm_content=tracker%2F1144755&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1144755&utm_medium=issues&utm_source=github).

**Comment by Bogdaan** [comment]
Why you need it?
If you want make XHR-request **from** other domain - use https://github.com/expressjs/cors
If you wont make XHR **to** other domain (for example api-server) - set CORS headers on remote server.

**Comment by prijindal** [comment]
@Bodgaan, i think there is still some issue in using cors with this kit.
I am trying to enable it as follows
```
app.use('/graphql', cors(), expressGraphQL(req => ({
  schema,
  graphiql: true,
  rootValue: { request: req },
  pretty: process.env.NODE_ENV !== 'production',
})));
```
but it does not work

**Comment by koistya** [comment]
Try enabling CORS in Browsersync settings, see `tools/start.js`

```js
      const bs = browserSync.create();

      bs.init({
        ...(config.debug ? {} : { notify: false, ui: false }),
        proxy: {
          target: server.host,
          middleware: [wpMiddleware, hotMiddleware],
        },
        cors: true,      // <------
      }, resolve);
```

**Comment by DylanYasen** [comment]
@koistya life saver!

I've been struggling with cors config on the server this whole morning.

calls are not getting through at all no matter how i set things up on server side.

turned out i completely neglected browsersync 

thanks for the help!

**Comment by squirmsound** [comment]
This didn't workout for me. Any other suggestions?

I see this approach.

https://github.com/kriasoft/react-starter-kit/issues/459

**Comment by langpavel** [comment]
@squirmsound You did not provide more info. What does not work for you? Can you see CORS headers in response?

**Comment by ulani** [comment]
@FakhruddinAbdi   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
