### ISSUE TITLE
add *compiled.js and *.js.map to .gitignore?

### ISSUE THREAD

**Issue by richb-hanover** [kriasoft/react-starter-kit#471]
Adding these two rules to .gitignore would be good

    *compiled.js
    *.js.map

**Comment by koistya** [comment]
Are these files specific to your IDE or text editor? If so, you may want to add them to the global .gitignore file as described here:

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by richb-hanover** [comment]
Hmmm... I never thought about it that way. I use Webstorm, and certainly could add those to the global .gitignore file. 

But I was under the impression that the *compiled.js and *.js.map files were created by Babel, and thus would apply to all people using react-starter-kit (or for that matter, using ES6...) But perhaps that is not so. 

Thanks! And thanks for react-starter-kit...
