### ISSUE TITLE
npm start - "ERROR in (webpack)-hot-middleware/client.js" message-FIXED

### ISSUE THREAD

**Issue by richb-hanover** [kriasoft/react-starter-kit#472]
Fresh install of react-starter-kit on OSX 10.10.5, node 5.3.0, npm 3.7.1

After git clone/cd/npm install/npm start, I get the above error. Here's the full terminal session that shows the error.

http://pastebin.com/jX6QNHt7

This worked in the past. Any ideas what's wrong? Thanks.

**Comment by mriosb** [comment]
I'm having the exact same issue. OSX 10.11.3. Node 5.7.0. NPM 3.6.0

**Comment by richb-hanover** [comment]
Temporary fix: the folks who made webpack-hot-middleware pushed a bad update a few hours ago (https://github.com/glenjamin/webpack-hot-middleware/issues/80)

The fix is to peg to webpack-hot-middleware to 2.7.1. To do this, update the package.json to say:

`"webpack-hot-middleware": "~2.7.1",`

Once they fix (by pushing out webpack-hot-middleware@2.8.1), you can update the package.json file

Sorry for the false alarm.

**Comment by richb-hanover** [comment]
webpack-hot-middleware was updated overnight to version 2.8.1 which I can confirm fixes the problem. Update your package.json to `"webpack-hot-middleware": "^2.8.1"` Thanks, all!
