### ISSUE TITLE
package.json - "Missing required property 'name'" 

### ISSUE THREAD

**Issue by richb-hanover** [kriasoft/react-starter-kit#473]
My ESLint was complaining about the package.json file, with a "Missing required property 'name'" message. 

I finally realized that the package.json file was missing several of the normal fields. Perhaps the package.json file could be updated to have these fields?

````
"name": "enter-the-name-of-your-project",
"description": "Enter a description for your project",
"author": "Enter your name, email, and/or website",
"version": "0.1.0",
"license": "MIT"
````

**Comment by Bogdaan** [comment]
Yes, current `package.json` is invalid, but it is marked as private

**Comment by richb-hanover** [comment]
I submitted a pull request https://github.com/kriasoft/react-starter-kit/pull/489 that adds these properties to the package.json (among other things).

**Comment by kriscooper29** [comment]
Thanks! I was having the same error using my VS Code.. I'm trying to run my vuejs project and it throws me the same error. I added the "name" and it works! Thank you.
![done](https://user-images.githubusercontent.com/31612708/85791220-095e2980-b764-11ea-89ae-f641e39ae622.JPG)
