### ISSUE TITLE
ERROR in ./src/data/queries/content.js

### ISSUE THREAD

**Issue by richb-hanover** [kriasoft/react-starter-kit#474]
After I worked around https://github.com/kriasoft/react-starter-kit/issues/472 (not a fault of react-starter kit - a dependency pushed out a bad update), I now get an error message `ERROR in ./src/data/queries/content.js`. 

The full error stream is at: http://pastebin.com/M6sXEkMQ Any ideas? Thanks.

**Comment by brianhei** [comment]
I am new to React Native and the starter kit. And I also got the same error when I run npm start

**Comment by richb-hanover** [comment]
After pulling this update, I can confirm it's fixed. Thanks, all!

**Comment by koistya** [comment]
@richb-hanover :+1:
