### ISSUE TITLE
This starter kit has SQL injection vulnerabilities up the wazoo 

### ISSUE THREAD

**Issue by robbyoconnor** [kriasoft/react-starter-kit#476]
See [bobby tables](http://bobby-tables.com)...use an ORM such as [bookshelf.js](http://bookshelfjs.org/) -- just don't do what you're doing. It's insecure!

**Comment by richb-hanover** [comment]
Would you care to point out one or two places that you discovered? Thanks.

**Comment by robbyoconnor** [comment]
He's not using an ORM -- he's just constructing queries and depending on postgres to sanitize the inputs, this falls apart when people choose to not use postgres...

**Comment by richb-hanover** [comment]
Not intending to be sarcastic, but it would help me if you could point out modules/line numbers where you see this bad practice? (I'm not doubting, but it would help me to see things through your eyes.) Thanks.

**Comment by ncrawlins** [comment]
Everyone knows, as long as you use an ORM, SQL injection is impossible and you never have to think about it again.  But if you don't use an ORM, your whole database will be stolen within minutes!  Yep, you should totally add in knex and bookshelf on top of pg just to feel safer about a handful of parameterized queries on 4 simple tables that are already protected from SQL injection ([here](https://github.com/brianc/node-postgres/wiki/FAQ#8-does-node-postgres-handle-sql-injection)). (I did intend to be sarcastic.)

**Comment by richb-hanover** [comment]
@ncrawlins This is to confirm I understand your sarcasm :-) 

1. There's no reason to fear SQL injection attacks if your code sanitizes all the inputs before creating the SQL queries to be sent to the database. 

2. It would be foolish (and indeed, a serious SQL injection vulnerability) to allow the web client to specify a full SQL command and forward it blindly to the database. That's the "Bobby Tables" scenario.

3. OP hasn't pointed out any specific modules/lines, so react-starter-kit has handles SQL commands properly.

Right?

**Comment by robbyoconnor** [comment]
@richb-hanover what's up with the condescending tone? https://github.com/kriasoft/react-starter-kit/blob/67593f112b93df3471c4f07ac0727703f16e1367/src/core/passport.js

**Comment by mlomeli** [comment]
According to the link @ncrawlins shared, node-postgres already offers SQL injection protection, so there isn't a security vulnerability. 

I'm not sure if the starter kit provides support for other databases so probably not an issue. I don't think introducing a ORM for a login should be part of the starterkit. 

Documenting with an inline comment that the SQL validation is performed by the package could be helpful, but I'm too new to Node.js to know if this is standard practice.

**Comment by koistya** [comment]
What @mlomeli said ^^ Closing for now, unless there is a proof of SQL injection vulnerability.
