### ISSUE TITLE
Is the dangerouslySetInnerHTML cause for concern?

### ISSUE THREAD

**Issue by zwhitchcox** [kriasoft/react-starter-kit#478]
Will this open my project up to XSS attacks?

And is there anything I need to not modify in order to make sure it stays that way?

**Comment by koistya** [comment]
`dangerouslySetInnerHTML` is currently in the `ContentPage` component, which is intended to serve static pages like "About Us", "Privacy Policy" etc. See `src/content`. The contents of these pages doesn't come from public users and thus should not be a security related concern.
