### ISSUE TITLE
Is 0.5.1 a breaking change?

### ISSUE THREAD

**Issue by richb-hanover** [kriasoft/react-starter-kit#481]
I think it's great to add the Markdown/HTML static pages and the global error handling in 0.5.1. And I really appreciate that you keep the CHANGELOG.md file up to date.

However, I'm worried that removing the Html React component could be a breaking change. (Fortunately, I happened to clone 0.5.1 as the base for my new project, so I'm not affected.)

But if removing those Html React components would require an earlier project to change, I would ask that you a) mention the potential breakage in the CHANGELOG.md file, b) consider holding off those features to at least a minor (0.x.0) release, or c) let us know that you still have a number of additional changes in the wings, so we should stay on our toes.

Thanks again for this great project!

**Comment by koistya** [comment]
@richb-hanover Thanks for the flag! I will pay more attention to versioning and maintaining the [changelog](https://github.com/kriasoft/react-starter-kit/blob/master/CHANGELOG.md) from now on.
