### ISSUE TITLE
npm start fails with TypeError message

### ISSUE THREAD

**Issue by jonsrose** [kriasoft/react-starter-kit#490]
I cloned the repository, was able to run npm install ok but when I ran npm start it errors out, here is the log. I also tried the react starter tool in webstorm and got the same issue, btw after seeing the issue I also tried the latest node.js  v5.7.1and npm 3.6.0 and got the same error

emjon:MyApp Jon$ npm start

> @ start /Users/Jon/dev/MyApp
> babel-node tools/run start

[21:39:47] Starting 'start'...
[21:39:47] Starting 'clean'...
[21:39:47] Finished 'clean' after 799 ms
[21:39:47] Starting 'bound copy'...
build/package.json
[21:39:48] Finished 'bound copy' after 502 ms
webpack built d4a67244452255cd9ad0 in 43121ms
Child
    Time: 43121ms
                           Asset     Size  Chunks             Chunk Names
    main.js?d4a67244452255cd9ad0  4.08 MB       0  [emitted]  main
Child
    Time: 39156ms
            Asset    Size  Chunks             Chunk Names
        server.js  281 kB       0  [emitted]  main
    server.js.map  296 kB       0  [emitted]  main
webpack: bundle is now VALID.
[21:41:02] The server is running at http://localhost:3000/
/Users/Jon/dev/MyApp/tools/start.js:117
                    handleServerBundleComplete = _runServer2.default;
                                               ^

TypeError: Assignment to constant variable.
    at start.js:102:11
    at Socket.onStdOut (runServer.js:34:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)

Here is the log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart @
6 info start @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec start script
9 verbose stack Error: @ start: `babel-node tools/run start`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid @
11 verbose cwd /Users/Jon/dev/MyApp
12 error Darwin 15.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.3.1
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error @ start: `babel-node tools/run start`
17 error Exit status 1
18 error Failed at the @ start script 'babel-node tools/run start'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     babel-node tools/run start
18 error You can get their info via:
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by batwicket** [comment]
I see this too using tag v0.5.1

**Comment by Bogdaan** [comment]
You using `node v4.3.1`
Required node version (for RSK >= v4.x - at package.json):
```
    "node": ">=5.0 <6",
```

Please read the docs before create issue.

**Comment by batwicket** [comment]
Not me. I see the following when `npm start` fails:
`npm ERR! node v5.5.0
npm ERR! npm  v3.5.3`
The command was working until I decided to start from scratch and checkout from github again.

**Comment by Bogdaan** [comment]
@batwicket which version of RSK?
`RSK v0.4.1` works fine with `node v5.5.0`

**Comment by batwicket** [comment]
I've tried v0.5.1 with the same result, but currently i'm following the startup instructions verbatim so it's coming from master:
`git clone -o react-starter-kit -b master --single-branch \
      https://github.com/kriasoft/react-starter-kit.git MyApp`

**Comment by Bogdaan** [comment]
ask @koistya 
For me `master` and `v5.x` is not ready to use.

Try checkout to v0.4.1

**Comment by batwicket** [comment]
Perhaps relevant.. not sure. The `npm start` complains:
`tools/start.js:117
                    handleServerBundleComplete = _runServer2.default;
                                               ^

TypeError: Assignment to constant variable.
    at start.js:102:11
    at Socket.onStdOut (runServer.js:34:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:523:20)`

But this does not match the `tools/start.js` in the source tree. The source file only has 111 lines and the closest I can see to the error is at line 102:
`handleServerBundleComplete = runServer;`
I suspect I'm just not familiar enough with the project to understand what is going on.

**Comment by Bogdaan** [comment]
@batwicket seems this related with OSX node/babel instalation,
RSK v4.x works fine on *nix and windows with nodejs v5.x

You use nvm for nodejs (https://github.com/creationix/nvm)?

**Comment by batwicket** [comment]
Not to my knowledge. It's not in the path. This is the only project i'm working on which uses node.

**Comment by batwicket** [comment]
The package.json appears to hardwire all of the versions. Is it possible that something changed between `npm install`s?

**Comment by batwicket** [comment]
BTW I just went back to v0.4.1, as you suggested. It works.

**Comment by groggy84** [comment]
same issue 
osx 10.10.5 
node 5.6.0
npm 3.6.0

> babel-node tools/run start

[20:44:06] Starting 'start'...
[20:44:06] Starting 'clean'...
[20:44:06] Finished 'clean' after 41 ms
[20:44:06] Starting 'bound copy'...
build/package.json
[20:44:06] Finished 'bound copy' after 177 ms
webpack built 3cca71520587fea7214d in 13344ms
Child
    Time: 13344ms
                           Asset     Size  Chunks             Chunk Names
    main.js?3cca71520587fea7214d  4.07 MB       0  [emitted]  main
Child
    Time: 12184ms
            Asset    Size  Chunks             Chunk Names
        server.js  282 kB       0  [emitted]  main
    server.js.map  297 kB       0  [emitted]  main
webpack: bundle is now VALID.
[20:44:22] The server is running at http://localhost:3000/
/Users/groggy/WebstormProjects/react-start-kit/tools/start.js:117
                    handleServerBundleComplete = _runServer2.default;
                                               ^

TypeError: Assignment to constant variable.
    at start.js:102:11
    at Socket.onStdOut (runServer.js:34:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:525:20)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

**Comment by koistya** [comment]
I have the same issue. For those who are not affected, don't remove `node_modules` making clean `npm install` for now :) Checking if "TypeError: Assignment to constant variable." is a known issue in Babel's bag tracker..

**Comment by koistya** [comment]
Try to replace `let handleServerBundleComplete` with `var handleServerBundleComplete` in `tools/start.js`. Does this workaround fixes the issue?

**Comment by groggy84** [comment]
koistya thx...
