### ISSUE TITLE
How to use req.params?

### ISSUE THREAD

**Issue by AliceRossa** [kriasoft/react-starter-kit#494]
Hello !

Could you explain to me how to use req.params to fetch data?

> src/routes/posts/index.js

```
import React from 'react';
import Post from './Post ';
import fetch from '../../core/fetch';

export const path = '/posts/:id';
export const action = async (state, res, req) => {
  const response = await fetch(`/graphql?query={posts(id:${req.params.id}){title,content}}`);
  const { data } = await response.json();
  state.context.onSetTitle({data.posts.title});
  return <Post post={data.posts} />;
};
```
Thank you

**Comment by koistya** [comment]
`req.params` variable comes from the [react-routing](https://github.com/kriasoft/react-routing) library. It's constructed based on URL route pattern such as `'/post/:id` and actual URL such as `/post/123` in which case `req.params` will equal to `{ id: '123' }`. You can use this argument inside your route handler (action) function to fetch the data as the example code in your question demonstrates.

BTW, you may want to prefer using [StackOverflow](http://stackoverflow.com/questions/tagged/react-starter-kit ) for questions like this one, where you have higher chances of receiving a good answer, see [CONTRIBUTING.md](https://github.com/kriasoft/react-starter-kit/blob/master/CONTRIBUTING.md) guide for more info.
