### ISSUE TITLE
Review README.md file

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#5]
There could be typos or inaccuracies.

https://github.com/kriasoft/React-Seed/edit/master/README.md

**Comment by sdiaz** [comment]
Added PR #66 with some minor changes (folder structure, test dir).

**Comment by matgessel** [comment]
Consider mentioning `gulp --verbose`. This ensures the webpack plugin emits a message when it encounters a syntax error. Otherwise, your only feedback is this error in the browser console: 

    Uncaught Error: Cannot find module "../../stores/AppStore

**Comment by koistya** [comment]
Closing for now.
