### ISSUE TITLE
Bag: Kit doesn't start with latest stable NVM 5.9.0

### ISSUE THREAD

**Issue by craft37** [kriasoft/react-starter-kit#517]
npm start stops on row 'webpack: bundle is now VALID.' but running well on node.js 4.1.1

Ubuntu 15.10
npm 3.3.4
node.js 5.9.0

**Comment by craft37** [comment]
Solution from #516 saves me

**Comment by Rathawut-l** [comment]
Node.js v5.0 or newer is one of the requirements for running react starter kit

https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md
