### ISSUE TITLE
Use .jsx extension for JSX files instead of .js

### ISSUE THREAD

**Issue by dmnd** [kriasoft/react-starter-kit#52]
As of React 0.12, [it is recommended](https://github.com/facebook/react/issues/832) to use the .jsx file extension rather than the pragma in .js files.

This will also help with editors doing syntax highlighting & linting.

**Comment by ChaosD** [comment]
+1 to avoid confusion

**Comment by sdiaz** [comment]
+1, i just got crazy with Webstorm and jsx files

**Comment by frankleng** [comment]
+1

**Comment by saitodisse** [comment]
+1 editors syntax highlighting

**Comment by seemsindie** [comment]
+1

**Comment by koistya** [comment]
Components in the starter kit currently use `.js` file extension for two reasons:

1. As of now, it's the default file extension for React components used at Facebook. See [react-tools](https://www.npmjs.com/package/react-tools) `jsx` command-line build tool. Also, see [React examples](https://github.com/facebook/react/tree/master/examples) and [Flux examples](https://github.com/facebook/flux/tree/master/examples).
2. You can reference these components in your source code without specifying file extensions, e.g. `require('./MyComponent')` instead of `require('./MyComponent.jsx')` and still be able to use "navigate to source" feature in your code editor.

Do you think that the benefits of having `.jsx` file extension for React components outmatch these two?

**Comment by sdiaz** [comment]
I prefer the use of `.js` as it's now

**Comment by saitodisse** [comment]
good point

2015-02-04 11:21 GMT-02:00 Santiago Diaz <notifications@github.com>:

> I prefer the use of .js as it's now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kriasoft/react-starter-kit/issues/52#issuecomment-72852766>
> .
>



-- 
Julio Mak*disse Saito*,
aka: saitodisse

**Comment by PixnBits** [comment]
Every .css file is valid SCSS, but a .scss file may not be valid CSS
Every .js file is valid TypeScript, but a .ts file may not be valid JS (ES3/5/6/2015/2016)
It feels a bit audacious to me that Facebook would put their custom superset into the subset's extension :(

**Comment by PixnBits** [comment]
FWIW a relevant discussion on this in the React repo:
https://github.com/facebook/react/issues/3582#issuecomment-89411479

**Comment by ehartford** [comment]
jsx isn't valid javascript so, it should not use a .js extension

**Comment by koistya** [comment]
@ehartford JSX it's just an extension to JavaScript, not a new language like TypeScript or CoffeeScript. Can you tell the same about `async/await` stuff which isn't valid JavaScript either?

**Comment by PixnBits** [comment]
@koistya JSX adds new syntax to ES just as TS does, they're both extensions/supersets that  don't follow the ES spec or any stage'd proposal.

FWIW [`async`/`await` is a Stage 3 proposal](https://tc39.github.io/ecmascript-asyncawait/), but you raise an interesting point on if proposals TC39 is considering should be considered "valid-enough" ES.

**Comment by langpavel** [comment]
Irrelevant. JSX syntax can be used (and it is) in every javascript source file. Closing

**Comment by wembernard** [comment]
@langpavel what about Facebook deprecating react-tools (last comment on https://github.com/facebook/react/issues/832) and setting .jsx files a. 

@koistya You're confused. 
> JSX is a preprocessor step that adds XML syntax to JavaScript. 
> Typescript is a typed superset of JavaScript that compiles to plain JavaScript.
See the 2 keywords here: `preprocessor`, `compiles` ? Both offer different features but both work the same way. 

As a newcomer to the React World, finding jsx syntax inside js is misleading. Everyone here's telling you it's confusing. You do as you please but you're going against your community, that's not really user-centric approach.

**Comment by ehartford** [comment]
facebook is recommending using .jsx extension how is this an invalid issue?

**Comment by tyrsius** [comment]
@ehartford Do you have a link for that, because the link PixnBits posted is React saying not to use `.jsx`.

**Comment by langpavel** [comment]
Create react app does not use jsx too

**Comment by koistya** [comment]
@ehartford `.jsx` is recommended by AirBnb guys, `.js` by Facebook guys.

**Comment by maratbn** [comment]
>> Irrelevant. JSX syntax can be used (and it is) in every javascript source file. Closing

If that's so, how come no browser will interpret a JSX <script> unless its 'type' attribute is specified as 'text/babel' rather than 'text/javascript' ?
