### ISSUE TITLE
How to disable Browser sync?

### ISSUE THREAD

**Issue by nguyenbathanh** [kriasoft/react-starter-kit#523]

**Comment by koistya** [comment]
You can run the site without Brwosersync (cross-device testing, HMR, React Reload) by running:

```bash
$ npm run build           # or, `npm run build -- --release`
$ node build/server.js
```

See also [#react-starter-kit](http://stackoverflow.com/questions/tagged/react-starter-kit) on StackOverflow.

**Comment by nguyenbathanh** [comment]
It works for me!
Thank you for very quick response.

**Comment by koistya** [comment]
Just to clarify.. the way it currently works is that when you run `npm run start`, the `tools/start.js` script starts Webpack bundler in "watch" mode, enables HMR / React Hot Transform, launches `node.js build/server.js` Browsersync proxy on top of it.

**Comment by nguyenbathanh** [comment]
Thank you.
I clearly understand what you explained, but I want to completely disabled Browse sync from my project, is it possible?
