### ISSUE TITLE
npm starts fails & live reload doesnt work

### ISSUE THREAD

**Issue by m4recek** [kriasoft/react-starter-kit#527]
my npm version is 3.7.3, node version v.5.9.0, windows 7 64bit

after clean `git checkout`, `npm install`, `npm start` fails 

```
webpack: bundle is now VALID.

D:\aircloak\node_modules\transformers\node_modules\uglify-js\tools\node.js:41
UglifyJS.AST_Node.warn_function = function(txt) {
                                ^
TypeError: Cannot set property 'warn_function' of undefined
```

after updating uglify-js version to 2.6.0 in transformer module (from here https://github.com/kriasoft/react-starter-kit/issues/514)

it loads but live reload is not working at all, output of `npm start` is:

```

> @ start D:\aircloak
> babel-node tools/run start

[22:30:53] Starting 'start'...
[22:30:53] Starting 'clean'...
[22:30:53] Finished 'clean' after 27 ms
[22:30:53] Starting 'bound copy'...
[22:30:53] Finished 'bound copy' after 137 ms
webpack built f9b95dc3e8c3a4d289d5 in 5622ms
Child
    Time: 5622ms
                           Asset     Size  Chunks             Chunk Names
    main.js?f9b95dc3e8c3a4d289d5  4.09 MB       0  [emitted]  main
Child
    Time: 5036ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  279 kB       0  [emitted]  main
    ../../server.js.map  296 kB       0  [emitted]  main
webpack: bundle is now VALID.
[22:31:01] The server is running at http://localhost:3000/
[BS] Proxying: http://localhost:3000
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3001
    External: http://192.168.1.172:3001
 --------------------------------------
          UI: http://localhost:3002
 UI External: http://192.168.1.172:3002
 --------------------------------------
[BS] Watching files...
[22:31:03] Finished 'start' after 10186 ms
```

**Comment by m4recek** [comment]
So, seems like Webstorm "safe save" feature is breaking live reload. As a temporary workaround its solvable by turning it off. 

Here is how. https://github.com/kriasoft/react-starter-kit/pull/528

**Someone please upload that image to dropbox and link it in documentation**

**Comment by nickeblewis** [comment]
Which version of WS are you using?

**Comment by m4recek** [comment]
11.0.3

**Comment by ulani** [comment]
@m4recek   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
