### ISSUE TITLE
Use 6to5 transform instead of ReactTools transform

### ISSUE THREAD

**Issue by dmnd** [kriasoft/react-starter-kit#53]
6to5 handles JSX just fine, but it also gives a lot more ES6 features.

**Comment by koistya** [comment]
@dmnd, yep, good suggestion! Do you use [6to5](https://6to5.org) at Khan Academy? I'm wondering, if there are any known issues with it?

**Comment by dmnd** [comment]
We don't use it at KA; we use ReactTools like you are. 

But I'm doing a side project based off this repo and I ended up wanting more ES6. I have 6to5 running and it seems to work fine. My code isn't yet in a state to send you PRs, though I really should get to that.

**Comment by adowning** [comment]
+1 good suggestion

**Comment by sdiaz** [comment]
6to5 and esnext has merged efforts : http://6to5.org/blog/2015/01/12/6to5-esnext/ so it's a good suggestion

**Comment by goatslacker** [comment]
I second this.

6to5 comes with some [caveats](https://6to5.org/docs/usage/caveats/) if you're trying to support legacy browsers like IE8 and below, it seems like the caveats are outweighed by the goodness that 6to5 brings.

**Comment by koistya** [comment]
Just have replaced the original JSX transpiler with 6to5. See [webpack.config.js](https://github.com/kriasoft/react-starter-kit/blob/9f490661270886c025f18ff1cd2fb6c1941b0059/config/webpack.js#L88-L90)
