### ISSUE TITLE
npm start command I am getting the below erro

### ISSUE THREAD

**Issue by texirv0203** [kriasoft/react-starter-kit#531]
Hi
- when I run npm start command I am getting the below error
- I followed the below steps in the link
  https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md
- can you tell me how to fix it
- providing error below

xxx-nameKumar--MacBook-Pro:MyApp xxx-name$ npm start

> @ start /Users/xxx-name/Desktop/FrontEnd/MyApp
> babel-node tools/run start

/Users/xxx-name/Desktop/FrontEnd/MyApp/tools/run.js:20
  const task = typeof fn.default === 'undefined' ? fn : fn.default;
  ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at loader (/Users/xxx-name/Desktop/FrontEnd/MyApp/node_modules/babel-cli/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js](/Users/xxx-name/Desktop/FrontEnd/MyApp/node_modules/babel-cli/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at /Users/xxx-name/Desktop/FrontEnd/MyApp/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/Users/xxx-name/Desktop/FrontEnd/MyApp/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:460:26)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx-name/Desktop/FrontEnd/MyApp/npm-debug.log

**Comment by frenzzy** [comment]
[babel-plugin-transform-strict-mode](http://babeljs.io/docs/plugins/transform-strict-mode/) should help you

**step 1** install transform strict mode plugin:
```shell
npm install babel-plugin-transform-strict-mode --save-dev
```

**step 2** update [package.json/babel](https://github.com/kriasoft/react-starter-kit/blob/master/package.json#L91-L97):
```js
{
  // ...
  "babel": {
    "presets": [
      // ...
    ],
    "plugins": [
      "transform-strict-mode" // <===
    ]
  },
  // ...
}
```

**Comment by ddm-flipkart** [comment]
**A suggestion**: Why not make it part of the original package? Because I believe people getting this error could be many in number.

**Comment by ulani** [comment]
@texirv0203   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
