### ISSUE TITLE
Error installing modules

### ISSUE THREAD

**Issue by fauria** [kriasoft/react-starter-kit#537]
npm install
npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.0-rc.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer graphiql@0.6.6 wants react@^0.14.0 || ^15.0.0-rc
npm ERR! peerinvalid Peer react-dom@15.0.0-rc.2 wants react@^15.0.0-rc.2
npm ERR! peerinvalid Peer react-addons-test-utils@15.0.0-rc.2 wants react@^15.0.0-rc.2
npm ERR! peerinvalid Peer redbox-react@1.2.2 wants react@>=0.13.2 || ^0.14.0-rc1
npm ERR! peerinvalid Peer enzyme@2.2.0 wants react@0.13.x || 0.14.x || 15.* || ^15.0.0-rc

**Comment by Bogdaan** [comment]
This kit works with npm3 and nodejs (>=5.0 <6)
see https://github.com/kriasoft/react-starter-kit/blob/master/package.json

Tip: you can use nvm (node version manager).

**Comment by fauria** [comment]
Thank you!
