### ISSUE TITLE
Excessive build times (css related?)

### ISSUE THREAD

**Issue by jtremback** [kriasoft/react-starter-kit#539]
I'm dealing with a project that uses this framework, and the hot-reload build time there is 15 seconds (after an initial build of ~4 minutes!). So I cloned a clean copy of this repo, and I'm seeing an incremental build time of 3.5 seconds. Is this to be expected? Using Browserify, I have been able to achieve much faster builds in the past. In fact, this is the first time that build times have been an issue for me on a Javascript project. These kind of build times make hot-reload superfluous.

**Comment by Ehesp** [comment]
These times are slow, for me at least anyway. Initial build here takes around 5 seconds and incremental builds are almost instant. Not much help, but something is wrong your side.

**Comment by koistya** [comment]
Sounds like there is a big room for improvement, even in large projects the initial build time (at least, for development / debug builds) should be under 30 seconds I believe, and incremental builds under 1 second.

Have you checked the [Build Performance](http://webpack.github.io/docs/build-performance) article on Webpack's homepage? Also look into [PrefetchPlugin](https://webpack.github.io/docs/list-of-plugins.html#prefetchplugin)

**Comment by jtremback** [comment]
thanks @koistya, @Ehesp. I think it must be some kind of misconfiguration in the project we inherited. One thing I noticed is that every component's scss is loading bootstrap. We started commenting these imports out and noticed improvements in build speed. Perhaps this has something to do with it. Do you have some recommended best practices for loading scss frameworks? Only load them once maybe?

**Comment by koistya** [comment]
I'm not sure if there is a best practice for that. I would personally import it inside the CSS of the top-level component that is used for all pages of the site.
