### ISSUE TITLE
Does webpack support require.extensions['.js'] ?

### ISSUE THREAD

**Issue by lildemon** [kriasoft/react-starter-kit#54]
I see the gulpfile.js and webpack's config file, it doesn't seem that webpack will property handle jsx code because those file's extension is '.js' not '.jsx'
I try to run or debug to know how it works, but don't saw a clue

Except that gulpfile has code that change the node's require behavior to transform jsx and ES6 code first

My question is:
Will webpack use node's require() to transform jsx/ES6 code?
It seems that webpack don't have this kinds of behavior
Or did I missed something?

Thanks :+1:

**Comment by koistya** [comment]
@lildemon `webpack` is configured so that `jsx-loader` is applied to both `.js` and `.jsx` files:

https://github.com/kriasoft/react-starter-kit/blob/master/config/webpack.js#L86-L89

**Comment by koistya** [comment]
@lildemon also, I'm going to remove jsx transform from `gulpfile.js` in the upcoming commit, it was used for `gulp-render` to work.

**Comment by lildemon** [comment]
thanks :P I missed the "?" part of the regex

**Comment by koistya** [comment]
I have made some modifications. Webpack now generates both client-side (app.js) and server-side (server.js) bundles, which is used for server-side rendering. There is now no need to use `require.extensions` hacks.
