### ISSUE TITLE
Redirect all routes to the same component

### ISSUE THREAD

**Issue by beeb** [kriasoft/react-starter-kit#55]
Hello,

I'm building a single page application which has only 1 component/page. I'd like to redirect all uri's to this "Index" component, instead of having the 404 page showing up for invalid routes. Is that possible ? I tried putting regular expressions inside routes in the app.js but it doesn't seem to work.

Thanks !

**Comment by koistya** [comment]
@beeb check it out, it now has a single top-level component (`./src/components/App`) and all page URLs are now handled by it.

**Comment by beeb** [comment]
Thanks, but this seems to change significantly from the previous version and I'm not sure I'm willing to update my project to use the new code. Any way to do it with Director ?
