### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by hosken5** [kriasoft/react-starter-kit#550]
I got this error when  I  run  "npm start " after npm install 

Warning: Failed propType: Required prop `news` was not specified in `Home`. Check the render method of `WithStyles(Home)`.
  TypeError: Cannot read property 'map' of null
- Home.js:20 new Home
  /Users/hongpf/hosken5/reacttest/build/webpack:/src/routes/home/Home.js:20:12  
- ReactCompositeComponent.js:148 [object Object].ReactCompositeComponentMixin.    mountComponent
  [reacttest]/[react]/lib/ReactCompositeComponent.js:148:18
- ReactPerf.js:66 [object Object].wrapper [as mountComponent]
  [reacttest]/[react]/lib/ReactPerf.js:66:21
- ReactReconciler.js:37 Object.ReactReconciler.mountComponent
  [reacttest]/[react]/lib/ReactReconciler.js:37:35
- ReactCompositeComponent.js:225 [object Object].ReactCompositeComponentMixin.    mountComponent
  [reacttest]/[react]/lib/ReactCompositeComponent.js:225:34
- ReactPerf.js:66 [object Object].wrapper [as mountComponent]
  [reacttest]/[react]/lib/ReactPerf.js:66:21
- ReactReconciler.js:37 Object.ReactReconciler.mountComponent
  [reacttest]/[react]/lib/ReactReconciler.js:37:35
- ReactMultiChild.js:241 ReactDOMComponent.ReactMultiChild.Mixin.mountChildren    [reacttest]/[react]/lib/ReactMultiChild.js:241:44
- ReactDOMComponent.js:591 ReactDOMComponent.Mixin._createContentMarkup
  [reacttest]/[react]/lib/ReactDOMComponent.js:591:32
- ReactDOMComponent.js:479 ReactDOMComponent.Mixin.mountComponent
  [reacttest]/[react]/lib/ReactDOMComponent.js:479:29
- ReactReconciler.js:37 Object.ReactReconciler.mountComponent
  [reacttest]/[react]/lib/ReactReconciler.js:37:35
- ReactCompositeComponent.js:225 [object Object].ReactCompositeComponentMixin.    mountComponent
  [reacttest]/[react]/lib/ReactCompositeComponent.js:225:34
- ReactPerf.js:66 [object Object].wrapper [as mountComponent]
  [reacttest]/[react]/lib/ReactPerf.js:66:21
- ReactServerRendering.js:42 
  [reacttest]/[react]/lib/ReactServerRendering.js:42:38
- Transaction.js:136 ReactServerRenderingTransaction.Mixin.perform
  [reacttest]/[react]/lib/Transaction.js:136:20
- ReactServerRendering.js:40 Object.renderToString
  [reacttest]/[react]/lib/ReactServerRendering.js:40:24

**Comment by liudonghua123** [comment]
I got the same problem.
![image](https://cloud.githubusercontent.com/assets/2276718/14552965/5f694cb8-0315-11e6-91da-7fd88718eda0.png)

**Comment by koistya** [comment]
@liudonghua123 @hosken5 do you have this `if (!data.news) throw new Error(..)` check in `/routes/home/index.js` route?

https://github.com/kriasoft/react-starter-kit/blob/master/src/routes/home/index.js#L31

**Comment by liudonghua123** [comment]
@koistya I checked the `/routes/home/index.js` file, there wasn't that line `if (!data.news) throw new Error(..)`, I added it manually, but it gave me the following error message.

![image](https://cloud.githubusercontent.com/assets/2276718/14553388/d721c99e-0318-11e6-908e-4b7e0387f192.png)

ps: I created my project with `yo react-fullstack` and start with `npm start`

**Comment by koistya** [comment]
`react-fullstack` generator is a little bit behind the master branch. You can copy the contents of these files into you project:

https://github.com/kriasoft/react-starter-kit/blob/master/src/data/schema.js - GraphQL schema
https://github.com/kriasoft/react-starter-kit/blob/master/src/data/queries/news.js - GraphQL news endpoint
https://github.com/kriasoft/react-starter-kit/blob/master/src/routes/home/index.js - Home page route that fetches news feed from the GraphQL endpoint above

**Comment by liudonghua123** [comment]
@koistya I replaced these three files and re-run `npm start`, but it gave me the following error.

![image](https://cloud.githubusercontent.com/assets/2276718/14555272/36edd65a-0324-11e6-988b-8c74e0f387df.png)

**Comment by koistya** [comment]
I see.. ok, give me a moment I will prepare and publish the updated version of `generator-react-fullstack`.

**Comment by ritsuyan** [comment]
the problem still exist 
btw ， I use the yo generator like above.
at the begining I would like use npm install but find maybe sth wrong with internet(u know , in China) or 
other cause that cannot be install .
such a pity...

**Comment by ritsuyan** [comment]
@liudonghua123 @koistya is this problem still exist?

**Comment by Amorites** [comment]
I've met the same problem.

**Comment by wallenweel** [comment]
@ritsuyan 其实是GFW的锅（哭笑，如果和我这边一样的话。下面是具体步骤，不想看的话，直接给cmd做个代理就成了（全局的话，得处理下localhost。

I have just met this problem.
1. Try to delete `{news.map((item.....))}` in Home.js, if no error happen again, restore change and continue following.
2. Browse `localhost:3001/graphql?query={news{title,link,contentSnippet}}`(you could find it in **index.js** within same directory.
3. More clear error infos show in the Graphiql's right panel, maybe such as:
`{
  "data": {
    "news": null
  },
  "errors": [
    {
      "message": "request to http://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=10&q=https://reactjsnews.com/feed.xml failed, reason: connect ETIMEDOUT 216.58.197.106:80",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}`
4. If your errors like mine that is **connect etimeout**, my solution is by _shadowsocks_ and _proxifer_ two softwores （I guess only provide the agent to cmd（windows
5. Redo 2. (do without restarting server
6. I got lots of data finally and everything looks good, hope you too.

**Comment by henryhuang** [comment]
@wallenweel 还真是，不过模版做这么多事不太好吧

**Comment by wallenweel** [comment]
@henryhuang 初始化的项目介绍（yeoman的生成器大都这样），之后会被使用者重写，开发者估计是没考虑一些国家的限制网络，这种坑踩过一次就差不多了

**Comment by fuchao2012** [comment]
@wallenweel 我开着ss 为啥还是报错呢，到了 2 ，3 两步只是看是吗？
如果不注释源码里的新闻，能看到不（翻墙以后）？

**Comment by wallenweel** [comment]
@fuchao2012 是全局代理么？要给运行服务的终端进行代理，比如cmd，只给浏览器代理不行的，ss的话我用的[proxifier](https://www.proxifier.com/)给其他程序做的代理，你可以试试这个

**Comment by ulani** [comment]
@hosken5   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
