### ISSUE TITLE
Where is routes/index.js called from?

### ISSUE THREAD

**Issue by BryanARivera** [kriasoft/react-starter-kit#555]
Where is routes/index.js called from?

**Comment by arvigeus** [comment]
/src/client.js, line 14
/src/server.js, line 24

**Comment by BryanARivera** [comment]
Thanks.  Is there any good place to ask questions besides here?

**Comment by BryanARivera** [comment]
I am a little confused as to whether this package uses react-router or universal-router.  Can someone please clarify?

**Comment by koistya** [comment]
@BryanARivera currently it uses `universal-router`, check out this tutorial:

https://slides.com/koistya/universal-router

And here is a comment regarding how it can be switched to `react-router` if you find its API more appealing: https://github.com/kriasoft/react-starter-kit/issues/20#issuecomment-207592082

For questions, you can also try StackOverflow (tag [#react-starter-kit](http://stackoverflow.com/questions/tagged/react-starter-kit)) and [#react-starter-kit](https://gitter.im/kriasoft/react-starter-kit) chat room on Gitter.

**Comment by BryanARivera** [comment]
Good to see an SO tag is available.  This kit has a lot of nice features, but seems somewhat complex (for a noob) and missing my must haves (react-router and redux).  It's probably worth it to try and grok this, and implement those components.  At least I will have some help!

(Do you have any slides for redux integration?)

**Comment by koistya** [comment]
I was going to add Redux integration guide whenever I have a chance.

**Comment by BryanARivera** [comment]
Is it complete and just need to post?

**Comment by koistya** [comment]
Nope, haven't written it yet.

**Comment by BryanARivera** [comment]
Ok, thanks!
