### ISSUE TITLE
error while running the script node ./node_modules/.bin/babel-node get-account-info.js on windows

### ISSUE THREAD

**Issue by swdpankaj** [kriasoft/react-starter-kit#558]
c:\wamp\www\ripple>node ./node_modules/.bin/babel-node get-account-info.js
c:\wamp\www\ripple\node_modules\.bin\babel-node:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by estyrke** [comment]
I am no expert on React or node.js, but `babel-node` seems to be a bash script. There is another script called `babel-node.cmd` which seems more appropriate. Does `node_modules\.bin\babel-node.cmd get-account-info.js` work better?

**Comment by koistya** [comment]
@swdpankaj you can run scripts from `node_modules` in a cross-browser way via [NPM scripts](https://docs.npmjs.com/misc/scripts). For example:

##### `pacakge.json`

```json
{
  "private": true,
  "devDependencies": {
    "babel-cli": "^6.7.5"
  },
  "scripts": {
    "get-account-info": "babel-node ./get-account-info.js"
  }
}
```

Then you can run it from a command line like so:

```cmd
> npm run get-account-info
```

**Comment by swdpankaj** [comment]
Could not solve. Here is the log file detail.


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'account-info' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'preaccount-info', 'account-info', 'postaccount-info' ]
5 info preaccount-info @
6 info account-info @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec account-info script
9 verbose stack Error: @ account-info: `babel-node ./get-account-info.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid @
11 verbose cwd c:\wamp\www\ripple
12 error Windows_NT 6.1.7600
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "account-info"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error @ account-info: `babel-node ./get-account-info.js`
17 error Exit status 1
18 error Failed at the @ account-info script 'babel-node ./get-account-info.js'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     babel-node ./get-account-info.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by swdpankaj** [comment]
When I tries to run this commend but it shows error 

c:\wamp\www\ripple>npm run account-info

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe
node_modules\\npm\\bin\\npm-cli.js" "run" "account
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0

npm ERR! missing script: account-info
npm ERR!
npm ERR! If you need help, you may report this err
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with an
npm ERR!     c:\wamp\www\ripple\npm-debug.log

**Comment by koistya** [comment]
The error message says that it cannot find `"scripts:" { "account-info": "...." }` entry in your `c:\wamp\www\ripple\package.json` file.
