### ISSUE TITLE
Split single Gulpfile into per task files

### ISSUE THREAD

**Issue by sdiaz** [kriasoft/react-starter-kit#56]
Hello,

Im using this starter kit for our projects, but we have to modify the current gulpfile and split into files per task in a gulp/ directory for better understanding of build processes as we have modify some of them (we use modernizr, semantic-ui, sass ..)

How do you feel about switching to that model instead of a single file.

The structure would be

gulpfile.js
gulp/index.js
gulp/config.js
gulp/tasks/<tasks>
gulp/util/errorHandling.js

**Comment by sdiaz** [comment]
The gulp boilerplate of the project has been significantly reduced so I don't know if this is still useful and submit a PR or we should keep at is now.

**Comment by koistya** [comment]
FYI, `styles` and `autoprefixer` stuff is going to be removed from the `gulpfile.js` (see #43), leaving just a few tasks related to firing up webpack and development web server. The `gulpfile.js` will be even smaller than it is now. Splitting it into separate files will add unnecessary complexity to the project's structure. Some folks go even farther and remove dependency on Gulp in favor of just using [webpack](https://webpack.github.io) and [npm scripts](https://docs.npmjs.com/misc/scripts).
