### ISSUE TITLE
cannot require less files in componnents

### ISSUE THREAD

**Issue by frankleng** [kriasoft/react-starter-kit#57]
when I use require('style.less'), the component will not work and the JSX transpiler complains about unexpected characters.
ex. using the included TextBox component which has a less require statement.

@koistya please advise. thanks!

**Comment by koistya** [comment]
As a workaround, try adding the following line to the `gulpfile.js` file:

`require.extensions['.less'] = function(m, file) { m._compile('', filename); };`

This way `.less` files should be ignored when Gulp is trying to pre-compile React components with `gulp-render` plugin.
