### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by mhuggins** [kriasoft/react-starter-kit#580]
I just downloaded v0.5.0 to set up a new app.  I had to make a few adjustments in order to get it to work, including:

* Added a `.babelrc` file:

    ```json
    {
      "presets": ["stage-2", "es2015"]
    }
    ```
* Installed babel-core: `npm install babel-core --save`
* Installed babel-cli: `npm install babel-cli`

Now that it's running (via `npm start`), I was able to open http://localhost:3000 as expected.  However, I'm seeing an error in the Chrome console.

> Uncaught SyntaxError: Unexpected token <

![Unexpected token](https://cloud.githubusercontent.com/assets/169093/14583915/e774a5ac-03ed-11e6-9696-45374d9f542a.png)

It looks like the issue is that `/assets/main.js?xxxxx` is returning HTML, but fetching via curl shows the correct Content-Type as "text/html; charset=utf-8".  Not sure if there's a way around this or if it's even worth worrying about, but seeing an error in the console is always worrisome.

Thanks!

**Comment by mhuggins** [comment]
Not sure if it's related as well, butthe index page and the about page have the page title set to "Error".  Other pages have an appropriate title as far as I can tell.

**Comment by koistya** [comment]
@mhuggins the `webpack-dev-middleware` when used in watch mode, doesn't write client-side files on disk, this middleware is injected into Browsersync dev server (localhost:3001), so when you try to open localhost:3000/main.js file, it returns 404 html page, which cannot be parsed as JavaScript..

**Comment by koistya** [comment]
@mhuggins please, let me know what approach from those three works best for you.

**Comment by mhuggins** [comment]
If I access via port 3001, then I no longer see the error.  I assumed it was just a development issue, in which case I'm not really worried about it.  Just thought it was worth making sure it's not a legit problem though.

Thanks!

**Comment by minhnguyenwp** [comment]
Hi guys, 
It happens when i deploy on the server. 
Could you teach me how to deploy on server as right way. 
1. I run : yarn run build -- --release --docker
2. And push source build to the server. 
3. I run : npm install 
4. test: npm start 
5. pm2 start server. 
and  i have :3000 is running. 
But ISSUE: Uncaught SyntaxError: Unexpected token < happens. and that's not same as localhost:3001 

what should i do now?
