### ISSUE TITLE
assets versioning

### ISSUE THREAD

**Issue by jvillasante** [kriasoft/react-starter-kit#59]
What would be the best way to add assets versioning to this? Both for css and javascript.

**Comment by koistya** [comment]
You may want to plug [gulp-rev](https://github.com/sindresorhus/gulp-rev) (appends content hashes) and [gulp-rev-replace](https://github.com/jamesknelson/gulp-rev-replace) (updates references to those files) into your `gulpfile.js`.

**Comment by yanivefraim** [comment]
+1 
Can I add a PR for this one?

**Comment by koistya** [comment]
If you're using Webpack, it allows to append hash strings to the output files. Take a look:

http://webpack.github.io/docs/long-term-caching.html

**Comment by koistya** [comment]
I'm going to close this one as it was resolved I think.
