### ISSUE TITLE
Question: how do I get reference to the store from within the Footer

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [kriasoft/react-starter-kit#595]
Hi,
I need to use store.dispatch from the Footer. But I'm so novice that I even don't know where to look for.

**Comment by langpavel** [comment]
Hi. Which store? :-) Do you using `master` branch? On master there is no concrete implementation of flux.

In `feature/redux` branch you can use [`react-redux`](https://github.com/reactjs/react-redux#react-redux) [`connect`](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) API
