### ISSUE TITLE
Jade has been renamed

### ISSUE THREAD

**Issue by akaRem** [kriasoft/react-starter-kit#606]
I've tried to install packages from latest master and such warning appeared:
> npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade

**Comment by akaRem** [comment]
upd:
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
appeared too

**Comment by akaRem** [comment]
not sure which components are outdated, but please take a look

**Comment by langpavel** [comment]
@akaRem Are you a bot? :-)

I was try to update `jade` to `pug` but it needs more work then looks like. Also, `jade` is dependency of `frontmatter` (I'm not sure) and this is issue with third party package too. I stopped working on, but you can discover it deeply and report or ping issue of affected package.
