### ISSUE TITLE
install packages as global

### ISSUE THREAD

**Issue by akaRem** [kriasoft/react-starter-kit#608]
I've tried to install packages from latest master and such warning appeared:

> npm WARN prefer global marked@0.3.5 should be installed with -g
> npm WARN prefer global jsonlint@1.6.2 should be installed with -g
> npm WARN prefer global colorguard@1.1.1 should be installed with -g

not sure which component trows this warning but please take a look

**Comment by langpavel** [comment]
@akaRem There is no way for package to install dependencies as global dependencies.

This is hint for npm user. You can install globally these dependencies on your computer.

Please, look at `preferGlobal` in `package.json` documentation at `npm` pages.

This is common `npm` behavior. Please close this issue.

**Comment by akaRem** [comment]
Thank you for explanation
