### ISSUE TITLE
jade has been rename to pug

### ISSUE THREAD

**Issue by tosone** [kriasoft/react-starter-kit#628]
jade has been rename to pug, https://github.com/pugjs/pug

**Comment by upq** [comment]
I recommend switching to handlebars

**Comment by langpavel** [comment]
@upq I recommend switching to React :-)
koistya is preparing something in #613, I believe there will not be need for any other template language after merged.

**Comment by upq** [comment]
@langpavel haha even better +1

**Comment by tomByrer** [comment]
For basic templating, I like handlebars the best.
For writing HTML, I like Jade/Pug since it is easy to scan & less typing.  Some bugs (like comments) will be fixed in 2.0.

**Comment by joernroeder** [comment]
crosslink #606

**Comment by arvigeus** [comment]
Since jade is no longer used, I think this issue should be closed (also #606)
