### ISSUE TITLE
Styles are not applied after.

### ISSUE THREAD

**Issue by upq** [kriasoft/react-starter-kit#630]
When I make changes to a scss file or add a new one everything goes fine until you refresh the page or relaunch the server,

You need to reserve the scss file for the changes to take effect again.
 Not sure what the source of the problem is , but this is the case with a freshly cloned RSK copy...

**Comment by langpavel** [comment]
> When I make changes to a scss file or add a new one everything goes fine until you refresh the page or relaunch the server

*until* or *when*?

**Comment by upq** [comment]
Until.

**Comment by langpavel** [comment]
Still... I'm not sure if I understand you.

1. You run `npm start`, editing, editing, everything refreshing well, still editing...
    Then you Ctrl+R, It's OK but editing more and nothing happens?
2. You run `npm start`, editing, editing, everything refreshing well, still editing...
    Then you restart server, It's OK but editing more and nothing happens?

**Comment by upq** [comment]
None, run npm start editing everything is good, REFRESH everything is not,
to make it work you have to save scss file again.
