### ISSUE TITLE
Q: how to switch off server-side rendering?

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [kriasoft/react-starter-kit#634]
I desperately need this functionality to be able to produce static site.

PS: I am aware of https://github.com/koistya/react-static-boilerplate

**Comment by koistya** [comment]
I think @frenzzy is working on adding `--static` flag to the build script, making it generate only the static portion of the site. But that's not done yet.

**Comment by langpavel** [comment]
Why somebody wants to switch off server side rendering???

**Comment by Dmitry-N-Medvedev** [comment]
@langpavel,
1. react-starter-kit is just awesome for development. awesome.
2. big apps is not always an option. oftentimes, one has to implement just a simple app with few screens that must run on the client-side.
