### ISSUE TITLE
feature/intl : Material-ui does'nt works on safari (mac, ios)

### ISSUE THREAD

**Issue by mika75** [kriasoft/react-starter-kit#639]
Material-ui does'nt works on safari (mac, ios).

step to reproduce : 

clone : branch feature/intl
add 

`"material-ui": "0.14.4"`, to `package.json`

and add some material-ui components.

All events are breaks

Safari console 

`[React Intl] The Intl APIs must be available in the runtime, and do not appear to be built-in. An Intl polyfill should be loaded.↵See: http://formatjs.io/guides/runtime-environments/"`

**Comment by mika75** [comment]
To solve it add

```import './serverIntlPolyfill';```

to 

```/src/client.js```

**Comment by langpavel** [comment]
This should be solved clever.
References:

 - [I18n in JavaScript (react-intl wiki)](https://github.com/yahoo/react-intl/wiki#i18n-in-javascript)
 - [How to Polyfill Browsers (formatjs.io guides)](http://formatjs.io/guides/runtime-environments/#polyfill-browsers)
 - [Intl.js and Browserify/webpack (Intl.js GitHub)](https://github.com/andyearnshaw/Intl.js#intljs-and-browserifywebpack)

**Comment by mika75** [comment]
Yes you're right. 
What do you think of create (like serverIntlPolyfill) a file called ```clientIntlPolyfill.js```.
then I include it in ```client.js``` import './clientIntlPolyfill';

clientIntlPolyfill may like 

```
import areIntlLocalesSupported from 'intl-locales-supported';

import { locales } from './config';

if (window.Intl) {
  // Determine if the built-in `Intl` has the locale data we need.
  if (!areIntlLocalesSupported(locales)) {
    // `Intl` exists, but it doesn't have the data we need, so load the
    // polyfill and replace the constructors with need with the polyfill's.
    const IntlPolyfill = require('intl');
    Intl.NumberFormat = IntlPolyfill.NumberFormat;
    Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
  }
} else {
  // No `Intl`, so use and load the polyfill.
  window.Intl = require('intl');
}

```

**Comment by langpavel** [comment]
```js
import areIntlLocalesSupported from 'intl-locales-supported';

import { locales } from './config';
```
Bad idea to import `config.js` See #633 
```js

if (window.Intl) {
  // Determine if the built-in `Intl` has the locale data we need.
  if (!areIntlLocalesSupported(locales)) {
    // `Intl` exists, but it doesn't have the data we need, so load the
    // polyfill and replace the constructors with need with the polyfill's.
    const IntlPolyfill = require('intl');
```
This will pack polyfill into bundle don't matter if it will be really used.
```js
    Intl.NumberFormat = IntlPolyfill.NumberFormat;
    Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
  }
} else {
  // No `Intl`, so use and load the polyfill.
  window.Intl = require('intl');
```
So this, bundle, don't matter if it will be really used.
```js
}
```

Code splitting and `require.ensure` should be used here, before application is loaded. This means entire new entrypoint for client application.

**Comment by bravo-kernel** [comment]
:tractor: (as I would like to track this issue)

**Comment by ulani** [comment]
@mika75   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
