### ISSUE TITLE
normalize.css / Material-ui

### ISSUE THREAD

**Issue by mika75** [kriasoft/react-starter-kit#640]
There is a conflict between normalize and Material-ui.

When normalize is imported ```App.scss```

```@import '../../../node_modules/normalize.css/normalize.css';```

This breaks all material-ui button

You can see it here : http://www.hostingpics.net/viewer.php?id=162453normalize.png

**Comment by langpavel** [comment]
@mika75 What do you suggest?

**Comment by mika75** [comment]
I will post it if i found something

**Comment by mika75** [comment]
It's a metarial-ui bug -> https://github.com/callemall/material-ui/issues/4008
It will be fixed with ->https://github.com/callemall/material-ui/pull/3953
