### ISSUE TITLE
Need help in implementing an API clients and use this for authentication.

### ISSUE THREAD

**Issue by kinger-de** [kriasoft/react-starter-kit#648]
Hi,

I'm not very familiar with this starter kit. But I've played around a bit in it and I like it quite well so far.

Now I wanted to write my first application so. The application is to get all the data from an external API. The application itself is to save nothing and be only a surface for the API. (Therefore, I have also sought an React starter kit and found this one.)

If I have understood correctly, I have to implement my API calls under /src/data. Just as in the example of news. Correct?

But I have a special requirement. The API calls always a certain token must be passed with (WSSE token), which contains the user's authentication. How can I do that best?

The entire application should be behind a login.
The authentication of the user on the application itself must also be checked against the API. Even with the special token. Now I do not know how I implement authentication. I Do it with passport.js? Is there something might already have a startegy? I Implement the authentication call itself under /src/data and then use these with passport.js?

I hope there are not too many questions and look forward to your answers.

greetings

**Comment by langpavel** [comment]
Did you ask on Gitter channel? You probably don't need passport.js. I resolved this by setting httponly cookie after successful authorization call to API, then client is capable to deliver cookie with token with every request. This is also more secure because token is not exposed to client side JavaScript

**Comment by langpavel** [comment]
Note you must set "credentials": "include" when calling fetch. I also have modified version of fetch which is capable to forward token in server side calls.

**Comment by karthikkolli** [comment]
@langpavel Can you share the version of fetch which forwards token in server side calls?

**Comment by langpavel** [comment]
I plan this, but at first I must clean some code. It's connected with redux middleware.

**Comment by kinger-de** [comment]
I am also interested in your customized version of the fetch script. That sounds what I'm looking for.

Can I build the token before the first API call? And, can the token looks like I want. (Need some X-WSSE headers)

I imagine it as follows. The user enters his login data (username and password). Then I build the token I need and send it for authentication to the API. If I get a 200 status code, the user is logged in. The user can then use the application. And every time I get data from the API I send the token with the request. After 30 minutes or after the user logs out, the token will be destroyed and the user is redirect to the login.

I hope you understand what i mean. It's hard to describe for me exactly what I want, because English is not my native language.

greetings

**Comment by SmboBeast** [comment]
@langpavel @kinger-de I know this is an old post, but any insight on how you solved this?

How were you able to check to see if the user is authenticated before loading a new route?  My auth token is in localStorage, but I don't seem to have access to it from the async action method in the routes.

**Comment by langpavel** [comment]
@SmboBeast You cannot depend on `localStorage` for SSR.. You should design a mechanism for example with Redux to pass ACL to store. Of course you should set store on SSR and you can query it in routes.

**Comment by SmboBeast** [comment]
Yes!  Thank you @langpavel 

I did just that.  I basically use a cookie to store my token.  On SSR, I write things out to state using Redux and my routes take advantage of all of this.  

Thank you Sir for confirming.

**Comment by ulani** [comment]
@karthikkolli   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
