### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by yuseferi** [kriasoft/react-starter-kit#649]
When I try to install with

`npm install`

I faced 

_

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
> npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
> npm WARN react-addons-test-utils@15.0.2 requires a peer of react@^15.0.2 but none was installed.
> _ 

and after that when I try to  start with 
`npm start`  
_

> babel-node tools/run start

/var/www/html/MyApp/tools/run.js:20
  const task = typeof fn.default === 'undefined' ? fn : fn.default;
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at loader (/var/www/html/MyApp/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js](/var/www/html/MyApp/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at _repl2.default.start.prompt (/var/www/html/MyApp/node_modules/babel-cli/lib/_babel-node.js:171:48)
    at Object.<anonymous> (/var/www/html/MyApp/node_modules/babel-cli/lib/_babel-node.js:172:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.42
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/MyApp/npm-debug.log
_

after some search  I add **"babel-core": "latest",** to package.json but not changed.
where is the problem?

**Comment by tprzepiorka** [comment]
Upgrading to Node 6.1.0 fixed this for me.

**Comment by Pravin-Parkhi** [comment]
I upgraded node to 6.0.1, npm to 3.8.6
Still facing the same problem.

**Comment by frenzzy** [comment]
Need to enable [strict mode](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Strict_mode)
..for example you can configure [transform-strict-mode](http://babeljs.io/docs/plugins/transform-strict-mode/) babel plugin or keep [googling](https://www.google.com/#q=node+strict+mode)

**Comment by ulani** [comment]
@yuseferi   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
