### ISSUE TITLE
Why Mocha over Jest

### ISSUE THREAD

**Issue by rterysen-openroad** [kriasoft/react-starter-kit#657]
I was curious as to why you made the move from jest to mocha?

**Comment by marod424** [comment]
I am also curious

**Comment by langpavel** [comment]
I have no opinion, I'm also curious why :-)

**Comment by marod424** [comment]
My curiosity stems from the fact that there was at one point a switch from jest to mocha.  Did anything catalyze that switch?  I am not advocating jest over mocha, I don't have the scope for such a decision.  Rather, I was hoping to get some feedback from anyone that has experience with both testing frameworks.

**Comment by langpavel** [comment]
I understood. But I'm not interested in much. Follow creators of React and you give answers.

**Comment by cpojer** [comment]
Hey everyone!

We recently had two major Jest releases which significantly improve the framework and added snapshot testing. Please check out facebook.github.io/jest/blog/2016/07/27/jest-14.html and facebook.github.io/jest/blog/2016/09/01/jest-15.html

I'm happy to help anyone who wants to try out Jest. We have a support channel on discord: http://facebook.github.io/jest/support.html :)

**Comment by jabacchetta** [comment]
Loving the new Jest — snapshot testing is a game changer.

**Comment by langpavel** [comment]
Hi. I'm seriously thinking about move to jest. Have anybody good resources or will be someone able to participate on new PR?

**Comment by piglovesyou** [comment]
@cpojer By reading this doc, it's confusing to know relation between Mocha and Jest in React Starter Kit. It's good time to maintain it, isn't it.
https://github.com/kriasoft/react-starter-kit/blob/master/docs/testing-your-application.md#testing-your-application

**Comment by langpavel** [comment]
`jest` is already in

**Comment by langpavel** [comment]
Documentation indeed needs improve
