### ISSUE TITLE
Update Starter kit to Relay 0.9?

### ISSUE THREAD

**Issue by CoericK** [kriasoft/react-starter-kit#674]

**Comment by koistya** [comment]
This starter kit doesn't contain Relay at the moment so that developers could integrate Flux library of their choice (Relay, Redux + some Ajax tools, Apollo, something else)

**Comment by CoericK** [comment]
Oh thanks for your answer.

**Comment by upq** [comment]
@koistya is there anything to do after using implementing relay to make everything isomorphic or will it have side effects on rendering on the server.

**Comment by koistya** [comment]
@upq originally Relay wasn't isomorphic friendly, so this guy forked it and applied a few fixes to make it work better in isomorphic context: https://github.com/denvned/isomorphic-relay. Though, I need to check the latest version of Realy, maybe it's already suitable for use in isomorphic apps out of the box..
