### ISSUE TITLE
scss file in new version nodejs 6.2

### ISSUE THREAD

**Issue by chienvuhoang** [kriasoft/react-starter-kit#677]
Hi all, at new version of reactjs-startkit. How i can write with scss file
i'm trying rename css to scss but not work.
Thanks all

**Comment by koistya** [comment]
First thing you need to add sass-loader by running `npm install sass-loader --save-dev`, then watch for hints in error messages, which should give you an idea where the problem is.. for example, the `.scss` files must contain only the code that's compatible with Sass parser.

**Comment by chienvuhoang** [comment]
@koistya thanks so much :)
