### ISSUE TITLE
static content intl support

### ISSUE THREAD

**Issue by awesomejerry** [kriasoft/react-starter-kit#684]
Hi all, really love this kit for handling so much cool stuff together. After merged with feature/react-intl, I was able to define messages for components, but I wonder if this can be extended to static content under src/content folder.
Possible usage might be:

```
src
--- content
------ about.en.jade
------ about.zh_Hant.jade
```

based on what locales you have defined in src/config.js

**Comment by langpavel** [comment]
You can customize yourself handling of static content loading.
Copy and resolve this checklist:

 * [ ] update `src/data/queries/content.js` to accept and handle `locale` argument (See `src/data/queries/intl.js` as reference).
 * [ ] This argument should be optional, defaulting to `req.language` (optional behavior)
 * [ ] in `src/routes/content/index.js` extend GraphQL query with `locale` argument

**Comment by AwesomeJerry** [comment]
Thanks for the checklist, making it so clear about implementing. Will make a PR when I have the time to resolve it :)

**Comment by langpavel** [comment]
Great, don't forget to make PR against `feature/react-intl` branch and keep backward compatibility ;-)
