### ISSUE TITLE
"dangerouslySetInnerHTML" breaks Facebook's React plugin for Chrome Developer Tools

### ISSUE THREAD

**Issue by jtiscione** [kriasoft/react-starter-kit#694]
Facebook's new Chrome Developer Tools plugin works well if you open up localhost:3000 and poke around. But you can only see a few levels deep into the react hierarchy- until it hits a div inside the ContentPage component that has a "dangerouslySetInnerHTML" attribute, which it thinks is a leaf node. So ContentPage is actually preventing the debugger from getting inside to the code that actually needs debugging.
What is the dangerouslySeetInnerHTML for anyway?

**Comment by langpavel** [comment]
Content of dangerouslySetInnerHTML is set to div via innerHTML or raw string insertion on server, so it is not controlled by React. There is no interest from react about content, no validation so content can break Dom or introduce vulnerabilities.. This is reason for its name.

**Comment by jtiscione** [comment]
You're right- I was examining the wrong URL in Chrome.
