### ISSUE TITLE
Test Watch Fails on Darwin?

### ISSUE THREAD

**Issue by JimLynchCodes** [kriasoft/react-starter-kit#695]
I'm using Mac OSX 10.11.4

When I scaffold a fresh version of this project and run: `npm run test:watch` it prints this error:

![react-start-kit-project_ _-bash_ _105x24](https://cloud.githubusercontent.com/assets/5354163/15986893/04bd4030-2fe3-11e6-985c-9d07c48c4cd0.png)

The npm-debug.log file shows this:
info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test:watch' ]
2 info using npm@3.8.6
3 info using node@v6.0.0
4 verbose stack Error: missing script: test:watch
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:449:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:436:12)
5 verbose cwd /Users/jim/Git-Projects/React-Start-Kit-Project
6 error Darwin 15.4.0

---

Does anyone know why this is happening and how I can fix it? :( 

`npm test` and `npm run test` seem to work fine.

**Comment by ulani** [comment]
@JimLynchCodes   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
