### ISSUE TITLE
Integrate React Hot Reload

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#7]
[![React Hot Reload](https://dl.dropboxusercontent.com/u/16006521/Screens/react-hot-reload.png)](http://gaearon.github.io/react-hot-loader/)
http://gaearon.github.io/react-hot-loader/

**Comment by goatslacker** [comment]
Definitely this. Do you need help tackling any of these things?

**Comment by koistya** [comment]
Trying to figure out, is there a way to use both Browser-Sync and React-Hot-Loader..

**Comment by gaearon** [comment]
Why user BrowserSync over Webpack? It can handle CSS just fine.

**Comment by koistya** [comment]
@gaearon with [BrowserSync](http://www.browsersync.io/) you can open your website in different browsers and even on different devices (it creates HTTP tunnel with external IP to make things simple for connecting from devices other than your local PC), then when you navigate through the site, all the click, scroll, form data events are synchronized accross all the connected browsers which makes testing in different browsers supper easy.

Check this article by Addy Osmani http://addyosmani.com/blog/browser-sync/

**Comment by gaearon** [comment]
I get it now, thanks! That's a nice tool.

**Comment by creat-or** [comment]
:+1: 
Here are some slides of a local presentation about that topic. Isn't very detailed, but enough for me to be excited about it :)
http://okonet.ru/slides/reactive-development/

**Comment by koistya** [comment]
React Hot Transform was integrated into the starter kit. It plugs into the app when you run the site in a "watch" mode by hitting `npm start` (see `tools/start.js`).
