### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by parthipansowmi** [kriasoft/react-starter-kit#700]
Server not starting after upgrade to Node 6.0

**Comment by frenzzy** [comment]
@parthipansowmi What error do you see? Your environment? Version of RSK?

**Comment by parthipansowmi** [comment]
This is error I am getting

throw new Error('Please install sqlite3 package manually');
            ^
Error: Please install sqlite3 package manually
    at new ConnectionManager
(D:\MyApp\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:25:13)
    at new SqliteDialect
(D:\MyApp\node_modules\sequelize\lib\dialects\sqlite\index.js:12:28)
    at new Sequelize
(D:\MyApp\node_modules\sequelize\lib\sequelize.js:233:18)
    at Object.<anonymous> (D:\MyApp\build\webpack:\data\sequelize.js:13:19)
    at __webpack_require__ (D:\MyApp\build\webpack:\webpack\bootstrap
a8bb5fb394643a4b9120:19:1)
    at Object.module.exports.Object.defineProperty.value
(D:\MyApp\build\webpack:\data\models\index.js:10:1)
    at __webpack_require__ (D:\MyApp\build\webpack:\webpack\bootstrap
a8bb5fb394643a4b9120:19:1)
    at Object.<anonymous> (D:\MyApp\build\webpack:\core\passport.js:18:1)
    at __webpack_require__ (D:\MyApp\build\webpack:\webpack\bootstrap
a8bb5fb394643a4b9120:19:1)
    at Object.<anonymous> (D:\MyApp\build\webpack:\server.js:21:1)
    at __webpack_require__ (D:\MyApp\build\webpack:\webpack\bootstrap
a8bb5fb394643a4b9120:19:1)
    at D:\MyApp\build\webpack:\webpack\bootstrap a8bb5fb394643a4b9120:39:1
    at Object.<anonymous> (D:\MyApp\build\webpack:\webpack\bootstrap
a8bb5fb394643a4b9120:39:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

On Tue, Jun 14, 2016 at 12:11 AM, Vladimir Kutepov <notifications@github.com

**Comment by frenzzy** [comment]
Try to [install sqlite3](https://github.com/mapbox/node-sqlite3#installing) package manually, if it doesn't help, reinstall node modules:
```shell
rm -rf node_modules
npm install
```

**Comment by simeg** [comment]
I solved this by running:

    npm rebuild

**Comment by colinharris05** [comment]
I this same error when trying to push my repo to heroku. Fixed it by specifying

`"engines": {
    "node": "5.0"
}`

in my `package.json`.

**Comment by christophemarois** [comment]
@colinharris05 fixed it for me. For my specific node version, it was: `"engines": { "node": "7.4.0" }`

**Comment by ulani** [comment]
@parthipansowmi   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
