### ISSUE TITLE
question about import path

### ISSUE THREAD

**Issue by DominikeCruz** [kriasoft/react-starter-kit#705]
if I change ...

(JS import)
in 'tools/webpack.config.js' line 52 
- (-) path.resolve(__dirname, '../node_modules/react-routing/src'),
- (+) path.resolve(__dirname, 'react-routing/src'),

and 

(CSS import)
in 'src/components/App/App.css' line 10
- (-) @import '../../../node_modules/normalize.css/normalize.css';
- (+) @import 'normalize.css/normalize.css';

Everything seems to be working fine...
but, #499 reply also use '../../../node_modules'

is it to evidence that is 3rd-party?

**Comment by stupidisum** [comment]
I think that's a refactor bug of webstorm.

At first it's 'some-lib/lib.js' in 'src/a.js'
After a file-position move, it becomes
'../../node_modules/some-lib/lib.js' in 'src/b/a.js'

**Comment by DominikeCruz** [comment]
I questioned because I usually don't see node_modules be used on paths.

But it's used just in path.resolve and css import, and make sense to ensure that it will work/seems fine in most editors/IDE.
