### ISSUE TITLE
After applying suggested solution, still seeing SyntaxError: expected expression <

### ISSUE THREAD

**Issue by gordillo99** [kriasoft/react-starter-kit#706]
Still seeing issue described on https://github.com/kriasoft/react-starter-kit/issues/407

<img width="1437" alt="screen shot 2016-06-15 at 9 18 18 pm" src="https://cloud.githubusercontent.com/assets/12925476/16105395/ea2a1ebe-333e-11e6-9b83-5ebf244bfff1.png">

even after applying solution suggested by https://github.com/kriasoft/react-starter-kit/issues/370

```
bs.init({
            notify: DEBUG,
            ui: DEBUG ? { port: 3001 } : false,
            proxy: {
              target: host,
              middleware: [wpMiddleware, ...hotMiddlewares],
            },
```

**Comment by kaivi** [comment]
Cloudflare is known to break JS, I've gotten that error before. Do you get the same error also without any proxies?

**Comment by gordillo99** [comment]
At first I was seeing only after I deployed to Heroku, and it was working fine locally. However, now I'm seeing the error in both Heroku and locally if I use Firefox. It work fine with Chrome.
