### ISSUE TITLE
Use eslint instead of jshint

### ISSUE THREAD

**Issue by dmnd** [kriasoft/react-starter-kit#71]
Eslint supports JSX and some ES6 features. That will allow you to get rid of all those `/* jshint ignore:start */`. 

Note that right now ES6 imports are not yet implemented by eslint, but they should be coming soon.

**Comment by koistya** [comment]
:+1:

**Comment by sdiaz** [comment]
:+1:

**Comment by ivanoats** [comment]
Until ESLint supports ES6 modules, you can also use JSCS and Esprima-fb to lint JSX / ES6 code. See config in https://youtrack.jetbrains.com/issue/WEB-13511
