### ISSUE TITLE
Can't get compression working 

### ISSUE THREAD

**Issue by sap9433** [kriasoft/react-starter-kit#712]
Added compression at the top 

import compression from 'compression';

```
app.use(compression());
app.use(express.static(path.join(__dirname, 'public')));
app.use(cookieParser());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
```

still not getting compressed. Why ?

**Comment by itaied246** [comment]
Got any progress with it?

**Comment by itaied246** [comment]
Found [this](https://github.com/kriasoft/react-starter-kit/issues/644) answer. Works for me.

**Comment by MinJieLiu** [comment]
It does not have any effect on my computer @sap9433 Have you solved this problem yet?

**Comment by langpavel** [comment]
This is not RSK issue, look into express instead

**Comment by langpavel** [comment]
Btw can you provide more info? Why you guess compression is not working?

**Comment by langpavel** [comment]
If you discover that it is related to RSK, please reopen.
Anyway keep us informed
