### ISSUE TITLE
GET  main.js [HTTP/1.1 404 Not Found 10ms]

### ISSUE THREAD

**Issue by gordillo99** [kriasoft/react-starter-kit#713]
I'm getting 

`Failed to load resource: the server responded with a status of 404 (Not Found) main.js?d90f4b627e381515459b`

on the browser console both using the latest version of the master branch and when using version 0.5.1 of the react-starter-kit. I'm seeing this problem in the production environment. Any suggestions on how to fix that?

**Comment by frenzzy** [comment]
[Answer is here](https://github.com/kriasoft/react-starter-kit/issues/427#issuecomment-178740335)

**Comment by kongliangyu** [comment]
any findings gordillo99? I just ran the same issue and haven't figure it out yet
