### ISSUE TITLE
Adding Bootstrap css from CDN

### ISSUE THREAD

**Issue by Aleyasen** [kriasoft/react-starter-kit#715]
In the react-bootstrap documentation, they [mentioned](https://react-bootstrap.github.io/getting-started.html) that css file is not included and the simplest way to include is using CDN. 
>  Because React-Bootstrap doesn't depend on a very precise version of Bootstrap, we don't ship with any included css. However, some stylesheet is required to use these components. How and which bootstrap styles you include is up to you, but the simplest way is to include the latest styles from the CDN.

```html
!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap-theme.min.css">
```html

I am wondering, what is the best place to add these css files from CDN. In general, I couldn't find a good and simple way to add new external css.

**Comment by Aleyasen** [comment]
Sorry, I just found out the gitter channel for the project and ask my question there, since it is not an issue.

**Comment by frenzzy** [comment]
Also please look at this PR: https://github.com/kriasoft/react-starter-kit/pull/646
