### ISSUE TITLE
Styles from modules not loading to page

### ISSUE THREAD

**Issue by iNikNik** [kriasoft/react-starter-kit#72]
Hello! Im just using this project and have a issue - **styles from modules not loading to page**
I'm tried to change this file https://github.com/kriasoft/react-starter-kit/blob/master/src/components/App/App.less:
```css
.App {
  background-color: red !important;
}
```
.. but after reloading nothing happens (no style elements in DOM, no style attachet to div). If i change files from this directory https://github.com/kriasoft/react-starter-kit/tree/master/src/styles - everything works perfect.

**Comment by koistya** [comment]
@iNikNik thanks for the report! It should be fixed now.

**Comment by iNikNik** [comment]
@koistya big thanks for hotfix !)
