### ISSUE TITLE
FB redirecting to port 3000 and everything stops working

### ISSUE THREAD

**Issue by gordillo99** [kriasoft/react-starter-kit#720]
I'm currently working on logging with fb, and I noticed that I get redirected to port 3000 (in the dev environment).

everything works fine until this code runs
```
app.get('/login/facebook/return',
  passport.authenticate('facebook', { failureRedirect: '/login', session: false }),
  (req, res) => {
    console.log('in the return callback');
    const expiresIn = 60 * 20; // 20 min
    const token = jwt.sign(req.user, auth.jwt.secret, { expiresIn });
    res.cookie('id_token', token, { maxAge: 1000 * expiresIn, httpOnly: true });
    res.redirect('/');
  }
```

browsersync seems to be running on the port 3001 so I was wondering if it's possible to add a check for the dev environment to redirect to the right port.

**Comment by mkubliniak** [comment]
This is an old (and closed) issue, but in case someone has the same problem, I just created a pull request with fix: #980.
