### ISSUE TITLE
How do I include .js file as in .html file

### ISSUE THREAD

**Issue by monotonique** [kriasoft/react-starter-kit#723]
Hi I am having a .js file which needs to be included in
\<head\>\</head\> with \<script\>\</script\> tag since the script need the `window` of the browser

I am curious about how to do this.

**Comment by koistya** [comment]
Do you need to minify that script, or just to include as it is into the `<head>` section of an HTML page?

**Comment by srobinson** [comment]
add your file to src/public
https://github.com/kriasoft/react-starter-kit/tree/master/src/public

/tools/copy task will copy it into the build directory
https://github.com/kriasoft/react-starter-kit/blob/master/tools/copy.js

you can then include it from index.jade
https://github.com/kriasoft/react-starter-kit/blob/master/src/views/index.jade

**Comment by monotonique** [comment]
I see.

frankly speaking, I would like to import Firebase in the app

```
  <script src="https://www.gstatic.com/firebasejs/3.1.0/firebase.js"></script>
  <script>
    // Initialize Firebase
    // TODO: Replace with your project's customized code snippet
    var config = {
      apiKey: "apiKey",
      authDomain: "projectId.firebaseapp.com",
      databaseURL: "https://databaseName.firebaseio.com",
      storageBucket: "bucket.appspot.com",
    };
    firebase.initializeApp(config);
  </script>
```

**Comment by monotonique** [comment]
if I make it right, I should do something like this

```
head
    script(src="https://www.gstatic.com/firebasejs/3.1.0/firebase.js")
    script.
      var config = {
        apiKey: "apiKey",
        authDomain: "projectId.firebaseapp.com",
        databaseURL: "https://databaseName.firebaseio.com",
        storageBucket: "bucket.appspot.com",
      };
      firebase.initializeApp(config);
```

I will check if it works :P

**Comment by langpavel** [comment]
Not relevant now. Open new issue of you are still competing with this
