### ISSUE TITLE
How do I include i18n translations ?

### ISSUE THREAD

**Issue by hab1** [kriasoft/react-starter-kit#724]
Hi everyone,

I would like to have different translations for my components by using i18n but I am struggling to implement the code. Any tip ?

I was using the following reference to adapt it to the code : 
https://github.com/i18next/react-i18next/tree/master/example

How can I make it?

In this example, I struggle with 
`ReactDOM.render(
  <I18nextProvider i18n={ i18n }><App /></I18nextProvider>,
  document.getElementById('app')
);`

Where should I adapt this code? In client.js for the react-starter-kit ?

Thanks in advance

**Comment by srobinson** [comment]
use this as a reference
https://github.com/kriasoft/react-starter-kit/tree/feature/react-intl

**Comment by hab1** [comment]
I didn't see this branch, sorry

**Comment by nisargrthakkar** [comment]
Any one help us to how to ingratiate https://github.com/i18next/react-i18next with react starter kit
