### ISSUE TITLE
post method not working

### ISSUE THREAD

**Issue by parthipansowmi** [kriasoft/react-starter-kit#725]
When I submit login page getting cann't post.

It is working if I use method='get' in the form submission

**Comment by langpavel** [comment]
Can you provide some code? Or more information?

**Comment by parthipansowmi** [comment]
Hi

Here is the code

**Comment by langpavel** [comment]
@parthipansowmi Sorry, where?

**Comment by langpavel** [comment]
See issue as I see it: https://github.com/kriasoft/react-starter-kit/issues/725

There is no attachment

**Comment by langpavel** [comment]
I'm closing this, sorry for that, I will reopen this when you provide more info..
