### ISSUE TITLE
React Tab not appearing in Chrome Dev Tools

### ISSUE THREAD

**Issue by DanielHoffmann** [kriasoft/react-starter-kit#727]
The React Tab does not appear in the Chrome Dev Tools, I can't figure out why, it is working fine on other websites on the same browser.

**Comment by frenzzy** [comment]
Maybe because your `main.js` returns 404 or 500 error? Have you looked at the Network tab?

**Comment by DanielHoffmann** [comment]
Yeah you were right, I was getting an error on that file, oddly it went away on its own after a few restarts. Thanks for your help!
