### ISSUE TITLE
JSX props should not use .bind() react/jsx-no-bind

### ISSUE THREAD

**Issue by hab1** [kriasoft/react-starter-kit#729]
When checking my files with `npm run lint` I get the following error :

> \src\client.js 112:15
> error JSX props should not use .bind() react-no-bind
> **? 1 problem <1 error, 0 warnings>**

The line referring to this error ( render: render.bind(undefined, container, location.state ) ) :

```
UniversalRouter.resolve(routes, {
      path: location.pathname,
      query: location.query,
      state: location.state,
      context,
      render: render.bind(undefined, container, location.state),
    }).catch(err => console.error(err)); // eslint-disable-line no-console
  }
```

Any idea of why is this happening ?

Also, when I run "`npm run lint`" , at the end I get 2 errors with the code ELIFECYCLE :

node v6.2.2
npm v3.10.2
code ELIFECYCLE 
@ eslint: `eslint src tools`
and
@ link: `npm run eslint && npm run stylelint`

Could  this be related ?

**Comment by maullerz** [comment]
> render: render.bind(undefined, container, location.state),

in this situation you can just disable eslint rule for this line
` // eslint-disable-line react/jsx-no-bind`

more about this rule here: [rules/jsx-no-bind](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md)

**Comment by hab1** [comment]
Thank you, for those who have the same problem, here is the solution.

```
    UniversalRouter.resolve(routes, {
      path: location.pathname,
      query: location.query,
      state: location.state,
      context,
      render: render.bind( // eslint-disable-line react/jsx-no-bind
        undefined,
        container,
        location.state
      ),
    }).catch(err => console.error(err)); // eslint-disable-line no-console
```

**Comment by frenzzy** [comment]
ref https://github.com/yannickcr/eslint-plugin-react/issues/663
