### ISSUE TITLE
Gulp Deploy to GitHub Pages - No static files

### ISSUE THREAD

**Issue by dmak78** [kriasoft/react-starter-kit#73]
Curious as to why there is a `gulp deploy` task that deploys to Github pages when the build process produces a Node server app. This build doesn't currently work on Github pages. Deploy task works fine, seems to be something that wasn't compensated for in the build process.

Am I missing something?

**Comment by koistya** [comment]
Good catch. We need to either move the Gulp `deploy` task to the FAQ section, describing how to setup this kind of deployment. Or, update the deployment task to make sure it generates all the required static `.html` files during deployment to [GitHub Pages](https://pages.github.com/).

**Comment by majodev** [comment]
How is the progress on this? Will this get implemented?

**Comment by iEricKoh** [comment]
@koistya Could I know how is the progress on this ticket?

**Comment by koistya** [comment]
@iEricKoh I haven't yet started working on this one. Any help is welcome!

**Comment by langpavel** [comment]
This is really old issue.
Feel free to reopen it if you think it may be useful for someone.
