### ISSUE TITLE
componentDidMount does not work

### ISSUE THREAD

**Issue by audi70r** [kriasoft/react-starter-kit#730]
Hello, I'm opening this issue here, but I'm also getting reports that the static react boilerplate project has the same problem. So, I believe that the root cause might be in one of the package updates common to both projects from ~3-5 days ago.

Basically the problem is in the "componentDidMount" method, which does not execute. The actual contents of the app gets rendered, but that particular method is not firing.

I have a backup of all the npm dependencies, so I will continue investigating this issue by deduction and keep you posted. If anybody has the same issue please let me know.

Thanks!

**Comment by koistya** [comment]
@audi70r can you please provide a guidance how to reproduce this issue?

**Comment by audi70r** [comment]
Solved. The problem lied with the code and was not related to any package.
