### ISSUE TITLE
Merge conflicts when merging feature/redux branch with master branch

### ISSUE THREAD

**Issue by pvijeh** [kriasoft/react-starter-kit#732]
conflicting files:

	both modified:   package.json
	both modified:   src/client.js
	both modified:   src/server.js

**Comment by langpavel** [comment]
This merge conflicts are simple to resolve... I know docs saying something different, you should smoothly merge branches...
But I have no privilege to keep this branches up to date with master and it is expensive for @koistya to do this after every merge. You can look at my fork: https://github.com/langpavel/react-starter-kit I have issues enable and I can help you with

**Comment by langpavel** [comment]
@pvijeh As creator of both of feature branches I recommended you to go with feauter/react-intl from my fork. It really shows you how to use redux on `LanguageSwitcher` component

**Comment by pvijeh** [comment]
its actually not simple to resolve the merge conflicts.  which changes do i keep?

**Comment by langpavel** [comment]
@pvijeh Try merge [`feauter/react-intl`](https://github.com/langpavel/react-starter-kit/tree/feature/react-intl) from my fork and I believe this should work for you

**Comment by langpavel** [comment]
Now in sync. Feel free to reopen is you are in trouble..

**Comment by sschenk** [comment]
I'm trying to pull your fork and I'm getting conflicts that can't be auto solved
