### ISSUE TITLE
Declarative routes with GraphQL and Relay

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#736]
I have created the bare minimum **declarative** vs **imperative** routing projects here to play with:

https://github.com/koistya/demos

**RSK** is currently using imperative (or, functional) routes. But if you're using Relay in your project, declarative routes might also be a good option. Here is an example (`routes.json`):

``` json
[
  {
    "path": "/tasks/:status(pending|completed)?",
    "queries": {
      "viewer": "query { viewer }",
      "tasks": "query { tasks(status: $status) }"
    },
    "component": "./routes/TaskList"
  },
  {
    "path": "/tasks/:id(\\d+)",
    "queries": {
      "viewer": "query { viewer }",
      "tasks": "query { task(id: $id) }"
    },
    "component": "./routes/TaskDetails"
  }
]
```

By using a simple loader for Webpack (see [`routes-loader.js`](https://github.com/kriasoft/react-static-boilerplate/blob/master/utils/routes-loader.js)) you can transform such routes into JavaScript during compilation by using wonderful [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp) library. So that when you reference the `routes.json` file in your code (e.g. `import routes from './routes.json'`) it will be transformed into something like this:

``` js
[
  {
    path: '/tasks/:status(pending|completed)?',
    pattern: /^\/tasks(?:\/((?:pending|completed)))?(?:\/(?=$))?$/i,
    keys: [{ name: 'status', ... }],
    queries: {
      viewer: () => Relay.QL`query { viewer }`,
      tasks: () => Relay.QL`query { tasks(status: $status) }`
    },
    component: './routes/TaskList',
    load: () => System.import('./routes/TaskList').then(x => x.default);
  },
  {
    path: '/tasks/:id(\\d+)',
    pattern: /^\/tasks\/((?:[^\/]+?))(?:\/(?=$))?$/i,
    keys: [{ name: 'id', ... }],
    queries: {
      viewer: () => Relay.QL`query { viewer }`,
      tasks: () => Relay.QL`query { task(id: $id) }`
    },
    component: './routes/TaskDetails',
    load: () => System.import('./routes/TaskDetails').then(x => x.default);
  }
]
```

You can find a working example of this approach in the [React Static Boilerplate](https://github.com/kriasoft/react-static-boilerplate) (RSB) project.

**P.S.**: This issue is created solely for discussion. Upvote or downvote this approach, add comments.

Ref #20

**Comment by langpavel** [comment]
DSL (Domain Specific Languages) are awesome. Why we do not use them? Because they are *specific*. Same here.
Do you really think that loader can be better than raw code? I'm skeptic in this..

**Comment by ulani** [comment]
@koistya  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
