### ISSUE TITLE
How to use redux in functional components

### ISSUE THREAD

**Issue by hab1** [kriasoft/react-starter-kit#737]
Hi, I am writing this issue cause I would like to ask for some help in how to use the redux on my functional components. I had a look at the intl-lang branch but I cannot understand how to get the "store" value in it.

My idea is to use my 

> store.getState 

function inside my functional component but I cannot make it happen.

Any help please ?

For example, a functional component : 

```
import React from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './Header.css';
import { Navbar, Nav } from 'react-bootstrap';
import HeaderMenu from '../HeaderMenu';
import cx from 'classnames';

function Header() {
  return (
    <Navbar fluid fixedTop id="Header" className={s.navContainer}>
      <Nav block className={cx(s.HeaderTitle, s.hideOnSmall)}>Project title</Nav>
      <Nav block className={cx(s.HeaderTitle, s.showOnSmall)}>PJT</Nav>
      <HeaderMenu />
    </Navbar>
  );
}

export default withStyles(s)(Header);
```

How can I use the "store" object inside my Header component ? I used the redux branch and it works, just I don't know how to use it within my components.

Should I use actions for retrieving the state instead ??

Thanks in advance!

**Comment by langpavel** [comment]
See how to use `react-redux` here: [LanguageSwitcher.js](https://github.com/kriasoft/react-starter-kit/blob/feature/react-intl/src/components/LanguageSwitcher/LanguageSwitcher.js)
