### ISSUE TITLE
How to secure redux data-initial-state

### ISSUE THREAD

**Issue by fchienvuhoang** [kriasoft/react-starter-kit#738]
Hi all,
Have any way to secure redux data-init-state below image:
<img width="832" alt="screen shot 2016-07-12 at 2 18 11 am" src="https://cloud.githubusercontent.com/assets/4451749/16743510/0bbab816-47d7-11e6-88a3-26e3e60c6165.png">

**Comment by upq** [comment]
+1 
it feels odd seeing everything just laid out there for everybody. I know you can get that data if you want but at least not straight forward like that.

**Comment by frenzzy** [comment]
Enable [Content Security Policy](https://developer.mozilla.org/en/docs/Web/Security/CSP)

**Comment by fchienvuhoang** [comment]
Hello @langpavel how do you think ? :)

**Comment by voquockhanh2** [comment]
+1

**Comment by alexsuslov** [comment]
You need to hide information on the transfer or make not readable?

**Comment by fchienvuhoang** [comment]
yeh, can hide it ?

**Comment by alexsuslov** [comment]
may be base64 ?
console.log(btoa("test"));
dGVzdA==
console.log(atob(btoa("test")));
test

**Comment by fchienvuhoang** [comment]
May be... But it's the best option ? :)

**Comment by alexsuslov** [comment]
there is an option to do bit operations. they are fast.
or https://www.npmjs.com/package/crypto-js

**Comment by fchienvuhoang** [comment]
I argee with you, and I think it's the best way. Thanks @alexsuslov

**Comment by langpavel** [comment]
Security by obscurity is no security at all. If you are unhappy to see this in, you can just delete `data-initial-state` attribute in DOM after it value is readed. But this will do not protect your data.

**Comment by langpavel** [comment]
@alexsuslov If you need decrypt data on client, you need key on client. It is not secure because all you need for decrypting can be achieved

**Comment by fchienvuhoang** [comment]
how to ! :|

**Comment by langpavel** [comment]
Closing this with only real solution from @frenzzy: Enable [Content Security Policy](https://developer.mozilla.org/en/docs/Web/Security/CSP)

**Comment by fchienvuhoang** [comment]
Thanks @langpavel
