### ISSUE TITLE
CSS module ignored except when BrowserSynced

### ISSUE THREAD

**Issue by jdelafon** [kriasoft/react-starter-kit#739]
Let's `npm start`. I create a new component: 

    components/Panel/Panel.js
    components/Panel/Panel.css

In Panel.css:

    .someClassName { border: 4px solid green; }

In Panel.js:

    import s from './Panel.css';
    // use ``className={s.someClassName}`` on a div

When BrowserSync loads the page after a change in Panel.css, I see the border. When I reload the page manually, it disappears.

N.B. I never was stopped in my work for 8 hours by a CSS sheet before trying this "starter-kit".

**Comment by fchienvuhoang** [comment]
I tried created a page like your component Panel, but i have  no issue like you. You are missing some thing?
`"border: 4ps solid green;" 4px or 4ps ?`

**Comment by jdelafon** [comment]
Here is my entire test component:

    class DotterPanel extends Component {
        render() {
            return (<div className={s.canvasContainer}>
                <div style={{width: '100px', height: '100px', background: 'red'}}></div>
            </div>);
        }
    }

    export default DotterPanel;

And the complete DotterPanel.css:

    @import '../variables.css';

    .canvasContainer {
        border: 1px solid brown;
        padding: 20px;
    }

After a manual refresh:

![manual](https://cloud.githubusercontent.com/assets/12040845/16778114/c2d7ff96-486c-11e6-95c7-9e2f6d944549.png)

After I add a blank line in the css and save, then BrowserSync kicks in and reloads:

![auto](https://cloud.githubusercontent.com/assets/12040845/16778137/dcd46a4c-486c-11e6-82c6-c8baa943ba70.png)

If you have any idea of what happens, it would help a lot. Now it has become so complicated overall that I have no idea how to debug it.

**Comment by frenzzy** [comment]
Maybe your server-side is not hot reloadable and it returns the first state of application after full page refresh?

**Comment by jdelafon** [comment]
I have no server-side, or I am not sure what you mean. I have nothing else than the starter-kit, so the "server-side" is what is provided with the kit. What if I don't care about "hot reload", can I turn it off easily at least to know what happens ?

**Comment by fchienvuhoang** [comment]
I'm working well with yours example.
Break line and save Hot-reload still work. If yours project is demo, let send me to check it.

<img width="504" alt="screen shot 2016-07-13 at 2 08 42 am" src="https://cloud.githubusercontent.com/assets/4451749/16779982/c81b4ac6-489e-11e6-86a7-4c0b6d18f4a9.png">

**Comment by jdelafon** [comment]
Thanks. Here is the zipped /src folder.

[src.zip](https://github.com/kriasoft/react-starter-kit/files/360239/src.zip)

**Comment by fchienvuhoang** [comment]
yours src buid undefined on my project. @@
But i saw `export default DotterPanel;` not withStyle?

Let Try:
`import withStyles from 'isomorphic-style-loader/lib/withStyles';`
...
"export default withStyles(s)(DotterPanel);"

**Comment by jdelafon** [comment]
That works ! Thanks a lot. 
I still do not fully understand it, but at least I know what to read now (several depths in. I feel like reading through Wikipedia. Rename to "react-isomorphic-starter-kit" ?).
I was imitating the other components, which do not show the right example due to some black magic. Can I register mine like the others to avoid this supplement of code ?

**Comment by jdelafon** [comment]
Actually, forget it. This is way too complex for what I am doing (a single-page, a priori client-side only app). Thanks for you help.
This kit should be renamed so that other people don't lose their time thinking it is standard project generator. Using the word "isomorphic" without any explanation in the description is not enough.

**Comment by langpavel** [comment]
Isomorphic is great description, better then universal, which is current hype.

And this kit is by my opinion one of the simplest and best in this area, this is reason why I joined into after year and half of discovering :-)

**Comment by jdelafon** [comment]
It is very well done for what it does. I could pull request a line of description to the README to make it clearer for others who are mistaken.

**Comment by langpavel** [comment]
You can try @jdelafon, PRs are always welcomed :-)

**Comment by jdelafon** [comment]
#740
