### ISSUE TITLE
npm install failed?

### ISSUE THREAD

**Issue by mkwokyk** [kriasoft/react-starter-kit#741]
I have just checkout the latest master, and do npm install but failed. Here is the log:
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer graphiql@0.7.2 wants react@^15.0.1
npm ERR! peerinvalid Peer react-dom@15.1.0 wants react@^15.1.0
npm ERR! peerinvalid Peer react-addons-test-utils@15.2.1 wants react@^15.2.1
npm ERR! peerinvalid Peer redbox-react@1.2.10 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer enzyme@2.4.1 wants react@0.13.x || 0.14.x || ^15.0.0-0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marvinkwok/Git/nodetesting/MyApp/npm-debug.log

**Comment by jahmaiosullivan** [comment]
I ran into the same issue. Ended up just bumping all the react dependencies to the latest versions, see here: [https://github.com/jahmaiosullivan/react-starter-kit/commit/9b5ddc605cc1e93648c289faa1611cba8cc9a7bd](https://github.com/jahmaiosullivan/react-starter-kit/commit/9b5ddc605cc1e93648c289faa1611cba8cc9a7bd)

**Comment by retailify** [comment]
I had the same problems. Please change the react version to 15.2.1. Then the install works.
But "npm start" does'nt work (Node 4.4.7 LTS)

**Comment by jahmaiosullivan** [comment]
If you're running into the issue with babel not compiling, add es2015 to the list of presets in package.json.

**Comment by retailify** [comment]
Your changes are working :)

**Comment by mkwokyk** [comment]
Thanks retailify, your changes work!
