### ISSUE TITLE
How to Add a Route to RSK?

### ISSUE THREAD

**Issue by richb-hanover** [kriasoft/react-starter-kit#754]
I am having trouble adding a new page/route to RSK. I have started with the current head (310bb5d), and done these steps:
1. Duplicate the routes/contact folder, and rename it to 'grumble'.
2. Rename the file names to Grumble.css and Grumble.js
3. Edit Grumble.js: `s/Contact/Grumble/g`
4. Edit index.js: change path to '/grumble', and `s/Contact/Grumble/g`
5. Edit routes/index.js to `import grumble from './grumble';` and to add `grumble,` to the end of the `children` list

`npm run start` opens the browser to the home page at localhost:3001
localhost:3001/contact gives the contact page
localhost:3001/grumble gives a blank page, instead of a copy of the Contact page.

What else do I need to do? Thanks.

**Comment by richb-hanover** [comment]
Update: The files look like this:

**routes/index.js**
````
...
import error from './error';
import grumble from './grumble';

export default {

  path: '/',

  children: [
    home,
    contact,
    login,
    register,
    content,
    error,
    grumble,
  ],
...
````
**routes/grumble/index.js**
````
import React from 'react';
import Grumble from './Grumble';

export default {

  path: '/grumble',

  action() {
    return <Grumble />;
  },

};
````
**routes/grumble/Grumble.js**
````
import React, { PropTypes } from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './Grumble.css';

const title = 'Grumble Us';

function Grumble(props, context) {
  context.setTitle(title);
  return (
    <div className={s.root}>
      <div className={s.container}>
        <h1>{title}</h1>
        <p>...</p>
      </div>
    </div>
  );
}

Grumble.contextTypes = { setTitle: PropTypes.func.isRequired };

export default withStyles(s)(Grumble);
````

**Comment by frenzzy** [comment]
[content route](https://github.com/kriasoft/react-starter-kit/blob/master/src/routes/content/index.js#L16) handles all paths, so you need to put your route before it
```js
children: [
  // put your routes here...
  content,
],
```

**Comment by richb-hanover** [comment]
Ahah. That did the trick! All my (own) routes must appear above "content", so routes.index.js is now:

```
...
import error from './error';
import grumble from './grumble';

export default {

  path: '/',

  children: [
    home,
    contact,
    login,
    register,
    grumble,
    content,
    error,
  ],
...
```
A new question: why is `error` listed below `content`? Thanks!

**Comment by drobertson123** [comment]
Appreciate the work. 

We could really use the How To for routing to have some more content. For those of us who are relatively new, this is seriously confusing.

Is there any chance this could get shifted over to the Docs for general use?

**Comment by richb-hanover** [comment]
I issued a PR for a placeholder page to update the How to Implement Routing page:

https://github.com/kriasoft/react-starter-kit/pull/756/commits/a0500298b18dd17b57a43bba3bd4ff994e3c2255

**Comment by samping** [comment]
thanks riche-hanover!  I put my route over the "content" And resolve the problem

**Comment by upq** [comment]
Im deploying my app to heroku
locally everything runs perfect
after deploy I get error complaining about this

```

   async action({ next, render, context }) {
    const component = await next();
    if (component === undefined) return component;
    return render(
      <App context={context}>{component}</App>
    );
  },
```
it says 
```component is not defined```
refering to the one inside the JSX HTML tag.

My order is this

```
  children: [
    home,
    admin,
    contact,
    start,
    login,
    register,
    persona,
    forgot,
    reset,
    content,
    error,
  ],

```

Any clues or help is appreciated

**Comment by upq** [comment]
Should I open an issue for that @langpavel ?

**Comment by langpavel** [comment]
@upq Yes, it is different problem, isn't it?

**Comment by ulani** [comment]
@richb-hanover   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
