### ISSUE TITLE
Error: Server terminated unexpectedly with code: null signal: SIGTERM

### ISSUE THREAD

**Issue by mohanramphp** [kriasoft/react-starter-kit#759]
`> @ start C:\mohan\experiments\react\boilerplates\MyApp
> babel-node tools/run start

[12:12:57] Starting 'start'...
[12:12:57] Starting 'clean'...
[12:12:58] Finished 'clean' after 49 ms
[12:12:58] Starting 'bound copy'...
[12:12:58] Finished 'bound copy' after 162 ms
webpack built 869f3b2ac4a25f52f21e in 9500ms
Child
    Time: 9500ms
                           Asset     Size  Chunks             Chunk Names
    main.js?869f3b2ac4a25f52f21e  4.19 MB       0  [emitted]  main
Child
    Time: 8319ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  197 kB       0  [emitted]  main
    ../../server.js.map  213 kB       0  [emitted]  main
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 869f3b2ac4a25f52f21e in 502ms
Child
    Time: 502ms
Child
    Time: 8319ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  197 kB       0  [emitted]  main
    ../../server.js.map  213 kB       0  [emitted]  main
webpack: bundle is now VALID.
C:\mohan\experiments\react\boilerplates\MyApp\tools\runServer.js:71
        throw new Error(`Server terminated unexpectedly with code: ${ cod
        ^

Error: Server terminated unexpectedly with code: null signal: SIGTERM
    at ChildProcess.server.once (runServer.js:53:15)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\n
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm install
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\mohan\experiments\react\boilerplates\MyApp\npm-debug.log`

I am new to react starter kit. Following things i have done

1. git clone -o react-starter-kit -b master --single-branch https://github.com/kriasoft/react-starter-kit.git MyApp
2. npm install
3. npm start [Hed this issue]

Please help.

**Comment by garfieldnate** [comment]
I had the same issue. I'm attaching the npm-debug.log file generated on my machine.
[npm-debug.log](https://github.com/kriasoft/react-starter-kit/files/532291/npm-debug.log.txt)

**Comment by frenzzy** [comment]
@mohanramphp looks like server terminated after breaking hot update, if so here is the fix: #918

**Comment by garfieldnate** [comment]
@frenzzy I checkout out #918 and it works on Windows! Japanese Windows, no less. Thanks!

**Comment by frenzzy** [comment]
Should be solved by #918. Please reopen if needed.

**Comment by broncha** [comment]
I pulled from master yesterday. I still get this exception!

**Comment by xiguaaxigua** [comment]
i got the same error.

**Comment by jshjohnson** [comment]
Same issue

**Comment by Deepblue129** [comment]
+1

**Comment by codeorelse** [comment]
+1

**Comment by pvijeh** [comment]
samsies

**Comment by Mykybo** [comment]
+1

**Comment by pvijeh** [comment]
anybody figure this out?

**Comment by iDVB** [comment]
+1  - Same error, more extensive repro steps though.

Host Machine: macOS
Docker Container: node:7.2.1-alpine
react-starter-kit #1044 

Basically, I'm running `docker-compose up` (my [Dockerfile and docker-compose.yml](https://gist.github.com/iDVB/023c67ea02609c12989411ce89b152fe)) and everything runs perfect. I can view the site from a browser on the host machine, even got HMR working.

**However**, editing/saving src files too quickly causes this error, which crashes the container. 

It's a showstopper for us since it happens each time and have far too long of a recovery to restart the container.

**Comment by pvijeh** [comment]
@iDVB  you can solve this temporarily by commenting out lines 51 through 57 in tools/runServer.js

    // if (pending) {
    //   server.once('exit', (code, signal) => {
    //     if (pending) {
    //       throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);
    //     }
    //   });
    // }


Im not sure what the root cause of the error is, but commetting these lines out does not seem to have any ill effect and will solve the problem.

**Comment by iDVB** [comment]
@pvijeh Woot! FIXED Thanks! 
You have no idea how much time that likely saved me. I've spend about 5 hours trying to get as much as I have working now... only to see that error. It's my docker first, so I was almost about to ditch docker.

**Comment by ryanbelke** [comment]
+1 getting this error and just pulled the project 2 months ago. Commenting the lines out fixed it temp but it still acts flaky

**Comment by ryanbelke** [comment]
solved with deleting the .yarnlock file and running yarn again

**Comment by TristanDongMaster** [comment]
are you sure fix the issues? I still have the same issues, heart break

**Comment by khashayarghajar** [comment]
same here !
