### ISSUE TITLE
component package.json

### ISSUE THREAD

**Issue by frankleng** [kriasoft/react-starter-kit#76]
@koistya what is the purpose of these package.json files?
should we actually define component level dependencies in there?

**Comment by wizraopeize** [comment]
You can read the CommonJS spec (http://wiki.commonjs.org/wiki/Packages/1.1#Minimal_Example_Package_Descriptor_File)

**Comment by frankleng** [comment]
@wizraopeize no kidding. I know what the files are. but how are they useful?
a minimal descriptor doesn't do much for the components. correct me if I'm wrong.

**Comment by wizraopeize** [comment]
`A CommonJS package is a cohesive wrapping of a collection of modules, code and other assets into a single form`,   `A CommonJS package` can use independently in ohter project. so It's need a descriptor file provides the name, the version and so on.

**Comment by frankleng** [comment]
You are going through definitions. Reuse is not enabled by having a package.json file and you do not need to define each React component as a package. If you really want to do it right, you would have to have a separate repo to house these components. That way other project can require it as an external dependency.

For internal dependencies, ex. the HomePage component, there is no need. and doesn't make sense to me.

**Comment by koistya** [comment]
Without it you would need to reference .js files directly:

```
import MyComponent from '../MyComponent/MyComponent.js';
```

vs.

```
import MyComponent from '../MyComponent';
```

There are some other use cases, for example you can describe your CSS inside `package.json` and use that info to create localized CSS bundles, stuff like that.

**Comment by frankleng** [comment]
@koistya that's awesome! wasn't aware of that.
