### ISSUE TITLE
Integrate react-app-tools

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#763]
What do you think about extracting (1) `webpack.config.js`, (2) all the dev dependencies (~70), and automation scripts (`build`, `run`) into a stand-alone npm package ([`react-app`](https://github.com/kriasoft/react-app))?

This way it might be easier for you to keep a project based on RSK template up to date, you just update `react-app-tools` dev dependency in your project from time to time, which will ensure that you're using the latest and greatest configs and CLI tools ready to be used for building, running and testing your React application.

The `package.json` file in your project will look nice and clean, literally:

``` json
{
  "private": true,
  "dependencies": {
    "history": "^3.0.0",
    "react": "^15.2.1",
    "react-app": "^1.1.1",
    "react-dom": "^15.2.1",
    "whatwg-fetch": "^1.0.0"
  },
  "devDependencies": {
    "react-app-tools": "^1.1.1",
  },
  "scripts": {
    "build": "react-app build",
    "start": "react-app run",
  }
}
```
### FAQ
- **Will I be able to customize Babel, Webpack, Browsersync and other configs?**<br>Yes, there will be an easy way to extend/tweak the default configs (Webpack, Babel, PostCSS etc.)
- **Will I be able to customize automation scripts?**<br>Yes, there will be an easy way to add or customize the existing scripts (`build`, `run` etc.)
### Preview

https://github.com/kriasoft/react-app

**Comment by maullerz** [comment]
I think this is great idea!

**Comment by drobertson123** [comment]
+1 This would make it simpler to separate out and deal with the Babel, Webpack & PostCSS file issues I am having with LESS files.

One request. Could we please have more debugging options in the Webpack process. I am not sure what this would entail, but Webpack is the bane of my existence right now and I can't figure out where or why.

**Comment by ulani** [comment]
@koistya  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
