### ISSUE TITLE
How to set locale for react-intl (with or without graphql)

### ISSUE THREAD

**Issue by tiaaaa123** [kriasoft/react-starter-kit#765]
Hey guys, 

I'm trying to use react-intl  using the react starter kit. I got it running but I can't change the locale to another language than 'en'. I have to say that I have no idea how to change this default value.....

I guess that it's coming from the `server.js`

``` jsx
app.get('*', async(req, res, next) => {
    try {
        global.navigator.userAgent = req.headers['user-agent'] || 'all';
        const memoryHistory = createMemoryHistory(req.url);
        const store = configureStore(memoryHistory, {});
        const history = syncHistoryWithStore(memoryHistory, store);
        const locale = req.language;

        store.dispatch(setRuntimeVariable({
            name: 'initialNow',
            value: Date.now(),
        }));

        store.dispatch(setRuntimeVariable({
            name: 'availableLocales',
            value: locales,
        }));
        await store.dispatch(setLocale({
            locale,
        }));`
    ...
```

When I switch `req.language` for `'fr'`, it does switch, but I can't make is switch elsewhere.
I tried using the component `LanguageSwitcher`from the starter kit but it doesn't work (Nothing happen's onClick). From what I see in the react-stater-kit-intl, it is using graphql to store the locale value (or not? I don't really know....).

To go further in what it does, clicking on the language from `languageSwitcher` enter the `setLocale` from the reducer `intl.js` with the good value in locale. 

``` jsx
export function setLocale({ locale }) {
console.log(locale);                  // <---- Is showing the good value. Nothing happens afterward 
    return async (dispatch) => {
        console.log(locale);          // <----- Doesn't show but it might be normal.....
        dispatch({
            type: SET_LOCALE_START,
            payload: {
                locale,
            },
        });

        try {
            console.log(locale);            // <------ Doesn't show anything.
            const resp = await fetch('/graphql', {
                method: 'post',
                headers: {
                    Accept: 'application/json',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    query: `query{intl(locale:${JSON.stringify(locale)}){id,message}}`,
                }),
                credentials: 'include',
            });
            if (resp.status !== 200) throw new Error(resp.statusText);
            const { data } = await resp.json();
            const messages = data.intl.reduce((msgs, msg) => {
                msgs[msg.id] = msg.message; // eslint-disable-line no-param-reassign
                return msgs;
            }, {});
            dispatch({
                type: SET_LOCALE_SUCCESS,
                payload: {
                    locale,
                    messages,
                },
            });

            // remember locale for every new request
            if (process.env.BROWSER) {
                const maxAge = 3650 * 24 * 3600; // 10 years in seconds
                document.cookie = `lang=${locale};path=/;max-age=${maxAge}`;
            }
        } catch (error) {
            console.log(error);               // <-----   Doesn't show.
            dispatch({
                type: SET_LOCALE_ERROR,
                payload: {
                    locale,
                    error,
                },
            });
            return false;
        }

        return true;
    };
}
```

Anyone would have an idea of the problem??

**Comment by tiaaaa123** [comment]
Found it! The LanguageSwitcher wasn't working because of `e.preventDefault();` which is in the starter kit... Weird

**Comment by langpavel** [comment]
Did you dispatch `setLocale` action via `store.dispatch()` or `connect` bound action from `react-redux`?

**Comment by tiaaaa123** [comment]
I bound it with connect from `react-redux`

```
export default connect(state => ({
    availableLocales: state.runtime.availableLocales,
    currentLocale: state.intl.locale,
}), { setLocale })(withStyles(styles)(LanguageSwitcher));
```

**Comment by langpavel** [comment]
@damiangreen If you disable `e.preventDefault()`, you can drop entire event handler :-)
You have trouble with dispatching redux action (probably),
see if all `console.log`s will report to you in browser console.
If not, you should check that action is dispatched through store:
 * by `store.dispatch(setLocale({ locale }))`
 * or `this.props.setLocale({ locale })` previosly bound by `connect` HoC
redux will trigger rerender of `LanguageProvider` after action is dispatched.

**Comment by damiangreen** [comment]
@langpavel If I leave the ```e.preventDefault``` line I get two actions dispatched:
SET_LOCALE_START
newLocale(pin): null => 'es-ES'

and then 
SET_LOCALE_ERROR
newLocale(pin): 'es-ES' => null

Debugging intl.js an exception is caught but ```error``` is ```undefined```
Ostensibly it appears that  ```queryIntl``` is ```undefined``, but I dont' always trust Chrome debugging tools
I've checked and that file exists.

![image](https://user-images.githubusercontent.com/1592820/44976982-b26bdc80-af5e-11e8-8c16-b1d0b8b9ee77.png)

**Comment by langpavel** [comment]
@damiangreen 
What is content of your `./intl.graphql`?
Did your `/graphql` endpoint knows `intl` field?

**Comment by damiangreen** [comment]
```query intl($locale: String!) {
  intl(locale: $locale) {
    id
    message
  }
}
```

Ah, maybe you've identified the problem, so I need to get my Java graphql back end to have awareness of the ```intl``` shape? Is there a way i can suppress this error without changing the backend as it's not a backend concern?
thanks for all your help

**Comment by langpavel** [comment]
RSK have integrated GraphQL server which is used in short-circuit fashion when SSR.
Messages are queried from GraphQL when you change locale on client.
You can reimplement `setLocale` action creator to load messages by different way, may be dynamic `import` or `fetch` them from different endpoint

**Comment by ulani** [comment]
@tiaaaa123   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
