### ISSUE TITLE
AWS Deployment [elasticbeanstalk]

### ISSUE THREAD

**Issue by kmx411** [kriasoft/react-starter-kit#767]
Tried looking through GitHub and asking on Gitter, but I haven't had any luck. We're using this kit and hosted on Heroku but am trying to switch to AWS w Elastic Beanstalk, I tried deploying there but I hit a wall of errors. Has anyone had any luck?

**Comment by smshuja** [comment]
@kmx411 Did you manage to use AWS EB for deployment?

**Comment by kjg531** [comment]
Has anyone been able to accomplish this?

**Comment by ss50** [comment]
I've been trying to deploy this kit to AWS EB - I created an app based off of it but I haven't had any luck deploying it. Is there anything that needs to be configured?

**Comment by valeeum** [comment]
i recommend building your docker image and storing it on aws ecr and using Dockerrun.aws.json file to build out your app.    The file below is set up to use multi container environment in the event you need to add additional containers to it.  

```
{
  "AWSEBDockerrunVersion": 2,
  "volumes": [
  ],
  "containerDefinitions": [
    {
      "name": "webserver",
      "image": "{YOURACCOUNTID}.dkr.ecr.{YOURDEFAULTREGION}.amazonaws.com/{IMAGEREPONAME}:{IMAGETAG}",
      "essential": true,
      "memoryReservation": 256,
      "portMappings": [
        {
          "hostPort": 80,
          "containerPort": 3000
        }
      ]
    }
  ]
}

```

**Comment by WiktorKa** [comment]
I managed to deploy to AWS EB without using of Docker.

**Comment by mxmtsk** [comment]
@WiktorKa would you share your solution with us?

**Comment by WiktorKa** [comment]
@mxmtsk Actually, what I do is simply run `yarn build --release`, than I zip content of `build` folder into one archive and deploy it into EB instance. I had some issues with sqlite3 dependency, but since I use RDS I don't need it.  What particular issues you're facing?

**Comment by karanp41** [comment]
Hello @shreysaroch @mxmtsk @WiktorKa guys,
I'm getting following error while deploying to AWS Beanstalk, in 3rd step:
`2020-01-24 11:38:31    ERROR   Failed to build Docker image aws_beanstalk/staging-app: 7d
Step 3/9 : COPY ./build/package.json .
COPY failed: stat /var/lib/docker/tmp/docker-builder168800563/build/package.json: no such file or directory. `
Any idea?

Thanks in advance!

**Comment by Filco306** [comment]
I am currently having the exact same issue as above. I would love some input on this matter. @WiktorKa do you only include the `build`-folder in the zip-file and upload it to a node-instance? 

I also tried @valeeum 's approach, but no luck. Not really sure what to do next. Ugh.
