### ISSUE TITLE
webpack config still references react-routing

### ISSUE THREAD

**Issue by nuclearspike** [kriasoft/react-starter-kit#770]
https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js#L52 (+ 2 more)

If everything works without having those paths be valid, do they really do anything?

**Comment by koistya** [comment]
It's considered to be a good practice to explicitly specify what
folders/files should be parsed by a Webpack loader.

**Comment by nuclearspike** [comment]
But react-routing is not in the package anymore and should now be 'universal-router' which is what I changed those references to in the config.

**Comment by koistya** [comment]
Ah, right, need to remove that line.
