### ISSUE TITLE
main.js Not Found after signing in with facebook

### ISSUE THREAD

**Issue by scottmcpherson** [kriasoft/react-starter-kit#773]
After setting up passport with my facebook tokens, when I log in with facebook and it redirects back to localhost, the user is successfully logged in, but main.js is no longer found. 

So when you navigate around in the app, all the pages are server loaded from that point on. Full page refreshes are happening. The only way to get main.js to the client again is to restart the server.

![about_us](https://cloud.githubusercontent.com/assets/2382172/17210490/4bc59e96-5491-11e6-8dbd-a245c0f7d2c6.png)

**Comment by langpavel** [comment]
It's because redirect point at `http://localhost:3000` instead of `http://localhost:3001`.
Works this when you build release?

**Comment by scottmcpherson** [comment]
Good catch @langpavel. I ran the build release and and then ran the server.js file with node and I'm no longer running into that issue. 

What was causing the issue to begin with was that the facebook login was failing and the `failureRedirect` was being called on the `/login/facebook/return` route. 

Are you able to get a successful facebook login on localhost?

**Comment by broncha** [comment]
umm why was this issue closed! How do we test returns when browsersync is proxying the main server? all the urls that are generated in passport are the main server url!

**Comment by langpavel** [comment]
@broncha You are right, but setting up authentication is outside scope of this project..

But It should be possible to setup proxy from :3000 to :3001 in development only to avoid this issues. Opening new issue for this

**Comment by ulani** [comment]
@scottmcpherson   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
