### ISSUE TITLE
error on latest version / on npm start

### ISSUE THREAD

**Issue by UXDart** [kriasoft/react-starter-kit#777]
Error: Server terminated unexpectedly with code: 0 signal: null
    at ChildProcess.server.once (runServer.js:44:15)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.

is anyone using the latest version?
TIA

**Comment by manumaticx** [comment]
same here

**Comment by langpavel** [comment]
Did you run `npm rebuild`? Try delete `node_modules` directory and install packages again. Does this help?

**Comment by alex4Zero** [comment]
Did you run `npm start` second time after stoping it manually?

**Comment by deveedutta** [comment]
+1

**Comment by DennisSen** [comment]
Same problem as OP. Hints here did not help.
[npm-debug.txt](https://github.com/kriasoft/react-starter-kit/files/543969/npm-debug.txt)

**Comment by isthisstackoverflow** [comment]
Same problem as OP, hints here didn't work for me.
[npm-debug.txt](https://github.com/kriasoft/react-starter-kit/files/543982/npm-debug.txt)

**Comment by deveedutta** [comment]
@isthisstackoverflow Few things may help

- update your node version to latest (`6.x` as of now, download and install if you're on mac)
- do an `npm update`
- Install `babel-core` (and it's dependencies if any) and `babel-cli`

Try running again.

**Comment by fireflieslive** [comment]
+1

**Comment by ulani** [comment]
@UXDart   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
