### ISSUE TITLE
unexpected token ...

### ISSUE THREAD

**Issue by pdhoward** [kriasoft/react-starter-kit#779]
Just checking out the repo -- ran npm start as instructed .. got

SyntaxError Unexpected token ...    for tools/start.js:36

what did i miss?

**Comment by elborre** [comment]
If you are using babel 6, You may need to add the following present into you package.json or into your .babelrc file 

`{
  "presets": ["es2015"]
}
`

these changes were introduced in babel 6, now we can decide which plugins to load or not, you can find more information on the offical release notes https://babeljs.io/blog/2015/10/29/6.0.0 

> Since Babel is focusing on being a platform for JavaScript tooling and not an ES2015 transpiler, we’ve decided to make all of the plugins opt-in. This means when you install Babel it will no longer transpile your ES2015 code by default.

**Comment by jgentes** [comment]
That fixes the issue, thanks
