### ISSUE TITLE
Navigating using HTML anchors

### ISSUE THREAD

**Issue by natke** [kriasoft/react-starter-kit#784]
I am new to React and the React Starter Kit, and have recently taken over ownership of a website built on RSK. Among other things, the site loads its content from static markdown files, parsed into HTML using marked. This content incorporates anchors for internal navigation. The generated HTML is correct but the anchors are not being navigated to in the final React site. 

Should this be something that should work out of the box, or does it need to be configured/programmed in?

(I have seen lots of commentary on problems with anchors in the React Link component, but this is not that)

**Comment by frenzzy** [comment]
you can add handler for such links by yourself, example:

[/src/routes/content/Content.js#L13](https://github.com/kriasoft/react-starter-kit/blob/89ac3c43fe16a584842759f27c543e2d602972fb/src/routes/content/Content.js#L13)
```js
import history from '../../core/history';

function isLeftClickEvent(event) {
  return event.button === 0;
}

function isModifiedEvent(event) {
  return !!(event.metaKey || event.altKey || event.ctrlKey || event.shiftKey);
}
```

[/src/routes/content/Content.js#L33](https://github.com/kriasoft/react-starter-kit/blob/89ac3c43fe16a584842759f27c543e2d602972fb/src/routes/content/Content.js#L33)
```js
onClick(event) {
  if (
    event.target.tagName === 'A' &&
    isLeftClickEvent(event) &&
    !isModifiedEvent(event) &&
    event.target.host === window.location.host
  ) {
    event.preventDefault();
    history.push({
      pathname: event.target.pathname,
      search: event.target.search,
    });
  }
}
```

[/src/routes/content/Content.js#L39](https://github.com/kriasoft/react-starter-kit/blob/89ac3c43fe16a584842759f27c543e2d602972fb/src/routes/content/Content.js#L39)
```js
<div
  dangerouslySetInnerHTML={{ __html: this.props.content || '' }}
  onClick={this.onClick} // add click handler
/>
```

**Comment by natke** [comment]
Thanks for that.
