### ISSUE TITLE
a warning of Link component - React 15.3.0

### ISSUE THREAD

**Issue by fchienvuhoang** [kriasoft/react-starter-kit#788]
Hi all,
Just a warning when used Link component with react 15.3.0

<img width="985" alt="screen shot 2016-08-03 at 6 27 20 am" src="https://cloud.githubusercontent.com/assets/4451749/17348821/729da660-5943-11e6-8b06-10c53e37b393.png">

**Comment by langpavel** [comment]
Ahh, It's probably related to `feature` branch, isn't it?

**Comment by langpavel** [comment]
TODO: Remove navigate from props at https://github.com/kriasoft/react-starter-kit/blob/feature/redux/src/components/Link/Link.js#L66

**Comment by fchienvuhoang** [comment]
yes, on redux branch. :)
