### ISSUE TITLE
Link component with Isomorphic redirect issue

### ISSUE THREAD

**Issue by fchienvuhoang** [kriasoft/react-starter-kit#789]
Hi there,
I had two components path as below: 
+ Component 1
` path: '/:storeId' `
+ Component 2
`path: '/:storeId/:categoryId`
With path component 1 is working well, but second component return a 404 page error.  
I think just a issues with Link component, When refresh browser two components still work.
Please take a look it.

Thanks

**Comment by langpavel** [comment]
@fchienvuhoang Why you close this issue?

**Comment by fchienvuhoang** [comment]
sorry, i wrong. I lost chars "/" when direct to component 2. :D.
