### ISSUE TITLE
Going to Privacy link and then hitting the Back Button does not work

### ISSUE THREAD

**Issue by rocketraman** [kriasoft/react-starter-kit#79]
Sometimes, clicking on the Privacy link and then clicking the browser's back button changes the URL path to `/` but it does not change the content of the screen, which remains on the Privacy page. I am using Chrome Version 42.0.2311.22 beta (64-bit) on Linux.

**Comment by tadjik1** [comment]
the same situation on macos

**Comment by koistya** [comment]
Thanks for the report! It should be fixed now in 7e06940b0616b8f3d9e84faeb3b533f4854d6a72.
