### ISSUE TITLE
error when run npm start 

### ISSUE THREAD

**Issue by yy-hh** [kriasoft/react-starter-kit#802]
YangyangdeMacBook-Pro:MyApp yangyangliang$ npm start

> @ start /Users/yangyangliang/apps/MyApp
> babel-node tools/run start

/Users/yangyangliang/apps/MyApp/tools/start.js:36
            plugins: [...(x.query ? x.query.plugins : []), ['react-transform', {
                      ^^^

SyntaxError: Unexpected token ...

**Comment by langpavel** [comment]
Use node 6, reopen if issue persist
