### ISSUE TITLE
Question about build system

### ISSUE THREAD

**Issue by juangl** [kriasoft/react-starter-kit#804]
Sorry for post a question here, but I found the same question in stackOverflow unanswered.

[Different main entry point in package.json for node and browser](http://stackoverflow.com/questions/38055510/different-main-entry-point-in-package-json-for-node-and-browser)

I just want to know how this configuration is done. 
How to specify different entries for different build targets in package.json?
![screenshot from 2016-08-17 23-23-17](https://cloud.githubusercontent.com/assets/1887029/17761998/9e53388a-64d1-11e6-9334-0390d84b1c16.png)

**Comment by langpavel** [comment]
See tools/webpack.config.js there are different configurations for client and server. Most important choir this is environment node/browser

**Comment by juangl** [comment]
Thank you. 
Can you give me some aditional information?

**Comment by langpavel** [comment]
Oh, sorry, I think you should really study this pieces of code yourself to fully understand what happens here.. I know it can consume a little of time but you must take it easy, you will learn something new and really useful ;-)
