### ISSUE TITLE
Running with pm2 - JS missing

### ISSUE THREAD

**Issue by mxmtsk** [kriasoft/react-starter-kit#805]
Hello,

I'm trying to run the starter kit on a server with the help of pm2. I passed a node env PORT = 80 and my output in pm2 looks like this:

```
wheretoclub-react-2 The server is running at http://localhost:80/
wheretoclub-react-2 [BS] Proxying: http://localhost:80
wheretoclub-react-2 [BS] Access URLs:
wheretoclub-react-2  -----------------------------------
wheretoclub-react-2     Local: http://localhost:3000
wheretoclub-react-2  External: http://SERVER_IP:3000
wheretoclub-react-2  -----------------------------------
```

So far so good, but when I call the server ip without a port (aka port 80) I'll get the ssr markup but it cannot find the JS file in /assets/main....js) but it does find it when I call the server with port 3000.

Can anyone help me or does have an idea why this happens? Did i miss somthing?

pm2 json file does look like this:

```json
{
  "apps": [
    {
      "name": "my_app",
      "script": "tools/run.js",
      "args": ["start", "--release"],
      "exec_interpreter": "babel-node",
      "exec_mode": "fork",
      "env": {
        "NODE_ENV": "production",
        "WEBSITE_HOSTNAME": "mydomain.com",
        "PORT": 80
      }
    }
  ]
}
```

**Comment by mxmtsk** [comment]
nevermind, I was missreading something. I made build on the server now and ran it with node build/server.js in pm2

**Comment by AnupVeerapur** [comment]
Hi,

@mxmtsk  can you please explain me how can I run my reactjs starter kit application with pm2. I have been on this since a while and I am not able to come up with a workaround.

Thankyou!

**Comment by GideonFlynn** [comment]
Build with yarn build -- --release

Install pm2 and run the start command(in project root folder): 
`pm2 start ./build/server.js`

You can use --name "somename"  to name your instance.

**Comment by GideonFlynn** [comment]
I myself run my RSK app with Pm2 and does the rest of the server stuff with nginx.
