### ISSUE TITLE
main.js file not found on port 3000

### ISSUE THREAD

**Issue by codyromano** [kriasoft/react-starter-kit#808]
The main.js file loads fine when I'm on port `3001` (BrowserSync server), but it returns `404` when I'm using port `3000`.

Request on port 3001:
```
GET http://localhost:3001/assets/main.f86eea1481c6fe0a8636.js (200)
```
Same request on port 3000:
```
GET http://localhost:3000/assets/main.f86eea1481c6fe0a8636.js (404)
```
Other network requests are working fine. Any ideas why only the JS doesn't load on that port?

**Comment by langpavel** [comment]
In development mode all javascripts and webpack assets are only handled by browsersync.

**Comment by codyromano** [comment]
I'm sorry, but how do I access the app in production mode? I was under the impression that running the app on port `3000` via `npm start --release` would do the trick, but apparently it's still in dev mode. I also tried forcing prod by replacing DEBUG with a hardcoded `false`.

**Comment by langpavel** [comment]
`npm run build --release` then go to build dir and run `node server`

**Comment by codyromano** [comment]
Perfect...thanks!
