### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by abiodun1** [kriasoft/react-starter-kit#809]
Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

**Comment by langpavel** [comment]
Please use node 6

**Comment by TanKucukhas** [comment]
I have the same issue with node 6.7.0

**Comment by langpavel** [comment]
I'm using latest node without issues. You are saying same, but it is impossible, because you are not using node 4. Provide more info.

**Comment by wenyanqi** [comment]
I also have the same issue with node 6.2.2.
sh: babel-node: command not found

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ start: `babel-node tools/run start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

**Comment by langpavel** [comment]
@wenyanqi have you installed all dependencies? Try purge and reinstall them: `rm -rf node_modules; npm install`

**Comment by langpavel** [comment]
Also ensure you have `node-gyp` installed globally
