### ISSUE TITLE
Link Component - Scroll to hash

### ISSUE THREAD

**Issue by mxmtsk** [kriasoft/react-starter-kit#812]
Hello,

I have multiple occurrences where I link to specific sections of my app. Sadly, linking to them with a hash (<Link to="/page#section"...) is not working as it stays on top. Is this something that could possibly be fixed or is there - in general another way to deal with this in React?

Thanks

**Comment by frenzzy** [comment]
Try this solution: https://github.com/frenzzy/react-starter-kit/commit/1c987235b97bce4e9b19d2eb2d0189f2c5a2f155

**Comment by langpavel** [comment]
@frenzzy Should we pick this into master?

**Comment by mxmtsk** [comment]
It works like a charm, thanks @frenzzy! I'd love to see this merged :)

**Comment by Shadowman4205** [comment]
Hello, i am loading some html code from db with dangerouslySetInnerHTML.
In this code i have got hash tag, for example something like this 
```
<a href="#test"></a>
<p id="test">Some text</p>
```
When i click <a>, in first place it go to <p> and again to top, any suggestion?

**Comment by frenzzy** [comment]
How about something like this?
```js
const Example = props =>
  <div
    dangerouslySetInnerHTML={{ __html: `
      <a href="#test"></a>
      <p id="test">Some text</p>
    ` }}
    onClick={event => {
      if (event.target.tagName === 'A') {
        const link = event.target
        const href = link.getAttribute('href')
        if (href.chartAt(0) === '#') {
          const target = document.getElementById(href.substr(1))
          if (target) {
            event.preventDefault()
            const rect = link.getBoundingClientRect()
            const scrollX = 0
            const scrollY = window.pageYOffset + rect.top
            window.scroll(scrollX, scrollY)
          }
        }
      }
    }}
  />
```

**Comment by Shadowman4205** [comment]
Using mozilla-firefox and micrsoft edge without this part of code u mentioned, it is working it go to p tag with id test,and also when i reload the page with path /example#test it still go there.
But chrome and opera have same behaviour it go to p tag and again to top.
With ur code it just go a little down. By using 2 or 3 hashlinks its go to same place

```
const hmtlRaw = `
       <a href="#test"></a>
       <a href="#test1"></a>
       <a href="#test2"></a>
      <p id="test">Some text</p>
      <p id="test1">Some text</p>
      <p id="test2">Some text</p>
 `
```

**Comment by frenzzy** [comment]
It should work in all browsers, try demo: https://jsfiddle.net/frenzzy/e09szjye/

**Comment by Shadowman4205** [comment]
Yes i see, it is also working without click event too i fiddle.  I will search more.
But for some reason it is rerendering i think,, cause on  hashlink click it go immediatly to p tag
and starting server side rendering and back to top.

**Comment by langpavel** [comment]
@Shadowman4205:

> But for some reason it is rerendering i think,,

No reason — except you didn't use `<Link …>` or something similar?
