### ISSUE TITLE
jQuery script for specific component (server side rendering)

### ISSUE THREAD

**Issue by manhhailua** [kriasoft/react-starter-kit#814]
If server side rendering, jQuery will not work because "jQuery need a document within a window". How would I write jQuery script with a specific component? Maybe like the way `context.insertCss()` work.
Would we make something named: `context.insertScripts()`?

**Comment by voquockhanh2** [comment]
You can only write jquery on ComponentDidMount() and componentDidUpdate().
ex: http://semantic-ui.com/introduction/integrations.html

**Comment by manhhailua** [comment]
@voquockhanh2 : the problem is componentDidMount() does not run on server side rendering

**Comment by voquockhanh2** [comment]
@manhhailua : I think you cannot run Jquery on Server side, jquery need to read rendered DOM so it is client script only.

**Comment by manhhailua** [comment]
@voquockhanh2: so, should we make a new func named `context.insertScripts`, it does exactly what `context.insertCss` did.

**Comment by voquockhanh2** [comment]
@manhhailua : I think we only need import jquery on bottom of Html.js

**Comment by manhhailua** [comment]
@voquockhanh2: then where will you put these lines of code in a specific component?
```
  $(function () {
    // using jQuery
  });
```

**Comment by voquockhanh2** [comment]
@manhhailua  in component you create componentDidMount() and componentDidUpdate(), and write jquery there (remmeber import jquery to your html.js)
example: http://semantic-ui.com/introduction/integrations.html
