### ISSUE TITLE
After npm start, fisrt open Chrome to open localhost:3001/,show Warning in console and Chrome console.

### ISSUE THREAD

**Issue by zhuqiuyang** [kriasoft/react-starter-kit#818]
![image](https://cloud.githubusercontent.com/assets/14734729/17997172/86c53f2c-6b9f-11e6-8dc5-d23d16e03740.png)
---
![image](https://cloud.githubusercontent.com/assets/14734729/17997277/2da1a484-6ba0-11e6-9f34-8e37088c7b23.png)

---
open local:3001/  again this waring is disappearing.

**Comment by zhuqiuyang** [comment]
Chrome version: 52.0.2743.116 (64-bit)
node 6.4.0
npm 3.10.3

**Comment by langpavel** [comment]
@zhuqiuyang Fresh cloned app? Which branch?

**Comment by zhuqiuyang** [comment]
in master branch.

**Comment by langpavel** [comment]
@zhuqiuyang I don't experiencing this, tested on second (freshly installed) computer. Reopen with more details please
