### ISSUE TITLE
Unneeded Deps 

### ISSUE THREAD

**Issue by juangl** [kriasoft/react-starter-kit#821]
I'm thinking if  `bluebird` is really necesary since node  >= 5 has built-in ES6 promises.

Can I try to remove `bluebird` and make PR? I just want to help have a slightly cleaner code.

Also `core-js` is necesary?

**Comment by andrewkolesnikov** [comment]
`core-js` is not directly referenced, but listed as dependency of other packages. Should probably be removed from package.json. `bluebird` is being used, but can easily be extracted.

**Comment by langpavel** [comment]
`bluebird` is well tested and optimized Promise implementation. I'm for keeping it

**Comment by ChrisCinelli** [comment]
`bluebird` is faster than the "native" promise implementation and on the browser side you lose compatibility with all IEs and a bunch of older browsers (see http://caniuse.com/#feat=promises )

**Comment by juangl** [comment]
Amazing!  So, is it preferable to set as default promises?

`require('babel-runtime/core-js/promise').default = require('bluebird');`
