### ISSUE TITLE
Not an issue just simple Question 

### ISSUE THREAD

**Issue by sauravskumar** [kriasoft/react-starter-kit#826]
Hello everyone...i am coming here from (react-redux-universal-hot-example)[https://github.com/erikras/react-redux-universal-hot-example]. Can anyone please tell me if there are any benefits switching over to this one?  is there any easy migration guide... thank you

**Comment by langpavel** [comment]
Feature branches, live community on Gitter, future

**Comment by sauravskumar** [comment]
@langpavel i have a few projects on that one... but that repo died... can i expect this one to be always up to date for the next few months?

**Comment by langpavel** [comment]
@sauravskumar Absolutely! :-)
