### ISSUE TITLE
How to make GA(Google analytics) detect changed router when using Link component

### ISSUE THREAD

**Issue by fchienvuhoang** [kriasoft/react-starter-kit#827]
Hi all,
I monitors GA module "Top active pages", when direct to new router using Link component, GA is not recognize url changed.
Thanks

**Comment by langpavel** [comment]
Hook it on history or hook it on router

**Comment by frenzzy** [comment]
It should, did you see [this code](https://github.com/kriasoft/react-starter-kit/blob/374b1dfc3acca38bcbe2edf0ce13aa2b38966265/src/client.js#L66-L70)?
Or maybe you forgot to [set `GOOGLE_TRACKING_ID` environment variable](https://github.com/kriasoft/react-starter-kit/blob/374b1dfc3acca38bcbe2edf0ce13aa2b38966265/src/config.js#L21)?

**Comment by fchienvuhoang** [comment]
Ahh, i was inserted <script src="/google-analytics.js"></script> to enable content security policy.
I'm current using:
``   
 if (window.ga) {
      window.ga('send', 'pageview');
}
``
``<script src="/google-analytics.js">``
:)

**Comment by fchienvuhoang** [comment]
Hi @langpavel and @frenzzy,
I tried with origin code of react-startkit redux branch.
I added GA code to config file like below:
```
export const analytics = {
  // https://analytics.google.com/
  google: {
    trackingId: 'UA-81634517-1', // UA-XXXXX-X
  },
};
```
and I tried something else:
```
export function navigate(descriptor) {
  if (window.ga) {
    window.ga('send', 'pageview');
  }
  return (dispatch, _, { history }) => history.push(descriptor);
}
```
```
export default {
  path: '/login',
  action() {
    if (window.ga) {
      window.ga('send', 'pageview');
    }
    return <Login />;
  },
};
```

but isn't work when monitor on GA. please take a look.
Thanks

**Comment by fchienvuhoang** [comment]
@langpavel , @frenzzy could you help me please,
I have no solution for this :(

**Comment by fchienvuhoang** [comment]
Hi all,
I had resolved this issues by add more param like below:
```
ga('send', 'pageview', window.location.pathname + window.location.search);
```
Thanks
