### ISSUE TITLE
Cannot seem to get socket.io integrated...

### ISSUE THREAD

**Issue by GQAdonis** [kriasoft/react-starter-kit#83]
I cannot seem to get socket.io to work with this toolkit no matter what I do.  I get compilation errors from simply using "npm install socket.io", which installs version 1.3.5, which conflicts with the version used by webpack.

However, once I revert to 0.9.7 of socket.io, the project will build and run until I actually attempt to "require('socket.io').listen(server)", which causes the following error:

, 'undefined' != typeof io ? io : module.parent.exports
                                                   ^
TypeError: Cannot read property 'exports' of undefined

Has anyone successfully integrated socket.io with this project and gotten it to work?

**Comment by koistya** [comment]
Try to add a dot `\.` to the following regular expression:

https://github.com/kriasoft/react-starter-kit/blob/master/webpack.config.js#L126
