### ISSUE TITLE
Nesting class in scss

### ISSUE THREAD

**Issue by ThePainnn** [kriasoft/react-starter-kit#830]
Hi, I really don't know if I'm suppose to be asking for help in here, but I really don't know what I'm doing wrong. Since it's working fine with my other react project also.

I use cubism.js with jolokia to monitor our servers. I've build a dashboard with your very nice kit and react around those two components. Everything work well expect for a small issue with scss.

jolokia and cubism generate 3 nodes for an Horizon graph. For example:

```
<div class="HorizonChart__horizon___3APg7">
  <canvas width="594" height="30"></canvas>
  <span class="title">Chart</span>
  <span class="value">1</span></div>
</div>
```

In my scss for my component I have:

```
.horizon {
  border-bottom: solid 1px #000;
  overflow: hidden;
  position: relative;
  border-top: solid 1px #000;
  border-bottom: solid 1px #000;

  canvas {
    display: block;
    left : 0;
  }

  /* HACK - suppose to be .title, but does not seem to work with .title */
  span:nth-child(2) {
    left: 0;
    display: block;
    float: left;
  }

  /* HACK - suppose to be .value, but does not seem to work with .value */
  span:nth-child(3) {
    display: block;
    float: right;
    width: 50%;
    text-align:right
  }

  .title {
    left: 0;
    display: block;
    float: left;
  }

  .value {
    display: block;
    float: right;
    width: 50%;
    text-align:right
  }
}
```

.horizon is working but it's nested classes are not:
.title and .value always seem to be ignore. I use a nasty hack with span:nth-child selector to get to them and set their style.

Any idea?

Thanks a bunch!

**Comment by frenzzy** [comment]
You need to read about [CSS Modules](https://github.com/webpack/css-loader#css-modules) and its [local scope](https://github.com/webpack/css-loader#local-scope)

A good article on the subject: [CSS Modules Welcome to the Future by Glen Maddern](https://glenmaddern.com/articles/css-modules)

**Comment by ulani** [comment]
@ThePainnn   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
