### ISSUE TITLE
automatically synchronize input value

### ISSUE THREAD

**Issue by stone89son** [kriasoft/react-starter-kit#832]
Hi all forum
I use reactjs startkit. i"m beginner reactjs, can you explain me?
I create a Input.  and input value to Input, but value automatically synchronize
I want to not  automatically synchronize. please help me. thank you.
 Image error:   [https://drive.google.com/file/d/0B7t1NUY93GMBdjFVWXFNanNKR2c/view?usp=sharing](url)
 p/s: copy to new tab

**Comment by azz0r** [comment]
Do you have a code sample? I also think a generic question like this is better suited for StackOverflow as its not specific to React starter kit.

**Comment by frenzzy** [comment]
@stone89son, look at React Docs -> [Uncontrolled Components](https://facebook.github.io/react/docs/forms.html#uncontrolled-components).
But it would be nice to read this topic completely.

**Comment by stone89son** [comment]
@azz0r  @frenzzy  thank you very much
