### ISSUE TITLE
Server.js should be using cluster package.

### ISSUE THREAD

**Issue by nuclearspike** [kriasoft/react-starter-kit#844]
The out-of-the-box server is single-process while just a bit of code can take advantage of multi-core processors/multi-processor servers and handle more concurrent requests. Using 'cluster' also means if a horrible error takes one process out, others are waiting to handle requests while the master spawns a replacement.

The basic pattern is:

```
const cluster = require('cluster');
if (cluster.isMaster) {
  const numCPUs = require('os').cpus().length;
  const maxWorkers = process.env.MAX_WORKERS || 7;
  for (var i = 0; i < Math.min(numCPUs - 1, maxWorkers); i++) {
    cluster.fork();
  }
  cluster.on('exit', worker => {
    console.log('Worker %d died :(', worker.id)
    cluster.fork() //start another one.
  });
  cluster.on('fork', worker => {
    console.log(`forked: new worker id ${worker.id}`);
  });
} else if (cluster.isWorker) {

   //all of the normal express route handling that's currently in server.js

}
```

**Comment by alex4Zero** [comment]
I'm not sure if it should be part of starter kit. Cluster is one of the option of doing process load balancing and it might not fit your production needs.

**Comment by nuclearspike** [comment]
There are other options and that's OK for people to alter the code or if
you choose to use a different one than cluster for the kit. But I see this
project as getting people up and running production worthy code with
some best practices preselected so they don't have to know about how to
incorporate that on their own because they may not even realize there are
simple options like that to improve server performance. If their opinion
differs from using the default selection then they can change it.

**Comment by JCMais** [comment]
I think it's better to handle this via process manager like [PM2](http://pm2.keymetrics.io/docs/usage/cluster-mode/).

**Comment by ulani** [comment]
@nuclearspike   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
