### ISSUE TITLE
`npm test` fails with Segmentation Fault

### ISSUE THREAD

**Issue by mbrochh** [kriasoft/react-starter-kit#85]
When I run `npm test` I'm getting the following output:

```
Using Jest CLI v0.4.0
Waiting on 1 test...sh: line 1: 51565 Segmentation fault: 11  jest
npm ERR! Test failed.  See above for more details.
```

I'm on OSX. Cloned the repo, ran `npm install` and then `npm test`.

**Comment by koistya** [comment]
It seems like Jest doesn't work well with node.js 0.12.x and io.js. I'm considering replacing Jest with Mocha + JSDom. See https://github.com/kriasoft/react-starter-kit/pull/78

**Comment by bpetersen** [comment]
I was able to get the tests to run with io.js 
Jest-cli v0.4.0
iojs v1.6.4
arch linux

**Comment by koistya** [comment]
I believe this issue was resolved.
