### ISSUE TITLE
Best way import jQuery plugins or external client scripts?

### ISSUE THREAD

**Issue by manhhailua** [kriasoft/react-starter-kit#856]
My projects comes with quite many external jQuery plugins. And I got troubles to import them into a specific component and make them work with development mode by `npm start` (server side rendering).
My current solutions is to add them all to the bottom of `Html.js` return func. But, this way increases page load.

**Comment by manhhailua** [comment]
@frenzzy : there will be too many things in `Html`. Is that good?
My `Html` is now like this!
![Html](http://i652.photobucket.com/albums/uu246/Manhhailua/Screen%20Shot%202016-09-19%20at%2010.17.49%20PM_zpsqunljzd5.png)

**Comment by codetony25** [comment]
I usually add external vendor libraries in `/assets/`

**Comment by manhhailua** [comment]
@codetony25 : would you please show some peaces of code?

**Comment by minhnguyenwp** [comment]
I have same problem with this. 
**how can i use jquery plugin in React comp.** 
i did:
- import jquery plugin in Html.js
- in componentDidMount of Component i run .slick({...})

and i got this error. 
<img width="821" alt="screen shot 2017-06-21 at 2 14 22 pm" src="https://user-images.githubusercontent.com/14305088/27371802-66c9d1aa-568c-11e7-8da4-9fed14c3b1f5.png">

**Comment by frenzzy** [comment]
If third-party plugins changes DOM, you need to create uncontrolled components for them, i.e.
```js
shouldComponentUpdate() {
  return false;
}
```

**Comment by manhhailua** [comment]
@minhnguyenwp : please stop importing jQuery into your component, that will increase the time on bundling process of Webpack and your `bundle.js` file as well. Just add a `<script />` tag which has `src` to your jquery file and use `$` in every component without re-importing jQuery.

Be aware of eslint alert that `'$' is not defined`, put a comment `/* global $ */` or update `.eslintrc.js` file at `globals` property to ignore this alert.

Anyway, using jQuery to handle the DOM might cause React DOM tree crash (React indexes all the actual rendered DOM by it virtual DOM tree). So, please ensure you read these post before getting your hands dirty with React and jQuery co-operation.

1. https://facebook.github.io/react/docs/refs-and-the-dom.html
2. https://facebook.github.io/react/docs/uncontrolled-components.html
3. https://facebook.github.io/react/docs/integrating-with-other-libraries.html
4. https://medium.com/@shuvohabib/using-jquery-in-react-component-the-refs-way-969de9aa651f

**Comment by minhnguyenwp** [comment]
Hi @manhhailua , 
thank you so much for your reply. 
i pretty sure to know using jquery is limited in react. but in this case i need to do that. 
**So could you tell me more about. eslint alert that '$' is not defined.** 
i imported jquery in html and jquery plugins too. 
and i get that issue. 
<img width="391" alt="screen shot 2017-06-21 at 4 19 02 pm" src="https://user-images.githubusercontent.com/14305088/27376785-5de02ee8-569d-11e7-9822-698810bb21dc.png">
![screen shot 2017-06-21 at 4 18 55 pm](https://user-images.githubusercontent.com/14305088/27376791-66a31b30-569d-11e7-85f7-2106742f9341.png)

**Comment by manhhailua** [comment]
@minhnguyenwp : `.slick` function is not belong to origin `$` or `jQuery` object. Moreover, Webpack separates each package that is imported to a component, so you cannot call `.slick` via `$` or `jQuery` object if you continue importing jQuery this way. Sorry.

**Comment by minhnguyenwp** [comment]
@manhhailua  I did like your words.
1. Html.js 
`
 <script src="js/libs.js"></script>
 <script src="js/plugins.js"></script>
`
2. in Component, no longer importing jQuery or jQ plugin. 
3. Just using $('...').slick() 

Please show me a right way. im just a new-comer in react.

**Comment by manhhailua** [comment]
@minhnguyenwp : are you currently using React-Starter-Kit? You wrote the right way in your most recent comment. Try it.

**Comment by minhnguyenwp** [comment]
@manhhailua  
Yes, i'm. 
Now i get this: ReferenceError: $ is not defined
"eslint alert that '$' is not defined, put a comment /* global $ */ on top of your files or update .eslintrc.js file at globals property to ignore this alert." 

could u tell more about this?

**Comment by manhhailua** [comment]
@minhnguyenwp : that's the linting error from `eslint`. Refer to the documentation from ESLint website via this: http://eslint.org/docs/user-guide/configuring#specifying-environments
Btw, imo, React-Starter-Kit is not recommended for React's starters.

**Comment by Dr-Steve** [comment]
Also having trouble with this.  I imported jquery and a plugin in index like so:

 ```
 <script src = "imports/jquery-3.2.1.js"></script>
 <script src = "imports/jquery.form.min.js"></script>
```
And I still get $ is undefined.  If I import jquery in the component with:

`import $ from 'jquery';`

I can use jquery, but then I can't use my plugin.

**Comment by manhhailua** [comment]
@Dr-Steve you should not import `jQuery`. Just attach it via `<script>` tags and you're good to go use it inside `componentDidMount`.

**Comment by anitahkimanzi** [comment]
I am using materializecss where by i am using materialize-sidenav [Link:](http://materializecss.com/side-nav.html) I want to intergrate jquery plugin for it to work but it bring an error

**ERROR**
×
TypeError: __WEBPACK_IMPORTED_MODULE_1_jquery___default(...)(...).sideNav is not a function
HTMLDocument.<anonymous>
C:/Users/LCY/Desktop/Kimanzi/ReactJS-projects/dashboard/src/Header.js:7
   4 | 
   5 |    componentDidMount = () =>{
   6 |        $( document ).ready(function(){
>  7 |            $(".button-collapse").sideNav();
   8 |        })
   9 |    }
  10 |    
View compiled
▶ 2 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.



**REACTJS CODE**
import React from 'react';
import $ from 'jquery';

export default class Header extends React.Component {
componentDidMount = () =>{
        $( document ).ready(function(){
            $(".button-collapse").sideNav();
        })
    }
    
  render () {
    return (
    <nav>
        <div className="nav-wrapper header">
            <a href="/" className="brand-logo">Home</a>
            <a href="#" data-activates="mobile-demo" className="button-collapse">
                <i className="material-icons">menu</i>
            </a>
            <ul className="right hide-on-med-and-down">
                <li><a href="/Login">LOGIN</a></li>
                <li><a href="/Signup">SIGN UP</a></li>
            </ul>
            <ul className="side-nav" id="mobile-demo">
                <li><a href="/Login">LOGIN</a></li>
                <li><a href="/Signup">SIGN UP</a></li>
            </ul>
        </div>
  </nav>

**Comment by manhhailua** [comment]
@rorteg there's going to be unit testing issue on your solution.

**Comment by manhhailua** [comment]
@rorteg 
1. `windows` is a browser instance. Most of time you will test or bundle in `nodejs` environment where `windows` is definitely `undefined`. [jsdom](https://github.com/jsdom/jsdom) or [karma](https://karma-runner.github.io/2.0/index.html) can handle this issue, but you will have to spend more time on further mocking and configuration.
2. `flexslider` is also a component and you can't test it. You should wrap it by a react component.
3. if `flexslider` somehow changes the rendered DOM you will not able to test it and `react` will throw errors.

**Comment by AbdelhafidFutureTrendz** [comment]
I have this error !!

ERROR in ./src/components/home/slider_section_element/FlexSlider.js
Module not found: Error: Cannot resolve module 'flexslider' in /Volumes/Data/Front_Project/my-project-name/src/components/home/slider_section_element
 @ ./src/components/home/slider_section_element/FlexSlider.js 29:18-39

**Comment by AbdelhafidFutureTrendz** [comment]
This is my code bellow:

import React, {Component} from 'react'
import $ from '../../common/Jquery' // Import component
import flexSlider from 'flexslider' // Import directly from node-modules

class FlexSlider extends Component {
  componentDidMount() {
    $(".flexslider").flexslider({
      controlNav: true,
      directionNav: false,
      animation: "fade"
    });
  }

  render () {
    return (
      <div className="hero hero-slider">
        <ul className="slides">
          <li data-bg-image="dummy/slider-1.jpg">
            <div className="container">
              <h3 className="slider-subtitle">Your header goes here</h3>
              <h2 className="slider-title">Professional</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa molestiae necessitatibus possimus
                ducimus facere, error, nostrum. Quos sapiente ducimus maxime odio alias dolor consequuntur, maiores
                commodi exercitationem veniam. Id, ex?</p>
              <a href="#" className="button large">Read more</a>
            </div>
          </li>
          <li data-bg-image="dummy/slider-2.jpg">
            <div className="container">
              <h3 className="slider-subtitle">Your header goes here</h3>
              <h2 className="slider-title">Professional</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In maiores illo eligendi obcaecati
                reiciendis, vel perspiciatis aliquid esse architecto deleniti asperiores, laboriosam nemo rerum! Ipsam
                numquam delectus minus iure sit!</p>
              <a href="#" className="button large">Read more</a>
            </div>
          </li>
          <li data-bg-image="dummy/slider-3.jpg">
            <div className="container">
              <h3 className="slider-subtitle">Your header goes here</h3>
              <h2 className="slider-title">Professional</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam iure, alias error suscipit porro
                quidem minus, autem repellendus rerum labore corrupti! Quia quas, architecto, quis non pariatur quisquam
                nisi magnam.</p>
              <a href="#" className="button large">Read more</a>
            </div>
          </li>
        </ul>
      </div>
    )
  };
};

export default FlexSlider

/*let liStyle = {
  background:'linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(../../../public/images/slider/maalem-slider-1.jpg) 50% 65%',
  backgroundSize:'cover',
  height:'100%'
};

const FlexSlider = () => {
  return (
    <div className="flexslider slider" id="slider-3">
      <ul className="slides">
        <li className="item-1 back-size">
        </li>

        <li className="item-2 back-size">
        </li>
      </ul>
    </div>
  );
};

export default FlexSlider;*/

**Comment by mgolshan-talentnet** [comment]
Follow this solution:
https://stackoverflow.com/a/33351325/4980017

**Comment by gucompi** [comment]
> @frenzzy : there will be too many things in `Html`. Is that good?
> My `Html` is now like this!
> ![Html](https://camo.githubusercontent.com/bcc4b2fc8e095e45ca71f1869542b6827fdabcd8/687474703a2f2f693635322e70686f746f6275636b65742e636f6d2f616c62756d732f75753234362f4d616e686861696c75612f53637265656e25323053686f74253230323031362d30392d3139253230617425323031302e31372e3439253230504d5f7a707371756e6c6a7a64352e706e67)

thank you!

**Comment by Zill-Saqee** [comment]
hello everyone , can anyone please help in this problem                                                                                          I am doing conversion from html template to react project.In html template external libraries like jquery , chosenjs are used but when i add them in index.html file of react project following error message is shown on console window and these libraries arenot working  
![err1](https://user-images.githubusercontent.com/42487746/76995994-8b270580-6972-11ea-89d1-0edf2a55f28e.png)
