### ISSUE TITLE
How do I enable server side rendering in react-intl repo?

### ISSUE THREAD

**Issue by sudharsan1988** [kriasoft/react-starter-kit#863]
Hi, I thought server side rendering was already enabled on this repo(react-intl)? When I look at the html elements on chrome developer console(dev server:3001), the data-reactid is incremental but I read some article that server side rendering will have random value like this '.4l224jkvls.0'.

I went through the below commit but it looks like, it isn't meant for react-intl repo/Redux

https://github.com/kriasoft/react-starter-kit/pull/833/commits/9ca408d385b3f8441c6c41b61debcfbc18d5b43b

I'm bit confused now. Please help me out. Thanks in advance!

**Comment by viktortsarevskiy** [comment]
@sudharsan1988 server side rendering working in `react-intl` branch by default. The easest way to test it:
Run command
`curl localhost:3001 > index.html`
and then open `index.html` in your browser.

**Comment by sudharsan1988** [comment]
@viktortsarevskiy , thank you for your response. I just followed your instruction to run this command while I ran "npm start" and below was the response that I've got.

curl localhost:3001 > index.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32037  100 32037    0     0   555k      0 --:--:-- --:--:-- --:--:--  558k

According to Dan Prince's answer to this question http://stackoverflow.com/questions/17585787/whats-data-reactid-attribute-in-html

When server side rendering happen, data reactid will be random. I went through both localhost:3000 & localhost:3001 but couldn't see the random reactid hence I got this question.

Also, whenever I run localhost:3000, I couldn't make any of the Javascript code to be working as it's missing main.js from the assets folder.

**Comment by viktortsarevskiy** [comment]
@sudharsan1988  incremental data-reactid appeared in React v.15.0, but I am also confusing why it is appear in any case, because [here](https://facebook.github.io/react/blog/2016/04/07/react-v15.html) was announced that reactid will be go out.

**Comment by sudharsan1988** [comment]
I deployed my copy to Heroku and here is the link , https://blooming-crag-72887.herokuapp.com/

As you can see my data-reactid is incremental and totally different from RSK demo site.

RSK demo site's data-reactid are random which starts with a dot. That's why I want to make sure if I am missing something in here. I went through the package.json in all the repos and they use the same version of react anyway.
