### ISSUE TITLE
Required prop 'context.store' and 'store' failed propType

### ISSUE THREAD

**Issue by itaied246** [kriasoft/react-starter-kit#864]
I have cloned the repo and checked out to `redux` branch. Then I hit `npm install` and `npm test` and I get the following error:

```
Warning: Failed propType: Required prop `context.store` was not specified in `App`.
Warning: Failed propType: Required prop `store` was not specified in `Provider`.
```

Any thoughts on that?

Also, trying to merge `redux` branch into master resulted conflicts.

**Comment by degroote22** [comment]
I'm also having issues using the redux branch.

**Comment by bingo-lumity** [comment]
@langpavel 

I was looking into why setting the context in client.js/server.js did not propagate down to my children components.

client.js
```
// Global (context) variables that can be easily accessed from any React component
// https://facebook.github.io/react/docs/context.html
const context = {
  color: 'purple',
  // Enables critical path CSS rendering
  // https://github.com/kriasoft/isomorphic-style-loader
  insertCss: (...styles) => {
    // eslint-disable-next-line no-underscore-dangle
    const removeCss = styles.map(x => x._insertCss());
    return () => {
      removeCss.forEach(f => f());
    };
  },
};
```

App.js
```
const ContextType = {
  color: PropTypes.string.isRequired,
  // Enables critical path CSS rendering
  // https://github.com/kriasoft/isomorphic-style-loader
  insertCss: PropTypes.func.isRequired,
  // Universal HTTP client
  fetch: PropTypes.func.isRequired,
};
```

If you inspect, say, the Home.js component, the context object is empty. I did notice that the WithStyles wrappers had context, namely "insertCss" property with a function. Do you suppose these conflict with the App-level context?

**Comment by bingo-lumity** [comment]
Ah, never mind, I just realized that I need to specify the child component's "contextTypes" static property.

**Comment by langpavel** [comment]
This should be fixed. Closing
