### ISSUE TITLE
`npm start` fails when requiring non-isomorphic components

### ISSUE THREAD

**Issue by 0x24a537r9** [kriasoft/react-starter-kit#877]
I'm just getting started with React Starter Kit, and while I like it so far, I've already run into issues rendering a basic CodeMirror component. I'm currently using the `react-codemirror` React component with an almost completely fresh pull of RSK (see my [Editor.js](https://github.com/0x24a537r9/JsBench/blob/feature/redux/src/routes/editor/Editor.js)).

That at least runs (albeit without proper CodeMirror styles), but if I want to get CodeMirror's `javascript` mode option working, I need to uncomment the `import 'codemirror/mode/javascript/javascript';` per the react-codemirror README.md. When I do so, I get the following error on npm start:

```
/home/username/dev/JsBench/node_modules/codemirror/lib/codemirror.js:12
    module.exports = mod();
                     ^
ReferenceError: navigator is not defined
    at /home/username/dev/JsBench/node_modules/codemirror/lib/codemirror.js:24:28
    at userAgent (/home/username/dev/JsBench/node_modules/codemirror/lib/codemirror.js:12:22)
    at Object.<anonymous> (/home/username/dev/JsBench/node_modules/codemirror/lib/codemirror.js:17:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /home/username/dev/JsBench/node_modules/codemirror/mode/javascript/javascript.js:6:9
    at Object.<anonymous> (/home/username/dev/JsBench/node_modules/codemirror/mode/javascript/javascript.js:11:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
/home/username/dev/JsBench/tools/runServer.js:71
        throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
```

Part of me is thinking "well duh navigator isn't supported--it's trying to render isomorphically on the server". But then I'm confused why it worked without the additional mode import in the first place.

To repro, just clone https://github.com/0x24a537r9/JsBench and run `npm install` and `npm start`. The code in question is in [`src/routes/editor/Editor.js`](https://github.com/0x24a537r9/JsBench/blob/feature/redux/src/routes/editor/Editor.js).

It'd be great if I could get an answer to exactly what's causing the exception, but even knowing where the problem probably lies (Webpack configuration? react-codemirror? CodeMirror? React Starter Kit's isomorphic component?) would be helpful. I'm thinking it might be Webpack-related since uncommenting the `import 'codemirror/lib/codemirror.css';` also fails to load the core CodeMirror CSS (albeit with a different error), or possibly related to the isomorphic renderer (not sure how that's supposed to handle non-isomorphic 3rd party code). I can say that this is an RSK-specific issue though, since I've found multiple examples of CodeMirror working with other React apps (see [here](https://github.com/react-toolbox/react-toolbox/blob/36e3a86c2e4e4c29f8bd7a8f6e26324f9cc24659/docs/app/components/editor/index.jsx) and [here](https://github.com/survivejs-demos/react-demos/blob/master/demos/index.js)).

**Comment by 0x24a537r9** [comment]
Turns out it's even easier to repro. Just clone a fresh react-starter-kit repo and run:

```
npm install
npm install codemirror --save
sed -i "15s|^|import 'codemirror';\n|" src/components/Header/Header.js 
npm start
```

It should fail exactly the same without having to clone my repo, and shows how merely importing codemirror breaks it.

Any thoughts on this? This probably has a trivially simple solution, but given that this is my first experience with most of these technologies I'm at a loss to even know where to look. In the meantime, I can't make any progress :(

**Comment by ulani** [comment]
@0x24a537r9   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
