### ISSUE TITLE
Inline CSS 

### ISSUE THREAD

**Issue by mxmtsk** [kriasoft/react-starter-kit#881]
I need to set a background image dynamically to a pseudo element so I'm making this:

```
        <style type="text/css">{`
            .hero-account::before{
              background-image: url('${headerBackground}');
            }
          `}
        </style>
```

Unfortunately the ' in my background-image statement are getting translated to &#x27; so the image is not working. Is this a bug or am I doing it wrong?

**Comment by koistya** [comment]
@mxmtsk React encodes unsafe characters, try this:
```
<style type="text/css" dangerouslySetInnerHTML={{ __html: `
  .hero-account::before{
    background-image: url('${headerBackground}');
  }
` }} />
```
