### ISSUE TITLE
Routing produces error when query parameter is given

### ISSUE THREAD

**Issue by D063520** [kriasoft/react-starter-kit#885]
Hello, 

thank you for providing this starter kit. We are trying to adapt it to our needs and we encountered problems when doing rooting using query parameters. We have modified the contact component and added a get request into the componentWillMount part:

import $ from 'jquery';

  componentWillMount() {
    this.serverRequest = $.get(
      url ,
      function (result) {
        });
      }.bind(this));
  }

When calling the component with "localhost:3001/link" everything works fine, when calling something like "http://localhost:3001/contact?query=hello"  it fails with the error message:

TypeError: _jquery2.default.get is not a function
    at ContactPage.componentWillMount (/Users/Dennis/WebstormProjects/website/build/webpack:/src/components/ContactPage/ContactPage.js:39:26)
    at ReactCompositeComponentMixin.mountComponent (/Users/Dennis/WebstormProjects/website/node_modules/react/lib/ReactCompositeComponent.js:210:12)
    at wrapper [as mountComponent] (/Users/Dennis/WebstormProjects/website/node_modules/react/lib/ReactPerf.js:66:21)

Any ideas what is going wrong. 
Thank you
Dennis

**Comment by frenzzy** [comment]
Most likely you need to use `$.get()` inside `componentDidMount`

**Comment by koistya** [comment]
Dennis, or maybe you need to use `fetch(...)` instead of `$.get(...)`. The former one can work universally on the server and client (inside componentWillMount()).

**Comment by D063520** [comment]
Yes, componentDidMount solved it. Thank you very very much! Can you also explain me way?

**Comment by koistya** [comment]
componentWillMount() fires in both client and server envrionments (before render()), and componentDidMount() fires only in the browser environment (after render()). $.get() is not designed to be used in Node.js (server) environment.
