### ISSUE TITLE
Just a couple of questions

### ISSUE THREAD

**Issue by AmitMY** [kriasoft/react-starter-kit#886]
I would like to know two things:

-  Is there a "system" type thing in the files? - meaning, files that I can just update when react-starter-kit comes out with another release? Just asking to know if I can count on bug-squashing for an existing project. in a future.
-  Why is this not written using TypeScript? I didn't see a place where you addresses this.
(I am coming from Angular background, so I am a bit confused why not to use TS)

Thanks, I really like this project and will hopefully work with it soon

**Comment by koistya** [comment]
@AmitMY the build scripts and configs (`tools` folder) might be updated with time, also `server.js` and `client.js` (entry points) and routing, so if you keep this files as close to original version as possible, it will help to pull and merge updates (either by using git fetch/merge or folder comparison tool). If you think something is missing in the core framework, create a PR, if it's a good addition/fix it will be merged to the master branch, it will also help to keep your project and RSK in sync.

Unfortunately, TypeScript doesn't have as many useful plugins as Babel, e.g. Hot Module Replacement / React Hot Loader. But in combination with Flow, it might be a great alternative to TypeScript. Another benefit of Flow is that it performs a more comprehensive analysis of your code reporting more potential issues/bugs than TypeScript can do.

If you need help with adopting boilerplate for your project, I'll be glad to assist you.
