### ISSUE TITLE
Lots of *.json.gzip files in the project root after installation...

### ISSUE THREAD

**Issue by joetidee** [kriasoft/react-starter-kit#890]
Lots of *.json.gzip files in the project root after installation... any ideas why ?

**Comment by langpavel** [comment]
Can you provide steps how to reproduce?

**Comment by joetidee** [comment]
I just installed the kit as per the instructions. Could it be with something to do with folder permissions, i.e. ar ethese files something to do with the set-up which are normally deleted once set-up has completed?

**Comment by langpavel** [comment]
Can you be more specific? Which installation steps?

**Comment by joetidee** [comment]
These:

https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md

**Comment by langpavel** [comment]
Can you be more specific? There are three different methods specified

**Comment by joetidee** [comment]
I went through the Quickstart method, after ensuring that all the Node, NPM and node-gyp dependencies were in place.

**Comment by langpavel** [comment]
Which of two?

**Comment by joetidee** [comment]
I can only see one Quickstart method.

**Comment by langpavel** [comment]
I see three:

> You can start by cloning the latest version of React Starter Kit (RSK) on your local machine by running:
> 
> $ git clone -o react-starter-kit -b master --single-branch \
>       https://github.com/kriasoft/react-starter-kit.git MyApp
> $ cd MyApp
> Alternatively, you can start a new project based on RSK right from WebStorm IDE, or by using Yeoman generator.
> You can start by cloning the latest version of React Starter Kit (RSK) on your local machine by running:
> 
> $ git clone -o react-starter-kit -b master --single-branch \
>       https://github.com/kriasoft/react-starter-kit.git MyApp
> $ cd MyApp
> Alternatively, you can start a new project based on RSK right from WebStorm IDE, or by using Yeoman generator.

1. git
2. WebStorm
3. Yeoman

If you are using git, there is no reason for *.json.gzip files.
You provide no useful info how to reproduce, about your setup..

I'm surprised myself why I wasting my time for answering you... ;-)

If you report bug in future, provide as much info with exact steps how to reproduce. This repository is used by hundreds of people an noone have same issue, so it must be on your side, then please be as much concrete as you can!

If you want to chat, there is [Gitter channel](https://gitter.im/kriasoft/react-starter-kit), but same apply here, be concrete, otherwise people will ignore you!

**Comment by joetidee** [comment]
I have to be honest, you attitude isn't good. I have been as clear as I can be... I went through the Quickstart section here:

https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md

and have said that after this process there are alot of *.json.gzip files in the project root.

**Comment by ucay** [comment]
Maybe it's from webpack.config.js
`cacheDirectory: DEBUG`
you can try set it to false.

or see this webpack [issue](https://github.com/webpack/webpack/issues/2223)

**Comment by langpavel** [comment]
Looks like relevant information, thanks @ucay

**Comment by langpavel** [comment]
@joetidee Please reopen if you are still in trouble
