### ISSUE TITLE
Merging the React Intl branch...

### ISSUE THREAD

**Issue by joetidee** [kriasoft/react-starter-kit#891]
In the documentation titled "How to Integrate React Intl" you suggest merging this feature branch into 'git' - do you mean merge it into the master branch?

I tried this and there were alot of merge conflicts - is this correct?

**Comment by jwhchambers** [comment]
Hi @joetidee, @langpavel, I have managed to merge react-intl into the master on my desktop and it now builds and runs fine. I am however completely useless with git and think that maybe I should have merged master into react-intl and then done a PR. Anyway, I have pushed a version of it to a repo on my account https://github.com/jwhchambers/react-starter-kit for now. I am going to try and spend some time today working out how to use git so I can push this back as a PR on the actual kriasoft repo. If you have any advice for how I should achieve this or any changes I should make to the code then please let me know :)

**Comment by joetidee** [comment]
If you are rubbish at GIT, how did you manage to merge the react-intl feature branch into master? I mean, when I tried, there were quite a few merge conflicts which were difficult to understand what I should keep or what i should overwrite during the merge, so how did you go about this?

**Comment by jwhchambers** [comment]
I managed to work my way around the git part by using a few online tutorials. The javascript part was fine, just I am quite new to using git. In answer to your question, it took me a quite a bit of time to work out how each branch was structured and then I just incorporated all the react-intl features into the flow of the master branch. As you say, there were a lot of merge conflicts to resolve, mainly in server.js, client.js, app.js layout.js and provide.js.

**Comment by langpavel** [comment]
@jwhchambers have your code on your Github? Can I try merge from it?

**Comment by jwhchambers** [comment]
https://github.com/jwhchambers/react-starter-kit the only change I have done past this on my local is take the div out from around the ProvideIntl in layout.js

**Comment by jwhchambers** [comment]
I don't think it's perfect, but it's a start! :)

**Comment by jwhchambers** [comment]
Also I have just noticed it might be one or two commits behind now, but it takes into account the history version change and the app/layout split

**Comment by JCMais** [comment]
Just running ``git clone https://github.com/kriasoft/react-starter-kit.git .`` and ``git merge origin/feature/react-intl`` worked for me.

**Comment by jwhchambers** [comment]
Hi @JCMais , I believe this issue should now be closed as @langpavel has cleared the backlog and there are no longer any merge conflicts.

**Comment by langpavel** [comment]
True
