### ISSUE TITLE
iisnode problem with react-intl branch

### ISSUE THREAD

**Issue by keremciu** [kriasoft/react-starter-kit#898]
hello guys,

I was working on `feature/react-intl` branch. I've updated last night to #895 

It is working on my macosx and windows with "npm start" command but on my iisnode server it is not working anymore. My iisnode log like that:
```
Unexpected token < in JSON at position 0 Object.parse /[node-fetch]/lib/body.js:48:15
```

**Comment by keremciu** [comment]
Fix here:

@koistya helped me on Gitter.im room, 

@keremciu it seems like when you do fetch(‘/api/someting’) it cannot parse the response from that URL as JSON
@keremciu try to add console.log(..) statements into /core/fetch/fetch.sever.js to see what’s going on, or use a debugger

I've tried it and problem was in ```src\routes\content\index.js```

I was on my console logs, my graphql link was wrong, it looks like 

```
"The server is running at http://localhost:\\.\pipe\3af11fdd-44dd-44c6-b1fa-5e6ed813f08b/
/graphql
Body {
  url: 'http://localhost:\\\\.\\pipe\\3af11fdd-44dd-44c6-b1fa-5e6ed813f08b/graphql',
```

so weird? yea. I've fixed the problem

I fixed this problem by adding 
```
<appSettings>
       <add key="WEBSITE_HOSTNAME" value="localhost:3000" />
</appSettings>
```
 to ```web.config``` on iisnode,


I don't know but the problem was all about IIS server, "process.env.WEBSITE_HOSTNAME" was wrong. If you are not using port 3000, you need to change ```localhost:3000``` value

**Comment by koistya** [comment]
@keremciu FYI, if you deploy your site to Azure App Service, then you will have to use `process.env.WEBSITE_HOSTNAME` since localhost:XX just won't work there.
