### ISSUE TITLE
'Unexpected token .' when importing a React component from node_modules

### ISSUE THREAD

**Issue by robertpataki** [kriasoft/react-starter-kit#902]
I have been trying to get my head around this issue, but unfortunately I haven't had any luck yet.

When I install a 3rd party component (react-flexbox-grid), and try to import it in `Layout.js` (https://github.com/robertpataki/react-starter-kit-component-css-bug/blob/master/src/components/Layout/Layout.js#L18), I get the following error:

```
xxx ~/projectLocation/react-starter-kit-component-css-bug (master)*$ npm start

> @ start /Users/xxx/projectLocation/react-starter-kit-component-css-bug
> babel-node tools/run start

[20:04:16] Starting 'start'...
[20:04:16] Starting 'clean'...
[20:04:16] Finished 'clean' after 134 ms
[20:04:16] Starting 'bound copy'...
[20:04:17] Finished 'bound copy' after 147 ms
webpack built 06ec4a9f5981192caafc in 5073ms
Child
    Time: 5073ms
                               Asset     Size  Chunks             Chunk Names
        main.js?06ec4a9f5981192caafc  1.69 MB       0  [emitted]  main
    main.js.map?06ec4a9f5981192caafc  2.02 MB       0  [emitted]  main
Child
    Time: 5245ms
            Asset    Size  Chunks             Chunk Names
        server.js  211 kB       0  [emitted]  main
    server.js.map  235 kB       0  [emitted]  main
webpack: bundle is now VALID.
/Users/xxx/projectLocation/react-starter-kit-component-css-bug/node_modules/flexboxgrid/dist/flexboxgrid.css:1
(function (exports, require, module, __filename, __dirname) { .container-fluid,
                                                              ^
SyntaxError: Unexpected token .
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/projectLocation/react-starter-kit-component-css-bug/node_modules/react-flexbox-grid/lib/components/Grid.js:18:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
/Users/xxx/projectLocation/react-starter-kit-component-css-bug/tools/runServer.js:71
        throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
        ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.server.once (/Users/xxx/projectLocation/react-starter-kit-component-css-bug/tools/runServer.js:53:15)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a pxxxlem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/projectLocation/react-starter-kit-component-css-bug/npm-debug.log
xxx ~/projectLocation/react-starter-kit-component-css-bug (master)*$ 
```

It seems that when running `npm start`, the server tries to load the css file as JavaScript, and I am not sure how to kindly ask WebPack to stop being confused.

I've tried with other components, or simply importing a css file both from `node_modules` or the `components` folder, the result is always the same.

Obviously I have no control over a component requiring another 3rd party dependency from `node_modules` folder, so this issue is particularly tricky to fix :/

Has anyone come across this issue, and have an actual fix for it?

Any help is much appreciated.

**Comment by ucay** [comment]
Seems like react-flexbox-grid issue with babel.
Please look at here 
https://github.com/roylee0704/react-flexbox-grid/issues/28

**Comment by robertpataki** [comment]
Thank you @ucay! I've tried that already, and I couldn't get it working. I'm abandoning `react-flexbox` altogether :(

**Comment by jhabdas** [comment]
@robertpataki Are you by chance using inline styles, like [aphrodite](https://github.com/Khan/aphrodite)? I enjoy inline style pattern, and the issue @ucay points at seems to be honing in the root cause (I'm using a different isomorphic boilerplate), but I'm feeling a  bit of the say way though would prefer not to roll my own flexbox if it can be avoided.

**Comment by robertpataki** [comment]
@jhabdas this was almost 2 weeks and ~15 Universal React boilerplates ago, so I'm not entirely sure what eactly I was doing while trying to do there :) I think the main problem is that the component's CSS file is being loaded into Webpack as JavaScript and not as CSS/SCSS. I wasn't trying to do inline styles, other than the styling already in place via CSS modules, which this starter kit seems to favour. I hope it helps.

**Comment by jhabdas** [comment]
Haha. Thanks @robertpakaki. If you land on any exceptional boilerplates with server-side rendering, feature-first organization, lazy-loaded JS payloads and code splitting with stable HMR I'd love to see a link here: https://habd.as/awesome-react-boilerplates/

Hope that doesn't feel spammy; I don't monetize that website in any way.

**Comment by mschipperheyn** [comment]
I'm struggling with the same issue, I seem to have solved it by adding 

      test: /\.(css|scss)$/,
      loader: ExtractTextPlugin.extract({
                use: [
                    'css-loader/locals?modules=1&importLoaders=1&localIdentName=[hash:base64:10]',
                    'sass-loader',
                ],
              }),

for the server-side webpack css/scss loader.

However, I'm now getting other follow up issues, so I'm not a 100% sure I got it.
