### ISSUE TITLE
Approach question - Passing events to header

### ISSUE THREAD

**Issue by pcooper1979** [kriasoft/react-starter-kit#904]
Hi,

I've downloaded the kit and altered my app.js to include a site header, I want to have a mini basket in the header and want to pass an "AddToCart" event from a child page into the header.

App.js now looks like this

`  render() {

```
return !this.props.error ? (

  <div>

    <Header data={this.state.navData} isShopPage={this.state.isShopPage} />

    {this.props.children}

    <Footer />

  </div>

) : this.props.children;
```

  }`

I've been using the kit to get to grips with react so this may be a newbie question but can someone explain the best way to wire up and pass an event from a child route back up into the app and over to the header component?

Thanks

**Comment by ucay** [comment]
Same with me, and I've tried something like this
`
<Header 
    data={this.state.navData} 
    isShopPage={this.state.isShopPage} 
    shopData={this.props.children.props.shopData}
/>
`
so, i just need to add props in children
`<Shop shopData={this.state.whatever}/>`

I don't know if this is good or bad way, at least it works for me. :smile:

**Comment by pcooper1979** [comment]
Thanks, that allows me the pass a value however I'm also looking to trigger an update within the Header, any ideas how?

**Comment by ucay** [comment]
From react [docs](https://facebook.github.io/react/tips/communicate-between-components.html)

> For communication between two components that don't have a parent-child relationship, you can set up your own global event system. Subscribe to events in componentDidMount(), unsubscribe in componentWillUnmount(), and call setState() when you receive an event. Flux pattern is one of the possible ways to arrange this.

Maybe you can try it, but i don't know ho to do it yet.

**Comment by callmenick** [comment]
You can create, dispatch, and listen for custom events with plain JS. So what the docs are saying is that in `componentDidMount`, you could listen for a custom event, and remove the event listener in `componentWillUnmount`. Then in the other component that you want to fire the event from, you dispatch it.

Some starter material here for you: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

**Comment by Jaikant** [comment]
@callmenick I want to change the size of the header, based on the url path. Is it better to do it by passing props or events?

**Comment by ulani** [comment]
@pcooper1979   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
