### ISSUE TITLE
HMR won't reload component changes

### ISSUE THREAD

**Issue by ChrisMashie** [kriasoft/react-starter-kit#907]
I'm fairly new to React and the Webpack environment so hopefully this is just me missing a setting but
if I make a fresh clone and install of react-starter-kit and get the server up and running without making ANY changes using 'npm start' I can't get the HMR to update the browser.  

I can get css changes to live update but if I for example go into the Header.js component and change the h1 tag from 'React' to 'Hello World' it will not reflect those changes without a manual refresh.  

My console shows that the bundle is rebuilding and validates and my devtools show all is well but no HTML is updated.  

client.js:58[HMR] connected
client.js:127[HMR] bundle rebuilding
client.js:130[HMR] bundle rebuilt in 2280ms
process-update.js:27[HMR] Checking for updates on the server...
process-update.js:100[HMR] Updated modules:
process-update.js:102[HMR]  - ./src/components/Header/Header.js
process-update.js:102[HMR]  - ./src/components/Layout/Layout.js
process-update.js:102[HMR]  - ./src/routes/home/Home.js
process-update.js:102[HMR]  - ./src/routes/contact/Contact.js
process-update.js:102[HMR]  - ./src/routes/login/Login.js
process-update.js:102[HMR]  - ./src/routes/register/Register.js
process-update.js:102[HMR]  - ./src/routes/admin/Admin.js
process-update.js:102[HMR]  - ./src/routes/content/Content.js
process-update.js:102[HMR]  - ./src/routes/notFound/NotFound.js
process-update.js:102[HMR]  - ./src/routes/notFound/index.js
process-update.js:102[HMR]  - ./src/routes/index.js
process-update.js:102[HMR]  - ./src/routes/content/index.js
process-update.js:102[HMR]  - ./src/routes/admin/index.js
process-update.js:102[HMR]  - ./src/routes/register/index.js
process-update.js:102[HMR]  - ./src/routes/login/index.js
process-update.js:102[HMR]  - ./src/routes/contact/index.js
process-update.js:102[HMR]  - ./src/routes/home/index.js
process-update.js:107[HMR] App is up to date.

Im using windows 10 and literally pulled down the repo today to install it.  Is there something I'm missing? I can't seem to find anyone with a similar problem :p

**Comment by frenzzy** [comment]
HMR works on all pages except main, because of this issue #871

![hmr](https://cloud.githubusercontent.com/assets/640669/19239823/77da8942-8f10-11e6-8a68-6908b8415282.gif)

**Comment by ChrisMashie** [comment]
Aha, I see.

I have this problem not only in Home.js but also for About.  Specifically the header and footer components wont update while on these pages/routes.  

However if I update the content in about.md such as "About me" to "About us" Then the page content will reflect the update ALONG with the header or footer update that did not reload last time.   I assume this has to do with the mentioned Ajax server to client issue mentioned in #871 as the content route uses parameters instead of loading another component directly.  I'm not sure to be honest how that works yet but I assume its related.  

But Ill keep checking back for a solution.  Thanks!

**Comment by ulani** [comment]
@ChrisMashie   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
