### ISSUE TITLE
Components' less files aren't being watched

### ISSUE THREAD

**Issue by yanivefraim** [kriasoft/react-starter-kit#91]
Inside gulpfile you can find that: 
`src.styles = 'src/styles/**/*.{css,less}';`
while components' less files are held inside
`components/{component-name}/{component-name}.less`

A simple solution will be to change src.styles to be:
`src.styles = 'src/**/*.{css,less}';`

This way it will take all less files from within the src folder. 

Is it an acceptable solution? If so, I would love to add a PR (:

**Comment by koistya** [comment]
@yanivefraim, FYI, the `styles` Gulp task and `./src/styles/` folder are going to be removed from the project. Currently webpack handles per-component CSS files as described here:

- http://webpack.github.io/docs/stylesheets.html
- https://github.com/webpack/style-loader
- https://github.com/webpack/url-loader
- https://github.com/webpack/file-loader

But if you have an alternative solution with per-component CSS, please share.

**Comment by yanivefraim** [comment]
@koistya, Thanks, I will read some more in order to better understand Webpack.

By the way - I was looking for a cool React/Flux starter kit to work/play with. This was by far the best I found! I was wondering if I could contribute back somehow (issues / take active part in development). I am pretty new to React (playing with it for several months now), after writing Angular.js in the last years

Thanks again!
Yaniv

**Comment by koistya** [comment]
@yanivefraim Thanks! And you're welcome to join the project! One of the upcoming tasks/features is to  make webpack save stats into a `.json` file, then use it to rename `app.js` (client bundle) into `app-<hash>.js` during a build and make sure that `index.html` references the correct file, e.g `<script src="app-63a7cef.js"></script>`. See `gulpfile.js > bundle task`. Would help me with that? I have many other interesting tasks/features like this one :)

**Comment by yanivefraim** [comment]
@koistya  Cool! I will love to help with that! I did the exact same think (Static files versioning with .json file holding those versions) at work - only that it was an Angular.js project and I used Grunt.js & grunt-hash-res plugin in order to do so. 

Should I do it on a fork? on a feature branch? How can I contact you for questions?

Thanks!
Yaniv

**Comment by koistya** [comment]
I believe this is no longer an issue. Feel free to reopen if needed. Assets versioning is already in place.
