### ISSUE TITLE
[intl] Get Messages without graphql request

### ISSUE THREAD

**Issue by mxmtsk** [kriasoft/react-starter-kit#911]
Hey,
I'm using the intl branch which works fine, but I'm not using the graphql api that is build into the starter kit. I have an external API which I'm calling, therefore I cannot use graphql to get the messages for the current locale, because I wanna keep the translations inside the source code and on the filesystem as it is currently.

Is there an alternative way (I'm sure there is) to get the messages? I've tried to copy and modify the code from the graphql resolve method to the redux action but fs is not working in the client so it doesn't work as I imagined.

Thanks for helping me out :)

**Comment by bbarrows** [comment]
I know this is old but if anyone runs into this in the future a quick hack that I am working on right (needs to be refactored but this may be helpful to someone):

    /* eslint-disable import/prefer-default-export */

    import {
      SET_LOCALE_START,
      SET_LOCALE_SUCCESS,
      SET_LOCALE_ERROR,
    } from '../constants';

    import fs from 'fs';
    import { resolve } from 'path';
    import Promise from 'bluebird';
    import { locales } from '../../config/config.default.js';

    // A folder with messages
    const CONTENT_DIR = resolve('./build/messages'); //resolve(__dirname, 'messages');

    const readFile = Promise.promisify(fs.readFile);

    async function readLocaleMessages(locale) {
      let localeData;
      try {
        localeData = await readFile(resolve(CONTENT_DIR, `${locale}.json`));
      } catch (err) {
        if (err.code === 'ENOENT') {
          throw new Error(`Locale '${locale}' not found`);
        }
      }

      return JSON.parse(localeData);
    };

    export function setLocale({ locale }) {
      return async (dispatch, getState, { graphqlRequest }) => {
        dispatch({
          type: SET_LOCALE_START,
          payload: {
            locale,
          },
        });

        try {
          const localeData = await readLocaleMessages(locale);
          const messages = localeData.reduce((msgs, msg) => {
            msgs[msg.id] = msg.message; // eslint-disable-line no-param-reassign
            return msgs;
          }, {});
          dispatch({
            type: SET_LOCALE_SUCCESS,
            payload: {
              locale,
              messages,
            },
          });

          // remember locale for every new request
          if (process.env.BROWSER) {
            const maxAge = 3650 * 24 * 3600; // 10 years in seconds
            document.cookie = `lang=${locale};path=/;max-age=${maxAge}`;
          }
        } catch (error) {
          dispatch({
            type: SET_LOCALE_ERROR,
            payload: {
              locale,
              error,
            },
          });
          return false;
        }

        return true;
      };
    }
