### ISSUE TITLE
Creating active Link behavior with history not working. 

### ISSUE THREAD

**Issue by ChrisMashie** [kriasoft/react-starter-kit#922]
I am trying to add a similar functionality to the <Link> component of react-router, where I can check to see if the current url path is the same as my link path to the outer component of my actual RSK <Link> component. 

My approach is to compare the path with history's pathname:  

```
import React, { PropTypes } from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import history from '../../core/history';
import s from './NavigationLink.css';
import cx from 'classnames';
import Link from '../Link';

function NavigationLink({page}) {

    const linkPath       = page.link;
    const currentPath    = (history.location.pathname === undefined) ?  'none' : history.location.pathname;
    const isActive       = linkPath== currentPath;

    return (
        <div className={cx(s.menuItem, (isActive ? 'active' : ''))}>
            <Link to={page.link}>{page.name}</Link>
        </div>
    );
}

NavigationLink.propTypes = {
    page: PropTypes.shape({
        link: PropTypes.string.isRequired,
        name: PropTypes.string.isRequired
    }).isRequired
};

export default withStyles(s)(NavigationLink);
```

But this is not quite working for a few reasons and I'm not sure how to tackle them.  The first problem is that on any page reload I get a type error:

TypeError
Cannot read property 'pathname' of undefined

No amount of testing pathname for undefined seems to help, I'm assuming this had to do with server side rendering. So I'm not quite sure how to approach that.  

The other issue is that although I can add an "active" class to my Navigation Link element the css selector ends up outputting :

```
<div class="NavigationLink_menuItem_2cO active" data-reactid="12"></div>
```

Which is fine and dandy and I know that's what its suppose to do but that means that my css 

```
.menuItem.active{} 
```

will never match the selector.  Again, here is a problem I am not sure how to approach.  I've read through #682 a few times trying to get a handle on how to approach this, but as of right now I don't need redux and am not using it and getCurrentLocation() has been removed as of v4.0.0-2.  

Any help or guidance would be appreciated! Thanks!

**Comment by aleksey-mukho** [comment]
Try:
const currentPath = (history.location) ?  history.location.pathname : 'none';

**Comment by ulani** [comment]
@ChrisMashie   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
