### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by kenny1har** [kriasoft/react-starter-kit#933]
node v6.9.1
Ubuntu 14.04

fresh clone #49399cd
npm install , npm start

> [02:16:48] Starting 'start'...
> [02:16:48] Starting 'clean'...
> [02:16:48] Finished 'clean' after 103 ms
> [02:16:48] Starting 'copy'...
> [02:16:48] Finished 'copy' after 157 ms
> webpack built bd47ba98ecf9fc4aa852 in 15457ms
> Child
>     Time: 15457ms
>                                   Asset     Size  Chunks             Chunk Names
>            main.js?bd47ba98ecf9fc4aa852  1.62 MB       0  [emitted]  main
>         admin.1.js?bd47ba98ecf9fc4aa852  7.58 kB       1  [emitted]  admin
>        main.js.map?bd47ba98ecf9fc4aa852   1.9 MB       0  [emitted]  main
>     admin.1.js.map?bd47ba98ecf9fc4aa852  7.88 kB       1  [emitted]  admin
> Child
>     Time: 15745ms
>                   Asset    Size  Chunks             Chunk Names
>         ../../server.js  242 kB       0  [emitted]  main
>     ../../server.js.map  240 kB       0  [emitted]  main
> webpack: bundle is now VALID.
> [02:08:57] The server is running at http://localhost:3000/
> [BS] Proxying: http://localhost:3000
> [BS] Access URLs:
>  ---------------------------------------
>        Local: http://localhost:3001
>     External: http://192.168.1.3:3001
>  ---------------------------------------
>           UI: http://localhost:3002
>  UI External: http://192.168.1.3:3002
>  ---------------------------------------
> [02:08:57] Finished 'start' after 18415 ms
> (node:17178) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): Error: Exited with code 3

**Comment by frenzzy** [comment]
Maybe some of modules were not updated correctly, can you try to reinstall from scratch?
```bash
rm -rf node_modules && npm install
```

**Comment by kenny1har** [comment]
tried several times deleting node_modules. npm cache clean -f

it is just a warning. it still runs smoothly.

**Comment by GGAlanSmithee** [comment]
try running with `node --trace-warnings` to see where the warning comes form.

**Comment by kenny1har** [comment]
node --trace-warnings ./node_modules/babel-cli/bin/babel-node.js tools/run start

it is still showing the same lines.
```
[08:01:16] Finished 'start' after 15200 ms
(node:20950) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): Error: Exited with code 3
```
