### ISSUE TITLE
Ignore first load fetch

### ISSUE THREAD

**Issue by kenny1har** [kriasoft/react-starter-kit#934]
When the page loaded, SSR contents/DOM are already passed in HTML.
The network is still requesting ajax for contents that are already rendered using SSR.

How to disable URL fetch in the client side only for the first page load ?

**Comment by frenzzy** [comment]
https://github.com/kriasoft/react-starter-kit/issues/813#issuecomment-242298055

**Comment by kenny1har** [comment]
thanks.
