### ISSUE TITLE
npm start not running

### ISSUE THREAD

**Issue by salshyn** [kriasoft/react-starter-kit#939]
npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/sam.test/Documents/Work/stest.github.io/node_modules/.bin:/usr/local/bin:/Applications/Postgres.app/Contents/Versions/latest/bin/:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
10 verbose lifecycle @~start: CWD: /Users/sam.test/Documents/Work/stest.github.io
11 silly lifecycle @~start: Args: [ '-c', 'babel-node tools/run start' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `babel-node tools/run start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid @
16 verbose cwd /Users/sam.test/Documents/Work/stest.github.io
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.9.0
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error @ start: `babel-node tools/run start`
22 error Exit status 1
23 error Failed at the @ start script 'babel-node tools/run start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node tools/run start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

from command line:
webpack: bundle is now VALID.
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/sam.test/Documents/Work/stest.github.io/build/webpack:/external "universal-router":1:1)
    at __webpack_require__ (/Users/sam.test/Documents/Work/stest.github.io/build/webpack:/webpack/bootstrap 3b1ce8bc878839b8141c:19:1)
    at Object.<anonymous> (/Users/sam.test/Documents/Work/stest.github.io/build/webpack:/server.js:20:1)
/Users/sam.test/Documents/Work/stest.github.io/tools/runServer.js:80
          throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
          ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.<anonymous> (/Users/sam.test/Documents/Work/stest.github.io/tools/runServer.js:54:17)
    at ChildProcess.g (events.js:273:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

**Comment by frenzzy** [comment]
[Requirements: node.js v6.5+](https://github.com/kriasoft/react-starter-kit/blob/master/package.json#L4)

**Comment by salshyn** [comment]
Yeehah, worked! Thanks!
