### ISSUE TITLE
Update React / Redux integration tutorial

### ISSUE THREAD

**Issue by AntonyKwok** [kriasoft/react-starter-kit#941]
I'm a newbie developer and, although I've learnt how to use the master branch of the React Start Kit, I'm having a very hard time integrating and using the feature/redux branch.

If an experienced developer could update the tutorial on how to integrate and use Redux (with a beginner's point of view), that would be awesome!

Thanks a lot!

**Comment by cellulosa** [comment]
Hi @andantonyan, based on my understanding you simply have to run this command: `git merge remotes/origin/feature/redux`. This may not work if you run the code from the documentation which only makes you download the master branch.

So let's assume you start from scratch:

    git clone https://github.com/kriasoft/react-starter-kit.git MyApp
    cd MyApp
    git merge remotes/origin/feature/redux

That's it!

**Comment by AntonyKwok** [comment]
Thanks for your help @cellulosa. The main pain point for me was the fact that the `App` component wasn't wrapped in a `Provider`. I was trying to `connect()` my other components to the Redux store but it didn't work because the store wasn't available globally.

I guess my question is: why include `react-redux` as a dependency if it's not used at all in the Redux Starter Kit?

**Comment by koistya** [comment]
@AntonyKwok take a look at PR #883 > Files changed, basically you would start by doing:

1. Install `redux`, `react-redux` and `serialize-javascript` npm modules
2. Add `core/createStore.js` file that initializes a new Redux store with your reducers, middlewares etc.
3. Call `createStore(..)` inside `server.js/app.get('*', ...)` (server-side rendering endpoint); pass the initialized store to your React app as a context variable (see `src/components/App.js`); after rendering your React app on the server, call `store.getState()` and embed that state into HTML page.
4. On the client (`src/client.js`), deserialize that state and initialize a new Redux store (e.g. `store = createStore(window.APP_STATE)`; pass that `store` object as a context variable to your React app.
5. Decorate your React components with `connect` HOC coming from the `react-redux` module.

**Comment by AntonyKwok** [comment]
Hey @koistya thanks for the steps! I'll try and update the Redux integration doc. :)

**Comment by langpavel** [comment]
Hi guys, I'm still alive but too busy, so thanks for dealing with this. In `feature/redux` there is no usage indeed. If someone want, one of best will be migrate content fetching in router to action, in better case witch caching.
I have do this in `feature/react-intl`. Localization messages are fetched on server and then they are reused from deserialized state. However if you switch language, new messages are fetched. If they are already present, they are switched and refreshed some milliseconds after request arrives. This is not needed at all because messages are static data, but extend action code to not do new request at all is really easy...

I will be glad if someone mention `react-intl` branch as a working example of redux integration. I create `feature/redux` branch only as slightly unopinionated version against `react-intl` ( and opinionated against `master`..  :-D )

**Comment by mantap123** [comment]
Hi!

when i want to merge **feature/redux** branch to master, it is conflict... It is the comparison:
https://github.com/kriasoft/react-starter-kit/compare/feature/redux...master

I have try to solve the merge conflict by myself, but it seems not perfect. I will try to do manual step first.

**Comment by tomawilkinson** [comment]
I am also a react-starter-kit / redux beginner.

I have merged the redux feature into master.

When I run the server I get the following in the console:
SET_RUNTIME_VARIABLE: { name: 'initialNow', value: 1480609977766 }

Which I assume means the store / redux is actually working (on runtime).

I've now followed the integration tutorial:
- I have created a constant, action, reducer and then combined them.

All I want to do is quite simple.
I want to update an array from the home route that will dispatch globally and then I want to display this array in a list format from the home route and the contact route but no where else.

When I try and access the "Store" from the home route to dispatch I just get "Store undefined".

Is there something basic Im missing on integrating redux where I can simply update the reducer / store and then pull in that data accordingly when needed?

Should I be importing a file on the home route?

Any clues would be much appreciated. My guess is this is a really simple workflow issue.

**Comment by AntonyKwok** [comment]
@mantap123 You experienced a git merge conflict, which means that both branches have made modifications to the same code. All you can do in this case is to decide on a case-by-case basis which version to keep (HEAD or master). From your screenshots it looks like you've made the right decision of updating the feature/redux code with the latest commits on the master branch, congrats!

---

@tomawilkinson I don't believe the SET_RUNTIME_VARIABLE console log does anything relevant, it's just a placeholder action/reducer pair that comes with React Starter Kit and in my opinion can be safely removed.

To access the store from any component, you need to bind your root app to Redux via a `Provider` from the `react-redux`.

In both `server.js` and `client.js`:
1. `import { Provider } from 'react-redux';`
2. Wrap your `<App context={context}>{route.component}</App>` instances like so:
```
<Provider store={store}>
  <App context={context}>
      {route.component}
  </App>
</Provider>,
```

Then in the component where you need to access the store:
1. `import { connect } from 'react-redux';`
2. `export default connect()(YourElement);

You can also use `connect()`'s two parameters to pass `mapStateToProps` and `mapDispatchToProps` as arguments like so:
```
const mapStateToProps = (state) => ({
  todos: state.todos,
});

const mapDispatchToProps = (dispatch) => ({
  addTodo: (id, text) => dispatch(addTodo(id, text)),
});

export default connect(mapStateToProps, mapDispatchToProps)(YourElement);
```

More information here: https://github.com/reactjs/react-redux/blob/master/docs/api.md

**Comment by sashakru** [comment]
Hey,

just started to use `feature/react-intl` and I'm little bit confused why there is no use of `react-redux` `Provider`, instead of `Provider` you do something like this in `App` component:

```
componentDidMount() {
    const store = this.props.context && this.props.context.store;
    if (store) {
      this.unsubscribe = store.subscribe(() => {
        const state = store.getState();
        console.log('state',state)
        const newIntl = state.intl;
        if (this.intl !== newIntl) {
          this.intl = newIntl;
          console.log('Intl changed'); // eslint-disable-line no-console
          this.forceUpdate();
        }
      });
    }
  }
```

What is the pros and cons in that implementation?

**Comment by langpavel** [comment]
Hi @sashakru 

Reason why it isn't used in `App` component is because `App` is only root component and because of this `App` have no access to parent context however it needs access to store for `IntlProvider`. 

In fact `App` do exactly what `Provider` does (`getChildContext()`) plus one extra thing – `App` will rerender with force when locale changes.

**Comment by Andriy-Kulak** [comment]
@AntonyKwok Thanks for the note. I was able to get the connect running quickly with your comment.

Why would you add the Provider to server.js though? Seems like Provider only needs to be provided in client.js

**Comment by AntonyKwok** [comment]
@Andriy-Kulak I added the Provider component by mistake. Redux is already hooked up to RSK via context.
