### ISSUE TITLE
Image path using variable

### ISSUE THREAD

**Issue by phoenix377** [kriasoft/react-starter-kit#943]
I need to display a image using variable.
What I can find is just displaying a image using static path by require, but what should I do if the path is variable?

**Comment by frenzzy** [comment]
Maybe [webpack's dynamic require](https://webpack.github.io/docs/context.html) can help you:
```js
const icon = 'icon-name';
require(`./icons/${icon}.svg`);
```
Be careful using dynamic require because all content of the folder may be bundled to your `main.js` in this case even if you use only few resources from the folder.

**Comment by antonlav** [comment]
Hi @frenzzy, it works.
Thank you for your help.

**Comment by phoenix377** [comment]
Hi @frenzzy, it works.
Thank you for your help.
