### ISSUE TITLE
Problem with integrating socket.io

### ISSUE THREAD

**Issue by j-rooks** [kriasoft/react-starter-kit#944]
Here is the code (stripped out to remove unrelated parts, it is a very simple component so not much change in the full code) where I try using socket.io on the client side:

```
...
import io from 'socket.io-client';
...

```
```
function MyComponent() {
  return (
...
        <a href="#" onClick={(e) => {
              e.preventDefault();
              const socket = io.connect(); // This is the line that produces the error
              ...
            }
          }>Click!</a>
...
  );
}
```

On the server side, this is the code I have to integrate socket.io:
```
//
// Launch the server
// -----------------------------------------------------------------------------
let server;
/* eslint-disable no-console */
models.sync().catch(err => console.error(err.stack)).then(() => {
  server = app.listen(port, () => {
    console.log(`The server is running at http://localhost:${port}/`);
  });
});
/* eslint-enable no-console */
const io = require('socket.io').listen(server);
```

I have installed all expected dependencies with the npm install commands. The issue I have is that when I click on my `<a>` button, I get this error in the browser console:

**GET http://localhost:3001/socket.io/?EIO=3&transport=polling&t=LWS5dKT 404 (Not Found)**
**polling-xhr.js:254**

After spending hours trying to resolve it, the problem seems to be related to BrowserSync, but running npm run build then node build/server.js to run without BrowserSync didn't solve the issue.
How can socket.io be integrated with this starter kit?

-Additional info: I am using the react-intl integration in case it matters (doubt it's related)

Thank you

**Comment by dhamaniasad** [comment]
@adjnor Did you manage to solve this?

**Comment by adjnor** [comment]
@dhamaniasad Unfortunately no. I ended up using react-boilerplate, which I would recommend taking a look at, it's been working great for me!

**Comment by langpavel** [comment]
@adjnor @dhamaniasad 
Did you consider there is browsersync in the development? Is socket properly proxied? I thing there can be issue.
You can try connect WS directly to your app at posrt 3000 (instead of through browsersync at 3001)

**Comment by ulani** [comment]
@j-rooks   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
