### ISSUE TITLE
Different view for mobile

### ISSUE THREAD

**Issue by phoenix377** [kriasoft/react-starter-kit#948]
I need to render different view on desktop and mobile.
I'm working on feature/redux branch.
How should I implement this functionality?

**Comment by buildbreakdo** [comment]
This is more of a general web development question more so than, something particular to react-starter-kit. 

See here: http://stackoverflow.com/questions/5981730/how-do-i-detect-mobile-clients-on-my-web-server

**Comment by phoenix377** [comment]
I stored running platform information (if it's on mobile or on desktop) in store and rendered different views according to it.
