### ISSUE TITLE
add lazy loading and progress bar

### ISSUE THREAD

**Issue by gauravprwl14** [kriasoft/react-starter-kit#949]
hey, i want to add lazy loading and progress bar at the top the page whenever a page is loaded.
i tried nprogress library but it always generate "document not define " error.

can you suggest some library which can be used to in this boilerplate to show loading indicator when a page is loaded

**Comment by frenzzy** [comment]
See lazy load (code splitting) example inside admin route: [src/routes/admin/index.js](https://github.com/kriasoft/react-starter-kit/blob/db08f54fb907b047d6ed163419fd00a60a456582/src/routes/admin/index.js#L24-L26), ref #901

To indicate page loading process just add any spinner (loader) component to your html and [show it at line 128 and hide at line 150](https://github.com/kriasoft/react-starter-kit/blob/db08f54fb907b047d6ed163419fd00a60a456582/src/client.js#L128-L150).

**Comment by langpavel** [comment]
For redux use https://github.com/mironov/react-redux-loading-bar.

In case of mounting after server rendering just dispatch `showLoading` on server before rendering and then dispatch `hideLoading` on client (after your initial render finish) (See [usage without middleware](https://github.com/mironov/react-redux-loading-bar#usage-without-middleware))

**Comment by gauravprwl14** [comment]
it is working. Thanks for the help

**Comment by Shadowman4205** [comment]
@langpavel  I tried this suggested loading bar. But i get error 

> Invariant Violation: Could not find "store" in either the context or props of "Connect(LoadingBar)". Either wrap the root component in a , or explicitly pass "store" as a prop to "Connect(LoadingBar)".

when i put it on Html component? when i put on another component itis working well. Why this happen?

**Comment by langpavel** [comment]
@Shadowman4205 Html component is rendered statically so your injection to `context` here is without effect.
You must use redux for this component and you must have redux injected, this is done in App component on all feature branches
