### ISSUE TITLE
Multiple webpack entry points not possible anymore

### ISSUE THREAD

**Issue by mxmtsk** [kriasoft/react-starter-kit#953]
I updated my project with the latest changes from react starter kit and [this](https://github.com/kriasoft/react-starter-kit/commit/2f7d127894fd547700a784c57f83af276b3e24bd#diff-3c56a79867d9b41d5950b61c8523f078) commit by @frenzzy  changed _tools/start.js_ line 36/34 from

```Javascript
config.entry = ['webpack-hot-middleware/client'].concat(config.entry);
```

to 

```Javascript
config.entry = ['react-hot-loader/patch', 'webpack-hot-middleware/client', config.entry];
```

Replacing .concat removes the possibility to have multiple entry points in _tools/webpack.config.js_

Was there any specific reasons to change it?

**Comment by frenzzy** [comment]
If you change entry points, you also should change this line.

For example different entry points can be specified like so:
```js
entry: {
  main: './client.js',
  home: './routes/home.js',
  about: './routes/about.js'
}
```
And maybe hot reload needed only for one of them or for all, who knows?

**Comment by mxmtsk** [comment]
Alright, thanks for the explanation! I was using _entry: ['my-module', './client.js']_

**Comment by frenzzy** [comment]
Just curious, why you do not want to import your module directly inside `client.js`?

**Comment by mxmtsk** [comment]
I can't answer detailed as I'm still fairly new in the React World but I used https://github.com/shakacode/bootstrap-loader and their explanation on how to integrate it

**Comment by tamerelsayed** [comment]
I'm having the same issue to import bootstrap-loader along with client.js entry in webpack.config.js

**Comment by mxmtsk** [comment]
@tamerelsayed what issue? I have bootstrap-loader integrated successfully
