### ISSUE TITLE
WithStyle decorator does not exist anymore

### ISSUE THREAD

**Issue by marekszala** [kriasoft/react-starter-kit#957]
Hi,

I am going to use Isomorphic-style-loader loader. @WithStyle generator looks more elegant than the current withStyle function approach.
I see that the previous versions of react-starter-kit also used decorators. 

Is there any reason why the decorator's approach was abandoned?

**Comment by koistya** [comment]
@marekszala Decorators are disabled in Babel v6, pending a proposal update – see babel/babel#2645. After this proposal is finalized we will bring decorator back.
