### ISSUE TITLE
Page load delayed styling and positioning

### ISSUE THREAD

**Issue by brandon-arnold** [kriasoft/react-starter-kit#958]
I don't really know where to start on this. I didn't get a response from @koistya on Gitter about it.

When the page loads, there are 1-5 seconds where elements are stacked weird. It depends on the framework, but it happened with React-Bootstrap and React-Slick. You can see it now on my website with my carousels using React-Slick; navigate to [brandonarnold.com](https://www.brandonarnold.com).

The only reason I post this here as well as React-Slick is that I have seen it with RSK before--it is clearly a delay in the styles getting related to the DOM content. I'm not getting any error messages on the client that would indicate it is re-rendering the DOM, however.

Im importing from the React-Slick CDN; it doesn't matter if I do it as below or in <link> tags in the HTML.

```css
@import 'https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css';
@import 'https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css';
```

At this time the file is loaded into my JSX using the withStyles from isomorphic-style-loader. Any suggestions on where I should go with this?

-Brandon

**Comment by frenzzy** [comment]
My browser loads 16 fonts (~500kb) when I come to your site. Are you sure that you need all of them? First of all, your website looks weird during loading fonts. If the download time over a certain timeout, the browser starts to display the page without fonts and when the next font is ready the browser redraws the page again. Possible optimizations:

1. Decrease amount of fonts (1-3 fonts or variations would be good)
2. Minimize font size, remove unused glyphs from the font (use google to find one of online font optimizer)
3. Inline font files in css ([file-loader technic](https://github.com/kriasoft/react-starter-kit/blob/39dfad685c6e8cf221ece74ab7df71412efad291/tools/webpack.config.js#L122))
4. Reuse server-side generated styles on frontend, replacing styles with fonts is a heavy operation (it would be nice to add this feature to RSK)

**Comment by brandon-arnold** [comment]
@frenzzy: Thanks, I know I need to cut the fonts down; I'm using 3. I will do that. It occurred to me that the CDN is probably the culprit here. I'm trying to get the CSS to get rendered into my content now, but I'm having the issue with .gif/.eot files not being available int he CSS node_module paths, so I'm having to copy the libs over manually and fix that stuff. Thanks, will update with changes shortly.

**Comment by brandon-arnold** [comment]
I'm pretty sure it's because the CSS is being downloaded on page load instead of being rendered inline by Webpack. So far I have been able to copy the above CSS files into my project but have been unsuccessful in getting them to be downloaded before the other content.

**Comment by brandon-arnold** [comment]
Nope. It didn't fix anything to remove ALL fonts and to have the slick.css and slick-theme.css files copied in plain <style> tags (set with dangerouslySetInnerHtml...). Thus it has nothing to do with file download times.

**Comment by Ank49** [comment]
I'm having this issue too.. I load my bootstrap style in the Html.js file but my own styles (as the main) is supposed to be loaded in the Layout but when I start the server, It doesn't… As soon as I make an edit inside it, Webpack reloads with the style. Anyone had it fixed ?

**Comment by ulani** [comment]
@brandon-arnold   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
