### ISSUE TITLE
Can you add a console.log to the DevTools out of the box?

### ISSUE THREAD

**Issue by ottomen** [kriasoft/react-starter-kit#962]
Default kit package is consoling into the command prompt. It's not convenient.
Thanks!

**Comment by ottomen** [comment]
Besides this I'm confused, cause componentDidMount(), onClick and other events are not firing my ordinary console.log() to the nodejs command prompt even.

**Comment by langpavel** [comment]
@ottomen *`componentDidMount()`, `onClick` and other events* will not fire on node console because there is no way how they can be invoked. Only `componentWillMount()` will fire inside node environment.

All lifecycle methods can log to console inside browser.

**Comment by langpavel** [comment]
> Default kit package is consoling into the command prompt. It's not convenient.

Don't know what you mean by this

**Comment by ottomen** [comment]
I figured out this thing.
I kinda modified the html.js vs app.js files, and when I downloaded kit once more later, all console.logs worked properly.
So it's just my dummy misunderstoods of this nontrivial kit.

I apologize, guys.

**Comment by ottomen** [comment]
I deleted {script && <script src={script} />} from HTML.js, so the consoles were going to the Node.js command prompt. When I renewed it, everything became as it should.

**Comment by langpavel** [comment]
Ok @ottomen, can you close this? :slightly_smiling_face:

**Comment by ottomen** [comment]
Of course I will.
