### ISSUE TITLE
After run npm start commend  ERROR:Failed to load the news feed.

### ISSUE THREAD

**Issue by Jeff-Kook** [kriasoft/react-starter-kit#966]
Error: Failed to load the news feed.

  - index.js:32 Object._callee$
    D:/[...]/MyApp/build/webpack:/routes/home/index.js
    :32:36

  - runtime.js:63 tryCatch
    [MyApp]/[regenerator-runtime]/runtime.js:63:40

  - runtime.js:337 Generator.invoke [as _invoke]
    [MyApp]/[regenerator-runtime]/runtime.js:337:22

  - runtime.js:96 Generator.prototype.(anonymous function) [as next]
    [MyApp]/[regenerator-runtime]/runtime.js:96:21

  - asyncToGenerator.js:17 step
    [MyApp]/[babel-runtime]/helpers/asyncToGenerator.js:17:30

  - asyncToGenerator.js:28
    [MyApp]/[babel-runtime]/helpers/asyncToGenerator.js:28:13

I'm git the project as the guide say.When I npm start,the error is coming up.
Is there someone meet this error?What's wrong?

**Comment by koistya** [comment]
It's trying to load the news feed for the home page from the following URL:

https://github.com/kriasoft/react-starter-kit/blob/4495f49/src/data/queries/news.js#L15-L16

If you need to make the app work in off-line mode, you may want to edit `src/routes/home/index.js` and disable news feed fetching. Does it solve it for you?

**Comment by Jeff-Kook** [comment]
You're right.Thank you so much.
My computer unable to access Google web site cause I'm in China.

**Comment by FairyRoc** [comment]
I came into the same problem...and I get it solved by following your steps,it's great!
