### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by Rushmead** [kriasoft/react-starter-kit#967]
Heres the error i get.
```
npm ERR! peerinvalid The package eslint@2.13.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@6.2.0 wants eslint@^2.4.0
npm ERR! peerinvalid Peer babel-eslint@5.0.4 wants eslint@<2.3.0 npm ERR! peerinvalid Peer eslint-loader@1.6.1 wants eslint@>=1.6.0 <4.0.0
```

**Comment by RustinAlexandru** [comment]
Same

**Comment by paul-gtv** [comment]
Same
npm ERR! peerinvalid The package eslint does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@6.2.0 wants eslint@^2.4.0
npm ERR! peerinvalid Peer babel-eslint@5.0.4 wants eslint@<2.3.0
npm ERR! peerinvalid Peer eslint-loader@1.6.3 wants eslint@>=1.6.0 <4.0.0

**Comment by langpavel** [comment]
Don't bother. If all compile and works. Moreover this is dev dependency.
