### ISSUE TITLE
Cannot use Sequelize - Error: Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by archansel** [kriasoft/react-starter-kit#968]
Hi, I'm trying to use my Sequelize model in routes but I got a lot of warnings and errors

    WARNING in ./~/sequelize/lib/sequelize.js
    Critical dependencies:
    686:60-73 the request of a dependency is an expression
     @ ./~/sequelize/lib/sequelize.js 686:60-73

    WARNING in ./~/sequelize/lib/dialects/mssql/connection-manager.js
    Critical dependencies:
    18:15-71 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/mssql/connection-manager.js 18:15-71

    WARNING in ./~/sequelize/lib/dialects/mysql/connection-manager.js
    Critical dependencies:
    18:17-60 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/mysql/connection-manager.js 18:17-60

    WARNING in ./~/sequelize/lib/dialects/postgres/connection-manager.js
    Critical dependencies:
    20:14-57 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/postgres/connection-manager.js 20:14-57

    WARNING in ./~/sequelize/lib/dialects/sqlite/connection-manager.js
    Critical dependencies:
    22:15-71 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/sqlite/connection-manager.js 22:15-71

    WARNING in ./~/sequelize/lib/dialects/postgres/connection-manager.js
    Module not found: Error: Cannot resolve module 'pg' in D:\Work\Startup\Goers\Repositories\Website\node_modules\sequelize\lib\dialects\postgres
     @ ./~/sequelize/lib/dialects/postgres/connection-manager.js 22:14-27

    ERROR in ./~/sequelize/lib/dialects/postgres/hstore.js
    Module not found: Error: Cannot resolve module 'pg-hstore' in D:\Work\Startup\Goers\Repositories\Website\node_modules\sequelize\lib\dialects\postgres
     @ ./~/sequelize/lib/dialects/postgres/hstore.js 3:13-33

    ERROR in ./~/mysql/lib/Connection.js
    Module not found: Error: Cannot resolve module 'net' in D:\Work\Startup\Goers\Repositories\Website\node_modules\mysql\lib
     @ ./~/mysql/lib/Connection.js 3:23-37

    ERROR in ./~/mysql/lib/Connection.js
    Module not found: Error: Cannot resolve module 'tls' in D:\Work\Startup\Goers\Repositories\Website\node_modules\mysql\lib
     @ ./~/mysql/lib/Connection.js 4:23-37

    ERROR in ./~/mysql/lib/protocol/sequences/Query.js
    Module not found: Error: Cannot resolve module 'fs' in D:\Work\Startup\Goers\Repositories\Website\node_modules\mysql\lib\protocol\sequences
     @ ./~/mysql/lib/protocol/sequences/Query.js 6:19-32

How do I solve this problem? I already tried adding 

    fs: 'empty',
    net: 'empty',
    tls: 'empty'

in webpack.config.js but no result

**Comment by ottomen** [comment]
I do have this issue now

**Comment by frenzzy** [comment]
Duplicate of #976
