### ISSUE TITLE
Query example accessing a db table (react-starter-kit/src/data/queries)

### ISSUE THREAD

**Issue by buildbreakdo** [kriasoft/react-starter-kit#969]
Would like to see an example where a database value is queried and injected into the page. Current understanding is that this project does not have an example like this.

We have fetch examples hitting an external API (google feeds) but nothing leveraging the generated sqlite3 db, would also mean we need a seed script which seems like a reasonable addition to the data folder.

Have spent a few days trying to figure out how to make a query to the sqlite3 db (to no avail) after setting up some seed values. Simple example would go a long way in helping.

**Comment by koistya** [comment]
The idea is to provide database client utility as a context variable to the GraphQL middleware:

```js
// server.js
app.use('/graphql', graphQLMiddleware(req => ({
  schema: require('./schema').default,
  context: {
    user: req.user,
    db: new Database(config.db.connection),
  },
}));
```

...then inside the resolver functions in your GraphQL types you would use that db client as follows:

```js
export default new GraphQLObject({
  name: 'Comment',
  fields: {
     ...
  },
  resolve(parent, arts, { db }) {
    return db.loadCommentById(parent.id);
  },
});
```

**Comment by koistya** [comment]
@buildbreakdo it's essential to understand how to use batching and caching when fetching data inside the resolver functions, it's a very simple pattern that's based on Node.js `process.nextTick(..)` and promises. Here is an example library implementing that pattern:

https://github.com/facebook/dataloader

**Comment by ulani** [comment]
@buildbreakdo   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
