### ISSUE TITLE
The gh-pages needs a facelift

### ISSUE THREAD

**Issue by emilkje** [kriasoft/react-starter-kit#97]
I don't think the demo page provides justice to the starter kits beauty.

**Comment by koistya** [comment]
Yep, indeed.

**Comment by koistya** [comment]
@emilkje done. Just need help with the content. Take a look: [www.reactstarterkit.com](http://www.reactstarterkit.com)

**Comment by koistya** [comment]
Just have updated the project template's default style as well in the following commit: c92ea26d9ff9f377335aad5c9acad320dda32a51

**Comment by emilkje** [comment]
Nice! The new design has improved the impression by orders of magnitude! Great job @koistya
