### ISSUE TITLE
[Opinion] Component's package.json?

### ISSUE THREAD

**Issue by blackxored** [kriasoft/react-starter-kit#971]
Why a `package.json` under components?
I'm coming new to this after seeing a ton of React projects, this is the first time I encounter this approach, and IMHO it's counterintuitive. I took a look at the file thinking this was some weird black magic to make components exportable (maybe Lerna/monorepo related or something) until I read what was about. 
I'd prefer a rename of the actual component to index.js to achieve the same effect. Granted, this breaks the naming convention for that particular file, but it's less counter-intuitive and more common.

**Comment by buildbreakdo** [comment]
@blackxored Sounds good in theory but in practice would be horrible. Think about all of your component files open in your IDE, all the files at the top of your screen would say index.js.. which one do you click on? Which one is the one you want? 

Other reasons aside, would be a terrible developer experience.

**Comment by blackxored** [comment]
That’s a good point. How about index.js requiring Component.js?

— 
Best Regards,

Adrian Perez
https://adrianperez.codes


On November 18, 2016 at 1:06:46 PM, Joshua Robinson (notifications@github.com) wrote:

@blackxored Sounds good in theory but in practice would be horrible. Think about all of your component files open in your IDE, all the files at the top of your screen would say index.js.. which one do you click on? Which one is the one you want?

Other reasons aside, would be a terrible developer experience.

**Comment by koistya** [comment]
> How about index.js requiring Component.js?

That's better. But comes to a personal preference. One of the nice pros with `pacakge.json` file is that you can always CTR+click on `import MyComponent from '../MyComponent'` in your editor or IDE and navigate straight to the `MyComponent.js` file, but in the case with `index.js` the editor will open it instead.

**Comment by buildbreakdo** [comment]
@blackxored How is that different from the package.json setup? Know it is different behind the scenes, import build step versus a file reference entry point, however in essence this is doing them same thing. If I opened a folder and saw:

Component/
Component.js
Index.js

To be honest, I would be confused as to which to click. Which one has logic? Both being JavaScript, they technically both could.

With a package.json file, I know not to click on that if I want to edit the component. That is not obvious with a index.js requiring Component.js scenario. 

Added bonus, having a package.json allows you to publish if you decided to externalize and share component on an internal or external npm server.

**Comment by koistya** [comment]
@buildbreakdo good point.

**Comment by dolbyzerr** [comment]
@buildbreakdo You can hack you IDE nowadays ;) I am using atom with https://atom.io/packages/rename-tabs plugin.

But creating meaningless `package.json` files each time you need to create a component - that's what I call terrible developer experience.

**Comment by langpavel** [comment]
@dolbyzerr You can easily hack scaffold too ;-)

**Comment by ulani** [comment]
@blackxored   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
