### ISSUE TITLE
backgroundImage in inline style

### ISSUE THREAD

**Issue by phoenix377** [kriasoft/react-starter-kit#979]
I need to specify dynamic background image for div.
So it looks like this.
"<div style={{backgroundImage: `url(../../public/${imgName})`}} />"
But when I run it with npm start, it converted into absolute url - http://localhost:3000/public/test.png, and it can't load the image.
Is there anyway I can solve this issue?

**Comment by frenzzy** [comment]
```js
function bgImage(props) {
  const imageUrl = require(`./images/${props.imageName}.jpg`)
  return <div style={{ backgroundImage: `url(${imageUrl})` }} />
}
```
