### ISSUE TITLE
both SSR and client side react

### ISSUE THREAD

**Issue by fatal10110** [kriasoft/react-starter-kit#984]
As I understand there is an option to use this kit to build an app that may be rendered on server side  or as regular react components ( for example use SSR for search bots and CSR for regular users).
But there is no examples or explanations how to do it, can someone add this examples please ? tnx.

CSR worked for me when I did it like it's done here: https://github.com/kriasoft/react-starter-kit/pull/833/files

**Comment by sauravskumar** [comment]
+1

**Comment by IDrinkMoreWater** [comment]
+1

**Comment by frenzzy** [comment]
The main idea of react-starter-kit is providing the base for [Isomorphic JavaScript Web Application](http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/).

This means that each component here is to be rendered on both the server-side (for crawlers, SEO, etc) and the client-side (for browser, visitors), it works out of the box and you do not need to configure anything extra, just add your own components.

If you don't need SSR (Server-Side Rendering), you probably don't need any starter kit because it is easy to start from scratch, or you can look at [react-static-boilerplate](https://github.com/kriasoft/react-static-boilerplate) or any others.

**Comment by fatal10110** [comment]
ok, you just repeated the readme, but by default you are using SSR, how to switch it to CSR on some cases, i need the SSR but only for crawlers.

as I understand i can take the js file (the bundle) from build directory and create and use it for CSR by requiring it using script tag, but then I need to provide some initial state, something like that:

```
<!doctype html>
<html class="no-js">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="apple-touch-icon" href="apple-touch-icon.png" />
</head>

<body>
    <script id="__bs_script__">
        //<![CDATA[
        document.write("<script async src='/browser-sync/browser-sync-client.js?v=2.18.1'><\/script>".replace("HOST", location.hostname));
        //]]>
    </script>
    <div id="app"></div>
    <script>
        window.APP_STATE = {
            "user": null,
            "runtime": {
                "initialNow": 1479674949659,
                "availableLocales": ["en-US", "cs-CZ"]
            },
            "intl": {
                "initialNow": 1479674949659
            }
        }
    </script>
    <script src="/assets/client.js?7bf71af8f91c4dad3aad"></script>
</body>

</html>
```

**Comment by bbarrows** [comment]
I know this is old but I ran into similar issues.

To solve the setting of initial state I just made my (custom) client entry point dispatch a few actions like:


    store.dispatch(setRuntimeVariable({
      name: 'initialNow',
      value: Date.now(),
    }));

    store.dispatch(setRuntimeVariable({
      name: 'currentPathname',
      value: '/' //req.path,
    }));

    store.dispatch(setRuntimeVariable({
      name: 'appIsMounted',
      value: false,
    }));

    store.dispatch(setRuntimeVariable({
      name: 'availableLocales',
      value: conf.locales
    }));

    store.dispatch({
      type: SET_LOCALE_SUCCESS,
      payload: {
        locale: 'en-US',
      }
    });

I am sure that is not the best way but may help.

I also posted a quick ex about loading the locales without GraphQL in another issue:
https://github.com/kriasoft/react-starter-kit/issues/911

**Comment by langpavel** [comment]
Hi there

@fatal10110, sorry, may be too late, but:
You really don't want disable SSR. You can write your API in different framework or language, but you really don't want wasting time with redirecting request forth and back through different app. There are exceptions like slowly migrating one app from legacy dev stack to new one but I cannot imagine how hard will be maintaining this craziness.

@bbarrows Intl fetching is still a little special, but is all done in Redux. And this is good path.
You can render app on server thanks to redux. This is most isomorphic and simple way you can do this.
Of course, you can load your dictionaries by different way, you can (now) switch to Apollo and you got caching for free, but payload will be same.

`store.dispatch(setRuntimeVariable({...})` is only example, nothing more.

`store.dispatch({ type: SET_LOCALE_SUCCESS, ...})` is practical use case how to dispatch action on server. Same action is dispatched on client.

And do you know how expensive are both dispatches? It cost almost nothing! So enjoy them as a way how to preload data :smiley:

**Comment by bbarrows** [comment]
For my current task for my job I was stuck with a pre existing code base
and asked to make an Electron app. Doing server side rendering in an
Electron app sounded and looked like a horrible idea to me personally but
maybe it's not so bad?

I was just trying to provide some rough example alternatives if someone
gets stuck in a situation like mine. This starter kit is not what I would
want to use for an Electron app personally, I would have started with
something more minimal.

I will look into Apollo though. Sounds really interesting, thank you!

**Comment by ulani** [comment]
@fatal10110   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
