### ISSUE TITLE
Problems with gulp

### ISSUE THREAD

**Issue by neilyoung** [kriasoft/react-starter-kit#99]
Hi,

fresh install. Getting 

module.js:338
    throw err;
          ^
Error: Cannot find module 'end-of-stream'

for "gulp build"

**Comment by wuichen** [comment]
having the same issue

**Comment by koistya** [comment]
Do you have gulp installed globally? (`npm install gulp -g` or `npm update gulp -g`)

To see a list of installed packages:

```
$ npm ls --depth=0               # or, `npm ls -g --depth=0` for global npm modules
```

**Comment by neilyoung** [comment]
Hmm. Yes, I did. Repeated it right now. As you can see, it is not in the list after installation

decades:cvpos decades$ npm install gulp -g
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
gulp@3.8.11 /usr/local/lib/node_modules/gulp
├── pretty-hrtime@0.2.2
├── interpret@0.3.10
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.1
├── tildify@1.0.0 (user-home@1.1.1)
├── v8flags@2.0.5 (user-home@1.1.1)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── semver@4.3.3
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, vinyl@0.4.6, chalk@1.0.0, lodash.template@3.5.1, through2@0.6.5, multipipe@0.1.2, dateformat@1.0.11)
├── liftoff@2.0.3 (extend@2.0.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.6, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.0, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)


decades:cvpos decades$ npm ls --depth=0 
/Users/decades
├── api-easy@0.3.6
├── azure-cli@0.7.4
├── browserify@9.0.8
├── classnames@1.2.2
├── frisby@0.8.5
├── grunt-hub@0.7.0
├── markdown-pdf@3.1.0
├── noble@0.2.7
├── react@0.13.2
├── react-bootstrap@0.21.0
├── react-router@0.13.3
├── reactify@1.1.0
├── request@2.9.203
├── should@0.6.3
├── uglify-js@2.4.20
├── vows@0.6.3
└── watchify@3.1.2

**Comment by VenelinPetkov** [comment]
I have a problem with gulp as well (gulp-webpack problem I guess):

[12:48:38] Using gulpfile .../react-starter-kit/gulpfile.js
[12:48:38] Starting 'build:watch'...
[12:48:38] Starting 'clean'...
[12:48:38] Finished 'clean' after 12 ms
[12:48:38] Starting 'build'...
[12:48:38] Starting 'vendor'...
[12:48:38] Starting 'assets'...
[12:48:38] Starting 'bundle'...
../react-starter-kit/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:206
					throw e;
					      ^
Error: Cannot find module 'to-fast-properties'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../react-starter-kit/node_modules/babel-core/lib/babel/types/index.js:81:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Any suggestions?

**Comment by koistya** [comment]
It seems like `webpack` wasn't properly installed. Maybe you can try reinstall it and see if there are any errors?

```shell
$ npm uninstall webpack
$ npm install
```

**Comment by ichbinedgar** [comment]
Hello,
I'm getting a similar error:

```
npm start

> @ start /opt/lampp/htdocs/books2
> babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"

module.js:338
    throw err;
          ^
Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/lampp/htdocs/books2/tools/start.js:20:20)
    at Module._compile (module.js:460:26)
    at normalLoader (/opt/lampp/htdocs/books2/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/lampp/htdocs/books2/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Linux 3.0.76-0.11-default
npm ERR! argv "/home/moreed3/bin/node" "/home/moreed3/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/lampp/htdocs/books2/npm-debug.log
```

This is happening on Linux server, but the same  fresh install is working on my Windows 7 machine. Do you know if I missing something?

**Comment by davidmdem** [comment]
In regards to the comment from @ichbinedgar - I too got an `Cannot find module 'browser-sync'` error.

In a Windows 10 environment I tried `npm install browser-sync` from a regular command prompt and it failed with an error code from node-gyp.  However, starting a new prompt with Administrative privileges worked.

**Comment by koistya** [comment]
`gulp` dependency was removed from this project in favor JavaScript-based automation scripts. See [You might not need Gulp.js](https://medium.com/swlh/you-might-not-need-gulp-js-89a0220487dd#.wq5chpsoc) blog post and `tools` folder.
