### ISSUE TITLE
Keep state in redirection

### ISSUE THREAD

**Issue by phoenix377** [kriasoft/react-starter-kit#995]
I need to save store when it is redirected.
I see this project use universal-router.
How should I implement this?

**Comment by frenzzy** [comment]
Which type of state? There is many ways how you can traverse the state further, for example via url query params, flux/redux/relay store or browser history api.

**Comment by phoenix377** [comment]
@frenzzy, thank you for your quick reply.
I want to redirect from index.js of route. It looks like this.

export default {
  path: /join',
  action({ store, params }) {
    ...
    store.dispatch(...);
    return { redirect: `/question` };
  },
};

Here what I want to is to use same store value in /question route. I see that by doing this, in /question route, the store is initialized again.
And store has many data, so sending it through url params is not appropriate I think.
Is there any other method?

**Comment by frenzzy** [comment]
To prevent reinitialization of store you should create it once inside `client.js` and just pass through router to your action methods. All your routes will have access to the same store instance in this case and you will be able to share any state between routes.

Here is an example: #883, plus this in `client.js`:
```js
// ...
const route = await UniversalRouter.resolve(routes, {
  // ...
  store: context.store,
});
// ...
```

**Comment by phoenix377** [comment]
@frenzzy, I'm also using react-intl branch and in my client.js, route is created like below.
const route = await UniversalRouter.resolve(routes, {
      ...context,
...
}
But still I can't preserve my store when I redirect.

**Comment by kencckw** [comment]
I have the same problem. Please help.

**Comment by ulani** [comment]
@phoenix377   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
