### ISSUE TITLE
get html/js files only

### ISSUE THREAD

**Issue by bastiankhalil** [kriasoft/react-starter-kit#998]
I just wounder how I can have the application bundled without Node.js and server stuff. only the html/js files. Is there is anyway to have that? I want to deploy in my own server.

**Comment by frenzzy** [comment]
Build your application with [`npm run build -- --static --release`](https://github.com/kriasoft/react-starter-kit/tree/master/tools#options) command and you will get all production ready statics inside `build/public` folder.

See #642 for more info.

**Comment by atalebagha** [comment]
@frenzzy How about linking/routing between different static pages?  rather than routing to `/page/subpage` we now need to route to something like `/page/subPage.html`.  Can the router handle that?

**Comment by langpavel** [comment]
frenzzy is right, but you should look for different stack or **ask yourself why you want throw away server side rendering stuff**...
If you create public accessible site you want robots to index you.

**Comment by bastiankhalil** [comment]
solved.
